#
#
#
#
#
{0}{}{Preferencias de juego}
{1}{}{Configuracion de pantalla}

{50}{}{Configuracion de pantalla}
{51}{}{Personalización}
{52}{}{Anchura}
{53}{}{Altura}
{54}{}{Hecho}
{55}{}{Cancelar}
{56}{}{Fallout debe reiniciar para aplicar los ajustes.}
{57}{}{¿Desea reiniciar Fallout ahora?}
{58}{}{Si}
{59}{}{No}
{60}{}{}

{100}{}{Alta-resolución}
{101}{}{RESOLUCIÓN}
{102}{}{Colores}
{103}{}{8 Bits}
{104}{}{16 Bits}
{105}{}{32 Bits}
{106}{}{Cambiar el arte de la barra lateral}
{107}{}{Invertir lista}
{108}{}{Ventana}
{109}{}{Tecla de desplazamiento}
{110}{}{Escala X2}
{111}{}{Frecuencia de actualización}

{130}{}{Tecla de Windows}
{131}{}{Seleccionar}
{132}{}{Nombre}

{140}{}{Modo Grafico:}
{141}{}{Básico}
{142}{}{Modo Sfall DirectX 9:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Procesamiento de hardware de vértices:}
{149}{}{Shader versión 2.0:}

{150}{}{Panel Scaling}
{151}{}{Ninguno}
{152}{}{Ajustar}
{153}{}{Rellenar}

{154}{}{Peliculas}
{155}{}{Splash}
{156}{}{Ayuda}
{157}{}{Muerte}
{158}{}{End Slides}
{159}{}{Menu principal}

{200}{}{Sfall}
{201}{}{Escalar a: Resolución.}
{202}{}{Modo DX-9}
{203}{}{Apagado}
{204}{}{Pantalla completa}
{205}{}{Ventana}
{206}{}{GPU Blitting}
{207}{}{Esta configuración no tiene efecto en el modo de gráficos básicos.}

{250}{}{Ignorar el límite de desplazamiento de la PC}
{253}{}{Distancia Máxima de Trazado}
{254}{}{Normal}
{255}{}{Max}
{256}{}{Enable Fog Of War}
{257}{}{Fog Visibility}
{258}{}{Dark}
{259}{}{Brighter}

{300}{}{PRESS A KEY or ESC to cancel.}

{500}{}{Hi-Res Patch settings.}
{501}{}{Setup the Screen Resolution, Colour mode and Refresh Rate for FullScreen Mode.}
{502}{}{Setup the Fullscreen Colour output here.}
{503}{}{Setup the Fullscreen Refresh Rate here. Set this to '0' for the driver default setting.}
{504}{}{Customize the Fullscreen Width by clicking the number box.}
{505}{}{Customize the Fullscreen Height by clicking the number box.}
{506}{}{Activa o desactiva el Modo Ventana.}
{507}{}{In Window Mode, this is the key you will hold down when using the mouse to scroll the Game and World maps.}
{508}{}{Press the red button to select a different key. Or click the number box to edit the Windows Virtual key code.}
{509}{}{The name of the currently selected key.}
{510}{}{Enable X2 scaling. This will also up the min res to 1280x960. With Window mode requiring more space for its frame.}
{511}{}{Enable or Disable Fog Of War. For best results this should be enabled before entering a map for the first time.}
{512}{}{Adjust the light level and the Mouse 'look at' visibility of floors, walls and scenery under the fog.}
{513}{}{Floors, walls and scenery will always be visible and Mouse "look at" will function normally.}
{514}{}{Floors, walls and scenery will be darkened and unresponsive to Mouse "look at" until discovered.}
{515}{}{When enabled, scrolling away from the Player Character is unlimited. This works well if Fog Of War enabled.}
{516}{}{Increase the number of search nodes to extend the path finding distance. 20 levels in 2000 node increments.}
{517}{}{2000 path search nodes (original value). Note: Each level requires an additional 156.25 KB of memory.}
{518}{}{40 000 path search nodes. Note: requires 3200000 bytes (3125 KB) of memory.}
{519}{}{Adjust how certain screens are displayed.}
{520}{}{Original size.}
{521}{}{Stretched to fit the size of the screen while maintaining the original aspect ratio.}
{522}{}{Stretched to fill the screen. Note: A space will remain at the bottom of the screen if subtitles are enabled.}
{523}{}{Click below to cycle the in-game interface Side Bar options.}
{524}{}{Apply any changes and Exit.}
{525}{}{Salir sin guardar.}


