{100}{}{Cohete}
{200}{}{Bola de plasma}
{300}{}{Explosión}
{400}{}{Sangre}
{500}{}{Casilla impenetrable}
{600}{}{cuchillo}
{700}{}{lanza}
{800}{}{Explosión IEM}
{900}{}{Disparo Láser}
{1000}{}{Disparo de Plasma}
{1100}{}{Explosión}
{1200}{}{Scroll Blocker}
{1300}{}{Rayo eléctrico}
{1400}{}{Explosión}
{1500}{}{Explosión}
{1600}{}{Salida}
{1700}{}{Salida}
{1800}{}{Salida}
{1900}{}{Salida}
{2000}{}{Salida}
{2100}{}{Salida}
{2200}{}{Salida}
{2300}{}{Salida}
{2400}{}{Bengala}
{2500}{}{Granada}
{2600}{}{Piedra}
{2700}{}{Explosión}
{2800}{}{Explosión}
{2900}{}{Explosión}
{3000}{}{Cóctel Molotov}
{3100}{}{Salida}
{3200}{}{Salida}
{3300}{}{Salida}
{3400}{}{Salida}
{3500}{}{Salida}
{3600}{}{Salida}
{3700}{}{Salida}
{3800}{}{Salida}
{3900}{}{Salida}
{4000}{}{Salida}
{4100}{}{Salida}
{4200}{}{Salida}
{4300}{}{Salida}
{4400}{}{Salida}
{4500}{}{Salida}
{4600}{}{Salida}
{4700}{}{Cohete de Robot}
{4800}{}{Ka-Pow!}
{4900}{}{Pincho de plasma}
{5000}{}{Bola de plasma doble}
{5100}{}{Borde del mapa}
{5200}{}{Borde del mapa}
{5300}{}{Escupe de ácido}
{5400}{}{Corriente de aire}
