#
#
#
#
#
{0}{}{Spieloptionen}
{1}{}{Bildoptionen}

{50}{}{Bildoptionen}
{51}{}{Benutzerdefiniert}
{52}{}{Breite}
{53}{}{Höhe}
{54}{}{Ok}
{55}{}{Abbrechen}
{56}{}{Fallout muss neu gestartet werden.}
{57}{}{Möchten Sie nun Fallout neustarten?}
{58}{}{Ja}
{59}{}{Nein}
{60}{}{}

{100}{}{Hi-Res}
{101}{}{Auflösung}
{102}{}{Farbmodus}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Side-Bar ändern}
{107}{}{Auswahl umkehren}
{108}{}{Fenstermodus}
{109}{}{Scrolltaste ändern}
{110}{}{2-fache Skalierun}
{111}{}{Bildwiederholrate}

{130}{}{Windowstaste}
{131}{}{Auswählen}
{132}{}{Name}

{140}{}{Grafikmodus:}
{141}{}{Einfach}
{142}{}{Sfalls DX9-Modus:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader-Version 2.0:}

{150}{}{Screen-Darstellung}
{151}{}{Aus}
{152}{}{Ska.}
{153}{}{Str.}

{154}{}{Videos}
{155}{}{Start}
{156}{}{Hilfe}
{157}{}{Tod}
{158}{}{Ende}
{159}{}{Hauptmenü}

{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{DX9-Modus}
{203}{}{Aus}
{204}{}{Vollbild}
{205}{}{Fenster}
{206}{}{GPU-Blitting}
{207}{}{Diese Einstellung hat im einfachen Grafikmodus keinen Effekt.}

{250}{}{Scrolllimit ignorieren}
{253}{}{Pfadfindungsreichweite}
{254}{}{Normal}
{255}{}{Max}
{256}{}{Nebel des Krieges einschalten}
{257}{}{Nebelsichtbarkeit}
{258}{}{Dunkel}
{259}{}{Heller}

{300}{}{EINE TASTE DRÜCKEN oder ESC zum Abbrechen.}

{500}{}{Einstellungen für den Hi-Res-Patch.}
{501}{}{Ändern von Auflösung, Farbmodus und Bildwiederholrate im Vollbild.}
{502}{}{Farbmodus im Vollbild ändern.}
{503}{}{Ändert die Bildwiederholrate. Bei '0' wird die Treibereinstellung benutzt.}
{504}{}{Eigene Auflösung (Breite) eingeben.}
{505}{}{Eigene Auflösung (Höhe) eingeben.}
{506}{}{Fenstermodus ein- oder ausschalten.}
{507}{}{Halte diese Taste im Fenstermodus gedrückt, wenn du die Maus zum Scrollen der Spiel- und Weltkarte verwendest.}
{508}{}{Drücken den roten Button, um eine andere Taste auszuwählen, oder klicke aufs Zahlenfeld, um den Windows-Virtual-Key-Code zu ändern.}
{509}{}{Der Name der aktuell ausgewählten Taste.}
{510}{}{Skaliert die Originalauflösung auf 1280x960. Im Fenstermodus etwas größer.}
{511}{}{Nebel des Krieges ein- oder ausschalten. Funktioniert am besten, bevor man eine Map erstmals betritt.}
{512}{}{Stellt die Helligkeit und Sichtbarkeit von Böden, Wänden und Objekten unterm Nebel mit 'Du siehst' ein.}
{513}{}{Böden, Wände und Objekte sind immer sichtbar und 'Du siehst' funktioniert normal.}
{514}{}{Böden, Wände und Objekte sind verdunkelt und mit 'Du siehst' nicht sichtbar bis sie entdeckt sind.}
{515}{}{Scrollen wird nicht limitiert, wenn es eingeschaltet ist. Funktioniert auch, wenn Nebel des Krieges eingeschaltet ist.}
{516}{}{Erhöht die Reichweite der Pfadfindung. 20 Intervalle je 2000 Nodes möglich.}
{517}{}{2000 Nodes (Originalgröße). Jeder Intervall erhöht den Speicher um 156.25 KB.}
{518}{}{40.000 Nodes. Erfordert 3200000 Bytes (3125 KB) an Speicher.}
{519}{}{Einstellen wie die Screens dargestellt werden sollen.}
{520}{}{Originalgröße.}
{521}{}{Größtmögliche Skalierung der Screens, bei der das Seitenverhältnis beachtet wird.}
{522}{}{Screens werden auf die komplette Bildschirmgröße gestreckt. Etwas kleiner, wenn Untertitel an sind.}
{523}{}{Ins Feld klicken, um den Stil der Side-Bar zu ändern.}
{524}{}{Änderungen übernehmen und Beenden.}
{525}{}{Beenden ohne zu Speichern.}


