#include "..\headers\define.h"
#include ".\BookAsh.h"
//---------------------

#define NAME                            SCRIPT_BookUnar

#define BOOK_TYPE2
#define BOOK_PID                        PID_BOOK_UNAR
#define SKILL_1                         SKILL_UNARMED_COMBAT
#define POINT_1                         (4)
#define SKILL_2                         SKILL_MELEE
#define POINT_2                         (4)
#define READ_MSG                        (710)

//---------------------

#include ".\TempBook.h"
