#include "..\headers\define.h"
#include ".\BookAsh.h"
//---------------------

#define NAME                            SCRIPT_BookLock

#define BOOK_TYPE1
#define BOOK_PID                        PID_BOOK_LOCK
#define SKILL_1                         SKILL_LOCKPICK
#define POINT_1                         (4)
#define READ_MSG                        (711)

//---------------------

#include ".\TempBook.h"
