#include "..\headers\define.h"
#include ".\BookAsh.h"
//---------------------

#define NAME                            SCRIPT_BookScie

#define BOOK_TYPE1
#define BOOK_PID                        PID_BOOK_SCIE
#define SKILL_1                         SKILL_SCIENCE
#define POINT_1                         (4)
#define READ_MSG                        (703)

//---------------------

#include ".\TempBook.h"
