#include "..\headers\define.h"
#include ".\BookAsh.h"
//---------------------

#define NAME                            SCRIPT_BookMedi

#define BOOK_TYPE2
#define BOOK_PID                        PID_BOOK_MEDI
#define SKILL_1                         SKILL_FIRST_AID
#define POINT_1                         (4)
#define SKILL_2                         SKILL_DOCTOR
#define POINT_2                         (4)
#define READ_MSG                        (707)

//---------------------

#include ".\TempBook.h"
