#include "..\headers\define.h"
#include ".\BookAsh.h"
//---------------------

#define NAME                            SCRIPT_BookEner

#define BOOK_TYPE1
#define BOOK_PID                        PID_BOOK_ENER
#define SKILL_1                         SKILL_ENERGY_WEAPONS
#define POINT_1                         (4)
#define READ_MSG                        (704)

//---------------------

#include ".\TempBook.h"
