{100}{}{Ves a Ian.}
{101}{}{Ves a un mexicano con una barba poblada y desaliñada.}

{110}{}{¡Ellos sí existen!}
{111}{}{Digo la verdad, ¿por qué no me creen?}
{112}{}{¡Algún día van a llegar!}
{113}{}{¡Tenemos que actuar ahora!}

#First dialogue
{200}{}{¡A huevo amigo! ¿Qué te trae por aquí?}
{1200}{}{A huevo, amiga! ¿Qué te trae por aquí?}
{201}{}{Bueno, estoy...}
{202}{}{¡Al tiro, amigo! ¡No digas nada! A ese tipo no le gustan los extranjeros. Hasta me quieren navajear.}
{1202}{}{¡Al tiro, amiga! ¡No digas nada! A ese tipo no le gustan los extranjeros. Hasta me quieren navajear.}
{203}{}{¿Por qué? ¿Pasó algo malo entre ustedes dos?}
{204}{}{(mira a su alrededor) ¡Monstruos!}
{205}{}{¿Monstruos?}
{206}{}{¡Monstruos! ¡Sanguijuelas gigantes! ¡Unas criaturas horrendas y apestosas! Aparecen en la costa, en donde me pongo a recojer mariscos. Pero esos tontos no me escuchan, ¡creen que estoy loco! Pero el viejo Ian no está loco. ¡Nada de loco!}
{207}{}{Están cometiendo un grave error al ignorarte.}
{208}{}{Me parece que perdiste la cabeza, viejo.}
{209}{}{No me dejes sólo, amigo. ¡Necesito ayuda!}
{1209}{}{No me dejes sólo, amiga. ¡Necesito ayuda!}
{210}{}{Te ayudaré, ¿en dónde están escondidos?}
{211}{}{Están en la goleta encallada de por ahí, en la costa. Pero ten cuidado.}
{212}{}{Ya veo. Adiós.}

#Re-dialogue
{220}{}{Hola, amigo.}
{1220}{}{Hola, amiga.}
{221}{}{Adiós, Ian.}

{230}{}{¿Quién está a cargo por aquí?}
{231}{}{Héctor. Nuestro capitán.}
{232}{}{¿De verdad es un capitán?}
{233}{}{Llegamos en una goleta, y Héctor era el capitán. Desde ese entonces se volvió costumbre llamarlo así.}
{234}{}{Que interesante. Cuéntame otra cosa.}
{235}{}{Ya veo. Adiós.}
{236}{}{¿Quién eres?}
{237}{}{Me llamo Ian, vivo aquí cerca y recojo mariscos en la costa.}
{238}{}{Ahora que lo pienso, ¿de dónde eres?}
{239}{}{Mi familia era mitad mexicana y mitad gringa. Casi siempre ha sido así.}
{240}{}{Eso es interesante. Dime otra cosa.}
{241}{}{Ya entiendo. Nos vemos.}
{242}{}{¿Por qué no te ayuda tu propia gente?}
{243}{}{¡Porque no me creen! ¡Piensan que soy un tonto!}
{244}{}{No temas, sólo quiero saber más acerca de ti y este asentamiento.}
{245}{}{Eso no es muy amable de su parte. Quizás podamos hablar de eso luego.}
