{100}{}{Ves a un comerciante.}
{101}{}{Ves a un pescador... o un cantinero, una de dos.}
{102}{}{Ven y escóndete, no creo que los demonios nos encuentren acá adentro.}

{200}{}{¿Qué necesita, compadre?}
{1200}{}{¿En qué la ayudo, señorita?}
{201}{}{No necesito nada. Nos vemos.}
{202}{}{Dame una cerveza...}
{203}{}{¿Nada más? Aquí tiene.}
{204}{}{Adiós.}
{205}{}{Gracias por el contador. De verdad.}
{206}{}{Después del incendio en la plataforma, hemos tenido suerte con los peces. Estamos agradecidos, amigo.}
{1206}{}{Después del incendio en la plataforma, hemos tenido suerte con los peces. Estamos agradecidos, amiga.}

{210}{}{¿En dónde puedo comprar una célula de fusión para el bote?}
{211}{}{Ninguno de los pescadores te venderá las suyas - ni siquiera tienen suficiente para ellos mismos. Las usamos para eso y el generador. El lugar más cercano del que nos conseguimos las baterías es Puerto Peñasco. Quizás encuentres una por allá.}
{212}{}{Gracias.}
{213}{}{Oye, si vas para allá, ¿te puedo pedir un favor?}
{214}{}{Depende. ¿Qué necesitas?}
{215}{}{Le he estado pidiendo un contador Geiger a los caballeros de Puerto. Pero si encuentran tecnología, no la sueltan; para el día que nos manden otro contador, seguramente ya podremos brillar en la oscuridad. Si me traes uno, te daré una batería a cambio, o chapas si así lo quieres.}
{216}{}{Lo tendré en cuenta.}
{217}{}{Estás de suerte, porque tengo un contador que no necesito.}
{218}{}{Encontré el contador que necesitabas.}
{219}{}{¿En dónde puedo comprar células de fusión para mi motocicleta?}
{220}{}{¡Por fin! Déjame echarle un vistazo... Sí, está en buen estado. ¿Qué quieres a cambio? ¿Chapas o la célula de fusión que necesitas?}
{221}{}{La célula de fusión.}
{222}{}{Las chapas.}
{223}{}{Es un regalo para que puedan cuidarse mejor, no quiero nada a cambio.}
{224}{}{Aquí tienes, está cargada por completo.}
{225}{}{Perfecto.}
{226}{}{Aquí tienes, }
{227}{}{ chapas}
{228}{}{Genial.}
{229}{}{¿En serio? ¡Gracias, amigo!}
{1229}{}{¿En serio? ¡Gracias, amiga!}
{230}{}{De nada.}

{240}{}{Gilberto me dijo que viajaste al Infierno.}
{241}{}{Sí, hace honor a su nombre. No hay más que escombros y... huesos humanos.}
{242}{}{¿En serio? Cuéntame más, tengo que ir hacia allá.}
{243}{}{Suena horrible, no sigas.}
{244}{}{¿En serio quieres saberlo? No me gusta hablar de ello, pero haré una excepción.}
{245}{}{¿Qué peligros me esperan allá?}
{246}{}{¿En serio quieres saberlo? No me gusta hablar de ello. ¿Vas a pedir algo o no?}
{247}{}{Ten 20 chapas, quiero un té. Cuéntame lo que viste.}
{248}{}{No tengo dinero, tal vez otro día.}
{249}{}{Buscaba entre los escombros a ver si tenía suerte, el lugar no está tan bien explorado como Fénix, así que está lleno de reliquias. Pero lo difícil es sacarlas de ahí - hay radiación y se te pueden venir encima los escombros. Estuve arrastrándome por unos túneles la mitad del tiempo, puedes esconderte de la radiación por un rato ahí adentro.}
{250}{}{Sigue, te escucho.}
{251}{}{Pero, lo peor fueron los demonios. Los 'Segadores'.}
{252}{}{¿Demonios? ¿Segadores? ¿A qué te refieres?}
{253}{}{Son como necrófagos, los que no murieron cuando estallaron las bombas. Son como un cadáver andante, perdieron la cabeza y su humanidad. Por suerte, raramente deciden salir de las ruinas centrales.}
{254}{}{Suena a que fue muy difícil.}
{255}{}{Muchos chatarreros murieron a mano de los demonios o la radiación. Si vas, ten cuidado - lleva medicamentos y algo con lo que defenderte.}
{256}{}{Gracias por el consejo.}
{257}{}{Eso no me asusta.}
{258}{}{Algo me dice que sabes perfectamente lo que hay ahí.}
{259}{}{En efecto. Cambiemos de tema.}

{260}{}{¿Qué sabes al respecto del tesoro que busca Ruiz?}
{261}{}{No te metas con ese hombre, es peligroso y astuto. El tesoro debe ser una mentira, nadie sabe si de verdad existe.}
{262}{}{¿Lo has buscado?}
{263}{}{Tengo una parte del mapa, y Ruiz no quiere soltar la suya. Ni idea en dónde puedan estar las demás.}
{264}{}{¿Estás dispuesto a venderme tu parte del mapa?}
{265}{}{Puede ser, pero no creo que exista ese tal tesoro. Te lo vendo a buen precio, digamos... }
{266}{}{ chapas.}
{267}{}{Trato hecho. Dámelo.}
{268}{}{¿¡Cuánto!? Claro que no, quédatelo.}
{269}{}{No, no tienes suficiente. Vuelve cuando tengas las chapas, así me aprovecho de la codicia de ustedes dos.}
{270}{}{Eh, bueno. Ya vengo...}
{271}{}{(conforme las cuenta, empieza a sonreír) ¡Soy un suertudo! Aquí tienes mi parte del mapa, te deseo suerte buscando el tesoro. La necesitarás más que yo.}
{272}{}{Adiós.}

{280}{}{Oye, ¿te enteraste de lo que pasó con Johnny?}
{281}{}{Sí, es un pueblo pequeño, los rumores corren rápido. Es terrible, jamás pensé que uno de nosotros sería capaz de algo así.}
{282}{}{¿Quién crees que sea el culpable?}
{283}{}{No lo sé. Todos queríamos a Johnny, la única excepción era Ruiz, pero él nos odia a todos. Aunque, ese payaso que tiene como tío... Tin-Tan. Johnny estaba emocionado, porque él viajaba desde Fénix. Pero después de que llegó, Johnny no era el mismo, no quería ni mirar a su tío.}
{284}{}{¿En serio viene de Fénix?}
{285}{}{Sí, sus papeles estaban en orden, todos eran del Sonora Express. No tienen oficina por aquí, así que cuando tenemos que enviar o recibir algo de Fénix, pasa por Casa Nueva.}
{286}{}{Entonces debería investigar en Casa Nueva o en Fénix. Gracias.}
{287}{}{¡Cabrón, no compraste nada!}
{1287}{}{¡Pinche chamaca, no compraste nada!}
{288}{}{Aguántate.}
{289}{}{Perdón, aquí tienes cinco chapas.}
