{100}{}{Ves una computadora.}
{101}{}{Ves una computadora con acceso a la red pública.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Regresar al menú principal}

{210}{}{23 de Octubre, 2077, 12:00}
{211}{}{Aquí la Plataforma llamando al Operador. ¿Me copian? (silencio) Repito, Plataforma al Operador. ¿Me copian?}
{212}{}{23 de Octubre, 2077, 12:10}
{213}{}{¡Aquí la Plataforma! ¡Llamando al Operador! ¿Pueden escucharme? (silencio) Qué demonios está ocurriendo allá...}
{214}{}{23 de Octubre, 2077, 13:00}
{215}{}{Aquí la Plataforma. No tenemos ningún contacto con la costa. Si alguien me escucha, por favor, envíen una señal de respuesta.}
{216}{}{23 de Octubre, 2077, 21:00}
{217}{}{Aún nada. La radio está en buenas condiciones; no tienen ninguna falla. ¿Por qué nadie me copia? ¿Por qué está tan callada la guardia costera?  Si me escuchan, ¡por favor, respondan!}
{218}{}{24 de Octubre, 2077, 12:00}
{219}{}{Cambiando a las frecuencias de emergencia. ¿Alguien me escucha? ¡Respondan! ¿Qué está pasando allá? Parece que ocurrió algo en Mexicali hace un par de días. Sospechamos que los Chinos sabotearon la central eléctrica. Pido ayuda de la guardia costera... ¡Quien sea, ¡respondan, por favor!}
{220}{}{30 de Octubre, 2077, 12:00}
{221}{}{Hemos estado una semana sin contacto alguno. La plataforma funciona, los trabajadores están bien, pero no sabemos qué está ocurriendo en la costa. La administración no ha dicho nada, en las estaciones de radio no se escucha nada. Hemos tenido problemas así en el pasado, pero jamás una semana entera. No podemos abandonar la plataforma sin quebrar nuestro contrato. Ojalá que esto se arregle pronto.}
{222}{}{6 de Noviembre, 2077, 8:02}
{223}{}{Se supone que hoy recibíamos comida y un cambio de turno. ¿En dónde carajo están todos? Si nadie nos contacta, nos veremos obligados a abandonar la plataforma.}
{224}{}{20 de Noviembre, 2077, 5:48}
{225}{}{¡Atención! Aquí la Plataforma. Evacuaremos nuestra única balsa. Queda una sola persona en la estación. A cualquiera que escuche esto, se lo imploro, envíen ayuda.}
{226}{}{21 de Noviembre, 2077, 12:33}
{227}{}{¡Aquí la Plataforma! ¿¡Quién está ahí!? - Somos nosotros, amigo. Tenemos terribles noticias... Mexicali fue destruida por una bomba nuclear... - ¿Qué...? ¡Dios mío! - ...Y me parece que absorbimos una dosis letal de radiación. Soy el único que llegó a la costa para decírtelo... Me estoy sofocando... No hagas nada estúpido... Conserva tu comida y agua. No podemos recuperar la balsa. Adiós, amigo. Fue un honor trabajar contigo...}
{228}{}{29 de Noviembre, 2077, 15:00}
{229}{}{Sé lo que dijo... Pero, ¿a quién le importa? Nadie necesitará la estación. Ni siquiera yo. Estoy sólo y no puedo irme. Cuando automatizaron la estación, los avaros de la administración nos dejaron una sola balsa para que hubiera más espacio para las máquinas, y ahora está en la costa. No puedo nadar hasta allá. ¿Vendrán a rescatarme, algún día? Quien sabe. Mis reservas de comida y agua durarán un mes, nada más. Por ahora, me aseguraré de que no ocurra ningún accidente. De todas formas, el Mar de Cortés ya es un desastre medioambiental, incluso sin la plataforma. Todo es culpa de la codicia humana...}
{230}{}{25 de Diciembre, 2077, 23:14}
{231}{}{¡Oigan, chicos! ¿Están celebrando navidad, cierto? *¡Hic!* Recordé una botella que estaba escondida. *¡Hic!* Hola a todos. Esto es una broma, ¿no? No hubo ninguna guerra, ¿cierto? Y Mexicali está bien, ¿verdad? Ya voy con ustedes, solo tengo que ponerme el salvavidas...  así que... ¡espérenme, niños! ¡Papá está en camino!}
