{100}{}{Ves a la computadora de seguridad.}
{101}{}{Ves una computadora con acceso al sistema de seguridad.}

#Dialogue
{200}{}{Acceso concedido. Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Regresar al menú principal}
{205}{}{Cancelar}

{210}{}{Desactivar las torretas de seguridad.}
{211}{}{Deshabilitar las torretas pone en peligro la seguridad de la plataforma. ¿Está seguro de que desea deshabilitarlas?}
{212}{}{¡Deshabilita las malditas torretas!}
{213}{}{Torretas desactivadas.}
{214}{}{Activar torretas de seguridad.}
{215}{}{Torretas activadas.}

{220}{}{Agregar nueva identidad a la base de datos.}
{221}{}{Por favor, rellene el formulario.}
{222}{}{Nombre: }
{223}{}{. Edad: }
{224}{}{. Lugar de nacimiento: La Villa, Arizona. Acceso: total.}
{225}{}{Hecho. Se ha agregado a un nuevo usuario a la base de datos.}
