{100}{}{Ves a un aldeano.}
{101}{}{Ves a un pescador de piel morena.}

{110}{}{Hola.}
{111}{}{Fuera de aquí.}
{112}{}{No nos agrada la gente como tú.}
{113}{}{¿Sabes? Deberías llevarte un barco y ahogarte en el mar.}

{120}{}{Hola.}
{121}{}{Es bueno ver una cara nueva.}
{122}{}{Encantado de conocerte.}
{123}{}{No hemos atrapado nada bueno estos días.}
{124}{}{Si tienes cerebro, es mejor que no nades demasiado lejos.}
{125}{}{Aquí hay un monstruo marino, ¡lo digo en serio!}
{126}{}{Parece que habrá una tormenta.}
{127}{}{No deberías caminar junto a la orilla durante la noche.}
{128}{}{}
{129}{}{}

{130}{}{Mis respetos.}
{131}{}{Siempre serás bienvenido aquí.}
{132}{}{Has hecho mucho por nosotros, gracias.}
{133}{}{El otro día atrapé uno muy grande.}
{134}{}{Debo ir a pescar, ¿quieres ir conmigo?}
{135}{}{Aquí hay un monstruo marino, ¡lo digo en serio!}
{136}{}{Parece que habrá una tormenta.}
{137}{}{No deberías caminar junto a la orilla durante la noche.}
{138}{}{}
{139}{}{}

{140}{}{Tú no sabrás lo que pasó en Puerto, ¿verdad?}
{141}{}{¡Destruyeron a la Hermandad en Puerto! Sin ellos las cosas se van a poner feas.}
{142}{}{La Hermandad del Acero se fue, y con ella, nuestra seguridad.}
{143}{}{Demonios, si la Hermandad tenía un armamento así, imagina lo que nos podrían haber regalado.}
{144}{}{Por supuesto que sobreviviremos sin la Hermandad, pero... nos daban todo lo que nos hacía falta.}

{150}{}{¡Mira como arde!}
{151}{}{Jamás pensé que podrías prenderle fuego al agua.}
{152}{}{El cielo está lleno de humo, parece que ese "petróleo" se cayó al mar.}
{153}{}{Gracias por ayudarnos con la plataforma. Aunque tendremos que aguantarnos todo el humo...}

{159}{}{¿Tú fuiste quien trató a los enfermos, verdad? Muchas gracias.}

{160}{}{Alguien mató al enano de Ruiz. No lo extrañaremos.}
{161}{}{Ruiz ya estiró la pata. Se lo merecía.}
{162}{}{Al menos ya no tendremos que escuchar a Ruiz gritarle a los pescadores por la mañana.}
{163}{}{Me muero por saber qué encontraron Ruiz y ese gringo del que hablaba.}
{164}{}{Ruiz anda pataleando como un bebé, parece que alguien le ganó en las cartas.}
{165}{}{¿Así que el monstruo del faro era real?}
{166}{}{No me acercaré al faro, mucho menos si no me acompañan, de ninguna manera.}
{167}{}{Los demonios del Infierno se nos están acercando demasiado...}
{168}{}{Dios mío, no puedo creer que un demonio del Infierno haya estado tan cerca. ¡Qué horror!}
{169}{}{¿Y si los Segadores del Infierno deciden invadirnos?}
