{100}{}{Ves al monstruo de la Laguna Negra.}
{101}{}{¡Una criatura de aspecto espantoso sale arrastrándose del faro!}
{102}{}{¡Ooooh!}

{200}{}{¡Oooh!}
{201}{}{¡Ahh, un monstruo! ¡Muere! ¡Muere!}
{202}{}{¡Alto! Soy como tú, no quiero herirte. ¿Me entiendes?}
{203}{}{¿Eh?}
{204}{}{Pensándolo mejor, es mejor si te mato. ¡Muere, monstruo!}
{205}{}{Escúchame, tienes que irte de aquí.}
{206}{}{¿A-já?}
{207}{}{Los pescadores te están buscando, y si te encuentran, te van a matar. ¿Entendido?}
{208}{}{¿Y-io? ¿Mat-arr? ¡Arrgh! ¡Comida! ¡Mi comida!}
{209}{}{Sí, sí. Entiendo que tengas hambre, pero éstos son sus peces. Y te van a matar si los tocas. ¡Sal de aquí antes de que sea demasiado tarde!}
{210}{}{No me estás entiendo. Ya intenté por las buenas... ¡Ahora por las malas!}
{211}{}{Entonces no me dejas otra opción, tienes que morir.}
{212}{}{(Sus ojos se llenan de terror y escapa)}
{213}{}{Regresa al infierno de donde vienes, fenómeno.}
