{100}{}{Ves a Ruiz.}
{101}{}{Ves a uno de los lugareños. Lleva un pañuelo y una capa ligera.}
{102}{}{Nos vemos cerca del tesoro.}
{103}{}{No me agotes la paciencia.}
{104}{}{Si vuelvo a encontrar un mapa del tesoro, hablaré contigo.}
{105}{}{¿Buscas un tesoro? Te aseguro que no está aquí.}
{106}{}{Ni siquiera te escondas por aquí, los Segadores te encontrarán.}
{107}{}{De acuerdo.}

{200}{}{¡Hola, compadre! Mi nombre es José René Ruiz. ¿Qué te trae a nuestro pueblito?}
{1200}{}{¡Hola, señorita! Mi nombre es José René Ruiz. ¿Qué te trae a nuestro pueblito?}
{201}{}{Estoy buscando algo.}
{202}{}{Busco a alguien.}
{203}{}{¿Sabes? Yo también estoy buscando algo. Si me ayudas, yo te ayudo a ti.}
{204}{}{¿En serio? ¿De qué se trata?}
{205}{}{Bueno, un viejo escondió un tesoro en la costa. Y luego se murió. No sé en dónde escondió el tesoro. Existe un mapa, pero lo rompió en cuatro pedazos y los escondió.}
{206}{}{Que astuto.}
{207}{}{Tengo un solo fragmento, si encuentras los demás, tráemelos, y podremos dividirnos el tesoro.}
{208}{}{¿Qué me garantiza que no me estafarás?}
{209}{}{Me parece bien, si lo encuentro, hablaré contigo.}
{210}{}{¿Y cómo sabré que *tú* no me vas a estafar? Dejémoslo como un acuerdo verbal. Si no te gusta, olvídalo y sigue con tu vida.}
{211}{}{Lo pensaré.}
{212}{}{¡Un fenómeno! Me pregunto cuánto te aguantarán los demás. Aunque, quizás me seas útil... Escucha, compadre, me llamo José René Ruiz. Cuéntame qué haces aquí.}
{1212}{}{Pero que mujer más... Me pregunto cuánto te aguantarán los demás. Aunque, quizás me seas útil... Escucha, señor... ¿Eres mujer, verdad? Bah, no importa. Me llamo José René Ruiz. Cuéntame qué haces aquí.}

{220}{}{¿Tienes alguna noticia?}
{221}{}{Todavía no.}
{222}{}{¿Has encontrado algo?}
{223}{}{No.}

{224}{}{¿En dónde podría buscar las piezas del mapa? ¿Alguna idea?}
{225}{}{Si supiera, ¿no crees que hubiera ido a buscar yo? Lo podría haber metido entre un montón de mierda, yo que sé.}
{226}{}{Está bien, seguiré buscando.}

{230}{}{¿Has ido a la plataforma?}
{231}{}{No. Porque no hay nada que hacer allá. Si existiera una máquina para producir chapas, sería el primero en ir allá.}
{232}{}{¿Sabes en dónde podría conseguir una batería para el bote?}
{233}{}{Los dueños de los botes ya se repartieron todas las baterías, y yo no te daré la mía. Prueba a hablar con los demás dueños; suelen estar en el bar.}
{234}{}{Lo intentaré.}

{240}{}{Tengo las demás piezas del mapa.}
{241}{}{¡Ven aquí!}
{242}{}{Em, bueno...}
{243}{}{¡Vete al carajo! Encontraré el tesoro sin tu ayuda.}
{244}{}{Entonces.. (Saca su fragmento, une los fragmentos y los cambia de lugar durante un buen rato) Ahí está...}
{245}{}{¿Estás seguro?}
{246}{}{¡Por supuesto! Lo único que falta es que vayas y lo saques de ahí. Encuentra una pala y anda hacia allá, el tesoro está enterrado junto al faro en la costa, hacia el norte de la villa.}
{247}{}{¡Voy!}

{250}{}{Admítelo, ¿fuiste tú quien mató a Johnny?}
{251}{}{¿¡De qué mierda estás hablando!?}
{252}{}{Lo estrangularon con una de tus cuerdas. ¿Cómo explicas eso?}
{253}{}{¡Ja! Le vendo esa cuerda a varios pescadores. ¿Y por qué demonios mataría a alguien? ¿Acaso eres idiota?}
{254}{}{¿A quién se la vendiste?}
{255}{}{Lo tengo en mis cuentas, mira... El único que compro una cuerda fue Tin-Tan. Espera, ¿no se supone que él era el tío de Johnny?}
{256}{}{Gracias, iré a hablar con él.}
{257}{}{Las preguntas las estoy haciendo yo, idiota. ¿Quién fue el último que te compró la cuerda?}
