{100}{}{Ves a un aldeano.}
{101}{}{Ves a un pescador con la piel bronceada.}
{102}{}{Es un aldeano enfermo.}
{103}{}{Ves a un pescador exhausto gracias a su enfermedad.}
{104}{}{Tus habilidades no son suficientes para curar al paciente sin medicamentos.}
{105}{}{(}
{106}{}{/3) de los pacientes se han recuperado.}
{107}{}{Me siento mejor. Gracias, doc.}

{110}{}{*Cof cof*}
{111}{}{Oh...}

{120}{}{*Cof cof*}
{121}{}{No me siento bien. ¿Lo dices en serio?}
{122}{}{Ya no estoy enfermo, es como si nunca hubiera ocurrido. Haces maravillas, doc.}
{123}{}{¿Por qué te molestaste en ayudarme si odias tanto este lugar?}
