{100}{}{Ves a Tin-Tan.}
{101}{}{Ves a un pescador flaco de ropa andrajosa, tiene un bigote fino y dientes torcidos.}
{102}{}{¡No te me acerques! Eh... es que hueles mal.}
{103}{}{Chingada madre, es todo culpa de ese maldito mocoso...}

{200}{}{¡Ay-ay-ay, qué pez más pequeñito! ¿Y yo para qué te quiero? Regresa al mar, engorda y luego vuelves. ¡Adiós! ¡Nos vemos, pecesito!}
{201}{}{Eh, creo que te estoy molestando.}
{202}{}{Las olas me enferman, y luego me duermo. ¡Pero a veces sueño algo genial, como si bailara con un montón de chiquitas lindas!}
{203}{}{Ya... ya veo.}
{204}{}{Todos te damos las gracias por eso del petróleo. «¡Aajúuaa!»}
{205}{}{«Eh... de nada.»}
{206}{}{De nada.}
{207}{}{Todos te damos las gracias por eso del petróleo. ¡Muchas gracias!}


{210}{}{Hola, soy Tin-Tan. ¿Cómo estás?}
{211}{}{Adiós.}

{220}{}{¿Has ido a la plataforma?}
{221}{}{¡En mis sueños puedo viajar a cualquier lado, a los brazos de cualquiera!}
{222}{}{Ah, ya veo.}
{223}{}{Tin-Tan - es un nombre raro.}
{224}{}{Yo me llamaba... redoble de tambores... ¡Topillo! Y luego me convertí en Tin-Tan. Pero mi nombre es... chan chan chaaan... ¡Germán Henaro Cipriano Gómez Valdés-y-Castillo! Pero es muy... inconveniente, ¿no crees?}
{225}{}{Ah, ya me quedó claro.}
{226}{}{Ese apodo te hace ver muy imbécil.}

{230}{}{Te tengo malas noticias. Murió tu pariente, Johnny.}
{231}{}{¡Ooh! ¿¡Qué pasó!?}
{232}{}{Alguien lo mató. Lo estrangularon con esta cuerda.}
{233}{}{¿Y esto qué es? ¡Espera! ¡Ruiz vende estas cuerdas! Ooh, ¿acaso Ruiz lo hizo? ¡No puede ser!}
{234}{}{Bueno, entonces tendré que preguntarle a Ruiz.}
{235}{}{Pero la cuerda es nueva, y el último que compró una fuiste tú.}
{236}{}{¿Y por qué haría eso? ¡Soy su tío! ¡Ay-ay-ay, déjame en paz, quiero llorar! ¡Pobre Johnny! ¡Ay caramba!}
{237}{}{Hmm, tienes razón. ¿Por qué? Necesito más evidencia.}
{238}{}{Tú no eres Germán Henaro Cipriano Gómez Valdés-y-Castillo, el está muerto. ¿Quién eres?}
{239}{}{¡No sé de quién hablas!}
{240}{}{El verdadero Germán Valdés murió en la caravana. Le robaste sus documentos y te hiciste pasar por él. ¿No es así?}
{241}{}{(mira a su alrededor) Escúchame, hijo de puta, basta de bromas. Cierra la boca o vas a terminar como ese niño. ¿De acuerdo?}
{1241}{}{(mira a su alrededor) Escúchame, hija de puta, basta de bromas. Cierra la boca o vas a terminar como ese niño. ¿De acuerdo?}
{242}{}{Gracias por confesar el crimen. ¡Mereces la muerte!}
{243}{}{No le diré nada a nadie. Lo prometo.}
{244}{}{¿En serio? Bueno, no importa. Perdón por molestarte.}
