{100}{}{Ves a un pueblerino.}
{101}{}{Ves a un pueblerino con la piel bronceada, sus prendas hechas con cuero de brahmán.}

{110}{}{Viene una tormenta de arena.}
{111}{}{La próxima temporada será calurosa.}
{112}{}{Mis brahmanes están flacos.}
{113}{}{Necesitamos llevar más agua cuando pastemos.}
{114}{}{Quedarnos en el nido es más peligroso que nunca.}
{115}{}{El pueblo siempre ha sido nuestro.}
{116}{}{Tenemos que proteger a nuestras familias de los saqueadores.}
{117}{}{¡Brahmán Divino, protégenos de los forasteros!}
{118}{}{Debemos obedecer a nuestros líderes.}

{130}{}{El Viejo Mangas nos llevará a la perdición.}
{131}{}{Pero Mangas nos lo advirtió...}
{132}{}{Estoy seguro de que Genaro querrá aliarse con Fénix.}
{133}{}{Genaro ha muerto, era el que mejor comerciaba con los forasteros.}
{134}{}{Nana cuida nuestra tribu como mujer y como líder.}
{135}{}{A Nana la mataron los misionarios, ¿quién más haría algo así?}
{136}{}{Me preocupa el futuro de Chatto y sus amigos.}
{137}{}{Hace tiempo que no vemos a Chatto...}
{138}{}{Chatto es joven y ya es un líder. Vivimos en tiempos extraños.}
{139}{}{Jerónimo siempre sabe qué es mejor para nuestra tribu.}
{140}{}{Jerónimo... Que el Sol siempre ilumine tu camino.}

{150}{}{Ha llegado el día. Fénix ahora controla nuestra tribu.}
{151}{}{Los misionarios de Fénix cumplieron con su trabajo.}
{152}{}{Nuestro Gran Jefe tomó su decisión. Debemos respetarla.}
{153}{}{¿Qué hay del pueblo? ¿Nos tenemos que ir?}
{154}{}{La codorniz debe abandonar su nido.}
{155}{}{La guerra se acabó, por fin.}
{156}{}{Espero que los rangers hagan cumplir su palabra.}
{157}{}{Le pediré a los espíritus del yermo para que acaben con la guerra.}
{158}{}{¡Brahmán Divino, muéstranos el camino!}
{159}{}{Los trucos del Brahmán Oscuro llevaron a nuestra tribu a un pastizal seco.}

{170}{}{No deberías entrar sólo en las catacumbas.}
{171}{}{¿Es por eso que los ancianos nos dijeron que no entráramos ahí?}
{172}{}{Había un monstruo en las catacumbas.}
{173}{}{¡Gloria al Brahmán Divino! Ahuyentaron a ese espíritu malvado.}
{174}{}{No me sorprende que los demás hablaran mal de las catacumbas.}
{175}{}{Me sigue dando miedo las catacumbas.}
