{100}{}{Ves a Sid.}
{101}{}{Ves a un hombre de negocios.}
{102}{}{Tuve mucha suerte al encontrarme contigo. Gracias por ayudarnos.}
{103}{}{El camino está despejado.}
{104}{}{No queda nadie que pueda pagarte por la protección de la caravana.}
{105}{}{¡Maldito traidor!}
{106}{}{Gracias a tu astucia, no te detectaron.}
{107}{}{ ha muerto. No queda nadie para pagarte por tu labor.}

#Before receiving the quest
{200}{}{Hola, viajero. Me llamo Sid, soy un mercader. Parece que los dos estamos atrapados aquí, ¿no?}
{1200}{}{Saludos, viajera. Me llamo Sid, soy un mercader. Parece que los dos estamos atrapados aquí, ¿no?}
{201}{}{Tengo un asunto del que ocuparme por aquí. Debo irme pronto.}
{202}{}{¿Entonces tienes algo pendiente? Entiendo. Aunque estés en buenos términos con estos pueblerinos, las tribus del yermo no serán tan amistosas. Al tener que atravesar su territorio, ¿crees que estarás a salvo?}
{203}{}{Hm, ¿entonces qué sugieres?}
{204}{}{Tienes toda la razón. No puedo esperar a conocer una ciudad de verdad, como esa de la que hablan todos.}
{205}{}{Llegar a Fénix sólo tomará unos días, pero es peligroso. Es mucho más seguro ir en grupo.}
{206}{}{¿Entonces tienes un grupo?}
{207}{}{Sí, estoy preparando mi caravana para regresar a Fénix. Somos pocos y el camino es más peligroso gracias a lo que ocurrió con los misionarios. Me preocupa que alguno de los salvajes intenten emboscarnos apenas salgamos del pueblo. Necesito más guardias, te pagaré 500 chapas si me acompañas a Fénix. ¿Te parece?}
{208}{}{Me lo pensaré.}
{209}{}{Claro, cuenta conmigo.}
{210}{}{¿Qué transporta tu caravana?}
{211}{}{Todo tipo de utensilios de la tribu, artículos de cuero, carne seca. Tuve mucha suerte, pues hice un intercambio con Genaro para algunos brahmanes. En la ciudad, pagan una fortuna por uno vivo.}
{212}{}{¿Crees que tengamos problemas en el camino?}
{213}{}{Es posible.}

{220}{}{Bien, ¿vendrás con nosotros?}
{221}{}{Todavía no me decido. No me incluyas en el plan, por favor.}
{1221}{}{Todavía no me decido. No me incluyas en el plan, por favor.}
{222}{}{Cuenta conmigo.}

{230}{}{Me alegra que nos acompañes. Habla conmigo cuando te hayas preparado.}
{231}{}{De acuerdo.}
{232}{}{Tengo todo lo necesario, vámonos.}

#After receiving the quest
{250}{}{¡No puede ser! Los salvajes no nos dejará en paz, tenemos que deshacernos de ellos.}
{251}{}{¡Los escorpiones matarán a los brahmanes! ¡No podemos dejar que ocurra!}
{252}{}{¡Una emboscada! ¡Que no cunda el pánico! ¡Protejan la caravana!}
{253}{}{Comprendo.}
{254}{}{No hay moros en la costa. ¿Están todos bien? Entonces sigamos.}
{255}{}{Espera, debo alistarme. Ya vengo.}
{256}{}{Listo, ya podemos irnos.}
{257}{}{¡Demonios! Hemos perdido a muchos brahmanes. Tendremos que abandonar parte del cargamento y llevar lo que podamos. No creo que vaya a ganar dinero, parece que lo perderé. Mierda.}
{258}{}{Eso no importa, porque estamos vivos. Tenemos que irnos.}
{259}{}{Espérame, ya vengo.}

{260}{}{Gracias por tu ayuda. Ha sido un placer trabajar contigo. Toma tus 500 chapas, es lo que prometí. Pero dudo que vuelva a San Brahmán hasta dentro de un par de años. Tengo que esperar a que las cosas se calmen. Lo entiendes, ¿no?}
{261}{}{Buena suerte, Sid.}
{262}{}{Gracias por tu ayuda. Pero perdimos a los brahmanes y gran parte del cargamento, no podré pagarte lo prometido. Puedo darte }
{263}{}{ chapas por tu labor.  Lo más seguro es que no vuelva a San Brahmán hasta dentro de un par de años. Tengo que esperar a que las cosas se calmen. Lo entiendes, ¿no?}
{264}{}{¿Qué tal si buscamos otra ruta a través de las ruinas?}
{265}{}{No, vamos atrasados. Y no tenemos ni los suministros ni la paciencia. Sigamos avanzando.}
{266}{}{Deberíamos atravesar las ruinas de allá, nos llevará más tiempo pero estaremos a salvo.}
{267}{}{Quería llegar a la ciudad durante el atardecer, pero tienes razón. Ve a echar un ojo y te seguiremos.}
{268}{}{Bien, me pondré con ello.}
{269}{}{Todavía no, dame un segundo.}
{270}{}{Es posible que haya peligro más adelante. Podría explorar un poco.}
{271}{}{¿Pero acaso te quieres morir? No hagas esa estupidez. Si vamos juntos, será más fácil salir adelante.}
{272}{}{Puede que hayan problemas más adelante, iré a ver qué hay.}
{273}{}{Con cuidado, somos pocos. Si te perdemos, será difícil.}
{274}{}{Estaré bien, espera mi señal.}
{275}{}{Creo que tienes razón, podrían eliminarme sin problemas. Te sigo.}
{276}{}{Tengo que prepararme, espérame un minuto.}
