{100}{}{Ves a un misionario.}
{101}{}{Ves a uno de los soldados. Está completamente preparado para la batalla.}

{110}{}{Deberías hablarle al comandante.}
{111}{}{Tienes suerte, no eres de una tribu de pastores.}
{112}{}{El comandante manda. Habla con él.}
{113}{}{¿Te quieres unir? No compartiré mi almuerzo contigo.}
{114}{}{No sé lo que piensen ustedes, pero yo pienso en salir con vida de todo esto.}
{115}{}{Parece que estaremos aquí por un buen rato.}

{150}{}{(Tararea una canción vieja mientras observa tu arma con envidia)}
{151}{}{~ Carabina Treinta Treinta ~}
{152}{}{~ Que los rebeldes portaban ~}
{153}{}{~ Y los maderistas decían ~}
{154}{}{~ Que con ellas no mataban. ~}
{155}{}{~ Con mi Treinta Treinta me voy a marchar ~}
{156}{}{~ A engrosar las filas de la rebelión ~}
{157}{}{~ Si mi sangre piden, mi sangre les doy ~}
{158}{}{~ Por los habitantes de nuestra nación ~}
{159}{}{~}

{160}{}{Por fin, acabamos.}
{161}{}{¡Lo hicimos! ¡Genial!}
{162}{}{Les partimos la madre.}
{163}{}{No se atreverán a meterse con nosotros.}
{164}{}{Los Rangers se están escapando al oeste, están asustados.}
{165}{}{¡Aquí mandamos nosotros!}

{170}{}{¡Malditos salvajes!}
{171}{}{Tendremos que volver a Fénix con nuestros nombres manchados...}
{172}{}{Esos malditos tiraflechas se arrepentirán de ésto.}
{173}{}{Gracias a Dios, nos vamos a casa.}
{174}{}{Si el comandante se va, entonces no tenemos por qué seguir aquí.}
{175}{}{Me dijeron que no me metiera con estos pendejos...}

{250}{}{(Tararea una canción vieja mientras observa tu arma con envidia)}
{251}{}{~ «Carabina Treinta Treinta» ~}
{252}{}{~ «Que los rebeldes portaban» ~}
{253}{}{~ «Y los maderistas decían» ~}
{254}{}{~ «Que con ellas no mataban.» ~}
{255}{}{~ «Con mi Treinta Treinta me voy a marchar» ~}
{256}{}{~ «A engrosar las filas de la rebelión» ~}
{257}{}{~ «Si mi sangre piden, mi sangre les doy» ~}
{258}{}{~ «Por los habitantes de nuestra nación» ~}
{259}{}{~}