{100}{}{Ves a un pastor.}
{101}{}{Ves a un hombre de cabello largo y negro.}
{102}{}{No pensé que los hongos estarían tan fuertes...}

{200}{}{¿Qué quieres?}
{1200}{}{¿Qué quieres?}
{201}{}{Déjame en paz, cara pálida.}
{1201}{}{Déjame en paz, cara pálida.}
{202}{}{¿Por qué tanta hostilidad?}
{203}{}{No te hagas el tonto. No necesito nada de ti. El tiempo se me escapa como arena de las manos. Pronto me marcho.}
{204}{}{¿A dónde vas?}
{205}{}{Mi pueblo se prepara, cruzaremos el desierto. Tenemos que estar listos antes de que llegue la tormenta de arena, pero la maldita carreta se quebró.}
{206}{}{¿Acaso es algo grave?}
{207}{}{Cuando necesitábamos ayuda de un cara pálida, hacíamos un trato o sólo lo pedíamos. Pero ahora ustedes nos declaran la guerra. Soy el único que debe arreglarlo, y no sé cómo.}
{208}{}{Yo puedo ayudarte.}
{209}{}{No quiero la ayuda de un desconocido.}
{210}{}{Déjame mostrarte que no todos somos iguales.}
{211}{}{¿Me ayudarás? Hmm, bueno. Pero no tengo nada que darte a cambio.}
{212}{}{No importa, lo haré.}
{213}{}{¿No me darás nada? Entonces no te ayudaré en nada.}
{214}{}{Lo arreglaré, pero te va a costar. Las herramientas no son gratis, ¿sabes?}
{215}{}{Ustedes los caras pálidas siempre buscan ganar algo. No tengo monedas, pero si lo arreglas, te daré carne seca.}
{216}{}{Me lo pensaré.}
{217}{}{Sólo me darás carne podrida. Arréglalo tú.}

{220}{}{¿Qué quieres?}
{1220}{}{¿Qué quieres?}
{221}{}{Déjame en paz, cara pálida.}
{1221}{}{Déjame en paz, cara pálida.}
{222}{}{Espero siempre te encuentres bien.}
{223}{}{Adiós.}

{230}{}{He arreglado la carreta.}
{231}{}{¡Lo conseguiste! Los caras pálidas siempre buscan hacernos daño, jamás pensé que nos ayudarían. La paz parece estar tan lejos.}
{1231}{}{¡Lo conseguiste! Los caras pálidas siempre buscan hacernos daño, jamás pensé que nos ayudarían. La paz parece estar tan lejos.}
{232}{}{¿Y no me darás nada a cambio?}
{233}{}{(suspiro) Sabía que no podía confiar en ti. Sólo piensas en ti, como todos los demás. Esa es la diferencia entre nosotros.}
{234}{}{Bueno, olvídalo.}
{235}{}{Te ayudé, es justo que reciba algo a cambio.}
{236}{}{Ya, aquí tienes algo de carne seca. Pero no me pidas más, tengo que prepararme para el viaje.}
{237}{}{De acuerdo.}
{238}{}{No quiero nada a cambio. Sólo quería ayudarte.}
{239}{}{Es la primera vez que veo a un cara pálida que no es un egoísta. Gracias. Que el Brahmán Divino te guíe en tus momentos más difíciles.}

{250}{}{¿Qué tiene de difícil reparar una carreta?}
{251}{}{Nuestra tribu trabaja el cuero, no las carretas. Solíamos pedirle ayuda a los caras pálidas como trato. Pero ahora no hay nadie a quién pedirle eso.}
{252}{}{Ya veo.}
{253}{}{¿Por qué te llevarás a tu familia entera al yermo?}
{254}{}{Nosotros viajamos por el desierto de Sonora. En épocas difíciles, la tribu se reúne aquí. Si nos quedamos, nos morimos de hambre. Los brahmanes necesitan pasto, y el pasto necesita tiempo. Y no hay suficiente agua para todos.}
{255}{}{Comprendo.}

{260}{}{¿Qué piensas de la alianza con los forasteros?}
{261}{}{El que mucho abarca, poco aprieta. No puedes mirar al este y al oeste al mismo tiempo.}
{262}{}{Creo que te entiendo...}
{263}{}{Tenemos que seguir nuestras tradiciones. Si no, los más fuertes decidirán nuestro destino. Ellos serán el pastor, y nosotros el rebaño.}
{264}{}{Ahora sí te entendí.}
