{100}{}{Ves a un guardia.}
{101}{}{Ves a un hombre de apariencia mexicana.}
{102}{}{Gracias, señor.}
{1102}{}{Gracias, señora.}
{103}{}{El guardia te sonríe, no parece que le preocupe su trabajo ahora mismo.}

{104}{}{«Muchas gracias, compadre.»}
{1104}{}{«Muchas gracias, señorita.»}

{110}{}{¡Lárgate, chingada madre!}
{111}{}{No te voy a dejar pasar.}
{112}{}{No toques la puerta.}

{120}{}{«¡Sal de aquí!»}
{121}{}{«No te puedo dejar pasar.»}
{122}{}{«No toques la puerta, por favor.»}
{123}{}{«No te puedo dejar entrar.»}
