{100}{}{Ves a uno de los niños de Santa Ana.}
{101}{}{Ves a uno de los niños.}

{110}{}{¡Hola!}
{111}{}{¡Hola, héroe!}
{112}{}{¡Hola, amigo!}
{1112}{}{¡Hola, amiga!}
{113}{}{¡Vete, traidor!}

# added for use of the Spanish Trait
{210}{}{«¡Hola! ¿Cómo estás?»}
{211}{}{«¡Eres nuestro campeón!»}
{212}{}{«¡Buenos días, señor!»}
{1212}{}{«¡Buenos días, señorita!»}
{213}{}{«¡Nos traicionaste! ¡Fuera de aquí!»}
