{100}{}{Ves a un mercader.}
{101}{}{Ves a un mercader vestido con un polvoriento atuendo de viaje.}

{200}{}{¡Miren quién es! Gracias a ti, tenemos una nueva ruta. No tenía idea de que había un pueblo por aquí.}
{201}{}{¿Qué piensan vender?}
{202}{}{Todavía vemos eso, amigo mío. Casa Nueva necesita mano de obra, y los Seguidores quieren cultivar unas plantas raras. Veremos qué hacer con eso.}
{203}{}{Es bueno saberlo. Me voy de aquí.}

{210}{}{¿Necesitas algo?}
{211}{}{Nos vemos luego.}
{212}{}{Me largo.}

{220}{}{¿Intercambiamos algo?}
{221}{}{Sólo estoy aquí para negociar. Ya sabes, ver qué quieren los pueblerinos. Pero si tienes algo que valga la pena, te lo compro.}
{222}{}{Entendido. Nos vemos luego.}
{223}{}{¿Tienes alguna idea de lo que pasó aquí?}
{224}{}{No, mantienen la boca cerrada. Y no se las voy a abrir. Todos tenemos secretos, así es el yermo. Mi única preocupación es asegurarme de que no nos vean la cara de tonto.}
{225}{}{¿Qué harán luego de hacer el trato?}
{226}{}{Nos vamos directo a Casa Nueva. ¿Por qué?}
{227}{}{Está bien, no te preocupes. Nos vemos luego.}
{228}{}{¿Podrías llevarme a Casa Nueva?}
{229}{}{Te agradezco que nos hayas ayudado con la ruta, pero no trabajo gratis. Son 300 chapas.}
{230}{}{Aquí tienes las chapas. Estoy preparado.}
{231}{}{No es necesario. Puedo ir sólo.}
{232}{}{¿Puedo ir con ustedes a Casa Nueva?}
