{100}{}{Ves a uno de los habitantes de Santa Ana.}
{101}{}{Ves a una persona de aspecto mexicano.}

{110}{}{¡Hola!}
{111}{}{¡Buenas tardes!}
{112}{}{¡Hola, gringo!}
{1112}{}{Hola, gringa}
{113}{}{¡Lárgate de aquí!}

# added for use of the Spanish Trait
{210}{}{«¡Saludos!»}
{211}{}{«¡Siempre serás nuestro héroe!»}
{212}{}{«¡Gracias por todo, compadre!»}
{1212}{}{«¡Gracias por todo, señorita!»}
{213}{}{«¡Fuera, traidor!»}