{100}{}{Ves a Don Bustos.}
{101}{}{Estás viendo a un hombre con un traje respetable pero raído. Sus sienes grises parecen insinuar un pasado difícil.}
{102}{}{Gracias por tu ayuda. Te veré en mi mansión.}
{103}{}{Regresa a mi mansión, hablaremos allá.}

#First dialogue
{200}{}{(Conforme te acercas al bar, encuentras a un grupo de gente armada; el alcalde está hablando seriamente con ellos.)}
{201}{}{Ejem.}
{202}{}{Ah, eres tú... Ven aquí, necesitamos toda la ayuda posible en este momento.}
{203}{}{¿Qué está ocurriendo?}
{204}{}{Unos malditos forajidos se metieron al bar. Han secuestrado a mi hija y debo pagarles si la quiero de vuelta, no podemos negociar con ellos. Le pagaré cualquier cantidad de chapas a quien rescate a Christina.}
{205}{}{¿Quieren dinero? Eso es malo.}
{206}{}{¿Y qué tengo que ver yo?}

#Re-dialogue
{210}{}{¿Se te ocurre algo?}
{211}{}{A mí me gusta mi cabeza en donde está, no cuentes conmigo.}
{212}{}{Entonces hazte a un lado y no te metas. Quizás se asustarán si ven que somos muchos.}
{213}{}{Eso tiene sentido. Veré cómo se la arreglan.}
{214}{}{Déjame hablar con ellos, quizás pueda convencerlos a que se vayan.}
{215}{}{¿Hablar con esos imbéciles? Eso es una misión suicida, no voy a salvarte si también te agarran de rehén.}
{216}{}{Voy a ver cómo se las arreglan. Buena suerte.}
{217}{}{No te preocupes por mí, sé negociar.}
{218}{}{Propongo un ataque frontal. No hay ninguna razón por la cual hablar con esos pendejos.}
{219}{}{Me parece que no tengo otra opción... ¿Quién está conmigo? Le pagaré bien a cualquiera que ayude a salvar a mi hija.}
{220}{}{Espera, no vayamos de cabeza. Primero hay que analizar la situación.}
{221}{}{Estoy contigo. ¡Esos bastardos se irán al infierno!}
{222}{}{¡Entonces, adelante!}
{223}{}{¡Vamos!}
{224}{}{¿Por qué no quieres pagar el rescate?}
{225}{}{Piden demasiado, la ciudad quedaría en ruinas, más de lo que ya está...}
{226}{}{¿Más?}
{227}{}{Proponen un intercambio, nos darán a Christina y a cambio debemos dejarlos ir. No puedo confiar en ellos.}
{228}{}{Quizás puedas infiltrarte con esa armadura que tienes... No es mala idea, pero... No, seguro te detectarán. ¿Alguna idea?}
{229}{}{Hmm...}

{250}{}{Como puedes ver, tu hija está a salvo.}
{251}{}{Christina, ¿estás bien? Dios mío... ¡Haré que estos bastardos paguen por lo que te hicieron!}
{252}{}{¿Estás pensando en atacarlos?}
{253}{}{Eso es obvio, si los demás forajidos se enteran de esto, van a secuestrar a mi hija todos los malditos días. Hay que acabar con ellos de una vez por todas.}
{254}{}{No te llevaré la contraria. Un criminal merece ser castigado. ¿Cuándo los atacaremos?}
{255}{}{No cuentes conmigo, yo no tengo nada que ver en esto.}
{256}{}{Tu hija está muerta. Pasó ante mis propios ojos.}
{1256}{}{Tu hija está muerta. Pasó ante mis propios ojos.}
{257}{}{¡No! ¡Noooo!}
{258}{}{Lo siento mucho.}
{259}{}{(furioso) Esos... ¡Esos bastardos me las van a pagar muy caro! ¡TODOS, ESCUCHEN! ¡Ofrezco una recompensa por la cabeza de cada hijo de puta metido en ese bar!}
{260}{}{Genial, cuenta conmigo.}
{261}{}{Tendrán que hacerlo sin mí, yo no quiero ser parte de esto.}
{262}{}{Rescata a mi hija. De inmediato.}
{263}{}{Ya no hay tiempo para hablar, los forajidos no se rendirán tan fácilmente.}
{264}{}{Merecen ser castigados, pero es demasiado peligroso atacarlos mientras están ahí adentro. Déjalos ir, al menos nadie morirá.}
{265}{}{No quiero que mi ciudad vea otra masacre... Ya tenemos una reputación bastante sangrienta. Pueden irse, nosotros regresaremos a la mansión.}
{266}{}{Buena idea, Sr. Alcalde...}
{267}{}{Pero eso no tiene sentido. Ya se van de la ciudad.}
{268}{}{Tienes una increíble capacidad para persuadir a los demás. Diría que hasta es sospechoso. Bueno, los dejaré ir. Nosotros regresaremos a la mansión.}
{269}{}{Buena idea, Sr. Alcalde...}
{270}{}{Ya está despejado...}
{271}{}{No cuentes conmigo, no quiero derramar sangre.}
{272}{}{Los forajidos no se irán a ningún lado, a no ser que les pagues.}
{273}{}{Ya no tenemos otra opción. Hay que eliminarlos a todos. ¿Puedes sacar a mi hija de ahí sin que te vean?}
{274}{}{Dame tiempo, intentaré rescatarla sin que lo noten.}
{275}{}{Eso es imposible. ¡Propongo que ataquemos de inmediato!}
{276}{}{No se preocupe, Don. Los forajidos ya están muertos.}
{277}{}{¡Eso es sorprendente! Tú sí que sabes resolver problemas.}
{1277}{}{¡Eso es sorprendente! Tú sí que sabes resolver problemas.}
{278}{}{Estás de suerte.}

{280}{}{}
{281}{}{[Escúchalos a escondidas]}
{282}{}{Bustos: John, ¿qué está pasando?}
{283}{}{[Escucha]}
{284}{}{Sullivan: Me han dicho que son cuatro. Tienen a tu hija de rehén, todavía no sabemos qué quieren. Debemos enviar a alguien a negociar con ellos.}
{285}{}{[Escucha]}
{286}{}{Bustos: Demonios... Sabían perfectamente a quién raptar y cómo hacerlo... Maldita sea, si otros bandidos se enteran de esto, volverá a ocurrir.}
{287}{}{[Escucha]}
{288}{}{Sullivan: Deberías haberla vigilado. Eres el alcalde de la ciudad y ni siquiera puedes cuidar a tu propia hija.}
{289}{}{[Escucha]}
{290}{}{Bustos: ¡Cierra la boca, John! Más te vale que averigües cómo rescatar a mi niña.}
{291}{}{[Escucha]}
{292}{}{Sullivan: No me hables así, Bustos. No te gustará recordar este momento mientras te matas bebiendo tequila. Ve preparando chapas, habrá que pagar el rescate. Apresúrate... (se dan cuenta de tu presencia) ¿Eh? ¿Qué quieres?}
{293}{}{¿Qué está pasando aquí?}

