{100}{}{Ves al líder de la banda.}
{101}{}{Ves a uno de los forajidos. Parece ser que es el jefe.}
{102}{}{Ya nos vamos, dile al alcalde que 'lo sentimos'.}

{200}{}{Tienes agallas para venir a hablarnos. Debes ser valiente, o muy estúpido. ¿Quién mierda eres?}
{1200}{}{El Don es tan patético que manda a una mujer a hacer su trabajo. ¿Quién mierda eres?}
{201}{}{Soy lo último que verás.}
{202}{}{No importa quien soy. El alcalde me envió para que hablara contigo.}
{203}{}{Justo lo que pensaba, Bustos es un cobarde. Siempre está listo para sacrificar a alguien más. Veamos si puede hacerle eso a su hija.}
{204}{}{El alcalde te exige que dejes ir a su hija. Si no, estás muerto.}
{205}{}{No podemos confiar en Bustos, es peor que una víbora. Dile que si no nos entrega lo que buscamos, mataremos a su hija.}
{206}{}{¿Qué es lo que quieres?}
{207}{}{Al diablo, charlar no sirve de nada. Mereces morir.}
{208}{}{Diez mil chapas.}
{209}{}{¿Diez mil? Ni siquiera el pueblo entero sería capaz de pagar eso.}
{210}{}{No es mi problema. Si no nos paga, puede terminar como su hija.}
{211}{}{Le diré lo que quieres.}
{212}{}{¿Cuál es tu problema?}
{213}{}{No eres de aquí, ¿cierto? Si fuera así, te reconocería.}
{1213}{}{No eres de aquí, ¿cierto? Si fuera así, te reconocería.}
{214}{}{¿Por qué te importa?}
{215}{}{No me importan las chapas. En el este de la ciudad hay un viejo cementerio, es una fosa común. Allí es donde va a descansar la gente de Casa Grande, incluyendo a mis padres.}
{216}{}{[Escúchalo]}
{217}{}{Ellos querían vivir en paz, trabajaron tan duro como pudieron en la bomba de agua y en la ciudad. Después llegó Bustos, los mató, y se apoderó del pueblo. Mató a cualquiera que estuviera contra él.}
{218}{}{¿Entonces quieres vengarte?}
{219}{}{Sí, ¿por qué mentiría? Sólo cuéntale al alcalde lo que acabo de decirte. Pero dudo que escuche.}
{220}{}{Le diré al alcalde lo que quieres.}
{221}{}{Mientes. Te mataré, así aprenderán los demás...}
{222}{}{Esto es el pueblo de tus padres, ¿quieres derramar aún más sangre sobre él?}
{223}{}{Suficiente. Trae al alcalde, solo hablaré con él.}
{224}{}{La ciudad está manchada con sangre, por fin tiene algo de paz.}
{225}{}{No quiero seguir escuchándote, te voy a matar...}
{226}{}{¿Acaso crees que por eso soy un egoísta? ¿Cómo voy a sobrevivir después de que el alcalde me echó de mi propio pueblo? Tengo que comer basura y robar caravanas para sobrevivir, es todo culpa de ese bastardo.}
{227}{}{Entonces abandona esta vida. Puedes vivir en Fénix o en otro lado.}
{228}{}{Es demasiado tarde, no puedo empezar de nuevo. Pero me conmueves, dejaré ir a la niña, es inocente. Pero si a ese imbécil le queda un poquito de dignidad, que tenga un duelo conmigo, a la vieja usanza.}
{229}{}{Me alegra que hayas sido razonable.}
{1229}{}{Me alegra que hayas sido razonable.}
{230}{}{¿Qué dijo el alcalde?}
{231}{}{Le colocó un precio a tu cabeza, y yo quiero ese premio.}
{232}{}{Nada ha cambiado. Dijo que podrás irte si dejas ir a la chica.}
{233}{}{¿Qué es esta mierda? ¿Acaso crees que me engañará un disfraz?}
{234}{}{Es que, yo...}
{235}{}{Te dará mil chapas si te largas de aquí. Si no, estás muerto.}
{236}{}{Esto es sorprendente, ni siquiera es capaz de hacer eso por su propia hija...}
{237}{}{[Más]}
{238}{}{(Uno de los saqueadores interrumpe a su líder y tienen una discusión) Ah... carajo.. tienes razón... (te mira) Acepto. Dame las chapas y puedes llevarte a la chica.}
{239}{}{¿Por qué el Don pierde el tiempo contigo? Mejor te mato y me quedo con las chapas...}
{240}{}{Espérame, iré por ellas.}
{241}{}{Toma, aquí tienes.}
{242}{}{Dile al Don que nos vamos, y que ni se atreva a perseguirnos.}
{243}{}{Son demasiadas chapas, no puedo dejar que te las lleves. Las tomaré de tu cadáver.}
{244}{}{El Don nunca haría eso. Creo.}
