{100}{}{Ves a Christina.}
{101}{}{Ves a la hija de Don Bustos.}
{102}{}{Si los forajidos nos ven, lo más seguro es que nos disparen.}
{103}{}{Estoy tan feliz de que se haya acabado.}
{104}{}{*Llora*}

#First dialogue
{200}{}{¡Aléjate de mí, maldito forajido!}
{1200}{}{¡No te me acerques, maldita saqueadora!}
{201}{}{Cálmate, tu padre me envió.}
{202}{}{¿Mi... papá? Papi... Vámonos de aquí, rápido.}
{203}{}{Déjame desatarte... Salgamos de aquí, en silencio.}
{204}{}{No podemos dejar que nos vean. Si los bandidos nos ven, nos van a disparar.}
{205}{}{Bien, vámonos.}
{206}{}{No es el momento. Espérame aquí.}
{207}{}{¿Qué? ¿Te vas? ¡Quítame estas cuerdas!}
{208}{}{Se paciente, ya vengo.}
{209}{}{Vamos, ya podemos irnos.}

#Re-dialogue
{210}{}{Hola.}
{211}{}{Adiós.}
{212}{}{Ya eres libre, pude negociar con saqueadores.}
{213}{}{¿En serio? Entonces salgamos de aquí, antes de que cambien de parecer.}
{214}{}{Vámonos de una vez.}
