{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia de caravana, está descansando luego de un largo viaje.}

{110}{}{Hola. ¿Qué tal te trata la vida?}
{111}{}{Lo siento, pero necesito descansar.}
{112}{}{Al menos tienen agua acá. Pero el resto de la ciudad es una mierda.}
{113}{}{En Casa Grande son muy agresivos.}
{114}{}{El alcalde está loco, ¿no crees?}
{115}{}{Deberías hablar con el jefe.}
{116}{}{El camino entre Fénix y Two-Sun es una maldita locura.}
{117}{}{La carretera es peligrosa, gracias a los saqueadores.}
{118}{}{Es mejor que evites a los forajidos.}
{119}{}{Los lugareños solo nos ven como alcancías.}
