{100}{}{Ves a un mercader.}
{101}{}{Estás viendo al gerente de la caravana.}
{102}{}{Había oído hablar de estas armaduras, pero pensé que eran una leyenda.}

{200}{}{Buenas, viajero. He estado dirigiendo a mi caravana por unos meses, así que podría decirse que conozco bien el yermo. ¿Quieres algún consejo?}
{1200}{}{Buenas, viajera. He estado dirigiendo a mi caravana por unos meses, así que podría decirse que conozco bien el yermo. ¿Quieres algún consejo?}
{201}{}{¿Qué consejo me daría un idiota como tú? Estoy perdiendo el tiempo.}
{202}{}{Sí, un consejo me vendría bien.}

{210}{}{¿Te ayudo en alguna cosilla?}
{211}{}{En nada, estoy bien. Adiós.}

#Questions
{220}{}{Háblame sobre esta ciudad.}
{221}{}{Casa Grande es la única parada entre Two-Sun y Fénix, las caravanas hacen una parada aquí para abastecerse de agua limpia y descansar un poco. Pero además de eso, este sitio es un vertedero.}
{222}{}{Esta ciudad es un desastre, ¿por qué?}
{223}{}{¿Quién demonios podría explicarlo? Los caravaneros traemos un montón de chapas, pero los ciudadanos ni pueden permitirse lo más básico. Los forajidos son parte del problema, pero hay algo que no me cuadra.}
{224}{}{Sí, parece un vertedero.}
{225}{}{Bueno, tampoco deberíamos juzgarlos tanto. Esta gente sólo intenta sobrevivir, igual que todos los demás.}
{226}{}{Quiero saber más.}
{227}{}{Tras las rejas hay unos contenedores, ¿qué son?}
{228}{}{Esa es la bomba de agua, lo único que mantiene a esta ciudad con vida. La ciudad se quedaría desolada si no estuviera allí.}
{229}{}{}

{230}{}{¿Quién está a cargo de la ciudad?}
{231}{}{Técnicamente, el alcalde es Don Bustos. Pero para serte honesto, no sé qué es lo que hace exactamente, pero nadie se atreve a hacer algo si no da su aprobación.}
{232}{}{John Sullivan llegó al poder, después de la muerte del Don. Quizás él mismo se declaró como jefe, quién sabe.}
{233}{}{No sabría decirte, desde que el Don y el dueño de la bomba estiraron la pata, no hay nadie que quiera hacerse cargo.}
{234}{}{Comprendo. Tengo otra duda.}
{235}{}{¿En dónde puedo encontrar al alcalde?}
{236}{}{Su mansión está más allá, en la calle principal. Si vas a hablar con él, guarda tu arma y no hagas ninguna locura. Sus guardaespaldas no son para nada amistosos.}
{237}{}{Puede que luego le de una visita. Por el momento, sigamos hablando.}
{238}{}{Iré a hablar con él de inmediato, nos vemos.}
{239}{}{}

{240}{}{¿Qué hay de nuevo en Casa Grande?}
{241}{}{No hay mucho, es la misma mierda de siempre que ves por todo el yermo.}
{242}{}{Comprendo.}
{243}{}{Alguien hizo un desastre en el cementerio, el alcalde se molestó y ofrece una recompensa por el culpable. ¿Quién haría algo así?}
{244}{}{¿Alguna otra noticia que contarme?}
{245}{}{El otro día, vi un enjambre de escorpiones en el sur de la ciudad. Lleva antídoto, si vas a andar por allá.}
{246}{}{¿Qué otra cosa puedes contarme?}
{247}{}{Se dice que los forajidos mataron al Don, nadie quiere hablar de los detalles.}
{248}{}{¿Qué más?}
{249}{}{He oído que Don Bustos se la pasa borracho todo el día en su mansión. Ese bastardo está perdiendo la cabeza, el tequila no lo ayudará.}
{250}{}{¿Qué otra cosa puedes contarme?}
{251}{}{La casa de baños ha vuelto a funcionar, por fin. Estar limpio se siente genial, ¿lo has intentado?}
{252}{}{Eso es... interesante. ¿Algo más?}
{253}{}{Solía haber una casa de baños por allá, pero fue clausurada, nadie sabe qué le pasó al dueño. Y yo aquí, queriendo bañarme.}
{254}{}{¿Alguna noticia que darme?}
{255}{}{Toda la ciudad está hablando sobre los rehenes en el bar, seguro que sabes más que yo acerca de eso.}
{256}{}{La bomba de agua ha subido sus precios debido a la caída de los Hojalateros. Esta ruta cada vez empeora más y más.}
{257}{}{Eso es útil. ¿Qué más?}
{258}{}{Los Escudos Azules han dejado de atacar a las caravanas, nadie sabe por qué lo hacen, pero la carretera es más segura.}
{259}{}{Sí que es bueno oír eso.}

{260}{}{¿Cómo podría ganar chapas en esta ciudad?}
{261}{}{No eres de aquí, por lo que comerciar es tu mejor opción. Aunque, puede que el alcalde te ofrezca un trabajo, si le caes bien.}
{262}{}{Lo tendré en cuenta.}
{263}{}{Eso es todo lo que tenía que decirte.}
{264}{}{Vale.}

#Shipping to Phoenix
{300}{}{¿Hacia dónde va tu caravana?}
{301}{}{Vamos a ir a Fénix, ya pronto vamos a volver.}
{302}{}{Ojalá les vaya bien en el viaje, ¿te puedo hacer unas dudas, antes de que partan?}
{303}{}{Tengo que ir a la gran ciudad, ¿puedo ir contigo?}
{304}{}{Perdona, pero no tengo más espacio. No nos hace falta un bulto más.}
{305}{}{Puedo pagarte.}
{306}{}{Lo entiendo. ¿Podrías responderme unas preguntas, al menos?}
{307}{}{Sin ofender, pero no te conozco y no me voy a arriesgar. La carretera es muy peligrosa.}
{308}{}{Lo entiendo, no te preocupes.}
{309}{}{Si te encuentro allá afuera, no olvidaré esto.}
{310}{}{Vale. Estoy dispuesto a tolerar la carga que llevas a cambio de }
{311}{}{ chapas. Pero tampoco lleves tanto - no tenemos otro brahmán que pueda llevar tus cosas.}
{312}{}{No puedo permitirme eso, supongo que iré por cuenta propia. Nos vemos.}
{313}{}{En este momento, lo que más me importa son tus respuestas a mis preguntas.}
{314}{}{Claro, aquí está el dinero.}
{1314}{}{Claro, aquí está el dinero.}
{315}{}{¿Quién crees que llevará todo eso? Trae 50 libras, o menos.}
{316}{}{De acuerdo.}
{317}{}{No trabajo gratis.}
{318}{}{Por supuesto...}
{319}{}{Estarás a salvo junto a mi caravana.}
{320}{}{[Espera a que la caravana empiece el viaje]}
{321}{}{No será un problema, te lo prometo.}
{322}{}{Ya lo veremos, porque cualquier cosa puede ocurrir allá afuera.}
{323}{}{Eso es cierto...}
{324}{}{Si llega a ser un problema, puedes dejarme por mi cuenta en el yermo con todas mis cosas.}
{325}{}{Eso me basta. Pero, yo no trabajo gratis.}
{326}{}{Claro...}
{327}{}{Entonces, trato hecho.}
{328}{}{Vale.}
{329}{}{Puedo darte }
{330}{}{ chapas por el peso.}
