{100}{}{Ves a un ciudadano.}
{101}{}{Ves a un ciudadano de Casa Grande. Está afiebrado y tembloroso.}
{102}{}{Ves a un ciudadano de Casa Grande.}
{103}{}{Tuviste éxito tratando al paciente.}
{104}{}{Este hombre fue envenenado por un escorpión. No tienes la habilidad suficiente para ayudarlo, necesitas un antídoto.}

{110}{}{*Gah*}
{111}{}{El veneno de los malditos escorpiones me tiene así.}
{112}{}{Me picó uno de los insectos en las afueras del pueblo.}

{115}{}{Gracias, ya me siento bien.}
{116}{}{Uno de los escorpiones me picó en las afueras del pueblo.}
{117}{}{Y yo que no le tenía estima a los doctores...}
{118}{}{Muchas gracias, Doc. Los escorpiones están muy agresivos estos días. Toma unos cartuchos de escopeta, espero te sean de ayuda.}

{120}{}{Oh...}
{121}{}{*Cof cof*}
{122}{}{*¡ACK!*}
{123}{}{Agh...}
{124}{}{*Gruñido*}
{125}{}{Hrr...}
