{100}{}{Ves a una ciudadana de Casa Grande.}
{101}{}{Ves a una de las habitantes de Casa Grande.}
{102}{}{Le contaré a los demás que me salvaste. Gracias.}
{103}{}{Esos escorpiones aparecieron de la nada. Mantente alerta.}
{104}{}{Puede que los forajidos estén aquí cerca, abre bien los ojos.}

{110}{}{¡Ayuda!}
{111}{}{¡Por favor, ayúdenme!}
{112}{}{Jodidos bichos, ¡piérdanse!}
{113}{}{¡Váyanse, malditos escorpiones!}
{114}{}{¡No me atraparán, malditas pestes!}
{115}{}{Tendré que esperar a que se vayan.}
{116}{}{Me pregunto si siquiera me están buscando.}
{117}{}{¿Alguien me escucha?}
{118}{}{¡Estoy atrapada, ayuda!}
{119}{}{¡Ayuda!}

{120}{}{¡Ayuda!}
{121}{}{¡Por favor, ayúdenme!}
{122}{}{¡Estoy aquí!}
{123}{}{Me encerraron los forajidos.}
{124}{}{Me muero de hambre.}
{125}{}{¿Será que me rescatarán?}
{126}{}{¿Siquiera me estarán buscando?}
{127}{}{¿Hola? ¿Me escuchan?}
{128}{}{¡Estoy atrapada, ayuda!}
{129}{}{¡Por favor, sálvenme!}

{200}{}{Por fin, pensé que jamás me encontrarían.}
{201}{}{¿Qué estás haciendo aquí?}
{202}{}{Me escondo de los escorpiones, obvio. Estaba atrapando iguanas, pero casi me atrapan a mí. Tuve suerte de entrar aquí a tiempo.}
{203}{}{¿Hace cuánto que estás aquí dentro?}
{204}{}{Ni siquiera lo recuerdo. Los escorpiones son muy pacientes, pueden esperarte bajo el sol durante muchos días. Pensé que me iba a morir de hambre.}
{205}{}{¿Quieres volver al pueblo?}
{206}{}{Por supuesto, ¿puedo salir? Si es así, te sigo.}
{207}{}{Quédate ahí, primero voy a lidiar con ellos.}
{208}{}{Claro, vámonos. Probablemente te están buscando.}
{209}{}{Sí, claro... (se asoma con cuidado) Tú primero.}
{210}{}{De acuerdo}
{211}{}{Te sigo.}
{212}{}{Esto no es lo que merece. Soy un asaltante, no tu salvador. Dame lo que tengas.}
{1212}{}{Esto no es lo que merece. Soy una asaltante, no tu salvadora. Dame lo que tengas.}
{213}{}{Por favor, déjame, ¡no tengo nada!}
{214}{}{Eso pensé.}
{215}{}{Olvídalo, mejor ni me molesto.}
{216}{}{¿Qué hay allá afuera? ¿Puedo salir?}
{217}{}{No, todavía hay escorpiones. Escóndete, ya vengo.}

{300}{}{¡Sí! Pensé que nadie vendría.}
{301}{}{¿Quién te encerró aquí?}
{302}{}{Los forajidos, creo que los Escudos Azules. Me atraparon en el desierto, porque pensaron que alertaría a los demás. Pero en vez de matarme, me dejaron aquí.}
{303}{}{¿Sabes qué pasó con ellos?}
{304}{}{Sí, planean algo muy grande. El ataque a la caravana sólo era una distracción. Dejaron casi todo atrás, excepto las armas.}
{305}{}{Tenemos que alertar al alcalde, vámonos al pueblo.}
{306}{}{Puede que los forajidos sigan allá afuera, quédate ahí.}
{307}{}{¿Qué está pasando? ¿Ya puedo salir?}
{308}{}{Vámonos, tenemos que decirle al Don lo que pasó.}
{309}{}{Todavía es peligroso, es mejor que me esperes ahí.}
