{100}{}{Ves a Gil McCord.}
{101}{}{Ves a un hombre desafeitado y enjuto de mirada penetrante. Te observa con cuidado debajo de su gorro de vaquero.}
{102}{}{¿Sigues ahí? Parece que no sientes miedo.}

{200}{}{Vaya, un ejecutor de ejecutores. No te preocupes, sé todo sobre ti. Debería haberte eliminado cuando cobraste a tu primer Pancho. Parece que subestimé tu calibre.}
{201}{}{Estoy lleno de sorpresas, McCord.}
{1201}{}{Estoy llena de sorpresas, McCord.}
{202}{}{Entonces muéstrame de lo que eres capaz, porque sólo uno de nosotros saldrá de esta.}
{203}{}{No quiero pelear contigo.}
{204}{}{Créeme, ese vas a ser tú.}
{205}{}{Parece que eres uno de esos tontos que nunca aprenden. No existe ni el bien ni el mal. Le muestras piedad a alguien, y te disparan por la espalda. Es la ley del yermo.}
{206}{}{Menudo discurso. Ya hablamos lo suficiente. Le llevaré tu cabeza a Bruce Turner.}
{207}{}{Dejemos esto de lado, no es necesario derramar sangre.}
{208}{}{¿Para que me metas una navaja por la espalda? De ninguna manera.}
{209}{}{[Espera su ataque]}
{210}{}{Entonces hagamos esto como vaqueros - un duelo.}
{211}{}{Está claro que tienes agallas. Acepto.}
{212}{}{[Párate en medio del camino y prepárate para el duelo]}
{213}{}{No quiero matar más gente, me pesa la consciencia.}
{214}{}{¿De qué estás hablando? Le arrancaste la cabeza a tres personas en sangre fría, y quién sabe a cuántas más. Las arrastraste durante millas, saboreando la sangre. ¿Y ahora me vienes con eso de que no quieres matar? Guárdate eso, porque yo no te creo.}
{1214}{}{¿De qué estás hablando? Le arrancaste la cabeza a tres personas en sangre fría, y quién sabe a cuántas más. Las arrastraste durante millas, saboreando la sangre. ¿Y ahora me vienes con eso de que no quieres matar? Guárdate eso, porque yo no te creo.}
{215}{}{Eso no fue lo que pasó. Hicieron todo el trabajo sucio por mí.}
{216}{}{(Toma una pausa, y sonríe) ¡Ja! Justo lo que pensaba, eres un charlatán. Ahora vete, no me hagas perder más tiempo.}
{1216}{}{(Toma una pausa, y sonríe) ¡Ja! Justo lo que pensaba, eres una charlatana. Ahora vete, no me hagas perder más tiempo.}
{217}{}{Cometiste un error, porque no me das miedo...}
{218}{}{Tienes razón, mejor me voy.}
