{100}{}{Ves a un ranger.}
{101}{}{Estás viendo a un hombre con una armadura de cuero.}
{102}{}{No tenemos nada de qué hablar.}

{200}{}{Vaya, vaya, ¿qué tenemos aquí? }
{201}{}{No puede ser...}
{202}{}{¿Qué estás haciendo, idiota?}
{1202}{}{¿Qué hace una señorita como usted en un cementerio?}
{203}{}{No es asunto tuyo, así que no preguntes.}
{204}{}{Sí que es asunto mío. Es una pena que los canallas como tú se dediquen a molestar a la gente de bien.}
{205}{}{[Más]}
{206}{}{(desenfunda su arma) Por la autoridad que me concede el Departamento de Rangers de Arizona y la Constitución, te condeno... a la pena de muerte. Serás ejecutado de inmediato.}
{207}{}{Pero qué...}
{208}{}{¡Vete al carajo!}
{209}{}{¡Espera! Los Hojalateros me pidieron que haga esto, buscan a uno de los suyos, me parece que está enterrado aquí.}

{210}{}{Estoy robando.}
{211}{}{¿Cómo se te ocurre robarle a un muertos? ¿No pensaste en que podrías hacer enojar a alguien?}
{212}{}{No me importa. ¿Ahora qué? ¿Acaso me detendrás?}
{213}{}{Ya están muertos, no necesitan sus cosas.}
{214}{}{Quizás, pero eso no lo decides tú. Y puedo condenarte por un crimen así, está en mi poder.}
{215}{}{¿Quién eres?}
{216}{}{Sí, señor. Confieso que soy culpable.}
{217}{}{No me vengas con eso, reconozco a un estafador cuando lo veo.}
{1217}{}{No me venga con eso, señorita. Reconozco a una estafadora cuando la veo.}
{218}{}{¿Quién eres?}
{219}{}{Estás equivocado, a los hermanos de este hombre no les importará. ¿Sabes por qué?}

{220}{}{Soy un ranger. ¿Y tú quién eres? ¿Por qué entrarías a una ciudad para comportarte así?}
{221}{}{Los Hojalateros están buscando a uno de los suyos, y parece que sabes lo que le ocurrió.}
{222}{}{¿Y quién eres tú?}
{223}{}{No es asunto tuyo.}

{230}{}{No, no, mire, esto es un malentendido. Permítame explicarlo.}
{231}{}{Te escucho.}
{232}{}{Verá, estoy buscando a... [Atácalo]}
{233}{}{No es asunto tuyo. No tengo por qué decírtelo.}
{234}{}{Me lo pidieron los Hojalateros, buscan a su hermano. Está enterrado aquí.}

{240}{}{Lo sé. Yo lo maté.}
{241}{}{¿Por qué? ¿Por qué matarías a un Hojalatero?}
{242}{}{Todos los Hojalateros merecen morir así. Se creen dioses, como si nada estuviera fuera de su alcance. Aplastan a los demás, quitándoles la tecnología que posean y los obligan a trabajar. Su poder pone en peligro cualquier esperanza que haya para ejercer la justicia en el sur de Arizona. Además, su existencia está ligada a la tecnología, lo cuál es inhumano. Para mí, es la única razón que necesito.}
{243}{}{[Más]}
{244}{}{¿Por qué trabajas para ellos? ¿Acaso te pagan bien?}
{245}{}{Quizás. Mientras me paguen, estoy dispuesto a hacer lo que sea. No me importa ni Arizona ni la justicia.}
{1245}{}{Quizás. Mientras me paguen, estoy dispuesta a hacer lo que sea. No me importa ni Arizona ni la justicia.}
{246}{}{Comprendo. Son un peligro para todo el yermo, y si trabajas para ellos, tú también lo eres.}
{1246}{}{Son un peligro para todo el yermo, y si trabajas para ellos, tú también lo eres.}
{247}{}{[Más]}
{248}{}{No tienes que hacer esto. Por favor.}
{249}{}{Oh, mierda...}
{250}{}{Al menos dices la verdad. Dame una razón por la cuál debería dejarte vivir.}
{251}{}{(desenfunda un arma) Aquí tengo seis razones. Déjame mostrarte...}
{1251}{}{(desenfunda un arma) Aquí tengo seis razones. Déjame mostrarte...}
{252}{}{Oh, mierda...}
{253}{}{No, no lo hagas...}
{254}{}{Estoy con los rangers, estoy en una misión. Se me ordenó infiltrarme dentro de los Hojalateros para descubrir sus debilidades.}
{255}{}{Hmm, no me esperaba esto. Me alegra ver a uno de los nuestros. En ese caso, no tengo más preguntas. Hagamos que esto nunca ocurrió.}
{256}{}{Claro, nadie vio nada.}
{257}{}{Déjame llevarme su cadáver, al menos merecen ese respeto.}
{258}{}{No. No puedo permitir que sigas trabajando para esos bastardos.}
{259}{}{[Más]}
{260}{}{Puede que los odies, pero eres un ranger, deberías respetar a un oponente tan formidable. Déjame llevarles el cadáver.}
{261}{}{Hmm, puede que tengas razón. Sigue haciéndoles el trabajo sucio, pero diles que no nos arrodillaremos ante ellos.}
{1261}{}{Hmm, puede que tengas razón. Sigue haciéndoles el trabajo sucio, pero diles que no nos arrodillaremos ante ellos.}
{262}{}{Como usted diga, señor.}
{263}{}{Entonces déjame en paz.}
{264}{}{Señor, no tengo ningún problema con usted, simplemente hago esto por un contrato.}
{265}{}{Sigue haciéndoles el trabajo sucio, pero diles que a diferencia de ti, no nos arrodillaremos ante ellos.}
{1265}{}{Sigue haciéndoles el trabajo sucio, pero diles que a diferencia de ti, no nos arrodillaremos ante ellos.}
{266}{}{Tengo un contrato con ellos, ¿hay algún problema?}
