{100}{}{Ves a un forajido.}
{101}{}{Ves a un hombre rudo con armadura hecha a partir de señales de tráfico.}
{102}{}{Muévete, forastero.}

{200}{}{¡Tú! ¿Qué crees que estás haciendo?}
{201}{}{Pensé que aquí no habría nadie. ¿Hay algún problema?}
{202}{}{Sí, y es uno grande. Estás en *nuestro* territorio, husmeando en *nuestro* almacén.}
{203}{}{¿Y cómo iba a saber eso? Podrían colocar un aviso.}
{204}{}{¿Estás ciego? ¿No sabes leer? Ah, ¿me estás tomando el pelo? Grave error, pendejo.}

{210}{}{No es asunto tuyo.}
{211}{}{Claro que es asunto mío, este lugar es NUESTRO.}
{212}{}{¿En serio? Deberían poner un aviso en la puerta o algo así.}
{213}{}{Mala suerte, entonces.}
{214}{}{Eres un cabo suelto, no puedo dejar que hables.}
{215}{}{Eso suena muy mal...}
{216}{}{Necesitas una buena golpiza, y también un baño.}

{220}{}{Parece que somos del mismo clan. No es necesario que peleemos.}
{221}{}{¡Un Escudo Azul! ¿Vienes de la base? Hace rato que no voy. ¿Qué hay de nuevo?}
{222}{}{Todo anda bien, el clan está a salvo y ganamos nuestra independencia.}
{223}{}{Sí, escuché de eso. Quizás me pase por allá un día de estos. Ten un buen viaje, hermano. Que el polvo cubra tus pisadas.}
{1223}{}{Sí, escuché de eso. Quizás me pase por allá un día de estos. Ten un buen viaje, hermana. Que el polvo cubra tus pisadas.}
{224}{}{Lo mismo digo, ten un buen viaje.}

{230}{}{Solo quería buscar entre la basura. Por favor, no me hagas daño.}
{231}{}{Entonces tienes que ser de por aquí, todos saben que husmear por aquí es una mala idea, ¿acaso eres nuevo? Te dejaré ir, pero si te vuelvo a ver, estás muerto.}
{1231}{}{Entonces tienes que ser de por aquí, todos saben que husmear por aquí es una mala idea, ¿acaso eres nuevo? Te dejaré ir, pero si te vuelvo a ver, estás muerta, perra.}
{232}{}{Está bien, lo que tú digas.}
{233}{}{Solo estoy echando un ojo, ¿qué tiene de malo?}
{234}{}{Lo malo es que no nos gustan los intrusos. Estás en nuestro territorio. Tendré que darte una paliza.}
{235}{}{¿Tu territorio? Sí, claro...}
