{100}{}{Ves a John Sullivan.}
{101}{}{Estás viendo a un hombre que se hace respetar. Se ve limpio y bien cuidado.}
{102}{}{No vas a pasearte por nuestra ciudad con esa cosa, ¿no?}
{103}{}{¿Acaso quieres morir? Sal de nuestra ciudad, maldito forajido.}

#Before repair
{200}{}{Hola, forastero. No me gusta que un desconocido se ande paseando por mi propiedad.}
{1200}{}{Ah, una señorita, es raro encontrarlas por aquí. Aunque no me suele gustar que una desconocida se ande paseando por mi propiedad.}
{201}{}{¿Esta bomba de agua es tuya? ¿Te pertenece?}
{202}{}{Es mía y sí, me pertenece. Soy John Sullivan, soy el dueño de la bomba entera. ¿Vienes a hacer negocios conmigo? Si no, sal de aquí. Tengo que arreglar este filtro, no hay tiempo para hablar con desconocidos.}
{203}{}{Perdón, no quería molestarte. Ya me voy.}
{204}{}{No soy de por aquí. ¿Te puedo hacer unas preguntas sobre la ciudad?}
{205}{}{¿Acaso no me escuchas? NO TENGO TIEMPO PARA HABLARTE.}
{206}{}{Ah, pues ya me voy.}
{207}{}{¿A quién debería hablarle acerca de la ciudad?}
{208}{}{Al viejo Bustos, llegarás a su mansión si bajas por la calle de allá.}
{209}{}{Gracias, adiós.}
{210}{}{¿Por qué no la reparas?}
{211}{}{¿En serio no hay nadie más que sea capaz de arreglar esta cosa?}
{212}{}{Los Hojalateros nos cobran un ojo de la cara por cualquier tipo de servicio. Ellos saben que el agua es un negocio rentable, pero no podemos entregarles lo que nos piden. Y aparte de los Hojalateros no hay nadie más que pueda hacer un trabajo así. Son los únicos con la maquinaria y las habilidades.}
{213}{}{Ah, lo siento, entonces no molesto.}
{214}{}{¿Y crees que lo podrás reparar por ti mismo?}
{215}{}{A veces funciona. Es uno de los filtros, es sólo que está atascado con tierra... o algo más.}
{216}{}{Puedo arreglarlo.}
{217}{}{¿De verdad? Si arreglas el filtro, te pagaré. Menos que los Hojalateros, por supuesto. Pero al final, todos ganamos.}
{218}{}{Bien... Esto llevará un rato.}
{219}{}{Hmm, esta tecnología es demasiado complicada para mí. Me temo que no soy capaz de arreglarla.}
{220}{}{¿Tú otra vez? ¿Y ahora qué quieres?}
{221}{}{Eh, nada.}
{222}{}{Respecto a la bomba. ¿Por qué no la puedes reparar?}
{223}{}{El filtro está bien. Algunas partes fueron estropeadas por la tierra y la arena, pero conseguí repararlas.}
{224}{}{Me gusta la eficiencia. Toma, te doy estas 200 chapas por tu trabajo.}
{225}{}{Gracias.}
{226}{}{Eso no es suficiente}
{227}{}{Es mucho. Si hubiera sabido que querías más, no te habría dado el trabajo.}
{228}{}{Eres un tacaño.}
{229}{}{Gracias, de todas formas.}
{230}{}{Esto apenas cubre el costo de los reemplazos.}
{231}{}{Está bien, te daré otras 50 chapas. Pero no me pidas más.}
{232}{}{Eres un tacaño.}
{233}{}{Eso me basta, gracias.}

{234}{}{Estoy buscando a un Hojalatero. ¿Ha habido alguno aquí recientemente?}
{235}{}{Sí, él estuvo aquí. Revisó la bomba, hablamos de unos arreglos menores y fue a ver al alcalde. No lo he visto desde ese entonces.}
{236}{}{Gracias, iré a hablar con el alcalde.}
{237}{}{De hecho, estoy rastreando a algunos esclavos que llevaron a Two-Sun.}
{238}{}{Entonces anda a Two-Sun. ¿Por qué me preguntas? Sólo atendemos a las caravanas y dejamos que sigan con su camino. Es parte del negocio, eso es todo.}
{239}{}{Que excusa tan conveniente.}
{240}{}{Tiene sentido.}

{241}{}{¿Qué clase de desacuerdo tuviste con el alcalde?}
{242}{}{Ese viejo tirano fue ablandado por el tiempo y su hija. Ha perdido su toque y ya no tiene el derecho de estar mandándome. Antes tenía que conformarme con el papel de gerente. Pero ahora es mi turno de vivir bien.}
{243}{}{Supongo que sí, al menos por ahora.}
{244}{}{Encuentra a alguien más con quien conversar. Yo no tengo el tiempo ni el interés.}
{245}{}{Bueno, entonces no te molesto.}

#After repair
{250}{}{Ahora podemos hablar un poco. ¿Qué necesitas?}
{251}{}{Nada en particular. Adiós.}

{260}{}{¿Todo esto es una bomba de agua? Es impresionante.}
{261}{}{Sí, tiene más de un siglo. Sólo debemos mantener a las máquinas en buen estado.}
{262}{}{¿Para qué almacenan tanta agua?}
{263}{}{Tengo que irme. Ahí nos vemos.}
{264}{}{Espera, tengo una pregunta más.}
{265}{}{¿Por qué no? Todos necesitan agua, y en el desierto, contar con ella es vida o muerte. Para mí es una buena forma de ganar chapas y además la bomba abastece a la ciudad entera.}
{266}{}{¿No se supone que tú controlas la bomba?}
{267}{}{El agua atrae a las caravanas, lo que significa más negocio para la ciudad. Además, el alcalde también se lleva su tajada de las chapas. Hay que mantenerlo contento.}
{268}{}{Y eso no te gusta, ¿verdad?}
{269}{}{Alguien tiene que hacerse cargo del papeleo y las negociaciones, pero yo preferiría estar arreglando cosas. Lo único que deseo es que Alfred sea más firme con sus clientes, siempre estamos saltando de comprador a comprador.}
{270}{}{Bueno, retrocedamos un poco.}
{271}{}{¿En dónde aprendiste tanto sobre la tecnología de la preguerra?}
{272}{}{Para ser sincero, los Hojalateros se encargan de los arreglos de verdad. Yo sólo me conozco algunos trucos por experiencia, pero los demás tipos de por aquí sólo deben presionar botones.}
{273}{}{No confías en ellos, ¿no?}
{274}{}{}
{275}{}{¿Qué tienen de especial los Hojalateros?}
{276}{}{Hemos sacrificado mucho para restaurar este lugar, ellos son y eran los únicos capaces de hacer algo así. Además, tienen un interés personal en las rutas comerciales.}
{277}{}{¿Sabías que esos tipos cayeron víctima a la tecnología que veneraban?}
{278}{}{Escuché sobre eso, no me molesta, pero... ¿Qué haremos cuando la bomba necesite un mantenimiento a fondo? No quiero ni pensarlo.}
{279}{}{Retrocedamos un poco.}
{280}{}{¿Quién está a cargo en este lugar?}
{281}{}{Yo mando por aquí.}
{282}{}{Interesante, así que tú eres con quien necesito hablarle.}
{283}{}{El alcalde y yo dirigimos las cosas juntos. Se llama Bustos; vive en una mansión grande, está bajando la calle.}
{284}{}{Háblame del alcalde. ¿Cómo es?}
{285}{}{Lo he conocido por mucho tiempo. Nos llevamos bien, pero a veces discutimos - especialmente sobre su hija. Siempre deja que se salga con la suya.}
{286}{}{¿Tiene una hija?}
{287}{}{Sí, es una niña agradable, pero es muy cabezota. No entiendo por qué Bustos es tan poco estricto con ella. Si fuera mía, ya la hubiera corregido hace mucho, con una correa.}
{288}{}{Ya veo. Hablemos de otra cosa.}
{289}{}{¿Cuál es tu opinión del alcalde?}
{290}{}{¿Qué, acaso quieres que hable mal de mi mejor amigo? Y de todas formas, ¿a ti qué te importa?}
{291}{}{Nada, nada. Sólo preguntaba.}
{292}{}{¿Hay algún trabajo que pueda hacer en la ciudad?}
{293}{}{Prueba a hablar con el alcalde. Ya no hay nada más que puedas hacer con la bomba.}
{294}{}{No lo creo, al menos en mi estación no tienes nada que hacer.}
{295}{}{Comprendo. Hablemos de otra cosa.}
{296}{}{Estoy perdiendo el tiempo en esta ciudad. Adiós.}
{297}{}{Lo único que tengo para ti es arreglar ese maldito filtro. ¿Se te da la tecnología?}
{298}{}{No, la verdad no es lo mío. Hablemos de otra cosa.}
{299}{}{Déjame ver, quizás pueda ayudar.}

{300}{}{Sé lo que pasó con el mercader. La pobreza lleva a la gente a hacer locuras.}
{301}{}{¿Me estás amenazando?}
{302}{}{Si sabes lo que te conviene, no dirás nada. Tenemos una reputación que mantener.}
{303}{}{No te preocupes. No vi nada, no escuché nada.}
{1303}{}{No te preocupes. No vi nada, no escuché nada.}
{304}{}{Bien pensado. Puede que tú y yo nos llevemos bien.}
{305}{}{Sí... por supuesto.}
{306}{}{No diré nada si me pagas.}
{307}{}{Cierra la maldita boca y no tendrás ningún problema. Así de simple.}
{308}{}{Ah, así que así estamos.}
{309}{}{Mi silencio no es gratis. Esta historia no se olvidará por sí misma. ¿Sabes?}
{310}{}{Sabes negociar. (te entrega 10 chapas) Pero cuidado con lo que dices. Si causas problemas, te arrepentirás.}
{311}{}{Te escucho fuerte y claro.}

