{100}{}{Ves a Don Reavis.}
{101}{}{Ves a un hombre con una hermosa barba negra y de apariencia noble.}

{198}{}{Agradezco tu ayuda con esos rebeldes, mi adalid metálico. Algún día sufrirán su tan merecido castigo.}
{199}{}{Agradezco tu ayuda con esos rebeldes, amigo mutante. Algún día sufrirán su tan merecido castigo.}
{200}{}{Agradezco tu ayuda con esos rebeldes, buen mozo. Algún día sufrirán su tan merecido castigo.}
{1200}{}{Agradezco tu ayuda con esos rebeldes, señorita. Algún día sufrirán su tan merecido castigo.}
{201}{}{¿Quién se supone que eres?}
{202}{}{Ayudo a quien lo necesite. ¿Pero quién es usted, y cómo molestó a esos campesinos?}
{203}{}{Soy el Don James Reavis, el heredero legítimo y Barón de toda Arizona. Este estado, bárbaramente robado a mis antepasados, será reclamado por su verdadero noble linaje.}
{204}{}{¿Lo dices en serio?}
{205}{}{¿Y cómo vas a probar eso?}
{206}{}{Poseo los documentos y una vieja lápida con los nombres de mis ancestros. ¿Pero será eso suficiente para convencer a alguien? Estoy más allá de probarme ante los ignorantes. Simplemente devolveré mis tierras a su legítimo heredero. Soy el Barón de Arizona, y ese título bastará.}
{207}{}{Pero muchos son personas libres, ¿crees que se unirán a ti?}
{208}{}{Por supuesto, muchos ya lo han hecho, como puedes ver. Aquellos que se me opongan llegarán a un desafortunado final. Únete a mí, y toma el juramento. Recordaré tu lealtad por toda la eternidad.}
{209}{}{Lo lamento, pero mi lealtad yace con mi hogar.}
{210}{}{Por tu asistencia, reconozco la soberanía de vuestra casa. La paz sea contigo.}
{211}{}{Adiós.}
{212}{}{No eres más que un fraude, me arrepiento de haberte ayudado.}
{213}{}{Palabras duras para alguien que le debe la vida a uno. Quizá no estemos alineados. Pero si nuestros caminos vuelven a cruzarse, espero que ejerza discreción.}
{214}{}{Tuve que haber permitido a esos campesinos que te lincharan. Adiós.}
{215}{}{Acabaré lo que esos campesinos empezaron. ¡Muere, canalla!}
{216}{}{Tomaré el juramento, Don Reavis, Barón de la Hermosa Arizona.}
{217}{}{¿En serio piensas que te voy a creer? ¡Prefiero matarte que unirme a ti!}
{218}{}{[Otras opciones]}

{220}{}{Te doy la bienvenida a mis filas, noble alma. Arrodíllate y recita las palabras del juramento...}
{221}{}{Juro protegerte a ti y a tus dominios. [+1 Fuerza]}
{222}{}{Juro ser tu fiel súbdito. [+1 Percepción]}
{1222}{}{Juro ser tu fiel súbdita. [+1 Percepción]}
{223}{}{Juro que nunca te abandonaré en tiempos de necesidad. [+1 Resistencia]}
{224}{}{Juro mantenerme como su firme aliado, Barón Reavis. [+1 Carisma]}
{225}{}{Juro ser su leal defensor. [+1 Inteligencia]}
{1225}{}{Juro ser su leal defensora. [+1 Inteligencia]}
{226}{}{Juro que forjaré un mejor camino hacia su Arizona. [+1 Agilidad]}
{227}{}{Juro que le traeré la fortuna a sus tierras. [+1 Suerte]}
{228}{}{Levántate, mi fiel sirviente. Desde hoy, tu sello es el mío. Defiende a Arizona y gobiérnala en mi nombre.}
{229}{}{Mis respetos, Barón Reavis.}

{230}{}{Dios te bendiga.}
{231}{}{Nos vemos.}
