{100}{}{Ves a un granjero en la quiebra.}
{101}{}{Ves a un granjero furioso con el mundo entero.}

{110}{}{¡Muéranse, malditos!}
{111}{}{¡No olvidaré ésto!}
{112}{}{¡Voy a tomar lo que es mío a la fuerza!}
{113}{}{Me quitaron mi granja, yo les quitaré el resto.}
{114}{}{¡Los rangers van a pagar por todo lo que han hecho!}
{115}{}{¿Crees que estoy loco? No, sólo quiero justicia.}
{116}{}{¿Por qué debería pagarle a alguien por vivir en MI TIERRA?}
{117}{}{¡No me importan ni las leyes ni las reglas!}
{118}{}{Los rangers me pusieron en juicio, yo los juzgaré ahora.}
{119}{}{¡Me las van a pagar!}
