{100}{}{Ves a Henry Bemis en medio de los escombros.}
{101}{}{Ves a Henry Bemis, un mero resto del viejo mundo. Un fragmento de lo que la humanidad se trajo a sí misma.}
{102}{}{Bueno, quizás me perdonen.}
{103}{}{*Suspira* Podré leer por toda la eternidad, pero perdí mis gafas. Que cosa tan, tan injusta.}
{104}{}{¡Libros! Son suficientes para una vida entera.}
{105}{}{¡Ah! ¡Ya puedo ver! Me salvaste de una desolación eterna... Ten, podemos leerlo juntos, es un libro realmente intrigante.}
{106}{}{Necesito mis gafas para leer, ¿sí?}

{110}{}{No pasa nada, todo está bien...}
{111}{}{Jamás tuve el lujo de estar sólo.}
{112}{}{¿Qué voy a hacer ahora?}
{113}{}{*Solloza*}
{114}{}{*Llora*}
{115}{}{Vaya, soy muy... suertudo. Sí, realmente suertudo... ¡Ayuda! ¡Quién sea!}
{116}{}{¿En verdad me encuentro sólo?}
{117}{}{Si sólo pudiera desaparecer tal soledad...}
{118}{}{Si sólo pudiéramos hacer algo...}
{119}{}{Algo debe hacerse... lo que sea...}
{120}{}{Esto es injusto. Terriblemente injusto.}

{150}{}{Ah, ¡pero si hay una multitud de libros!}
{151}{}{¡Todas las obras de Dickens!}
{152}{}{¡Todas las obras de George Bernard Shaw!}
{153}{}{¡La poesía de Browning, Shelley y Keats!}
{154}{}{"David Copperfield," "El Gran Gatsby" "La Cabaña del Tío Tom"...}
{155}{}{Libros... Los preciados tesoros del mundo...}
{156}{}{Libros, libros, libros... ¡Ah!}
{157}{}{Enero... Febrero... Marzo... este año... y el siguiente...}
{158}{}{Lo único que importa es que tengo todo el tiempo del mundo.}
{159}{}{*Deja salir un arrullo, muy contento*}
{160}{}{Soy un suertudo... claro que sí.}
{161}{}{Es todo lo que siempre he querido.}
{162}{}{Ahora, sí que tengo algo con lo que ocuparme.}
