{100}{}{Ves a un administrador robótico.}

{200}{}{¡Bienvenido al mundo del Viejo Oeste!}
{201}{}{¡Bienvenido a Legend City!}
{202}{}{¡Bienvenido al parque de atracciones más grande de Arizona!}
{203}{}{Eso suena genial.}
{204}{}{Fuera de mi camino, pedazo de basura.}

{210}{}{¿Cómo puedo ayudarlo, señor?}
{1210}{}{¿Le ayudo, señorita?}
{211}{}{Nada más.}
{212}{}{Eso era todo. Ahora, déjame divertirme.}

{220}{}{¿Qué es este lugar?}
{221}{}{Usted se encuentra en Legend City. ¡El parque de atracciones más grande de Arizona!}
{222}{}{¿Qué se puede hacer por aquí?}
{223}{}{Tenemos distintas atracciones, un área de videojuegos, un campo de tiro y una cafetería. ¿De qué quiere saber?}
{224}{}{Sería mejor que eche un vistazo por mi cuenta...}
{225}{}{Pero, ¿qué es este lugar?}
{226}{}{Me interesan las atracciones.}
{227}{}{Me apena informarle, señor, que las atracciones están cerradas por fallas técnicas. Le pedimos disculpas por cualquier inconveniencia.}
{1227}{}{Me apena informarle, señorita, que las atracciones están cerradas por fallas técnicas. Le pedimos disculpas por cualquier inconveniencia.}
{228}{}{¿Puedo entrar al campo de tiro?}
{229}{}{Lo lamento, señor, pero al campo de tiro se le acabó la munición.}
{1229}{}{Lo lamento, señorita, pero al campo de tiro se le acabó la munición.}
{230}{}{¿Está abierta la cafetería?}
{231}{}{Lo lamento, señor, pero el café está cerrado.}
{1231}{}{Lo lamento, señorita, pero el café está cerrado}
{232}{}{¿Hay algo que sí funcione?}
{233}{}{Puede disfrutar de nuestros videojuegos en nuestro salón recreativo. ¡Disfrute su aventura en el Viejo Oeste, señor!}
{1233}{}{Puede disfrutar de nuestros videojuegos en nuestro salón recreativo. ¡Disfrute su aventura en el Viejo Oeste, señorita!}
{234}{}{Está bien, probemos esos videojuegos.}
{235}{}{Hazte a un lado, montón de chatarra, ¡voy a ganar en grande!}
{236}{}{¿La cafetería está cerrada, verdad?}
