{100}{}{Ves a un supermutante.}
{101}{}{Ves a un supermutante enorme.}

{110}{}{Yo hambre.}
{111}{}{¿Tú hambre también?}
{112}{}{Si yo no comer, yo matar.}
{113}{}{¿Tú querer comparar fuerza con mía?}
{114}{}{Los humanos morirán. Viviremos más que ellos.}
{115}{}{El Maestro escuchar mis plegarias.}
{116}{}{¿Quién se tiró un pedo?}
{117}{}{Odio cuando la gente me mira.}
{118}{}{¿Qué año es?}
{119}{}{¿Cuándo nos iremos de este desierto?}

{120}{}{¡Por el Maestro!}
