{100}{}{Ves a un mexicano.}
{101}{}{Ves a un mexicano, apareció de la nada en medio del desierto.}
{102}{}{Muchas gracias.}
{103}{}{«Muchas gracias.»}


{200}{}{Muchas gracias. (Te da un sorbo de agua como muestra de gratitud) Bebe, gringo.}
{1200}{}{Muchas gracias. (Te da un sorbo de agua como muestra de gratitud) Bebe, gringa.}
{201}{}{¿Acaso se me nota?}
{202}{}{Sí, algo.}
{203}{}{Ya veo. Eh, bueno, ten un buen día.}
{204}{}{«De nada. Por cierto, ¿de dónde eres?»}
{205}{}{«Soy de Hermosillo. No más ciudades en el área, aunque no sé si llamarla ciudad.»}
{206}{}{«¿Qué estás haciendo en medio del desierto?»}
{207}{}{«Estaba explorando el área, el ejército necesita saber si hay agua por aquí, o cualquier otra cosa. Y cómo esperaba, no hay nada, nada más que desierto y bichos gigantes. Pensé que estaba acabado, tuve mucha suerte de que te aparecieras.»}
{208}{}{«Ya veo. Ten suerte en el viaje de vuelta.»}

{300}{}{«Muchas gracias. (Te da agua como muestra de gratitud) Bebe, amigo.»}
{1300}{}{«Muchas gracias. (Te da agua como muestra de gratitud) Bebe, amiga.»}