{100}{}{Ves a Fred Stadtmuller.}
{101}{}{Ves a un padre de atuendo simple y ascético.}
{102}{}{La paz sea contigo.}

{198}{}{(se queda mirando tu armadura, desde los pies a la cabeza) Saludos, em... ¿hijo? No esperaba encontrarme a alguien en el medio del desierto. ¿Estás perdido? ¿Necesitas ayuda?}
{199}{}{Saludos, mi pobre, pobre hijo. No esperaba a encontrarme a alguien de tu tipo en medio del desierto. ¿Estás perdido? ¿Necesitas ayuda?}
{200}{}{Saludos, hijo mío. No esperaba encontrarme a alguien en el medio del desierto. ¿Estás perdido? ¿Necesitas ayuda?}
{1200}{}{Saludos, hija mía. No esperaba encontrarme a alguien en el medio del desierto. ¿Estás perdida? ¿Necesitas ayuda?}
{201}{}{¿Quién eres?}
{202}{}{Soy el Padre Fred Stadtmuller. Viajo a través de Arizona para ayudar a aquellos que lo necesiten - ya sea estén heridos, enfermos, o perdidos.}
{203}{}{Encantado de conocerlo, Padre.}
{1203}{}{Encantada de conocerlo, Padre.}
{204}{}{Tú no eres mi papá.}
{205}{}{Oh, no, no. Por supuesto, no lo soy. Padre es un título que se le otorga a los hombres de mi rango. Te pido perdón si te ofendí.}
{206}{}{De acuerdo.}

{210}{}{¿Puedo ayudarte con algo? hazmelo saber.}
{211}{}{No, me las arreglaré. Le deseo lo mejor, Padre.}

{220}{}{Sólo quiero hablar contigo.}
{221}{}{Por supuesto. ¿Qué quieres saber?}
{222}{}{Espera, quiero preguntar otra cosa.}
{223}{}{¿Quién eres?}
{224}{}{Mi nombre es Fred Stadtmuller. Difundo la palabra de Dios en estas tierras, como hacía el clero de la Iglesia Católica antes de la Gran Guerra. Por desgracia, hay muchos que han olvidado esto y me ven como un viajero que está mal de la cabeza.}
{225}{}{Respóndame otra pregunta, por favor.}
{226}{}{¿Quién le otorgó ese rango?}
{227}{}{Fui parte de una orden monástica en las afueras de Fénix, allí me nombraron sacerdote. Esto ocurrió antes de que Fénix cediera ante el caos, nuestra iglesia moraba en la Catedral del Fuego Santo y evitábamos meternos en los asuntos del mundo.}
{228}{}{¿Entonces eres parte de la Iglesia del Fuego Santo? ¿Por qué los dejaste?}
{229}{}{Hubieron desacuerdos con el actual líder de la Catedral. Hace tiempo, nuestra pequeña iglesia rechazaba enriquecerse ser más poderosa, y se enfocaba en ayudar a aquellos que sufrían y en preservar las reliquias antiguas.}
{230}{}{¿Qué pasó después?}
{231}{}{La Catedral ha cambiado drásticamente, ya no podía hacer la misa entre tanto vicio y maldad. Ahora llevo a cabo mis servicios igual que los monjes de la orden de antaño, siguiendo las viejas tradiciones.}
{232}{}{Bien, usted siga así, Padre.}
{233}{}{Supongo que a la Catedral no deben de gustarle esas tradiciones.}

{240}{}{¿Cómo aprendiste a controlar ese pájaro de hierro?}
{241}{}{Los libros antiguos nos ayudan a comprender la aviación, entre otras cosas. Pero, ¿por qué digo eso? Apenas hace unos años, Fénix y otros asentamientos dependían de las velas para iluminarse. ¿Y ahora? Gracias a la sabiduría de los libros, ha regresado la energía eléctrica.}
{250}{}{Sí, necesito ayuda.}
{251}{}{¿En qué puedo ayudarle, joven?}
{252}{}{Pensándolo bien, sólo quiero hablar.}
{253}{}{Entonces no lo retrasaré más, Padre.}
{254}{}{Necesito ayuda médica.}
{255}{}{Tu cuerpo se encuentra bien. En cuanto a tu alma, tendrás que trabajar en ella por tu cuenta. Debo apresurarme; me esperan los niños enfermos dentro de la capilla de Santa María.}
{256}{}{Adiós, Padre.}
{257}{}{Busco arrepentirme, padre. He cometido muchos pecados.}
{258}{}{No puedo absolverte por completo de tu carga, pero puedo ayudarte a aligerarla. Arrodíllese, joven...}
{259}{}{Gracias Padre.}
{260}{}{Necesito tus cosas. Entrégame todo lo que tengas, tu ropa igual.}
{261}{}{Que San José te perdone...}
{262}{}{Cállate.}
{263}{}{Estoy cansado de caminar por este desierto, quiero llegar a alguna ciudad. ¿Puedo subirme contigo al pájaro de hierro?}
{1263}{}{Estoy cansada de caminar por este desierto, quiero llegar a alguna ciudad. ¿Puedo subirme contigo al pájaro de hierro?}
{264}{}{Por supuesto, no tardaremos mucho.}
{265}{}{¿A dónde sugieres que vaya?}
{266}{}{Eso depende de qué esté buscando tu alma.}
{267}{}{Dame un momento, tengo que pensarlo.}
{268}{}{Quiero vengar a mi familia, se los llevaron al este de nuestra Villa.}
{269}{}{Que así sea. Pienso que deberías ir a Ciudad Garaje o Flagstaff.}
{270}{}{Vamos a Ciudad Garaje.}
{271}{}{Vamos a Flagstaff.}
{272}{}{No, mejor no. ¿Y si vamos a otro lado?}
{273}{}{Lo único que necesito es encontrar buen equipamiento y munición. Y quizás dinero, tengo que comer.}
{274}{}{La respuesta a lo que buscas está en Fénix. Es la ciudad más grande y desarrollada que encontrarás por millas.}
{275}{}{Llévame a Fénix.}
{276}{}{Sólo quiero descansar, un lugar tranquilo me vendría bien.}
{277}{}{Sé de un lugar así, en medio del desierto de Sonora existe un lugar llamado Casa Nueva, es como un oasis.}
{278}{}{Vamos allá.}
{279}{}{Me gustaría explorar lo desconocido.}
{280}{}{Entonces, lo más seguro es que quieras viajar al sur, hacia el territorio Mexicano.}
{281}{}{Vamos al sur, llévame a la ciudad Mexicana más próxima.}
