{100}{}{Ves al morador de un refugio.}
{101}{}{Ves al morador de un refugio. Tiene una apariencia limpia y suave, si lo comparas con la gente del yermo.}

{110}{}{Buenos días... ¿O buenas noches? No sé que hora es allá afuera.}
{111}{}{¡No nos hagas daño, por favor! ¡Somos gente de bien!}
{112}{}{Hemos estado en el refugio por toda nuestra vida. ¿Y tú de dónde eres?}
{113}{}{Los saqueadores han intentado penetrar nuestras defensas durante meses.}
{114}{}{¿Cómo conseguiste entrar?}
{115}{}{No podemos irnos a ningún otro lado, el refugio es nuestro único hogar.}
{116}{}{Jamás podríamos sobrevivir en el desierto. ¡Por favor, ayúdanos!}

{120}{}{¡Gracias! Nos salvaste del mundo exterior.}
{121}{}{Gracias por arreglar el sistema, te debemos una.}
{122}{}{¿Puedes sentir el aire fresco? ¡Es tan refrescante sentirlo de nuevo!}
{123}{}{Pensaba que tendríamos que abandonar el refugio, pero llegaste a ayudarnos.}
{124}{}{Eres un héroe, a diferencia de los malditos saqueadores.}
{125}{}{¿Sabías que nuestro primer supervisor se llamaba Van Buren?}
{126}{}{Muchísimas gracias, siempre te lo agradeceremos.}
{127}{}{Menos mal que llegaste, ninguno de nosotros habría sobrevivido allá afuera.}
