{100}{}{Ves a Joe, el cantinero local.}
{101}{}{Estás viendo a Joe, el estimado cantinero de Flagstaff, es toda una celebridad local.}
{102}{}{Lo siento, pero el bar está cerrado. Vuelve en la mañana.}
{103}{}{Z-z-z...}
{104}{}{Bonita armadura, pero para estar en un bar, te vendría mejor algo más simple.}
{105}{}{Oye, perdona, pero no se permiten las armas en el bar. Esa es mi regla.}

#Floating lines
{109}{}{¿Qué se dice por ahí?}

{110}{}{Se está planeando un trato comercial con Ciudad Garaje, promete mucho.}
{111}{}{Las calles de Ciudad Garaje están muy silenciosas, es como si todos hubieran desaparecido de la noche a la mañana.}
{112}{}{Faber ha hecho un trato con Ciudad Garaje, creo que beneficiará a todos los involucrados.}

{113}{}{San Brahmán tenía la mejor carne del yermo, pero dejaron de venderla.}
{114}{}{Se rumoreaba que hubo un problema en San Brahmán, pero parece que ya se calmaron las cosas.}
{115}{}{Esos pastores son muy testarudos, cerraron toda ruta comercial que tuvieran con Fénix.}

{116}{}{Los cultistas del sur deben estar tramando algo.}
{117}{}{La Catedral del Fuego se incendió. Que irónico, ¿no?}
{118}{}{Los cultistas que hay al sur están planeando algo grande, o eso se dice.}

{119}{}{Está llegando más gente del sur, pero cada vez hay menos bienes.}
{120}{}{Se dice que Fénix está teniendo problemas en estos momento.}
{121}{}{Estás pensando en ir a la Gran Ciudad otra vez, ¿no?}

{122}{}{Alguien ha estado atacando a los patrulleros en las ruinas.}
{123}{}{No sabía que los Rangers estaban detrás de los ataques a las patrullas.}
{124}{}{¿Quién se creen esos rangers?}

{125}{}{Faber tiene un plan en mente para Flagstaff, la reconstruirá. Recuerda mis palabras.}
{126}{}{Hemos perdido a Roy Faber y nuestra colonia sentirá las consecuencias.}
{127}{}{La mina jamás había funcionado así de bien.}

{128}{}{Los carceleros se están apoderando de la trata de esclavos. Si me lo preguntas, es un poco turbio.}
{129}{}{Los prisioneros se han fugado, tenemos que tener cuidado.}
{130}{}{Jamás había visto a los carceleros dejar ir a sus esclavos.}

{131}{}{A veces lo único que hace falta para sentirte vivo es un trago fuerte y una chica con las tetas grandes.}
{132}{}{Esto es un bar, no un mercado.}
{133}{}{¿Buscas algo más fuerte?}
{134}{}{Me parece que el nuevo cargamento no llegará a tiempo.}
{135}{}{Esto de aquí es el mejor alcohol que encontrarás al norte de Fénix.}
{136}{}{¿Te sirvo otro vaso?}

#First dialogue
{200}{}{Hola.}
{201}{}{¿Te importa si te hago algunas preguntas?}
{202}{}{Nos vemos.}
{203}{}{Adelante, siéntete como en casa.}
{204}{}{Siéntate, pero deja los problemas en la puerta.}

#Questions
{210}{}{¿Qué quieres saber?}
{211}{}{Dime otra cosa.}
{212}{}{Hablemos del bar.}
{213}{}{¿Te puedo hacer otra pregunta?}
{214}{}{Retrocedamos un poco.}
{215}{}{Bueno, no tienes muchas opciones. La mina siempre necesita más trabajadores y la guarnición tiene chambitas de vez en cuando. Puede que yo también tenga algún trabajo que darte. Tú decides.}

{220}{}{¿En dónde podría ganarme unas chapas?}
{221}{}{Pues, no hay muchas opciones. La mina siempre necesita más trabajadores y la guarnición tiene chambitas de vez en cuando. Puede que yo también tenga algún trabajo que darte.}
{222}{}{Acabo de llegar a Flagstaff, háblame de este lugar.}
{223}{}{Flagstaff es una colonia penal y tiene un régimen estricto. Los lugares importantes son la guarnición que está al este y la mina de uranio, que está al norte de la guarnición.}
{224}{}{¿Podrías hablarme de la mina?}
{225}{}{La ciudad entera le debe su existencia a la mina, pues fue construida desde cero para extraer el uranio. Solía generar una montaña de chapas, pero debido a una escasez laboral, las cosas han empeorado.}
{226}{}{¿Qué puedes decirme de la prisión?}
{227}{}{Los mercenarios de Faber establecieron un campamento entre las ruinas y encierran a los criminales allí adentro, los trajeron de todas partes. Y ahora esos convictos trabajan para pagar sus deudas y la colonia prospera gracias a sus esfuerzos.}
{228}{}{¿Qué hay del servicio postal?}
{229}{}{Es una sucursal de una compañía que provino de Fénix, se encarga de entregar paquetes pequeños entre asentamientos.}
{230}{}{He oído que este lugar está lleno de esclavos. ¿Es cierto eso?}
{231}{}{Te daré un consejo: cuidado con lo que dices. Los trabajadores son una mezcla de prisioneros y esclavos. Algunos cumplen su sentencia y otros pagan sus deudas. Es obvio que también hay salvajes entre ellos, pero los llamamos sirvientes, no esclavos.}
{232}{}{¿Por qué mantienen a los delincuentes bajo custodia?}
{233}{}{Para que hagan el trabajo duro, lo han hecho casi todo. Sin ellos, establecer Flagstaff hubiera sido un proceso lentísimo.}
{234}{}{En tu opinión, ¿crees que es justo?}
{235}{}{Oye, fue gracias a esos tipos que reconstruimos la ciudad y nos pudimos establecer aquí. ¿Has visto algún otro lugar así en el yermo?}
{236}{}{¿En dónde consigues todo este licor?}
{237}{}{Todo esto fue destilado en Fénix, las caravanas lo traen una vez al mes. No podría compararlo con los tragos de la preguerra, pero es barato y abundante.}
{238}{}{Me gustaría invitarle un trago a todos.}
{239}{}{Eso es muy generoso de tu parte, te costará 50 chapas.}
{240}{}{El dinero no es ningún problema. ¡Sírvele un trago a todos, yo invito!}
{241}{}{¿Cuánto? Pensándolo bien, mejor me lo ahorro.}
{242}{}{Espera, primero tengo una pregunta.}
{243}{}{Eso es demasiado caro. Quizás en otro momento, en el futuro, algún otro día.}
{244}{}{Has empezado bien, los demás lo apreciarán. Pero recuerda esto - una bebida no será suficiente para formarte una reputación en este lugar.}
{245}{}{Sigamos hablando, antes de que se pase la borrachera.}
{246}{}{De acuerdo, es hora de que vaya a enfocarme en cosas más importantes.}
{247}{}{¿Qué opinas de Roy Faber?}
{248}{}{Es el jefe, así de simple. Flagstaff no existiría sin él. (se inclina hacia ti y baja la voz) Escucha, es mejor que no hables de él. Si quieres vivir, no hagas preguntas o hables a sus espaldas. ¿Lo comprendes?}
{249}{}{Es nuestro líder, este lugar no existiría sin él.}

#Teeth of the rat king from the mine
{250}{}{Mira esto, le saqué un diente al Rey Rata de la mina.}
{251}{}{¿Me estás tomando el pelo? ¡Si esa cosa no era del tamaño de un brahmán, que me parta un rayo! Habían dicho tantos rumores acerca de esa bestia... Mira, véndemelo, te ofrezco 100 chapas.}
{252}{}{¿Qué quieres hacer con el diente?}
{253}{}{Claro, aquí tienes.}
{254}{}{No, estaba pensando en hacerlo un amuleto para asustar a mis enemigos.}
{255}{}{Me lo voy a pensar.}
{256}{}{Estoy seguro de que esta cosa atraerá a algunos clientes.}
{257}{}{Ah, tú y tus supersticiones rurales... darte chapas sería un desperdicio. Piénsalo.}
{258}{}{(sonríe de forma siniestra) Es hora de presumir esta cosa... Ah, cierto - tus cien chapas.}
{259}{}{Trato hecho.}
{260}{}{Hasta luego, Joe.}
{261}{}{No parece que estés listo para hablar de esto. Hablemos de otra cosa.}
{262}{}{No le tengo miedo a nadie, pero si eso dices, cambiemos de tema.}
{263}{}{Te lo regalo, pero hazme un favor y cuéntales a los demás acerca de mí. ¿Bien?}
{264}{}{Jo-jo-jo, es hora de presumir a este bebé. ¿De verdad no quieres nada como muestra de gratitud? ¿Qué tal si te invito una bebida?}
{265}{}{Gracias, eso me refrescará un poco. Buena suerte, Joe.}
{266}{}{Por favor, me hace falta algo de medicina. Somos amigos, ¿no?}
{267}{}{No seas así, no quieres que me muera, ¿cierto?}

#About trading
{270}{}{¿Qué tienes a la venta el día de hoy?}
{271}{}{Alcohol y botanas. ¿Qué esperabas encontrar en un bar? Aunque a veces, debo hacer de tienda y tener de todo.}
{272}{}{Lo único que aceptas son chapas, ¿no?}
{273}{}{Sí, es porque en el sur, ahora sólo comercian con chapas. Por lo que en estos tiempos, el dinero de la preguerra ha perdido todo su valor.}
{274}{}{¿En dónde podría conseguir medicamentos?}
{275}{}{No encontrarás eso en esta ciudad, lo lamento. Quizás las caravanas tengan algo, yo tengo mis medicamentos almacenados para emergencias.}
{276}{}{Me temo que ya no tengo nada más.}
{277}{}{Véndeme tus medicamentos, será un buen trato, seguramente ya están por vencer.}
{278}{}{Hmm. Tienes razón, esto es lo que tengo. (coloca varios medicamentos sobre el mostrador)}
{279}{}{Claro que no, incluso en un lugar tan seguro como Flagstaff, siempre viene bien guardar un par de estimulantes.}
{280}{}{Merezco un precio especial con la reputación que tengo, ¿no crees?}
{281}{}{Creo que tienes razón, tanto yo como los demás clientes estarían felices de verte aquí más a menudo. ¿Qué tal si te ofrezco un 20% de descuento?}
{282}{}{Eso sería fantástico. ¿Qué tienes a la venta?}
{283}{}{Se dice que hay un forastero que anda causando problemas en Flagstaff. Ojalá que no se quede aquí.}
{1283}{}{Se dice que hay una forastera que anda causando problemas en Flagstaff. Ojalá que no se quede aquí.}
{284}{}{¿Subiste los precios? ¿Por qué?}
{285}{}{Ah, es que hubo una 'crisis' comercial. Si no te gustan mis precios, pues, buena suerte encontrando otro bar en esta ciudad... Sí, este es el único.}
{286}{}{Comprendo.}

#Showdown at the bar
{287}{}{Ya tenía ganas de que alguien pusiera a ese mercenario en su lugar, era muy arrogante. Aquí tienes una cerveza, la casa invita. Pero cuídate la espalda, porque la guarnición no se olvidará de esto.}
{288}{}{Me las arreglaré de alguna forma. Gracias por la cerveza.}
{289}{}{Sí, un "precio especial"... creo que cobrarte el doble estaría bien.}

#About my relatives in the city
{290}{}{Vengo del oeste, de una aldea. Estoy buscando a mis parientes.}
{291}{}{¿Vinieron aquí por voluntad propia? ¿No? Entonces lo más probable es que estén en el corral de los prisioneros. Ve directo hacia el este, sigue la calle principal.}
{292}{}{¿Por qué crees que deben estar ahí?}
{293}{}{No he visto a ningún recién llegado en estos días, pero hubo un alza en la cantidad de salvajes en el corral.}
{294}{}{¿Por qué encierran así a la gente?}
{295}{}{Para que puedan trabajar en la mina, así ayudan a reconstruir la ciudad. Esta colonia le debe su existencia al trabajo de los delincuentes.}
{296}{}{Es hora de que vaya a hablar con el jefe de los carceleros.}
{297}{}{Buena idea, pero cuídate la espalda y no busques problemas. No deberías meterte con Faber; todos le tienen miedo.}
{298}{}{Gracias por la ayuda, tengo que irme.}

#Tequila sales have been stopped
{300}{}{¿Qué pasó? ¿En dónde está el tequila?}
{301}{}{Lo destilan en Fénix y se dice que tuvieron problemas. Y ahora me encuentro comprándole lo que sea que me traigan las caravanas. Es por eso que subí los precios.}
{302}{}{Eso pensaba. Bueno, cuídate.}
{303}{}{Eso es una pena, nos vemos luego.}
{304}{}{En ese caso, muéstrame lo que te queda.}
{305}{}{Déjame ver que puedo ofrecerte...}

#Quest - Repay the Debt
{310}{}{¿Tienes algún otro trabajo que ofrecerme?}
{311}{}{Sí, la verdad es que sí. Hay un mercenario llamado Davis, me debe unas cien chapas. Está vetado del bar, pero eso no es bueno para el negocio.}
{312}{}{¿Qué estás planeando?}
{313}{}{Si consigues que pague su deuda, dividiré lo recaudado contigo.}
{314}{}{consideralo hecho.}
{315}{}{Eso debe ser arriesgado, paso.}
{316}{}{Me lo pensaré.}
{317}{}{Es un trato. Recuerda que Davis me debe 100 chapas, te daré la mitad.}
{318}{}{Entendido.}
{319}{}{Claro, no hay problema. Pero mi oferta sigue en pie.}
{320}{}{De acuerdo.}
{321}{}{Tómate tu tiempo, Davis no tiene prisas de pagar su deuda.}
{322}{}{Está bien.}
{323}{}{Tengo las chapas de Davis conmigo.}
{324}{}{¿De verdad? No puedo creerlo. Gracias, dame 50 chapas y el resto es tuyo, como acordamos.}
{325}{}{Mi bolsillo se está poniendo pesado. Adiós.}

#Pinball Machine
{330}{}{La máquina de pinball está rota.}
{331}{}{Sí, lo sé. Atraía a muchos clientes.}
{332}{}{¿Qué le pasó?}
{333}{}{Me parece que algo se descompuso ahí adentro y aquí no hay ningún repuesto. Debes viajar mucho, si encuentras algo para reparar el StarBall, te daré 50 chapas.}
{334}{}{Trato hecho.}

{335}{}{Suena bien.}
{336}{}{Antes de que haga eso, tengo unas preguntas acerca de la máquina.}
{337}{}{Hablemos de otra cosa}
{338}{}{De acuerdo.}

{339}{}{No es lo mío.}
{340}{}{De acuerdo, buscaré a otra persona.}
{341}{}{¿Sabes qué le falta a tu bar?}
{342}{}{¿Qué cosa?}
{343}{}{No sé. Te diré cuando se me ocurra.}
{344}{}{Una bandera en la pared, una patriótica. Y estás de suerte, tengo una aquí.}
{345}{}{Dios mío, pensé que ya no quedaba ninguna de estas banderas. Te ofrezco un trato, te daré esta carabina a cambio de la bandera de Arizona. Está en buenas condiciones, pero aquí no hay mucha munición. ¿Qué dices?}
{346}{}{Trato hecho, hagamos el trueque.}
{347}{}{¿Quieres que te de mi pedazo de basura por tu pedazo de basura? No gracias.}
{348}{}{Voy a colgar la bandera después del cierre. Muchísimas gracias.}
{349}{}{De nada, fue un placer.}

{350}{}{Tengo una pregunta acerca de la máquina de pinball.}
{351}{}{Dime.}
{352}{}{Olvídalo, no importa.}
{353}{}{¿De dónde vino ese aparato?}
{354}{}{Estaba en el armario cuando llegué aquí, le limpié el polvo y el Tío Tom le hizo unos arreglos por un par de chapas, y ahí está.}
{355}{}{¿Cómo se juega?}
{356}{}{La pelota tiene una estrella, le debes dar a los botones de los lados para que entre a las ranuras que te dan puntos. Cuando entre en un "agujero negro", ganarás puntos, dependiendo de cuanto tiempo haya estado rebotando la pelota. Pero ten cuidado, tiene algunas bobinas electromagnéticas que te pueden electrocutar.}
{357}{}{¿Puedes ganar algún premio al jugar?}
{358}{}{Es sólo para divertirse. Aunque prometí que le daría un trago gratis a cualquiera que consiga 1.000 puntos.}
{359}{}{¿Es eso posible?}
{360}{}{Hubo una vez que casi pasó, pero el tipo estaba exhausto y se desmayó cuando le faltaban unos puntos.}
{361}{}{He conseguido arreglar el StarBall.}
{362}{}{Genial, te daré 50 chapas y te invitaré un trago.}
{363}{}{¿Te importa si le doy una probada?}
{364}{}{Claro, pero no la rompas.}
{365}{}{De acuerdo.}
{366}{}{Bien hecho, te daré 50 chapas.}
{367}{}{¡No puede ser! ¡Lo conseguiste! Estuve guardando esta botella para una ocasión especial, la casa invita. Después de tanta tensión, te lo has ganado.}
{368}{}{Lo agradezco.}
{369}{}{Ojalá que sea la primera botella de muchas.}
{370}{}{Creo que ya me voy.}

{380}{}{¿En dónde conseguiste ese collar?}
{381}{}{Me lo dieron en un trueque, parece que es de oro puro.}
{382}{}{Conozco a la dueña, me dijo que se lo robaron.}
{383}{}{Pues... No es problema mío. Yo lo obtuve de forma honesta. Si lo quieres, tendrás que ofrecerme algo a cambio.}
{384}{}{¡Entrégamelo de inmediato!}
{385}{}{No sabes lo que estás haciendo. O pagas o te largas de aquí.}
{386}{}{Bueno, como gustes.}
{387}{}{No, gracias.}
{388}{}{Te arrepentirás de esto.}

{390}{}{El cantinero de Ciudad Garaje necesita alcohol.}
{391}{}{Pensaba que ese lugar ya estaba desierto. No ha venido ninguna caravana desde allá en un buen rato... Pero... Ah, claro, los pastores. Han estado causando alborotos en las rutas comerciales, ya que impiden que las caravanas crucen su territorio.}
{392}{}{Ciudad Garaje está tranquila, no hay mucho más que hacer además de beber.}
{393}{}{Puedo venderle un poco al cantinero, pero te aseguro que sus días están contados. Contratar a un mensajero cuesta muchas chapas.}
{394}{}{Le haré saber al cantinero sobre esto. Todavía le queda un poco de esperanza a Ciudad Garaje.}
{395}{}{Has hecho un buen trato, pero hablemos un poco más antes de que me vaya.}

{400}{}{¿Le entregaste el almuerzo al administrador de la mina?}
{1400}{}{¿Le entregaste el almuerzo al administrador de la mina?}
{401}{}{Todavía no, jefe.}
{402}{}{Muévete de una vez, o la comida se enfriará.}
{403}{}{Ya voy.}
{404}{}{No, todavía no.}
{405}{}{Sabía que no podía confiar en ti, fuera de mi negocio.}
{406}{}{. . .}
{407}{}{Traigo malas noticias, el administrador ha muerto. La mina es un desastre.}
{408}{}{Mierda... eso es una pena. Era un buen cliente, ordenaba ese almuerzo a menudo. Ojalá que el nuevo administrador siga esa tradición. No puedo darte las chapas, pero quédate con el almuerzo.}
{409}{}{Bueno, al menos no me moriré de hambre.}
{410}{}{¿Me darás un platillo en vez de las chapas? Ojalá que la guarnición no se entere de lo tacaño que eres.}
{411}{}{Lo entregué justo a tiempo.}
{412}{}{Hiciste un buen trabajo, aquí están tus chapas. Ya conseguí a otro repartidor, así que ya no te necesitaré. Pero pásate por aquí cuando quieras.}
{413}{}{Hasta luego, Joe.}

{420}{}{¿Qué trabajo tienes disponible?}
{421}{}{El administrador de la mina pidió un almuerzo y hay que entregárselo. La paga es buena, pero mi mensajero se enfermó en el peor momento posible. Te daré dos chapas, pero debes entregarlo en menos de seis horas.}
{422}{}{Tendré que decir que no, lo siento.}
{423}{}{Entiendo, ya voy.}
{424}{}{Estas son las salchichas de brahmán que ordenó, pero no te las tragues. Vamos, a moverse.}
{425}{}{De acuerdo.}
{426}{}{¿Quién es tu mensajero?}
{427}{}{El niño que está cerca del servicio postal, por alguna razón su padre lo tiene en cama.}
{428}{}{¿Qué le pasó?}

{430}{}{¿Tienes algún otro trabajo para mí?}
{431}{}{Sí, estoy esperando a que un campamento de cazadores me traiga carne. He esperado a que digan algo por la radio, pero nada. Hace falta ir a echar un ojo y ver qué pasó, si necesitan ayuda, me vendría bien que alguien se encargue de eso.}
{432}{}{Puedo echarte un hilo.}
{433}{}{Lo siento, pero no tengo tiempo. Se las arreglarán sin mí.}
{434}{}{El Campamento Winon está al este de aquí, son unas 60 millas y está entre las montañas. Ten cuidado con los animales.}
{435}{}{Deséame suerte.}
{436}{}{Lo más seguro es que estén borrachos, los voy a despellejar como a una rata cerdo si resulta que no era nada.}
{437}{}{Respecto al campamento de cazadores...}
{438}{}{¿Te has enterado de algo?}
{439}{}{No, todavía no voy.}
{440}{}{¿Me puedes recordar en dónde está el campamento?}
{441}{}{El Campamento Winon está al este de aquí, son unas 60 millas.}
{442}{}{Entendido, ya me voy.}
{443}{}{Fui al Campamento Winon, resulta que unos salvajes mataron a los cazadores.}
{1443}{}{Fui al Campamento Winon, resulta que unos salvajes mataron a los cazadores.}
{444}{}{¡Demonios, que malas noticias! Ese campamento le daba de comer a nuestra ciudad. Son nuestros terrenos, allí cazamos, no podemos permitir que unos salvajes nos lo quiten.}
{445}{}{¿Y entonces qué deberíamos hacer?}
{446}{}{Puede que Faber envíe un escuadrón, de todos modos, la guarnición no está haciendo nada. Si no lo hace, tendremos que echar a los salvajes por cuenta propia.}
{447}{}{¡Hay que echarlos! Si solo Faber estuviera aquí... nos hace falta la guarnición.}
{448}{}{Hasta luego.}
{449}{}{No te preocupes - ya me encargué de los salvajes.}
{450}{}{¿En serio? ¿Cómo lo conseguiste?}
{451}{}{¿Qué le puede hacer un salvaje a alguien como yo? Muy poco.}
{452}{}{Utilicé sus supersticiones en su contra.}
{453}{}{Demonios, es mejor que no me cruce en tu camino. El campamento es una fuente de carne muy importante, tanto para mí como para la ciudad. Te debemos un gran favor, gracias.}
{454}{}{La gente no debería sufrir por los errores de sus líderes.}
{455}{}{Un 'gracias' no es ninguna recompensa.}
{456}{}{Estaba pensando en darte 20 chapas para que trajeras la carne de vuelta. Pero por como terminó esto, necesitaría un año entero para recuperarme. Ya sé, te daré un 50% de descuento en todo lo que vendo. Es justo, ¿no?}
{457}{}{Eso es justo, debo irme, el yermo necesita de mi ayuda.}
{458}{}{Me ocuparé de ello.}
