{100}{}{Ves a una clienta del bar.}
{101}{}{Ves a una de las clientas del bar. Siempre estará dispuesta a hablar, mientras haya un trago en su mesa.}

{200}{}{¿Qué tal? ¿Cómo estás?}
{201}{}{Nos vemos luego.}
{202}{}{Oye, amigo. ¿Te sientes generoso? ¿Qué tal si me invitas una cerveza? ¿O acaso te quedarás ahí parado?}
{1202}{}{Oye, hermana. ¿Te sientes generosa? ¿Qué tal si me invitas una cerveza? ¿O acaso te quedarás ahí mirando?}
{203}{}{Sí que tuviste una buena pelea. ¿Qué tal si bebemos un poco para celebrarlo? ¿O acaso sólo viniste al bar para pelear?}

{204}{}{No tengo dinero, lo siento.}
{205}{}{¡Ja! Que avaro...}
{206}{}{¿A quién le acabas de decir eso? ¿A mí?}
{207}{}{Bueno, adiós.}
{208}{}{Sí, ¿y qué?}
{209}{}{Pero si la que anda rogando por un trago eres tú, puta.}
{210}{}{Eh, no importa.}
{211}{}{Tranquilo, vaquero. En esta ciudad, es mejor que no hagas escándalos por algo tan pequeño.}
{1211}{}{Tranquila, señora. En esta ciudad, es mejor que no haga escándalos por algo tan pequeño.}
{212}{}{Entonces cierra la boca.}

{220}{}{Claro, déjame ir por algo.}
{221}{}{Aquí te espero.}
{1221}{}{Aquí te espero.}
{222}{}{Nos vemos luego.}
{223}{}{Tengo una cerveza. No es nada impresionante, pero sirve. ¿No?}
{224}{}{Tengo una botella de tequila. Será perfecta para relajarse. ¿No crees?}
{225}{}{Gracias. (vierte un poco en el vaso y se queda callada)}
{226}{}{¿Qué ocurre? ¿Pasó algo?}
{227}{}{No es eso... (se bebe el vaso entero) Podría estar mejor.}
{228}{}{Mira, pagué yo, ¿me podrías contar un poco de la ciudad?}

{229}{}{Sólo he estado en la ciudad por un mes, pero no me tomó mucho tiempo darme cuenta de una cosa: es mejor que no hagas amigos por aquí.}
{230}{}{Puedes decir eso de cualquier ciudad que no conozcas bien.}
{231}{}{Suena a que ocurrió algo muy malo.}
{232}{}{No pedí tu opinión. Pero... creo que dices la verdad.}
{233}{}{¿Por qué no me cuentas lo que pasó?}
{234}{}{Sí, fue algo bastante malo...}
{235}{}{Y, ¿me contarás lo que pasó?}
{236}{}{Pues, llegué aquí junto a mi novio. Las cosas iban bien, buscamos chatarra entre las ruinas, pagábamos impuestos.}
{237}{}{[Sigue]}

{238}{}{Pero se nos empezaron a acabar las chapas, y Karl se endeudó. Las cosas fueron cuesta abajo, y Faber lo metió a la cárcel. Y yo estoy... aquí. No sé qué haré.}
{239}{}{¿Qué tan larga es su condena?}
{240}{}{Faber lo sentenció a un año de trabajo, pero Karl no durará tanto. Y yo tampoco.}
{241}{}{¿No hay ninguna forma de ayudarlo?}
{242}{}{Solo si podemos reunir suficientes chapas para pagar sus deudas, pero no hay ninguna forma de ganar tantas.}
{243}{}{Es una pena. Lo lamento.}
{244}{}{Sí, lo sé.}
{245}{}{[Déjala sola]}
{246}{}{¿Qué harás ahora?}
{247}{}{Después de esto, no podemos quedarnos aquí, de ninguna manera. Debo irme, quizás vuelva al sur.}
{248}{}{¿Podrías recordarme qué le pasó a tu novio?}
