{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia. Ha tenido un largo viaje, y está cansado.}

{110}{}{¿Qué debería hacer antes de cargar las cajas?}
{111}{}{¿Nos echamos una partida de Caravana? Es fácil de aprender.}
{112}{}{Despiértenme cuando empiecen a cargar las cajas.}
{113}{}{En el sur están muy *acalorados* con este mineral. Jeje.}
{114}{}{Cada viaje podría ser el último.}
{115}{}{No sé que haríamos si no hubiera una colonia por aquí.}
{116}{}{Habla con el jefe, yo sólo soy un guardia.}
{117}{}{No solemos llevar gente con nosotros.}
{118}{}{Las tormentas de polvo nos atraparon en San Brahmán por una semana.}
{119}{}{El viaje será difícil.}
