{100}{}{Ves a un patrullero.}
{101}{}{Ves a uno de los mercenarios, está patrullando la calle con mucha tranquilidad.}
{102}{}{Demonios, casi te vuelo los sesos. No deberías salir luego del toque de queda.}

{110}{}{Saludos.}
{111}{}{Bienvenido a Flagstaff.}
{112}{}{Sigue caminando.}
{113}{}{¿Hay algún problema?}
{114}{}{¿Qué necesitas?}
{115}{}{Si tienes un arma, es mejor que la enfundes.}
{116}{}{Ten un buen día.}
{117}{}{Si vas al Galaxy Lunch, pídete las salchichas de brahmán, son deliciosas.}
{118}{}{Si ves algo sospechoso, hazmelo saber.}
