{100}{}{Ves a tu madre.}
{101}{}{Ves a una mujer que te resulta muy familiar. Es tu madre.}
{102}{}{Adiós, mamá. De ahora en adelante, me cuidaré por cuenta propia.}
{103}{}{Recibes }
{104}{}{ puntos de experiencia por liberar a los campesinos.}
{105}{}{Tu madre ha muerto. Debes encontrar a los demás campesinos de la Villa.}
{106}{}{Tu madre ha muerto. No tienes nada más que hacer aquí.}
{107}{}{Hablemos luego, tenemos que salir de aquí.}

# First Dialogue
{200}{}{... ¿Cómo? Dios mío, ¡no deberías de haberte arriesgado así! Sé que hubiéramos encontrado alguna forma de volver a la Villa... Pero no sabes lo feliz que estoy de verte. ¡Qué orgulloso estaría tu padre de conocer la determinación que tienes! Lo has hecho bien.}
{201}{}{A veces no te soporto, mamá. Ya no soy un niño.}
{1201}{}{A veces no te soporto, mamá. Ya no soy una niña.}
{202}{}{Si te hubiera pasado algo y no hubiera hecho nada, jamás me lo perdonaría.}
{1202}{}{Si te hubiera pasado algo y no hubiera hecho nada, jamás me lo perdonaría.}
{203}{}{Ah, sí, por supuesto... Lo entiendo. Quizás fue todo este desastre. Nos cambió a todos. Lo veo en tus ojos, veo a una persona distinta. Y, no sé si eso es bueno o malo.}
{204}{}{Esa es la fuerza de la Villa - somos como una familia muy grande. Todos se cuidan entre sí. Y estoy feliz de ver que tus viajes no han cambiado eso dentro de ti.}
{205}{}{Hay que pensar en cómo podemos salir de aquí.}

{206}{}{Me temo que no será fácil. Como puedes ver, sólo hay tres de los nuestros. Hay otros dos que desaparecieron en la mina. Se llevaron a los demás, incluyendo a tu padre, a una gran ciudad en el sur llamada 'Fénix'.}
{207}{}{¿Qué te han hecho los mercenarios?}
{208}{}{¿Cómo puedo llegar a Fénix?}
{209}{}{¿Qué sabes de los desaparecidos?}
{210}{}{¿Se te ocurre cómo puedo sacarte de aquí?}
{211}{}{Encontraré alguna forma de resolver todo esto. Espérame aquí.}
{212}{}{Estoy tan contenta de verte.}
{213}{}{Todavía estoy intentando liberarte. Resiste.}
{214}{}{¿Sí?}
{215}{}{Adiós.}
{216}{}{Ya veo.}
{217}{}{Nada en especial, no te preocupes. En su mayoría, he hecho los quehaceres del hogar igual que en la Villa. Pero es más difícil y más a menudo. Los colonos son tan... crueles. Los hombres lo han tenido difícil, los obligan a trabajar en la mina.}
{218}{}{He oído que es una gran ciudad en el sur, pero jamás he ido allá. Las caravanas viajan entre Flagstaff y Fénix. Pregúntale a los demás colonos, seguramente sepan algo.}
{219}{}{Hugo y Sancho planeaban cavar un túnel y escapar de la mina. No hemos vuelto a saber de ellos.}
{220}{}{Ellos no nos dejarán ir sin razón alguna. Puedes hablar con su jefe, pero no creo que nos escuche, a no ser que tengas algo con lo que persuadirlo.}
{221}{}{¿Qué tal si escapamos?}
{222}{}{Ya hubiéramos escapado hace mucho si no fuera por estos collares. Si nos alejamos demasiado de aquí, nos matarán de inmediato. Dicen que los controla esa antena gigante de allá, pero ninguno de los prisioneros sabe algo al respecto.}
{223}{}{No quieres que vaya hacia allá, ¿cierto?}
{224}{}{No se trata únicamente de los peligros del viaje, es la ciudad en sí. Cuentan muchas cosas acerca de ella, ninguna es buena. Además, una vez tu tío Miguel se fue con una caravana a Fénix y jamás volvió. Intenta encontrarlo, quizás pueda ayudarte.}
{225}{}{Faber los ha dejado ir, es hora de salir de la Villa.}
{226}{}{¡Somos libres! No te preocupes de nosotros, podremos volver por cuenta propia. Tu padre te necesita, lo enviaron al sur. ¡Sálvalo!}
{227}{}{Nos vemos en la Villa, mamá.}
{228}{}{Los guardias están muertos, pueden irse.}
{229}{}{Esos collares ya no son ningún problema. Pueden quitárselos.}
{230}{}{¡Maravilloso! Pero, ¿cómo vamos a evadir a los guardias?}
{231}{}{Todavía tengo que pensar en eso.}
{232}{}{Déjamelos a mí, los sacaré de aquí.}
{233}{}{¿En serio sabes lo que haces? Apenas salgamos del corral, los guardias nos atacarán. No podremos hacer nada contra ellos.}
{234}{}{No te preocupes, sé lo que hago.}
{235}{}{Quédate aquí dentro hasta que diga lo contrario.}
{236}{}{Está bien, vámonos. Podemos hablar al estar fuera de la guarnición.}
{237}{}{Vámonos.}
{238}{}{Esto es malo, no puedo rescatarte por mi cuenta. ¿Habrá alguien que nos ayude?}
{239}{}{Los únicos que podrían ayudarnos son los Rangers. Su base está al sur de la Villa, junto al Colorado. Pero ten cuidado si les pides ayuda, ellos no ofrecerán su protección sin pedirnos algo a cambio.}
{240}{}{¿Qué tal si los ayudo a escapar?}
