{100}{}{Ves a un mercenario.}
{101}{}{Ves a un viejo 'conocido'.}

{110}{}{He visto plantaciones así en el yermo, no es un recuerdo muy lindo que digamos.}
{111}{}{¡Ah, Fénix! El mejor lugar que he conocido, y también el peor.}
{112}{}{¿Crees que tu gente ande por aquí?}
{113}{}{¿Cómo llegamos aquí? Esto es territorio de los Rangers.}
{114}{}{¿Perdiste la cabeza? ¡Deberíamos haber traído Rad-X antes de entrar aquí!}
{115}{}{Creo que hay gente por aquí.}
{116}{}{Quizás nos den un pescado, ¿no?}
{117}{}{Este lugar me da mala espina, mejor me preparo para lo peor...}
{118}{}{Jamás he venido aquí. Me pregunto qué clase de gente habrá.}
{119}{}{Hay un pueblo por allá, no les gustan los forasteros.}
{120}{}{Volver a pasarse por aquí se siente raro. Lo bueno es que la única persona que me reconoce eres tú.}

{200}{}{(De la nada, te encuentras con un viejo 'conocido' - el saqueador del sótano de la Villa. Sus heridas están mejor.) Vaya, pero miren quien es. Joder. ¿Cómo terminaste aquí?}
{201}{}{Intento salvar a mi familia. ¿Por qué te sorprende?}
{202}{}{Vaya, eso sí que será difícil. Mientras estés aquí, no te metas en mi camino.}
{203}{}{¿Cómo puedes hablarme así? ¡Te salvé la vida!}
{1203}{}{Eres un irrespetuoso. ¡Yo te salvé la vida!}
{204}{}{Supongo que te debo una, ¿no? Mira, quizás podamos sacar partido de esto.}
{205}{}{¿De qué estás hablando?}
{206}{}{Se acabaron mis días de mercenario, Faber no me quiere de vuelta y no tengo a donde ir. Quizás necesites ayuda buscando a tu familia. Por }
{207}{}{Se acabaron mis días de mercenario, Faber está muerto y no tengo a donde ir. Quizás necesites ayuda en tu misión. Por }
{208}{}{ chapas, viajaré contigo. Te vendrá bien un guía, no conoces el mundo como yo.}
{209}{}{¿Eso es todo? Bueno, aquí las tienes.}
{210}{}{No te pagaré para que seas mi 'ayudante'.}
{211}{}{Me lo pensaré.}
{212}{}{Entonces piérdete.}
{213}{}{Hm.}
{214}{}{}
{215}{}{¿En serio? ¿Confías en mí después de lo que pasó en la Villa?}
{1215}{}{¿En serio? ¿Confías en mí después de lo que pasó en la Villa?}
{216}{}{Sí, quédate a mi lado. Serás mi guardaespaldas.}
{217}{}{Es la mentira más grande que he escuchado. Pero no tengo nada mejor que hacer.}
{218}{}{Ahora serás mi guardaespaldas, vámonos.}
{219}{}{Es la mentira más grande que he escuchado. }
{220}{}{Tu actitud me empieza a dar coraje. Bueno, ¿cuánto quieres?}
{221}{}{Puedes seguir pudriéndote aquí, perdedor.}
{222}{}{Tengo una mejor idea, nos repartimos el botín que encontremos, mitad y mitad.}

{230}{}{¡Boo-hoo!}
{231}{}{El yermo te ha hecho un desastre. No me hagas perder el tiempo - ¡Lárgate!}
{232}{}{Buh, buh.}

{240}{}{¿A dónde vamos, gran líder?}
{241}{}{Quédate a mi lado.}
{242}{}{No tan rápido. Tenemos que hablar unas cosas.}
{243}{}{Quiero que vengas conmigo otra vez.}
{244}{}{Es hora de que vayamos por nuestros caminos. Puedes irte.}
{245}{}{¿Eso fue todo? Mierda, esperaba más. Si me necesitas, te estaré esperando justo aquí.}
{246}{}{Lo que tú digas.}
{247}{}{Claro que no. Estoy cansado de acompañarte.}
{248}{}{Yo decido quién se queda y quién no.}

{250}{}{¿Qué pasó?}
{251}{}{[Sigue moviéndote]}
{252}{}{Enfunda tu arma.}
{253}{}{Lo que digas. Pero no me voy a quedar parado si empiezan a dispararnos.}
{254}{}{De acuerdo.}
{255}{}{Quítate la armadura.}
{256}{}{¿De verdad es necesario?}
{257}{}{Hazlo de una vez.}
{258}{}{}
{259}{}{}

{260}{}{¿Qué quieres?}
{261}{}{¿A quién le podríamos robar?}
{262}{}{Me vendría bien algo de acción.}
{263}{}{¿Cuál es el plan?}
{264}{}{¿Ahora qué? ¡Te estás volviendo una molestia!}
{265}{}{Tengo una idea: ¡Encontremos a algún fortachón y lo lanzamos de un edificio!}
{266}{}{¡Tengo ganas de pelear!}
{267}{}{¿Cuándo nos vamos a repartir las chapas?}
{268}{}{¿Alguna vez pensaste en empezar una pandilla?}
{269}{}{Necesito un arma mejor. ¡O mejor aún, dos!}

{300}{}{Tengo algunas preguntas.}
{301}{}{¿De qué se trata?}
{302}{}{Nada más, por ahora.}
{303}{}{¿Qué metas tienes?}
{304}{}{Sobrevivir. Es todo lo que importa.}
{305}{}{Comprendo.}
{306}{}{¿Sientes algún remordimiento por lo que pasó en la Villa?}
{307}{}{Ni uno.}
{308}{}{¿Qué piensas de Faber?}
{309}{}{No es el peor tipo de Arizona. Siempre puedes encontrar peores.}
{310}{}{¿Sabes cómo llegar a Fénix?}
{311}{}{Sí, sé en donde está.}
{312}{}{Marca la ciudad en el mapa.}
{313}{}{Aquí está. ¿Vamos a Fénix? Hagas lo que hagas, siempre llegas ahí.}
{314}{}{¿Cuáles son tus armas preferidas?}
{315}{}{Pistolas, subfusiles y revólveres - es mi arsenal preferido.}
