{100}{}{Ves a Látigo, el supervisor.}
{101}{}{Ves a un hombre enfadado y gritón.}
{102}{}{¿Y tu pala, esclavo? Ah, no eres uno de ellos... Menos mal, porque te hubiera golpeado hasta dejarte inconsciente.}
{1102}{}{No debería estar aquí, señorita. En este lugar solo hay criminales y esclavos.}
{103}{}{¡Fuera de aquí!}
{104}{}{Fuera de mi camino, rata.}

{110}{}{¡Trabajen, estúpidos! ¡Están reconstruyendo América!}
{111}{}{¡Más les vale que trabajen más rápido!}
{112}{}{¡Apresúrate, pedazo de mierda!}
{113}{}{¡Le quebraré la espalda al primer flojo que vea!}
{114}{}{¡Te voy a dar mierda de rata para la cena!}
{115}{}{¡El que trabaje duro comerá carne de verdad!}
{116}{}{¿A dónde crees que vas? ¡Es allá! ¡Allá, te digo!}
{117}{}{}
{118}{}{}
{119}{}{}

{200}{}{¿Acaso quieres problemas?}
{1200}{}{Vaya, vaya, qué sorpresa. Me daría mucha pena que ensucies esas hermosas manos trabajando aquí.}
{201}{}{No, pero parece que tú sí.}
{1201}{}{Pero no sientes pena por ese esclavo al que acabas de golpear, ¿verdad?}
{202}{}{Sí, me encanta patearles la cabeza a los idiotas que no conocen su lugar en el mundo.}
{203}{}{¿Qué demonios te pasa, imbécil?}
{204}{}{¿Qué quieres decir, idiota?}
{205}{}{¡Cállate! ¿Qué crees que haces, hijo de puta? ¿Quieres unirte a los esclavos de la mina, verdad? ¡Te mataré! ¡Te haré comer mierda! ¿¡Me escuchas!?}
{206}{}{Sí, señor. Perdón, señor.}
{207}{}{No me asustas. Jódete, idiota.}
{208}{}{¡TE MATARÉ, PENDEJO DE MIERDA!}
{1208}{}{¡TE MATARÉ, PERRA ESTÚPIDA!}
{209}{}{Sí, claro, imbécil...}
{210}{}{Ese esclavo no merecía ser tratado así.}
{211}{}{¿Y qué sabes tú? Aquí los esclavos son sólo criminales y basura humana. Si quieres hacerte un bonachón, te agarraré y te pondré un collar. ¿Entendido?}
{212}{}{Inténtalo y te meteré el collar por el culo, imbécil.}
{213}{}{Sí, señor. Perdón, señor.}
{214}{}{De ninguna manera, señor.}

{220}{}{¡Todos, atrás! ¡Esto es una conspiración! Están... ¡Están todos bajo arresto! ¡Haré que trituren las piedras con los dientes!}
{221}{}{Te volviste loco, te haré entrar en razón, pero a los golpes...}
{222}{}{Oye, yo no tengo nada que ver. Enójate con el tipo de allá.}
{223}{}{Hablemos de esto, ¿te parece?}
{224}{}{¡No voy a caer en eso! ¿Quieres deshacerte de este capataz? Me las vas a pagar.}
{225}{}{La orden fue firmada por Faber. Cálmate, antes de que sea demasiado tarde.}
{226}{}{Grrr... No te saldrás con la tuya. Ustedes lo pagarán, ¡lo juro!}
{227}{}{Sí, claro.}
