{100}{}{Ves a un bandido, está armado.}
{101}{}{Ves a un prisionero fugitivo, está armado y es peligroso.}
{102}{}{¡Da un paso más y estás muerto!}
{103}{}{Parece que la ciudad ha empeorado.}
{104}{}{¡Guarda el arma o los mato a todos!}

#Floating lines
{110}{}{¡Pon las chapas en la mesa, rápido!}
{111}{}{Podemos hacerlo por las buenas o por las malas, tú eliges.}
{112}{}{¡Dame las chapas, ahora!}
{113}{}{Me están agotando la paciencia.}
{114}{}{¡Dame las chapas o te mato?}
{115}{}{¡Pónganse en el piso, ahora!}

#Dialogue
{200}{}{¡Tú! Dame todas tus chapas. ¡Y no intentes nada!}
{201}{}{Cálmate, ya te escuché, tengo 50 chapas, no le hagas daño a nadie...}
{202}{}{¿Eso es todo? Mierda, no llegaré muy lejos... Ponte contra la pared, y cuenta hasta a mil.}
{203}{}{Eh, claro, lo que digas...}
{204}{}{Suficiente, ¡es hora de darte una lección!}
{205}{}{Cálmate, no es necesario que hieras a nadie. Todavía tienes tiempo de arrepentirte.}
{206}{}{¡Te dije que me des las chapas! ¡Ahora!}
{207}{}{Ya, ya, llévate todas mis chapas, pero no le hagas daño a nadie...}
{208}{}{¿¡De qué mierda hablas!? Si me vuelven a atrapar, estoy acabado.}
{209}{}{Pero hacer esto no resolverá tus problemas.}
{210}{}{Poca madre, tienes razón... Ya, date la vuelta y cuenta hasta mil.}
{211}{}{No te daré nada.}
{212}{}{¡Eso ya lo veremos!}
{213}{}{¡Ten cuidado con dónde apuntas esa cosa!}
{214}{}{¡Acabemos con esto!}
{215}{}{¡No tengo chapas, lo juro!}
{216}{}{¡MIENTES!}
