{100}{}{Ves a un ranger en frente tuyo.}
{101}{}{Ante ti se encuentra un ranger, sus ojos demuestran una determinación inquebrantable.}
{102}{}{Me iré de aquí tan pronto como empaque mis cosas.}

#First dialogue
{200}{}{¡Alto ahí! Da un paso más y te volaré los sesos.}
{201}{}{Está bien, te escucho, aquí me quedo. Pero no me dispares.}
{202}{}{Bien. Sé lo que estoy haciendo, así que no intentes nada.}
{203}{}{[Más]}
{204}{}{¿Me estás amenazando? ¡Sí que los tienes bien puestos!}
{205}{}{(te apunta velozmente con el arma)}
{206}{}{¡Espera, no me dispares!}
{207}{}{¡Hijo de perra!}
{208}{}{Cálmate. ¿Qué está ocurriendo?}
{209}{}{Me parece que no entiendes lo que está pasando. Esto es un arma. Está cargada. Te matará si te mueves. ¿Lo entendiste?}
{210}{}{Sí, entendí.}

{211}{}{Hmm. (baja el arma) No parece que seas un mercenario. ¿Quién eres y qué haces aquí?}
{1211}{}{Hmm. (baja el arma) No parece que seas una mercenaria. ¿Quién eres y qué haces aquí?}
{212}{}{Habla, antes de que te desparrame la cabeza.}
{213}{}{Uno de los dos va a morir, y no seré yo.}

{214}{}{¿Qué? ¿Qué quieres?}
{215}{}{(baja el arma) Hmm. Te perdiste, ¿verdad? La gente como tú me da pena. Tengo una bala, quizás debería dispararte y sacarte de tu miseria.}
{216}{}{¿Disparar? ¿Yo? ¿Miseria?}
{217}{}{No, no debería hacer eso. Es mejor que hagas de cebo para los mercenarios. Ve a dar una caminata. ¿Lo entendiste? ¡Anda, muévete!}
{218}{}{Ve a dar una caminata. ¡Anda!}

{220}{}{Sólo soy un viajero, estoy revisando si estas ruinas contienen algo de valor.}
{1220}{}{Sólo soy una viajera, estoy revisando si estas ruinas contienen algo de valor.}
{221}{}{Eso no me convence, debes estar aquí en contra de tu voluntad, o trabajas para los mercenarios de la guarnición.}
{222}{}{No es posible pedirle comida a la guarnición, hay que hurgar entre las ruinas.}
{223}{}{Estoy buscando chatarra, eso es todo.}
{224}{}{Esto solía ser el Museo de Arizona del Norte, era una de las atracciones de la ciudad.}
{225}{}{Te estoy diciendo la verdad.}
{226}{}{Te mentí, pero tengo una razón por la que estar aquí.}
{227}{}{Exacto. Y planeo llevarles tu cabeza.}

{230}{}{(vuelve a levantar el arma) Debes pensar que soy un idiota.}
{231}{}{No puedo engañarte, ¿verdad? Estoy aquí por otra razón.}
{232}{}{Me llevaría demasiado tiempo explicártelo, es mejor que acabe contigo de una vez.}

{233}{}{De acuerdo, digamos que eso es verdad. Pero, ¿cómo conseguiste evadir mis trampas?}
{234}{}{Quizás atrapes a un niño con esas cosas, pero yo cuento con la experiencia de un trampero.}
{235}{}{Puse mucha atención, eso es todo.}
{236}{}{¿Trampas, en serio? ¡Chinga tu madre! Deberías haber colocado un aviso afuera.}
{237}{}{(muestras tus heridas) Bueno, eso no es del todo cierto.}
{238}{}{No lo sé, supongo que tuve mucha suerte.}

{240}{}{Supongo que debería haber prestado más atención en las clases de trampas.}
{241}{}{Entonces, ¿no me vas a disparar?}
{242}{}{Que respuesta más estúpida... (se prepara para dispararte)}
{243}{}{¡Espera, dame un momento! ¡Estoy aquí por otra razón, lo juro!}
{244}{}{[Prepárate para el ataque]}
{250}{}{No debería matarte. Por ahora. Puedes irte, pero ten cuidado por donde pisas.}
{251}{}{Está bien.}
{252}{}{Espera, necesito preguntarte algunas cosas.}

{260}{}{Se podría decir que soy un cazarrecompensas. He oído que me pagarán bien por tu cabeza.}
{261}{}{Eso es cierto, a Faber le pesa la consciencia porque sabe que algún día, la justicia lo encontrará. Tu muerte servirá como un pequeño recordatorio...}
{262}{}{Empecemos de una vez.}
{263}{}{Espera, no vine aquí para pelear.}
{264}{}{Sí, claro. Especialmente porque te estoy apuntando a la cabeza.}
{265}{}{Yo estoy pensando en apuntar a la cabeza de Faber. Hagamos un equipo, ¿qué me dices?}
{266}{}{¡Al diablo con esto, peleemos!}
{267}{}{¿Qué estás tramando?}
{268}{}{Mis parientes están encerrados en el corral de la guarnición. Necesito liberarlos.}
{1268}{}{Mis parientes están encerrados en el corral de la guarnición. Necesito liberarlos.}
{269}{}{¿Así que eso te trajo aquí? (empieza a bajar su arma) Tiene sentido, es justo lo que haría Faber.}
{270}{}{No vas a dispararme, ¿verdad?}
{271}{}{Ahora que bajaste la guardia, ¡toma esto!}

{280}{}{Tengo una misión, estoy intentando liberar a mis parientes de la esclavitud.}
{281}{}{¿También los esclavizaron a ustedes? Los matones de Faber cada vez son más audaces. Solían capturar únicamente a criminales para hacerlos trabajar, pero ahora traen a personas inocentes.}
{282}{}{¿Y qué hay de tu arma? ¿Acaso planeas usarla contra mí?}

{283}{}{Estoy con los rangers, he venido a impartir la justicia a esta colonia.}
{284}{}{Es un gusto conocerte, pero no pedí refuerzos. Esto pondrá a mi cobertura en peligro.}
{285}{}{He venido aquí por voluntad propia.}
{286}{}{Entonces podremos llegar a un acuerdo. Pero si vienes aquí, asegúrate de que nadie te siga.}
{287}{}{Entiendo.}

# Re-dialogue
{300}{}{Te escucho.}
{301}{}{Hasta otro día, Ranger.}

# Traps
{310}{}{Muéstrame en dónde están tus trampas, o saldré de aquí con una sola pierna.}
{311}{}{Sólo los idiotas o los traidores preguntan tales cosas. Mi supervivencia depende de esas trampas, son mis secretos.}
{312}{}{Bueno, entonces mi destino depende de tus secretos. Adiós.}

{313}{}{Los dos somos rangers, puedes confiar en mí.}
{314}{}{Jeje, los nuevos reclutas siempre creen que son especiales. Ten cuidado con las puertas y no toques la puerta trasera.}
{315}{}{Te lo agradezco.}

{316}{}{¿Te preocupa que sea un espía de la colonia, no? No te preocupes, estoy contigo.}
{317}{}{Sí, quizás tengas razón... Ten cuidado con las puertas y no toques la puerta trasera.}
{318}{}{Gracias.}
{319}{}{Lo siento, no puedo.}
{320}{}{El ranger te ha revelado todas sus trampas en el interior del edificio.}
{321}{}{¿Acaso quieres que muera?}
{322}{}{No... Está bien, te mostraré. Pero recuerda, ten cuidado con las puertas, especialmente la de atrás del edificio.}
{323}{}{Gracias.}

# Questions
{330}{}{Háblame de ti.}
{331}{}{Soy el Ranger Kuyuk, de la División Este de los Rangers de Arizona.}
{332}{}{Tengo algunas preguntas más.}
{333}{}{Ya veo.}
{334}{}{¿Cómo te volviste un ranger?}
{335}{}{Los Rangers me acogieron cuando era un niño. Mi aldea fue atacada por esclavistas, he dedicado mi vida entera a prevenir que esas tragedias vuelvan a ocurrir.}
{336}{}{¿Viniste sólo?}
{337}{}{En lugares como Flagstaff, es más fácil trabajar por tu cuenta, hace que evadir a los mercenarios sea más fácil.}
{338}{}{No debe ser nada fácil, porque es un ranger contra una banda entera.}
{339}{}{Exacto. Cuando se trata de asuntos locales, nuestros comandantes prefieren no interferir, así que decidí lidiar con esto por cuenta propia. Sin embargo, nadie intentó detenerme cuando me fui.}
{340}{}{¿Crees que los Rangers vuelvan a aceptarte después de esto?}
{341}{}{Sigo siendo un ranger, con la placa y todo. Puede que me den una reprimenda por cómo he actuado, pero sigo siendo uno de ellos.}
{342}{}{Tienes un nombre interesante.}
{343}{}{Ya no quedan muchos de mi tribu, dudo que hayas oído hablar de nosotros.}
{344}{}{Debe ser un nombre Indio. Mojave, Hopi... ¿Quizás Navajo?}
{345}{}{Hmm. Me sorprendes. Por lo general, nuestras tribus se escondieron de los blancos después de la Lluvia de Fuego. Me fui de la Reserva cuando llegaron los esclavistas.}
{346}{}{Nuestras historias son parecidas, mi aldea sufrió ese mismo destino.}
{347}{}{Lo lamento... (te entrega varias balas de rifle) Úsalas. Véngate.}
{348}{}{Eh, gracias.}
{349}{}{Eso haré.}

{370}{}{¿Podrías hablarme sobre los rangers?}
{371}{}{¿Qué quieres saber?}
{372}{}{Dame más detalles sobre los rangers.}
{373}{}{Ya hablamos suficiente de los rangers.}
{374}{}{¿Quiénes son ustedes?}
{375}{}{Somos los guardianes de la Ley y el Orden. Nos dedicamos a cazar criminales, proteger asentamientos y a traerle la paz al yermo.}
{376}{}{Entiendo.}
{377}{}{Por lo tanto, el ranger promedio es un guerrero habilidoso y un maestro cuando se trata de sobrevivir en el yermo.}
{378}{}{¿Por qué no se cuentan más historias acerca de ustedes?}
{1378}{}{¿Por qué no se cuentan más historias acerca de ustedes?}
{379}{}{Porque no presumimos. Y porque la mayoría nos ve como cazarrecompensas y nada más.}
{380}{}{¿Qué se necesita para ser un ranger?}
{381}{}{Debes llevar a cabo cinco años de un entrenamiento muy duro, luego debes demostrar que estás listo a través de una misión. Hay muchos cadetes que ni siquiera pasaron del entrenamiento.}
{382}{}{¿Qué sucede con los que fracasan?}
{383}{}{Algunos mueren durante una misión, otros se van al yermo y trabajan como guardias, mercenarios o líderes de caravanas. Si tienes suerte, te dejan en la base con algún rol de apoyo.}
{384}{}{¿En dónde está la base de los rangers?}
{385}{}{¿Por qué debería contarte eso?}
{386}{}{No seas así, no les haré daño.}
{387}{}{Me interesa unirme a los rangers.}
{388}{}{Necesito la ayuda de los rangers para liberar a mis parientes.}
{389}{}{}
{390}{}{No puedo arriesgarme a hacer eso, podrías decirle esa información a mis enemigos.}
{391}{}{Eso es entendible, hablemos de otra cosa.}
{392}{}{Estoy de acuerdo. Cambiemos de tema.}
{393}{}{Está bien, te la indicaré en el mapa. La base está en el Río Colorado, se ubica en el interior de una presa vieja.}
{394}{}{Lo agradezco.}

# Re-dialogue
{400}{}{¿Podrías explicarme tu misión?}
{401}{}{Como ranger, mi deber es mantener la ley y la justicia. Al optar por la esclavitud, estos colonos quebraron esas reglas. Mis balas los castigarán.}
{402}{}{¿Qué era lo que me habías dicho sobre tu misión?}
{403}{}{Quiero preguntarte otra cosa.}
{404}{}{Volvamos a hablar de tu misión.}
{405}{}{Estás hiriendo a gente inocente, no sólo a los criminales.}
{406}{}{Para erradicar a un mal mayor, a veces debemos recurrir a uno menor. Es una pena, pero a veces no puedes evitar los daños colaterales.}
{407}{}{¿No te pesa la consciencia?}
{408}{}{No.}
{409}{}{Pero los colonos también apoyan a la ley y el orden.}
{410}{}{Claro, pero sólo dentro de su sociedad colonial, además de ser opresiva hacen eso a costa de los demás. Esto no puede seguir así. Nadie los quería en este lugar, nadie les pidió que construyeran una ciudad con la sangre de los esclavos.}
{411}{}{¿Qué es lo que intentas conseguir?}
{412}{}{No voy a detenerme hasta que Roy Faber esté muerto y los esclavos hayan sido liberados.}
{413}{}{Eso es ambicioso.}
{414}{}{¿Entonces tú eres el que disparó a las patrullas de la guarnición?}
{415}{}{Así es. Recibieron su merecido a causa de sus acciones.}
{416}{}{¿De qué 'acciones' estamos hablando?}
{417}{}{Fueron cómplices en los crímenes de Roy Faber; tiranía, esclavitud y bandidaje.}
{418}{}{¿Los Rangers están de acuerdo con el asesinato?}
{419}{}{Únicamente si es en defensa propia o por el bien mayor.}
{420}{}{¿Sabías que Faber ofrece chapas por tu cabeza?}
{421}{}{Debería triplicar su oferta.}
{422}{}{¿Qué sabes de Faber?}
{423}{}{Es un tirano con ambiciones, sueña con poseer su propio imperio. Pero en realidad, es sólo un criminal que controla a los demás a través del miedo y la violencia.}

{450}{}{Debo pedirte que te vayas de Flagstaff.}
{451}{}{Voy a quedarme.}
{452}{}{Entonces quédate, la verdad no me importa.}
{453}{}{Te arrepentirás, ya vas a ver.}
{454}{}{¿Qué puedo hacer para que cambies de opinión?}
{455}{}{No me detendré hasta que ya no haya más esclavitud en este lugar.}
{456}{}{Tu base fue hundida. ¿No deberías estar ayudando a los tuyos?}
{457}{}{¿De qué estás hablando?}
{458}{}{No es nada, sólo fue un rumor que escuché. Olvídalo.}
{459}{}{Parece que no te enteraste. Alguien abrió las compuertas y la presa fue arrasada. ¿No lo sabías?}
{460}{}{¿Cómo? Eso no puede ser verdad... Tengo que contactar a alguno de los puestos. Si eso es verdad, regresaré a la base.}
{461}{}{Entonces ve.}
{462}{}{El general ha ordenado que regreses a la base.}
{463}{}{¡Demonios! ¿¡Por qué no puede dejarme en paz!? Mi misión es muy importante, no puedo abandonarla.}
{464}{}{Piensa en los demás rangers, puede que tu ayuda en la base sea más importante de lo que pienses.}
{465}{}{Hmm. Quizás tengas razón. Quizás me enfoqué demasiado en la venganza. Está bien, había estado ignorando la radio, pero les hablaré por allí. Volveré a la base.}
{466}{}{Bien pensado.}
{467}{}{No estás siendo honesto contigo mismo, piensa bien tus razones.}
{468}{}{Voy a traer la justicia a estas tierras, esa es mi razón..}
{469}{}{Hablar contigo no servirá de nada. Quédate si eso quieres.}
{470}{}{No creo que pueda persuadirte. Me voy.}
{471}{}{No. Eso es lo que dices, pero sólo estás haciendo esto por tu pasado.}
{472}{}{¿Qué sabes tú de mi pasado? He peleado tanto, que he olvidado lo que es la paz... Lo mismo con el hogar y la familia... ¡Perdí todo eso, por culpa de la gente como Faber!}
{473}{}{Eso justo a lo que me refería. Deja de derramar sangre y vuelve con los tuyos.}
{474}{}{Si sólo puedes pensar en la venganza, no creo que pueda convencerte. Sigue luchando.}
{475}{}{Voy a quedarme.}
{476}{}{Quizás estoy demasiado enfocado en vengarme. El general me lo había advertido... Está bien, me iré de Flagstaff y volveré a la base. Gracias, amigo.}
{1476}{}{Quizás estoy demasiado enfocado en vengarme. El general me lo había advertido... Está bien, me iré de Flagstaff y volveré a la base. Gracias, señorita.}
{477}{}{Buena suerte.}
{478}{}{Ten cuidado allá afuera.}

{480}{}{Faber está muerto. ¿Estás satisfecho?}
{481}{}{Entonces lo que escuché era verdad. (respira profundo y toma una pausa) La verdad es que no siento nada. Pensé que acabar con el mal me traería la paz, pero por fin veo que no es el caso. Matar a Faber no resolverá nada, otro tirano ocupará su lugar y el ciclo continuará... Las personas nunca cambian. El general tenía razón, sólo pensaba en la venganza. Gracias por tu ayuda. Es hora de que regrese a la base.}
{482}{}{Me alegra que esto se haya resuelto.}
{483}{}{Buena suerte.}
