{100}{}{Ves a un niño.}
{101}{}{Ves al hijo de uno de los colonos.}
{102}{}{¡Me estafaste! ¡Te voy a acusar!}

{104}{}{Necesitas a un doctor de verdad. O quizás unas dosis de RadAway.}

#Response
{110}{}{Hola.}
{111}{}{Z-z-z}
{112}{}{Tengo unas heridas aquí. Y ahí. Ah, y acá.}
{113}{}{¡Me siento mucho mejor!}

{116}{}{Has empezado.}
{117}{}{Apenas encontraste una vena, en la cual inyectas un RadAway. Hará que tratarlo sea mucho más fácil.}
{118}{}{Es hora de empezar con el tratamiento.}
{119}{}{El paciente se está recuperando.}
{120}{}{Sigue así.}
