{100}{}{Ves a un minero.}
{101}{}{Ves a un hombre sucio con una mirada intensa y desesperada.}
{102}{}{No quiero seguir viviendo.}
{1102}{}{No quiero seguir viviendo.}

{200}{}{(Ves a un hombre de aspecto demacrado con la ropa sucia y rota. Sostiene un cuchillo cerca de su collar y el sudor le resbala por la frente.)}
{201}{}{¿Qué estás haciendo?}
{202}{}{Em...}
{203}{}{¡Atrás! ¡Voy a hacerlo! ¡Es mejor que vivir otro día más!}
{204}{}{No lo harás. Mírate, eres un debilucho.}
{205}{}{¡Cállate! Ellos me llevaron a este punto. ¿Qué más puedo hacer?}
{206}{}{Típico, siempre ponen excusas y más excusas...}
{207}{}{¡Cállate! ¡Cállate de una vez!}
{208}{}{¿Acaso vas a llorar, mamón?}
{209}{}{Entiendo que quieras salir de aquí, pero deja de tocar el collar o morirás.}
{210}{}{No hagas esto. ¡El collar te matará!}
{211}{}{Lo siento, no puedo ayudarte. Vamos, ¿qué esperas?}
{212}{}{¡YA LO SÉ! Pero hasta aquí llegué. Si me muero, al menos escaparé de todo este sufrimiento. ¿Y qué tal si no me mata? ¿Y si nos mintieron sobre los collares? Entonces puedo salir corriendo.}
{213}{}{¿Por qué no pruebas tu teoría? Se valiente. Hazlo.}
{214}{}{Eres un debilucho, debería entregarte al supervisor, será divertido.}
{215}{}{Piénsatelo bien, no dejes que te controlen tus emociones.}
{216}{}{¿Y qué vas a saber tú? ¡Me tienen de esclavo! Sí, me encarcelaron por una razón, ¿pero debería aguantar que los guardias me humillen y me golpeen? ¡No es justo!}
{217}{}{Sea lo que sea que hayas hecho, fue culpa tuya. Nadie sentirá pena si muere un criminal como tú.}
{218}{}{Hazlo de una vez. ¿Qué estás esperando?}
{219}{}{Está bien. Intentaré ayudarte, tengo que sacar a mi familia de aquí.}
{220}{}{¿En serio? Entonces perdón, me dejé llevar. Mira, dicen que controlan los collares por radio. Hay una antena en la guarnición, debes apagarla o destruirla. ¿Crees que puedas hacer eso?}
{221}{}{Está bien, lo intentaré. Espera a mi señal.}
