{100}{}{Ves a un salvaje.}
{101}{}{Ves a uno de los prisioneros de la colonia. Tiene rasgos faciales más fuertes que los demás.}

#Dialogue
{200}{}{Mantén la distancia, forastero. Los otros no pensarán bien de ti.}
{1200}{}{Aléjate, mujer. Los otros no pensarán bien de ti.}
{201}{}{Adiós.}
{202}{}{¿Cómo te llamas?}
{203}{}{Me llaman Aullador, pero no creo que puedas pronunciar mi nombre real.}
{204}{}{¿Así que no eres de por aquí?}
{205}{}{Yo *soy* de aquí. Mi tribu vivió en estas montañas por tres generaciones. Y ahora soy el último que queda.}
{206}{}{¿Qué le pasó a tu tribu?}
{207}{}{Nos atacaron algunos hombres malvados. Se llevaron todo lo que teníamos y nos forzaron a trabajar en la mina. Desde ese entonces, soy el último de la tribu.}  
{208}{}{¿Te gustaría salir de aquí?}
{209}{}{No tengo ningún lugar a donde ir. Destruyeron a mi hogar y mataron a mi familia. Lo único que me queda es esperar la muerte.}

{210}{}{Digamos que empieza un escape. ¿Me ayudarías?}
{211}{}{Es una batalla que no tendría sentido. No es lo mío.}
{212}{}{Hmm. Eso sería una muerte digna para un guerrero. Te ayudaré.}
{213}{}{Genial, espera mi señal.}
{214}{}{Como quieras.}
