{100}{}{Ves a un prisionero.}
{101}{}{Ves a uno de los prisioneros de la colonia. Su apariencia no te da confianza.}

#Dialogue
{200}{}{¿Qué quieres?}
{201}{}{Adiós.}
{202}{}{¿Por qué estás aquí?}
{203}{}{(te da una sonrisa retorcida) Asesinato.}
{204}{}{¿Sólo uno?}
{205}{}{Ya perdí la cuenta. Yo y mis hermanos teníamos la Interestatal 17 llena de cadáveres, le robábamos a los viajeros. Extraño esos días.}
{206}{}{Dudo que hayan habido tantos viajeros.}
{207}{}{Bueno, quizás exageré un poco. Mierda, a lo mejor nunca maté a nadie. Pero las carreteras cada vez están peor estos últimos años. Ahora hay más gente en el yermo, pero no hay espacio para todos. Así que van a la carretera, caminando sin rumbo alguno.}
{208}{}{Pero, ¿cómo acabaste aquí?}
{209}{}{Robamos ganado a unos pastores. Resulta que el ganado era para unos tipos importantes en Fénix, por lo que contrataron cazarrecompensas. Nos acorralaron en las ruinas, eran máquinas de matar, estaban entrenados y bien armados. Tuvimos que rendirnos, pero me arrepiento, ser ejecutado era lo mejor.}
{210}{}{Si intento un escape, ¿me ayudarás?}
{211}{}{¿Nosotros dos contra los guardias? ¡Perdiste la cabeza!}
{212}{}{¿Nosotros dos contra los guardias? Bueno, si lo piensas bien, es posible que salgamos con vida, y si me muero, que así sea. Bueno, estoy dentro. ¿Me darás un arma?}
{213}{}{Tengo una. Escóndela en tu ropa para que nadie la vea.}

{214}{}{No. Prepárate.}
