{100}{}{Ves a un mercenario.}
{101}{}{Ves a uno de los mercenarios de Faber. Está listo para ayudarte a lidiar con los salvajes.}

{110}{}{No te preocupes, te cuidaré la espalda.}
{111}{}{Ya no habrá ni un solo tiraflechas por acá.}
{112}{}{Dime a quién le disparo y yo me encargo del resto.}
{113}{}{Juntos podemos hacerlo.}
{114}{}{Sólo recuerda como era Arizona antes de que llegara Faber.}
{115}{}{Malditos salvajes...}
{116}{}{Esta tribu siempre ha sido un problema para nosotros.}
{117}{}{Si ves uno de los salvajes, hazmelo saber.}
{118}{}{}
{119}{}{}
