{101}{}{Ves el tieso cadáver de un prisionero. Desconoces la causa de su muerte.}  
{102}{}{Ves el tieso cadáver de un prisionero. Murió intentando quitarse el collar.}  
{103}{}{Enterraste el cadáver del prisionero. Alguien tenía que hacerlo.}  
{104}{}{Ponerte a cavar en medio de una pelea no es la mejor idea que has tenido.}  
{105}{}{El prisionero murió de un fuerte choque eléctrico mientras intentaba quitarse el collar.}  
{106}{}{Su final no algo que deba envidiarse.}  
{107}{}{¡Ja! Qué patético.}  