{110}{}{Esta radio está descompuesta.}
{111}{}{Conseguiste deshabilitar el transmisor de la radio. Ahora la colonia carece de comunicaciones por radio.}
{112}{}{No tienes la menor idea de cómo funciona.}
{113}{}{No es posible reparar esto.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión.}
{202}{}{Regresar}
{203}{}{El transmisor de la radio no responde.}

{210}{}{Deshabilita el control de los collares.}
{211}{}{¡Cuidado! Deshabilitar los collares reducirá el control sobre los prisioneros. ¿Está seguro?}
{212}{}{Sí, deshabilitar los collares.}
{213}{}{El control de los collares fue deshabilitado.}

{214}{}{Copia la frecuencia de los mercenarios para espiar sus comunicaciones.}
{215}{}{Frecuencias copiadas.}

{216}{}{Nota del ingeniero}
{217}{}{Esta sagrada máquina fue traída desde el campo de los Navajo, a 11 millas de Flagstaff, y se instaló en la colonia en honor al Fuego Santo en el año 2*** por Su humilde sirviente ** a orden de Aaron, Señor de Fénix. Que se le caiga el cielo a cualquiera que la profane.}
