{200}{}{"Bienvenido a Flagstaff - ¡La mejor ciudad al norte de Fénix! Fundada en el año 2163."}
{201}{}{Ya me cansé de este cartel.}
{202}{}{¿La mejor ciudad? Quizás valga la pena echar un vistazo.}

{210}{}{¿Qué es eso del toque de queda?}
{211}{}{"El toque de queda es desde las 00:00 hasta las 06:00. Está prohibido llevar armas al descubierto, por favor, guárdalas."}

{220}{}{¿Qué dice el mapa de la colonia?}
{221}{}{Hay un diagrama muy básico con 4 áreas distintas: Bloque A (el área residencial, estás aquí), al este se encuentra el Bloque B (la guarnición y la prisión) al norte se encuentra el Bloque C (la mina de uranio), más al este se encuentran los escombros de una ciudad antigua.}
{222}{}{Hay un aviso sobre la ciudad antigua.}
{223}{}{"¡Peligro! Se sospecha que un grupo de saqueadores está operando entre las ruinas de la ciudad antigua. ¡Ten cuidado!"}
{224}{}{Alguien dibujó una X roja sobre el aviso, parece que ya no es relevante.}

{230}{}{Hay muchas cosas que están mal escritas...}
{231}{}{(Encontraste un montón de errores gramáticos en la sección de noticias)}
{232}{}{¡Agh, cuántos errores! Tengo que corregirlos...}
{233}{}{(Corregiste los errores gramáticos)}
{234}{}{Mucho mejor.}
{235}{}{(No encontraste ningún error)}
{236}{}{No sé si de verdad esté mal escrito, mejor lo dejo así.}
