{100}{}{Ves al Sr. Kogan.}
{101}{}{Ves al Sr. Kogan. Todavía lleva su traje sucio.}
{102}{}{La transacción fue un éxito.}

{110}{}{Vigila bien el área, no podemos dejar que nadie interfiera.}
{111}{}{Ve a lidiar con esos idiotas mientras me ocupo de la caravana.}
{112}{}{Vuelve al garaje, hablaremos allá.}
{113}{}{Sal de mi vista.}
{114}{}{Volveré al garaje, pero Lucas pagará por su insolencia.}
{115}{}{Esa caravana era nuestra última esperanza para un mañana mejor...}

{120}{}{No hay moros en la costa.}
{121}{}{Carajo, son los hombres de Lucas. Ve a lidiar con ellos.}
{122}{}{Ya terminamos. Puedes volver al garaje.}

{200}{}{Tú no eres nadie. Lárgate de la ciudad y no tendrás problemas.}
{201}{}{Lucas te ofrece un acuerdo, dale el control de la fábrica.}
{202}{}{Ya no puedo confiar en Lucas, le robó a los demás chatarreros y arrebató el territorio de Trayvon. Dile que si no se larga de mi ciudad, hoy será el último día de su corta vida.}
{203}{}{Lucas no se irá a ningún lado. Decídete de una vez.}
{204}{}{Está bien, iré a hablar con él.}
{205}{}{Muy bien, saca a sus hombres de aquí antes de que arruinen todo. ¡Haz lo que digo!}
{206}{}{Parece que ya empezó...}
{207}{}{Lucas y los suyos son los únicos que saben arreglar la fábrica. Deberías cooperar con él.}
{208}{}{Hmm... Es verdad que Trayvon y sus hombres no tienen la menor idea de eso. Son buenos hurgando entre las ruinas, pero la fábrica necesita las habilidades de alguien como Lucas.}
{209}{}{Bueno, ¿entonces qué le digo?}
{210}{}{Claro que no, no se irá con las manos vacías.}
{211}{}{Acepto. Puede quedarse con la fábrica y dirigirla, pero que no espere impuestos bajos en MI ciudad. No olvidaré esto.}
{212}{}{Gracias, Sr. Kogan.}
