{100}{}{Ves a un chatarrero enfermo.}
{101}{}{Ves a uno de los chatarreros de Trayvon, es obvio que sufre de alguna enfermedad.}
{102}{}{Has tratado al chatarrero con éxito.}
{103}{}{No eres capaz de hacer un diagnostico, mucho menos tratarlo sin la medicina adecuada.}
{104}{}{Este chatarrero está sufriendo de una alta dosis de radiación. Tus habilidades no serán suficientes para curarlo sin medicamentos.}

{110}{}{*Cof cof*}
{111}{}{Perdón, no me siento bien.}
{112}{}{Me enfermé cuando regresamos de las ruinas}
{113}{}{*¡ACK!* ...Estoy enfermo, si no lo notaste.}
{114}{}{...No es contagioso, no te preocupes.}

{115}{}{Gracias por ayudarme, ya estaba preparando el funeral.}
{116}{}{Gracias a ti, seguiría sufriendo hasta morirme.}
{117}{}{Me asombran los curanderos como tú.}
{118}{}{Me enfermé en las ruinas, ten cuidado si vas.}
{119}{}{¿Buscas a los tuyos? Sé que se los llevaron al este, pero nada más.}

{120}{}{Ay...}
{121}{}{*Cof cof*}
{122}{}{*ACK!*}
{123}{}{Agh...}
{124}{}{*Quejido*}
{125}{}{Hrr...}
