{100}{}{Ves a un ciudadano.}
{101}{}{Ves a uno de los habitantes de Ciudad Garaje.}

{110}{}{¿No te vas a quedar, verdad? Eso es bueno.}
{111}{}{Es mejor que te largues. No hay espacio para más gente.}
{112}{}{¿Es tu primera vez en una ciudad?}
{113}{}{Ciudad Garaje es un buen sitio, creo que te encantará.}
{114}{}{¿Piensas en quedarte?}
{115}{}{Aquí tenemos nuestras reglas, paleto.}
{116}{}{No entiendo por qué sigue viniendo gente, estamos en decadencia.}

{120}{}{¡Hola! ¿Cómo estás?}
{121}{}{¡Miren quién llegó! ¿Te quedarás unos días?}
{122}{}{¿Qué tal la cosecha, amigo?}
{123}{}{Ten un buen día, amigo.}
{124}{}{Lo siento si te tratamos mal al principio.}
{125}{}{No sabíamos que los aldeanos de la Villa fueran así de amistosos.}
{126}{}{¿Te puedo ayudar en algo?}

{1120}{}{¡Hola! ¿Cómo estás?}
{1121}{}{¡Miren quién llegó! ¿Te quedarás unos días?}
{1122}{}{¿Qué tal la cosecha, señorita?}
{1123}{}{Tenga un buen día, señorita.}
{1124}{}{Lo siento si te tratamos mal al principio.}
{1125}{}{No sabíamos que los aldeanos de la Villa fueran así de amistosos.}
{1126}{}{¿Te puedo ayudar en algo?}

{130}{}{No te me acerques.}
{131}{}{Ándate a tu granja y no me molestes.}
{132}{}{Dile al anciano de tu pueblo que es un bastardo arrogantes y tacaño.}
{133}{}{La Villa no es conocida por ser amable con los demás.}
{134}{}{¿Será que todos en tu cerro son igual de pendejos que tú?}
{135}{}{Ya entiendo por qué la Villa nos cobra tan caro.}
{136}{}{Te seré honesto, me alegro ver cómo se llevaron a tus parientes.}
{137}{}{Cuando nos moríamos de hambre, ustedes nos cobraron más caro aún.}
{138}{}{Piérdete, no eres más que un campesino.}
{139}{}{Le dieron su merecido a la Villa.}
