{100}{}{Ves a Frank.}
{101}{}{Ves a uno de los ciudadanos de Ciudad Garaje.}
{102}{}{Oh-oh, necesito ir al baño, tan pronto como pueda...}
{103}{}{Frank no está en condiciones de hablar.}
{104}{}{Boo-uh...}
{105}{}{Hrrr...}
{106}{}{Tras un buen trago, Frank se desmaya en su destartalada silla.}
{107}{}{Oh-oh...}
{108}{}{No me siento nada bien...}

#Before the quest
{200}{}{¿Qué quieres? ¿Por qué estás en mi casa?}
{201}{}{Soy un ladrón.}
{1201}{}{Soy una ladrona.}
{202}{}{Genial, justo lo que me faltaba... ¡Fuera de aquí, estúpido!}
{1202}{}{¡Piérdete, puta! No tengo dinero para ti.}
{203}{}{Adiós}
{204}{}{Oye, sólo bromeaba. Soy tu nuevo vecino.}
{1204}{}{Oye, sólo bromeaba. Soy tu nueva vecina.}
{205}{}{¿Crees que soy tonto? Nadie viene aquí por voluntad propia. ¡Ya no hay trabajos! Pero si de verdad quieres quedarte aquí, hazme un favor y no me molestes.}
{206}{}{Bueno, como tú digas.}
{207}{}{Me gustaría conocer a mis vecinos.}
{208}{}{¿Por qué desconfías tanto de tus vecinos?}
{209}{}{}
{210}{}{hazme un favor y déjame en paz.}
{211}{}{¿Por qué desconfías tanto de tus vecinos?}
{212}{}{Bueno, como tú digas.}
{213}{}{En este pueblo no puedes confiar en nadie. Hasta los vecinos quieren lo que te pertenece. Sal de tu casa, y alguien sacará las ganzúas para meterse a robar.}
{214}{}{¿Alguien te robó, verdad?}
{215}{}{Claro, siempre están desapareciendo cosas. Todo se fue cuesta abajo cuando cerraron la mina, porque dejó a muchos sin nada.}
{216}{}{Para ser exactos, ¿qué te robaron?}
{217}{}{Mi máquina soldadora. Es valiosa porque todavía funcionan, y no hay muchas así en la ciudad. Me ganaba la vida con ella, ¿qué voy a hacer ahora?}
{218}{}{Ya veo. Quizás pueda buscarla.}
{219}{}{¿En serio? O quizás esto es parte de tus planes - me la robaste y ahora la 'encontrarás'... ¿Por qué demonios te echo la culpa? Acabas de llegar, y me la robaron hace un tiempo. Bueno, si la encuentras, te pagaré por ella.}
{220}{}{Me parece bien, lo haré.}
{221}{}{No te preocupes, castigaré al ladrón. Soy un ranger, y he jurado defender la ley.}
{1221}{}{No te preocupes, castigaré al ladrón. Soy una ranger, y he jurado defender la ley.}
{222}{}{¿Cómo? ¿Eres parte de los rangers? ¿Y me lo dices ahora? ¡No quiero tu 'ley'! ¡Soy un hombre libre y no me arrodillaré ante ti!}
{223}{}{Ahora no es asunto tuyo. Me ocuparé del ladrón, espérame.}

#After receiving the quest
{230}{}{¿Tú otra vez? ¿Qué quieres?}
{231}{}{He oído a los demás hablar acerca de ti. ¿Qué te trae por aquí?}
{232}{}{Hola, vecino. ¿Cómo estás?}
{1232}{}{Hola, vecina. ¿Cómo estás?}
{233}{}{Sólo quería saludarte antes de irme.}

{240}{}{¿En qué trabajas, Frank?}
{241}{}{Hago estatuas. Venden muy bien a través del yermo.}
{242}{}{¿Es un negocio rentable, verdad?}
{243}{}{¿De verdad ganas dinero?}
{244}{}{No, la verdad no. A la mina se le está acabando la chatarra, y no hay muchos trabajos por aquí. Solía ser parte de un cartel, minábamos y reparábamos cosas viejas. Pero ahora apenas puedo sustentarme.}
{245}{}{Siento oír eso. ¿Te puedo preguntar otra cosa?}
{246}{}{Que triste historia. Adiós.}

{250}{}{Quiero hablarte acerca de la máquina soldadora.}
{251}{}{¿Encontraste alguna pista?}
{252}{}{No, pero aún tengo la esperanza de encontrarla.}
{253}{}{¿Sospechas de alguien? ¿Quién podría haberlo hecho?}
{254}{}{Si supiera, la hubiera recuperado yo. El ladrón es muy discreto, así que se necesita astucia para atraparlo.}
{255}{}{De acuerdo.}
{256}{}{Encontré la máquina, toma.}
{257}{}{¡No puede ser! Pensé que jamás la vería de nuevo. ¿Quién la robó?}
{258}{}{Estaba en... las ruinas, sí. No sé quién la habrá escondido ahí.}
{259}{}{Hmm, o tienes una buena intuición, o sólo estás encubriendo al ladrón. De todas formas, gracias. Aquí tienes las }
{260}{}{ chapas.}
{261}{}{De nada}
{262}{}{Fue Todd, el del tráiler.}
{263}{}{¡Ja! Todd se cree el más inteligente del pueblo. Pero tarde o temprano, la justicia encuentra a cualquiera, no importa quién o dónde estén. Bueno, dámela. Te pagaré }
{264}{}{ chapas. Pero no le digas a nadie.}
{265}{}{Claro.}
