{100}{}{Ves a un anciano.}
{101}{}{Ves a un anciano robusto con una barba espesa y desaliñada.}
{102}{}{Es el viejo Carmelo.}

# Acquaintance
{200}{}{¡No te me acerques! Todos saben que no meterse contigo es lo mejor.}
{201}{}{Y tienen razón. Así que cierra la boca, viejo.}
{202}{}{Sólo quiero que sepas que todavía puedo defenderme.}
{203}{}{Puedes desconfiar de mí, pero guárdatelo. A mí me interesa otra cosa.}
{204}{}{No quiero herirte, esos rumores son una exageración.}
{205}{}{Ojalá que eso sea verdad, pero recuerda que todavía puedo defenderme.}
{206}{}{No hay por qué ser así, vamos a conversar.}
{207}{}{Oh, es la nueva celebridad del pueblo. ¿A qué debemos este placer?}
{208}{}{¿Qué puede hacer para mí un viejo como tú?}
{209}{}{Pues, nada, supongo. ¿Por qué debería?}
{210}{}{Entonces hablemos.}
{211}{}{Entonces, no me interesas. Adiós.}
{212}{}{Deberíamos conocernos mejor, ¿no crees?}
{213}{}{La gente no suele ser tan amable sin un motivo. Pero, parece que tú lo dices con sinceridad.}
{214}{}{Sí, sólo quiero hablar contigo.}
{215}{}{Así es, no soy amable porque sí. Pero es obvio que tú no puedes ayudarme.}
{216}{}{¿Qué quieres? Si buscas una iguana, olvídalo, porque apenas tengo suficiente para alimentarme.}
{217}{}{No voy a quitarte la comida de la boca.}
{218}{}{Eso está bien, así conservarás tu mano. ¿Qué quieres?}
{219}{}{Quiero hablar, eso es todo.}
{220}{}{Es obvio que no me serás de ninguna ayuda.}
{221}{}{¡Dame la maldita iguana!}
{222}{}{¡Bueno, quédatela! ¿Cuál es la necesidad de ser así? ¿De dónde viene la gente como tú en el yermo?}
{223}{}{Todavía no terminamos de hablar, tengo preguntas y necesito respuestas.}
{1223}{}{Todavía no terminamos de hablar, tengo preguntas y necesito respuestas.}
{224}{}{Eso era todo lo que quería, pero volveré.}
{225}{}{¡Quita tus manos! ¡Esto es mío! Si quieres una iguana, ve al desierto y caza una.}
{226}{}{Cálmate, anciano. Es una broma.}
{227}{}{Bueno, lo haré. No tengo por qué hablar con un bastardo egoísta como tú.}
{228}{}{No soy ningún peligro. Te daré una chapa como muestra de mi sinceridad.}
{229}{}{¿Estás bromeando?}

# Re-dialogue
{230}{}{¿De verdad?}
{231}{}{¿Tú otra vez?}
{232}{}{}
{233}{}{Adiós, viejo. El yermo me llama.}
{234}{}{No hay nada que comprar en esta ciudad... pero, gracias por la chapa.}

{239}{}{Bueno, no hay por qué tirarle la cola a la iguana. ¿Qué quieres? Dime de una vez.}
{240}{}{¿Quién eres?}
{241}{}{Me llamo Carmelo y vivo aquí.}
{242}{}{¿Acaso tienes amnesia? Ya te lo dije, me llamo Carmelo.}
{243}{}{Pensándolo bien, quiero preguntar otra cosa.}
{244}{}{Adiós, Carmelo.}
{245}{}{¿A qué te dedicas?}
{246}{}{No es fácil un trabajo fácil, pero capturo lagartos y se los vendo a los demás.}
{247}{}{¿Has trabajado como chatarrero?}
{248}{}{Sí, tengo un buen olfato para hallar cosas útiles. Al fin y al cabo, hasta un montón de basura tiene su uso. (suspiro) Pero la mina... es decir, las ruinas de la ciudad, ya está agotada, apenas queda chatarra. Así que me dedico a cazar lagartos en vez de recoger las sobras que quedan.}
{249}{}{Ya veo. Tengo una pregunta más.}
{250}{}{Tengo que irme, anciano. Nos vemos.}
{251}{}{¿Trabajaste como chatarrero?}
{252}{}{¿Por qué eres tan desconfiado, Carmelo?}
{253}{}{Si llegas a vivir tanto como yo, igual dejarás de confiar en los demás.}
{254}{}{¿Siempre eres tan desconfiado?}
{255}{}{¿Puedes recordarme a qué te dedicas?}
{256}{}{¿También trabajabas en la 'mina'?}
{257}{}{Hoy en día es muy raro encontrar a un anciano.}
{258}{}{Dicen que antes la gente vivía hasta los cien años, pero en estos tiempos, sólo unos pocos suertudos llegan a vivir tanto como yo. Nunca buscaba problemas, creo que es por eso que sigo vivo.}
{259}{}{Por cierto, ¿a qué te dedicas?}

{260}{}{¿En serio? Resulta que yo tengo un poco de basura en mi bolsillo. Mira...}
{261}{}{Veamos... (registra la basura de tu bolsillo con interés) Si tuviera bolsillos como los tuyos, ya sería rico.}
{262}{}{¿Encontraste algo de utilidad?}
{263}{}{Mira, hay un dólar de la preguerra, un par de chapas y una bala de bajo calibre. Si llegas a tener un día de suerte, con todo esto te alcanzaría para comprarte una iguana. Es mejor que nada, ¿no?}
{264}{}{Agh, sabía que no valdría nada.}
{265}{}{Así que todavía tengo una oportunidad. Iré a buscarme un inversor.}

{266}{}{Carmelo, ¿conoces a alguien con una máquina soldadora?}
{267}{}{En el garaje debe haber una, no lo dudo. Frank tenía la suya, pero es un avaro. Ah, cierto, el otro día pase al lado del remolque de Todd y sentí el olor de alguien soldando. Quizás me lo haya imaginado pero deberías preguntarle, por si acaso.}
{268}{}{Gracias.}
{269}{}{No hay mucho que puedes hacer sin una soldadora, es por eso que el Sr. Kogan compró la mayoría de ellas, y para empezar no es que hubieran muchas.}

{270}{}{Cuéntame, ¿viste si alguna caravana esclavista pasó por aquí?}
{271}{}{Sí, había una. Pero me hice a un lado, no quería cruzarme en el camino de gente así de peligrosa.}
{272}{}{¿Sabes hacia dónde se fueron?}
{273}{}{Hacia algún lugar en el este, nunca he ido hacia allá.}
{274}{}{Gracias, pero tengo más preguntas.}
{275}{}{Eso me basta, voy a ir hacia allá. Adiós.}
{276}{}{Has levantado sospechas luego de preguntar sobre los esclavos.}

{280}{}{Háblame sobre la 'mina'.}
{281}{}{¿Qué te digo? Antes, no había nadie viviendo aquí. Pero llegó el cartel y después vinieron un montón de chatarreros.}
{282}{}{Esas eran todas mis preguntas sobre la mina.}
{283}{}{Creo que debería irme.}
{284}{}{¿Qué función cumple el cartel?}
{285}{}{Ellos compran lo que encuentren los chatarreros, luego lo arreglan y lo subastan en otras ciudades.}
{286}{}{¿Quiénes son los chatarreros?}
{287}{}{Chatarreros, carroñeros, como quieras llamarlos. Se dedican a hurgar entre las ruinas para encontrar objetos útiles y las llevan al garaje para reciclarlas.}
{288}{}{¿Ese tipo de trabajo atrae a la gente? ¿En serio?}
{289}{}{¡Claro que sí! Hay mucha gente que llega aquí, esperan ganarse un montón de chapas e irse a un asentamiento mejor. Pero en la mayoría de casos, esta ciudad es su última parada.}
{290}{}{Me suena a que esta ciudad está en las últimas.}
{291}{}{Todavía no tocamos fondo, pero casi estamos ahí. Se están acabando los recursos en las ruinas y la gente ya no tiene nada con lo que ganarse la vida. La ciudad está muriendo, se quedará así hasta que a alguien se le ocurra un milagro.}
{292}{}{Sería imposible salvar a este vertedero.}
{293}{}{Que triste historia. Cambiemos de tema.}
{294}{}{¿En serio no hay nada que pueda hacerse?}
{295}{}{Bueno, si el garaje decide restaurar la fábrica vieja, podría salvar a la ciudad y crear trabajos. Pero lo dudo mucho.}
{296}{}{¿Qué tiene de especial la fábrica?}
{297}{}{Reparar una fábrica vieja es una locura, un trabajo de ese estilo requiere mucha electricidad y bastantes trabajadores. Pero lo más importante es que hace falta conocimiento que ya nadie posee. Lo único que podemos esperar es un milagro.}
{298}{}{¿Quién necesita una industria? En mi Villa, nos las arreglamos sin ella, usamos las manos.}
{299}{}{Créeme que hay muchos lugares en el sur que están ansiosos por tener estas maravillas de la preguerra. Usar las manos no es suficiente.}

{300}{}{Dices que antes no había nadie viviendo aquí, ¿entonces de dónde vienen las ruinas?}
{301}{}{Antes... Quiero decir, antes de que llegara el cartel. No te confundas. Pero por supuesto, antes de la Guerra, había un pueblo entero aquí; se llamaba Kingman. Pero eso fue hace unos cien años ya.}
{302}{}{¿De qué hablas? ¿Hubo una guerra en alguna parte?}
{303}{}{¿Acaso no lo sabes? Es una vieja historia, hay muchas leyendas al respecto. Dicen que hace cien años habían... em, ciudades grandes que no se llevaban bien y tampoco podían compartir la 'basura' que quedaba en el mundo. Es lo mismo que está pasando en Ciudad Garaje.}
{304}{}{¿Entonces se destruyeron entre sí?}
{305}{}{Inventaron un arma terrible que podía borrar una ciudad entera de la faz de la tierra. Sólo sobrevivieron unas pocas personas, y nosotros somos sus descendientes. Han pasado cinco o seis generaciones desde ese entonces.}
{306}{}{Un arma así de poderosa no puede existir. ¡Esto debe ser un cuento!}
{307}{}{Vas a visitar las ciudades en el sur y lo verás con tus propios ojos. Pero no sé por qué lo discuto - yo sólo he escuchado esas historias porque me las han contado.}
{308}{}{Suficiente. Puedes guardarte tus historias de terror para los niños.}
{309}{}{Esto es una historia triste, quizás sea verdad.}
{310}{}{Hablas demasiado, eso no es bueno.}

{320}{}{Háblame sobre cómo atrapas a las iguanas.}
{321}{}{Las iguanas son lagartos desérticos, atraparlas no es nada fácil. Pero si las comes con una cerveza, son el mejor bocadillo del mundo. ¿Quieres un bocado? No será gratis.}
{322}{}{Ya escuché suficiente, me está rugiendo el estómago.}
{323}{}{Genial, si los demás empiezan a atrapar lagartos, ya no quedará nada para mí.}
{324}{}{¿En serio no hay más comida aquí?}
{325}{}{No, ¿qué más podríamos comer? A los alrededores sólo hay desierto y montañas. Los comerciantes sureños solían traer la comida, pero últimamente hay menos caravanas que nunca y la comida es cada vez peor. Tenemos que capturar lagartos, es mejor que nada.}
{326}{}{¿Qué hay de los coyotes y los escorpiones?}
{327}{}{Son más peligrosos, un coyote es capaz de arrancarte la pierna y los escorpiones son venenosos, además de que saben muy mal.}
{328}{}{¿Han intentado plantar cosechas?}
{329}{}{Aquí no se puede. Vivimos entre ruinas antiguas, así que lo único que crece por aquí es pasto seco y moho. Hay una granja hidropónica por allá, pero sólo alimenta a unas pocas personas.}
{330}{}{¿Cómo atrapas a las iguanas?}
{331}{}{No pienses que voy a decírtelo, porque no necesito competencia.}
{332}{}{¿Cómo se te ocurren estas preguntas? Es como si pensaras que es posible cultivar maíz en el desierto.}
{333}{}{No seas así, viejo. Todos estamos en esto juntos.}
{334}{}{Si fueras una buena persona, compartirías tus experiencias.}
{335}{}{¿Qué tal si te doy 25 chapas?}
{336}{}{Dudo que tengas dinero. Y si así fuera, seguro que las encontraste en algún cadáver o se las robaste a alguien. Además, no las necesito.}
{1336}{}{Dudo que tengas dinero. Y si así fuera, seguro que las encontraste en algún cadáver o se las robaste a alguien. Además, no las necesito.}
{337}{}{Hmm, vaya.}
{338}{}{Gánate la confianza de la ciudad y hablamos.}
{339}{}{Eso quiere decir que todavía no confías en mí. De acuerdo.}
{340}{}{Lo estoy diciendo en serio.}
{341}{}{Claro, no hay problema.}
{342}{}{¿Y si te pago?}
{343}{}{¿Y con qué me vas a pagar? ¿Con chapas? No me sirven, en esta ciudad no hay nada en lo que gastarlas.}
{344}{}{Bueno, pensándolo bien, debido a lo que paso en la Fábrica, las chapas están de vuelta. Te lo contaré por 50 chapas.}
{345}{}{No vas a seguir mintiéndome, ¿no?}
{346}{}{Hmm... Está bien. Pero primero, tendrás que ayudarme con una cosita.}
{347}{}{Dime de una vez cómo capturas a las iguanas.}
{348}{}{No, eso no funcionará.}
{349}{}{¿Qué es eso?}
{350}{}{Pues, ¿qué es lo que quieres?}
{351}{}{Hongos. Afuera de la Fábrica, hay lagunas tóxicas en las que crecen unos hongos raros y verdes. Tráeme unos cuantos y te revelaré mis trucos de trampero.}
{352}{}{Está bien, intentaré conseguir algunos.}
{353}{}{Muy bien. Ponte en ello.}
{354}{}{¿Para qué quieres esos hongos? ¿No serían tóxicos?}
{355}{}{Eso es cosa mía. Encuéntralos y traelos, así de simple.}
{356}{}{Trato hecho. Pero más te vale que esto no sea una estafa, anciano.}
{357}{}{No hay problema.}
{358}{}{Si ganas dinero con ellos, no es asunto mío. Nos vemos.}

{360}{}{¿Puedes enseñarme cómo conseguir esos malditos hongos?}
{361}{}{Las lagunas tóxicas te harán daño, necesitas botas gruesas. Si usas botas de caucho estarás bien, pero no durarán mucho tiempo.}
{362}{}{Entiendo.}
{363}{}{¿Y por qué no vas a recogerlos tú?}
{364}{}{Porque te lo puedo pedir a ti.}
{365}{}{No te preocupes, sólo debes agarrar los hongos y salir corriendo.}
{366}{}{¿Eso es todo lo que tienes? No es suficiente, tráeme más.}
{367}{}{Se me está agotando la paciencia.}
{368}{}{Bueno, no hay problema.}

{370}{}{Tengo los hongos, espero que sepas lo que estás haciendo.}
{371}{}{Puedo oler esos hongos a una milla de distancia.}
{372}{}{¿Y en dónde están? Los tenía aquí...}
{373}{}{Ah, perfecto, me durarán un largo tiempo.}
{374}{}{Entonces, ¿cómo atrapas a las iguanas?}
{375}{}{Con lo que acabas de entregarme.}
{376}{}{¿Qué? ¿Con los hongos?}
{377}{}{No exactamente. Los hongos atraen insectos y los insectos atraen lagartos. No hay muchas personas que sepan este truco.}
{378}{}{¡Eso tiene sentido! Tú sí sabes lo que haces.}
{379}{}{Que truco más interesante. Pero, estoy seguro de que no debe ser el único que guardas.}
{380}{}{Por supuesto. Pero, ¿qué es lo que quieres aprender, exactamente?}
{381}{}{Háblame de las iguanas y de sus hábitos y en dónde viven. [+3% a Supervivencia]}
{382}{}{Enséñame algunos trucos de trampero, podrían salvarme la vida. [+3% a Trampas]}
{383}{}{Quiero saber acerca de tus habilidades de chatarrero. Sé que trabajabas para el cartel. [+3% a Reparar]}
{384}{}{Entonces pon atención, porque no te lo voy a repetir.}
{385}{}{Te escucho, anciano. Voy a absorber toda tu experiencia...}
