{100}{}{Ves a Eugene.}
{101}{}{Ves a un adolescente. Sus manos están sucias con tierra y óxido, está claro que disfruta juguetear con la maquinaria.}
{102}{}{¿Quieres una mejor vida, niño? Es lo mejor que te puedo dar.}
{103}{}{Lo siento, niño. Pero en esta vida, sólo te esperaba el dolor y el sufrimiento.}
{104}{}{Eugene ha llegado a su destino.}
{105}{}{¡Wow!}
{106}{}{Mientras tengas a Eugene en tu equipo, recibirás una bonificación de 20 puntos a la habilidad de Reparación al reparar objetos rotos.}

#Floating remarks when visiting locations:
{120}{}{ }
{121}{}{¡Wow! ¡Jamás había visto algo así!}
{122}{}{¿Es una estación de radio de verdad? ¿Y funciona? ¡Eso es genial!}
{123}{}{ }
{124}{}{Vámonos de aquí, este lugar me da miedo.}
{125}{}{Tienes suerte de tener una casa como esta, mi choza está hecha de basura.}
{126}{}{¡Había oído de esta ciudad, pero jamás pensé que vendría aquí!}
{127}{}{No sé por qué, pero no me gusta este lugar.}
{128}{}{Esto no se parece a una base ranger, ¿nos equivocamos de camino?}
{129}{}{¿Qué está haciendo esta gente?}
{130}{}{¿Qué...? ¿¡Qué pasó aquí!?}

#Final dialogue
{190}{}{Gracias por todo. Los Rangers son unos tipos duros, y esta presa es todo un castillo. ¡Estoy tan contento!}
{191}{}{Me alegra que te guste este lugar. Diviértete.}
{192}{}{No te emociones, niño. Te falta mucho por aprender.}
{193}{}{Hola, ¿cómo estás?}
{194}{}{Nos vemos, niño.}

{195}{}{En el yermo dicen muchas cosas malas de ti. ¿Son reales?}
{196}{}{Para mí, el fin justifica los medios. Eso es todo.}
{197}{}{Mis enemigos cuentan rumores acerca de mí, ignóralos.}
{198}{}{Eso pensaba...}
{199}{}{Hmph.}

#First dialogue
{200}{}{¿Quién eres? Oye, ¡tú no eres de aquí!}
{201}{}{Eh, no.}
{202}{}{Entonces, ¿de dónde eres? ¿También vienes a esclavizar campesinos?}
{203}{}{Claro que... ¡SÍ!}
{204}{}{¡Aléjate! ¡No te acerques!}
{205}{}{Oye, no seas tan mariquita... No le haré eso a este vertedero.}
{206}{}{Al contrario, los voy a rescatar. ¿Qué sabes acerca del ataque a la Villa?}
{207}{}{Nada. Es mejor que te vayas, o los demás te darán una bienvenida 'cálida'.}
{208}{}{¿Qué quieres decir con eso?}
{209}{}{Ya, ya. No creo que me quede aquí por mucho tiempo.}
{210}{}{Bueno, este lugar está empeorando. Pronto las ruinas quedarán agotadas y el cartel se desmoronará, a los habitantes sólo les quedará convertirse en asaltantes. ¡Ojalá pudiera largarme de aquí!}
{211}{}{¿A dónde irías, si pudieras?}
{212}{}{Con los Rangers. O quizás sólo irme al sur, al menos por allá hay un poco de civilización.}
{213}{}{Eres muy ambicioso. Adiós, muchacho.}
{214}{}{¿Qué sabes acerca del asalto a la Villa?}
{215}{}{Hola.}
{216}{}{Adiós, niño.}
{217}{}{A mi papá no le gusta que la gente se meta a nuestra casa.}

#In a team
{220}{}{¿Qué hacemos aquí?}
{221}{}{¿Cuándo iremos con los Rangers?}
{222}{}{¿Ya llegamos?}
{223}{}{Estoy cansado...}
{224}{}{Vamos a tomar un descanso, ¿bien?}
{225}{}{Quiero ver la presa de los Rangers, no puedo esperar.}
{226}{}{¿Sabes a dónde tenemos que ir?}
{227}{}{Viajar con los rangers debe ser agradable.}
{228}{}{¿Es cierto que los rangers beben su propia orina mientras viajan?}
{229}{}{¡Ojalá pudiera ver al General de los Rangers en persona!}

{230}{}{Espérame aquí, ya vuelvo.}
{231}{}{Vamos.}
{232}{}{Esconde esa cosa.}
{233}{}{Pero, me vas a proteger, ¿cierto?}
{234}{}{Quítate eso.}
{235}{}{Lo que tú digas.}
{236}{}{Sólo quiero llegar a casa tan rápido como pueda... Pero... Ya no sé que es lo que quiero realmente.}
{237}{}{No me agradan esos tipos. ¿Nos van a acompañar? Entonces no iré.}
{238}{}{No es una buena idea, niño.}
{239}{}{Eugene no confía en tus acompañantes. No te seguirá si tienes más compañeros.}

#Joining the team
{300}{}{Oye, niño. A los Rangers les interesan tus habilidades, estoy aquí para llevarte a su base.}
{301}{}{¿¡Cómo!? ¿¡De verdad!? ¡Eso es asombroso! He soñado con esto desde la primera vez que vi a un ranger. Pero...}
{302}{}{¿Pero?}
{303}{}{Papá no me dejará ir, no quiere ni saber de los Rangers y piensa que debo ser un chatarrero igual que él. Pero yo no quiero recolectar chatarra, ¡quiero repararla!}
{304}{}{Exacto, aquí nunca podrás desarrollar tus talentos. Deberías estar con los Rangers.}
{305}{}{No puedo escaparme, porque si lo hago, los demás chatarreros van a culpar a los Rangers y estarán en su contra. De por sí ya los tratan con desprecio. ¿Puedes hablar con mi papá? Quizás te escuche.}
{306}{}{De acuerdo, hablaré con él.}
{307}{}{Los Rangers siguen interesados en ti.}
{308}{}{Eso es genial... Pero no puedo irme hasta que mi papá esté de acuerdo.}
{309}{}{Comprendo. Voy a hablar con él.}
{310}{}{Tu padre está de acuerdo, puedes irte.}
{311}{}{¿¡De verdad!? No tenía esperanza, pensé que jamás lo permitiría... ¿Cuándo nos vamos?}
{312}{}{Ahora. Vámonos.}
{313}{}{Tu padre ha muerto. Eres libre.}
{314}{}{¿¡Qué!? Pero... No pensé que terminaría así. (solloza) A pesar de todo, él quería lo mejor para mí... (se calma) Bueno, ya no tengo nada que perder. ¿Cuándo nos vamos?}
{315}{}{Ahora. Vámonos.}
{316}{}{¿Qué hay de una pequeña dosis de veneno de escorpión?}
{317}{}{No lo dices en serio, ¿verdad? ¡Jamás lo perdonaría!}
{318}{}{¿Y qué tal si te escapas?}
{319}{}{Aquí tratan mal a los rangers, eso lo haría peor. Y yo no podré llegar lejos por mi cuenta.}

#If the dam is broken
{320}{}{Traigo malas noticias: la base de los Rangers fue destruida.}
{321}{}{¡No puede ser! Pensé que esto funcionaría... y así nunca más tendría que hurgar entre la basura por un par de chapas... Pero, tampoco quiero volver a casa. ¿Qué debería hacer?}
{322}{}{No vas a sobrevivir por tu cuenta en el desierto y lo que queda de los Rangers no podrán ayudarte. Es mejor que vuelvas a casa.}
{323}{}{Perdí el tiempo, ahora nadie me pagará por hacer de niñera. Estás por tu cuenta, niño. Piérdete.}
{324}{}{Papá me dijo que no debía confiar en ti. ¡Yo encontraré el camino a casa!}
{325}{}{Te la lavas.}
{326}{}{Sí, supongo... ¡No puedo creerlo! ¡Todo esto para nada!}
{327}{}{Bueno, quizás no sea tan malo vivir en un vertedero. Vámonos.}
{328}{}{Ya estamos aquí. ¿QUé pasa?}
{329}{}{¿Sabes...? Este viaje que tuvimos no fue en vano. Vi muchas cosas, descubrí un mundo entero que no conocía. Después de todo eso, mi vida no será la misma. Algún día iré al sur, lo juro.}
{330}{}{Es bueno que digas eso, pero también es un poco triste. Buena suerte, niño.}
{331}{}{Es tu decisión. Mi trabajo está hecho. Cuídate, niño.}
