{100}{}{Ves a un refugiado.}
{101}{}{Ves a uno de los recién llegados.}
{102}{}{Para dar de comer a un refugiado, utiliza comida sobre ellos.}

#First dialogue
{200}{}{(desde sus harapos sucios, te observa un par de ojos penetrantes y salvajes) ¿Qué quieres? ¿Eh? ¿Qué quieres?}
{201}{}{No te preocupes, no te haré daño.}
{202}{}{No confías en los desconocidos, ¿no es así?}
{203}{}{¿Qué quieres? No he comido en dos días, y me van a echar de la ciudad. Dame algo de comer o piérdete.}
{204}{}{Claro, déjame ver si tengo comida en la mochila.}
{205}{}{¿Darte de comer? ¡Vete al infierno!}
{206}{}{Claro, puedes comerte la suela de mi zapato.}
{207}{}{Sigue así, y haré que te comas tu propia mano.}
{208}{}{¡Basta! ¡No me toques!}
{209}{}{Cálmate, tengo que preguntarte algo.}
{210}{}{Responde mis dudas y no te haré nada.}
{211}{}{Déjame en paz.}
{212}{}{Eh, bueno. Lo que sea.}
{213}{}{¿Así que fue su grupo el que habló con los rangers y se arrepintió?}

#Re-dialogue
{220}{}{¿Qué quieres?}
{221}{}{Adiós.}
{222}{}{Gracias por darme de comer. ¿En qué te puedo ayudar?}
{223}{}{Por hoy, nada. Adiós.}
{224}{}{Comprendo.}

{230}{}{¿Por qué estás en este pueblo?}
{231}{}{Estamos escapando. Están ocurriendo cosas horribles en el sureste: las cosas están cambiando en las ciudades, están esclavizando gente, echan a los granjeros de sus tierras. Pensamos que estaríamos seguros con los rangers, pero es lo mismo.}
{232}{}{¿Cómo cruzaron el desierto?}
{233}{}{Fue brutal. En las noches hacía frío, y en el día estaba tan caluroso que podíamos cocinar lagartos entre las piedras. Hicimos la mayor parte del recorrido durante las tardes y las mañanas. A veces pensábamos que no sobreviviríamos. No podremos resistir otro viaje así, de ninguna manera.}
{234}{}{El desierto es horrible, lo sé bien.}
{235}{}{¿Podrías volver a decirme cómo acabaron aquí?}

{240}{}{¿Qué pasó con los Rangers?}
{241}{}{¿Los Rangers? ¡Ja! Nos dijeron que protegían la ley y el orden. Pero en verdad, solo son unos saqueadores.}
{242}{}{¿Qué te hace pensar eso?}
{243}{}{Cuidado con lo que dices de ellos.}
{244}{}{Primero, nos quitaron todo lo que teníamos, y luego nos dijeron que nos fuéramos de su territorio.}
{245}{}{Pero, ¿por qué te echarían?}
{246}{}{Mira nuestra ropa - no tienen nada más que quitarnos, sólo somos refugiados. Y no tenemos ni la fuerza ni las ganas de ser sus esclavos. No nos necesitan, así que nos tiraron como a un montón de basura.}
{247}{}{¿Cómo sabes que fueron los Rangers?}
{248}{}{Uno de ellos nos mostró su placa. Además, un saqueador no nos hubiera echado; directamente nos hubiera matado o asaltado.}
{249}{}{Eso es raro. Tengo que investigar más al respecto. No te vayas de la ciudad.}

{250}{}{Tengo que encontrar a esos Rangers.}
{251}{}{¿Para qué? No tientes a Dios. Te matarán o te asaltarán.}
{252}{}{Voy a lidiar con ellos, muéstrame en donde están.}
{253}{}{Tienes razón, solo me meteré en problemas. Olvídalo.}
{254}{}{No, estoy muy débil como para viajar. Necesito recuperarme.}
{255}{}{Volveré cuando te sientas mejor.}
{256}{}{Haré que te tragues tus propios dientes si no me llevas.}
{257}{}{Hmm... Entonces te pagaré 20 chapas; puedes usarlas para comprar comida en el bar.}
{258}{}{(se relame los labios mientras metes la mano al bolsillo)}
{259}{}{Eh, me dejé las chapas en el... eh... motel.}
{1259}{}{Eh, me dejé las chapas en el... eh... motel.}
