{100}{}{Ves a un chatarrero.}
{101}{}{Ves a un chatarrero con un casco de soldador.}

{110}{}{¿Qué estás haciendo aquí?}
{111}{}{¿Nos estás espiando?}
{112}{}{¿Kogan te envió?}

{120}{}{Lucas sabe lo que hace.}
{121}{}{He pasado por muchas cosas junto a Lucas.}
{122}{}{Trayvon debe estar enojadísimo. Jaja...}
{123}{}{Esta fábrica es nuestra última esperanza.}
{124}{}{Fuimos los primeros en abrir la fábrica, así que ahora es nuestra.}
{125}{}{Kogan tendrá que ceder unas cosas.}

{130}{}{Tenemos suerte de que estés de nuestro lado.}
{131}{}{Gracias por la ayuda.}
{132}{}{Siempre serás bienvenido aquí.}
{133}{}{Estamos a cargo ahora. Gracias..}
{134}{}{No sé como hubiéramos terminado sin ti.}
