{100}{}{Ves a una chica.}
{101}{}{Ves a una chica semidesnuda.}

{110}{}{¡Yo les dije que no y me quitaron la ropa!}

{200}{}{(se sienta en la cama y lentamente se pone la ropa con una expresión triste) Gracias... supongo...}
{201}{}{¿Por qué estabas con esos tipos?}
{202}{}{No lo sé... No pensé que harían eso...}
{203}{}{No eres muy inteligente, eso es obvio.}
{204}{}{Creo que tendrás más cuidado en el futuro.}
{205}{}{¡Eres un animal! ¿Por qué los mataste? ¡Eres peor que ellos! ¡Ahora todos me van a evitar!}
{206}{}{Pero, era lo correcto. ¿No?}
{207}{}{¡No! ¿Y ahora cómo voy a ganar dinero? En esta ciudad no hay trabajo, y estoy atrapada aquí... Ojalá no hubieras aparecido... ¡Ojalá que no existiera esta maldita ciudad!}
{208}{}{Eh, dejaré que te calmes tú sola. Adiós...}
{209}{}{Reacciona, estúpida. Hice lo que tenía que hacer.}
{1209}{}{Reacciona, estúpida. Hice lo que tenía que hacer.}
{210}{}{No quiero hacer esto. Pero si no, no puedo ganar dinero. Estoy atrapada aquí... ¡Ojalá que no existiera esta maldita ciudad!}
{211}{}{Hmm... hmm... Eres tú... Hola.}
{212}{}{Hmm... hmm... Eres tú... Lárgate, no quiero verte.}
{213}{}{Adiós.}
