{100}{}{Ves la computadora de Kogan.}  
{101}{}{Ves una computadora viejísima, fue reparada por los mecánicos del garaje.}  
{102}{}{¡La computadora fue destruida!}  
{103}{}{[prueba: daño]}  

#Dialogue
{200}{}{Introducir comando:}  
{201}{}{Cerrar sesión}  
{202}{}{Regresar}  

{210}{}{Revisa todos los informes del cartel}  
{211}{}{(A partir del año 2160, los chatarreros empezaron a extraer recursos de las ruinas de Kingman. La mina tuvo grandes ingresos sus primeros seis años, pero después de eso, la producción local y el comercio cayeron en picada.)}  
{212}{}{Contratos con Flagstaff}  
{213}{}{(El Sr. Kogan firmó varios contratos con la colonia de Flagstaff para intercambiar chatarra y servicios de mantenimiento por comida, medicamentos y combustible nuclear. Parece que también espera contratos mucho más grandes para el futuro.)}  
{214}{}{Contrato para apoyar al despliegue}  
{215}{}{(El Sr. Kogan ayudó a los asaltantes de la Villa antes y después del ataque. Bajo el contrato, les proporcionó dormitorios, agua potable y servicios de mantenimiento a sus armas. Aunque el beneficio inicial era pequeño, los beneficios potenciales justificaban la inversión.)}  
{216}{}{Siguiente}  
{217}{}{(Entre sus notas, descubres que los atacantes de la Villa fueron un grupo de mercenarios de una colonia llamada Flagstaff. Parece que los campesinos secuestrados fueron llevados hasta allá.)}  

{220}{}{Copia los contratos para Lucas.}  
{221}{}{Datos copiados con éxito.}  
{222}{}{Genial.}  
