{100}{}{Ves al hijo de Domínguez.}
{101}{}{Ves a un niño de pueblo. Huele muy mal.}
{102}{}{Hrrr...}
{103}{}{Mis zapatos viejos se están desgastando...}
{104}{}{El niño se encuentra muy contento con las chanclas nuevas.}
{105}{}{¡Gracias!}

{106}{}{«¡Gracias!»}

{110}{}{H-Hola. En serio... ¿En serio vienes del norte?}
{111}{}{Qué raro. No parece que... que comas gente.}
{112}{}{Dicen que en el norte sólo viven salvajes.}
{113}{}{¿De verdad comen gente allá en el norte?}
{114}{}{Algún día, el General Sarabia se apoderará de Arizona.}
{115}{}{¿Quieres empujar a la waka?}
{116}{}{Mejor mantente alejado de nuestras wakas. No toleran a los extraños.}
{117}{}{¿Quieres montar una waka? Entonces paga el doble de pesos.}
{118}{}{¿De verdad estás pagando con chapas? ¡Pf-ja-ja-ja!}
{119}{}{¡Estúpida norteña! ¡Estúpido norteño! ¡Be-be-be!}
{120}{}{Mis zapatos se rompieron... ¿Me ayudas?}

{210}{}{«Hola. ¿De verdad viniste del norte?»}
{211}{}{«Qué raro. No parece que comas gente.»}
{212}{}{«Siempre nos han dicho que solo los salvajes viven en el norte.»}
{213}{}{«¿De verdad comen gente allá en el norte?»}
{214}{}{«Algún día, el General Sarabia se apoderará de Arizona.»}
{215}{}{«¿Quieres empujar el waka?»}
{216}{}{«Mejor mantente alejado de nuestras wakas. No toleran a los extraños.»}
{217}{}{«¿Quieres montar una waka? Entonces paga el doble de pesos.»}
{218}{}{«¿De verdad estás pagando con chapas? ¡Pf-ja-ja-ja!»}
{219}{}{«¡Estúpida norteña! ¡Estúpido norteño! ¡Be-be-be!»}
{220}{}{«Mis zapatos se rompieron... ¿Me ayudas?»}

{1110}{}{Hola. ¿De verdad viniste del norte?}
{1111}{}{Qué raro. No pareces un salvaje caníbal.}
{1112}{}{Siempre nos han dicho que solo los salvajes viven en el norte.}
{1113}{}{¿De verdad comen gente allá en el norte?}
{1114}{}{Un día el General Sarabia se apoderará de Arizona.}
{1115}{}{¿Quieres empujar a la waka?}
{1116}{}{Mejor mantente alejado de nuestras wakas. No toleran a los extraños.}
{1117}{}{¿Quieres montar una waka? Entonces paga el doble de pesos.}
{1118}{}{¿De verdad estás pagando con chapas? ¡Pf-ja-ja-ja!}
{1119}{}{¡Estúpida norteña! ¡Estúpido norteño! ¡Be-be-be!}
{1120}{}{Mis zapatos se rompieron... ¿Me ayudas?}

{1210}{}{«Hola. ¿De verdad viniste del norte?»}
{1211}{}{«Qué raro. No parece que comas gente.»}
{1212}{}{«Siempre nos han dicho que solo los salvajes viven en el norte.»}
{1213}{}{«¿De verdad comen gente allá en el norte?»}
{1214}{}{«Algún día, el General Sarabia se apoderará de Arizona.»}
{1215}{}{«¿Quieres empujar el waka?»}
{1216}{}{«Mejor mantente alejado de nuestras wakas. No toleran a los extraños.»}
{1217}{}{«¿Quieres montar una waka? Entonces paga el doble de pesos.»}
{1218}{}{«¿De verdad estás pagando con chapas? ¡Pf-ja-ja-ja!»}
{1219}{}{«¡Estúpida norteña! ¡Estúpido norteño! ¡Be-be-be!»}
{1220}{}{«Mis zapatos se rompieron... ¿Me ayudas?»}