{100}{}{Ves a El Marchitado.}
{101}{}{Estás viendo a una criatura marchita la cual te observa con ojos enloquecidos.}
{102}{}{Te comeré y me volveré más fuerte... pero, no sabes cuánto me odio por eso.}
{103}{}{¡El Marchito decidió atacarte cuando le diste la espalda!}
{104}{}{Me empiezan a doler los cuernos. ¡Es mejor que te vayas!}

{110}{}{Duele... Duele mucho...}
{111}{}{Ya no siento dolor... Ahora estoy débil...}

#Encounter with the Ragged Creature
{200}{}{(Ante ti se encuentra una criatura que recuerda vagamente a una persona. Está vestido con harapos y te examina con ojos enloquecidos, los que están llenos de miedo y hambre.)}
{201}{}{¡Ahhh! ¡Un demonio! ¡Muere! ¡Mueeereee!}
{202}{}{No quiero hacerte daño. ¿Quién eres?}
{203}{}{Retrocede, monstruo. Dime quién eres.}
{204}{}{(agarra su propia cabeza; observas que desde ella crecen varios cuernos)}
{205}{}{¿Eres de por aquí?}
{206}{}{Responde cuando te hablan.}
{207}{}{(se levanta y mira a su alrededor) Sí... Sí. Pero, ¿qué hay de ti? ¿De dónde eres? No he visto a una persona normal en un buen tiempo. Y esa ropa... Ya lo recuerdo. Sí. Los moradores de los refugios la utilizaban. (camina a tu alrededor mientras te examina) Jamás entré a un refugio. Es por eso que estoy aquí.}
{208}{}{Espera, tengo muchas preguntas para ti, amigo mío.}
{209}{}{Quédate quieto, fenómeno. Si intentas ponerme un dedo encima, te mato.}

{220}{}{(se cubre el rostro con sus manos) ¿Qué quieres? La ciudad está en ruinas. Aquí no hay nadie. Vete.}
{221}{}{De acuerdo, ya me voy. Ni se te ocurra seguirme.}
{222}{}{(se levanta y mira a su alrededor) Sí... Sí. Pero, ¿qué hay de ti? ¿De dónde eres? No he visto a una persona normal desde... (camina a tu alrededor mientras te examina) Desde que los demás entraron a los refugios. Yo no llegué, así que aquí estoy.}

#About Me
{230}{}{¿Quién eres? ¿Qué eres? Eres como un necrófago, pero, tienes cuernos... ¿Eres un demonio?}
{231}{}{¿Demonio? (mira a otro lado) Así nos llamamos unos a otros... Yo solía ser un hombre... un granjero. Solía derramar la leche al piso para que los precios no cayeran. Enterraba las patatas y los vegetales... que estúpido fui.}
{232}{}{¿Eres la única persona aquí? ¿Hay alguien más?}
{233}{}{¿Aquí solía estar tu granja? ¿Entre estas ruinas?}
{234}{}{¿Cómo conseguiste sobrevivir?}
{235}{}{¿Sobrevivir? No. Esto no es vida. Esto es un infierno. Todos estamos en el infierno. No podemos morir. La radiación nos hizo esto. Este es nuestro castigo. Algunos tuvieron la suerte de ser alcanzados por las bombas nucleares. Pero yo no fui parte de ellos.}
{236}{}{¿Qué le pasó a los demás supervivientes?}
{237}{}{Esto solía ser una ciudad grande, ¿no es así?}
{238}{}{¿Y qué haces ahora? No parece que este sea un lugar muy próspero, ni siquiera podrías hacer una granja.}
{239}{}{¡Aquí no hay comida! Solíamos comer lo que hallábamos en las ruinas. Ahora nos comemos unos a los otros. Pero ya no ocurre tanto. Nos acostumbramos al hambre.}
{240}{}{¿Así que en este lugar hay otros... iguales a ti?}
{241}{}{No me sorprende, hay ruinas por todos lados.}
{242}{}{¿Un granjero, dices? Espera... ¿cuándo fue eso?}
{243}{}{Fue hace mucho tiempo, cuando cayeron las bombas. Tú ni habías nacido.}
{244}{}{¿De verdad viste la Gran Guerra con tus propios ojos?}
{245}{}{Además de ti, ¿hubo alguien más que haya sobrevivido ese infierno?}
{246}{}{Por cierto, ¿Qué clase de ciudad solía estar aquí?}
{247}{}{Eso no es lo que quería escuchar. Hablemos de otra cosa.}

### About Packs

{250}{}{Ya no quedan muchos de nosotros. Pero incluso ahora estamos divididos entre los demonios ricos, y los pobres como yo. Los demonios ricos brillan en la oscuridad. Mantienen a todos bajo control y ellos se quedan con las mejores cosas.}  
{251}{}{[Sigue escuchando]}  
{252}{}{Antes, solían ser importantes e influyentes. Y ahora que son demonios, siguen pisando a los demás y manteniéndolos bajo sus suelas. (se ríe) Eso está bien, que brillen y que vivan atormentados para siempre.}  
{253}{}{[Más]}  
{254}{}{Esto es un infierno, es peor que la muerte. No pueden morir por mucho que quisieran. Este es su castigo - la inmortalidad. Son atormentados por sus pecados, deberán sufrir para siempre.}  
{255}{}{Supongo que también eres un demonio, igual que los resplandecientes.}  
{256}{}{¿Qué clase de lugar es este que convierte a la gente en... esto?}  
{257}{}{¿Así que te echaron de la manada? ¿Es por eso que eres tan flaco?}  
{258}{}{La manada comparte la comida, aquí no es posible sobrevivir por tu cuenta. Los resplandecientes se dejan lo mejor para ellos. Cuando no hay comida, se comen a los más débiles... como yo. El siguiente en ser devorado soy yo y me liberarán de mi tormento. Pero no quiero que me coman. Es por eso que me escondí aquí.}  
{259}{}{Creo que estoy empezando a entenderlo. Pero, cambiemos de tema.}  
{260}{}{Aquí no hay nadie normal, ¿cierto?}  
{261}{}{¡Sí, sí lo hay! Alguien vive en la iglesia. Prenden las luces en la tarde, pero no he visto quién es. Hay muchos que quieran entrar ahí, pero no pueden.}  
{262}{}{¿Sabes cómo puedo llegar a salvo a esa iglesia?}  
{263}{}{Te podría mostrar el camino, pero me devorarían al llegar. Y a ti igual. Pero, si realmente quieres... ve a través del alcantarillado, es la ruta más segura.}  
{264}{}{Interesante. Pero, ¿qué más sabes?}  
{265}{}{Además de ti, ¿quién vive en estas ruinas?}  
{266}{}{¿Qué es esta ciudad?}  

### About the City

{270}{}{(mira a su alrededor por un largo tiempo) Hace mucho tiempo, aquí había una gran ciudad. Se llamaba Mexicali, era hermosa. Luego cayeron las bombas atómicas...}  
{271}{}{[Sigue escuchando]}  
{272}{}{La transformaron en un campo de basura quemada y chatarra. Lo hicieron los Rojos. Le apuntaron a las fábricas de aeronaves, pero destruyeron todo lo demás. Y ahora, gracias a la radiactividad, ya no queda ningún tipo de vida en este lugar. Ni siquiera crece el pasto.}  
{273}{}{[Más]}  
{274}{}{Aquí todo está contaminado con la radiación. Es por eso que tengo mutaciones como esta. (se toca los cuernos)}  
{275}{}{¿Y cómo conseguiste sobrevivir en un infierno como este?}  
{276}{}{¿Así que no estás sólo? ¿Hay más supervivientes en las ruinas?}  
{277}{}{¿Por qué está destruida la ciudad? ¿Fue por la Gran Guerra?}  

### About the War

{280}{}{Esto es culpa de la gente estúpida. Ellos transformaron al planeta en un yermo, usaron todo el petróleo y empezaron a quitarse las migajas del uno al otro. Las ciudades y la naturaleza que amábamos fueron borradas de la faz de la Tierra.}  
{281}{}{[Sigue escuchando]}  
{282}{}{Mira, ahí hay una hormiga gigante. Antes no había ninguna así. Eso no está bien. Las hormigas deberían ser... pequeñas. Más pequeñas que la uña de tu meñique. Pero ya no son así.}  
{283}{}{[Más]}  
{284}{}{Y es por la radioactividad... ¡Shh! ¿Lo oyes? Son los demonios, dan alaridos de dolor. Cuando cae la noche, todos los demonios sienten dolor.}  
{285}{}{¿Y esos demonios son los demás supervivientes?}  
{286}{}{Cuéntame como solía ser esta ciudad, antes de las bombas.}  
{287}{}{Bueno, paremos aquí. Necesito procesar toda esta información.}  
{288}{}{¿Y tú? ¿También eres un demonio?}  
{289}{}{¿Eres el único que sigue con vida? ¿Hay alguien más aquí?}  

### About the Brotherhood of Steel

{300}{}{¿Habrás visto a una caravana de la Hermandad del Acero? Eran un escuadrón de soldados, se supone que pasaron por aquí.}  
{301}{}{¡Ah, mi cabeza! ¡Duele! Es tan doloroso...}  
{302}{}{No voy a caer en eso. ¡Dime qué le pasó a los soldados!}  
{1302}{}{Eso no funciona conmigo. ¡Dime qué le pasó a los soldados!}  
{303}{}{Lo siento, pero es muy importante. Intenta recordarlo.}  
{304}{}{Ah, esos paliduchos no podían salir de nuestro inframundo. Jeje, tendrán que arder aquí por toda la eternidad, igual que los demás.}  
{305}{}{Entonces, ¿están vivos?}  
{306}{}{Los tienen de rehenes en la iglesia. Pero no podrás llegar ahí, ¡No, no lo intentes! Alrededor de la iglesia hay multitudes de demonios y nadie sabe qué está ocurriendo en su interior. Ese lugar está maldito, es la guarida del mismísimo Lucifer. Nunca, nadie jamás ha vuelto de ahí.}  
{307}{}{Esto no será fácil...}  
