{100}{}{Ves a un supermutante.}
{105}{}{¡Malditos bastardos! ¡Los mataré por lo que le hicieron a mis amigos!}

{110}{}{Habla con Levi.}
{111}{}{Patético humano.}
{112}{}{No te atrevas a mirarme.}
{113}{}{Detesto cuando la gente me mira.}
{114}{}{Hmmmm...}
{115}{}{No pruebes tu suerte conmigo.}
{116}{}{No me hagas enojar.}
{117}{}{Levi responderá tus preguntas. Si quiere.}
{118}{}{No me hables, normalucho.}
{119}{}{hazme enojar y te haré pedazos, serás la comida de los segadores.}

{120}{}{Hola, normalucho.}
{121}{}{Levi nos dijo que eres un amigo}
{122}{}{Sigues vivo, y eso es bueno.}
{123}{}{¿Echamos unos pulsos?}
{124}{}{Estoy aburrido...}
{125}{}{Levi nos dijo que pronto habrá una cura.}
{126}{}{¿Quieres parecerte a mí?}
{127}{}{¡Jajaja, mi sufrimiento acabará pronto!}
{128}{}{Me encanta hacer enojar a los segadores. No pueden hacerme nada.}
{129}{}{Segadores tontos, yo ser inteligente.}
