{100}{}{Ves al Guía.}
{101}{}{Ves a una persona con una vieja túnica de viaje. Tiene la cabeza y las manos vendadas.}
{102}{}{Aquí es dónde nuestros caminos se separan. Si quieres regresar a Sonora, tendrás que esperar junto a esta bandera a la siguiente caravana.}
{103}{}{Fue un gusto conocerte, piel suave.}

{200}{}{Hijo de la humanidad, este lugar es peligroso para alguien como tú.}
{201}{}{También es peligroso para ti. ¿Qué estás haciendo aquí?}
{202}{}{Hmm. ¿Has visto a algún necrófago en tu vida? ¿Los que parecen leprosos y tienen unos cien años? Los estoy buscando para guiarlos a las ruinas de San Diego.}
{203}{}{¿Por qué están yendo los necrófagos a San Diego?}
{204}{}{Nuestro hogar solía ser Necrópolis. Debido al ejército supermutante, hubo que abandonar la ciudad, y los necrófagos se esparcieron a través del yermo. Nos echaron de todos lados. Por fin hemos creado una nueva ciudad - Dayglow. Tiene las puertas abiertas a todos los necrófagos y mutantes que estén dispuestos a compartir nuestra carga.}
{205}{}{Quiero ir contigo.}
{206}{}{Entonces no compartimos intereses. Adiós.}
{207}{}{Es posible que mueras por la radiación en Dayglow, piel suave. Incluso si evitas eso, es poco probable que te acepten los necrófagos. Los humanos tampoco nos han aceptado, así que considera si estás preparado para tal prueba.}
{1207}{}{Es posible que mueras por la radiación en Dayglow, piel suave. Incluso si evitas eso, es poco probable que te acepten los necrófagos. Los humanos tampoco nos han aceptado, así que considera si estás preparada para tal prueba.}
{208}{}{No siento que esté encajando en éste mundo tampoco. Quizás visitar un lugar distinto me hará bien.}
{209}{}{Un extraño misterioso me invitó a Dayglow. No puedo ignorar eso.}
{210}{}{Todo esto suena repugnante. Por ahora me gustaría posponer el viaje. Adiós.}
{211}{}{Bueno, la decisión es tuya.}
{212}{}{Háblame del viaje.}
{213}{}{¿Por qué se reúnen los necrófagos en San Diego?}

{220}{}{Nos encontramos de nuevo. ¿Será el destino?}
{221}{}{No es más que una coincidencia. Adiós.}
{222}{}{Quiero acompañarte hasta Dayglow.}

{230}{}{¡Santo Set! Me recuerdas a los necrófagos de Necrópolis en las fases iniciales de la radiación. Pero, no te reconozco. ¿Eres un hijo nuevo del Maestro?}
{231}{}{No soy de Necrópolis, ni tampoco un hijo del Maestro. Un tipo llamado Levi me hizo esto.}
{232}{}{¿Levi? Lo conozco. Es uno de los mejores trabajos del Maestro, pero menosprecia a los que son como nosotros. Entonces, ¿eres víctima de sus experimentos? Siento pena por ti. Ahora podrás sentir lo agria que es la vida de un necrófago.}
{233}{}{Me gusta como soy. No sé por qué te deprimes tantos.}
{234}{}{Eso es cierto, todos me evitan. Incluso mi propia familia.}
{235}{}{}
{236}{}{}
{237}{}{Entonces ven con nosotros. Queremos construir un hogar para gente como tú y como yo.}
{238}{}{¿Un hogar para los mutantes? ¿En dónde está?}
{239}{}{Los necrófagos están construyendo una nueva ciudad en las ruinas de San Diego, un mundo para ellos mismos. Busco y guío a todos los necrófagos a los que aún les quede algo de cordura. Quizás encuentres un hogar ahí.}
{240}{}{Está bien. Quiero ir contigo hasta San Diego.}
{241}{}{Aún no puedo irme de aquí. Pero tendré en cuenta que hay otro lugar en el yermo en donde me esperan.}

{250}{}{Tendrás que dejar a tus amigos detrás. Sólo puedes llevar lo esencial, no más de 20 libras. A través del desierto tienes que viajar ligero, veloz como el viento.}
{251}{}{De ninguna manera. ¡No puedo dejar mis cosas tiradas por aquí!}
{252}{}{¿Podré regresar si no me gusta cómo es?}
{253}{}{Sí, podrás regresar a Sonora. Pero sólo puedes contar conmigo una vez, no te será posible regresar a la ciudad.}
{254}{}{Entonces necesito pensármelo. Hablaré contigo si me decido.}
{255}{}{Estoy listo para el viaje.}
{1255}{}{Estoy lista para el viaje.}
{256}{}{Pronto te encontrarás en un mundo mejor, amigo mío.}
{1256}{}{Pronto te encontrarás en un mundo mejor, amiga mía.}
{257}{}{[Emprende el viaje]}
{258}{}{Tienes demasiadas cosas encima.}
{259}{}{Llevo demasiadas cosas. Regresaré luego de guardarlas en algún lado.}
