{110}{}{La rocola está rota.}
{111}{}{La rocola fue reparada y está lista para reproducir esos terroríficos sonidos llamados música.}
{112}{}{La máquina fue reparada con éxito. ¡Qué maravilloso!}
{113}{}{La rocola está descompuesta. Para siempre.}

{120}{}{*De las lunas*}
{121}{}{*La de octubre es más hermosa*}
{122}{}{*Porque en ella se refleja la quietud*}
{123}{}{*De dos almas*}
{124}{}{*Que han querido ser dichosas*}
{125}{}{*Al arrullo de su plena juventud*}
