{100}{}{Ves a un niño salvaje.}
{101}{}{Ves a un niño de la tribu Chacal.}
{102}{}{*Bufido*}

#Response
{200}{}{*Te enseña los dientes*}
{201}{}{*Gruñido*}
{202}{}{¡Wof!}
{203}{}{Aléjate o te muerdo.}
{204}{}{*Lloriquea, se encoge y se aleja de ti*}
{205}{}{¡Grrr!}

{210}{}{*Da un resoplido*}
{211}{}{*Te olfatea*}
{212}{}{¡Wof!}
{213}{}{¡Wof wof!}
{214}{}{Mis dientes están más afilados que los tuyos.}

{220}{}{*Saltos de felicidad*}
{221}{}{*Hace trucos para presumir*}
{222}{}{Juega conmigo.}
{223}{}{¿Quieres ver mis saltos mortales?}
