{100}{}{Ves a Cráneo Resbaladizo.}
{101}{}{Ves a uno de los Chacales.}
{102}{}{Aléjate de mí.}

#Response
{200}{}{Mantén la distancia, forastero.}
{201}{}{Vale.}
{202}{}{Cuéntame sobre Colmillo Negro.}
{203}{}{Es el mejor guerrero de todos. Debes temerle, forastero, y mostrarle respeto. Trae más comida con sus trampas que cualquier otro. Vale la pena perdonar su mal comportamiento.}
{204}{}{Háblame sobre la Perra Loca.}
{205}{}{Nadie habla mal de la Perra. Ella nos manda; todos deben mostrarle respeto y compartir su comida. Pero en estos tiempos de hambruna, hasta dar un trapo viejo es difícil.}
{206}{}{¿Quién debería ser el líder de la tribu?}
{207}{}{Colmillo debería llevarnos a las montañas, lejos de estas tierras baldías. La Perra Loca busca alianzas con los forasteros. ¿Cuál es la mejor opción? Que la tribu lo decida. Yo seguiré a la manada.}
{208}{}{Adiós.}
