{100}{}{Ves a una perra.}
{101}{}{Ves a una de las hembras de los Chacales.}

#Response
{200}{}{(rechina sus dientes) ¡Shh! ¡No te me acerques!}
{201}{}{Adiós.}
{202}{}{Solo quiero preguntarte algo acerca de la tribu.}
{203}{}{Tus palabras solo me dan hambre. Tráeme comida o déjame en paz.}
{204}{}{Claro.}
{205}{}{La comida estaba buena. ¿Qué quieres saber?}
{206}{}{Suficiente. Adiós.}
{207}{}{¿De dónde vino tu tribu?}
{208}{}{Cuando era una cachorra, recuerdo que las otras tribus nos echaron de nuestras tierras. Deambulamos por el yermo, buscando donde sobrevivir. Nos refugiamos de una tormenta de polvo aquí dentro, eran tiempos de hambruna y solo sobrevivieron los fuertes. Han crecido dos generaciones aquí abajo desde ese entonces.}
{209}{}{¿Qué comen ustedes?}
{210}{}{Lo que sea que encontremos aquí o en el yermo.}
{211}{}{¿Crees que está bien comer carne humana?}
{212}{}{¿Qué otra opción nos queda si no hay nada que comer? En el desierto no crece ni un poco de pasto. El agua del río hace que nuestros estómagos se hinchen y sangren... Hmm, tienes comida.}
{213}{}{¿Hay algún otro forastero además de mí?}
{214}{}{Sí... es nuestro almuerzo. Es un forastero muy fuerte, su carne será buena. (sonríe) No podrás hablarle, porque Bestia Nocturna protege el almacén. Solo la Perra Loca sabe hablarle.}
{215}{}{¿Qué piensas de la Perra Loca?}
{216}{}{(con un tono atemorizado e inquieto) Ella manda. Habla por todos nosotros. ¡No vuelvas a hablar de ella!}
{217}{}{¿Qué hay de Colmillo Negro?}
{218}{}{Colmillo... (gruñido) Es un perro arrogante. Golpea a las mujeres, nos roba la comida. Derrota a Colmillo si quieres tomar su lugar.}
{219}{}{¿Por qué hay calaveras en el salón principal?}
{220}{}{Es una reliquia del pasado. Pregúntale a la Perra Loca.}
{221}{}{Cuéntame más.}
{222}{}{Nadie. Nuestra presa se escapó. Nos dejó con hambre... (escupe al piso, enojada)}
