{100}{}{Ves al delegado.}
{101}{}{Ves al embajador de los Rangers.}
{102}{}{El embajador está muerto... fueron los Chacales. Yo no tuve nada que ver.}
{103}{}{¿Qué clase de idiota hizo esto? ¡Todos mis esfuerzos a la basura!}
{104}{}{Creo que ocurrió algo, porque los Chacales me quieren echar.}

#Response
{200}{}{Así que ahí está nuestro héroe. Te aplaudo, porque tienes buenas habilidades diplomáticas. Muy pocas personas podrían haber convencido a una tribu como ellos. ¡Bien hecho! Sigue así.}
{1200}{}{Así que ahí está nuestra heroína. Te aplaudo, porque tienes buenas habilidades diplomáticas. Muy pocas personas podrían haber convencido a una tribu como ellos. ¡Bien hecho! Sigue así.}
{201}{}{Es lo que intento. ¿Qué tal está yendo todo?}
{202}{}{¿Sí?}
{203}{}{Hablemos de otra cosa.}
{204}{}{Adiós, Embajador.}

{210}{}{¿Has hecho algún progreso?}
{211}{}{Aunque haya sido difícil, se está avanzando. Lo primero que tenemos que hacer es apaciguar a los Chacales con unos pocos suministros. Y luego podremos empezar a enseñarles cómo tener una vida civilizada.}
{212}{}{¿Qué crees? Alguien arruinó el plan, porque los Chacales están muertos. Ojalá que esos salvajes no se vayan por toda Sonora y el Mojave en busca de víctimas.}
{213}{}{¿Crees que los Chacales serán útiles?}
{214}{}{Podrían enseñarnos nuevas técnicas de supervivencia y tácticas de combate. Y nosotros podemos usarlos para monitorear el área, de por sí eso es muy valioso. Pero hay mucho que me molesta de ellos - el canibalismo, su creencia en el Espíritu del Refugio, su vida subterránea, y otras idioteces. Nos llevará mucho tiempo cambiar eso.}
{215}{}{¿Qué piensas tú acerca de la alianza?}
{216}{}{Es una pregunta difícil. Hay muchos que están en desacuerdo con la alianza y creen que deberíamos exterminar a los Chacales. Y es por eso que la reputación de los Rangers se ensució un poco. Pero al hablar con la tribu, me quedó claro que eso no es una opción. También hay miembros de la "manada" en el Desierto del Mojave e incluso más al oeste. Al eliminar esta guarida, lo único que conseguiremos será enojar a las demás tribus. Es como tirar una piedra a un río para cambiar su curso.}
{217}{}{¿Cuál es la verdadera razón detrás de la alianza?}
{218}{}{Es obvio que tenemos otros motivos además de hacer la paz. Los Chacales han aterrorizado estos lares durante años. Pero, los rangers tienen un gran interés en el norte y esa es la única ruta; es una larga historia. Además, la tribu podría ayudarnos a aplicar presión hacia los asentamientos de la zona.}
{219}{}{Hasta ahora, no he podido hablar con su líder. Esto no irá a ningún lado sin tu ayuda.}
