{100}{}{Ves a un ranger.}
{101}{}{Ves a un prisionero. Los Chacales le han dado una golpiza.}
{102}{}{Genial, viviré un poco más.}
{103}{}{¿Eso es todo lo que has aprendido, Ranger?}
{104}{}{El ranger ha abandonado el Valle de los Chacales.}

#Dialogue BEFORE escaping
{200}{}{Déjame en paz, maldito salvaje... Mierda, no eres uno de ellos, ¿quién eres? ¿También te atraparon?}
{201}{}{De cierta forma, sí.}
{202}{}{No, idiota, yo *quiero* estar aquí.}
{203}{}{Pensé que jamás vería a alguien normal de nuevo...}
{204}{}{Es tu día de suerte, amigo.}
{205}{}{¿Tan mal estás?}

{210}{}{Escúchame, tengo que salir de aquí. ¡Ayúdame! Si lo haces, los rangers te deberán una.}
{211}{}{Todavía no podemos escapar. Espérame.}

{220}{}{¿Puedes caminar?}
{221}{}{Apenas, los Chacales me acuchillaron las piernas para que no pudiera escapar. ¿Puedes tratar mis heridas? Si no, encuentra mi estimulante. Alguno de los salvajes debe tenerlo.}
{222}{}{¿Qué es un 'estimulante'?}
{223}{}{¿En serio no lo sabes? Puta madre... ¡Mátenme! Escucha, es una cosa antigua con una aguja y un líquido rojo. ¡Encuéntralo, rápido!}
{224}{}{De acuerdo, intentaré encontrarlo.}
{225}{}{Quizás se me ocurra otra forma de ayudarte.}
{226}{}{Eso creo, al menos podré salir de aquí.}
{227}{}{Genial. Vamos, andando.}
{228}{}{No es el momento, espérame aquí.}

{230}{}{¿Puedes pelear?}
{231}{}{Sólo si me das un arma, los Chacales se llevaron mis cosas, incluido mi rifle. Podría estar en cualquier lado, con cualquier persona.}
{232}{}{Comprendo. Lo tendré en mente.}
{233}{}{Cuéntame cómo acabaste aquí abajo.}
{234}{}{Yo estaba con mi grupo, explorando el área. Estos hijos de perra son astutos y nos tendieron una trampa. Soy el único que sobrevivió.}
{235}{}{Entiendo.}
{236}{}{¿Los Chacales no pelean cara a cara?}
{237}{}{Ese no es su estilo. Si están por su cuenta, son cobardes, sólo atacan como una manada... ¡Argh! Me arden las piernas... ¡Maldigo a estos salvajes!}
{238}{}{¿Qué es lo que estabas buscando por aquí?}
{239}{}{Se nos asignó una misión. No podemos discutir nuestras ordenes. Es parte de nuestro estatuto.}
{240}{}{Está bien, creeré en ti.}
{241}{}{¿Qué interés podrían tener los rangers en un lugar tan salvaje y desolado?}
{242}{}{Tienes buen ojo para las mentiras... Los comandantes pensaron que los Chacales serían un buen incentivo para que una ciudad cercana firmara un contrato.}
{243}{}{¿Qué clase de contrato?}
{244}{}{¿Los rangers siempre son así de reservados?}
{245}{}{Los asentamientos de la región sufren a causa de los Chacales. Si lidiamos con ellos, podríamos mejorar nuestra reputación en el área. Eso hará que firmar acuerdos con los asentamientos sea un poco más fácil. El primer paso es reunir información estratégica acerca del enemigo y su territorio... Y, ¿qué tal si dejamos de charlar y salimos corriendo de aquí?}
{246}{}{No hasta que obtenga más información.}
{247}{}{Buena idea.}
{248}{}{¿Qué sabes acerca de estos túneles?}
{249}{}{No pude echar un vistazo. Pero ten cuidado si subes - hay muchas trampas alrededor de la choza.}
{250}{}{Comprendo.}

#Dialogue during and after the escape
{260}{}{Cubriré la retaguardia, pero lo más importante es que seamos discretos.}
{261}{}{Vamos, hay que salir de aquí.}
{262}{}{Podemos hablar afuera, rápido, salgamos de aquí.}
{263}{}{Ten cuidado, este lugar está lleno de trampas. Tenemos que alejarnos un poco.}
{264}{}{No parece que nos estén siguiendo. ¡Parece que perdieron nuestro rastro!}
{265}{}{Vámonos.}
{266}{}{No te preocupes por mí, podré llegar sólo.}
{267}{}{Ten cuidado.}

{270}{}{No parece que nos estén siguiendo. ¡Parece que perdieron nuestro rastro!}
{271}{}{Relájate, ya estamos a salvo.}
{272}{}{No por mucho. Además, tendré que cojear a nuestro puesto más cercano y pedir ayuda. Pero puedo hacerlo.}
{273}{}{¿Estás seguro de que no quieres ayuda?}
{274}{}{Sí, conozco algunos sitios en donde podría descansar y recuperar fuerzas.}
{275}{}{Bueno, tú eres el experto aquí.}
{276}{}{Te aconsejo que te pegues al río y te muevas a trote lento. Así ahorrarás energía, pero harás distancia.}
{277}{}{Sí, buena idea, aunque la ruta será más larga.}
{278}{}{[Más]}
{279}{}{Buen viaje, ranger.}
{280}{}{Gracias por salvarme, le contaré a los chicos de la base acerca de ti. Si alguna vez nos visitas, pregunta por Jason - así me llamo. Tengo que irme.}
{281}{}{Nos vemos luego, ranger.}
{282}{}{Gracias por salvarme. Me aseguraré de que tus hazaña sea conocida por mis compañeros en la base. Por ahora, necesito descansar y hablar con el comandante.}

{290}{}{Quédate aquí, debo explorar el área.}
{291}{}{Sígueme.}
{292}{}{Es mejor que enfundes tu arma, hace demasiado ruido.}
{293}{}{Quítate esa armadura, te hace resaltar en la oscuridad.}
