{100}{}{Ves a una salvaje.}
{101}{}{Ves a una de las perras de la tribu Chacal. Sus pequeños ojos te observan desde las sombras.}

#Replicas floating
{120}{}{Para almorzar hay larvas. De nuevo.}
{121}{}{¡Shhh, no ladres en vano!}
{122}{}{Dicen que hay un forastero hurgando por ahí.}
{123}{}{Nuestras crías morirán si no encontramos comida.}
{124}{}{Es hora de afilarme las garras.}
{125}{}{Los forasteros no tienen piedad.}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

#Response
{200}{}{¡Si nos haces algo te arrancaré la carne de los huesos!}
{201}{}{Serás el almuerzo de mis cachorros.}
{202}{}{Mis garras están ansiosas de tu carne.}
{203}{}{}
{204}{}{}

{205}{}{Mis niños tienen sed de tu sangre.}
{206}{}{Mis cachorros gustarán de tu carne.}
{207}{}{¿Buscas la muerte, forastero?}
{208}{}{Mmm, hueles delicioso.}
{209}{}{*Relame sus labios mientras te observa*}

{210}{}{¡Gólpeame!}
{211}{}{¡Quiero ser tu perra!}
{212}{}{Móntame y muérdeme el cuello.}
{213}{}{}
{214}{}{}
