{100}{}{Ves a un saqueador.}
{101}{}{Ves a uno de los Escudos Azules.}

{110}{}{Hola, ¿qué tal te va?}
{111}{}{Ten buena suerte allá afuera.}
{112}{}{Eres más duro de lo que pensábamos.}
{113}{}{No puedo creer que ahora estemos protegiendo las carreteras.}
{114}{}{Tenemos a las carreteras bajo nuestra protección.}
{115}{}{Nos traes suerte.}
{116}{}{Ben confía en ti.}

{120}{}{Sigue mirándome y te haré llorar.}
{121}{}{¿Qué quieres, pendejo?}
{122}{}{*Escupe al piso*}
{123}{}{Ben te dejó pasar, pero no eres uno de nosotros aún.}
{124}{}{Estoy aburrido. Cuéntate un chiste.}
{125}{}{Es mejor que no te quedes mucho rato.}

{130}{}{¿Qué demonios eres?}
{131}{}{Es él, mantengan silencio.}
{132}{}{Quiero una armadura como la tuya.}
{133}{}{¿Eres una creación de los Hojalateros?}
