{100}{}{Ves a Edmond, el mutante.}
{101}{}{Ves a un hombre horriblemente desfigurado.}
{102}{}{De repente, aparece un mutante desde las sombras.}

{110}{}{Márchate y no nos toques.}
{111}{}{¡Déjame en paz!}
{112}{}{No quiero hablar contigo.}
{113}{}{No podemos confiar en los desconocidos.}

{120}{}{¡Oh! ¡Ohh! ¡Wow!}
{121}{}{¡Arrr!}
{122}{}{¡Arrr!}
{123}{}{¡Bah! ¡Mujer!}

{200}{}{(El mutante te bloquea el paso, blandiendo un arma) ¡Ooh! ¡Wooo!}

{201}{}{[Das un paso atrás, mostrando tu amabilidad]}
{202}{}{¡Arrr! (Al observar que no te defenderás, decide atacarte.)}
{203}{}{¡No me toques!}
{204}{}{¡Mutante asqueroso!}
{205}{}{¡Alto! ¡No te me acerques!}
{206}{}{(Tus palabras no hacen más que enojar al mutante, y decide atacarte)}

{210}{}{[Da un paso adelante de forma audaz]}
{211}{}{¡Arrr! (El mutante se echa para atrás, y ahora su mirada se ve aún más desquiciada)}
{212}{}{Escúchame, no quiero pelear. Confía en mí.}
{213}{}{¡Muere, mutante!}
{214}{}{¡Basta! ¡Atrás!}

{220}{}{(El mutante frena de repente y da un paso atrás. Tu determinación parece asustarlo.)}
{221}{}{¿Pasa algo, guapetón? ¿Pelear no es lo tuyo, cierto?}
{222}{}{Mucho mejor. Ni siquiera te muevas, pedazo de mierda.}
{223}{}{(El mutante se queda tieso e indeciso. Al observar su rostro de cerca, tiene marcados años de dolor y miedo. Su cuerpo es retorcido y delgado.)}
{224}{}{No es ninguna sorpresa que estés aquí abajo mientras los demás pelean. ¿Cómo es posible que sigas vivo?}
{225}{}{Pobrecito, ¿naciste así? Es un milagro que sigas vivo.}
{226}{}{(De la nada, desde el cuarto de al lado, escuchas el llanto histérico de alguien. Esto hace reaccionar al mutante, y toma una posición defensiva para bloquearte el paso)}
{227}{}{¿Quién está ahí? ¿¡Estás torturando a alguien!?}
{228}{}{¡Arrrgh! (Te hace un gesto para que te vayas)}
{229}{}{¡Habla, maldito mutante!}
{230}{}{¡Arrrgggh! ¡Argrrgh!}
{231}{}{¡Muere, hijo de perra! ¡Muere!}
{232}{}{Hazte a un lado, fuera de mi camino.}
{233}{}{¿No sabes hablar? Entonces iré a ver qué está pasando.}
{234}{}{(Sacude la cabeza con mucha lástima)}
{235}{}{Sal de aquí, si vuelves, estás muerto. ¿Me escuchas?}
{236}{}{No te haré nada mientras no interfieras. Sal, toma aire fresco.}
