{100}{}{Ves a la Señorita Bates.}
{101}{}{Ves a una mujer horrendamente desfigurada.}
{102}{}{*Sollozando*}
{103}{}{Mis hijos te matarán y te devorarán.}

{200}{}{(En las sombras de la habitación, ves a una mujer encima de la cama; solloza en silencio, mirando la pared)}
{201}{}{...Hola, señorita.}
{202}{}{¡Fuera! ¡Aléjate de mí!}
{203}{}{Cálmese, señora, quiero ayudarla.}
{204}{}{Deja de gritar, o los mutantes vendrán corriendo.}
{205}{}{¡No! ¡No me toques! ¡Aaahhh!}
{206}{}{Todo estará bien, esos monstruos ya no te harán daño.}
{207}{}{O te callas, o te amordazo. ¿Me escuchas?}
{208}{}{(La mujer deja de gritar; en su silencio, te percatas de que tiene terribles magulladuras en todo su cuerpo).}
{209}{}{Dios mío, necesitas un doctor. Tengo que sacarte de aquí.}
{210}{}{¿Quieres vivir, no? Entonces vámonos de aquí.}
{211}{}{¿Por qué?}
{212}{}{¿Qué?}
{213}{}{¿Por qué querría salir de aquí? Este es mi hogar. No me iré de aquí.}
{214}{}{Y entonces... ¿Quiénes son esos monstruos?}
{215}{}{Sherman, George, Edmond - son chicos muy buenos, estoy orgullosa de ellos. Son mis pequeños.}
{216}{}{¿Esos mutantes caníbales son tus hijos?}
{217}{}{¿Me estás diciendo que esos fenómenos son tus hijos?}
{218}{}{Ja, no tienes hijos, eso es obvio. Me enorgullecen, son mi sol. Nadie puede separar a la familia Bates, ningún forastero lo ha conseguido.}
{219}{}{Es demasiado tarde para presumir de los logros de tu familia. Tus hijos están muertos.}
{220}{}{¡Monstruo! Ellos solo querían vivir. Todos los quieren matar, igual que tú. ¿Por qué eres así? (con un espasmo, la mujer te mira a los ojos con su rostro desfigurado) Desde la primera vez, no dejamos a nadie entrar. ¡Todos los forasteros nos quieren matar!}
{221}{}{Pero, yo...}
{222}{}{Esto me parece demasiado familiar...}
{223}{}{Pero eso está bien, porque somos una familia. Nadie puede separarnos, algún día, habrán más y más de nosotros. ¡Ja! ¡Jajaja! ¡Ajajajaja! ¡Jijijiji...!}
{224}{}{[Déjala en paz]}
{225}{}{Estás loca.}
{226}{}{Ustedes han matado a demasiadas personas, esto tiene que parar.}
{227}{}{¿Acaso crees que no puedo con unos fenómenos?}
{228}{}{¡Mis hijos te matarán, matarán a cualquiera que se meta con nosotros! Porque somos una familia. Nadie puede separar a los Bates. ¡Ja! ¡Ja ja! ¡Ajaja! Jijiji...}
{229}{}{Entiendo como se siente. Mi Villa también es una familia, y también intentaron separarnos. Y es por eso que no moriré hoy.}
{230}{}{Unos desconocidos también intentaron separar a mi Villa. No dejaré que me detengas, tus hijos lo intentaron - y murieron.}
