{100}{}{Ante ti se encuentra un centinela.}
{101}{}{Ves a uno de los Escudos Azules.}
{102}{}{Creo que estoy alucinando...}

{110}{}{¿Buscas problemas, pendejo?}
{1110}{}{¿Buscas problemas, vieja?}

{200}{}{(Conforme te acercas, el centinela escucha tus pasos y levanta la cabeza de golpe; por el susto, no consiguió agarrar su arma a tiempo)}
{201}{}{[Más]}
{202}{}{¿Pero qué carajo...? ¿Quién putas eres? ¿Qué quieres?}
{203}{}{¿Pero qué...? Puto fenómeno, no asustes así a la gente. ¿Qué quieres?}
{204}{}{¿Quién eres...? ¡Chicos, nos están espiando!}
{205}{}{No deberías haber hecho eso...}
{206}{}{¿Espía? ¿Yo?}

{210}{}{Buena pregunta. ¿Qué es este lugar?}
{211}{}{Un lugar hermoso, perra. ¿No sabes quiénes son los Escudos Azules? Nos pertenece cada carretera de la zona, y esta es nuestra base.}
{212}{}{¿Ustedes son los que asaltan viajeros en las carreteras? Menos mal, no tuve que rastrearlos. Los mataré a todos.}
{213}{}{Sí, claro. Seguro que ni podrías mandonear a un niño. No son más que perdedores en un basurero.}
{214}{}{Luego de matarte, atropellaremos tu cadáver un rato... (con una expresión de furia, presiona el mango del arma con fuerza)}
{215}{}{¿Y qué?}
{216}{}{Oh oh...}
{217}{}{Vaya, ustedes son geniales. ¿Les queda espacio en la banda? Quiero unirme.}
{218}{}{Ja, no hay sitio para atropellados como tú. Estoy de buen humor, así que te dejaré ir.}
{219}{}{Ya me voy, no seas así.}
{220}{}{Llévame con tu líder, sé que opinará otra cosa.}
{221}{}{Yo soy el que cuida esta puerta, no te dejaré pasar. ¿Lo comprendes? Ahora lárgate.}
{222}{}{Me dejarás pasar, o pasaré encima de tu cuerpo.}
{1222}{}{Me dejarás pasar, o pasaré encima de tu cuerpo.}
{223}{}{Inténtalo, perra.}
{224}{}{Parece que solo entiendes a los golpes...}
{225}{}{Ya, tú eres el que manda aquí. Me voy.}
{226}{}{Llévame con tu líder. Ahora.}
{227}{}{De acuerdo, sígueme.}
{228}{}{[Síguelo]}
{229}{}{¿Qué tal si te recompenso? Tengo 25 chapas, déjame pasar y son tuyas.}
{230}{}{(agarra las chapas mientras mira a su alrededor) Está bien, sígueme.}
{231}{}{[Síguelo]}
{232}{}{(Te observa con el ceño fruncido, mientras buscas las teóricas e inexistentes chapas de tus bolsillos.)}
{233}{}{Eh, las tengo por aquí... En serio...}
{234}{}{Al carajo con esto, matarte será mucho más fácil...}
{235}{}{Deberíamos haber empezado así. Déjame ir.}
{236}{}{No tan rápido, perra. Suelta las chapas, las quiero todas - y entonces te dejaré ir.}

{240}{}{Sólo estoy viajando, ¿puedo pasar la noche ahí dentro?}
{241}{}{(Con una sonrisa tétrica en su rostro, baja su arma.) Mira, te lo voy a explicar. ¿Sabes en dónde estás? Esto es la base de los Escudos Azules. ¿Has visto esas vallas publicitarias en la carretera? Nos gusta colgar a la gente como tú ahí arriba. ¿Lo comprendes? Si quieres salir de aquí con vida, piérdete.}
{242}{}{Que encantador. ¿Quién te crees que eres?}
{243}{}{(se le quita la sonrisa del rostro y la reemplaza una mirada de desprecio) ¿Cómo? A ver, dímelo a la cara, quizás te escuche mal.}
{244}{}{¿Estás sordo, pendejo?}
{245}{}{¡Ah, perdona! No soy de por aquí. No me volverás a ver, adiós.}
{246}{}{Me recuerdas a esos animalitos atropellados de la carretera, jeje. Suelta todas tus chapas.}
{1246}{}{Cometiste un error al pasarte por aquí, perra. Suelta todas tus chapas.}
{247}{}{No te voy a dar nada.}
{248}{}{Claro, por supuesto, llévate lo que quieras...}
{249}{}{¿En dónde estoy? ¿Qué es este lugar?}
{250}{}{Voy a perdonarte tu actitud, sólo por esta vez. Déjame entrar, quiero hablar con tu jefe.}
{251}{}{Llévame con tu líder, necesito hablar con él.}
{252}{}{(mientras lo piensa, rasca su cuello lleno de mugre) ¿Quieres hablar con Ben? ¿Siquiera sabes en dónde estás?}
{253}{}{Claro, estoy en una pocilga. Y alguien tiene que sacar la basura.}
{254}{}{Eso creo. ¿En dónde estamos?}
{255}{}{Estoy aquí en nombre del alcalde de Casa Grande. Necesito hablar con tu jefe.}
{256}{}{[Obedece y regresa al desierto]}

{300}{}{¿Sigues aquí? Es obvio que quieres problemas.}
{301}{}{Tengo que hablar con tu líder.}
{302}{}{¿Todavía estás por acá? No sé que es lo que quieres, pero otra chela me vendría bien.}
{303}{}{Puedo traerte unos tragos, pero primero debo ver a tu jefe.}
{304}{}{Vete al carajo, voy a entrar.}
{305}{}{Ya, cálmate, me largo.}
{306}{}{Déjame entrar.}
{307}{}{Me encontré a uno de los tuyos en medio del desierto. Dijo que podía hablar con Ben.}
{308}{}{Ah, eso cambia las cosas. Ben te está esperando, pasa. Pero ten cuidado con lo que dices, si quieres conservar la cabeza.}
{309}{}{De acuerdo.}

{310}{}{Suerte en la carretera, hermano.}
{1310}{}{Suerte en la carretera, hermana.}
{311}{}{¿Qué pasa, hermano?}
{1311}{}{¿Qué pasa, hermana?}
{312}{}{Vete al carajo.}
{313}{}{No me agradas. Fuera de mi vista, imbécil.}
{314}{}{Me muero de ganas por aplastarte el cráneo.}
{315}{}{Adiós.}

{320}{}{¿Hace cuánto que estás en la banda?}
{321}{}{¿Eh? ¿A ti qué te importa? Deja de preguntar pendejadas y cuídate la espalda.}
{322}{}{Aun así, este lugar es bastante genial.}
{323}{}{Lo que sea...}
{324}{}{¿Así recibes a los nuevos, imbécil?}
{325}{}{Tienes suerte de que Ben te dejó pasearte por la base. Pero no te pases.}
{326}{}{¿Por qué no?}
{327}{}{No nos gusta que hayan forasteros andando por ahí. Además, hay muchas trampas alrededor de la base. Mira por donde pisas. En serio.}
{328}{}{¿Trampas? ¿Me puedes mostrar en dónde están?}
{329}{}{No las colocamos porque sí. Ya te dije suficiente.}
{330}{}{Está bien, ya entiendo. Adiós.}
{331}{}{Respecto a esas trampas. ¿Me puedes mostrar las partes peligrosas?}
{332}{}{Te voy a pagar 50 chapas, nadie lo sabrá.}
{333}{}{De ninguna manera. A un pendejo como tú le voy a cobrar 100 chapas.}
{334}{}{Eso es muy caro.}
{335}{}{De acuerdo, aquí las tienes.}
{336}{}{De verdad necesito saberlo, Ben me dio el permiso.}
{337}{}{Carajo... Mira, hemos minado el perímetro de las murallas, excepto la puerta y la pared que está al lado del tanque de combustible. Lo peor está en el lado oeste. A veces los escorpiones pisan las trampas, así que aguas con donde pisas.}
{338}{}{Genial, eso es de mucha ayuda.}
