{100}{}{Ves a un saqueador.}
{101}{}{Ves a un forajido con el hombro herido.}
{102}{}{Ves a un forajido. Ha mejorado desde la última vez que lo viste.}
{103}{}{Sin ti me hubiera muerto, doc.}
{104}{}{Esos p-pendejos del a caravana me dieron en el hombro... ¡Carajo, duele!}
{105}{}{Me dispararon en el hombro mientras robábamos una caravana. Pero nos pudimos llevar todo.}
{106}{}{¿Estás seguro de que eso ayuda, doc? Me siento peor...}
{107}{}{¡Ay! Bueno, em, era demasiado tarde para salvarlo...}
{108}{}{¿Quién te dejó entrar?}

{200}{}{Sin tu ayuda me hubiera muerto, doc.}
{201}{}{De nada.}

{210}{}{¿Te ayudo en algo, doc?}
{211}{}{Adiós.}

{220}{}{Cuéntame qué te pasó.}
{221}{}{Me dieron en el hombro mientras robábamos una caravana. Pero nos pudimos llevar todo lo que tenían. ¡Jaja!}
{222}{}{¿Por qué te uniste a los Escudos Azules?}
{223}{}{No tenía otro lugar a donde ir, así que decidí unirme a Ben. No fue fácil, tuve que pasar por un ritual de iniciación. Fue duro y todavía me dejó cicatrices. Pero demostré que puedo ser un Escudo Azul. Fue un día por el que estaré orgulloso toda mi vida.}
{224}{}{¿Qué es lo que haces para los Escudos Azules?}
{225}{}{Ya sabes, lo que me diga Ben o Rio. Hace poco estaba a cargo de entregar combustible antes de un asalto. Ben es muy conservador con nuestros suministros, así que controla mucho el combustible.}
{226}{}{¿Me podrías dar un litro o dos?}
{227}{}{¡Claro! Me ayudaste. Te haré unos cócteles molotov o te lo puedo dar en bruto, lo que sea, pero no todo, ¿vale?}
{228}{}{Genial...}
