{100}{}{Ves a la esclava de Ben.}
{101}{}{Ves una mujer. Su rostro fue hermoso alguna vez, pero ahora se contorsiona en un ataque de histeria.}
{102}{}{Te hice un favor, perra.}
{103}{}{Espero que encuentres la paz.}

{110}{}{¡Mátame, por favor!}
{111}{}{No puedo vivir luego de todo lo que me han hecho.}
{112}{}{Me trataron como un pedazo de carne.}
{113}{}{Ya no lo soporto.}
{114}{}{Mátame.}
{115}{}{Solo quiero estar en paz.}

{120}{}{¡No puedo creerlo, están todos muertos! ¡Gracias, gracias!}
