{100}{}{Ves una puerta.}

{110}{}{La puerta está cerrada desde adentro.}
{111}{}{La puerta está cerrada.}
{112}{}{Quitas el cerrojo de la puerta. Ahora el camino está despejado.}
{113}{}{La puerta está cerrada desde adentro. No puedes abrirla desde aquí.}
{114}{}{Ya quitaste el cerrojo de la puerta.}
{115}{}{Pusiste el cerrojo de nuevo. La puerta está bloqueada..}
{116}{}{Tienes que cerrar la puerta primero.}
{117}{}{El cerrojo solo puede cerrarse desde adentro.}
{118}{}{No hay ninguna cerradura, tiene un cerrojo.}
{119}{}{La puerta es demasiado resistente para tirarla abajo.}
