{102}{}{Alguien amarró a este pobre hombre al poste para que sea visto por todos. El calor lo hace delirar, está hablando sólo.}
{103}{}{No puedes reparar a un ser humano. Es una pena.}

{200}{}{¡A-agua! ¡Te lo ruego, dame agua!}
{201}{}{[Ignóralo]}
{202}{}{[escupe en el suelo] Ahí está tu agua.}
{203}{}{¡Señor, tenga piedad! ¡Estoy muriendo de sed!}
{1203}{}{¡Señorita, tenga piedad! ¡Estoy muriendo de sed!}
{204}{}{No sé qué hiciste, pero seguro que lo mereces. Adiós.}
{205}{}{Está bien, iré por un poco de agua.}
{206}{}{Claro, te traeré agua, espérame.}

{210}{}{(Traga tanto como puede) ¡Agua! Jamás había estado tan feliz de tomar agua. Gracias, señor, me salvó la vida.}
{1210}{}{(Traga tanto como puede) ¡Agua! Jamás había estado tan feliz de tomar agua. Gracias, señorita, me salvó la vida.}
{211}{}{Dime, ¿por qué te ataron?}
{212}{}{¿Quién te dejó a tu suerte bajo el sol?}
{213}{}{Frank me hizo esto. Es así como castiga a cualquiera que se pase de la raya.}
{214}{}{¿Y qué hiciste?}
{215}{}{Me parece un castigo muy brusco.}
{216}{}{Tomé demasiado tequila, y... Me puse agresivo. Es mi culpa, lo admito. Pero me habría salido con la mía, si es que no le hubiera gritado al propio Frank... Fue un error.}
{217}{}{Bueno, al menos Frank sí tenía una razón. Lo bueno es que admites lo que hiciste.}
{218}{}{Frank no puede hacerte esto, no hiciste nada malo.}
{219}{}{Estuvo mal lo que hice, ahora lo sé. No lo haré de nuevo, si sólo me dieran otra oportunidad... Ay, mi cabeza...}
{220}{}{¿Quieres que te desate?}
{221}{}{Ya veo.}
{222}{}{No, señor. Gracias, pero a Frank no le gustará. Me volverá a amarrar otro día, quizás dos. Es mejor que no lo provoque. Así son las cosas por aquí - o sigues las reglas, o te obligan a seguirlas. Lo entendí a las malas, jamás volveré a cometer este error.}
{1222}{}{No, señorita. Gracias, pero a Frank no le gustará. Me volverá a amarrar otro día, quizás dos. Es mejor que no lo provoque. Así son las cosas por aquí - o sigues las reglas, o te obligan a seguirlas. Lo entendí a las malas, jamás volveré a cometer este error.}
{223}{}{¿Quién es Frank?}
{224}{}{Es nuestro sheriff. Probablemente sea la persona más importante del pueblo, debe estar en la cárcel, al lado de la entrada.}

{230}{}{Gracias, señor. No sabe cuánto lo agradezco.}
{1230}{}{Gracias, señor. No sabe cuánto lo agradezco.}
{231}{}{Tú puedes.}
{232}{}{Puedo desatarte.}
