{100}{}{Ves a Nick.}
{101}{}{Ves a uno de los ciudadanos de Casa Nueva.}
{102}{}{Tenemos una regla muy simple, cuando es de noche, nos vamos a dormir y no molestamos a los demás.}

{200}{}{Hola, soy Nick. ¿Te ayudo en algo?}
{201}{}{Es un gusto conocerte, Nick. ¿Te puedo preguntar algo?}
{202}{}{Tu nombre no me importa, pero necesito preguntarte algo.}
{203}{}{Tengo que irme.}

{210}{}{¿Cómo te puedo ayudar?}
{211}{}{¿Qué quieres?}
{212}{}{No es nada. Adiós.}
{213}{}{¿Te puedo hacer una pregunta?}

{220}{}{Claro.}
{221}{}{Gracias, Nick. Adiós.}
{222}{}{Eh, perdón, pero tienes que hablarle al alcalde. O tendremos problemas.}
{223}{}{¿Lo dices en serio? Bueno...}

{230}{}{¿Quién eres?}
{231}{}{Ya te lo dije, me llamo Nick.}
{232}{}{¿Qué haces aquí, Nick?}
{233}{}{¿Cómo puede ser que alguien con un nombre así viva en un lugar como este?}
{234}{}{Estoy trabajando. Solía trabajar en una planta de concreto, pero cerró hace poco.}
{235}{}{Eres realmente dedicado, muy poca gente haría un esfuerzo así. Quiero preguntarte otra cosa.}
{236}{}{¿Y ahora no haces mucho, verdad? Bueno, tengo algo que sí puedes hacer - responder mis preguntas.}
{237}{}{Debes tener mucho tiempo libre. ¿Me podrías responder unas cosas?}

{240}{}{¿Cómo acabaste aquí?}
{241}{}{Sabes, aquí no es nada normal preguntarle a alguien sobre su pasado. Queremos construir una vida nueva para reemplazar la vieja. Pero si de verdad quieres saber, vengo de Casa Grande. Es un pueblo pequeño, en el camino a Fénix. ¿Has pasado por ahí, verdad?}
{242}{}{¿Casa Grande? No, nunca. ¿Te puedo preguntar otra cosa?}
{243}{}{¿Acaso intentas sonar astuto? Conozco Casa Grande, por supuesto. Tengo otras preguntas.}
{244}{}{Sí, he estado por ahí. Tengo más preguntas.}
{245}{}{¿Cuánta libertad tienes aquí? ¿Puedes irte si así lo deseas?}
{246}{}{¿Por qué me iría del paraíso? A los alrededores no hay más que desierto, y en los asentamientos grandes abunda la miseria. Es cierto, pierdo parte de mi libertad. Pero a cambio, me dan comida y un hogar. Primero, tenemos que sobrevivir y crear un nuevo mundo, sólo después de eso podremos pensar en la libertad. Así son las cosas en estos tiempos.}
{247}{}{Eso es muy inspirador, Nick. La vida aquí es mucho mejor que en el resto de Arizona. ¿Me puedes contar otra cosa?}
{248}{}{Sólo los débiles no se atreven a ir contra la corriente. Ojalá que tengas la fuerza de responderme una cosa más.}
{249}{}{Lo entiendo. ¿Te puedo preguntar una cosa más?}
{250}{}{¿En dónde está Casa Grande?}
{251}{}{En el medio de la Interestatal 10, entre Fénix y Two-Sun. Te lo mostraré en el mapa.}
{252}{}{Gracias.}
