{100}{}{Ves a Meñique.}
{101}{}{Ves a... una rata cerdo mascota. Qué inusual...}
{102}{}{¡Squeak!}
{103}{}{¡Grr!}
{104}{}{Meñique murió de la nada.}
{105}{}{Squee...}
{106}{}{Grrrr...}
{107}{}{¡Gggraaahhh!}

{200}{}{¡Squeak!}
{201}{}{Sí, sí, squeak.}
{202}{}{¿Sabes hablar, pequeñín?}
{203}{}{Vámonos, Meñique.}
{204}{}{¡Squeak! ¡Squeak!}
{205}{}{Buen chico.}
{206}{}{Espérame aquí, Meñique.}
{207}{}{Ve a casa, Meñique.}
