{100}{}{Ves a Lo.}
{101}{}{Ves a una vieja campesina con las manos desgastadas. Se truena la espalda.}
{102}{}{Vete o llamaré a los guardias.}

{210}{}{¿Qué quieres?}
{211}{}{¿Qué pasa?}
{212}{}{¿Quién eres?}
{213}{}{No vendo nada, lo siento.}
{214}{}{Deberías hablar con el alcalde, yo sólo soy una trabajadora.}
{215}{}{Parece que te equivocaste de casa.}

{220}{}{Me hace feliz verte.}
{221}{}{Y, ¿qué te parece el pueblo?}
{222}{}{¿Quieres hablar de algo?}
{223}{}{¡Hola! Es genial ver que sigues aquí.}
{224}{}{Todos agradecemos tu ayuda.}

{229}{}{Adiós.}

{230}{}{¿Quién eres?}
{231}{}{Me llamo Lo.}
{232}{}{¿Qué haces, Lo?}
{233}{}{Trabajo. En el campo. Es mi trabajo.}
{234}{}{No es nada fácil, ¿verdad?}
{235}{}{Trabajar es mucho más duro que asaltar caravanas, ¿verdad? Ah, perdóname, pensé que eras uno de "esos"...}
{236}{}{Hmm... Voy a pretender que no te escuché.}
{237}{}{No importa, es entendible que no confíes en un desconocido.}

{240}{}{¿Te gusta vivir aquí?}
{241}{}{¡Es maravilloso! Es el mejor lugar del yermo. Hay que trabajar duro a cambio de la protección y el alimento que nos dan, eso es obvio. Pero es justo. ¡Es todo gracias a los Seguidores y el alcalde Álvaro!}
{242}{}{Me alegra que te guste tanto.}
{243}{}{¿Estás hablando en serio?}
{244}{}{Por supuesto, no hay lugar como Casa Nueva. Y si no te gusta, puedes irte a otro lado.}
{245}{}{Está bien, te creeré.}
{246}{}{Es bueno saberlo. Ten un buen día.}
{247}{}{Creo que exageras. Después de todo lo que he visto, me parece que viven como esclavos.}
{248}{}{Por favor... (mira a su alrededor) No hables de eso... Tenemos muchas regulaciones y leyes, algunos no lo soportan. Hasta tenemos prohibido hablar sobre cómo vivimos.}
{249}{}{¿Y por qué no protestar por sus derechos?}
{250}{}{Porque no tenemos. Sólo somos campesinos, serviremos por toda la vida, casi somos esclavos... Castigan a cualquiera que se queje, y cualquier protesta nos llevaría a la otra vida. Suficiente, no es asunto tuyo.}
{251}{}{Sí, me lo dejaste... muy claro.}
{252}{}{Un momento... Hmm, ¿puedo ser honesta con nuestro héroe, verdad?}
{1252}{}{Un momento... Hmm, ¿puedo ser honesta con nuestra heroína, verdad?}
{253}{}{Claro, ¿qué pasa?}
{254}{}{Depende, ¿de qué se trata?}
{255}{}{Todo este tiempo he dudado acerca de este lugar, sobre cuánto va a durar. Así que guardaba munición en caso de que cambiara de parecer y quisiera escapar.}
{256}{}{Sigue.}
{257}{}{¿Y?}
{258}{}{Pero, debería dejar el pasado atrás, porque el mañana será mucho más hermoso. Llévate estos cartuchos, los necesitarás más que yo.}
{259}{}{Gracias. Me serán de ayuda.}
{260}{}{Bueno, si insistes.}
