{100}{}{Ves a Rosalía.}
{101}{}{Ves a una campesina, su ropa está en buen estado.}
{102}{}{Hola, jovencito. ¿Traes alguna noticia del yermo?}
{1102}{}{Hola, jovencita. ¿Traes alguna noticia del yermo?}
{103}{}{¡Esos bastardos! Sabían que al encerrarme no podría decir nada y los demás dejarían de confiar en mí.}

#First meeting
{200}{}{Un extranjero... Hola, ¿Es tu primera vez aquí, no?}
{1200}{}{Una extranjera... Hola, ¿Es tu primera vez aquí, no?}
{201}{}{¿Por qué lo preguntas?}
{202}{}{Me gustaría hablar contigo... en privado, si eso está bien.}
{203}{}{Claro. ¿Por qué no?}
{204}{}{Eso es sospechoso. ¿Qué quieres de mí?}
{205}{}{Es importante. Veámonos afuera del pueblo para que nadie nos escuche.}
{206}{}{Claro, nos vemos bajo el cartel de la entrada.}
{207}{}{Más te vale que esto no sea una estafa.}
{208}{}{Piérdete.}

{210}{}{Gracias por venir, ¿nadie te siguió, verdad?}
{1210}{}{Gracias por venir, ¿nadie te siguió, verdad?}
{211}{}{No... ¿Por qué me pediste que viniera?}
{212}{}{Verás... mi esposo desapareció hace unos días. Se fue a la plantación y nunca volvió, y no lo puedo encontrar. ¡Necesito que me ayudes!}
{213}{}{Pero, ¿por qué me lo dices en secreto?}
{214}{}{¡Porque no tengo permitido hablar de ello? Es para no causarles pánico a los demás, eso me dijo el alcalde. ¡Debe ser una conspiración! Están escondiendo algo.}
{215}{}{¿Qué hay de los demás? ¿Acaso nadie del pueblo lo está buscando?}
{216}{}{Este lugar no es tan pacífico como lo parece, nos obligan a quedarnos callados, pero créeme, no es la primera vez que alguien desaparece.}
{217}{}{¿Cómo te obligan?}
{218}{}{Tenemos reglas muy estrictas, si lo miras desde afuera, este lugar es un paraíso, pero en realidad lo pagamos con nuestra libertad. Si alguien causa problemas, es castigado o expulsado.}
{219}{}{Comprendo. Lo buscaré, ¿cómo se ve tu esposo?}
{220}{}{Es moreno, bajo, tiene bigote... Ah, y lleva un collar de nuestro matrimonio. El alcalde le otorga uno a cualquiera que se case en nuestra ciudad.}
{221}{}{Intentaré encontrarlo.}
{222}{}{No te prometo nada.}
{223}{}{Me parece que podría traerme problemas. Veré qué encuentro, pero te costará.}
{224}{}{Por supuesto, puedo darte comida y todas mis chapas - ya no me queda nada más.}
{225}{}{¡Por favor, encuéntralo! ¡Nadie más me ayudará con esto!}
{226}{}{Cálmate, ya entendí.}

{230}{}{¿Qué tal está todo? Como puedes ver, yo he estado mejor.}
{231}{}{¿Y? ¿Lo encontraste?}
{232}{}{Todavía no.}
{233}{}{Entiendo. Adiós.}

{240}{}{Todavía no nos presentamos. ¿Cómo te llamas?}
{241}{}{Ah, perdón. Me llamo Rosalía, me ocupo de las cosechas.}
{242}{}{Tengo que irme, Rosalía.}
{243}{}{Dicen que discutías con tu esposo.}
{244}{}{¡Es obvio que discutíamos! No nos casamos por amor, el alcalde apoya los matrimonios y nos dan beneficios. Pero con los años, nos acostumbramos el uno al otro...}
{245}{}{Ya veo...}
{246}{}{Un momento, ¿quién te dijo eso? ¿No se lo dijiste al alcalde, cierto? ¡No podemos confiar en él, debes entenderlo! Ni siquiera pienses en hablarle de los desaparecidos.}
{1246}{}{Un momento, ¿quién te dijo eso? ¿No se lo dijiste al alcalde, cierto? ¡No podemos confiar en él, debes entenderlo! Ni siquiera pienses en hablarle de los desaparecidos.}
{247}{}{Ya entendí, cálmate...}

{250}{}{Tu esposo está muerto. Lo siento.}
{251}{}{¿Será que tu esposo era un mutante verde? Si es así, su cadáver se está pudriendo en el granero de la plantación.}
{252}{}{Lo sabía... Lo sabía. ¿Lo mataron? ¡Dime la verdad!}
{253}{}{No lo parece, le ocurrió algo extraño. Es como una... enfermedad. Es mejor que lo veas por ti misma.}
{254}{}{Dios mío... ¿Qué le pasó? Sabíamos que algunos insectos pueden infectarse, ¿pero qué causaría una infección así?}
{255}{}{¿Cómo? ¿No es la primera vez que esto ocurre?}
{256}{}{Es todo culpa de los Seguidores. ¡Lo mataron con sus experimentos! ¡Y no fue el único! ¡Son unos demonios!}
{257}{}{¿Los Seguidores del Apocalipsis? ¿De qué clase de experimentos hablas?}
{258}{}{Tienen un laboratorio en el desierto, pero tenemos prohibido acercarnos... ¡Malditos científicos! Nos trajeron estas cosechas, y a cambio se llevaron nuestras almas.}
{259}{}{[Mantén el silencio]}
{260}{}{Tienes un buen corazón, amigo. Dios te bendiga, y por favor, aléjate de esos científicos.}
{1260}{}{Tienes un buen corazón, amiga. Dios te bendiga, y por favor, aléjate de esos científicos.}
{261}{}{No te rindas, Rosalía. Adiós.}
{262}{}{Puede que eso sea lo más seguro, pero debería hablar de esto con ellos. Adiós.}
{263}{}{Hice lo que me pediste. ¿Y mi dinero?}
{264}{}{¿Qué quieres? ¿Chapas? ¡Llévatelas y déjame sola! Ustedes solo piensan en sí mismos...}
{265}{}{No te alteres tanto, mujer.}
