{100}{}{Ves a un trabajador.}
{101}{}{Ves a un hombre en uniforme de trabajo. Está exhausto.}

{110}{}{Así que tú eres la razón por la que estoy atrapado aquí.}
{111}{}{Si no hubiera sido por ti, no me tendrían como esclavo acá.}
{112}{}{El administrador está en ese edificio de allá.}
{113}{}{¿Alguna idea de cómo me puedo escapar?}
{114}{}{A la mayoría nos tienen de trabajo forzado. Al resto les pagan una miseria.}
{115}{}{¿Estás aquí a hacer mierda el sitio?}
{116}{}{Dicen que había un monstruo por acá. Ojalá haya sido el único.}
{117}{}{Si el monstruo vuelve otra vez, ojalá me disparen en la cabeza.}
{118}{}{Hay muchísima demanda de concreto y ladrillos.}
{119}{}{Tenemos mucho trabajo. Son tres turnos.}
