{100}{}{Ves un mezclador de gas.}
{101}{}{Ves un sistema de cilindros de gas y tuberías conectados al sistema de ventilación. Parece ser parte del control climático.}
{102}{}{Esto es una parte del control climático. Tiene un cartel cerca, "¡Peligro! ¡Puede ser explosivo!"}
{103}{}{El sistema se está sobrecalentando y está a punto de incinerar todo a su alrededor.}
{104}{}{Eso no ayudará, el sistema sufrió una falla y está a punto de quemar todo a su alrededor.}
{105}{}{¡Arde! ¡Arde!}
{106}{}{El sistema está a punto de sobrecargarse, explotará en cualquier momento.}