{110}{}{No es necesario reparar esto.}
{111}{}{Se ha acabado la materia prima.}
{112}{}{No tienes la menor idea de cómo funciona esto.}
{113}{}{Esta máquina está configurada únicamente para hojas de agave que estén maduras.}
{114}{}{Esta máquina se utiliza para crear jarabe, no al revés.}

{120}{}{Has preparado una botella de jarabe.}
{121}{}{Has preparado dos botellas de jarabe.}
{122}{}{Has preparado tres botellas de jarabe.}
{123}{}{Has preparado cuatro botellas de jarabe.}
{124}{}{Has preparado cinco botellas de jarabe.}
{125}{}{Has preparado seis botellas de jarabe.}
{126}{}{Has preparado siete botellas de jarabe.}
{127}{}{Has preparado ocho botellas de jarabe.}
{128}{}{Has preparado nueve botellas de jarabe.}
{129}{}{Has preparado diez botellas de jarabe.}
