#Using items
{200}{}{Esto no funcionará en el maletero. Prueba a usarlo en la motocicleta.}
{201}{}{Al reemplazar la parte vieja, el límite del peso de la motocicleta sube en 5.}
{202}{}{Ya reemplazaste eso, no es necesario hacerlo de nuevo.}
{203}{}{Es mejor que no hagas eso durante el combate.}
{204}{}{Instalaste un nuevo compartimiento para el maletero. La motocicleta podrá llevar más peso.}
{205}{}{No hay más espacio para contenedores adicionales en la motocicleta.}
{206}{}{La motocicleta no te pertenece.}

#Using skills
{300}{}{No hay nada que piratear aquí.}
{301}{}{Luego de examinar con cuidado el maletero, concluyes en que su peso límite es de }
{302}{}{ libras.}
{303}{}{Con la habilidad que posees, no será posible mejorar el maletero.}
{304}{}{No hay nada que reparar.}
{305}{}{No podrás reparar la bicicleta hasta que sea tuya.}
{306}{}{Luego del mantenimiento, la capacidad del maletero ha incrementado en 5.}
