{100}{}{Ves a Ralph.}
{101}{}{Estás viendo a un hombre de piel chamuscada y marchita. Lleva puesto un overol andrajoso, el cual lleva un emblema de la preguerra.}
{102}{}{No hago tratos con traidores.}
{103}{}{Agradezco tu ayuda, fuiste muy útil.}

{200}{}{Alto, no se permiten forasteros más allá de este punto. ¿Qué quieres?}
{201}{}{¿Qué están haciendo aquí? Pensé que este lugar era otra ruina abandonada.}
{202}{}{Hemos vivido aquí durante años, la ciudad entera lo sabe. Así que puedes dejar de mentir.}
{203}{}{Pero, yo no soy de aquí. Vengo de una aldea en el noroeste.}
{1203}{}{Pero, yo no soy de aquí. Vengo de una aldea en el noroeste.}
{204}{}{Ah, bueno, no es que te parezcas al hombre promedio de esta ciudad... tu piel está un poco quemada, tu acento es inusual. Eso es interesante...}
{1204}{}{Ah, bueno, no es que te parezcas a la mujer promedio de esta ciudad... tu piel está un poco quemada, tu acento es inusual. Eso es interesante...}
{205}{}{Hmph. ¿Y qué tal si me voy?}
{206}{}{¿Qué tiene eso de interesante?}
{207}{}{Bueno, mira, estamos en medio de una crisis, quizás puedas ayudarnos. Ve a hablar con el jefe de la planta y ve qué puedes hacer.}
{208}{}{Hmm... bueno.}

{210}{}{Pero qué... ¿Te maquillaste?}
{211}{}{No, esa es mi piel. Un poco verde, pero me las arreglo.}
{212}{}{Más te vale que no estés bromeando acerca de tu piel con *nosotros*.}
{213}{}{No, lo digo en serio. Este es el resultado de un experimento por el que pasé en el Infierno.}
{214}{}{(te mira de cerca) Demonios, es cierto. Bueno, la verdad ni siquiera puedo recordar cómo me veía antes de la Transformación. Fue difícil para ti, ¿no? Estoy feliz de verte.}
{215}{}{Oh, ¿así que ahora estás feliz de verme? Sí, claro.}
{216}{}{Lo mismo digo. Bien, ¿qué está pasando aquí?}
{217}{}{Cierto, no me había presentando. Me llamo Ralph, y se podría decir que soy la mano derecha de Theodore. Perdona si no te dimos una cálida bienvenida, pero últimamente no nos sentimos muy amistosos.}
{218}{}{Ralph, ¿te puedo hacer unas preguntas?}

{220}{}{¿Qué necesitas?}
{221}{}{Ahí nos vemos.}

{230}{}{¿Es cierto que esta planta eléctrica ha estado en funcionamiento desde la preguerra?}
{231}{}{Fue hace poco que pusimos el reactor principal en marcha otra vez, la planta había estado inactiva durante un largo tiempo.}
{232}{}{¿Cómo hicieron eso?}
{233}{}{Gracias a los Seguidores del Fuego y su colonia en Flagstaff. Allí se mina uranio y lo utiliza la iglesia, parte del mineral nos llega a nosotros. Fue un trato que beneficia a la ciudad entera.}
{234}{}{Esos tipos de la iglesia deben hacer más que rezar, entonces.}
{235}{}{Claro, los beneficia a ustedes, pero no a los esclavos que mueren minando el uranio.}
{236}{}{¿Y ustedes cómo llegaron acá?}
{237}{}{Llegamos aquí desde el oeste, de California, pero explicarte eso llevaría un buen rato. Nos dieron la oportunidad de restaurar la planta. La verdad es que ustedes, los de esta época, no saben ni madres de la tecnología de la preguerra.}
{238}{}{Espera, ¿o sea que ya estaban vivos antes de que ocurriera la Gran Guerra?}
{239}{}{Nos hemos conservado bien, ¿no? Ese es nuestro chiste favorito. Se dice que nuestra mutación fue causada debido a un virus que quedó libre cuando bombardearon un laboratorio durante la guerra. Pero, es sólo un rumor.}
{240}{}{¿Cómo era el mundo antes de la guerra? Cuéntamelo.}
{241}{}{Hmm... Han pasado cien años, eso es mucho tiempo y no lo recuerdo todo. Me acuerdo de los carros, los rascacielos, los controles militares. Me acuerdo de la guerra y cómo las bombas cayeron sobre las ciudades. Pero, ¿cómo puedo explicarle eso a alguien como tú? Para ti, es sólo parte de la historia.}
{242}{}{Tiene sentido que deba ser difícil recordar eso. Cambiemos de tema.}
{243}{}{¿Alguien cómo yo? Entonces quédate con tus historias, Sr. Piel Podrida.}
{244}{}{Tu jefe me dijo que *alguien* hizo explotar la tubería. ¿Qué piensas de eso?}
{245}{}{Vaya, eso es una acusación grave. No le prestes mucha atención a lo que dice el viejo. No me digas que no te diste cuenta que está loco.}
{246}{}{Pero, se supone que todavía me debe mi paga por el trabajo.}
{247}{}{Entonces, has lo que dice. Si quiere culpables, encuéntralos, pero eso mismo es la parte difícil... Sabes, los saboteadores tuvieron que haber entrado por las alcantarillas. Pero... pensé que habíamos sellado bien las entradas.}
{248}{}{Hmm, entonces iré a revisar las alcantarillas.}
{249}{}{Lo más probable es que los saboteadores hayan entrado a través de las alcantarillas. Pero, pensé que habíamos sellado todas las entradas adecuadamente.}

{250}{}{Eres un Engendro del Infierno Electromagnético... ¡Vete de aquí! Todo estaba bien hasta que llegaste.}
{251}{}{Estás acabado, Ralph. Perdiste.}
{252}{}{Oh, no, apenas vamos a empezar a divertirnos. ¡Verás el verdadero poder del Viejo Mundo!}
{253}{}{No, no hagas eso...}
{254}{}{Es tu funeral, imbécil.}
{255}{}{Ralph, escúchame. Te usaron, lo cierto es que esto fue una mala idea desde el principio.}
{256}{}{Es un contrato que nos beneficiará a ambos. La planta podría cobrar vida y así estaría resucitando una pieza del Viejo Mundo, sólo los Seguidores del Fuego son capaces de eso, no hay nadie más que tenga el conocimiento o los recursos necesarios para hacer eso. Y el viejo Theodore está perdiendo la cabeza. Me da miedo pensar en cómo acabará todo esto si él está al volante.}
{257}{}{Aunque eso sea verdad o no, no saldrás de aquí con vida.}
{258}{}{A la iglesia no le importas tú, ni los demás, o el mundo a su alrededor. ¿Acaso no lo ves?}
{259}{}{¡Me cansé de oír tus estupideces! Ahora verás el verdadero poder del Viejo Mundo.}
{260}{}{Te entiendo, quieres traer de vuelta al Viejo Mundo que conocías. Pero mira a tu alrededor - los Seguidores del Fuego están creando un mundo distinto.}
{261}{}{Un mundo distinto... Hmm... Eso es verdad. Puede que Aaron sólo nos esté utilizando para construirse un imperio. No lo había pensado, realmente. Pero si lo piensas a bien... Mierda, ¿qué debería hacer? ¿Regresar a una California en ruinas? ¿O irme más al este con los demás? Quién sabe, quizás encontremos petróleo en Texas, o podamos resucitar a las viejas fábricas de Chryslus Motors.}
{262}{}{Créeme, aquí no tendrás ningún futuro. En el mejor de los casos, serás otra herramienta más en las manos de ese emperador.}
{263}{}{He oído suficiente, no puedo dejar que un lunático como tú quede en libertad. Morirás aquí y ahora.}
{264}{}{Bien dicho. Me iré sin causar problemas. Dile a Theodore que sus guardias me dejen pasar.}
{265}{}{Bien pensado, Ralph.}
{266}{}{Tu jefe me pidió que arreglara el sistema de enfriamiento. ¿Por dónde puedo empezar?}
{267}{}{¿En qué está pensando ese viejo al permitir que un forastero entre al corazón de la planta? Bueno, a ver. Primero, debes revisar el daño hecho en la planta inferior. Te harán falta materiales y equipamiento para reparar la tubería, el lugar más fácil en donde conseguir eso es la base de los Hojalateros. Está en algún punto al sur de Fénix, los caravaneros deberían saber exactamente el dónde.}
{268}{}{Gracias.}

{270}{}{Sé que los Cardenales contaron con tu ayuda para sabotear el sistema de enfriamiento.}
{271}{}{Habla más bajo, no te precipites. Vamos a un lugar más tranquilo...}
{272}{}{[Continuar]}
{273}{}{Debes tener algún contacto con los Seguidores del Fuego, si no, ¿cómo te enteraste de nuestro acuerdo? Es un secreto.}
{274}{}{Tengo muchos contactos. Pero, ¿qué es lo que quieres *tú*? ¿Quieres quitarle el puesto a tu jefe?}
{275}{}{Por favor, eso sería un motivo poco visionario. No olvides que tengo cien años, si estuviésemos en el Viejo Mundo yo estaría ganando ascenso tras ascenso. Pero, ¿qué es lo que le queda al mundo? Nada más que ruinas, no hay infraestructura, no hay servicios, carreteras, agua corriente y potable... las personas sólo han conocido las luces de las farolas gracias a nosotros y la Iglesia del Fuego Santo.}
{276}{}{La iglesia te abastece de uranio, ¿verdad?}
{277}{}{Sí, pero hacer trueques para conseguir uranio no nos basta. Theodore consigue mantenerlos alejados de los asuntos de la planta eléctrica, pero sin ellos, vamos más lentos que un caracol. Al principio, las cosas eran puramente técnicas - nos daban uranio y lo usábamos para obtener energía. Pero ha llegado el momento y debemos tener en cuenta la economía, de los negocios y los impuestos. Theodore no entiende nada acerca de esto y cree que venderle energía a todos es suficiente.}
{278}{}{Entonces quieres negociar un trato exclusivo con ellos. ¿Qué hay de Theodore?}
{279}{}{El problema es que está perdiendo la cabeza y a pesar de eso, los demás trabajadores todavía lo apoyan. Necesito tomar el liderazgo de la planta para que las cosas cambien. Ayúdame a lidiar con Theodore, eso te hará ganar respeto y una recompensa. Y más que eso, le estarás haciendo un favor a la ciudad entera.}
{280}{}{Voy a pensármelo.}
{281}{}{Debido a que has arreglado el sistema de enfriamiento, una parte de mi plan ya falló. No cometas más errores.}
{1281}{}{Debido a que has arreglado el sistema de enfriamiento, una parte de mi plan ya falló. No cometas más errores.}
{282}{}{Adiós.}
{283}{}{Ya no tenemos nada más de qué hablar. No cometas más errores.}
{284}{}{Adiós.}
{285}{}{Pero, ¿cómo puedo eliminar a Theodore? No es una tarea fácil.}
{286}{}{Ya lo había pensado, debes ser discreto al asesinarlo o causará disputas y sospechas. Intenta utilizar veneno o drogas potentes, ese necrófago ya está viejo, su corazón no lo aguantará.}
{287}{}{Buena idea, sé que hay un traficante en algún punto de los barrios bajos.}
{288}{}{Listo, la posición de jefe de la planta ya está vacante.}
{289}{}{El Ángel del Electromagnetismo te tuvo que haber enviado con nosotros. Gracias, hiciste lo correcto. Ve con el intendente y pide una recompensa, encontrará alguna forma de agradecértelo.}
{1289}{}{El Ángel del Electromagnetismo te tuvo que haber enviado con nosotros. Gracias, hiciste lo correcto. Ve con el intendente y pide una recompensa, encontrará alguna forma de agradecértelo.}
{290}{}{Adiós, Ralph.}

{291}{}{He oído que Flagstaff te abastece con uranio.}
{1291}{}{He oído que Flagstaff te abastece con uranio.}
{292}{}{No exactamente. Flagstaff envía el uranio al sur y ellos nos envían las barras de uranio que utilizamos como combustible. ¿Por qué lo preguntas?}
{293}{}{Ese uranio es extraído con esclavos, ¿no te molesta?}
{294}{}{No me importa quién o cómo lo minan. Necesitamos uranio, lo demás no es nuestro problema.}
{295}{}{Hmm. Lo entiendo... Pero sigues siendo parcialmente responsable.}
{296}{}{Lo entiendo, son negocios.}
