{100}{}{Ves a un necrófago de la central eléctrica.}
{101}{}{Ves a un hombre con la piel chamuscada y podrida. Lleva un traje desgastado de trabajo, con un símbolo de la preguerra.}
{102}{}{Gracias, Doc. De verdad lo aprecio.}
{103}{}{Tengo un problemita. ¿Conoces algún doctor?}

{200}{}{Muchísimas gracias. No pensé que quedaran doctores en el mundo.}
{201}{}{¿Qué te pasó?}
{202}{}{Estábamos reparando las tuberías cuando una se reventó, y me lanzó contra la baranda. Al menos no me caí al nivel inferior, si hubiera sido así, estaría nadando en los desechos radioactivos como un pato en una tina.}
{203}{}{Entonces tuviste un montón de suerte. Cuídate.}
{204}{}{Nos vemos luego.}
{205}{}{¿Pato?}
{206}{}{Sí, ya sabes, un pájaro, de antes de la guerra. Desde ese entonces no he visto ninguno vivo, quizás se extinguieron como los dinosaurios...}
{207}{}{¿Dinosaurios?}
{208}{}{Ah, no importa. Dejémoslo así.}

{210}{}{Hola, Doc. Gracias otra vez.}
{211}{}{De nada.}
