{100}{}{Ves a Badi.}
{101}{}{Ves a un mendigo, apenas sobrevive. Es un milagro que siga vivo.}
{102}{}{Hola. ¿Cómo estás?}
{103}{}{Me vengaré, lo juro.}

{200}{}{Ya llegamos. Ten cuidado, los robots deben estar por ahí. Si los destruyes, las chapas serán nuestras.}
{201}{}{No perdamos el tiempo, espérame aquí.}
{202}{}{No me digas. Espera aquí.}
{203}{}{Necesito saber más acerca de este lugar.}

{210}{}{No hay que perder el tiempo.}
{211}{}{Espera, ya vengo.}
{212}{}{Ya casi es de noche. Apresúrate, por favor.}

{220}{}{¿Qué es este lugar?}
{221}{}{Es un almacén de Nuka-Cola de la preguerra. Solían guardar la bebida antes de distribuirla. Había otra planta en donde la embotellaban, pero la destruyó la explosión nuclear.}
{222}{}{¿Por qué los chatarreros no han saqueado este lugar?}
{223}{}{Las ruinas de alrededor hacen que sea difícil llegar aquí. Además, aquí cerca hubo una explosión nuclear y eso asusta a los demás. Y están los malditos robots, por supuesto.}
{224}{}{¿Se te ocurre cómo podría deshabilitar a los robots o algo así?}
{225}{}{Pensé que ya sabrías cómo hacer eso. Quizás haya un interruptor o algo así allá adentro. No entiendo la tecnología, especialmente si es de la preguerra. Nadie sabe, excepto quizás los Seguidores en la Catedral.}
{226}{}{¿Podrías recordarme lo que estamos buscando?}
{227}{}{¡Chapas! Muchas, muchas chapas.}
{228}{}{De acuerdo.}
{229}{}{Volveré.}

{250}{}{Estas son todas las chapas que encontré ahí adentro.}
{251}{}{¿Una caja entera? Carajo, ¡eso es una fortuna! Somos más ricos que la mitad de la ciudad. ¿Puedes creerlo?}
{252}{}{No tan rápido. Primero tienes que pagar tu deuda al casino.}
{253}{}{Ah, claro. Estaba tan emocionado que me olvidé. Aquí tienes.}
{254}{}{Genial. Y ahora, dame mi parte - es la mitad.}
{255}{}{Eso me deja con menos de lo que esperaba. Apenas será suficiente para pagar la renta y mis otras deudas. Quedaré pobre, de nuevo.}
{256}{}{Así es la vida. Es tu culpa por dejar que llegara a esto. Ahora hay que volver a la ciudad.}
{257}{}{¿Sabes? Cambié de opinión. Me llevaré TODAS las chapas.}
{1257}{}{¿Sabes? Cambié de opinión. Me llevaré TODAS las chapas.}
{258}{}{¡No! ¡No puedes hacerme esto! Somos socios, yo te traje aquí... Demonios, algún día... algún día tendré tantas chapas que contrataré mercenarios para que te maten. Y jugaré al fútbol con tu cabeza. Te arrepentirás de este día.}
{259}{}{Suerte con eso. Adiós, perdedor.}
{260}{}{Hmph. Entonces debería acabar contigo ahora mismo.}
