{100}{}{Ves una mujer de los barrios bajos.}
{101}{}{Ves una mujer con una mirada preocupada. Se ve fuera de lugar con la casa.}
{102}{}{¡Un bastardo lo mató!}
{103}{}{¿Eh? ¿Cómo? ¿Tienes comida?}
{104}{}{Gracias, señor.}
{1104}{}{Gracias, señorita.}

{200}{}{Hola. ¿Te puedo ayudar en algo?}
{201}{}{Lo más seguro es que no.}

{210}{}{¿Quién eres?}
{211}{}{Me llamo Susie. Mi esposo y yo vivíamos en un rancho. Era difícil vivir allá, entonces probaremos suerte aquí.}
{212}{}{Adiós, Susie.}

{220}{}{¿Por qué vivir en un lugar así?}
{221}{}{No podemos permitirnos vivir en otro lado. Pero, al menos Vernon protege de la pandilla.}
{222}{}{¿Quién es Vernon?}
{223}{}{Es el gerente, su oficina está al fondo del pasillo, a la derecha.}
{224}{}{¿De qué pandilla hablas?}
{225}{}{Son gente peligrosa, los evitamos todo lo posible. Ten cuidado si vas al norte, se apropiaron de un gimnasio por allá.}
{226}{}{Entiendo. Adiós.}
{227}{}{¿Me podrías repetir tu nombre?}
{228}{}{¿Quién eres?}

{230}{}{¿Qué puedes contarme de esta zona?}
{231}{}{Es el peor barrio de la ciudad para vivir.}
