{100}{}{Ves a Badi.}
{101}{}{Ves a un mendigo que apenas puede mantenerse. Es una maravilla que siga vivo.}
{102}{}{Hola, socio. ¿Cómo andas?}
{103}{}{Me vengaré de ti, lo juro.}

{110}{}{¿Por qué debería seguir intentándolo?}
{111}{}{Estoy acabado.}
{112}{}{Me queda una chapa. Una.}
{113}{}{Perdí mi última chapa en el casino.}
{114}{}{No sé cómo voy a pagar mis deudas.}
{115}{}{Lo perdí todo en unos pocos días.}
{116}{}{Quizás este sea mi último día con vida.}
{117}{}{¿Me prestas mil chapas? Te las devolveré, lo juro.}
{118}{}{Parece que pronto seré un esclavo.}
{119}{}{Tendré que dormir en la calle.}

{200}{}{Ay, no me asustes así. Intento evitar a la gente que no conozco.}
{201}{}{¿Quién eres?}
{202}{}{Me llamo Badi, vivo aquí. Aunque no te reconozco.}
{203}{}{Eres un mugroso mendigo, ¿por qué deberías conocerme?}
{204}{}{Pues, hola, Badi. Soy }
{205}{}{.}

{210}{}{¿Qué quieres de mí?}
{211}{}{¿De ti? Nada. Adiós.}

{220}{}{Vernon está cansado de tus interminables deudas. Paga de una vez o piérdete.}
{221}{}{¡No, por favor, no me corras de aquí! Le pagaré a Vernon, pero sólo necesito un poco más de tiempo para saldar mis cuentas con el casino.}
{222}{}{¿Le debes dinero al casino?}
{223}{}{Sí, sé que suena tonto, pero tenía una buena racha y no pude controlarme.}
{224}{}{No voy a oír tus excusas. Lárgate de una vez.}
{225}{}{¡Pero si he vivido aquí por años! ¿En serio Vernon trata a sus huéspedes así? Chingada madre... esto no terminará así, lo juro.}
{226}{}{Ahí está la puerta.}
{227}{}{Entiendo. ¿Cuánto le debes a Vernon?}
{228}{}{37 chapas, es por la renta.}
{229}{}{Sé como se siente perderlo todo. No te preocupes, cubriré tu renta.}
{230}{}{¿En serio? ¡Que Dios te bendiga! ¡Gracias! ¡Muchas gracias!}
{231}{}{Para mí, eso no es nada. Soy }
{232}{}{. Recuérdalo.}
{233}{}{Nos vemos luego.}
{234}{}{Está bien, te daré un poco más de tiempo.}
{235}{}{¿Lo dices en serio? ¡Gracias! Pronto tendré el dinero, lo prometo.}
{236}{}{Más te vale que sea así.}

{250}{}{Le debes muchísimo dinero al casino. Se te acabó el tiempo.}
{251}{}{¡Ya les di todo lo que tenía! ¡No tengo nada más! Por favor, denme más tiempo. ¡Voy a pagar todas mis deudas!}
{252}{}{No, ya tuviste suficiente tiempo. ¿Por qué no puedes reunir unas cuántas chapas?}
{253}{}{En esta ciudad no hay trabajo y esta deuda arruinó mi reputación. Ahora mismo sobrevivo hurgando en las ruinas.}
{254}{}{Me parece que no hay nada que pueda quitarte. Sigue revolcándote en la pobreza.}
{255}{}{Dame una buena razón para no golpearte.}
{256}{}{¡No! No hagas eso, si Don Diego quiere que le pague, me necesita vivito y coleando, ¿no? Si no fuera así, ya estaría tieso o en la esclavitud. ¿No?}
{257}{}{Carajo, me haces perder el tiempo.}
{258}{}{¿Cómo vas a saldar tus deudas?}
{259}{}{Tengo un plan, sólo necesito más tiempo para prepararme.}
{260}{}{¿Es otra de tus excusas?}
{261}{}{¿Qué estás tramando? Vamos, cuéntame.}
{262}{}{Suficiente. Tráeme las chapas o te estás muerto.}
{263}{}{Escúchame, tú también podrías ganarte unas chapas. Don Diego no te pagará tanto, ni pensará en contratarte. ¡Pero yo sé cómo podrás ganarte unas chapas de verdad!}
{264}{}{Intrigante. Cuéntame más.}
{265}{}{Excusas y más excusas. Te escucharé, sólo por esta vez.}
{266}{}{Conozco un sitio que tiene un chingo de chapas. Lo digo en serio, yo soy el único que lo sabe. Podemos ir hacia allá, entrar, y llevarnos todo. Luego lo partimos cincuenta y cincuenta. ¿Qué te parece?}
{267}{}{Algo no me cuadra. ¿Por qué no lo has hecho antes?}
{268}{}{Es demasiado bueno para ser verdad. ¿Acaso hay una trampa?}
{269}{}{Sí, tiene un detallito. Es un almacén, y lo resguardan un par de robots. Algunas personas intentaron evadirlos, y terminaron... chamuscados. ¡Pero sé que tú podrías con ellos!}
{270}{}{Hmm, suena prometedor. ¿En dónde está?}
{271}{}{Esto me suena a estafa. Muéstrame en dónde está.}
{272}{}{Em, no. ¿Y qué tal si tú me estafas a mí? Es mi última oportunidad para sacarme las deudas de encima. Necesito a alguien en quién confiar, así que, ¿hacemos un trato? ¿Cincuenta y cincuenta?}
{273}{}{De acuerdo. Pero debo prepararme.}
{274}{}{Por supuesto. Equípate bien para lidiar con los robots, pero no traigas tanto bulto. Ah, y cerca de ahí impactó una bomba nuclear, así que hay áreas radioactivas, pero sé cómo evadirlas.}
{275}{}{Comprendo, Ya vuelvo.}
{276}{}{No me engañas. He oído suficiente, para la siguiente vez, volveré con un cuchillo.}
{277}{}{Oye, yo sólo te estoy ofreciendo un trato, no seremos socios permanentemente. Piénsalo un rato.}
{278}{}{Ya lo veremos.}

{280}{}{Respecto al 'trato', ya puedes llevarme al almacén.}
{281}{}{¡Genial! No te arrepentirás, vamos. Entre menos tardemos, mejor.}
{282}{}{Te sigo.}
