{100}{}{Ves a Bob.}
{101}{}{Estás viendo a un negro con barba, viste ropa de senderismo.}
{102}{}{Ves al viejo Bob. Está bebiendo, como de costumbre.}

#First Dialogue
{200}{}{Hola, ¿te perdiste?}
{1200}{}{Hola, ¿te perdiste?}
{201}{}{Algo así. ¿En serio vives aquí?}
{202}{}{(quejido de disgusto) Sí, esto es una casa comunal y esta es mi habitación.}
{203}{}{¿Y tú eres...?}
{204}{}{Soy Bob, un chatarrero y un manitas. Pero, ¿quién eres tú y qué haces aquí?}
{205}{}{No es asunto tuyo.}
{206}{}{¿Lo dices en serio? ¿Vienes a mi habitación y me dices que no es asunto mío? No sé quien seas, pero más te vale que te largues.}
{207}{}{No me digas que hacer.}
{208}{}{Perdona, ya me voy.}
{209}{}{Me llamo }
{210}{}{. Estoy visitando Fénix, busco un lugar en el que quedarme.}
{211}{}{Entonces háblale a Vernon, él es que maneja esta casa.}
{212}{}{Gracias.}
{213}{}{De acuerdo.}
{214}{}{¿Ya volviste? No querrás causar problemas, ¿o sí?}
{215}{}{Sí, es justo lo que quiero hacer.}
{216}{}{No, no quiero. Adiós.}
{217}{}{Te pido perdón por lo de antes. Soy }
{218}{}{, estoy buscando un lugar en el que quedarme.}
{219}{}{Seguro que sí. Pero primero, quiero hablar contigo.}

#Re-dialogue
{220}{}{Hola.}
{221}{}{¿Qué quieres?}
{222}{}{¿Buscas algo?}
{223}{}{¿Sí?}

{225}{}{Aléjate de mí, no quiero que me vean contigo.}
{226}{}{Este lugar es peligroso, no deberías estar aquí por cuenta propia.}
{227}{}{No sé que quieres, pero deberías irte de aquí.}
{228}{}{}
{229}{}{Nos vemos, Bob.}

{230}{}{Luchaste muy bien, }
{231}{}{. Peleas igual de bien que Iron Mike. Es una pena que no haya apostado, podría haberme hecho rico.}
{232}{}{Deberías haber apostado, entonces.}
{233}{}{Gracias por el apoyo, Bob.}
{234}{}{Fue otra pelea más. No es nada.}
{235}{}{Lo que tú digas, campeón. Lo que tú digas.}
{1235}{}{Lo que tú digas, campeona. Lo que tú digas.}
{236}{}{Hmm.}

#Questions about Scavengers
{250}{}{Mencionaste que eras un chatarrero.}
{251}{}{(desconfiado) Sí... tal vez. ¿Y qué?}
{252}{}{Sólo me daba curiosidad. ¿Qué hay de nuevo por aquí?}
{253}{}{Eh, no mucho.}
{254}{}{Sí, hubo una era dorada en la que los chatarreros inundaban las ruinas de Fénix. Ahora las únicas áreas sin explorar son las más peligrosas y altamente radioactivas de Fénix. ¿Y qué?}
{255}{}{Háblame sobre los chatarreros.}
{256}{}{¿De verdad no sabes sobre nosotros? Hmm, sí mantenemos un perfil bajo, supongo.}
{257}{}{He estado en Ciudad Garaje, allí también viven chatarreros.}
{258}{}{Ah, el viejo Kogan ya debe haber enloquecido por completo, ¿verdad? Una vez que empezó esa sucursal del cartel, llamó mucho la atención y un montón de chatarreros fueron hacia allá para ganar dinero. Yo tenía miedo de emprender un viaje tan largo. Pero ya no hay por qué ir hacia allá - dicen que las ruinas quedaron vacías y que el cartel se hizo pedazos.}
{259}{}{¿A qué se dedicas?}
{260}{}{De donde vengo, no hay chatarreros. ¿A qué se dedican?}
{261}{}{}
{262}{}{Un perfil bajo... bien... Hablemos de otra cosa.}
{263}{}{Entramos a las ruinas y buscamos cosas útiles, luego se venden en el mercado o algún cliente. Es un trabajo difícil y peligroso. Es por eso que los chatarreros formaron todo un cartel para operaciones a gran escala.}
{264}{}{¿En serio era tan alta la demanda?}
{265}{}{Por supuesto. La ciudad crecía y necesitaba más y más cosas. Sin embargo, hoy en día no queda mucho en las ruinas. Estos últimos años, mayormente he buscado partes electrónicas y libros para el Culto del Fuego.}
{266}{}{Ya veo. Por cierto, ¿qué hay de nuevo en la ciudad?}
{267}{}{¿Partes y libros? Hmph. Te deseo suerte con eso. Ya es hora de que me vaya.}

{270}{}{¿Qué sabes sobre los refugios?}
{271}{}{¿Refugios? ¿De qué hablas? Cualquier escondite puede ser un refugio.}
{272}{}{No, no, me refiero a los Grandes Refugios.}
{273}{}{Ah, el proyecto Vault-Tec. Me encontré con uno de esos, era... el número 26.}
{274}{}{¿En serio? ¿En dónde estaba?}
{275}{}{En las ruinas que hay al oeste, en el borde del cráter. El Cartel de Chatarreros lideró una expedición allá, pero el refugio estaba hecho polvo y regresamos con las manos vacías.}
{276}{}{Hmph. Eso es malo. ¿Qué hay de los demás refugios?}
{277}{}{Te emociona encontrar un botín de verdad, ¿no? Muchos lo han intentado, pero sólo obtuvieron cáncer cerebral o la bala de algún bandido. Si alguien sabe de Refugios, debe ser el Culto del Fuego, pero a ellos no les gusta compartir lo que saben.}
{278}{}{Gracias, quizás me puedan ayudar.}
{279}{}{Entonces hablarte no me sirve de nada, vejestorio.}
{280}{}{De acuerdo, hablemos de otra cosa.}

{290}{}{¿Podrías enseñarme algún truco?}
{291}{}{No quiero enseñarte nada. No me agradas. Vas por ahí causando problemas en la ciudad. ¿Acaso un cazador te picó el culo?}
{292}{}{Eh, cambiemos de tema.}
{293}{}{Está bien. Olvídalo.}
{294}{}{Créeme que esto es un trabajo peligroso e ingrato.}
{295}{}{Me parece que simplemente no te quieres meter conmigo.}
{296}{}{Tienes razón. No me agradas.}
{297}{}{Lo entiendo, espero que algún día cambies de parecer.}
{298}{}{Tú tampoco me agradas, Bob.}
{299}{}{Me parece que tu sabiduría debe ser muy útil. Eso me vendría bien en mis viajes.}
{300}{}{Claro, claro. Pero ya no soy alguien que pueda estar viajando por ahí. Sólo puedo contarte los lugares que hay alrededor de la ciudad, si eso ayuda.}
{301}{}{Genial, echémosle un vistazo al mapa de mi PipBoy...}
{302}{}{La parte más difícil es eludir a los problemas.}
{303}{}{Gracias, Bob. Esto me será de mucha ayuda.}

{350}{}{¿Qué hay de nuevo por aquí?}
{351}{}{(te entrecierra los ojos) No recuerdo que nos llevásemos bien como para hablar de las noticias locales.}
{352}{}{Creo que me dijiste que eras un chatarrero.}
{353}{}{Bueno, entonces dejémoslo ahí.}
{354}{}{Todo sigue igual en nuestro barrio. Pandillas, cultistas y la pobreza.}
{355}{}{Ya veo. No hablemos de cosas malas.}
{356}{}{¿Las pandillas los están amenazando?}
{357}{}{No nos amenazan, este barrio les pertenece. Los Cardenales Rojos controlan toda el área. Las demás pandillas son pequeñas y tienen miedo de venir aquí.}
{358}{}{¿Qué quieren los Seguidores del Fuego con este lugar?}
{359}{}{¿Qué hay de los Seguidores del Fuego?}
{360}{}{Quieren apoderarse de la ciudad entera. En sus ojos, los barrios bajos son simple y llanamente una fuente de mano de obra barata. Lo disimulan con sus misiones nobles, vienen a pedir limosna para los pobres, ese tipo de mentiras. Pero necesitamos ayuda de verdad, más que cualquier otro lugar en la ciudad.}
{361}{}{¿Piensas que no están siendo honestos?}
{362}{}{(mira a su alrededor) ¡Shhh! Si no quieres problemas con los cultistas, no hagas preguntas sobre ellos.}
{363}{}{¿Qué habías dicho sobre las pandillas que controlan el área?}
{364}{}{¿Así están las cosas? Entonces lo tendré en cuenta.}
{365}{}{}
{366}{}{Vamos, cuéntamelo, nadie nos está escuchando.}
{367}{}{(niega con la cabeza tristemente) Siempre están escuchándonos... Ya dije lo suficiente.}
{368}{}{Está bien.}
{369}{}{Patético.}
{370}{}{Puedo cuidarme las espaldas, y tú también. Dime qué tienen de malo esos tipos.}
{371}{}{Los Seguidores no son lo que aparentan. Parecen ser unos bonachones de buena voluntad, te hablan de los beneficios de la alfabetización, del 'Renacimiento' y cosas así. Pero dentro de la Catedral, se les cae la máscara. Son los únicos que saben qué ocurre en sus reuniones secretas.}
{372}{}{Te escucho.}
{373}{}{Sé que están acumulando conocimiento y tecnología de la preguerra. Dicen que es para el 'Renacimiento' del mundo. Pero no dejan que la gente común acceda a eso. Y teniendo en cuenta que Aaron llegó al poder a través de la violencia y la sangre, todo bajo el estandarte del Fuego Santo, no es difícil deducir cuáles son sus verdaderos objetivos.}
{374}{}{¿Buscan controlar la región entera?}
{375}{}{Ya conoces el viejo dicho: 'La guerra nunca cambia'. Bueno, es cierto. A nadie le importa la gente común. Aquellos que estaban en contra de la iglesia terminaron trabajando como esclavos o ardiendo en la hoguera. Y si te unes a los Seguidores, sólo saldrás de ahí metido en un ataúd.}
{376}{}{Eso suena siniestro...}
{377}{}{Por cierto, algunos se dieron cuenta de que entra más gente a la Catedral de la que sale, no sé por qué. Pero hay rumores de que el edificio es más grande de lo que parece y está conectada a algún tipo de estructura subterránea. Así están las cosas. Pero cierra la boca, porque la gente que habla demasiado sobre esto, desaparece.}
{378}{}{En ese caso, no volvamos a hablar de esto.}
{379}{}{No creo en tus historias, Bob. Adiós.}
{380}{}{Nos mintieron al decir que la Catedral era usada únicamente para fines pacíficos. Había un búnker lleno de armas nucleares debajo del edificio. Después de la explosión, muchos habitantes empezaron a hablar sobre como los cultistas los habían estado intimidando. No confío en ese culto. Y ahora nadie lo hace.}
{381}{}{Ya veo. Tengo unas preguntas más.}
{382}{}{Es una pena que no sepas todo lo que ocurrió. Adiós, Bob.}
