{100}{}{Ves a un jugador.}

{101}{}{Parece que esté jugador tiene un golpe de suerte.}
{102}{}{Ves a un cliente, está frenético gracias a su racha de victorias.}
{103}{}{Este jugador está aburrido, no está ganando, pero tampoco está perdiendo.}
{104}{}{Estás viendo a un cliente, le sale humo de las orejas debido a su racha de derrotas.}
{105}{}{Ves a un jugador, sus ojos están llenos de pánico. Lo ha perdido todo.}

{109}{}{¿Cómo entraste aquí con esa armadura?}

# Response
# - Fine
{110}{}{Este lugar es genial, ¿no?}
{111}{}{Estoy teniendo una racha, ¿y tú?}
{112}{}{Hoy es mi día de suerte.}
{113}{}{Esto es el mejor casino del yermo.}
{114}{}{Sé que trucos usar para ganar, confía en mí.}
{115}{}{¿Juegas? Es una locura.}
{116}{}{¡Chapas, bebé! ¡Chapas!}
{117}{}{No me mires, me traes mala suerte.}
{118}{}{¿Por qué me sigue pasando esto?}
{119}{}{Creo que ya agarré el truco.}
{120}{}{Hazte a un lado.}
{121}{}{No me tapes la vista.}
{122}{}{¡Hoy es el día en el que quebraré al banco!}
{123}{}{Aquí adentro me siento como una parte de la máquina.}
{124}{}{Hemos estado aquí un buen rato, ¿no?}
{125}{}{Si estás borracho, no apuestes todo.}
{126}{}{¿Tienes las agallas para apostar contra mí?}
{127}{}{Malditos turistas, están quebrados...}
{128}{}{Deja de distraerme, estoy jugando.}
{129}{}{No voy a darte de mi suerte, piérdete.}

# - bad
{150}{}{Este lugar apesta, no puedo ganar nada.}
{151}{}{Estoy peor que nunca. ¿Y tú?}
{152}{}{La suerte no está de mi lado.}
{153}{}{Esto no es un casino, es una estafa.}
{154}{}{Juro que si me quedo, jamás voy a ganar.}
{155}{}{¿Por qué sigo jugando? Es inútil.}
{156}{}{Oye, préstame unas chapas, ¿quieres?}
{157}{}{Si gano, te invito unos tragos.}
{158}{}{Ojalá que tengas más suerte que yo.}
{159}{}{Esta racha de mala suerte jamás acabará.}
{160}{}{Necesito ganar, en serio...}
{161}{}{Es sólo un juego, nada más...}
{162}{}{Estos dados están arreglados, lo juro.}
{163}{}{Tienen que estar haciendo trampa, es imposible que esto sea real.}
{164}{}{La suerte está en mi contra...}
{165}{}{Esté lugar está infestado con estafadores.}
{166}{}{Se me acabaron las fichas... de nuevo.}
{167}{}{La suerte es caprichosa.}
{168}{}{¡Me gané 60 chapas! Y luego... las perdí.}
{169}{}{Siento que mi vida entera depende de esto.}
{170}{}{Cuídate la espalda, están haciendo trampa.}
{171}{}{Las máquinas están arregladas, no hay duda.}

# Random remarks
# - Badly
{200}{}{¡Vamos, chingada madre!}
{201}{}{¿Por qué tengo tanta mala suerte en este juego?}
{202}{}{Hoy no es mi día de suerte.}
{203}{}{¡Este juego es una basura!}
{204}{}{Odio este maldito juego.}
{205}{}{¡Lo estoy perdiendo todo!}
{206}{}{Todo iba tan bien... ¿qué pasó?}
{207}{}{Una de dos, o gano o lo perderé todo.}
{208}{}{Si pierdo una vez más, dejaré este lugar hecho un desastre.}
{209}{}{No me iré hasta que gane algo.}
{210}{}{Dame un respiro...}
{211}{}{¡Ya casi estoy en la quiebra!}
{212}{}{Un poco más y estaré totalmente en la quiebra.}
{213}{}{Ya estoy cansado de perder.}
{214}{}{¿En serio ya se me acabaron las fichas?}
{215}{}{¡A la mierda todo!}
{216}{}{Si mi suerte no cambia, me voy de aquí.}
{217}{}{Mis bolsillos están vacíos...}
{218}{}{Sólo un poco más...}
{219}{}{¡No otra vez!}
{220}{}{Lo estoy perdiendo todo.}
{221}{}{¿Debería intentarlo de nuevo?}
{222}{}{¡No, no, no, basta!}
{223}{}{Ay. Eso es malo.}
{224}{}{¡Estaba tan cerca!}
{225}{}{¡Demonios!}
{226}{}{¿Cómo acabe así?}
{227}{}{¿Por qué siempre a mí?}
{228}{}{¿¡De nuevo!? ¿¡En serio!?}
{229}{}{No tengo nada de suerte...}
{230}{}{Necesito un trago fuerte.}
{231}{}{Hoy tengo todo en mi contra.}
{232}{}{¡Ya casi lo tenía!}
{233}{}{Sólo esperen, ganaré una fortuna.}
{234}{}{Genial, dejaron entrar a otro mendigo...}
{235}{}{Agh, necesito ir al baño.}
{236}{}{Quizás debería vender mi bazo para volver a jugar...}
{237}{}{No en esta vida.}
{238}{}{¡El universo se está riendo de mí!}
{239}{}{Hoy no es mi día.}
{240}{}{¡Vete a la mierda!}
{241}{}{¡No, otra vez!}

# - Fine
{300}{}{¡Sí! ¡Un premio!}
{301}{}{Vamos, no me falles ahora.}
{302}{}{Hoy me siento con suerte, sí señor.}
{303}{}{¡Este juego es genial!}
{304}{}{¡Me encanta esto!}
{305}{}{¿Es esto real, o estoy soñando?}
{306}{}{Genial, sigamos así.}
{307}{}{Hoy la voy a pasar en grande.}
{308}{}{¡Si sigo así, yo invito los tragos!}
{309}{}{¡Si estás en una racha, no debes parar!}
{310}{}{No perderé, de ninguna manera.}
{311}{}{Puedo oler esas chapas.}
{312}{}{¡Si sigo así voy a ser el más rico de la ciudad!}
{313}{}{Esto se está poniendo mejor.}
{314}{}{¡Chapas, chapas y más chapas!}
{315}{}{¡Sí!}
{316}{}{La suerte está de mi lado.}
{317}{}{Parece que estas chapas me pertenecen.}
{318}{}{Ojalá que siempre fuera así...}
{319}{}{¡Genial! ¡Gané otra vez!}
{320}{}{¡Que siga así, bebé!}
{321}{}{¡Es obvio que yo iba a ganar!}
{322}{}{¡Sigamos así!}
{323}{}{¡Esto es genial!}
{324}{}{¡Genial!}
{325}{}{¡Mesera, otro trago!}
{326}{}{Suerte, no me falles.}
{327}{}{¿Quién es el ganador? ¡Así es, yo!}
{328}{}{¡Jaja, soy imparable!}
{329}{}{Supongo que hoy dormiré como un rey.}

# - In front of the stage
{350}{}{Verónica tiene una voz hermosa.}
{351}{}{Es preciosa, ¿no crees?}
{352}{}{Le vendría bien ser un poco más alegre.}
{353}{}{Parece que pasó por un infierno antes de venir.}
{354}{}{Sus canciones son algo tristes, ¿no?}
{355}{}{¿De qué está cantando, siquiera?}
{356}{}{Quizás sea hora de cambiar las canciones.}
{357}{}{Creo que me relajaré para escucharla.}
{358}{}{Este es el único sitio con música en vivo.}
{359}{}{Este es el único lugar con una cantante.}
{360}{}{Me encanta el casino, solamente por los espectáculos.}
{361}{}{La ciudad no tiene ningún otro sitio con espectáculos en vivo.}
{362}{}{¡Mesero, otro cóctel!}
{363}{}{¿En dónde está mi trago, mesero?}
{364}{}{Mesero, tengo una orden.}
{365}{}{Parece que se me acaban las chapas...}
{366}{}{Esto es el mejor bar de la ciudad, no hay duda.}
{367}{}{Los filetes de brahmán son los mejores.}
{368}{}{Odio irme luego de ver espectáculos así.}
{369}{}{}
