{100}{}{Ves a la crupier de la ruleta.}
{101}{}{Ves a una chica de ojos atentos y conducta profesional.}
{102}{}{L-lo siento, no puedes sentarte aquí con ESO.}
{103}{}{Si no te vas, llamaré a los guardias.}

{200}{}{(Ves una mesa de ruleta con temática nuclear. La mesa de las apuestas está divida en casillas negras y rojas, dos de ellas están marcadas con un "0" y un "00" que sobresaltan con un dibujo de una nube atómica. El crupier toma una pelota amarilla, llamada una "bomba." La lanza hacia la ruleta bajo la intensa mirada de los jugadores.)}
{201}{}{No tengo ni la menor idea de cómo se juega esto.}
{202}{}{Probaré a jugar.}
{203}{}{Solo estoy mirando.}
{204}{}{Por supuesto, señor. Siéntese.}
{1204}{}{Por supuesto, señorita. Siéntese.}
{205}{}{Veamos, qué tenemos aquí...}

{210}{}{Pongan sus apuestas.}
{211}{}{He tenido suficiente.}
{212}{}{Apuesto 5 fichas al rojo.}
{213}{}{Apuesto 5 fichas al negros.}
{214}{}{Apuesto 5 fichas al cero.}
{215}{}{Se me acabaron las fichas. Volveré después.}

{220}{}{Se cierran las apuestas.}
{221}{}{No me defraudes, pequeña bombita.}
{222}{}{Veamos quién tiene suerte.}
{223}{}{¡Vamos, bebé!}
{224}{}{Sigamos.}
{225}{}{¡Aquí viene la bomba!}
{226}{}{Espera. Voy a doblar mi apuesta.}
{227}{}{Un momento. Quiero triplicar mi apuesta.}
{228}{}{Em, ¿señor?}
{1228}{}{Em, ¿señorita?}
{229}{}{Parece que se me acabaron las fichas. Bueno, sigan sin mí.}

{230}{}{Se cierran las apuestas.}
{231}{}{[Espera]}
{232}{}{La bomba cayó en el rojo. Perdiste.}
{233}{}{La bomba cayó en el negro. Perdiste.}
{234}{}{¡La bomba cayó en el cero! Perdiste.}
{235}{}{¡Bomba al doble cero! Todas las apuestas van al casino.}
{236}{}{Quiero apostar de nuevo.}
{237}{}{Suficiente por hoy.}
{238}{}{La bomba cayó en el rojo. Ganaste.}
{239}{}{La bomba cayó en el negro. Ganaste.}
{240}{}{Bomba al cero. ¡Ganaste! Tu paga es de 1 a 8.}
{241}{}{Genial, ¡sigamos así!}
{242}{}{He tenido suficiente. Tengo que tomar un respiro.}
