{100}{}{Ves a un guardia.}
{101}{}{Ves a un matón del casino, mantiene el orden.}
{102}{}{Ves a un matón del casino, está buscando ladrones.}
{103}{}{Ves a un matón del casino, vigila la puerta principal.}
{104}{}{Ves a un matón del casino, está vigilando a un par de clientes sospechosos.}
{105}{}{Ves a un matón del casino, está aburrido.}
{106}{}{Ves a un matón del casino, intenta hacerse el duro.}
{107}{}{Ves a un hombre con traje y un arma. Es un guardia, no hay dudas.}

{110}{}{Guarde el arma de inmediato.}
{111}{}{No me haga repetirlo, guarde el arma.}
{112}{}{Se lo advertí.}
{113}{}{Detrás de esa puerta están los cuartos de servicio, no puede entrar ahí.}
{114}{}{Oiga, bájese del escenario.}
{115}{}{Tiene que esconder eso, no permitimos llevar armas en el casino.}

#Trying to speak

{200}{}{No me pagan por hablar, lo siento.}
{201}{}{Habla con el gerente.}
{202}{}{No puedo hablar con los clientes.}
{203}{}{Al gerente no le gusta que molestemos a los clientes.}
{204}{}{Pásela bien, tenemos todo acomodado.}
{205}{}{Estará a salvo aquí dentro, no se preocupe.}
{206}{}{Aquí no hacemos nada raro, puede relajarse.}
{207}{}{No soportamos a ningún ladrón.}
{208}{}{Espero que esté disfrutando del casino.}
{209}{}{¿Ha probado nuestro tequila? Es todo un éxito.}
{210}{}{Pruebe el Cóctel Atómico - es realmente fuerte.}
{211}{}{El bar está por allá.}
{212}{}{Nuestro bar tiene disponible los mejores tragos.}
{213}{}{No nos gustan los malhechores... pero, digamos que depende.}
{214}{}{¿Está todo bien?}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}

{250}{}{No te me acerques, o tendremos problemas.}
{251}{}{Estás cavando tu propia tumba.}
{252}{}{Juega todo lo que quieras, pero no molestes a los guardias.}
{253}{}{Si nos causas problemas, te echamos a la calle. ¿Lo comprendes?}
{254}{}{Vete de una vez, pendejo.}
{255}{}{No estoy de adorno.}
{256}{}{Créeme, no quieres causarnos problemas.}
{257}{}{Con una reputación como la tuya, deberías salir corriendo de aquí.}
{258}{}{¿Te crees muy gallo, cierto?}
{259}{}{(el guardia te ignora)}

{280}{}{Em... debe dejar ese traje afuera.}  
{281}{}{No podemos dejarlo pasar con... No importa, pase.}  
{282}{}{No causará ningún problema, ¿cierto?}  
{283}{}{Pero, ¿cómo vas a jugar dentro de esa cosa?}  
{284}{}{No es nada personal, pero no nos gusta esa armadura.}  
{285}{}{¿Podría dejar eso en la puerta, por favor?}  
{286}{}{Eh, sí, claro... puede pasa, señor... ¿Señora?}  
{287}{}{Lo siento, pero podría dañar los muebles con esa cosa. Por favor, váyase.}  
{288}{}{Por favor, no entre aquí con... lo que sea que sea eso.}  
{289}{}{Se ve muy... intimidante, con esa armadura.}  

{290}{}{Guarda el arma, ahora.}  
{291}{}{Te sugiero que enfundes el arma, de inmediato.}  
{292}{}{No permitimos las armas aquí dentro.}  
{293}{}{Si buscas pelear, Hazlo afuera.}  
{294}{}{No estás en un lugar cualquiera, guarda el arma.}  
{295}{}{¿Me estás amenazando?}  
{296}{}{El casino no admite armas, punto.}  
{297}{}{Oye, guarda eso, no queremos problemas.}  
{298}{}{Enfunda el arma y nadie saldrá herido.}  
{299}{}{No queremos problemas, ni se te ocurra amenazar a alguien.}  

