{100}{}{Ves a un botones.}
{101}{}{Ves a un joven muy servicial con una mirada congraciadora.}
{102}{}{N-no te vas a quedar aquí, ¿verdad?}
{103}{}{Lo siento amiguito, pero no tengo permitido ayudar a los pendejos como tú.}
{1103}{}{Lo siento, pero no tengo permitido ayudar a una perra como tú.}

{200}{}{¿En qué puedo servirle, señor?}
{1200}{}{¿La ayudo en algo, señorita?}
{201}{}{¿Quién eres?}
{202}{}{Soy un botones. Me encargo de tareas menores.}
{203}{}{Ya veo.}
{204}{}{¿Has mejorado? Yo sí... Jeje.}

{210}{}{Buenas noches, señor.}
{1210}{}{Buenas noches, señorita.}
{211}{}{Buenos días, señor.}
{1211}{}{Buenos días, señorita.}
{212}{}{Buenas tardes, señor.}
{1212}{}{Buenas tardes, señorita.}
{213}{}{Buenas noches, señor.}
{1213}{}{Buenas noches, señorita.}
{214}{}{Mis respetos, señor.}
{1214}{}{Mis respetos, señorita.}
{218}{}{Ya veo.}
{219}{}{Adiós.}

{220}{}{¿Qué es este lugar?}
{221}{}{Esto es un casino, y tenemos un pequeño hotel en el segundo piso. Aquí puede relajarse y apostar.}
{222}{}{¿Puedes recordarme qué es lo que haces?}
{223}{}{Me encargo de algunos recados, señor. Soy un botones.}
{1223}{}{Me encargo de algunos recados, señorita. Soy un botones.}
{224}{}{¿Qué haces aquí?}
{225}{}{¿Así que esto es un hotel?}
{226}{}{Deseo una habitación.}
{227}{}{Sólo tenemos una habitación disponible. Serán }
{228}{}{ chapas por cada noche.}
{229}{}{No, mejor no.}
{1229}{}{No, mejor no.}
{230}{}{Qué mala suerte, no tengo chapas.}
{231}{}{Me parece bien. Aquí tienes.}
{232}{}{Has tomado un buen descanso, te sientes con energías.}

# Luxury furnishings
{250}{}{Me estoy quedando en la suite. ¿Podría encargarte unos muebles?}
{1250}{}{Me estoy quedando en la suite. ¿Podría encargarte unos muebles?}
{251}{}{Por supuesto, señor. ¿Qué necesita?}
{1251}{}{Por supuesto, señorita. ¿Qué necesita?}
{252}{}{Pensándolo bien, ya hay mucho desorden ahí adentro.}
{253}{}{Un inodoro. [5 chapas]}
{254}{}{Algunas estanterías para guardar cosas. [20 chapas]}
{255}{}{Un armario espacioso. [50 chapas]}
{256}{}{Un refrigerador. [50 chapas]}
{257}{}{}
{258}{}{Ajá. Las chapas.}
{259}{}{Sí, sí, claro...}
{260}{}{Está hecho, señor.}
{1260}{}{Está hecho, señorita.}
{261}{}{Genial.}
{262}{}{Hmm. No tienen competencia, es de esperarse que el servicio sea tan malo.}

#Improving skill
{300}{}{Cuéntame, ¿ustedes no hacen trampa en el casino, verdad?}
{301}{}{Eh... Sí, supongo.}
{302}{}{No pareces estar convencido, ¿qué pasa?}
{303}{}{Pues, depende de tu suerte. Y, generalmente, es mucho mejor para el casino que para el jugador. Pero eso no quiere decir que no puedas ganar y hacerte rico.}
{304}{}{¿Me dirás cómo hacerlo? Tienes que conocerte un montón de trucos.}
{305}{}{No, claro que no. (mira al guardia y baja la voz) Al jefe no le gustaría eso.}
{306}{}{Nadie tiene que saberlo. (muéstrale algunas chapas para tentarlo)}
{307}{}{Entonces olvídalo.}
{308}{}{Lo que sea por los clientes. Te cobraré 300 chapas por una... clase, sí. "Cómo incrementar tus posibilidades en un 5% y por qué eso importa." Algo así.}
{309}{}{Puedo ganar esas chapas de vuelta si funcionan tus trucos. ¿Cuándo empezamos?}
{310}{}{No puedo permitirme eso. Nos vemos.}
{311}{}{Nos vemos en la mesa de billar del segundo piso. Y... no olvides traer las chapas.}
{312}{}{Claro.}

{320}{}{Estoy listo, ¿y tú?}
{321}{}{Traje las chapas, ten. }
{322}{}{Espérame, tengo que ir a buscar el dinero.}
{323}{}{Gracias. (mira a su alrededor mientras esconde las chapas) Empecemos con las reglas...}
{324}{}{[Seguir]}
{325}{}{...Y jamás dividas un cinco, porque la suma será de diez.}
{326}{}{Puta madre, esto no es nada fácil. Ahora sé qué debo evitar hacer.}
{327}{}{Eso es todo lo que sé. Pero ese 5% de probabilidad te ayudará. Bien, tengo que irme, o el jefe sospechará.}
{328}{}{Gracias por los consejos, amigo mío.}
{329}{}{Piérdete, ya no te necesito.}
