{100}{}{Ves a un hombre corpulento.}
{101}{}{Ves a uno de los hombres de Don Diego.}

{110}{}{Mis respetos. ¿Cómo está Don Diego?}
{111}{}{No sé como puede llevarse también con el jefe.}
{112}{}{¿Puedo ayudarle en algo?}
{113}{}{Espero pueda darle mi más profundo respeto a Don Diego.}
{114}{}{¿Le podrías decir al jefe que me de un ascenso?}

{115}{}{Mis respetos.}
{116}{}{¿Cómo estás?}
{117}{}{Vuelve al casino.}
{118}{}{Al jefe no le gustará que andes por aquí..}
{119}{}{Mi trabajo es mantener las cosas en orden.}

{120}{}{Es mejor que te vayas de aquí.}
{121}{}{Esto es un área privada, ¿qué estás haciendo aquí?}
{122}{}{¿Tienes algo que hablar con el jefe? Entonces ve a verlo.}
{123}{}{Al jefe no le gustará que hable contigo.}
{124}{}{Si me entero de que andas espiando...}

{125}{}{¿Qué estás haciendo aquí?}
{126}{}{¿Acaso andas espiándonos?}
{127}{}{Oye, vuelve al casino, ahora.}
{128}{}{Esto es un área privada.}
{129}{}{No deberías estar aquí.}
