{100}{}{Ves al pregonero del casino.}
{101}{}{Ves a un hombre que molesta a los transeúntes para que entren en el casino.}
{102}{}{Alguien mató al pregonero en las afueras del casino. Parece que la muerte de Don Diego les dio libertad a los matones callejeros.}
{103}{}{Un momento, ¿a ti no te andan buscando los guardias? Será mejor que no entres en el casino.}

{110}{}{¿Buscas ganar unas chapas? ¡Pase al casino!}  
{111}{}{¿Por qué pasarte la tarde buscando chapas en la basura cuando te las puedes ganar sentado?}  
{112}{}{¡El único e inimitable casino de Arizona te espera!}  
{113}{}{¡Aquí en Fénix te puedes volver rico! ¡Pasa y mira cómo te llegan las chapas!}  
{114}{}{¡Chapas y uranio! ¡La pareja perfecta para la fortuna!}  
{115}{}{¡Nuestro casino es donde las señales de radiación llevan a las chapas!}  
{116}{}{¡Pasen, pasen! ¡El Atomic Rush atrae a los valientes!}  
{117}{}{¡No te pierdas la oportunidad de ganar en grande en nuestro casino!}  
{118}{}{¡Pasen, pasen! ¡La fortuna los espera adentro!}  
{119}{}{¡Todos son bienvenidos aquí - humanos, mutantes y hasta bebés!}  

