{100}{}{Ves a un fugitivo.}
{101}{}{Ves a un hombre muy preocupado.}
{102}{}{Nos vamos de aquí, jamás volveremos a una ciudad tan violenta como Fénix.}

{110}{}{Tenemos que salir de aquí.} 
{111}{}{No hay de otra.} 
{112}{}{Irnos al sur sería lo mejor.} 
{113}{}{¿A dónde se fueron todos?} 
{114}{}{No podremos cruzar el desierto.} 
{115}{}{Si cruzamos el desierto, moriremos todos.} 
{116}{}{Pero, si no vamos al sur, ¿entonces a dónde?} 
{117}{}{Podríamos ir a las montañas en el oeste.} 
{118}{}{He oído rumores sobre un refugio, pero quién sabe en dónde está.} 
{119}{}{Tenemos que irnos.}

{200}{}{(Ves a un grupo de personas inmersas en una discusión)} 
{201}{}{¿Qué está pasando?} 
{202}{}{(Todos se dan la vuelta para mirarte; sus ojos están repletos de miedo y tensión) Ya lo sabes. Esto es un desastre... Nuestra ciudad fue destruida, no sólo ella, sino también su espíritu.} 
{203}{}{¿Te refieres a la explosión de la catedral?} 
{204}{}{Obvio que sí. ¡La mitad de la ciudad dependía de ella! Nos dejó sin nada, ahora debemos irnos de aquí y encontrar un lugar mejor.} 
{205}{}{Buena idea, espero que encuentren un lugar mejor.}
{206}{}{Más les vale que se cuiden la espalda.}
{207}{}{¿Acaso eran parte del culto? No tiene sentido que salgan corriendo sólo por una explosión.} 
{208}{}{(Intercambian miradas incómodas entre sí) Ya no importa... Nuestros familiares eran miembros del culto, así que teníamos más privilegios. Los demás nos guardaban rencor por eso. Y ahora el culto no está, así que estamos en peligro. Todos están buscando a gente relacionada a los Seguidores. Si nos quedamos, nos van a linchar.} 
{209}{}{Entonces no tienen otra opción. Buena suerte.} 
{210}{}{Sáquense de Fénix, imbéciles.}
