{100}{}{Ves a un niño.}
{101}{}{Ves a un niño normal, no lleva más que harapos encima.}
{102}{}{Hm, tengo que irme.}

{200}{}{¡Disculpe, señor!}
{1200}{}{¡Disculpe, señora!}
{201}{}{No ayudo a los mendigos. Piérdete.}
{202}{}{¿Qué necesitas, jovencito?}
{203}{}{Se me pidió que te trajera esto. (te entrega una nota)}
{204}{}{Si esto es algún truco, lo pagarás muy caro.}
{205}{}{Gracias, niño. Dámelo.}
{206}{}{Dámelo.}
{207}{}{(El niño huye momentos después de entregarte la nota. Dice esto: "Los cultistas obtuvieron su merecido. Detén tu investigación o correrás la misma suerte.")}
{208}{}{Si ese niño escribió esto, entonces todo lo que me queda por hacer es temblar de miedo.}
{209}{}{Parece que algo peor que un bandido está detrás de los ataques.}
