{100}{}{Ves a un operador de radio.}
{101}{}{Ves a uno de los Seguidores.}
{102}{}{¿Qué pasó? ¿Te perdiste? La salida está ahí, los forasteros no tienen permitida la entrada.}
{1102}{}{¿Qué pasó? ¿Te perdiste? La salida está ahí, los forasteros no tienen permitida la entrada.}
{103}{}{Saludos, hermano. Que el Fuego Santo te ilumine.}
{1103}{}{Saludos, hermana. Que el Fuego Santo te ilumine.}
{104}{}{Santo Átomo... ¿qué me está pasando?}
{105}{}{Ya veo... Fuego Santo...}
{106}{}{Ya he tenido suficiente... No me tientes más, por favor...}
