{100}{}{Ves a un delegado.}
{101}{}{Ves a alguien que no parece ser del culto. Contrasta mucho con la Catedral, pues parece un salvaje.}

{200}{}{Tú. Tráeme fruta. Tengo hambre.}
{201}{}{¿Por qué debería hacerlo?}
{202}{}{Ah, ¿no estás con los Seguidores? Entonces vete, no me importas. Sólo la Iglesia del Fuego Santo merece mi respeto. Son el futuro de éstas tierras, los demás son todos basura.}
{203}{}{¿Quién eres?}
{204}{}{Soy un anciano de una tribu al oeste. Formaremos una alianza con los Seguidores porque queremos ser parte de su gran nación.}
{205}{}{¿Por qué querría la iglesia aliarse con una tribu?}
{206}{}{A la iglesia sí le importa la gente del yermo. ¿Es tu primera vez en la ciudad? Mira cuánto bien ha traído la Iglesia del Fuego Santo a este lugar. Los Seguidores conquistaron al Sol, y lo metieron en unos palos y unas lámparas. ¿No es eso una señal de su grandeza y su poder divino?}
{207}{}{¿Entiendes de qué se tratan sus enseñanzas?}
{208}{}{No mucho, si te soy sincero. Pero los Seguidores prometieron que nos enseñarían. Abrirán un templo en nuestro valle, nos enseñarán el idioma de los Antiguos y hasta cómo podemos conquistar al Sol. Es lo que nos prometen.}
{209}{}{¿Y qué les darán ustedes a cambio?}
{210}{}{Nos volveremos sus sirvientes, ¡será un honor para la tribu! Trabajaremos por el bien de la iglesia, y la iglesia nos ayudará a nosotros. Así no sólo nos salvaremos, sino que también seremos mejores, más inteligentes y más fuertes.}
{211}{}{Ya veo. Adiós.}
{212}{}{¿Tú otra vez? Déjame en paz, sólo hablaré con Aaron.}
