{100}{}{Ves al Hermano Francis.}
{101}{}{Estás viendo a uno de los Seguidores. Está ocupado, pues copia dibujos antiguos.}
{102}{}{¿Cómo podré copiar los dibujos con esta oscuridad?}

{200}{}{Saludos, extraño. ¿Puedo ayudarte en algo?}
{1200}{}{Saludos, extraña. ¿Puedo ayudarte en algo?}
{201}{}{Puedes empezar hablándome de este lugar.}
{202}{}{¿Ayudarme? Hmph, lo dudo mucho.}
{203}{}{Por favor, vete. Este no es lugar para ser grosero.}
{204}{}{Lo siento, empezamos mal. ¿Podrías decirme qué es este lugar?}
{205}{}{Me voy. Por ahora, tal vez.}

{210}{}{¿Qué quiere, señor?}
{1210}{}{¿Qué quiere, señorita?}
{211}{}{¿En qué puedo ayudarle, acólito?}
{1211}{}{¿En qué puedo ayudarle, acólita?}
{212}{}{Adiós.}
{213}{}{Parece que sabes mucho, me gustaría preguntarte otra cosa.}

{220}{}{Háblame de ti.}
{221}{}{Me llamo Francis, soy el bibliotecario.}
{222}{}{¿Cómo te convertiste en un Seguidor?}
{223}{}{He sido un Seguidor desde que era un adolescente. En ese entonces, la iglesia era poco conocida y no se involucraba en el destino de la ciudad.}
{224}{}{¿Crees ciegamente en los dogmas de tu iglesia?}
{225}{}{"Nisi videro, non credam. Non credam, nisi videro." No tiene sentido discutir eso.}
{226}{}{¿Qué es exactamente lo que haces como bibliotecario?}
{227}{}{Me encargo de restaurar libros viejos, de copiar textos antiguos y de hacer listas. Por ejemplo, ahora estoy ocupado con este maravilloso dibujo.}
{228}{}{¿Por qué copias los textos antiguos?}
{229}{}{Debemos preservar el conocimiento de nuestros ancestros para la posteridad, pues eran infinitamente más sabios. Pero el papel de los textos viejos ya casi se ha deteriorado por completo; tales textos no durarán por mucho tiempo más, especialmente al aire libre. Por lo tanto, debemos restaurar, copiar y preservar los escritos antiguos.}
{230}{}{Pero si los preservas, ya no se podrá acceder a ellos, ¿no?}
{231}{}{Correcto. Y es por eso que creamos copias que guardamos en nuestra biblioteca. Es cierto que en cuanto a calidad, suelen ser inferiores al original, pero es una cuestión difícil.}

{240}{}{¿Qué es este lugar?}
{241}{}{Esto es una biblioteca, un lugar en el que se conserva el conocimiento a través del papel, en su mayoría viene de la preguerra. Sé que puede parecer raro, pero difícilmente quedan bibliotecas en el mundo. Eso sólo hace a nuestro trabajo más importante aún.}
{242}{}{¿De dónde vinieron todos estos libros?}
{243}{}{De todos lados. Compramos todos los libros y manuscritos de la preguerra. Heredamos parte de esta colección de nuestros ancestros, quienes los enterraron en el desierto.}
{244}{}{Pero, ¿para qué son estos libros viejos?}
{245}{}{Contienen el conocimiento de nuestros ancestros. Para nuestra desgracia, somos incapaces de entender la mayoría de ellos. Pero en un punto llegaría el día y estos libros nos revelarán sus secretos.}
{246}{}{¿Crees que este conocimiento sea seguro? Nuestros ancestros se destruyeron a sí mismos - junto al mundo - con él.}
{247}{}{Eso es cierto, pero las personas aprenden de los errores... del pasado. Además, somos cuidadosos al compartir este conocimiento sólo con los que sean dignos de él.}
{248}{}{¿Los enterraron en el desierto? ¿A qué te refieres?}
{249}{}{Después de la Gran Guerra, los científicos fueron rehuidos, se les culpaba por haber causado el Apocalipsis. La gente intentó quemar sus libros en hogueras de gran tamaño - o al menos, eso dicen las crónicas. Nuestros ancestros, los científicos, salvaron lo que pudieron. Pues sellaron los libros dentro de barriles y los enterraron en el desierto. Todavía hay muchos allá afuera, esperando ser encontrados.}

{250}{}{Acerca de ese dibujo en el que estás trabajando... Dime, ¿qué significa "bloque transformador 6-B"?}
{251}{}{Eso es... bueno... el título del documento, eso está claro.}
{252}{}{Sí, lo entiendo. ¿Pero QUE significa?}
{253}{}{Es el *nombre* del dibujo que estás mirando. ¿Qué significa tu nombre?}
{254}{}{Bueno, tiene sentido lo que dices.}
{255}{}{Por supuesto.}
{256}{}{Sí, creo que esta conversación no llevará a ningún lado.}
{257}{}{Mi nombre no tiene nada que ver en esto. ¿Qué simboliza el dibujo?}
{258}{}{Simboliza... el... (se da vuelta para mirar el dibujo y leer la inscripción) bloque transformador 6-B.}
{259}{}{Ya no tengo más dudas. Gracias, Hermano Francis.}

{260}{}{Sí que tienes muchos libros. ¿Me permites estudiar algunos?}
{261}{}{Lo siento, pero cuando se trata de dar acceso a nuestra biblioteca, somos muy cuidadosos. Estos libros son muy valiosos, y para una persona común, su conocimiento puede ser peligroso.}
{262}{}{De acuerdo, olvídalo.}
{263}{}{Ustedes son un montón de cerebritos. Adiós.}
{264}{}{Francis, soy tu hermano, ya soy parte de la iglesia. No me dirás que no, ¿verdad?}
{1264}{}{Francis, soy tu hermana, ya soy parte de la iglesia. No me dirás que no, ¿verdad?}
{265}{}{Ah, no sabía que ya te encontrabas entre los acólitos. Por supuesto, estudia el libro que gustes. Pero cuidado, son muy frágiles.}
{266}{}{Gracias, Hermano Francis. Seré muy cuidadoso.}
{1266}{}{Gracias, Hermano Francis. Seré muy cuidadosa.}
{267}{}{Si alguno se rompe, no me eches la culpa.}
{268}{}{Podría donar unas 300 chapas a tu biblioteca.}
{269}{}{Eso cambia las cosas. Puedes estudiar nuestros libros, pero ten cuidado, son muy frágiles.}
{270}{}{}
{271}{}{Eso cambia las cosas.}
{272}{}{No tengo tantas chapas, volveré luego.}
{273}{}{Después de haberte ayudado no me confías unos libros. ¿En serio?}
{274}{}{Ah, claro, tienes razón. Puedes estudiar los libros. Pero cuidado, son muy frágiles.}

{280}{}{Hermano Francis, ¿tienes la agenda de las misiones de los acólitos?}
{281}{}{Sí. Pero debes entender que no te los puedo mostrar. Sólo algunos tienen acceso a la agenda. ¿Por qué lo preguntas?}
{282}{}{No puedo decírtelo. Pero, ¿al menos puedes decirme quién la ha examinado últimamente?}
{283}{}{Hmm. Rara vez se utilizan estos documentos. Creo que podría alinear esas fechas con los sellos de los visitantes. Cuéntame las fechas que te hace falta saber.}
{284}{}{Me interesan estos días...}
{285}{}{...Bueno, parece ser que en estas fechas, únicamente el Hermano Matthias examinó la agenda.}
{286}{}{¿En dónde puedo encontrarlo?}
{287}{}{Su habitación está en este mismo piso, al final del pasillo. Pero no hagas ruido, al Hermano Matthias le molesta mucho que lo interrumpan bruscamente mientras está meditando.}
{288}{}{Gracias, Hermano Francis, me has ayudado mucho.}
{289}{}{Ya veo. Entonces ya me voy.}


#Books
{300}{}{Habías dicho que compran libros. Yo viajo mucho...}
{301}{}{Por supuesto. Si te encuentras con cualquier libro antiguo, por favor, tráemelo. La Iglesia te pagará generosamente por tus esfuerzos.}
{302}{}{Lo tendré en cuenta.}
{303}{}{Necesitas más libros, ¿no?}
{304}{}{Tengo algunos libros de la preguerra.}
{305}{}{¡Ah! Excelente. ¿Cuántos libros tienes?}
{306}{}{Puede que esto no sea lo que estás buscando. Disculpa las molestias.}
{307}{}{A lo que me refería es que voy a buscar libros. Adiós.}
{308}{}{Te daré todos los libros que tengo.}
{309}{}{Sólo un libro.}
{310}{}{Dos libros.}
{311}{}{Tres libros.}
{312}{}{Esto le vendrá de maravilla a nuestra colección. Estás contribuyendo al progreso de toda la humanidad. Muchísimas gracias.}
{313}{}{Te los daré gratis, es una donación para la iglesia.}
{314}{}{Tu generosidad no tiene límite alguno. Gracias.}
{315}{}{Me gustaría preguntarte otra cosa.}
{316}{}{Muchas gracias. Adiós.}
{317}{}{Quiero chapas a cambio de esto.}
{318}{}{Por supuesto, es justo. Puedo ofrecerte }
{319}{}{ chapas.}
{320}{}{¿Tu biblioteca necesita algún libro en específico?}
{321}{}{Oh, sí. Sabemos de algunos libros que nos gustaría tener en nuestra colección. Sin embargo, sus dueños... no quieren compartir su conocimiento. Quizás tú seas capaz de hacerlos cambiar de opinión.}
{322}{}{Cuéntame más. ¿Quién se interpone en el camino del progreso?}
{323}{}{Puedo hacerlos cambiar de opinión muy fácilmente, si entiendes lo que quiero decir.}
{324}{}{Bueno, se me ha informado que un libro antiguo, incluso sagrado, se encuentra en el pueblo de San Brahmán. Y aparenta ser mucho más viejo que la Gran Guerra. ¿Puedes imaginar eso? Desafortunadamente, los lugareños no pueden leerlo y ni siquiera tenemos permitido verlo, debido a la guerra reciente.}
{325}{}{¿Me estás diciendo que lo robe?}
{326}{}{Supongo que eso suena un poco mal, pero no me malentiendas. Los salvajes no entienden el verdadero significado de este libro y no se les puede confiar su preservación. Si estuviera en nuestras manos, esa reliquia le serviría a un propósito mucho más grande. ¿Nos traerás el libro? Te aseguro de que pagaré un buen monto a cambio de él.}
{327}{}{No lo creo, no me gustaría ser parte del saqueo de un lugar 'sagrado'.}
{328}{}{Está bien, lo entiendo. En ese caso, olvida todo lo que dije.}
{329}{}{Claro.}
{330}{}{Un libro así de viejo y sagrado debería estar en esta biblioteca. Te lo traeré.}
{331}{}{Maravilloso. Estaré ansioso de tenerlo aquí.}
{332}{}{Tengo el libro sagrado.}
{333}{}{No es posible... ¡Estas páginas son hermosas! ¡Dios, incluso contienen latín! Tiemblo de la emoción con apenas verlo...}
{334}{}{Parece que es muy importante para la iglesia, puedes quedártelo, no cobraré nada. Quiero hacer una buena acción.}
{335}{}{No olvidaré tu generosidad. Voy a orar por ti, hermano mío. El mundo necesita más gente como tú.}
{1335}{}{No olvidaré tu generosidad. Voy a orar por ti, hermana mía. El mundo necesita más gente como tú.}
{336}{}{Buena suerte, Hermano Francis.}
{337}{}{No fue nada fácil conseguir este libro, quiero 300 chapas a cambio.}
{338}{}{Tienes razón, te daré las chapas. Es un pequeño precio a pagar por una reliquia así.}
{339}{}{Buena suerte, Hermano Francis.}
{340}{}{Un momento, hermano. Creo que deberías hablar con el mismísimo Aaron. Le haré saber acerca de la ayuda que has prestado a nuestra iglesia. Y si te hace falta mi recomendación, puedes contar con ella.}
{1340}{}{Un momento, hermana. Creo que deberías hablar con el mismísimo Aaron. Le haré saber acerca de la ayuda que has prestado a nuestra iglesia. Y si te hace falta mi recomendación, puedes contar con ella.}
{341}{}{De acuerdo.}
{342}{}{Nos vemos luego.}
{343}{}{Sabes... Creo que ya tengo este libro.}
