{100}{}{Ves a un Seguidor del Fuego.}
{101}{}{Ves a uno de los Seguidores. Se encuentra en su propio mundo debido a su frenética oración.}

{200}{}{...El cielo se convertirá en tierra... El fuego es Dios... ...que se apiada de Él... Fuego... Los infieles caerán... El sol está en nuestras manos... Flores...}
{201}{}{Oye, ¿de qué estás hablando?}
{202}{}{...el Fuego es poder...}
{203}{}{Tu fuego no es más que una idea inventada.}
{204}{}{(al ser distraído de su oración, te observa con la mirada vacía) El Fuego... es... la verdad...}
{205}{}{Oh, bueno, eso lo explica todo. Adiós.}
{206}{}{Eh, es mejor que no moleste...}
