{100}{}{Ves a un Seguidor del Fuego.}
{101}{}{Ves a uno de los Seguidores. Está hablando sólo, murmurando sus plegarias, o alguna otra cosa.}
{102}{}{Su Majestad Aaron le está esperando.}
{103}{}{El Señor de Fénix te está esperando.}

{110}{}{*Murmullo*}
{111}{}{¿Estás preparado para aceptar a la iglesia del Fuego Santo?}
{112}{}{Aquellos quienes ignoren al Fuego y a su llamado arderán a su merced.}
{113}{}{El Fuego Santo quemó a nuestros ancestros por sus pecados.}
{114}{}{Tener fe en el Fuego es lo único que salvará tu cuerpo y alma.}
{115}{}{Que el Fuego te bendiga, hermano.}
{116}{}{El Fuego Santo abrió tus ojos, ¿verdad?}
{117}{}{Pronto, la luz del Fuego Santo iluminará a toda Sonora.}
{118}{}{Todos venimos del mismo Fuego.}
{119}{}{Ser iluminado por el Fuego es difundir su luz a los demás.}

{1114}{}{Tener fe en el Fuego es lo único que salvará tu cuerpo y alma.}
{1115}{}{Saludos, hermana.}
{1116}{}{¿Será que el Fuego Santo también te abrió los ojos?}
{1117}{}{Pronto, la luz del Fuego Santo iluminará a toda Sonora.}
{1118}{}{Todos nacimos desde el mismo Fuego.}
{1119}{}{Ser iluminado por el Fuego es difundir su luz a los demás.}
