{100}{}{Ves a un Seguidor del Fuego.}
{101}{}{Ves a uno de los Seguidores. Habla consigo mismo, debe ser una oración o alguna tontería.}

{200}{}{Saludos, forastero.}
{1200}{}{Saludos, forastera.}
{201}{}{Bienvenido seas, hermano.}
{1201}{}{Bienvenida seas, hermana.}
{202}{}{Adiós.}
{203}{}{Que el Fuego Santo te ilumine.}
{204}{}{Eh, sí, claro.}

{210}{}{¿Cómo te convertiste en un Seguidor?}
{211}{}{Era igual que cualquier otra alimaña del yermo, perdido y sin propósito. Sólo pensaba en sobrevivir y no sabía del Fuego Santo. Toqué fondo y me discriminaban, lo único que quería, era el consuelo. Un día, me topé con este templo. Aquí encontré un hogar y un nuevo propósito en mi vida.}
{212}{}{¿Qué te ha dado tu fe?}
{213}{}{A nuestra Iglesia sí les importan sus Seguidores. Recibimos atención médica, educación y además protección de nuestros enemigos.}
{214}{}{Pero, ¿y los demás? Ya sabes, los que no pertenezcan a la iglesia.}
{215}{}{Nuestros recursos son limitados a la hora de tratar con ellos, así que debemos tener cuidado con quienes consideramos amigos.}
{216}{}{¿Cuál es tu trabajo en la Catedral?}
{217}{}{Estudio nuestra doctrina y le rezo al Fuego Santo. Un día estaré listo, y me espera un viaje a otras tierras. Voy a predicar las enseñanzas del Fuego Santo para que nuestra fe se fortalezca en otros lados, por lejanos y perdidos que estén.}
{218}{}{¿Quién es el que está a cargo por aquí?}
{219}{}{Aquí todos somos hermanos. Pero nuestro guía es Aaron, el Señor de Fénix. Lo puedes encontrar en su trono, en el último piso de la Catedral.}
{220}{}{He oído un rumor de que un monje infiltró a los Cardenales Rojos. ¿Sabes algo de eso?}
{221}{}{Es posible, supongo. Estamos dispuestos a llevar la palabra del Fuego Santo aún a las almas más depravadas.}
{222}{}{Alguna idea de quién podría ser ese... ¿agente?}
{223}{}{¿Qué? ¿Acaso crees que te daría su nombre? Ni siquiera sé quién es, y no te diría si lo supiera. Pero todas nuestras comunicaciones con los "agentes" las guarda el operador de la radio. Sólo unos pocos tienen permitido el acceso a tal información. ¿Eres uno de ellos?}
{224}{}{Ya veo. Gracias.}
{225}{}{Escúchame, Orris ya casi ha descubierto quién es. Si no me ayudas, tu hermano está muerto.}
{226}{}{No quiero meterme en esto. Lo siento.}
{227}{}{De acuerdo...}
{228}{}{¿Tan mal está la situación? Entonces avísale a Murphy que Orris lo descubrirá. Él sabrá que hacer.}
{229}{}{Así que es Murphy. Gracias, era todo lo que necesitaba saber.}
