{100}{}{Ves a un matón.}
{101}{}{Ves a un matón determinado.}
{102}{}{¡Basta! ¡Ya nos vamos! ¡Todo está bien, que no cunda el pánico!}

{110}{}{¿A dónde crees que vas? Este es nuestro territorio.}
{111}{}{Hablas demasiado. Pruébame que es tu territorio, pedazo de mierda.}
{112}{}{Está bien, lo siento...}
{113}{}{Por favor, vete, los lugareños no quieren problemas...}
{114}{}{¡Entonces les daremos problemas! ¿Entendido? ¡Ahora lárgate mientras puedas, pendejo!}
{115}{}{Estás en territorio de los Cardenales. A ellos no les gusta la competencia. Piérdete.}
{116}{}{Hace tiempo que los Cardenales dejaron de ser relevantes. ¿Acaso los ves por algún lado?}
{117}{}{Eso no importa. Yo estoy al mando aquí. Piérdete.}
{118}{}{Los Cardenales mandan por acá. Lárgate.}
{119}{}{¡Grrr! (aprieta los dientes, levanta los puños y retrocede hacia la salida)}
{120}{}{Lárgate y no vuelvas nunca, imbécil...}
{121}{}{Chicos, les daré 100 chapas si nos dejan en paz. ¿Vale?}
{122}{}{¿Ves? Solo necesitabas pagarnos. Nos vemos el otro mes, pendejos.}
{123}{}{Sí, eh, adiós...}
