{100}{}{Ves a un refugiado de Flagstaff.}
{101}{}{Ves a una persona con la ropa polvorienta. Parece que viajó mucho para llegar aquí.}
{102}{}{*Solloza}
{103}{}{Gracias, me salvaste la vida.}
{104}{}{Aléjate de mi, maldito pervertido.}
{1104}{}{Aléjate de mi, maldita pervertida.}
{105}{}{¿¡Qué está pasando aquí!?}

{110}{}{¿Por qué nos haces esto?}
{111}{}{Nos conocemos desde niños.}
{112}{}{Me llegarán chapas, te lo prometo, sólo dame más tiempo.}
{113}{}{Sé cómo puedo pagar la renta.}
{114}{}{No puedo pagarte la renta, pero te prometo que no seguirá así.}
{115}{}{Dame una oportunidad y ganaré algunas chapas.}
{116}{}{Escúchame, encontraré un trabajo.}
{117}{}{Por favor, no quiero pelear contigo.}
{118}{}{Así que algunas personas siguen guardando rencor, ¿no?}
{119}{}{Déjame quedarme una última noche.}

{200}{}{¿...Qué te pasa? Antes fuiste amable con nosotros. Y ahora nos tratas como basura.}
{201}{}{¿Qué está pasando aquí?}
{202}{}{Este bastardo quiere desalojarnos, a sus viejos amigos. No tenemos dinero para pagar la renta, pero lo podemos resolver, sólo tenemos que encontrar trabajo.}
{203}{}{¿Entonces no son de aquí?}
{204}{}{Sí, somos de aquí, pero hemos estado trabajando en Flagstaff los últimos años. Como cerraron la mina de uranio, muchos perdieron sus trabajos, y ahí empezaron las revueltas. Tuvimos que regresar, el viaje de vuelta fue muy duro, y se nos acabaron las chapas.}
{205}{}{Todo llega a su fin.}
{206}{}{Qué triste historia.}

{210}{}{¿Puedes darnos diez chapas? Te las devolveré apenas pueda, lo prometo.}
{211}{}{Lo siento, pero tampoco tengo chapas.}
{212}{}{Claro, era de esperarse, todos tienen sus problemas. Está bien, buscaré cómo resolverlo.}
{213}{}{Adiós.}
{214}{}{Parece que te hacen mucha falta. Tengo algunas, toma.}
{215}{}{Claro, aquí tienes.}
{216}{}{¿En serio? (las agarra con rapidez) Gracias, ¡gracias! ¿Cómo te llamas?}
{217}{}{No importa. Tengo que expiar mis pecados. Adiós.}
{218}{}{Me llamo }
{219}{}{. Recuérdalo, y cuéntale a tus hijos de mí.}

{220}{}{Te daré 35 chapas, pero con una condición. Necesito un 'favorcito' de tu parte.}
{221}{}{(Te mira con repudio por tu sórdida propuesta)}
{222}{}{¿Qué te parece?}
{223}{}{Bueno, olvídalo. No es buena idea, eso es obvio.}
{224}{}{Todavía tengo mi orgullo, de ninguna forma haré eso. ¡No te me acerques, me das asco!}
{225}{}{Oye, cálmate.}
{226}{}{(suspira) Yo vivía en la colonia, pero jamás pensé que tendría que ganarme la vida así.}
{227}{}{Hay una primera vez para todo. Mueve el culo, vayamos a algún lugar a escondidas.}
{228}{}{Lo siento, esto es una mala idea. Olvídalo, me voy...}
{229}{}{(tras una hora de sexo duro, te paras de la cama y observas su cuerpo desnudo e inmóvil; sacas las chapas de tu bolsillo y las sueltas sobre las sábanas sucias sin decir nada; la mujer te da la espalda y empieza a sollozar en silencio)}
{230}{}{[Hecho]}
