{100}{}{Ves a Lloyd.}
{101}{}{Estás viendo a un mendigo que hurga las calles buscando comida.}
{102}{}{La gente como él son una plaga para el mundo.}
{103}{}{Oye, ¿qué dijiste de mí, pedazo de hojalata? Parece que esa botella tenía algo raro adentro...}
{104}{}{Oh, Lloyd...}

{200}{}{Oye, no parece que seas de por aquí. En esta ciudad, los nuevos la tienen difícil. Te daré un consejo, haz amigos. Aquí eso viene bien.}
{201}{}{¿Cómo te llamas, amigo mío?}
{202}{}{Es raro escuchar eso de un vagabundo.}
{203}{}{Soy Lloyd, sólo soy un perro callejero. Pero que eso no te engañe, conozco esta ciudad mejor que a mis tres dedos.}
{204}{}{Me vendría bien la sabiduría de un experto de Fénix. ¿Me puedes responder unas preguntas?}
{205}{}{A mí se me hace que eres un perdedor. No quiero nada que ver contigo, adiós.}
{206}{}{Oye, parece que tienes algunas chapas encima. Si compartes un poco de dinero, te ganarás amigos leales y estarán agradecidos contigo, así son las cosas en la ciudad.}
{207}{}{Adiós, Lloyd.}
{208}{}{Nos vemos, Lloyd.}
{209}{}{Sigue hablando, no tengo prisa.}

{210}{}{¿Una chapa? No lo arrepentirás.}
{211}{}{Eres tú, ¡Hola! ¿Te puedo ayudar en algo?}
{212}{}{Ahora no, quizás otro día.}

{213}{}{¡Pero que tremendo terremoto! ¿Y esos rumores de que ensamblaban una bomba nuclear? Eran ciertos. Están locos, ahora la ciudad entera los odiará, y yo perdí un trabajo. Mierda...}
{214}{}{Recibieron su merecido, Lloyd.}
{215}{}{Sí.}

{220}{}{Aquí tienes una chapa.}
{221}{}{Toma, una chapa. Necesito tus consejos.}
{222}{}{Te daré una chapa, ¿qué puedes contarme?}
{223}{}{Aquí tienes una chapa. Cuéntame un rumor interesante.}
{224}{}{[Siguiente]}
{225}{}{Gracias, patrón.}
{1225}{}{Gracias, jefa.}
{226}{}{Gracias, patrón. Pero hasta nuevo aviso, al viejo Lloyd se le acabaron los consejos.}
{1226}{}{Gracias, jefa. Pero hasta nuevo aviso, al viejo Lloyd se le acabaron los consejos.}
{227}{}{No hay problema. Lo entiendo, estoy igual de quebrado que tú. Nos vemos.}
{228}{}{Eh, sí, adiós.}
{229}{}{Por hoy, nada. Adiós.}

{230}{}{Ah, rumores. Para eso vivo.}
{231}{}{(mira a su alrededor) B-bueno...}
{232}{}{Lloyd lo ve todo desde las calles. Te lo aseguro.}
{233}{}{Sabes, yo escucho muchas cosas.}
{234}{}{¿Nuevas noticias? Algo he escuchado.}
{235}{}{Sí, te tengo un consejo.}
{236}{}{Hmm... (se rasca su sucio mentón)}
{237}{}{Sabes, la gente dice todo tipo de cosas.}
{238}{}{(tarareando) Ah, chapa chapa, chapita...}
{239}{}{Muchas gracias.}

{240}{}{¿Y bien?}
{241}{}{Continua.}
{242}{}{Habla.}
{243}{}{[Escucha]}
{244}{}{[Siguiente]}
{245}{}{¿Qué puedes contarme?}

{250}{}{Saludos. ¿Qué te parece mi ropa nueva? La compré con tus chapas, te lo agradezco. A veces pienso que puedo salir de este agujero y empezar otra vez. Pero a quién engaño...}
{251}{}{No todo está perdido, Lloyd. No puedes caer más bajo, solo te queda subir.}
{252}{}{Las personas como tú no tienen futuro. Aguántate.}
{253}{}{Escucha, estoy haciendo tanto dinero que me puedo permitir un regalito. Con este traje, se me abren todas las puertas. Y es gracias a ti.}
{254}{}{Escucha, estoy haciendo tanto dinero que me puedo permitir un regalito. Con este traje, podría mudarme al cuarto de lujo. Es una pena que ya esté ocupado.}
{255}{}{Estoy feliz por ti, Lloyd.}
{256}{}{No puedo creerlo. Tuviste suerte, eso es todo.}

#Vault 27
{260}{}{¿Sabes algo sobre el Refugio 27?}
{261}{}{No mucho. Te diré lo que sé por 10 chapas.}
{262}{}{Olvídalo.}
{263}{}{Aquí tienes las chapas. Habla.}
{264}{}{He oído varias leyendas sobre ese refugio. Algunos dicen que los peces gordos de Fénix crearon un laboratorio secreto ahí, otros dicen que desde la guerra está embrujado con fantasmas. Quizás ni siquiera existe.}
{265}{}{Es triste saber eso.}
{266}{}{Si quieres encontrar esa leyenda, habla con el viejo Bob. Vive en los barrios bajos, eso está al este de aquí. Él conoce bien las ruinas de Fénix.}
{267}{}{Gracias, has sido de mucha ayuda.}
{268}{}{No me fuiste de ayuda, pero quizás ese tal Bob sí.}

{270}{}{Esta ciudad es enorme, pero necesito hallar a un pariente. Uno de ellos se llama Miguel.}
{271}{}{Sí, en una ciudad tan grande como esta es difícil encontrar a alguien. Además, no todos quieren ser encontrados. Pero hay una forma, te lo diré por 5 chapas.}
{272}{}{Aquí tienes. ¿Qué debo hacer?}
{273}{}{En otro momento.}
{274}{}{Aquí cerca hay una agencia de reclutamiento. Si pagas, encontrarán a cualquiera, incluso sacarían al Diablo del piso.}
{275}{}{Gracias, amigo mío. De verdad fuiste de ayuda.}
{276}{}{¿Me cargaste 5 chapas para eso? Que estafa.}
{277}{}{Conozco a unos diez Miguel. Uno es una mujer. Pero si tu pariente es de lejos, quizás hasta se haya cambiado el nombre. No será fácil encontrarlo, intenta preguntarles al Gremio de Mercenarios, también buscan gente.}

{280}{}{¿Qué sabes del ataque contra los monjes?}
{281}{}{Eso te saldrá caro. 20 chapas.}
{282}{}{Me parece justo. Ten, habla.}
{283}{}{No, seguramente alguien me lo dirá por menos.}
{284}{}{Perdóneme, patrón, pero no vendo información así, es peligroso. Prueba con alguien del mercado.}
{1284}{}{Perdón, jefa, pero no vendo información así, es peligroso. Prueba con alguien del mercado.}
{285}{}{De acuerdo.}

#Tips and Rumours
{300}{}{En los últimos años, las chapas se volvieron la moneda de por aquí. Es parecido a los dólares de la preguerra, están respaldadas por la Iglesia del Fuego Santo. Pero hay muchos que no confían en ellas.}
{301}{}{Hablando de chapas, aquí tienes otra. ¿Qué hay de los dólares de la preguerra?}
{302}{}{Eso es más complicado. Lo normal es que nadie los usa, pero el casino comprará todo el dinero de la preguerra. Si encuentras un billete, llévaselo a la cajera, quizás te ganes unas chapas.}
{303}{}{¿Alguna vez has estado en el casino Atomic Rush? Vale la pena visitarlo, puedes gastar unas chapas y ver si tienes suerte. Pero que no te engañen, hagas lo que hagas, la casa siempre gana.}
{304}{}{¿Quién es el dueño de ese lugar? Quizás pueda trabajar ahí.}
{305}{}{Dudo que el casino contrate a alguien de la calle. Ahí son como una familia, y la cabeza, Don Diego, es quisquilloso cuando se trata de contratar a alguien. Si quieres trabajar para él, debes ganarte la confianza de sus empleados o tener una buena reputación en la ciudad.}
{306}{}{Debes tener cuidado en los barrios bajos. Por ahí manda la pandilla de Orris, es mejor que evites estar ahí.}
{307}{}{Aquí tienes otra chopa, háblame de esa pandilla.}
{308}{}{Orris es el líder de los Cardenales Rojos y junto a ellos manda en los barrios bajos. Pero a diferencia de sus chicos, él no es tan malo. Si te apunta con un arma, intenta hablarle.}
{309}{}{La planta eléctrica subió sus precios y le dieron un ultimátum a Aaron. No sé quién ganará, pero la ciudad lo tendrá difícil.}
{310}{}{Te daré otra chapa si me hablas de ese lugar.}
{311}{}{Alrededor de la planta hay una fosa de desechos tóxicos, trampas y alambre de púas. Sé que hay un túnel en las alcantarillas que lleva al sótano de la planta, pero debe estar lleno de trampas.}
{312}{}{Algo está pasando en la Catedral del Fuego. Hay más caravanas que van para allá, y Aaron se está volviendo más audaz, presiona más al pueblo.}
{313}{}{Toma, otra chapa. ¿Qué sabes acerca de ese tal Aaron?}
{314}{}{No sé mucho, hay rumores conflictivos, pero está claro que es un tipo poderoso y está obsesionado con sus ideales. Algunos dicen que está enganchado a unas pastillas con las que no puede vivir.}
{315}{}{Últimamente se encuentran más cadáveres en la alcantarilla. Antes sólo habían okupas ahí abajo, pero ahora es peligroso.}
{316}{}{Ten una chapa más. Háblame de los okupas.}
{317}{}{Son gente rara que vive en el alcantarillado. No les gusta la superficie y sólo salen de ahí para intercambiar ratas muertas. Si quieres hablarle, dales de comer y empezarán a hablar.}
{318}{}{Un vagabundo nos habló de un refugio lleno de comida y tecnología funcional. Aquellos que le creyeron desaparecieron sin dejar rastro.}
{319}{}{Te daré otra chapa si puedes decirme cómo encontrar a ese vagabundo.}
{320}{}{Se fue. Si estás en los barrios bajos, busca al viejo Bob. Él tiene experiencia cuando se trata de hurgar entre las ruinas.}
{321}{}{La caravana de correos va regularmente hacia Flagstaff. Esa colonia es nueva y crece rápido, gracias a la Catedral del Fuego.}
{322}{}{He escuchado que hubo una pelea en San Brahmán y que los Seguidores del Fuego estaban metidos en eso. Nadie sabe qué pasó exactamente.}
{323}{}{Los rumores de Casa Grande no son falsos - la ciudad está hecha pedazos por conflictos por el poder. Cada vez que amanece, hay un nuevo alcalde que reemplazó al viejo. Si vas hacia allá, prepárate para encontrar problemas.}
{324}{}{Llegan muchos rumores del sur acerca de los Hojalateros. Hay caravanas que van allá, pero hay pocos que comercien con ellos, son misteriosos.}
{325}{}{Como las caravanas iban al sur, algunos saqueadores se establecieron cerca de las carreteras. Ellos son los forajidos. Matan a los viajeros y roban sus cadáveres.}
{326}{}{Aquí tienes otra chapa. ¿Cómo puedo cuidarme en la carretera?}
{327}{}{Para evitar a esos forajidos, tienes dos opciones. Primero - aléjate de la carretera y viaja en el desierto. Segundo - únete a una caravana bien protegida.}
