{100}{}{Ves a un mercenario de aspecto robusto.}
{101}{}{Ves a un hombre fuerte equipado con armadura pesada.}
{102}{}{Has perdido a tu guardaespaldas.}
{103}{}{Se te acabó el tiempo; tu guardaespaldas regresó al área de caravanas.}

{110}{}{El campamento de las caravanas probablemente sea el lugar más seguro de la ciudad.}
{111}{}{Esto es el mercado, por aquí no te harán daño, pero te vaciarán los bolsillos antes de que lo notes.}
{112}{}{Ten cuidado, los Cardenales controlan estos barrios, y si te metes en problemas, no podré sacarte de esa.}
{113}{}{Más adelante hay una central eléctrica, es vieja pero sigue funcionando gracias a los necrófagos.}
{114}{}{Estamos en la Catedral del Fuego Santo. Lo siento, pero no voy a entrar ahí.}

#Dialogue without accompaniment
{200}{}{Hola, no eres de aquí, ¿verdad?}
{201}{}{Sí, me muero por saber que me ofrecerá esta ciudad.}
{202}{}{¡Puede ofrecerlo todo! Fénix es enorme, es la ciudad más grande que encontrarás, probablemente en cualquier lado.}
{203}{}{Me suena a que me pondrás un 'pero'.}
{204}{}{Genial, no puedo esperar a explorarla.}
{205}{}{Pero te lo advierto, ve con cuidado; no es el mejor sitio para 'explorar'.}
{206}{}{¿Qué? ¿Por qué no?}
{207}{}{¿En serio? ¿No será que exageras para sacarme unas chapas?}
{208}{}{¿A ti qué te importa?}
{209}{}{Oye, relájate. No es necesario estresarse, eso es trabajo mío. Quizás te guste un recorrido a través de la gran Fénix.}
{210}{}{Puede ser. Quizás valga la pena.}
{211}{}{¡Por supuesto!}
{212}{}{Entonces mira, ten cuidado; no es el mejor momento para eso..}
{213}{}{La ciudad ha sido inestable durante años. Algunas áreas son controladas por bandas, incluso ocurren robos y atracos en el mercado. Es más seguro ir acompañado por las calles.}
{214}{}{¿Qué sugieres?}
{215}{}{Supongo que sabes cómo lidiar con los problemas de esta ciudad.}
{216}{}{Mi trabajo es escoltar gente importante por la ciudad. Los ladrones salen corriendo como cucarachas cuando ven un guardia armado. Pero parece que ya te acompaña alguien. Si necesitas protección, habla conmigo. Soy un profesional.}
{217}{}{Lo tendré en cuenta. Adiós.}
{218}{}{Mi trabajo es escoltar gente importante por la ciudad. Los ladrones salen corriendo como cucarachas cuando ven un guardia armado. Si necesitas protección, habla conmigo. Es lo que hago.}
{219}{}{Me lo pensaré. Debo irme. Adiós.}
{220}{}{Puedo cuidarme por mi cuenta.}
{221}{}{¡No lo dudo! Pero si cambias de parecer, ya sabes en dónde encontrarme..}
{1221}{}{¡Sí le creo, señorita! Pero si cambia de parecer, ya sabe en dónde encontrarme.}
{222}{}{Lo consideraré. Adiós.}
{223}{}{Parece que cada gran ciudad tiene una estafa en la entrada. Me largo.}
{224}{}{Me interesa. ¿Cuánto cobras por tu servicio?}
{225}{}{Mis servicios valen }
{226}{}{ chapas la hora. No es negociable.}
{227}{}{No puedo permitirme eso. Adiós.}
{228}{}{Claro, aquí tienes.}

{230}{}{Mientras te cuide la espalda, tendrás a Fénix a tus pies.}
{231}{}{Estoy contigo.}
{232}{}{Mientras esté cerca tuyo, no necesitarás ni un médico ni un cura.}
{233}{}{No dejaré que te pase nada, lo juro por mi madre.}
{234}{}{Relájate, hasta los perros de la calle me conocen.}
{235}{}{No te preocupes, conozco la ciudad como la palma de mi mano.}
{236}{}{Puedes divertirte y pasarla bien, yo te cubro.}

{239}{}{Genial, tengo mi propio guardaespaldas.}

{240}{}{¿Buscas un guardaespaldas? Te sugiero que contrates uno, o consigas un buen lanzagranadas.}
{241}{}{Adiós.}
{242}{}{¿Todavía escoltas gente?}

#Escort Dialogue
{250}{}{Lo que usted quiera, patrón.}
{251}{}{No hay moros en la costa.}
{252}{}{Parece que estamos a salvo.}
{253}{}{No te hagas encima, no hay nada que temer.}
{254}{}{Te sacaré de cualquier problema.}
{255}{}{¿Qué?}
{256}{}{¿Algún problema?}
{257}{}{¿Sí?}
{258}{}{Este barrio es controlado por la banda de los Cardenales. Si quieres vivir, es mejor que nos vayamos.}
{259}{}{Estoy listo, vamos.}

{260}{}{Espérame aquí, ya vuelvo.}
{261}{}{Claro, lo que tú digas. Pero si se te acaba el tiempo, regresaré con las caravanas.}
{262}{}{No vayas a ningún lado.}
{263}{}{Vamos.}
{264}{}{Como usted diga, patrón.}
{265}{}{Adelante.}
{266}{}{Ya no necesito de tus servicios.}
{267}{}{¿Estás seguro? No te reembolsaré el tiempo que falte.}
{1267}{}{¿Está segura? No le reembolsaré el tiempo que falta.}
{268}{}{Sí, puedes irte. Si necesito tu ayuda, sé en donde encontrarte.}
{269}{}{Está bien, quédate un poco más.}
