{100}{}{Ves a una niña pidiendo limosna.}
{101}{}{Ves a una niña con dos maracas, intenta tocar una canción.}
{102}{}{Gracias, señor.}
{1102}{}{Gracias, señorita.}
{103}{}{¡No te me acerques!}
{104}{}{*Bosteza y se frota los ojos*}

{200}{}{(Al ver como te acercas, la niña empieza a mover las maracas mientras canta, en un ritmo penoso). ~ La cucaracha, la cucaracha, ya no puede caminar... ~}
{201}{}{[Escucha]}
{202}{}{[Sigue caminando]}
{203}{}{~ Porque no tiene, porque le falta, marihuana que fumar ~}
{204}{}{[Sigue escuchándola]}
{205}{}{~ Ya se van los carrencistas, ya se van por el alambre, porque dicen los villistas, que se estarán muriendo de hambre. ~}
{206}{}{[Sigue escuchando]}
{207}{}{~ Pobre de la Cucaracha, se queja con decepción, de no usar ropa planchada, por la escasez de carbón. ~}
{208}{}{}
{209}{}{(Te acerca su jarrita de la limosna)}
{210}{}{No tengo dinero. Quizás otro día.}
{211}{}{Ten una chapa, úsala bien.}
{212}{}{Tengo un par de chapas, te las ganaste.}
{213}{}{Toma tres chapas, cómprate algo para comer.}
{214}{}{Hoy me siento generoso, aquí tienes cuatro chapas.}
{1214}{}{Hoy me siento generoso, aquí tienes cuatro chapas.}
{215}{}{No quiero verte sufrir. Ten, son cinco chapas.}
{216}{}{¡Cantas horrible! Ahórranos la miseria de volver a escucharte.}
{217}{}{¡Bravo! Tienes talento, jovencita.}
{218}{}{Es una buena canción, pero necesitas practicar.}

{220}{}{Gracias, señor...}
{1220}{}{Gracias, señorita...}
{221}{}{Podrías ser un poco más agradecida, pero supongo sería mucho pedir...}
{222}{}{De nada. Ojalá que sea de ayuda.}

{230}{}{Niña tonta, es al revés, ¡YO te quitaré las chapas!}
{231}{}{(Sacude la cabeza en silencio, horrorizada, mientras da un paso atrás.)}
{232}{}{Te pido disculpas, sólo bromeaba. No te haré nada.}
{233}{}{¡Quieta ahí! ¡Dame tus chapas!}
{234}{}{(La niña se escapa hábilmente de ti, aprovechando tu torpeza)}
{235}{}{¡Corre mientras puedas, niña estúpida! ¡Te atraparé!}
{236}{}{Hoy tuviste suerte.}
{237}{}{¡Déjame! (Mientras agarras su brazo, encuentras diez chapas y te las quedas.) ¡Ayuda, por favor!}
{238}{}{Si buscas ayuda, te mato. Lárgate.}
{239}{}{Puedes irte, sólo quería las chapas.}
