{100}{}{Ves a Elisa.}
{101}{}{Ves a una mujer de ojos llenos con determinación. Intentar a hacerla cambiar de parecer no dará frutos.}
{102}{}{Marcos decidirá qué hacer contigo, pero yo no te quitaré los ojos de encima.}
{103}{}{¡Nuestra misión falló y por culpa tuya!}
{104}{}{Fue sólo gracias a ti que tuvimos éxito. Gracias.}

# Dialogue
{200}{}{Puede que Marcos te haya permitido estar aquí, pero eso no significa que confiemos en ti. Debes ganártela con tus acciones, y aguas con lo que dices.}
{201}{}{Claro, es de esperarse.}
{202}{}{No será fácil confiar en ustedes si me reciben así.}

{210}{}{Bienvenido seas, hermano. ¿Te ayudo en algo?}
{1210}{}{Bienvenido seas, hermano. ¿Te ayudo en algo?}
{211}{}{Adiós, hermana.}

{220}{}{Háblame de ti.}
{221}{}{Estamos reunidos aquí por una causa, no para socializar. La verdad es que no hablamos de nuestro pasado.}
{222}{}{¿Cómo te involucraste en todo esto?}
{223}{}{Entiendo. Perdón.}
{224}{}{Eso no importa. Lo único que diré es que al principio, tenía mis propias razones. Pero hoy, lucho por algo mucho más grande.}
{225}{}{Eso es interesante. ¿Te puedo hacer otra pregunta?}
{226}{}{¿Qué puedes contarme acerca de Marcos?}
{227}{}{Es un gran hombre.}
{228}{}{¿Eso es todo?}
{229}{}{Pues, tiene un pasado oscuro. Sólo sé que antes de crear el Partido, sufrió una tragedia.}
{230}{}{¿Él te gusta?}
{231}{}{¿Qué...? ¿Cómo...? Mira, lo admiro como líder. Al fin y al cabo, ha unido a muchas personas bajo una buena causa. Pero jamás le he visto la cara; nunca se la quita en frente mío.}
{232}{}{Gracias por una respuesta tan... detallada.}
{233}{}{Ya veo. Gracias.}
{234}{}{¿Qué hacen aquí?}
{235}{}{Es nuestro cuartel general. Aquí hacemos nuestros planes, además de guardar y preparar nuestro equipamiento.}
{236}{}{¿Puedo usar las mesas de trabajo?}
{237}{}{Mientras las uses para ayudar a nuestra causa, no importa.}
{238}{}{Gracias.}
{239}{}{¿Qué es este lugar?}
{240}{}{Esto solía ser una estación de tren subterránea. Los túneles colapsaron durante la Gran Guerra, y sólo quedó la salida hacia el alcantarillado. Es por eso que sólo unas pocas personas saben de este lugar.}

# Issue of Equipment
{250}{}{Voy a necesitar algo de equipamiento para la misión.}
{251}{}{De acuerdo, Marcos dijo que eres de confianza. Esto es lo que tenemos, ¿qué necesitas?}
{252}{}{Por el momento, nada. Volveré después.}
{253}{}{Si eso no te basta, puedes ir a la armería del centro, el dueño trata con nosotros en secreto. Esta es la contraseña: "Prefiero morir de pie que vivir de rodillas."} #No hay nadie más leal al emperador que un puñado de campesinos.
{254}{}{Comprendo. Me encargaré de la misión. Hasta luego, Elisa.}
{255}{}{}
{256}{}{Justo lo que necesitas.}
{257}{}{Equipo de Francotirador. (Rifle de Caza, Munición)}
{258}{}{Claro, toma un rifle de caza y una caja de munición. Debería bastarte.}
{259}{}{Equipo de Asalto. (SMG, Balas, Granadas, Estimulante)}
{260}{}{¿Irás de cabeza, cierto? Está bien, supongo que tú y Marcos saben lo que hacen. Aquí tienes un subfusil junto a una caja de cartuchos de 10mm, un par de granadas y un estimulante por si te dan.}
{261}{}{Equipo de Espía. (Bengala, Sigilante, Explosivos, Estimulante)}
{262}{}{De acuerdo, déjame ver. Una bengala para ver en la oscuridad, un sigilante para ir a escondidas y explosivos por sí acaso. Por si acaso, llévate un estimulante, en caso de que te descubran.}

{270}{}{¿Eres la experta en explosivos? Me vendrían bien unos consejos.}
{271}{}{Lo siento, pero no tengo tiempo para enseñarte.}
{272}{}{Puedo cubrirlo, tengo chapas.}
{273}{}{Me parece bien, las chapas nos ahorrarán tiempo y podrán fundar las operaciones del Partido. Primero, trae 350 chapas, en ese entonces te enseñaré lo que sé.}
{274}{}{De acuerdo, volveré cuando tenga las chapas.}
{275}{}{Olvídalo.}
{276}{}{Merezco una ayuda, ¿no crees? Después de todo, pude salvar a uno de tus amigos.}
{1276}{}{Merezco una ayuda, ¿no crees? Después de todo, pude salvar a uno de tus amigos.}
{277}{}{Tienes razón. Lo siento, estamos bastante ajetreados. Unas 100 chapas serán suficientes.}
{278}{}{Ten 100 chapas. Enséñame.}
{279}{}{Ten 350 chapas. Enséñame.}

# Tasks
{300}{}{Marcos quiere que vaya a la superficie. ¿Cuál es mi misión?}
{301}{}{Pon atención. Uno de nuestros agentes fue a la superficie para colocar un amplificador de señal, pero perdimos contacto con él. Encuéntralo y termina lo que empezó.}
{302}{}{¿Por qué quieren un amplificador allá arriba?}
{303}{}{Utilizamos la radio para comunicarnos y para espiar a los cultistas. Pero bajo tierra, la señal es demasiado débil, por eso necesitamos un amplificador en la superficie.}
{304}{}{De acuerdo. Me pondré con ello.}
{305}{}{¿Me equiparás para la misión?}
{306}{}{Lo único que debes hacer es pasarte por las ruinas. Si no puedes con algo así, ¿cómo te las arreglaste para llegar hasta acá? Además, Marcos no me ha dicho que deba equiparte.}
{307}{}{Ya veo. Nos vemos luego.}
{308}{}{Si me muero, será culpa tuya.}

{310}{}{¿En dónde debería buscar al agente?}
{311}{}{Dirígete a la alcantarilla principal, por donde llegaste a este lugar, y ve al oeste. Debes llegar a las ruinas de Union Station. No te vayas a perder.}
{312}{}{Quiero hablar acerca de mi misión.}
{313}{}{¿Qué tienes que contar?}
{314}{}{Nada, por ahora. Ya mero me pongo con ello.}
{315}{}{Es acerca del agente. Ha muerto.}
{316}{}{Demonios... Esto es malo. ¿Qué hay del amplificador?}
{317}{}{No lo sé.}
{318}{}{El amplificador está listo, puedes revisar la señal.}
{319}{}{Entonces, no perdamos más tiempo...}
{320}{}{[Más]}
{321}{}{El amplificador es crucial, encuéntralo e instálalo. Es el único que tenemos.}
{322}{}{Me encargaré de ello.}
{323}{}{Los monjes consiguieron emboscar al agente, pero lo saqué de ahí.}
{324}{}{Gracias al cielo. Lo hiciste bien, pero hace falta instalar el amplificador.}
{325}{}{}
{326}{}{De acuerdo, ya voy.}
{327}{}{Encontré el amplificador, ya está activado.}
{328}{}{Genial, sólo dame un momento, tengo que revisar la señal...}
{329}{}{[Más]}
{330}{}{Bien hecho. ¿Qué hay del agente?}
{331}{}{Está muerto.}
{332}{}{No... Esto es malo... Muy malo. Espera, tengo que revisar si funciona el amplificador...}
{333}{}{[Más]}
{334}{}{No pude encontrarlo. Quizás escapó.}
{335}{}{No, no ha hecho contacto con nosotros, lo más probable es que haya sido capturado por los cultistas. Averigua qué le ocurrió mientras me encargo de la señal.}
{336}{}{Entiendo. Estoy en ello.}
{337}{}{Bien hecho, ahora será mucho más fácil espiar a los Seguidores. Tuviste éxito, así que habla con Marcos.}
{338}{}{De acuerdo. Adiós, Elisa.}
