{100}{}{Ves a un Cardenal encarcelado.}
{101}{}{Ves a uno de los Cardenales Rojos.}
{102}{}{*Oof*}
{103}{}{Malditos bastardos...}

{110}{}{Ayúdame a salir de aquí. No lo olvidaré.}
{111}{}{¿Conoces a Orris? Dile que estoy encerrado aquí.}
{112}{}{Los mercenarios no me dejarán salir. Dile a Orris que me tienen tras las rejas.}

{115}{}{¿Te envía Orris? No le gustará este asunto, ni un poco.}
{116}{}{Nos vemos en la base. A Orris no le gustará lo que tengo que decirle.}
{117}{}{Parece que alguien nos tendió una trampa.}
