{100}{}{Ves a un mensajero.}
{101}{}{Ves a un hombre con un cuchillo en las costillas. Puede que muera pronto.}
{102}{}{Ves a un hombre herido. Apenas tiene energías para pararse.}
{103}{}{...Bruce, sus mercenarios... nos atacaron...}
{104}{}{Pensé que iba a morirme. Gracias, doctor.}

{110}{}{...Estoy herido...}
{111}{}{...Ahh... duele...}
{112}{}{...A-ayúdame...}
{113}{}{...Voy a hablar, ayúdame...}
{114}{}{...Nos emboscaron... nos esperaban...}
{115}{}{¡Por favor, ayúdame!}
{116}{}{Está bien... hablaré...}
{117}{}{...Bruce, sus mercenarios...}
{118}{}{...Se llevaron al... al Cardenal Rojo... y...}
{119}{}{...Ar-rh...}
{120}{}{Lo lamento, pero la ayuda llegará demasiado tarde.}

{200}{}{Gracias, te debo una.}
{201}{}{¿Quién te atacó?}
{202}{}{Fueron los mercenarios del gremio de Bruce, creo que nos tendieron una trampa. Se llevaron al tipo con el que hablaba, era uno de los Cardenales Rojos. Me acuchilló y me dejó por muerto.}
{203}{}{¿Por qué te metiste en esto?}
{204}{}{Sólo soy un desempleado. Alguien me pidió que entregara una nota, eso era todo. No sé nada más.}
{205}{}{Los trabajos fáciles no existen, recuerda eso. Iré a darle una visita al gremio de mercenarios.}
{206}{}{Lo siento, tuvo que haber sido difícil. Adiós.}
{207}{}{Adiós.}
