{100}{}{Ves a Murphy.}
{101}{}{Uno de los Cardenales Rojos se encuentra ante ti.}
{102}{}{Tu armadura me vendría bien.}
{103}{}{¿Nos vas a chivar? Ven, tenemos que hablar.}
{104}{}{Eres una rata, fuera de mi vista.}
{1104}{}{Eres una rata, fuera de mi vista.}
{105}{}{Me alegra verte.}
{106}{}{Murphy te está esperando en el cuadrilátero, al sur de aquí.}

{200}{}{No te me vayas a acercar. Seguro que me ensucias, rata.}
{1200}{}{No soporto el hedor de una puta como tú, ¿te puedes ir a bañar?}
{2200}{}{Ni me mires, fenómeno. No quiero que me pegues la lepra.}
{201}{}{¿Qué tal si le bajas a la hostilidad, Murphy?}
{202}{}{Ni lo pienses. A diferencia de Orris, no soy tan ingenuo.}
{203}{}{Bueno, como quieras. Adiós, Murphy.}
{204}{}{Puedo decir lo mismo, baboso.}
{205}{}{Dame una oportunidad y te desangrarás a mis pies. Por ahora no, Orris te necesita. Por el momento.}
{1205}{}{Dame una oportunidad y te desangrarás a mis pies. Por ahora no, Orris te necesita. Por el momento}
{206}{}{Hm. Lo mismo digo, Murphy.}
{207}{}{Entonces mantendré la distancia.}
{208}{}{Mejor así, es bueno que sepas tu lugar.}
{209}{}{Como tú digas, Murphy.}

{210}{}{¿Qué pasa?}
{1210}{}{¿Por qué me molestas, perra?}
{2210}{}{¿Qué quieres, fenómeno?}
{211}{}{Ya cálmate. Me voy.}
{212}{}{Hola. ¿Qué necesitas?}
{213}{}{Nada, hasta luego.}
{214}{}{¿Qué tal? ¿Todo bien?}
{215}{}{Estoy bien. Adiós.}
{216}{}{Me alegra verte.}
{217}{}{Adiós.}

{220}{}{He escuchado que un espía se infiltró en los Cardenales. ¿Sospechas de alguien?}
{221}{}{Eso es una pendejada. No hay ningún soplón acá. No soportamos a los Seguidores, ni podemos acercarnos a la Catedral. Nos ven como criminales.}
{222}{}{Hmm, parece que no sabes nada.}
{223}{}{Te demostraré que hay un espía entre nosotros.}
{224}{}{Sé quién eres, Murphy. Trabajas para la Iglesia, eres un Seguidor. ¿No es así?}
{225}{}{¿De qué mierda hablas? ¿Un Seguidor? ¿Yo? No tengo nada que ver con esos idiotas. ¿Me escuchas?}
{226}{}{Claro, claro. Nos vemos en el cuadrilátero que está al sur, allí podremos hablar a solas.}
{227}{}{Ahora que lo pienso, hay mucha gente llamada Murphy en esta ciudad. No importa.}

{230}{}{Ya te dije todo. Si vas a ayudarme, haz lo que tienes que hacer.}
{231}{}{Claro.}
{232}{}{¿Quién demonios eres? ¿Vienes de parte de la Catedral?}
{233}{}{Sé que eres un agente de los Seguidores. Ganarse la confianza de Orris fue difícil, ¿no?}
{234}{}{Aaron necesita agentes en todos lados. Esa es mi misión, y me estoy arriesgando al hablar contigo. ¿Quién eres?}
{235}{}{Se podría decir que tengo mis propios planes.}
{236}{}{¿De verdad debería creerte? En todo caso, puede que lleguemos a un acuerdo. Quiero derrocar a Orris y reformar la banda para el beneficio de la iglesia. Estos tipos sólo saben pelear, pero al menos deberían pelear con las personas correctas.}
{237}{}{Eso es muy ambicioso.}
{238}{}{Si me ayudas, le harás una buena impresión a los Seguidores. No puedo encargarme de Orris por mi cuenta, o habrán consecuencias.}
{239}{}{Eres un traidor, no confío en los traidores.}
{240}{}{He sido un Seguidor desde el principio. Quítate de mi camino.}
{241}{}{Bueno, ya lo veremos.}
{242}{}{Estoy de acuerdo, hay que pararle los pies a Orris y su banda. ¿Cómo puedo ayudar?}
{243}{}{Debes eliminar a Orris, no será fácil hacerlo discretamente y no tampoco sé cómo. ¿Veneno? ¿Sobredosis? ¿Un arma silenciada?}
{244}{}{Encontraré una solución.}
{245}{}{Con la muerte de Orris, la ciudad será más segura. La gloria del Fuego Santo iluminará las ruinas una vez más, y es todo gracias a ti.}
{246}{}{Sólo hice mi deber.}
{247}{}{Le haré saber a la Catedral que me ayudaste, eso evitará futuros malentendidos. Adiós, hermano.}
{1247}{}{Le haré saber a la Catedral que me ayudaste, eso evitará futuros malentendidos. Adiós, hermana.}
{248}{}{Nos vemos, Murphy.}
{249}{}{La Catedral ha sido destruida, pero esto nos da un atisbo de esperanza. Puede que las cosas todavía no hayan acabado.}

{250}{}{¿Qué estás planeando, Murphy?}
{251}{}{Orris me encarga los problemas más duros, después de todo, soy su mano derecha.}
{252}{}{¿Entonces eres el segundo al mando? Es un buen trabajo.}
{253}{}{¿Cómo te uniste a la banda?}
{254}{}{Aquí no nos gustan los mariquitas. Me encargué de los 'problemitas' de Orris hasta que vio mi potencial.}
{255}{}{¿Te gusta el peligro, verdad? Tendré cuidado contigo.}
{256}{}{Los Seguidores intentan acabar con ustedes, ¿no?}
{257}{}{Malditos cultistas, no los soporto. Siempre predican qué está bien y qué está mal. ¿Pero por qué debería importarnos? La única ley que seguimos es la del más fuerte y lo hemos demostrado, porque somos los únicos que controlan este barrio.}
{258}{}{Ya entiendo.}
{259}{}{Estoy contigo, Murphy. ¿Cómo podría acercarme a Orris?}

{260}{}{La central eléctrica fue saboteada. ¿Sabes quién fue?}
{261}{}{Quizás. ¿Quién pregunta?}
{262}{}{Theodore me pidió que lo investigara.}
{263}{}{No me agradan mucho esos necrófagos, ¿por qué delataría a sus enemigos?}
{264}{}{Le preguntaré a alguien más, olvídalo.}
{265}{}{No te preocupes, no le diré a nadie.}
{266}{}{Ni en tus sueños. Lárgate.}
{267}{}{Me apena que no confíes en mí.}
{268}{}{Aunque estés metido en eso, ¿por qué te delataría? No te preocupes, no diré nada.}
{269}{}{¿Preocupado? ¿Yo? ¡Ja! No es eso. Fuimos nosotros, yo estuve ahí. La Catedral quería sabotear la central para que los necrófagos cooperen con ellos, pues no saben reparar nada por su cuenta. Ralph nos lo dejó fácil, es uno de los necrófagos más importantes y nos abrió la puerta subterránea. Quiere ganarse el favor de los Seguidores, así que nos dio una mano.}
{270}{}{¡Eso es una gran historia! Ahora sé que tú eres el que manda. Adiós, Murphy.}
{271}{}{Eres un gran tipo, ¿por qué esconderías algo así? Solo cuéntamelo.}
{272}{}{Yo creía que los Cardenales eran tipos duros. ¿Acaso te preocupa?}
