{100}{}{Ves a un luchador.}
{101}{}{Ves a un luchador. Parece que se lastimó mientras entrenaba.}
{102}{}{Ves a un luchador. Se ve feliz.}
{103}{}{Gracias, me siento mucho mejor.}

#Responses
{110}{}{*Quejido*}
{111}{}{Duele... mucho.}
{112}{}{Agh...}
{113}{}{*Empieza a toser con fuerza*}
{114}{}{Esto duele demasiado...}
{115}{}{Eso fue horrendo...}
{116}{}{Jamás daré otra pelea.}
{117}{}{¿Acaso no tenemos médicos?}
{118}{}{Necesito un analgésico, rápido.}
{119}{}{Cada hora me siento peor...}

{150}{}{Me golpearon muy fuerte.}
{151}{}{Como puedes ver, estoy empeorando.}
{152}{}{Esa última pelea fue mortal.}
{153}{}{Creo que tengo una conmoción cerebral.}
{154}{}{Un doctor... por favor.}
{155}{}{¿Tienes algún analgésico?}
{156}{}{¿En serio no pueden encontrar un sólo estimulante...?}
{157}{}{Esto es un infierno.}
{158}{}{*Gruñe mientras se agarra la cabeza*}
{159}{}{Agh... ¡Mi cabeza me está matando!}

#Random phrases for gratitude and recovery
{170}{}{Gracias, me salvaste.}
{171}{}{Es gracias a ti que sigo vivo.}
{172}{}{¿En dónde aprendiste primeros auxilios?}
{173}{}{Tuve suerte de que hayas estado ahí.}
{174}{}{Ojalá hubieras estado aquí antes, conocí a mucha gente que murió por sus heridas.}
{175}{}{¿No estarás pensando en pelear, verdad?}
{176}{}{Pronto tendré otra pelea, ¿me ayudarás con las heridas?}
{177}{}{¿Quieren que pelee otra vez? Bah, por qué no.}
{178}{}{Tu ayuda es todo lo que necesitaba.}
{179}{}{Algún día volveré a pelear.}
