{100}{}{Ves a un vendedor de poca monta.}
{101}{}{Ves a un vendedor local, prepara bebidas para la audiencia de la arena.}

{110}{}{Bueno, ya está, se acabó mi negocio.}
{111}{}{¿Qué clase de idiota querría matar a Angelo?}
{112}{}{Lo siento, pero ya tengo de eso.}
{113}{}{La arena ha cerrado. Mi negocio también.}
{114}{}{Tendré suerte si salgo de aquí vivo.}

{200}{}{¿Quieres algo de beber antes de la pelea? Tengo buenos precios.}
{201}{}{No, nada de alcohol por hoy.}
{202}{}{Hola. No pensé que un ganador como tú se pasaría por un lugar como este.}
{203}{}{Esa pelea fue genial, }
{204}{}{. Sigue así.}

{210}{}{¿Quieres algo de beber antes de la pelea? Tengo buenos precios.}
{211}{}{Hasta luego.}
{212}{}{¿Puedo apostar en la arena?}
{213}{}{No sé cuándo será la nueva pelea, tendrás que preguntar por ahí. ¿Quieres beber algo o no?}
{214}{}{No, nada de alcohol por hoy.}
{215}{}{Lo pensaré.}
