{100}{}{Ves a Arthur Carrington.}
{101}{}{Ves al mismo arqueólogo del Refugio 27.}
{102}{}{¡Gracias por todo lo que has hecho! Nos vemos en Casa Nueva.}
{103}{}{¡Gracias por todo lo que has hecho! Nos vemos en la Villa.}

#First dialogue
{200}{}{¡Mi salvador! Estoy feliz de verte.}
{1200}{}{¡Mi salvadora! Estoy feliz de verte.}
{201}{}{¿Qué haces aquí? Pensé que después del refugio irías a la Catedral del Fuego para dedicarte a la ciencia.}
{202}{}{Y así fue. Pero la Catedral fue destruida, no sé lo que ocurrió, pero ahora los Seguidores del Fuego han sido exiliados; ya nadie necesita a un científico como yo.}
{203}{}{¿Estás seguro de eso?}
{204}{}{Bueno, no del todo. En el Templo, me crucé con informes de una secta que aprecia a la ciencia tanto como yo, los Seguidores del Apocalipsis. Su base está en algún lugar hacia el sur, pero tengo muy poca información al respecto. Si te los encuentras, házmelo saber, ¿vale?}
{205}{}{No te prometo nada. Gracias por la información.}

#Further conversation
{210}{}{¿Ahora qué?}
{211}{}{No es nada. Adiós.}
{212}{}{Adiós.}

{220}{}{¿Qué crees que le ocurrió a la Catedral?}
{221}{}{Sé que estaban fabricando una bomba nuclear bajo la catedral. Pero una explosión espontánea es casi imposible, por lo que tuvo que haber sido saboteada. Los Seguidores del Fuego tenían muchos enemigos, lo único que me sorprende es que pudieron infiltrarse tan a fondo. Hmm, tuvo que haber sido alguien en quién confiaban...}
{222}{}{Sí, ese fui yo.}
{1222}{}{Sí, esa fui yo.}
{223}{}{Lo dudo, creo que estás mintiendo, la ciudad no necesita rumores como este, créeme.}
{224}{}{¿Por qué necesitaban una bomba?}
{225}{}{Lo único que sé es esto: no era para ellos, alguien más la pidió.}
{226}{}{¿Qué vas a hacer ahora?}
{227}{}{Buscaré algún lugar que necesite científicos como yo. Además de dudosos rumores de los Seguidores del Apocalipsis, no se me ocurre nada más.}
{228}{}{¿Por qué no ir a la Villa? Necesitamos trabajadores para ayudar con la reconstrucción luego del ataque. También necesitamos cerebros que no estén limitados por nuestras tradiciones.}
{229}{}{¿La Villa que mencionaste en el refugio, no es así? Leí algunos informes y descubrí que es una comunidad cerrada de campesinos. La Secta tenía archivos detallados acerca de ustedes. Bueno, creo que sería un lugar fantástico para investigar e implementar tecnología nueva.}
{1229}{}{¿La Villa que mencionaste en el refugio, no es así? Leí algunos informes y descubrí que es una comunidad cerrada de campesinos. La Secta tenía archivos detallados acerca de ustedes. Bueno, creo que sería un lugar fantástico para investigar e implementar tecnología nueva.}
{230}{}{Estoy de acuerdo. Cuándo llegues, diles que yo te envié. Te veo en la Villa.}
{231}{}{Tómate tu tiempo, seguiré intentando averiguar sobre los Seguidores del Apocalipsis.}
{232}{}{Pude encontrar a los Seguidores en Casa Nueva. Estarán encantados de aceptar a un científico como tú. Vamos, andando.}
{233}{}{Tienes muchas conexiones para alguien que nació en una granja. Gracias, no sabes cuánto te lo agradezco.}
{234}{}{Te veo en Casa Nueva.}

#Further options
{240}{}{Buscaré algún lugar que necesite científicos como yo. Hasta ahora, solo sé de la base científica de Casa Nueva.  Pero mi reputación... no es adecuada para tal lugar. ¿No sabes de otro sitio, verdad?}
{241}{}{Ven a la Villa. Necesitamos trabajadores para ayudar con la reconstrucción luego del ataque. También necesitamos cerebros que no estén limitados por nuestras tradiciones.}
{242}{}{¿La Villa que mencionaste en el refugio, no es así? Leí algunos informes y descubrí que es una comunidad cerrada de campesinos. La Secta tenía archivos detallados acerca de ustedes. Bueno, creo que sería un lugar fantástico para investigar e implementar tecnología nueva.}
{1242}{}{¿La Villa que mencionaste en el refugio, no es así? Leí algunos informes y descubrí que es una comunidad cerrada de campesinos. La Secta tenía archivos detallados acerca de ustedes. Bueno, creo que sería un lugar fantástico para investigar e implementar tecnología nueva.}
{243}{}{Estoy de acuerdo. Cuándo llegues, diles que yo te envié. Te veo en la Villa.}
{244}{}{Ahora que lo pienso, es una mala idea. No serás bienvenido; difícilmente aceptan a un científico. Es mejor que vayas a Casa Nueva. O a dónde sea pensabas ir.}
{245}{}{Estoy seguro de que Casa Nueva le daría la bienvenida a otro científico. Quizás vaya, algún día.}
{246}{}{Eso está claro. Aunque el camino a través del desierto no será fácil. Espero nos veamos de nuevo.}
{247}{}{Exactamente. Nos vemos en Casa Nueva.}
{248}{}{Dudo que sea así. Adiós. Arthur.}
