{100}{}{Ves un cartel de "Se Busca".}
{101}{}{Este póster contiene una persona que te es extrañamente familiar.}
{102}{}{Ves un póster con tu rostro y una descripción: "Se busca por crímenes contra la Iglesia del Fuego Santo."}
{103}{}{Ves un póster con tu rostro y una descripción: "Se busca por crímenes contra la ciudad. Recompensa: 500 chapas."}
{104}{}{Ves un póster con tu rostro y una descripción: "Se busca por crímenes contra la ciudad. Recompensa: 1,000 chapas."}
{105}{}{Ves un póster con tu rostro y una descripción: "Se busca por crímenes contra la ciudad. Recompensa: 2,000 chapas."}
{106}{}{El póster fue arrancado y destruido.}
