{100}{}{Ves a un guardia.}
{101}{}{Ves a uno de los guardias de la secta. Te sería difícil distinguirlo de los demás guardias.}

{104}{}{Alguien sonó la alarma. No puedo dejarte pasar...}
{105}{}{¿Ya te vas? Bien.}
{106}{}{¡Alto! ¿Quién está ahí?}
{107}{}{¡Alerta, un intruso! ¡Suenen la alarma!}
{108}{}{¡Alto! Quién es... Ay, parece que vi un fantasma.}

{200}{}{¡Alto! Indique su nombre y el propósito de su visita.}
{201}{}{Lo siento, hermano, soy nuevo aquí, sólo quería echar un vistazo.}
{1201}{}{Lo siento, hermano, soy nueva aquí,  sólo quería echar un vistazo.}
{202}{}{Lo siento, hermano, soy nuevo y sólo quería echar un vistazo.}
{203}{}{¿Por qué tantas preguntas, hermano? ¿Acaso mi túnica no es suficiente?}
{204}{}{Será mejor que me vaya de aquí...}
{205}{}{Dile a tu jefe que tengo información para él.}
{206}{}{Estoy aquí para hablar con Ulysses Grant. Aaron me envía.}
{207}{}{Permítame expresarle nuestro mi más profundo respeto. Diríjase al nivel inferior, Ulysses está en su puesto.}

{210}{}{¡Alerta, un intruso! ¡Suenen la alarma!}
{211}{}{¡No tienes idea del error que acabas de cometer!}
{212}{}{¡Pero yo no hice nada!}
{213}{}{Muy bien, puedes entrar, hermano.}
{1213}{}{Muy bien, puedes entrar, hermana.}
{214}{}{Alabado sea el Fuego Santo, Hermano.}
{215}{}{Gracias... hermano.}

{220}{}{¿Ya te vas?}
{221}{}{Sí. Nos vemos luego?}
{222}{}{Vete. Puedes ir sin nosotros.}
{223}{}{Bien.}
{224}{}{Voy a ver al Asesor. Me envía Su Santidad, Aaron, Señor Supremo de Fénix.}
