{100}{}{Ves al profesor Zimmer.}
{101}{}{Ves al líder del equipo científico. Tiene un aspecto excéntrico.}
{102}{}{No es el momento adecuado para tener un debate científico...}

# Primer diálogo
{200}{}{(Un científico con bata de laboratorio, mirada salvaje y pelo despeinado; te habla sin levantar la vista de su tableta) Estoy ocupado, lárgate.}
{201}{}{Llegué aquí hace poco, ¿Puedo hacerte unas preguntas?}
{202}{}{¿Cómo te atreves a hablarme así?!}
{203}{}{Perdón por molestarte.}

{207}{}{Eso intento decirte, llegué hace poco y...}
{208}{}{¡Seguridad! ¡Un intruso!}
{209}{}{No deberías haber hecho eso...}

{210}{}{(irritado) Ya te dije, no tengo tiempo para nada... Espera. ¿Quién eres?}
{1210}{}{(irritado) Ya te dije, no tengo tiempo para nada... Espera. ¿Quién eres?}

{211}{}{Soy parte de los Seguidores.}
{212}{}{Ya veo. (Levanta gradualmente la voz) ¡¿Y ahora crees que puedes irrumpir en el laboratorio y distraerme de mi trabajo?! (Vuelve a alzar la voz) ¡Entiende esto, pedazo de podredumbre social, el trabajo en este laboratorio es mucho más importante que tus insignificantes payasadas de la catedral! Y no importa qué rango elevado tengas en tu "secta", ¡aquí eso no significa nada! ¿Lo has entendido? Ahora desaparece.}
{1212}{}{Ya veo. (Levanta gradualmente la voz) ¡¿Y ahora crees que puedes irrumpir en el laboratorio y distraerme de mi trabajo?! (Vuelve a alzar la voz) ¡Entiende esto, pedazo de podredumbre social, el trabajo en este laboratorio es mucho más importante que tus insignificantes payasadas de la catedral! Y no importa qué rango elevado tengas en tu "secta", ¡aquí eso no significa nada! ¿Lo has entendido? Ahora desaparece.}
{213}{}{Ya veo.}
{214}{}{Ajá.}

{215}{}{Se me permitió echar un vistazo.}
{216}{}{En ese caso, no voy a darte un recorrido. ¡Lárgate antes de que llame a seguridad!}
{217}{}{No hay problema.}

{219}{}{Me enviaron a arreglar algo.}
{220}{}{¡Entonces ve y arréglalo, estúpido!}
{1220}{}{¡Entonces ve y arréglalo, estúpida!}
{221}{}{Sí, eh, por supuesto.}

{223}{}{Yo también soy un científico, y me enviaron a hablar contigo.}
{224}{}{¿En serio? (deja la tableta a un lado) Muy curioso, muy curioso... Pero nadie me informó de un nuevo asistente. Tráeme la orden escrita y luego hablaremos.}
{225}{}{Bien.}

{227}{}{Se me permitió echar un vistazo.}

# Preguntas repetidas
{300}{}{Bien. Ahora, ¿qué quieres?}
{301}{}{Nada más.}
{302}{}{Adiós.}
{303}{}{¿Quizás podríamos cambiar de tema?}
{304}{}{Permítame hacer una pregunta más.}
{305}{}{Con el debido respeto, colega, *yo* estoy a cargo aquí. Tengo la autoridad para echar a cualquiera del laboratorio, incluso al propio Aaron. ¡Fuera de aquí!}
{306}{}{Vale, vale...}

# Preguntas personales
{310}{}{Disculpe, ¿pero quién es usted?}
{311}{}{(agita la mano con decepción) Así que esto es lo que significa trabajar en las sombras... Mi nombre es Zack Zimmer. Profesor Zack Zimmer. Dirijo este departamento científico. Prácticamente, soy la tercera persona más importante de toda la iglesia, después de Aarón y el Asesor. No tienes que inclinarte ante mí.}

{312}{}{Es raro encontrar un científico en nuestros tiempos.}
{313}{}{Por eso estoy sentado en este refugio bajo la protección de una organización. Los científicos no pueden sobrevivir sin algún mecenas en nuestros tiempos.}
{314}{}{¿Es Profesor un nombre?}
{315}{}{(suspira) Jamás había escuchado una pregunta más estúpida.}
{316}{}{Profesor es un título. Se concede colectivamente.}
{317}{}{¡Qué perspicacia! Te contaré un secreto: una vez, hice cursos en una organización poco conocida por aquí. Fue allí donde me gané este título.}
{318}{}{¿Cómo terminó aquí, profesor?}
{319}{}{Debes haber tenido una vida interesante.}
{320}{}{Es una larga historia, y no es para ti. Digamos que no había lugar para mis ambiciones en el Oeste.}
{321}{}{Al oeste está California. Dudo que hayas cruzado el desierto que nos divide.}
{322}{}{Ejem. Estás haciendo demasiadas preguntas.}
{323}{}{Soy miembro de la Hermandad del Acero. Seguramente, la base tiene un expediente detallado sobre ti.}
{324}{}{Esto cambia mucho. Sí, vine aquí con la Hermandad. Recibí el título de los Seguidores del Apocalipsis en el Cementerio. Pero tuvimos nuestras diferencias, y tuve que irme a Arizona.}
{325}{}{¿En qué cosas no estaban de acuerdo?}
{326}{}{Digamos que los Seguidores del Apocalipsis eran demasiado... blandos. Estaban en contra de los experimentos con seres humanos vivos. Esto ralentizó muchos proyectos médicos.}
{327}{}{¿Qué tipo de cementerio?}
{328}{}{Son ruinas al oeste, más allá del desierto de Sonora. Está demasiado lejos, no puedes llegar allí.}

{330}{}{¿Entonces también eres un Seguidor del Fuego Sagrado?}
{331}{}{¿De qué tonterías estás hablando? ¡Soy un científico, no un sacerdote! Además, mucho de lo que enseñan me parece ridículo.}
{332}{}{¿Qué puedes decirme sobre Aaron?}
{333}{}{Hablar acerca de un líder siempre ha sido peligroso. Incluso entre miembros de una secta.}
{334}{}{No soy miembro de la secta.}
{335}{}{Entonces no tenemos nada más de qué hablar.}
{336}{}{Soy miembro de la Hermandad del Acero.}
{337}{}{Ah... Eso cambia mucho... Entonces, deberías hablar con el Asesor en vez lugar de hablarme a mí.}
{338}{}{Esto quedará entre nosotros.}
{339}{}{Aaron no sería nada si no le hubieran puesto a cargo de la ciudad y de la iglesia. Aún se siente como una marioneta, a veces le vuelve loco... Sin embargo, hoy estoy hablando demasiado.}
{340}{}{No se puede confiar en nadie aquí.}
{341}{}{¿Por ejemplo?}
{342}{}{Ya estoy cansado de explicar cosas sencillas a estos monjes. Es mejor leer literatura científica.}
{343}{}{¿Cómo decir que las partículas elementales son divinas?}
{344}{}{¡Exactamente! ¿Qué clase de ficción ridícula es ésta, que alguna deidad castigó a la gente con un Diluvio Ardiente por sus pecados? Fue una guerra nuclear. Es decir, una guerra ordinaria con bombas muy poderosas.}
{345}{}{¿No saben eso?}
{346}{}{Me temo que ha pasado demasiado tiempo. Los acontecimientos de una era anterior se convierten en mito y leyenda. Por otro lado, la fe de los Seguidores es beneficiosa para la sociedad... hasta que vaya en contra del progreso.}

{350}{}{¿Por qué le gritas a tus subordinados?}
{351}{}{Porque estoy cansado de estar rodeado de idiotas y simios ignorantes.}
{352}{}{¿Eso es todo?}
{353}{}{No tengo intención de discutir esto contigo.}
{354}{}{Creo que es una proyección de esperanzas insatisfechas. Te mantienen atado, ¿no?}

{355}{}{(Se ajusta las gafas perplejo) ¡Vaya! Mira, ¡el primer psicólogo de la civilización posnuclear! Guárdate esas dulces palabras de consuelo para los de arriba. Si tuvieran más RESPETO por mi trabajo, no tendría que levantar la voz a quién sea que me encuentre.}
{356}{}{Claro, lo que tú digas.}
{357}{}{¿Qué es un "simio"?}
{358}{}{(Suspira) Es lo que eres.}
{359}{}{[Ciencia 20] Dicen que el trabajo convirtió a los simios en hombres.}
{360}{}{¡Tonterías! He encontrado textos antiguos que afirman claramente que se trata de dos ramas diferentes de la evolución con antepasados comunes. Sin embargo... es mucho más importante oír eso de la boca de un plebeyo.}

# Preguntas sobre una bomba
{378}{}{¿Diseñaste todo esto tú mismo?}
{379}{}{Por supuesto. Esto representa muchos años de minucioso trabajo hecho por un puñado de científicos.}
{380}{}{¿Es eso una bomba atómica? Impresionante.}
{381}{}{Esto puede ser lo más difícil que hemos hecho. Nadie, ni en California ni en Texas, ha podido hacerlo. ¡Y estamos a punto de terminarlo! Sólo tenemos que esperar algunas partes de Two-Sun.}
{382}{}{California y... ¿Tijas?}
{383}{}{(Suspira) ¡Texas! Estas son partes de un país pasado, estúpido. Tal vez ahora se llamen de otra manera, pero antes de la Guerra, se llamaban así.}
{384}{}{Pero no podrías haberlo construido sin instrucciones, ¿verdad?}
{385}{}{Hmm, ¡entiendes rápido! Sin instrucciones, no habríamos conseguido más que cáncer y leucemia. Las instrucciones fueron traídas por orden de una antigua base militar, muy lejos de aquí.}
{386}{}{¿De dónde sacas el material nuclear?}
{387}{}{De Flagstaff. Tienen una mina de uranio en funcionamiento y una planta de enriquecimiento. La calidad es baja, la producción lenta, pero no hay otra fuente.}
{388}{}{¿Por qué necesitas un arma tan poderosa?}
{389}{}{Buena pregunta. Digamos que hay muchas razones. Y todas ellas sólo las conoce una persona en todo Fénix: el propio Consejero.}

# Preguntas sobre estudios
{400}{}{¿Qué tipo de investigaciones conduce el laboratorio?}
{401}{}{De varios tipos. (Se pierde en sus pensamientos) Nuestra misión es... primero, proveer a los Seguidores del Fuego de todo lo que necesiten... Sí. Y luego encargarnos de la reconstrucción de la ciudad y sus instalaciones industriales. Después de todo, necesitamos trabajadores... Y esto es sólo la primera parte del plan. Lo más importante ahora es eliminar la escasez de alimentos y agua potable en Fénix.}
{402}{}{¿Han tenido avances con ello?}
{403}{}{Hay progreso, pero es demasiado lento. La ciudad está muy destruida, los viejos equipos están arruinados o desgastados, y la base de producción de este refugio sólo basta para abastecer a la Catedral. A esto hay que añadir las disputas entre los distintos clanes de la ciudad, el analfabetismo y toda una lista de problemas. Y si no tienes más preguntas estúpidas, entonces volveré a buscar soluciones.}
{404}{}{No pensé que los Seguidores fueran lo suficientemente generosos como para repartir comida.}
{405}{}{De qué estás hablando? ¡Nadie va a alimentar a la chusma en las calles! Si los Seguidores obtienen el control sobre la comida y el agua, obtienen el poder completo de toda la ciudad. A cambio de comida, los locales están dispuestos a hacer cualquier trabajo, y necesitamos mano de obra barata.}
{406}{}{¿Poder? Qué perogrullada.}
{407}{}{¡Qué mente tan estrecha! El poder es sólo un mecanismo. Cuando creamos el Culto del Fuego, no había poder en esta ciudad. Y había patéticos primates, peleando entre ellos por una rata muerta. Y mira la ciudad ahora. Con nuestra ayuda, la electricidad y la moneda volvieron aquí, la industria y la educación nacieron, ¡incluso aparecieron las apuestas! Y todo gracias a la mano dura de la secta que enderezó a los simios locales.}
{408}{}{[Ciencia 100] ¿Estás seguro de que la sociedad está lista para tales cambios?}
{409}{}{He estado pensando mucho en ello...}
