{100}{}{Ves la computadora del laboratorio.}
{101}{}{Ves una computadora del laboratorio, valdrá la pena investigar sus contenidos.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}

{210}{}{Copiar datos geográficos.}
{211}{}{Se han copiado los datos geográficos a la sección de mapas de su Pip-Boy.}

{220}{}{Información acerca del Refugio 25}
{221}{}{Número del Refugio: 25. Inicio de construcción: Marzo, 2064. Finalizada: Enero, 2068. Contratista: Vault-Tec. Propósito: Proteger a civiles en caso de un ataque nuclear. Capacidad: 450 habitantes. Duración del aislamiento: 15 años.}
{222}{}{Historia del Refugio 25}
{223}{}{En el año 2077, durante la Gran Guerra, se abrió el refugio ante los ciudadanos de Fénix. Sin embargo, la proximidad y lo repentino de los ataques nucleares obligaron a los trabajadores a sellar la puerta antes de tiempo, permitiendo entrar sólo al 12% de los residentes previstos.}
{224}{}{Siguiente}
{225}{}{El exceso de espacio y recursos permitió a los habitantes llevar una vida despreocupada sin tener que salir a la superficie. El refugio fue abierto y colonizado durante la expedición de Ulysses Grant durante el año 2162.}
{226}{}{Características de los habitantes}
{227}{}{Los moradores del refugio gozaba de una salud física excelente pero una baja resistencia corporal, por lo que no eran adecuados para el trabajo duro. La salud mental era generalmente buena, aunque muchos tenían fobias acerca del mundo exterior.}

{230}{}{Experimentos Médicos}
{231}{}{Los Seguidores del Fuego están llevando a cabo varios experimentos médicos gracias al equipo del refugio, pues está bien conservado.}
{232}{}{Proyectos en Desarrollo}
{233}{}{Incremento de la resistencia a la radiación, incremento en la efectividad de combate de los guardias por medios químicos, cura para la 'enfermedad del yermo'.}
{234}{}{Proyectos Suspendidos}
{235}{}{Vacunas estándar de Med-Tec (debido a la falta de materia prima), control mental a distancia (falta de equipamiento).}

{240}{}{Proyecto de Alimentos Asequibles}
{241}{}{Los Seguidores del Fuego investigan cómo resolver la escasez de alimentos en Fénix. Esto incluye experimentos en plantas (transferidos a Casa Nueva), hongos y granjas microbiológicas, la producción de nuevos procesadores de alimentos en Two-Sun, e investigación sobre la tecnología del GECK.}
{242}{}{¿GECK? ¿Qué es eso?}
{243}{}{El Kit de Creación del Jardín del Edén - es una antigua tecnología para restaurar la tierra tras una guerra nuclear. Bajo las condiciones del laboratorio del Refugio 25, la tecnología es demasiado complicada como para replicarla. Los Seguidores han enviado expediciones en busca de un GECK operativo.}
{244}{}{Expedición al Refugio 26}
{245}{}{El Refugio 26 fue destruido a causa de un ataque nuclear, el GECK no sobrevivió.}
{246}{}{Expedición al Refugio 27}
{247}{}{Se encuentra en proceso de excavación bajo el mando de Arthur Carrington. Se adjuntan las coordenadas del Refugio. No se ha confirmado la presencia del GECK dentro del refugio.}

{250}{}{Proyecto: Bomba Nuclear.}
{251}{}{Se está construyendo una bomba de uranio utilizando los materiales de Flagstaff, se le bautizó como la 'Bebé Fénix'. Encargado: Profesor Zack Zimmer. La bomba se encuentra un 92% completa.}
{252}{}{Desactivar el campo de fuerza en la sección de la bomba nuclear.}
{253}{}{Campo de fuerza desactivado.}

{260}{}{Informes de cargamentos de uranio y esclavos}
{261}{}{(Este informe trimestral describe el uranio de Flagstaff y los esclavos de la región. En parte son utilizados por la secta y en parte enviados al sur hacia Two-Sun.)}
{262}{}{Busca información acerca de esclavos que provengan de la Villa.}
{263}{}{(Por desgracia, descubres que varios prisioneros de la Villa ya fueron enviados a Two-Sun)}
