{100}{}{Ves la computadora del Asesor.}
{101}{}{Ves una computadora muy poderosa con una ranura para una tarjeta de acceso.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}

{210}{}{Apagar la alarma.}
{211}{}{La alarma se apagado.}
{212}{}{Deshabilitar las trampas del pasillo.}
{213}{}{Las trampas se han desactivado.}

{220}{}{Sabotaje en Flagstaff}
{221}{}{(Los agentes de Flagstaff han informado de sabotaje en la mina de uranio. Se asume que los culpables son prisioneros. Deberíamos reconsiderar nuestras políticas respecto a la colonia y los métodos del Sr. Faber.)}

{230}{}{Un viejo informe del golpe de estado en Fénix}
{231}{}{(El Asesor detalla el golpe de estado en Fénix de hace unos años. Los registros indican que una tercer partido instaló al Culto del Fuego en la ciudad, colocando a sus propios agentes al mando. La meta de tal organización trata de crear una sociedad capaz de fabricar materia prima, una base de reconstrucción, y para suministrar al cuartel general con recursos básicos. Por lo tanto, el Culto no es más que un peón en el juego de alguien más.)}
{232}{}{Informe financiero}
{233}{}{Gracias a nuestros esfuerzos sistemáticos, hemos introducido una nueva moneda gracias al Eje: las chapas de botella se han establecido firmemente dentro de Fénix. Dado que sus habitantes no estaban acostumbrados a una divisa, se necesitaron unos años para inculcar el concepto y estabilizar el valor de una chapa. Se encuentran adjuntas una variedad de estadísticas y análisis de los procesos financieros en la ciudad, junto con futuros planes para las chapas.}

{240}{}{Informe del estado del Culto}
{241}{}{...Conclusión 1: Como era de esperarse, el Culto del Fuego, quienes siguen el modelo de los Niños de la Catedral, ha tenido buenos resultados. Controla casi cada aspecto de la vida en esta ciudad y ha consolidado su posición. La población de Fénix es leal a los Seguidores, o les temen. Por lo tanto, podemos manipular flexiblemente a la sociedad local usando a los Seguidores del Fuego. Mientras que los rebeldes del alcantarillado nos causan problemas, no representan ninguna amenaza a nuestro plan.}
{242}{}{Siguiente}
{243}{}{Conclusión 2: Nos hemos mantenido en incógnito y limitados a un círculo pequeño de individuos selectos. El líder del culto sigue nuestras ordenes sin resistencia alguna, a pesar de sus ambiciones personales. Es un peón, esto lo tiene claro y lo acepta pero desconoce de nuestros futuros planes. Esperamos mantener esta relación por unos 3 o 4 años, después de eso, puede que sea beneficioso reemplazar a Aaron.}
{244}{}{Siguiente}
{245}{}{Conclusión 3: Pienso que el culto está listo para su expansión. Empezaremos a predicar las creencias del Fuego Santo en San Brahmán y así establecer una colonia que nos proveerá de materia prima y transporte.}

{250}{}{Respecto a la búsqueda del GECK}
{251}{}{Aún no tenemos información acerca de un Kit de Creación del Jardín del Edén en buen estado; la búsqueda continua. Se encuentran adjuntos los informes de las expediciones.}
{252}{}{Expedición al Refugio 26}
{253}{}{La expedición al Refugio 26 fue un fracaso. El refugio fue destruido durante el bombardeo nuclear, lo que hizo imposible la excavación.}
{254}{}{Expedición al Refugio 27}
{255}{}{La expedición al Refugio 27 no ha conseguido confirmar la presencia del GECK. Se está ejecutando una excavación a largo plazo. Se ha confirmado que el refugio ya fue saqueado y está en malas condiciones. Se pudo transportar algo de maquinaria a Two-Sun; se encuentra adjunta la lista, junto con unas copias de los informes de la expedición.}
{256}{}{Nota}
{257}{}{Se sabe que la población de Fénix desciende de los habitantes del Refugio 27. También existe una leyenda acerca de una discordia entre sus ancestros, cosa que los llevo por caminos distintos. Una hipótesis afirma que el otro grupo se llevó el GECK. Hay que seguir esta hipótesis si no se encuentra el dispositivo.}
{258}{}{Buscar las coordenadas del Refugio 27}
{259}{}{(Introduces las coordenadas en tu Pip-Boy.)}

{260}{}{Informe del proyecto de la bomba nuclear}
{261}{}{El proyecto se encuentra al 92%. Estamos a la espera de nuevos componentes mecánicos de los talleres en Two-Sun. El progreso se retrasa debido a la falta de personal científico y la lenta producción de la mina de uranio en Flagstaff. Los Seguidores del Fuego todavía desconocen el verdadero propósito y destinatario de la bomba.}
