{102}{}{Has llenado el recipiente con materias primas sintéticas.}

{200}{}{Introduzca el comando.}
{201}{}{Fin de la sesión.}
{202}{}{Comprueba el material sintético restante en el cartucho.}

{210}{}{El cartucho de materia prima sintética está vacío.}
{211}{}{El cartucho de materia prima sintética está al }
{212}{}{% de su capacidad total.}
{213}{}{Fabrica un mono del refugio (utiliza un 25% del material)}
{214}{}{Fabrica una túnica de los Seguidores del Fuego (utiliza un 50% del material)}
{215}{}{Hecho.}
