{100}{}{Ves al General Ranger.}
{101}{}{Ves a un anciano fuerte y canoso quien ha visto la vida con todas sus duras realidades.}
{102}{}{Estoy acostumbrado a hablar con gente real, no con robots. ¿Entendido?}
{103}{}{Adiós, Ranger. Tus ideales demostraron ser... inviables.}
{104}{}{Lo siento, pero esta dama necesita calmarse un poco.}
{105}{}{Me alegra verte con buena salud. Pero no tengo tiempo de hablar ahora, el mal sembrado por la Hermandad aún supura en los yermos.}

#The first dialog
{200}{}{Me han informado de que cierto granjero insistía en reunirse conmigo para tratar un asunto importante. Normalmente, los exploradores y los emisarios se encargan de los contactos externos. Entonces, espero que esto sea realmente algo importante.}
{1200}{}{Me han informado de que cierta granjera insistía en reunirse conmigo para tratar un asunto importante. Normalmente, los exploradores y los emisarios se encargan de los contactos externos. Entonces, espero que esto sea realmente algo importante.}
{201}{}{[Siguiente]}
{202}{}{Entonces, ¿Por qué estás aquí?}
{203}{}{Sabes, ahora me doy cuenta de que no tengo nada que hacer aquí. Esto fue un error. Me iré, y te olvidarás de mí.}
{204}{}{Ese es un chiste absurdo.}
{205}{}{Lo digo en serio. Lamento molestarte.}
{206}{}{Sabes, tengo muchas preguntas que hacerte..}

#Re-dialogue
{210}{}{Te escucho.}
{211}{}{Adiós.}
{212}{}{Santo cielo, a juzgar por tu apariencia, has sufrido mucho en el despiadado yermo. Lo siento mucho.}
{213}{}{Gracias por sus palabras, General. La mayoría de la gente sólo me echarían.}
{214}{}{No necesito tu compasión. Mírate, anciano.}
{215}{}{Informe, Ranger.}

#Family of a criminal
{220}{}{Una mujer enojada exigía verte.}
{221}{}{Sí. Me lo dijeron. Simpatizo con personas así, más de lo que podrías esperar, pero ya no puede hacerse nada. Siempre se ha marcado a las familias de los delincuentes, incluso en el Viejo Mundo.}
{222}{}{Debe haber alguna forma de lidiar con esto.}
{223}{}{Nada va a cambiar aunque intervenga. Esa mujer siempre odiará a los Rangers, no importa cuánto bien le hagamos. Y en los asentamientos vecinos, los lugareños no la dejarán en paz si se enteran del pasado oscuro de su esposo.}
{224}{}{Sigue.}
{225}{}{Planteas un punto interesante.}
{226}{}{Me temo que la única opción para esta familia es abandonar Sonora y dirigirse a California, donde podrán empezar de nuevo.}
{227}{}{Intentaré que acepte la idea.}
{228}{}{Quizás no sea mala idea.}

#Lone Ranger in Flagstaff
{230}{}{¿Qué está haciendo el ranger Kuyuk en Flagstaff?}
{231}{}{(suspira) Es nuestro problema con patas, y lleva un rifle. El cuartel general estaba en contra del sabotaje en Flagstaff, pero las ambiciones personales de un ranger terminaron siendo más fuertes que nuestras regulaciones. Es difícil echarle la culpa por eso.}
{232}{}{¿Le estás poniendo excusas?}
{233}{}{Kuyuk sufrió un destino difícil debido a la esclavitud de su pueblo. Parece que encontró una forma de vengarse por su pasado en Flagstaff. Lo dejamos ir para que pudiera encontrar el sentido a su vida y encontrar la paz.}
{234}{}{¿Entonces lo sacarás de allí?}
{235}{}{¿Herir a uno de nuestros mejores tiradores? Debe haber una muy buena razón para esto.}
{236}{}{Creo que tiene razón, General. No deberías sacarlo de allí hasta que él quiera.}
{237}{}{¡No puedo creer esto! ¿Es eso lo que piensa, General? Suficiente, me voy.}
{238}{}{Se está vengando de todo el mundo. Sus acciones perjudican a los pacíficos colonos.}
{239}{}{No me importan sus problemas. Sólo sáquelo de allí.}
{240}{}{Eso cambia las cosas. Parece que llevó las cosas demasiado lejos.}
{241}{}{Eres un general. No desobedecerá tus órdenes.}
{242}{}{Es lo más probable. Por favor, dale órdenes de volver a la base si llegas a estar cerca. Mantiene el silencio en la radio y por alguna razón evita a los demás Rangers.}
{243}{}{¡Bien!}
{244}{}{Sólo si llego a estar cerca.}

#Union Villas
{250}{}{Tenemos tiempos difíciles en mi villa natal. Necesitamos la ayuda de los Rangers.}
{251}{}{Tiempos difíciles... Podría decirse eso para casi cada asentamiento en Arizona y California. Pero, a diferencia de una persona común y corriente, nosotros sí tenemos la oportunidad de luchar por los derechos de los habitantes del yermo.}
{252}{}{[Más]}
{253}{}{Mantener el orden requiere una seria inversión en la formación ranger, equipar a nuestros escuadrones y patrullas, además de reconocer el terreno y llevar a cabo operaciones de combate. No todo el mundo puede invertir en una alianza así, pero intentamos responder a todos.}
{254}{}{Creo que la Villa no tendrá ningún problema con proporcionarte comida y alfarería.}
{255}{}{Sabes, la verdad no tenemos nada que ofrecerte. Parece que esta alianza no va a durar.}
{256}{}{¿Así que pides un pago para tu protección?}
{257}{}{Por supuesto. Es una especie de impuesto de seguridad, una práctica normal en el Viejo Mundo.}
{258}{}{¿Y si la población no tiene nada con lo que pagar los impuestos?}
{259}{}{Sabemos como beneficiarnos de cualquier cooperación. Algunos pueden construir casas, otros pueden cultivar cosechas, y otros son buenos cadetes. Con el enfoque adecuado, cualquiera puede llegar a ser útil a la sociedad.}

{260}{}{La Villa... Los rangers siempre hemos respetado su independencia. Pero siempre se han mantenido alejados del resto del mundo. Cuando necesitábamos comida durante los años de la hambruna, ustedes nos echaron. Ahora nos piden ayuda. Dime, ¿Quién te envió a hablar con nosotros?}
{261}{}{El consejo de la comunidad decidió que es la hora de formar una alianza con ustedes.}
{262}{}{Nadie. Muchos de los habitantes de la Villa fueron tomados como esclavos y llevados a Flagstaff.}
{263}{}{Nadie. Muchos de los habitantes de la Villa fueron tomados como esclavos y llevados a otra ciudad.}
{264}{}{Estoy aquí sin el consentimiento de la comunidad.}

{270}{}{Ya veo... Bueno, una alianza con la Villa sería muy conveniente, pues necesitamos comida más que nunca. Pero estoy preocupado de que el orgullo de tu gente cause problemas con nuestras tropas.}
{271}{}{Eso es difícil de discutir. Aún así, ¿está listo para ayudarnos?}
{272}{}{No podrían importarme menos tus tropas. Mi única preocupación es salvar la Villa.}
{273}{}{Me temo que este no es el mejor momento. Nos enfrentamos a grandes problemas en el sureste, y hemos comprometido todas nuestras fuerzas en esa dirección.}
{274}{}{Una de mis aficiones es resolver problemas, General.}
{275}{}{Habla con el Comandante Helford. Podría asignar gente a una guarnición en la Villa. En ese entonces podremos discutir los términos de la alianza... si tu comunidad realmente lo desea.}
{276}{}{Gracias, General. Hablaré con Helford.}
{277}{}{No tan rápido. Recuerda, tendrás que actuar como un emisario a tu gente. Debes convencerlos de nuestra buena voluntad y la necesidad de esta alianza.}
{278}{}{Entendido.}
{279}{}{Prometiste ayudar. Algunos de los habitantes de la Villa siguen esclavizados.}

{280}{}{El Comandante Helford aceptó a proteger la Villa.}
{281}{}{(asiente pensativo, ensimismado por un momento) Los tiempos están cambiando...}
{282}{}{Eh, ¿Qué?}
{283}{}{[Escucha]}
{284}{}{Los habitantes de la Villa solían rechazar a los forasteros y echar a los rangers. Pero los tiempos están cambiando, tú también, te guste o no. Creo que es la hora de dejar a un lado nuestros viejos rencores.}
{285}{}{Entonces, ¿Estás listo para una alianza?}
{286}{}{Daré la orden al Comandante Helford para enviar una guarnición a tu valle. Discute los detalles con él. Recuerda, serás nuestra voz entre tu gente. Una vez que tu comunidad esté lista, sellaremos la alianza oficialmente.}
{287}{}{Gracias, General.}
{288}{}{Algunos de los nuestros todavía son esclavos en otra ciudad.}
{289}{}{¿Te refieres a las minas de Flagstaff? Sabemos de la situación y estamos trabajando en ello. Intentaremos comprar a algunos de los tuyos. Los de tu tribu pronto estarán en casa.}
{290}{}{¿Cómo sabes tanto de nosotros?}
{291}{}{Reunimos información sobre cada asentamiento del yermo. Es parte de nuestro trabajo. Además, tu líder vino a hablarnos una vez... ¿Cómo se llamaba? Ander... No, Andrés Tejada.}
{292}{}{¡Ese es mi padre! No tenía idea de que había viajado tan lejos de la Villa.}
{1292}{}{¡Ese es mi padre! No tenía de que había viajado tan lejos.}
{293}{}{Sí. Desafortunadamente, esas charlas no llevaron a nada..}

{294}{}{La Villa está lista para nuestra alianza.}
{295}{}{Excelente. Desde hoy, oficialmente tenemos una alianza. Regresa a la Villa y celebra con los tuyos.}
{296}{}{Lo haré.}
{297}{}{Primero termina con tu misión. Luego hablaremos.}
{298}{}{Entendido.}

#Jackals
{300}{}{Hablemos sobre los Chacales.}
{301}{}{Los Chacales son como una piedra en el zapato para estas tierras. ¿Qué quieres hablar exactamente?}
{302}{}{Conozco la ubicación de su base principal. Y pude explorarla desde adentro.}
{303}{}{Una afirmación audaz. Nadie ha encontrado ese lugar y vivido para contarlo.}
{304}{}{¿Qué hay del ranger que fue rescatado?}
{305}{}{¿Así que ese fuiste tú? Bueno, con este incidente se demostró la falta de experiencia del ranger Jason, se perdió mientras regresaba y caminó por el desierto hasta que se topó con uno de nuestros puestos avanzados que abandonamos. Nunca conseguimos las coordenadas exactas, y buscar toda esa peligrosa área por sus escondites era demasiado.}
{306}{}{Así que incluso un ranger prioriza su supervivencia...}
{307}{}{Confía en mí, soy el único que sabe.}
{308}{}{Está bien, ¿Dónde está la base?}
{309}{}{En la frontera de los desiertos del Mojave y Sonora, al noreste de la Villa.}
{310}{}{Necesito revisar el mapa. Dame un momento.}
{311}{}{Sí, parece que es correcto. Tendremos que enviar una misión de reconocimiento allí. Y si encontramos la base... Acabaremos con ellos.}
{312}{}{Es un buen plan. Esos Chacales no merecen su lugar bajo el sol. ¡Acaben con todos!}
{313}{}{Bien. Necesitaremos un guía para esta operación. Tu participación te permitirá reclamar trofeos. ¿Nos ayudarás?}
{1313}{}{Bien. Necesitaremos una guía para esta operación. Tu participación te permitirá reclamar trofeos. ¿Nos ayudarás?}
{314}{}{Sí.}
{315}{}{No.}
{316}{}{¿Entonces tendré que... matar?}
{317}{}{Me gusta tu actitud. Un equipo de asalto te estará esperando en el lugar que indicaste. Dirígete allí inmediatamente.}
{1317}{}{Me gusta tu actitud. Un equipo de asalto te estará esperando en el lugar que indicaste. Dirígete allí inmediatamente.}
{318}{}{El recorrido no es fácil. ¿Me lo podrías facilitar?}
{319}{}{¡Lo haré, General!}
{320}{}{Habla con las patrullas. Te llevarán con ellos.}
{321}{}{Es triste saber eso. Bueno, como es normal, nos ocuparemos de ello. Gracias por la información, puedes irte.}
{322}{}{¡Cambié de opinión! Déjame unirme al asalto.}
{1322}{}{¡Cambié de opinión! Déjame unirme al asalto.}
{323}{}{Adiós.}
{324}{}{Puedes no hacer nada y mirar... Mirar como tus salvadores y protectores son asesinados. O puedes agarrar un arma y ayudarlos. Entonces, ¿Ayudarás?}
{1324}{}{Puedes no hacer nada y mirar... Mirar como tus salvadores y protectores son asesinados. O puedes agarrar un arma y ayudarlos. Entonces, ¿Ayudarás?}
{325}{}{Bueno, ya sabes qué hacer.}
{326}{}{Bien. Nos ocuparemos de ello nosotros mismos. Gracias por la información.}
{327}{}{Me alegra ser de ayuda.}
{1327}{}{Me alegra ser de ayuda.}

{330}{}{No te precipites. Los Chacales podrían aliarse con forasteros si eso resuelve su hambre.}
{331}{}{¿De qué estás hablando? Esos salvajes han dejado secos tanto a los rangers como a los demás asentamientos. ¡No se puede hablar con ellos!}
{332}{}{Creo que vale la pena intentarlo. Son agresivos porque se están muriendo de hambre.}
{333}{}{Hmm. Entonces, dime, ¿Cuál será la ventaja de aliarse con caníbales salvajes?}
{334}{}{Están dispersos por el yermo. Destruir su base principal sólo enojará al resto de los clanes. Esta disputa podría prolongarse durante generaciones.}
{335}{}{La idea de una guerra contra ellos no me asusta, sólo me irrita. Intentaremos hablar con ellos. Tal vez eso una y pacifique a los clanes Chacal. Gracias por la información. Puedes retirarte.}
{336}{}{Encantado de ayudarle, General. Regresaré con los Chacales y los prepararé para las negociaciones.}
{1336}{}{Encantada de ayudarle, General. Regresaré con los Chacales y los prepararé para las negociaciones.}
{337}{}{La última vez intentaron matarme y comerme. Dudo que pueda negociar con ellos de nuevo.}
{338}{}{Olvídalo. Esos Chacales no merecen su lugar en el mundo. ¡Aniquílenlos!}

{340}{}{Deseo denunciar los crímenes del ranger Garth.}
{341}{}{¿El ranger en el Acueducto? Lo estacionamos allí para mantener el orden. ¿Qué delitos ha cometido?}
{342}{}{Ha asesinado a varios refugiados, desconfiando de los forasteros, y desechó sus cuerpos en los túneles del acueducto.}
{343}{}{¿Tienes pruebas de esto? Tenemos un gran juicio delante de nosotros. Pondremos a Garth en custodia. Gracias por la información... aunque estas noticias me suponen un gran peso, especialmente en tiempos tan difíciles.}
{344}{}{Sí, lo entiendo... Adiós, General.}

#Ranger Title
{350}{}{Quiero unirme a los Rangers.}
{351}{}{Es encomendable de tu parte. Pero el título de ranger debe ganarse. Muchos cadetes pasan años entrenando y llevando a cabo misiones para ganarse la placa. ¿Con qué méritos cuentas?}
{352}{}{No creo tener mucho que demostrar.}
{353}{}{Como sospechaba. Únete al cuerpo de cadetes y sirve unos años en nuestras filas.}
{354}{}{Lo pensaré.}
{355}{}{¿Le importa si tomo un poco más de su tiempo, General?}
{356}{}{¿Hay alguna forma más rápida?}
{357}{}{Hmm. Habla con el Comandante Helford. Ha estado buscando a reclutas para misiones especiales.}
{358}{}{Lo pensaré.}
{359}{}{Una afirmación audaz, pero no es suficiente para ser un ranger.}
{360}{}{Erradiqué a la tribu Chacal.}
{1360}{}{Erradiqué a la tribu Chacal.}
{361}{}{Ayudé a formar una alianza con los Chacales.}
{362}{}{Gracias a mí, ya no hay trata de esclavos en Flagstaff.}
{363}{}{Liberé a los esclavos en Flagstaff.}
{1363}{}{Liberé a los esclavos en Flagstaff.}
{364}{}{He resuelto el conflicto en San Brahmán a favor de los rangers.}
{365}{}{He desmantelado a la Catedral del Fuego en Fénix.}
{1365}{}{Eliminé a la Catedral del Fuego en Fénix.}
{366}{}{Eliminé a la Hermandad del Acero.}
{1366}{}{He desmantelado a la Hermandad del Acero.}
{367}{}{Detuve la expansión de los Hojalateros.}
{368}{}{Con mi ayuda, el Partido de la Liberación derrocó a Aaron.}
{369}{}{[TRAMPA: Merezco este título, General.]}
{370}{}{Esta lista es impresionante. Déjame comprobar el informe de tus actividades... Sí, nuestro equipo de inteligencia está siguiendo a algunos individuos "notables". No te preocupes, es un procedimiento rutinario.}
{371}{}{Hmm. Está bien...}
{372}{}{Tu reputación en el yermo no concuerda del todo con tus hazañas. Muchos te ven como poco digno de confianza.}
{373}{}{Ya sabes cómo va eso. No se puede complacer a todo el mundo.}
{374}{}{¿Acaso los rangers hacen caso a las palabras de los mendigos? No me hagas reír.}
{375}{}{Algunos rangers tienen una opinión negativa sobre ti. No es una ofensa mayor, pero a veces es sabio escuchar.}
{376}{}{Con el tiempo, entrarán en razón.}
{377}{}{Tengo mis problemas con algunos rangers también. Pero no voy corriendo a llorar con el General.}
{378}{}{ay rumores de tus lazos con los Escudos Azules. A veces es mejor mantenerse alejado de los forajidos.}
{379}{}{No son forajidos, confíe en mí, general.}
{380}{}{¿Quién es el malo aquí? Deja que me lo digan en la cara, porque yo no soy el que anda contando rumores.}
{1380}{}{¿Quién es el malo aquí? Deja que me lo digan en la cara, porque yo no soy la que anda contando rumores.}
{381}{}{Dicen que eres parte de los Seguidores del Fuego. No es algo muy digno.}
{382}{}{A los rangers les vendría bien un agente interno.}
{383}{}{Es lamentable que no estés de acuerdo con nuestra fe. Deberías arrepentirte ante el Fuego Santo.}
{384}{}{Dice aquí que estás involucrado con una organización sospechosa llamado la Hermandad del Acero.}
{385}{}{Así es. En aquel momento, parecía una buena idea. Pero ya no.}
{386}{}{Así es. Los rangers deberían tratar a esa "organización" con su debido respeto.}
{387}{}{Con tales recomendaciones, no puedo aceptarte en nuestras filas. Necesitas ganarte más confianza.}
{388}{}{No hay problema, General. Mi confianza se mantiene intacta.}
{389}{}{Caramba, después de esto, ni siquiera quiero volver aquí.}
{390}{}{Hmm. Estos son casos excepcionales. Sólo unos pocos se han ganado su placa sin años de duro entrenamiento. Pero estoy dispuesto a iniciarte en los Rangers.}
{391}{}{Entonces, ¿Puedo recibir una placa?}
{392}{}{Es normal. Siempre consigo lo que me propongo.}
{393}{}{¿Estás listo para soportar esta carga? Jura defender la Ley y el Orden y honrar a los Rangers.}
{1393}{}{¿Estás lista para soportar esta carga? Jura defender la Ley y el Orden y honrar a los Rangers.}
{394}{}{¡Lo juro!}
{395}{}{Excelente. Lleva tu placa con orgullo. Habla con el intendente para tu retirar tu equipo inicial. Voy a preparar el papeleo para su inscripción.}
{396}{}{¡Gracias, General!}

#Questions
{400}{}{¿Puedo hacerte algunas preguntas?}
{401}{}{Que sea rápido. Tengo poco tiempo para charlar.}
{402}{}{Tienes razón, suficiente charla.}
{403}{}{Permíteme una pregunta más.}

{410}{}{¿Cómo te hiciste un ranger?}
{411}{}{Superé todos los hitos y ascendí al rango de General gracias a un esfuerzo honesto.}
{412}{}{Tuviste que haber viajado mucho, ¿No?}
{413}{}{Así es, he estado en muchas partes del suroeste, incluyendo Los Ángeles, Las Vegas, y Fénix. Los mismos problemas en todos lados, hambre, devastación y un desierto interminable.}

{420}{}{¿Podrías hablarme de este lugar?}
{421}{}{Esta es la principal base de los rangers en Arizona. La central eléctrica es nuestra ciudadela, la presa nuestra fortaleza. Afuera, encontrarás el centro de información y el área de entrenamiento.}
{422}{}{¿Hay otras bases?}
{423}{}{Sí. Hay varios fuertes grandes como éste en Nevada y California. Seguimos en contacto, pero cada uno tiene sus propias normas y principios.}
{424}{}{¿Cuál es la misión de los rangers?}
{425}{}{Traemos la Ley y el Orden a este caótico mundo. Empezamos protegiendo los asentamientos y las rutas de caravanas de bandidos y mutantes. Pero eso es sólo el principio.}
{426}{}{[Más]}
{427}{}{Los residentes que se unen a nosotros deben aceptar la Ley, pagar impuestos, y contribuir a través de trabajo útil como la agricultura o la cacería..}
{428}{}{¿Por qué pusieron una presa en el Colorado?}
{429}{}{(suspira burlonamente) La presa ha estado aquí por mucho tiempo. Utiliza la presión del agua para generar electricidad... asumo que sabes qué es eso. Acabamos de repararla y la convertimos en un fuerte para resguardarnos ante nuestros enemigos y los elementos.}
{430}{}{Pero has asegurado el único cruce del Colorado en kilómetros.}
{431}{}{Los puestos de control mantienen la presa y la central eléctrica a salvo de plebeyos irreflexivos. Este equipamiento único es fundamental para nosotros y las tierras de alrededor. Hay un ferry río abajo con precios razonables para cruzar.}
{432}{}{¿De qué Ley estás hablando, General?}
{433}{}{Verdades sencillas para una sociedad próspera. No mates a no ser sea necesario. No tomes lo que no es tuyo. Actúa por el bien de tu comunidad. Esas son las reglas básicas. Desafortunadamente, muchos en el yermo no saben leer, así que tenemos que explicarlo en términos más simples.}
{434}{}{Las relaciones humanas son mucho más importante que las leyes.}
{435}{}{(da un cansado suspiro) Como decían en el Viejo Mundo, la ley es dura, pero es la ley. Las personas no podrían idear nada mejor para la autoorganización y la disciplina. Rechazar la Ley conduce al caos, y lo hemos aprendido bien en los últimos cien años.}
{436}{}{Mencionaste al Viejo Mundo, pero ha estado en ruinas desde hace años.}
{437}{}{Correcto. El Apocalipsis Nuclear fue el resultado de la arrogancia e insensatez. Ahora nosotros pagamos el precio. Pero todos cometen errores. Lo importante son las lecciones que podemos aprender de ellos.}
{438}{}{Sólo quería que supieras que las cosas están avanzando. Sólo queda negociar con el líder. Me pondré a ello pronto.}

#Holodisk of Ulysses Grant
{450}{}{Quizás te interese este informe de la Catedral.}
{451}{}{¿De la Catedral del Fuego Santo en Fénix? Intrigante. ¿Dónde conseguiste este holodisco?}
{452}{}{Conseguí ganarme al Consejero. Me encargó que entregara este informe en la base militar de Puerto Peñasco.}
{453}{}{Esta información es un poco antigua, pero agradezco tu ayuda.}
{454}{}{De nada.}
{455}{}{Vaya, vaya. Bastante interesante. Llevamos tiempo vigilando esta base y sabíamos que la Catedral estaba implicada. Este informe secreto arroja algo de luz... ¿Por qué nos lo das?}
{456}{}{Sólo digamos que estoy... desilusionado con los mandamientos del Fuego Santo.}
{1456}{}{Sólo digamos que estoy... desilusionada con los mandamientos del Fuego Santo.}
{457}{}{Tengo una venganza personal contra este Consejo. Apoyaron a los esclavistas que capturaron a mi familia.}
{458}{}{Eso suena convincente. Gracias por tu ayuda; esta información podría ser muy valiosa.}
{459}{}{De nada..}

#San Brahmin - Quest
{460}{}{Ah, sí. Espero que no sea muy tarde para la alianza. Son tiempos difíciles, y necesitaremos todo el apoyo posible. Pero hasta que tu comunidad se estabilice y recoja una nueva cosecha, la situación puede cambiar.}
{461}{}{¿A qué te refieres?}
{462}{}{Esta tragedia sólo ha afectado a tu pequeña y pacífica comunidad. La verdadera amenaza se cierne sobre el sur de Arizona. Los Rangers ya están luchando para recuperar San Brahmán de los invasores.}
{463}{}{No queríamos involucrarnos en una guerra.}
{464}{}{Por mucho que intenten permanecer aislados, el mundo ya sabe sobre la Villa. Si cae San Brahmán, tu pacífica comunidad podría ser la siguiente.}
{465}{}{Maldición, debemos hacer algo.}
{466}{}{Necesito pedirte un favor mientras nos ocupamos de la Villa. Lleva mis instrucciones al Agente Óscar en San Brahmán. Está ayudando a la resistencia local. consideralo parte de nuestro trato.}
{467}{}{El trabajo parece sencillo. ¿Permiso para ir, General?}
{468}{}{Parece que tendré que ocuparme de esto antes de que la amenaza llegue a la Villa. Nos vemos, General.}
{469}{}{Te escucho atentamente. ¿Cuáles son las noticias de San Brahmán?}

{470}{}{Necesito hablarte acerca de la situación en San Brahmán.}
{471}{}{Aún no he podido entregar tus instrucciones.}
{472}{}{Entonces apresúrate. Entre más nos tardemos, más fuerte se hace el enemigo.}
{473}{}{Entendido, General.}
{474}{}{[TRAMPA: ¡Ya está hecho!]}
{475}{}{Los misioneros han dejado San Brahmán. Es una buena noticia. Pero no debemos olvidar que pueden volver. Perdimos una gran oportunidad de aliarnos con el jefe tribal. El momento ha pasado.}
{476}{}{[Más]}
{477}{}{Hmm. Esto era lo que más temía. Un destacamento de misioneros fue a San Brahmán bajo las órdenes de Fénix. Parece que las ambiciones imperiales de Aaron no eran meras fantasías.}
{478}{}{¿Cómo podríamos detener a este "señor" de Fénix?}
{479}{}{No será fácil. Pero hay un grupo de rebeldes en Fénix que también luchan en contra de Aaron y su iglesia. Intenta contactar con ellos y ofrecerles nuestra ayuda. Te lo estoy pidiendo porque los Rangers tienen dificultades en entornos urbanos densamente poblados.}
{480}{}{¿Podrías elaborar sobre el propósito de mi misión?}
{481}{}{Hemos tenido que participar en varios conflictos locales para evitar la propagación de la "peste roja" de Fénix. La situación es crítica y necesita una solución urgente.}
{482}{}{[Más]}
{483}{}{Ve a San Brahmán y encuentra al Ranger Óscar. Está coordinando a los lugareños para que peleen contra los invasores. Llévale el informe y ayúdale como sea necesario para resolver el conflicto.}
{484}{}{Entendido, General.}
{1484}{}{Entendido, General.}
{485}{}{Parece que se me está arrastrando a tu guerra. Espero que valga la pena.}
{486}{}{¿Sólo llevarle el informe? Suena muy simple.}
{487}{}{El Ranger Óscar murió defendiendo la libertad de la tribu.}
{488}{}{Son tristes noticias, pero él sabía de los riesgos. Recordaremos a Óscar como un héroe.}
{489}{}{Lo siento mucho.}
{490}{}{El Ranger Óscar escapó de San Brahmán. La situación allí es grave.}
{491}{}{No condeno sus fracasos. Estoy seguro de que Óscar hizo todo lo que pudo.}
{492}{}{Lo siento mucho.}
{493}{}{El Ranger Óscar completó su misión en San Brahmán. La situación allí ha cambiado mucho.}
{494}{}{No he escuchado su informe completo todavía. Pero estoy seguro de que ambos tienen mucho que contar.}
{495}{}{Por supuesto.}
{496}{}{Entonces, ¿Cómo terminó todo en San Brahmán? Estoy esperando el informe completo...}
{497}{}{[Informa]}
{498}{}{Excelente trabajo. Gracias a nosotros, la tribu ha ganado su libertad. Esta victoria le enseñará a todos el valor de los rangers. Sin mencionar el necesitado suministro de carne de brahmán.}
{499}{}{[Siguiente]}

#Phoenix - Quest Conclusion
{500}{}{Necesito hablarte acerca de Fénix.}
{501}{}{Te escucho atentamente. ¿Qué noticias tienes?}
{502}{}{Desafortunadamente, sigue igual.}
{503}{}{¿Cómo podría encontrar a esos rebeldes que mencionaste?}
{504}{}{Por lo que sé, se esconden en los túneles subterráneos y utilizan transmisiones de radio encriptadas. También podrías preguntar por ahí; seguro que algunos lugareños les apoyan. Pero ten cuidado de a quién le preguntas.}
{505}{}{Gracias, puede que esto ayude.}
{506}{}{¿Por qué es tan importante deshacerse de Aaron y su iglesia?}
{507}{}{El culto es simplemente una marioneta en las manos de Aaron, el gobernador local. Pretende construir un imperio, llevando a cabo una política de conquista y eliminando físicamente a los disidentes.}
{508}{}{[Siguiente]}
{509}{}{Entonces necesito encontrar a esos rebeldes pronto. ¿Cómo puedo hacer eso?}
{510}{}{Pero, ¿Por qué es tan importante deshacerse de la Catedral del Fuego en Fénix?}
{511}{}{La Catedral del Fuego Santo ha sido destruida.}
{512}{}{(suspira aliviado) ¡Excelente trabajo! Al menos hay un enemigo menos del que preocuparse.}
{513}{}{[Más]}
{514}{}{Hiciste lo correcto al tomar medidas drásticas. Quién sabe qué secretos guardaba ese templo y cuántos problemas podrían haber causado a nuestro ya frágil mundo.}
{1514}{}{Hiciste lo correcto al tomar medidas drásticas. Quién sabe qué secretos guardaban las cámaras del templo y qué desastres podrían haber causado a nuestro ya frágil mundo.}
{515}{}{[Más]}
{516}{}{Pero un desafío más difícil está por venir. Mientras descansas, necesito reunir a los comandantes de campo. Reúnete conmigo en la sala de reuniones; tienes que estar allí también.}
{517}{}{Me pasaré por allí después, General.}
{518}{}{Aaron, el Señor de Fénix, está muerto.}
{519}{}{(suspira aliviado) Escuché las noticias. Un trabajo excepcional. Un tirano menos del que preocuparse.}
{520}{}{[Más]}
{521}{}{Sin su líder, la ciudad se sumirá en el caos. Los gobernantes de Aaron empezarán a luchar entre sí por el poder, los civiles "recordarán" viejos rencores contra la iglesia y los rebeldes podrán actuar de forma más abierta y decidida. Serán tiempos difíciles, pero al final conducirán a un futuro mejor para Fénix.}
{522}{}{[Más]}
{523}{}{Aaron era responsable por el resurgimiento de la esclavitud, tecnología dañina previa a la Guerra, y las drogas en Arizona. Nuestro mundo es demasiado frágil para que tales tiranos prosperen.}
{524}{}{Entendido.}
{525}{}{Vaya coincidencia, ¡Ya estuve allí!}
{526}{}{El Partido de la Liberación, liderado por Marcos, asaltó la catedral. El Señor de Fénix está muerto.}

#Dialogue Block
{550}{}{No voy a confiar en una víbora. Prueba que se eres digno de confianza, y hablaremos. Ya sabes donde está la salida.}
{551}{}{Sí, General Mossman, lo sé.}
{552}{}{Está cometiendo un gran error, General. Se arrepentirá de esto.}
{553}{}{Entonces, ¿estás aquí para hacer justicia? Oh no, estás aquí por tus propias razones egoístas..}
{554}{}{¿Por qué me despojaron de mi rango?}
{555}{}{Luchar en dos frentes hace imposible la lealtad. El conflicto es inevitable. Si te pones del lado del colonialista que doblega el sur de Arizona a su voluntad, no tienes sitio entre los Rangers.}
{556}{}{La división entre religión y derecho es demasiado amplia. En un escenario así, el entendimiento es imposible; el conflicto es inevitable. Si eliges el camino cultista, no tienes sitio con los Rangers.}
{557}{}{Claramente, tus acciones no se alinean con los principios de la Ley y el Orden. Puede que los malinterpretes, pero eso no te libera de la responsabilidad. No podemos permitir a alguien como tú llevar la placa de los rangers.}
{558}{}{[Más]}
{559}{}{Vete en paz. Por respeto a tu servicio previo, sólo te despojamos de tu rango. En otras circunstancias, la traición aseguraría tu ejecución.}
{560}{}{Lo entiendo, General. No escuchará de mí otra vez.}
{561}{}{Aprenda a perdonar, General. Lo necesitará algún día.}
{562}{}{Sabemos lo que te traes entre manos. Vete. El centinela te escoltará fuera.}
{563}{}{[Salir del cuarto]}

{570}{}{Esto es una visita muy inesperada. Pensé que tu iglesia despreciaba nuestra hermandad.}
{571}{}{¿No podemos vivir en paz?}
{572}{}{Sólo si construimos barricadas y un mote lleno de desechos radioactivos en la frontera.}
{573}{}{[Más]}
{574}{}{Tu iglesia impone sus retorcidos dogmas a los demás y castiga a quienes discrepan. Tu líder, bajo la bandera de la iglesia, crea un imperio y revive la esclavitud. No tenemos nada que negociar con una víbora. Ve a entregar este mensaje a tu prior. Estas negociaciones han terminado.}
{575}{}{[Salir del cuarto]}
{576}{}{Así que aquí viene un embajador de buena voluntad de la propia Hermandad del Acero. ¿Estás aquí para presentar un armisticio? ¿O tal vez a demandar que nos rindamos}
{577}{}{No sé de que estás hablando. Estoy aquí por mi propia voluntad.}
{578}{}{Quizás. De todas formas, no podemos permitir que estés en nuestra base. El centinela te escoltará afuera.}
{579}{}{[Salir del cuarto]}
{580}{}{Si no negocias con la Hermandad, destruirán tu presa.}
{581}{}{Estas amenazas sólo confirman la hostilidad de la Hermandad del Acero. El ejército fue creado para la guerra, no para crear un nuevo mundo. Tu Hermandad debe aprender a coexistir pacíficamente. Ahora vete, y dile eso a tu general. Estas negociaciones han terminado.}
{582}{}{[Salir del cuarto]}

#Phoenix - Completing the Quest
{590}{}{¿Estamos todos aquí? Empecemos entonces.}
{591}{}{[Más]}
{592}{}{Como ya saben, nuestro nuevo aliado, }
{1592}{}{Como ya saben, nuestra nueva aliada, }
{593}{}{ de la Villa, ha liberado al yermo del tirano Aaron. Nos llegan informes de todo el estado sobre el colapso de su culto. Pronto, esta pelea sólo será un recuerdo.}
{1593}{}{ de la Villa, ha liberado al yermo del tirano Aaron. Nos llegan informes de todo el estado sobre el colapso de su culto. Pronto, esta pelea sólo será un recuerdo.}
{594}{}{[Más]}
{595}{}{Pero esto no es el fin. Como sospechamos, Aaron solo era un peón en un juego mucho más grande. Los Hojalateros le suministraban con armas y equipamiento a cambio de uranio barato.}
{596}{}{[Más]}
{597}{}{Lo que es aún más intrigante es que una misteriosa tercera entidad medió en el acuerdo. Sin ellos, Aaron y los Hojalateros no habrían acordado trabajar juntos, y Aaron nunca habría tomado el poder.}
{598}{}{[Más]}
{599}{}{No sabemos casi nada de esta enigmática organización. Tienen su base en el viejo puerto de Puerto Peñasco y una postura militar agresiva.}
{600}{}{[Más]}
{601}{}{Lo que sí sabemos es que el mineral de uranio de Flagstaff era enviado a los Hojalateros, y las baterías de uranio son mayormente enviadas al puesto avanzado de Puerto.}
{602}{}{[Más]}
{603}{}{En otras palabras, esta organización pretende dominar el sur de Arizona para obtener recursos, utilizando mano de obra barata. Instalan a sus títeres en asentamientos, como en Casa Grande. Incitan revoluciones, como en San Brahmán. Se apoderan de recursos y emplean esclavos para la tarea. Y ni siquiera sabemos quiénes son.}
{604}{}{[Más]}
{605}{}{, ahora sabes que tu Villa está en riesgo. Si este ejército continúa subyugando el sur de Arizona, la Villa, al igual que otros pequeños asentamientos, perderá su libertad. La mejor forma de evitarlo es aliarse con los Rangers y formar un frente unido contra los invasores.}
{606}{}{¿Qué necesitas que haga ahora?}
{607}{}{Ve a Puerto Peñasco e identifica los puntos débiles del enemigo. Nuestros exploradores no han sido capaces de reunir información valiosa - la base militar es demasiado remota y está bien fortificada.}
{608}{}{¿Cómo se supone que voy a hacer eso?}
{609}{}{Eres un campesino. Despertarás menos sospechas. Además, tienes un fuerte motivo - la esclavización de la Villa. Buena suerte.}
{1609}{}{Eres una campesina. Despertarás menos sospechas. Además, tienes un fuerte motivo - la esclavización de la Villa. Buena suerte.}
{610}{}{Permiso para retirarme, General.}
{611}{}{Creo que es una misión suicida. No quiero ser parte de esto, General.}
{612}{}{Piensa en lo que hemos hablado. Quizás sólo tu apoyo no será suficiente para ganar esta guerra.}
{613}{}{Tiene razón, General. Intentaré aprender más de esta misteriosa organización.}
{614}{}{Encuentra a alguien más. Me voy a casa; mi amada Villa me espera, General.}

{620}{}{He conseguido infiltrarme en la base de la Hermandad del Acero.}
{621}{}{Son buenas noticias. ¿Qué has descubierto? ¿Qué debilidades tienen?}
{622}{}{Aún no conozco sus debilidades. Están demasiado bien organizados y están bien resguardados.}
{623}{}{Es una pena. Pero creo que tendrás éxito. Sigue investigando.}
{624}{}{Permiso para retirarme, General.}
{625}{}{¿Podría darme otro momento de su tiempo?}
{626}{}{Su nave está cargada de explosivos. Pero aún no he descubierto como aprovechar eso.}
{627}{}{Brillante. Si encuentras alguna forma de hacer explotar la nave, borrará a la Hermandad del mapa de Arizona. Sus vasallos y puestos más pequeños quedarán indefensos. Inténtalo. Yo creo que puedes hacerlo.}
{628}{}{Sabes, me dejaron ir porque me ofrecieron una misión similar.}
{629}{}{Entonces... ¿Qué has decidido? ¿De qué lado estás?}
{1629}{}{Entonces... ¿Qué has decidido? ¿De qué lado estás?}
{630}{}{Por supuesto que de tu lado, General.}
{631}{}{Entonces utiliza la confianza que has ganado para destruir a nuestro enemigo común.}
{632}{}{Permiso para retirarme, General.}
{633}{}{No puede con ellos, General. Admita su derrota.}
{634}{}{¿Admitir la derrota por un mensaje? Es una pena que las cosas hayan acabado así. Ahora, no puedo dejarte ir hasta que tengamos todas las respuestas. No deberías haber traicionado a los rangers.}
{635}{}{No, General. Me iré de aquí. Y nadie me pondrá un dedo encima.}
{636}{}{Ya no somos aliados. Así que púdrete, viejo. No me asustas.}
{637}{}{He conseguido infiltrarme en la nave de la Hermandad y activar los torpedos. La base está completamente destruida.}
{638}{}{¡No hemos tenido noticias tan buenas en años! Al expulsar a la Hermandad, hemos asegurado nuestra patria para nosotros y nuestros descendientes. ¿Qué podría ser mejor?}
{639}{}{Absolutamente.}
{640}{}{Aún nos queda mucho por hacer para erradicar los restos del mal de la Hermandad. Tu misión está completa. Te sugiero que te hagas un ranger y sirvas en tu ciudad natal, la Villa.}
{641}{}{Gracias, General. Pero quiero mantener mi libertad y de la Villa.}
{642}{}{Bueno, vuelve con tu familia en Villa y comparte las buenas noticias..}
{643}{}{Encantado de servirle, General.}
{1643}{}{Encantada de servirle, General.}
{644}{}{Sería un honor ser parte de los rangers.}
{645}{}{A partir de ahora, eres uno de los nuestros. Mantén la Ley y el Orden en tu patria. Ahora regresa a la Villa e informa a tu familia de las buenas noticias.}
{1645}{}{A partir de ahora, eres una de los nuestros. Mantén la Ley y el Orden en tu patria. Ahora regresa a la Villa e informa a tu familia de las buenas noticias.}
{646}{}{Encantado de servirle, General.}
{1646}{}{Encantada de servirle, General.}
{647}{}{Aún nos queda mucho por hacer para erradicar los restos del mal de la Hermandad. Tu misión está completa. Regresa a la Villa e informa a tu familia de las buenas noticias.}
{648}{}{¿Por qué no sólo asaltar el fuerte con un escuadrón de rangers?}
{649}{}{Nuestro enemigo es fuerte y está bien organizado. No tenemos ninguna posibilidad en una batalla en campo abierto. En situaciones como ésta, decimos: si quieres derrotar a una bestia poderosa, dispara a las patas y acaba con ella a distancia.}
{650}{}{Quiero hablar sobre nuestro nuevo enemigo.}
{651}{}{Por supuesto. ¿Has descubierto algo?}
{652}{}{De ninguna manera.}
{653}{}{¿Qué sabes de la base en Puerto?}
{654}{}{No mucho. El viejo barco apareció en el puerto hace varios años. No se permite entrar a nadie; el perímetro está fuertemente vigilado. Es difícil para los exploradores llegar a través del desierto y, además, hemos concentrado nuestras fuerzas en otra parte. Tendrás que averiguar los detalles tú mismo.}
{655}{}{¿Cómo podría una organización tan secreta apoderarse de tantos asentamientos?}
{656}{}{A través de astutas Mediante políticas astutas y tecnología avanzada. Los militares de Puerto no participan directamente en los conflictos internos de Arizona. Pero son expertos en provocarlos. Cuando pasa la tormenta, los líderes que eligieron, marionetas como Aaron, acaban al mando de los asentamientos.}
{657}{}{¿Por qué es esto un problema para Arizona?}
{658}{}{Imponen su visión del mundo por la fuerza, lo que es inaceptable. Sus políticas despojan a los asentamientos de su autonomía, dejándolos en un estado de servidumbre. La sociedad no está preparada para sus ideas supuestamente "progresistas".}
{659}{}{Entendido. Cambiemos de tema.}
