{100}{}{Ves a un cadete, está asignado a la cocina.}
{101}{}{Ves al encargado de la cocina, va tan rápido como puede.}
{102}{}{Lo siento, pero no estás en la lista del almuerzo.}

{200}{}{Un momento, ¿por qué hay un civil aquí?}
{201}{}{Solo me dio curiosidad ver que había aquí.}
{202}{}{No puedes estar aquí, por favor, vete.}
{203}{}{Oblígame, perro.}
{204}{}{Claro, no quiero problemas.}
{205}{}{No te preocupes, tengo permiso.}
{206}{}{Relájate, tengo permitido estar aquí.}

{210}{}{Hoy me asignaron a la cocina. No puedo darte de comer, no eres uno de nosotros.}
{211}{}{Me parece justo. Entonces me voy, adiós.}
{212}{}{Por hoy, me asignaron a la cocina. Y lo siento, pero no te tengo en la lista del almuerzo.}

{220}{}{¿Quién es tu comandante, cadete?}
{221}{}{La capitana Agatha, ¿por qué preguntas?}
{222}{}{¿Qué piensas de su entrenamiento?}
{223}{}{Nos deja exhaustos, la verdad. Pero lo que nos enseña nos podría salvar la vida en el yermo. Mi única queja es que todavía no podemos usar el armamento pesado, desde el primer día que quiero usarlas. Y aunque me gane la placa, nos seguirán racionando la munición. Es una pena.}
{224}{}{Sé que algún día lo conseguirás. No te asustes.}
{225}{}{No es lo que esperabas, ¿verdad?}
{226}{}{Comprendo. Solo quería charlar un poco, cuídate.}
{227}{}{¿Crees que es una buena capitana?}
{228}{}{Por supuesto, cuida a los cadetes como si fueran familia. Agradezco que estemos bajo su mando.}
{229}{}{Sí que tuviste suerte. Nos vemos.}

{230}{}{El Intendente me contó que se perdió un arma después de su entrenamiento. ¿Eso es cierto?}
{231}{}{Pero... la regresamos.}
{232}{}{Déjame adivinar, ¿la entregaste y la tomaste prestada? ¿O usaste la firma de alguien más en el registro? Dime, ¿cuál fue?}
{233}{}{Hmm, entonces no creo que hayas hecho nada malo. Adiós, cadete.}
{234}{}{Eh... O sea... Mira, yo les dije que era una mala idea.}
{235}{}{Anda, suelta la sopa.}
{236}{}{Así que te haces el responsable, ¿no?}
{237}{}{Regresamos el arma luego de entrenar, pero luego la tomamos prestada junto a un par de balas. Pensamos que podríamos practicar un poco. ¿Qué clase de ranger no sabe disparar?}
{238}{}{Y pensaste que nadie se daría cuenta, ¿no?}
{239}{}{Queríamos devolverla, lo juro. Pero el ruido que hacíamos atrajo a los escorpiones y tuvimos que salir corriendo, y dejamos el arma tirada en el desierto. Intentamos recuperarla, pero el Intendente empezó a revisar el inventario antes de que pudiéramos meterla de vuelta al almacén.}
{240}{}{No debería juzgarte, aunque no esté de acuerdo. Pero a los demás sí les importará.}
{241}{}{Que historia tan creativa. Me pregunto que pensarán los demás al respecto.}
{242}{}{Sé que a los demás no les gustará que te lo cuente, pero es necesario. Tú eres nuevo aquí, ¿por qué no hacemos un trato?}
{243}{}{Está bien, ¿qué tienes en mente?}
{244}{}{Vas por el arma y yo te entrego nuestras balas. Después dejaré el arma en el almacén y todos quedamos contentos. Se me cayó al lado de un cactus grande, cerca de la granja. ¿Te parece?}
{245}{}{Es un buen plan. Lo pensaré.}
{246}{}{No ayudaré a un ladrón. Hasta luego, cadete.}
{247}{}{No le diré a nadie, no te preocupes.}
{248}{}{Eh... Mira, yo les advertí que era una mala idea. Pero nadie me escuchó.}
{249}{}{Refréscame la memoria, ¿en dónde está el arma?}

{250}{}{¡La encontraste! Gracias, nos salvaste el pellejo. Tendremos más cuidado de ahora en adelante. Aquí tienes los cartuchos que te prometí. }
{251}{}{Cuídate.}
{252}{}{¿De verdad tenías que decirle al Intendente? Ahora los demás cadetes saben que no pueden confiar en ti.}  
{253}{}{Lo siento, no tuve elección.}  
{254}{}{Ustedes se jodieron a sí mismos. Es culpa suya.}
{255}{}{Encontré un arma, ¿es esta?}
