{100}{}{Ves a una persona enferma, claramente necesitada de ayuda.}
{101}{}{Ves a un aldeano afiebrado y reseco, tiene síntomas de una enfermedad grave.}
{102}{}{Tu diagnóstico confirma que el paciente sufre de una alta dosis de radiación.}
{103}{}{El paciente espera a que lo examines.}

{210}{}{(Ves a un aldeano enfermo, está sediento, suda mucho, tiembla y tiene problemas al respirar)}
{211}{}{[Deja al aldeano enfermo en paz]}
{212}{}{¿Cómo te sientes?}
{213}{}{*Cof cof*... con la cabeza pesada. Y ayer estaba joya.}
{214}{}{¿Tienes alguna idea de qué te causó esto?}
{215}{}{No sabría decirte. Comí el pez de siempre, fui a los mismos lugares de siempre.}
{216}{}{¿Te habrá contagiado alguien más?}
{217}{}{Tal vez... *Cof Cof*... pero entonces los demás también estarían enfermos.}
{218}{}{Necesito determinar la causa. ¿Te importa si te examino?}
{219}{}{Claro. ¿Me quito la ropa, o...?}
{220}{}{Sí...}
{221}{}{Bueno.}
{222}{}{Parece que recibiste una alta dosis de radiación.}
{223}{}{¿Qué? ¿Cómo? Por acá no hay ninguna fuente de radiación.}
{224}{}{Seguramente fue algo que tragaste. ¿Qué has comido últimamente?}
{225}{}{Lo mismo de siempre, pez y pan... Ah, y una Nuka-Cola que le compré a Flick. ¿Será que un par de botellas me hicieron esto?}
{226}{}{Es posible. Tengo que investigar...}
