{100}{}{Ves al guardia de Flick.}
{101}{}{Ves a un guardia musculoso, no parece ser muy listo.}

{110}{}{Habla con Flick, él se ocupa de todo.}  
{111}{}{Flick es inteligente, comercia la basura que nadie quiere por lo que nosotros sí.}  
{112}{}{¿Buscas algo? Flick seguramente lo tiene.}  
{113}{}{Estoy aquí para cuidar las cosas de Flick, ¿entendido?}  
{114}{}{¿Buscas aguardiente, cierto?}  
{115}{}{De verdad me enojo cuando Flick mete la pata.}  
{116}{}{Nada de robarle al jefe, ¿me escuchas?}  
{117}{}{Si le intentas robar a Flick, te cortaré las manos.}  
{118}{}{No pienses que no te estoy mirando.}  
{119}{}{¿Quieres descubrir cómo se siente mi lanza?}  
{120}{}{El jefe dice que es hora de irse. Vámonos.}  

