{100}{}{Ves a un bandido.}
{101}{}{Ves a alguien que casi se parece a un ranger.}

{110}{}{Acércate si tienes los huevos puestos.}
{111}{}{¿Te crees muy valiente?}
{112}{}{Deberías tenernos miedo.}
{113}{}{Esto es NUESTRO territorio, que te quede claro.}
{114}{}{Hoy es mi día de suerte, no tendré que buscar a una presa.}
{115}{}{Veamos lo que llevas en esa mochila.}
{116}{}{*Hace tronar sus nudillos con una sonrisa retorcida*}
{117}{}{Buscas problemas, ¿verdad?}
{118}{}{Empieza a rezar, el jefe se siente piadoso el día de hoy.}
{119}{}{¿Por qué te metes en nuestro territorio?}
