{100}{}{Ves a un ranger, o eso crees.}
{101}{}{Ves a un hombre que parece un ranger, pero algo anda mal.}
{102}{}{Piérdete, antes de que cambie de opinión.}

#First Dialogue
{200}{}{Alto ahí. Te encuentras en el territorio de los Rangers, ¿por qué estás aquí?}
{201}{}{¿Cuál es tu problema? El yermo no le pertenece a nadie, está abierto a todos, sólo un idiota intentaría apoderarse de él.}
{202}{}{Me interesa tu perspectiva, pero es irrelevante. Te lo vuelvo a preguntar, ¿por qué estás aquí?}
{203}{}{Quizás te estoy buscando a ti. He escuchado que robas a los viajeros, haciéndote pasar por un Ranger.}
{204}{}{Soy un Ranger, aquí tengo mi placa. Y no le estoy robando a nadie, simplemente es la tarifa por cruzar la frontera. Así me gano la vida. Tú igual me vas a pagar, por cierto.}
{205}{}{¿Esto es tu territorio? Demuéstralo.}
{206}{}{Eres otro repugnante saqueador, ¿verdad?}
{210}{}{¿Se te pudrió el cerebro o qué? Tú no eres nadie. Dame tu mochila y dejaré que te vayas.}
{211}{}{No me hagas daño, llévate todo lo que tengo.}
{212}{}{Sáquese de aquí, no quiero volver a verte.}
{213}{}{Como tú digas...}
{214}{}{¡Oye! ¡Dame mis cosas, ahora!}
{215}{}{Ni en tus sueños.}
{216}{}{Tú me obligaste. Ya saben qué hacer, chicos...}
{217}{}{¿A quién mataré primero...?}
{218}{}{Ya, ya, aquí tienes. Es todo lo que tengo...}
{219}{}{Tengo cosas terriblemente radioactivas. ¿En serio arriesgarás tu salud por algo así?}
{220}{}{¿Me ves la cara de tonto? Es tu última oportunidad, o esto se pondrá feo.}
{221}{}{Está bien. Sólo ten cuidado con mis cosas, tienen una dosis letal de radiación.}
{222}{}{¿¡Cómo!? ¡No te me acerques, imbécil! ¿Por qué llevas eso contigo?}
{1222}{}{¿¡Cómo!? ¡No te me acerques, pendeja! ¿Por qué llevas eso contigo?}
{223}{}{Para un día como este.}
{224}{}{Es para un trabajo.}
{225}{}{No. Primero, quiero saber quién eres. Un Ranger no mantiene la Ley y el Orden de esta forma.}
{226}{}{No eres un Ranger. Ellos jamás robarían como si fueran bandidos.}
{230}{}{Yo soy la ley. Yo soy el que manda aquí. ¿Quién eres para cuestionar eso? ¡Haz lo que te digo!}
{231}{}{De ninguna manera...}
{232}{}{Si eres un ranger, entonces no eres digno de tu placa. Te despojo de tu rango. Entrégamela.}
{233}{}{Si un Ranger quiebra la ley, se le despoja de su rango. Entrégame la placa.}
{240}{}{Ley y el Orden... Esas palabras no valen nada. Los Rangers llegan, reclaman un territorio, y le quitan todo a la gente común. ¿Qué tiene eso de distinto con lo que estoy haciendo? Si ellos pueden robar, nosotros también.}
{241}{}{A cambio, esas personas reciben protección. Y siempre hay más lugares a donde ir.}
{242}{}{¿Entonces los Rangers no protegen sus territorios?}
{243}{}{Para ellos, los demás son sólo peones. ¿Acaso no lo entiendes? No cuidan a nadie. Los rangers prometieron defendernos de los bandidos, ¿pero en dónde estaban cuando mi pueblo fue atacado?}
{244}{}{¿Quizás estaban ocupados?}
{245}{}{¿Crees que eso me hará sentir mejor? Durante dos años, nos tenían hasta el cuello de impuestos. Nos moríamos de hambre, y eso jamás les importó. Y claro, se llevaron las mejores armas que teníamos. Las que nos hubieran ayudado contra los bandidos, si las hubiéramos conservado.}
{246}{}{Que triste historia, tiene sentido que les guardes rencor.}
{247}{}{No me digas. No creas que te dejaré ir, dame todas tus cosas. Incluida tu ropa.}
{248}{}{No tengo nada que ver con esto. Déjame en paz.}
{249}{}{Los crímenes de otros no son excusa. Dame tu placa y puede que te deje vivir.}
{250}{}{Lo que te pasó fue horrible, pero debes superarlo. Pasar página.}
{251}{}{¿Acaso crees que soy un idiota? Suelta todo lo que tengas, y Hazlo lento para verlo bien.}
{252}{}{Sé lo que sientes, mi pueblo fue atacado por unos esclavizadores.}
{253}{}{Creo que escuché algo al respecto. Ambos somos víctimas.}
{254}{}{Exactamente. Y tú serás mi siguiente víctima. Di tus últimas palabras, perdedor...}
{255}{}{Así es - no deberías seguir haciéndole esto a más civiles. Son inocentes, igual que tú y yo. Estás atacando a la gente equivocada.}
{256}{}{¡YA LO SÉ! ¿Pero qué podemos hacer? Vivimos al margen de la ley, no tenemos a dónde ir.}
{257}{}{¿Qué tal si cazan animales o protegen caravanas? Siempre hay una solución.}
{258}{}{Al diablo con esto, es imposible hacer cambiar de parecer a un saqueador...}
{259}{}{Yo y los demás lo estábamos conversando. Estamos cansados de vivir así, no hay mucha gente por estos lares y cada vez es más arriesgado. Es hora de cambiar. ¿Quieres la placa? Quédatela. Para mí no tiene ningún valor, de todos modos.}
{260}{}{Estás haciendo lo correcto. Bien hecho.}
{261}{}{Sí, como tú digas. Piérdete antes de que cambie de opinión.}
{262}{}{Ya, ya me voy...}
{300}{}{¿Tú otra vez? ¿Acaso no entendiste la primera vez?}
{301}{}{No hay nada que deba 'entender'. Eres un bandido, nada más. Los rangers respetan la ley, y claramente no eres uno.}
{302}{}{No tienes el derecho de decirle a los demás en dónde pueden estar y dónde no.}
{303}{}{¿De verdad eres un Ranger, o sólo estás jugando a la 'Ley y el Orden'?}
