{100}{}{Ves a Jack.}
{101}{}{Ves a un ranger, está vigilando la entrada a la presa.}
{102}{}{¡Oye, oye! ¡Sal de esa maldita cosa! ¡No volveré a repetirlo!}
{103}{}{¡Piérdete, maldito cultista! ¡No vamos a hablarte!}

#Initial dialogue
{200}{}{(Conforme te acercas a los guardias, notas que sus rostros cambian al levantar sus armas.) Alto, no permitimos la entrada a los civiles.}
{201}{}{¿Qué tienen ahí adentro?}
{202}{}{¿Ahí? ¿Detrás de esa puerta? Es el cuartel general de los rangers.}
{203}{}{Ah, no necesito entrar ahí.}
{204}{}{Entonces deja de perder el tiempo y lárgate.}
{205}{}{De acuerdo.}
{206}{}{Alto, ¿por qué vienes a la base?}
{207}{}{Nada.}
{208}{}{Tengo que hablar con el general.}
{209}{}{Sí, claro. No todos los reclutas pueden ir allí, y tú menos. ¿Tienes un pase?}
{210}{}{Te arrepentirás de esto.}
{211}{}{Entonces no hay problema.}
{212}{}{Por favor, es muy importante.}
{213}{}{Si algún ranger fuera a responder por ti, entonces PUEDE que te dejen pasar. Dame una buena razón, o piérdete.}
{214}{}{Está bien, puedes pasar. Pero no te quitaremos los ojos de encima, recuerda eso. Ve directo a hablar con el general y no te pongas a husmear. Mantén tu arma guardada.}
{215}{}{No es necesario que lo digas, es obvio.}
{216}{}{Muchas gracias, ranger.}
{217}{}{Tengo que hablar con el general.}
{218}{}{Puede que el intendente esté interesado en mi mercancía.}
{219}{}{No, haré que te arrepientas tú si sigues buscando problemas. Piérdete.}

{220}{}{No deberías andar por la base con esos harapos puestos, pensarán que buscas sabotearnos.}
{221}{}{¿Por qué?}
{222}{}{No te hagas. Es una túnica de los Seguidores del Fuego, y no nos gustan esos tipos. Que se vayan al carajo, siempre imponen sus creencias en los demás.}
{223}{}{Comprendo.}
{224}{}{¿El viejo Rufus estaba esperando a ese niño, no? Has hecho bien al traerlo con nosotros, deja que sea útil para el yermo. Es muy habilidoso, no debería pasarse la vida en un basural.}
{1224}{}{¿El viejo Rufus estaba esperando a ese niño, no? Has hecho bien al traerlo con nosotros, deja que sea útil para el yermo. Es muy habilidoso, no debería pasarse la vida en un basural.}
{225}{}{Hice lo que dije que haría. El resto depende de ustedes.}
{226}{}{Me alegra que quieran recibir al niño.}
{227}{}{¡Oye! ¿¡Quieres que te matemos, o qué!? ¿Qué demonios pasó con Flick?}
{228}{}{¿Qué pasó? ¿A ustedes les agradaba?}
{229}{}{¿Cómo crees? A casi todos nos caía mal. Pero era uno de los pocos mercaderes del área, ¡no puedes matarlo así como así! Mira, no sé que habrá pasado - nuestros jefes lo solucionarán. Pero ten en cuenta que si es culpa tuya, los rangers no lo olvidarán.}  
{1229}{}{¿Cómo crees? A casi todos nos caía mal. Pero era uno de los pocos mercaderes del área, ¡no puedes matarlo así como así! Mira, no sé que habrá pasado - nuestros jefes lo solucionarán. Pero ten en cuenta que si es culpa tuya, los rangers no lo olvidarán.}

{230}{}{El Comandante Helford me permitió pasar.}
{231}{}{Tengo algo que contarle al general. Se trata de Kuyuk, en Flagstaff.}
{232}{}{Yo ayudé a Oscar en San Brahmán.}
{1232}{}{Yo ayudé a Oscar en San Brahmán.}
{233}{}{Tengo información de un espía en Two-Sun.}
{234}{}{El general debería saber acerca de mi conexión con los rebeldes de Fénix.}
{235}{}{Poseo información muy importante, se trata de la Hermandad del Acero.}
{236}{}{Hola, sólo estoy pasando por aquí.}
{237}{}{Tengo un holodisco importante, es un informe interno de la Catedral en Fénix.}

#Repeat dialogue
{250}{}{Hola.}
{251}{}{Adiós.}

{260}{}{Quiero reportar algo. Hay un espía escondido en la carretera vieja, dentro de la choza...}
{261}{}{...Gracias por avisarnos. Enviaremos un escuadrón para atraparlo por sorpresa.}
{262}{}{}
{263}{}{Buena suerte.}

{270}{}{¿Hay alguna forma de cruzar al otro lado?}
{271}{}{Sólo con el permiso del general. Los civiles tienen prohibido cruzar la presa, si necesitas llegar al otro lado, tendrás que ir nadando.}
{272}{}{¿Dónde está el cruce más cercano?}
{273}{}{Quince millas río abajo, hay una barca.}
{274}{}{¿Entonces se apoderaron del único puente que había al otro lado?}
{275}{}{Sí, así es. ¿Algún problema?}
{276}{}{Eh, no, ninguno.}
{277}{}{Sí. Es injusto.}
{278}{}{¿Injusto? Entonces anda a llorar con tu mamá.}
{279}{}{Así que así están las cosas...}
{280}{}{¿Por qué no permites que esta mujer hable con el general?}
{281}{}{Está muy ocupado.}
{282}{}{¿En serio? Me parece que simplemente no quiere hacerse responsable por lo que hacen sus soldados.}
{283}{}{Tonterías. Esa mujer estaba con un criminal, se lo merece. Si la vas a ayudar, aléjate de la base antes de que pierda la paciencia.}
{284}{}{Entonces dejemos el tema.}
