{100}{}{Ves a un ranger.}
{101}{}{Ves a un ranger promedio.}
{102}{}{Improvisamos esta enfermería, pero no admitimos a los civiles.}

# Floating Lines
{110}{}{Hasta que eliminemos a los Chacales, viajar al norte es una sentencia de muerte.}
{111}{}{Quien sea le haya puesto fin a los Chacales merece una chela bien fría.}
{112}{}{Hicimos un trato con los Chacales, no puedo creerlo...}
{113}{}{He oído que hay unos campos frondosos y verdes en el norte, pero por allá es muy estéril.}
{114}{}{A los tipos de la Villa se les cayó la máscara y se unieron al enemigo.}
{115}{}{Los norteños nos cobran hasta un ojo de la cara, por un par de mazorcas.}
{116}{}{Los pastores de San Brahmán van a durar muy poco sin nuestra protección.}
{117}{}{Esos pastores se arrepentirán de darnos la espalda.}
{118}{}{Los Seguidores en Fénix casi nos arrebató San Brahmán, pero nos mantuvimos firmes contra ellos.}
{119}{}{Flagstaff es parte del mercado de esclavos, algún día lo pagarán.}
{120}{}{Mientras Flagstaff se deshaga de sus esclavos, me da igual lo que hagan.}
{121}{}{La expansión de Flagstaff nos atraerá problemas.}
{122}{}{Necesitamos aplastar a los Seguidores del Fuego antes de que nos quemen a todos.}
{123}{}{El culto del Fuego Santo ardió bajo sus propias llamas.}
{124}{}{Esos malditos cultistas están conquistando más y más territorio.}
{125}{}{¿Qué es esa "amenaza sureña"? ¿Y por qué hablan de ello en secreto?}
{126}{}{La Hermandad del Acero recibió su merecido, meterte en la vida de los demás siempre termina mal.}
{127}{}{No sé si podamos contra la Hermandad del Acero.}
{128}{}{La presa Parker es una maravilla del ingenio del Viejo Mundo.}
{129}{}{Encontrar una base para reemplazar esta no será nada fácil.}
{130}{}{El viejo Rufus le volvió a meter mano a la central eléctrica.}
{131}{}{Ese tal campesino tiene mucho potencial.}
{132}{}{¿Será que todos los campesinos de la Villa son así de impresionantes?}
{133}{}{No le quitaré los ojos de encima a ese tal campesino.}
{134}{}{Debería conocer mejor a ese tal campesino.}
{135}{}{Ese campesino parece ser muy sospechoso.}
{136}{}{No me agrada ese campesino.}
{137}{}{Un día, cambiaremos el yermo para mejor.}
{138}{}{Dicen que alguien mató al barquero.}
{139}{}{Algún bastardo ha estado cavando las tumbas de nuestros rangers, y dudo que sea algún mutante.}
{140}{}{En el Acueducto abunda la paz y la tranquilidad.}
{141}{}{Garth estaba detrás de las desapariciones, ¿quién lo hubiera dicho?}
{142}{}{William Garth es un gran hombre, ¿no lo crees?}

#Response
{150}{}{Los rangers luchan por su causa hasta el final.}
{151}{}{Siempre apuntamos con la justicia en mente, y nuestras balas disipan el mal.}
{152}{}{Algún día, cambiaremos el yermo por completo.}
{153}{}{Un vehículo nos haría la vida mucho más fácil...}
{154}{}{Deberíamos haber acabado con esos malditos Chacales hace años.}
{155}{}{Fénix es una amenaza, y cada día crece más y más.}
{156}{}{Debes tener cuidado en el yermo.}
{157}{}{Estás a salvo con nosotros.}
{158}{}{No tengo el permiso de hablar al respecto.}
{159}{}{Tienes buenos rasgos, podrías ser un ranger.}
{160}{}{Las criaturas más peligrosas del yermo son nocturnas, así que ten cuidado.}
{161}{}{Te deseo buena suerte.}

{170}{}{¿Estás buscando problemas?}
{171}{}{Nuestros disparos nunca fallan, recuérdalo.}
{172}{}{Llegaste justo a tiempo - podemos usarte de práctica en el campo de tiro.}
{173}{}{No deberías pasearte por aquí.}
{174}{}{¿Qué quieres?}
{175}{}{Hmm, no parece que podamos confiar en ti.}
{176}{}{No puedo hablar contigo al respecto.}
{177}{}{Estás por tu cuenta.}
{178}{}{Juntos podremos reconstruir el yermo.}
{179}{}{¿Algún problema?}

{180}{}{Bienvenido, ranger.}
{181}{}{Lo siento, pero no puedo escoltarte a la base.}
{182}{}{Estás haciendo la diferencia en el yermo.}
{183}{}{Todos te agradecemos que luches con nosotros.}
{184}{}{Pásate por la base cuando puedas.}
{185}{}{Mantén los ojos bien abiertos, ranger.}
{186}{}{Espero con ansias tus informes acerca de las nuevas zonas.}
{187}{}{Un vehículo lo cambiaría todo...}
{188}{}{Un día, haremos del yermo un lugar mejor.}
{189}{}{Ten cuidado con los mercaderes, son estafadores.}
