{100}{}{Ves a la oficial de comunicaciones.}
{101}{}{Estás viendo a una mujer de aspecto serio.}

{200}{}{Hola.}
{201}{}{Hasta luego.}
{210}{}{¿Qué pasa?}
{211}{}{Adiós.}
{220}{}{Háblame de ti.}
{221}{}{Soy Jain, la oficial de comunicaciones.}
{222}{}{¿Cómo acabaste entre los rangers?}
{223}{}{Solo pasó.}
{224}{}{Ah, ya entiendo.}
{225}{}{¿Alguna otra pregunta, genio?}
{226}{}{Sí.}
{227}{}{No.}
{228}{}{}
{229}{}{Tengo otra pregunta.}
{230}{}{¿Qué es este lugar?}
{231}{}{Es una estación de radio. No es una estación de radiación, por si acaso. No es fácil de explicar, pero básicamente utilizamos estos equipos para mantenernos en contacto con las patrullas, aunque estemos lejos.}
{232}{}{Esta tecnología es muy vieja, me sorprende que todavía funcione.}
{233}{}{Es todo un milagro, ¿no? Es todo gracias a las caravanas que nos dieron las partes y la presa que nos da energía.}
{234}{}{En el yermo, no hay mucha gente que posea tecnología del Viejo Mundo.}
{235}{}{Así es, la tecnología es nuestro salvavidas. Hay algunas personas que le tienen miedo a sitios como este, pero para nosotros, es un legado que ha pasado de generación en generación, está documentado en las holocintas. Para nosotros, es como una reliquia.}
{236}{}{¿En dónde están todos? Apenas hay gente por aquí.}
{237}{}{Así esta mejor, de por sí la radio ya hace ruido. Y por acá no nos gustan los forasteros, mucho menos los que nunca se callan.}
{238}{}{Quizás quieras relajarte en algún lado.}
{239}{}{¿En dónde? Si quieres matar algunos coyotes, me apunto, pero no creo que tú y yo la pasemos bien.}
{240}{}{¿Te frustran las demás personas?}
{241}{}{Un poco. Si tratas con cadetes que causan problemas y con sargentos que ignoran sus ordenes, también cambiaría cómo piensas de los demás.}
{242}{}{¿Por qué hay un montón de cruces al lado de la estación?}
{243}{}{Es nuestro cementerio, allí descansan los rangers y sus familias. Ni siquiera pienses en profanar esas tumbas, porque sería tu último error.}
{244}{}{Tengo más preguntas acerca de la estación de... radiación.}

{250}{}{Necesito los códigos de la radio.}
{251}{}{Eso es clasificado, no es algo que cualquiera pueda saber.}
{252}{}{Hace poco que me uní a los reclutas.}
{253}{}{De acuerdo, entonces nunca lo pregunté.}
{254}{}{Entonces métetelos por donde te quepan.}
{255}{}{Ah, ya entiendo, perdón. Toma los códigos y el cifrado para nuestras frecuencias principales. Pero esto se queda entre los rangers y tú, recluta. Recuerda eso.}
{256}{}{Muchas gracias, oficial.}
{257}{}{De acuerdo, gracias.}
{260}{}{La presa fue destruida, ¿por qué siguen aquí?}
{261}{}{En tiempos como estos, mi trabajo es más importante que nunca. El alto mando está buscando un nuevo cuartel general, y sin comunicación a distancia, es como si estuvieran ciegos.}
{262}{}{Sigue, te escucho.}
{263}{}{Pero esto no durará para siempre. La energía de los generadores no durará mucho, una vez que se haya acabado o la estación deje de funcionar, estamos fritos. Al menos, la vista del valle es bastante buena desde acá arriba.}
{264}{}{Entiendo.}
{270}{}{Escuché que atrapaste al espía que estaba merodeando por la granja. Bien hecho.}
{271}{}{De nada, quería ayudarlos.}
{1271}{}{De nada, quería ayudarlos.}
{272}{}{Sólo estaba haciendo mi deber.}
{273}{}{Jason escapó de las garras de los Chacales gracias a ti, ¿no? Eso es impresionante, pensé que nunca volvería.}
{274}{}{Solo quería ayudar.}
{1274}{}{Solo quería ayudar.}
{275}{}{De nada.}

#Story quest
{278}{}{¿En serio?}
{279}{}{El problema es que la mitad de los repetidores no han funcionado por años. Hay que repararlos o buscar un repuesto. Una vez que funcionen, tendremos suficiente cobertura y podremos controlar territorio tan lejos como San Brahmán... quizás hasta Fénix.}
{280}{}{El comandante Helford me dijo que viniera aquí.}
{281}{}{Genial. Maravilloso. ¡La estación se cae a pedazos y Helford trae a un campesino para arreglarla! ¿Tienes la menor idea de cómo funciona una estación de radio?}
{282}{}{Ya lo descubriré. ¿Qué debo hacer?}
{283}{}{Ahora mismo, nuestros soldados no dan abasto en el frente al este y el sureste. Hay algunos puestos que no están en contacto con nosotros, cuando deberían estarlo.}
{284}{}{Entonces, ¿en dónde está el equipo que no funciona?}
{285}{}{En el sótano debajo de la antena. Un trabajo a medias no será suficiente para esto, quizás encuentres lo que falta en Ciudad Garaje si hablas con los chatarreros, pero no les caen bien los rangers. ¿Crees que puedas hacer eso?}
{286}{}{Iré a revisar...}
{287}{}{Espera, vas a Ciudad Garaje a buscar los repuestos, ¿no? Entonces hazme un favor, perdimos una patrulla en el área, intenta descubrir que les pasó. Nuestras radios no funcionan a esa distancia, pero sí pueden detectar las señales cercanas. Si tienes éxito, los Rangers te lo agradecerán mucho.}
{288}{}{Voy a investigar qué ocurrió, no te preocupes.}
{289}{}{No te prometo nada.}
{290}{}{He reparado la radio.}
{291}{}{Me he encargado del eco, pude descomponer el repetidor del espía.}
{292}{}{¿Me podrías repetir qué tengo que hacer?}
{293}{}{¿Fue demasiada información para tu cerebro, cierto? Encuentra la fuente del eco que suena en nuestra señal. Ve al desierto, hacia el sur o el este, y utiliza el walkie-talkie para rastrear la señal. Averigua de dónde proviene.}
{294}{}{Ya comprendo, me pondré con ello...}
{295}{}{[Sigue]}
{296}{}{¡Genial! Ahora... un momento, ¿lo escuchas?}
{297}{}{Se escucha un eco, ¿será que algo está repitiendo la señal?}
{298}{}{Eso parece... La señal es débil, viene del sur... quizás el este... No lo habíamos detectado antes, puede que sea un error con el equipo nuevo, pero... Mira, necesitamos saber qué es. No podemos ignorarlo.}
{299}{}{[Sigue]}
{300}{}{Ve al sur o el oeste hacia la dirección de la señal y averigua qué está causando el eco, tendrás que entrar al desierto. Llévate este walkie-talkie para rastrearla.}
{301}{}{Supongo que esto todavía no termina...}

{302}{}{¡Esto no me lo esperaba! Pensé que sólo nosotros teníamos tecnología de radiodifusión tan potente. Habla con el comandante Helford de inmediato.}
{303}{}{[Sigue]}
{304}{}{Parece que sabes algo... Informa al comandante Helford respecto a la operación.}
{305}{}{¡Señora, sí señora!}
