{100}{}{Ves a un niño.}
{101}{}{Ves al integrante más joven de la familia Milton.}

#Dialogue
{110}{}{Buenos días. ¿Viniste para ayudarnos con esas plagas?}
{111}{}{¡Por favor, salva a mis padres!}
{112}{}{Los rangers son geniales. Cuando crezca, quiero unirme a ustedes.}
{113}{}{¡Todo es culpa tuya! ¡Fuera de aquí!}
{114}{}{¡Todo es culpa tuya! ¡Fuera de aquí!}
{115}{}{¡Lárgate!}
{116}{}{Gracias por salvarnos de ese monstruo.}

{200}{}{¡Esperen! Hay... hay un... ¡Un bandido!}
{201}{}{¿Dónde?}
{202}{}{Cálmate, no puedo entenderte si hablas tan rápido.}
{203}{}{¡Hay un bandido en nuestra casa! ¡Tiene un arma y amarró a mi mamá y mi papá! ¡Por favor, tienes que ayudarlos!}
{204}{}{Quédate aquí. Echaremos un ojo.}
{205}{}{Hazte a un lado, niño. Deja que los profesionales se encarguen.}
{206}{}{Seguro que solo viste una rata, niño...}
