{110}{}{Este equipamiento no funciona.}
{111}{}{Conseguiste deshabilitar el transmisor de radio. Ahora los rangers se encuentran sin comunicación por radio.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{El transmisor de radio no responde.}

{210}{}{Copiaré las frecuencias de los Rangers y el código... Así podré escuchar lo que digan en la radio.}
{211}{}{Frecuencias de radio copiadas.}
