{110}{}{Este mecanismo sujeta la compuerta de la presa con cables de acero.}
{111}{}{El mecanismo falló, no debe ser posible repararlo.}
{112}{}{Al mecanismo no le quedó ningún rasguño.}
{113}{}{El mecanismo se hace pedazos, y los cables son arrastrados a la oscuridad. Unos momentos después, al fondo del pozo, escuchas el golpe de la compuerta.}
{114}{}{Bueno... se cayó el sistema, literalmente.}
