{100}{}{Ves al Oficial Bell.}
{101}{}{Ves a un soldado que está completamente exhausto.}
{102}{}{Este paciente no tiene ninguna herida o concusión. Ha sufrido un profundo trauma mental.}
{103}{}{Eso debería despejarle la cabeza, soldado...}
{104}{}{Ellos me observan cuando duermo... ¡No dejes que me duerma!}
{105}{}{Gracias, me siento mucho mejor. Es como si hubiera estado en un sueño muy largo.}
{106}{}{Bell se rehúsa a tomar eso.}

#Floating dialogue (problems not to be removed!)
{110}{}{   }
{111}{}{¡Doctor! ¡DOCTOR! ¡No deje que me duerma!}
{112}{}{Cálmate, Bell. Todo está bien, no hay ningún problema. ¿Tuviste una pesadilla?}
{113}{}{Ellos me observan cuando duermo... Tienen ojos que me miran hasta el alma...}
{114}{}{¿Quiénes?}
{115}{}{¡Doctor! ¡Me quieren llevar al infierno!}
{116}{}{Bell, amigo mío, cálmate. Nadie te hará nada mientras duermas. Sólo fue una pesadilla.}
{117}{}{¡No! Son reales... Sus voces están en mi cabeza... ¡acabo de escucharlo!}
{118}{}{¡Contrólate, soldado! No hay nadie hablándote, sólo soy yo.}
{119}{}{Entonces... ¿está todo dentro de mi cabeza? Perdón, doctor.}
{120}{}{Así es, Bell. Es sólo un problema mental, tienes que descansar.}
{121}{}{Doctor, eso no me ha ayudado, las pastillas para dormir tampoco funciona...}
{122}{}{Toma, es una doble dosis. Todo estará bien.}
{123}{}{Gracias, doctor. Intentaré dormirme...}
{124}{}{Bien pensado, Bell. Intenta dormir, nadie te molestará.}
{125}{}{*Ronquido*}
{126}{}{Por fin se calló.}
{127}{}{*Z-z-z*}
{128}{}{Ah, adoro estos momentos de paz...}
{129}{}{*Murmura*}
{130}{}{   }

{200}{}{Ellos me observan cuando duermo... ¡No dejes que me duerma!}
{201}{}{¿Quién? ¿Quién es el que viene?}
{202}{}{¡Ellos! Son enormes, terroríficos...}
{203}{}{Bell, escúchame, quiero ayudarte. ¿A qué le temes? Descríbemelo.}
{204}{}{¡Contrólate, soldado! ¡No está pasando nada!}
{205}{}{Son espantosos, sus ojos arden en la oscuridad... no puedo recordar nada más.}
{206}{}{Parece que has escondido esa memoria en tu subconsciente.}
{207}{}{Deja de llorar, pareces un niñito.}
{208}{}{Es... una sombra, muy grande. Sus ojos parecen arder. Se me acerca cuando duermo... No puedo moverme... Me observa... Es enorme.}
{209}{}{¿Qué hay alrededor tuyo? Intenta recordarlo.}
{210}{}{¿Quién te mira? ¿En dónde te mira? ¡No lo entiendo!}
{211}{}{Alrededor mío... veo... oscuridad, un yermo gris... No, no es arena, es ceniza. ¡Es el infierno! Intento correr, pero no puedo... ¡No puedo!}
{212}{}{¿Un yermo hecho de cenizas? Pero, ¿en dónde será eso?}
{213}{}{Estás delirando, no existe ningún desierto hecho de cenizas.}
{214}{}{¡No lo sé! ¡No sé! ¡Déjame en paz!}
{215}{}{Está bien.}
{216}{}{Bueno. Ya me aburriste, de todas formas.}

{220}{}{Quiero dormir, ¡pero no puedo! O vendrá por mí... Sí, ¡vendrá por mí y me arrastrará al infierno!}
{221}{}{Eh, tengo que irme. Adiós.}

{230}{}{Bell, mira. Tengo el cráneo de esa bestia que tanto temes.}
{231}{}{Bell, ya sé que viste en la planta de concreto. La bestia ha muerto, los ciudadanos de Casa Nueva están bailando sobre su tumba.}
{232}{}{¿Cómo...? Eso es un... ah, ja. ¡Jaja! ¡Está muerto! ¡Muerto! Y no da tanto miedo a plena luz del día. ¡Órale! ¡He sido un estúpido! No puedo creer que un mutantito me asustara tanto. ¡Jaja!}
{233}{}{Sí, ya se acabó. No volverás a tener pesadillas.}
{234}{}{Quién lo hubiera dicho.}
{235}{}{Ahora lo recuerdo, esa bestia se apareció en frente de mí mientras estaba de guardia en la planta. ¡Me miró directo a los ojos! Estaba a punto de morir, pero tuve suerte, pues atacó a mi compañero. Supongo que me aterró tanto que escondí ese recuerdo.}
{236}{}{Todos habrían hecho eso en tu lugar.}
{237}{}{A mí no me hubiera asustado.}
{238}{}{Pero, ¡ahora soy libre! Gracias, ¡tú sí que mereces ser un Paladín! Por favor, déjame compartirte algo de munición. Es lo menos que puedo hacer.}
{239}{}{Cuídate, soldado.}
{240}{}{Sí, creo que a diferencia de ti, yo sí sabré usarlos. Adiós.}
