{100}{}{Ves a un líder de caravana.}
{101}{}{Ves a un hombre de ropa polvorienta, parece que ha caminado mucho tiempo por el yermo.}
{102}{}{Después de ti.}
{103}{}{Gracias por la ayuda, soldado.}

{200}{}{¡Oye! ¿Eres parte de la Hermandad, no? Ya era hora - pensé que me habían dejado por muerto.}  
{201}{}{Jamás dudes del honor y valentía de la Hermandad.}
{202}{}{¡Pero si todo esto es culpa de tu maldita Hermandad! Así que me la debes, ¡sácame de aquí!}  
{203}{}{Vámonos, te llevaré al punto de extracción desde donde atacamos.}
{204}{}{Es mejor que te escondas, espérame ahí y cúbrete los oídos.}
{205}{}{La Hermandad llegó para ayudarte, debo sacarte de aquí, son mis órdenes.}
{206}{}{Te sigo, soldadito. Pero te aviso - si empiezan a dispararnos, saldré corriendo.}  
{207}{}{Vamos, el Paladín Dobbs ordenó tu rescate.}
{208}{}{Entonces escóndete, ya vengo. Volveré cuando sea el momento.}
{209}{}{Escóndete y baja la cabeza, tengo que ir a echar un ojo.}
{210}{}{Oye, ¿en dónde están los paladines? Me estoy poniendo nervioso.}  
{211}{}{Ya llegamos, los paladines te recogerán cuando terminen.}
{212}{}{Gracias por ayudarme, soldado. La verdad, pensé que jamás volvería a verle la cola a un brahmán.}  
{213}{}{De nada, nos vemos.}

{220}{}{Cuéntame lo que ocurrió durante el ataque.}
{221}{}{Estábamos transportando carga para la Hermandad, de parte de los Hojalateros. Teníamos que llegar a Casa Nueva para pasar la noche, pero los malditos forajidos se enteraron de nuestra ruta antes de que llegáramos. Pero no nos atacaron - nos siguieron, reclutando a cada saqueador del área como si planearan algo. Y así fue, antes de llegar a Puerto nos atacaron - parecían un maldito enjambre. No teníamos escapatoria.}  
{222}{}{¿Qué era la carga que llevaban a Puerto?}
{223}{}{No era más que un montón de dispositivos electrónicos. Pero pagaban bien. Lo único que sé es que la Hermandad quería que tuviéramos cuidado, dijeron que era importante, o algo así.}  
{224}{}{¿Qué sabes de los atacantes?}
{225}{}{Eran algunos saqueadores de por aquí. Por su forma de hablar, diría que deben ser del sur o que han estado por aquí mucho antes que la Hermandad.}  
{226}{}{De acuerdo. Ya hablamos mucho.}
