{100}{}{Ves a Raymond.}
{101}{}{Estás viendo al intendente de la Hermandad. En su cabeza está montado un gran lente, con el que observa las listas.}
{102}{}{No tengo tiempo para hablar contigo.}
{103}{}{¿?}
{104}{}{¡No vengan aquí si llevan servoarmadura, ya lo he dicho mil veces! ¡Vas a quebrar algo!}

#Floating lines
{110}{}{Tengo que hacer el inventario.}
{111}{}{Para la siguiente vez, el que va a limpiar las manchas serás *tú*.}
{112}{}{La Hermandad me aprecia más de lo que crees.}
{113}{}{Se me está metiendo el óxido por la nariz.}
{114}{}{Si me lo preguntas, las granadas están sobrevaloradas.}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}

#Dialogue
{200}{}{Vaya, vaya, alguien nuevo en la nave. Eso siempre resulta interesante. ¿Te puedo ayudar en algo?}
{201}{}{Por hoy, en nada. Quizás otro día.}
{202}{}{Quizás puedas. ¿Me puedes decir qué es este lugar?}
{203}{}{Estás en el almacén de la nave, y yo soy su intendente. Soy el Caballero Raymond.}
{204}{}{Es un honor conocerte, Caballero Raymond.}
{205}{}{Ya veo.}
{206}{}{Ah, es un almacén... pensé que sería más interesante.}

{210}{}{¿Cómo puedo ayudarte?}
{211}{}{Vendré luego.}
{212}{}{¿Te puedo hacer unas preguntas?}
{213}{}{¿Sobre qué?}
{214}{}{Sólo tengo curiosidad.}
{215}{}{¿En qué te ayudo, hermano?}
{1215}{}{¿En qué te ayudo, hermana?}

{220}{}{Encontré una medalla de Valor. ¿Sabes algo al respecto?}
{221}{}{¿La Operación Anchorage? Sí, fue una de las mayores victorias de los Estados Unidos previas a la Gran Guerra. Nuestras fuerzas estaban frente a frente contra los Rojos en Alaska. Pero, eso no nos salvó de que nos bombardearan por completo...}
{222}{}{Parece que para ti, se trata mucho más que de una historia.}
{223}{}{La Hermandad del Acero tiene raíces entre familias militares, alguno de ellos incluso lucharon en esa batalla. ¿Sabías que la servoarmadura hizo su debut durante la Operación Anchorage? Hablando de la medalla - no le tienes demasiado apego, ¿cierto? Me gustaría agregarla a nuestra colección. ¿Qué quieres a cambio?}
{224}{}{¿De qué medalla se trata? Muéstramela.}
{225}{}{Te la traeré después.}
{226}{}{350 chapas.}
{227}{}{Trato hecho. Aquí tienes.}
{228}{}{Gracias..}
{229}{}{No quiero nada a cambio, sólo quiero ayudar a la Hermandad.}
{230}{}{Mis hermanos lo apreciarán mucho, gracias. Si algún día quieres hacer un trato conmigo, te daré un descuento.}
{231}{}{Eso suena bien, lo tendré en cuenta.}
{232}{}{Lo que necesito es practicar mis habilidades con las armas. Tengo batallas difíciles por delante.}
{233}{}{Entonces déjame ayudarte. Puedes entrar al campo de tiro, así puedes practicar.}
{234}{}{Justo lo que necesitaba...}
{235}{}{El Intendente ha reducido el precio de sus existencias en 10%.}

{240}{}{¿Qué puedes contarme sobre la Hermandad?}
{241}{}{Si quieres saber de nosotros, habla con los escribas o el general. Si no quieren hablar, entonces yo tampoco.}
{242}{}{Comprendo. Entonces haré eso.}
{243}{}{Entonces déjame preguntarte otra cosa.}
{244}{}{¿Me podrías recordar qué es este lugar?}
{245}{}{Estás en el almacén de la nave, y yo soy su intendente. Soy el Caballero Raymond.}
{246}{}{Gracias, ahora sí lo recordaré.}
{247}{}{¿Qué son esos cartuchos de 10mm? Son distintos, es la primera vez que los veo.}
{248}{}{Es mi propio invento. La bala consiste de una aleación nanoestructurada particularmente fuerte y una forma que penetra de forma inusual. Es efectiva contra enemigos bien acorazados. Aunque sea raro encontrar gente bien armada, vale la pena llevar un cargador de reserva.}
{249}{}{Ya veo.}

{250}{}{¿Puedo ver lo que vendes?}
{251}{}{Por supuesto. Te ofreceré lo mejor que tengo.}
{252}{}{¿Quieres comerciar? Lo siento, pero la Hermandad no hace trueques. Sólo tratamos con caravanas en las que confiamos. Pero si me das algo útil, quizás haga una excepción.}
{253}{}{¿Una excepción? ¿Qué tal si te compro una de esas armas poderosas?}
{254}{}{Los comandantes creen que entregar armas avanzadas o explosivos terminará siendo malo para nosotros. Por ahora, tendrás que conformarte con lo que tengo - hasta que te ganes nuestra confianza.}
{255}{}{¿Cómo puedo ganarme eso?}
{256}{}{Ayudándonos, por supuesto.}
{257}{}{Ya veo.}
{258}{}{De acuerdo, hablemos al respecto otro día.}
{259}{}{Acerca de las caravanas, podría convertirme en un maestro de caravanas.}
{260}{}{Claro que podrías, pero necesitamos a un proveedor habitual.}
{261}{}{No puedo engañarte, supongo...}
{262}{}{Tengo contactos por toda Arizona. Podría traerte algunas caravanas de alto calibre.}
{263}{}{¿Sí? Bien, entonces me convenciste. Te agregaré a nuestra lista de proveedores.}
{264}{}{Gracias.}
{265}{}{No te preocupes, tengo autorización de parte del General.}
{266}{}{Cierto, lo recuerdo. Entonces, cuentas con acceso total.}
{267}{}{Gracias.}
{268}{}{No seas así, Raymond. Todos saben que pueden confiar en mí, pregúntale a cualquiera.}
{269}{}{Hmm... De acuerdo, te agregaré a nuestra lista de proveedores.}
{270}{}{Gracias.}
{271}{}{No te preocupes, tengo autorización de la Escriba Suprema.}
{272}{}{No te preocupes, tengo autorización del Paladín Latham.}
{273}{}{Perdimos a uno de nuestros escuadrones por allá. Deberías hablar con el Paladín Latham al respecto, está bajando la rampa.}
{274}{}{Comprendo.}
{275}{}{Encontré esta chapa de identificación en las ruinas del Infierno.}

{280}{}{He encontrado unas chapas de identificación de la Hermandad. ¿Qué debería hacer con ellas?}
{281}{}{Hmm... cada una representa a un hermano caído. Es un terrible destino. Te daré 10 chapas por cada una que me traigas.}
{282}{}{Esas chapas me vendrían bien.}
{283}{}{No te cobraré por ellas, estaría mal aprovecharme de una tragedia.}
{284}{}{Gracias, cada una de ellas es importante para nosotros.}
{285}{}{Lo entiendo. Pero tengo más preguntas.}
{286}{}{De nada.}
{287}{}{El General Dixon me prometió una recompensa por un informe que le entregué.}

{288}{}{Así es. La tengo justo aquí, son 250 chapas, junto con tres estimulantes y un par de Rad-X. Firma aquí, por favor.}
{289}{}{Gracias.}

{290}{}{¿Tienes alguna mejora para mi lanzagranadas?}
{291}{}{Sí, tengo un cargador de tambor para ese modelo. Sólo uno. Te lo instalaré por }
{292}{}{ chapas.}
{293}{}{Genial. Eso me ayudará a sobrevivir. Tengo las chapas, Hazlo.}
{294}{}{En otro momento.}

{300}{}{Me parece que aquí debo recibir mi equipamiento.}
{301}{}{Así es. Bienvenido a la Hermandad.}
{302}{}{¿Qué recibiré?}
{303}{}{Tu equipamiento dependerá de tu rol y tu rango. Si quieres algo fuera del equipamiento estándar, lo tendrás que comprar o convencer a alguien que te lo preste para ciertas misiones. Pero, ya tienes acceso total para el almacén, y te daré un buen precio. Bien, ¿qué es lo que buscas?}
{304}{}{¿Puedo hacer esto otro día? Tengo que hacer una cosa. Nos vemos.}
{305}{}{Dame el equipamiento de Escriba.}
{306}{}{Genial. Aquí tienes: una pistola láser con munición adicional, un decodificador y un contador Geiger. Firma aquí, por favor.}
{307}{}{Dame el equipamiento de Paladín.}
{308}{}{¿Te gustan las armas grandes, no es así? Los jóvenes siempre buscan ser paladines. Aquí tienes: una ametralladora ligera junto a una caja de munición y una armadura de combate. Firma aquí, por favor.}
{309}{}{Dame el equipamiento de Caballero.}
{310}{}{Ah, eres del mismo rango que yo, muy bien. Aquí tienes: un cortador atómico, una superalmádena y unas botas de goma. Firma aquí, por favor.}
{311}{}{Dame el equipamiento de Explorador.}
{312}{}{Buena elección, dado que eres del yermo... Eh, perdón, no quería ofenderte. Aquí tienes: un lanzagranadas con munición, un guante eléctrico y un sigilante. Firma aquí, por favor.}
{313}{}{Gracias, Raymond.}
{314}{}{¿Eso es todo? Supongo que bastará.}

{320}{}{Aquí es donde tengo que entregar una servoarmadura perdida, ¿verdad?}
{321}{}{Ah, ¿la que estábamos esperando? ¿La tienes?}
{322}{}{La tengo... cerca. Espérame.}
{323}{}{Sí, aquí tienes. Se la regreso a ustedes, a sus verdaderos dueños.}
{324}{}{¡Pero mira como brilla el cromo bajo la luz! No hay nada como la tecnología del viejo mundo, y esto es una máquina preciosa... Cierto, gracias por la ayuda. La Hermandad lo agradece.}
{325}{}{Sufrió mucho daño en las ruinas del Infierno, por desgracia.}
{326}{}{Comprendo. Está bien, es posible reparar los daños, aunque me llevará unas semanas.}
{327}{}{¿Y si la necesito de nuevo?}
{328}{}{Agradecemos que la hayas regresado, pero la armadura le pertenece a la Hermandad, no tienes derecho a usarla. Aunque, puede que el general reconozca tus esfuerzos y te autorice, habla con él. Mientras tanto, tendré que empezar a repararla. ¿Qué idiota le arrancó esa parte...?}
{329}{}{Podrás ejercer tu derecho a llevar la servoarmadura... cuando termine de arreglarla. Carajo, quién pensó que sería una buena idea arrancar esa parte...}
{330}{}{Entonces volveré en un par de semanas.}
{331}{}{Sólo quiero saber si la podré usar después de entregarla.}
{332}{}{¿Qué clase de pregunta es esa? Eso es propiedad de la Hermandad del Acero. Si quieres usarla, necesitarás permiso - o mejor aún, ser uno de nosotros. Por ahora, tendrás que regresar la servoarmadura. No me hagas perder el tiempo.}
{333}{}{De acuerdo, aquí tienes. Ustedes son sus dueños.}
{334}{}{Claro, espérame y te la traigo..}
{335}{}{¿Así que esta es la que fue transportada a través del Infierno? Maravilloso. Anda, sal de ahí, no puedo esperar a revisarla.}
{336}{}{Esto llevará un rato. ¿Podemos hablar?}
{337}{}{Ah, claro, me la quitaré de inmediato.}

{340}{}{¿Ya reparaste la servoarmadura?}
{341}{}{No. No es tan fácil como parece.}
{342}{}{Comprendo.}
{343}{}{Claro que sí, ¡esta como nueva!}
{344}{}{¿Puedo usarla?}
{345}{}{Necesito usar la armadura, tengo una misión importante.}
{346}{}{Eso es una pregunta estúpida. Es propiedad de la Hermandad del Acero, si quieres usarla, necesitarás permiso - o mejor aún, ser uno de nosotros.}
{347}{}{De acuerdo...}
{348}{}{Por supuesto, está a tu nombre. Puedes ejercer tu sagrado derecho a portar una servoarmadura.}
{349}{}{Gracias... Genial, se ve mejor que nunca.}
