{100}{}{Ves a un centinela.}
{101}{}{Ves a un hombre que porta servoarmadura. Es impresionante.}
{102}{}{No es el mejor momento para ponerme a charlar.}
{103}{}{¿?}
{104}{}{Corres un gran riesgo al volver aquí.}
{105}{}{Bienvenido de vuelta. ¿Cómo te fue en la patrulla?}

#First dialogue
{200}{}{Alto. ¿Por qué estás aquí?}
{201}{}{No es nada, mejor me voy.}
{202}{}{Estaba explorando la costa y me topé con ustedes. ¿Qué es este lugar?}
{203}{}{Es mejor que no lo sepas. Muévete.}
{204}{}{Me parece que son un montón de malhumorados.}
{205}{}{¿Por qué demonios sigues aquí? No necesitamos a gente como tú. Lárgate y no vuelvas nunca.}
{206}{}{Em, claro.}
{207}{}{¿Y a dónde me puedo ir?}
{208}{}{No tienes mucha cabeza, ¿verdad? Nuestros escribas deberían usarte de sujeto de pruebas. Pero es mejor que no me ensucie las manos. Piérdete.}
{209}{}{Ah, claro. Ya entendí. Por supuesto.}

#Re-dialogue
{210}{}{Puedes pasar.}
{211}{}{Gracias.}
{212}{}{Bienvenido, hermano de armas.}
{1212}{}{Bienvenida, hermana de armas.}
{213}{}{Hasta luego, hermano.}
{214}{}{(observa el estado de tu armadura) Pasa. Necesitan otra olla en la cocina.}
{215}{}{Permiso para subir a bordo.}
{216}{}{¿Por qué me lo pedirías? Sube de una vez, hermano.}
{1216}{}{¿Por qué me pedirías eso? Pasa, hermana.}
{217}{}{Gracias hermano.}

{220}{}{¿Puedo hacerte algunas preguntas?}
{221}{}{Tengo prohibido charlar, especialmente si se trata de nuestra Hermandad.}
{222}{}{Comprendo. Adiós.}
{223}{}{¿Cuál es tu trabajo?}
{224}{}{¿Qué crees? Vigilo la rampa. No permitimos a nadie subir sin permiso. Tú tampoco lo tienes.}
{225}{}{¿Qué haces aquí?}
{226}{}{¿En dónde estamos?}
{227}{}{En nuestra base. Si no tienes nada más que preguntar, es mejor que te vayas. No deberías distraer a un guardia si está trabajando.}
{228}{}{Ya me voy.}
{229}{}{¿Al menos puedes decirme qué es este lugar?}
{230}{}{Ustedes son geniales. ¿Puedo unirme?}
{231}{}{Lo dudo.}
{232}{}{Maldita sea, entonces no.}
{233}{}{Eh... ¿Y si trabajo para ustedes?}
{234}{}{No creo que sea posible. Pero habla con el jefe de las patrullas, está en esa caseta de allá, quizás lo puedas ayudar con algo.}
{235}{}{Entiendo. Gracias.}
{236}{}{Espera. Tengo una pregunta.}

{240}{}{Tengo que hablar con el comandante.}
{241}{}{¿Para qué?}
{242}{}{Es... personal. ¿Puedo subir?}
{243}{}{No.}
{244}{}{Que mala suerte.}
{245}{}{Encontraré alguna forma, ya lo verás.}
{246}{}{Está bien, sube a bordo.}
{247}{}{Gracias.}
{248}{}{Mientras te encuentres a bordo, enfunda tu arma y no hagas nada estúpido. La oficina del general se encuentra en la cubierta central del barco, y el almacén está a la derecha de la entrada. No tienes permitido entrar a ningún otro lugar. ¿Entendido?}
{249}{}{Sí, lo entiendo.}

{250}{}{Me ha enviado el Maestro Hard de Two-Sun. Aquí tengo su recomendación.}
{251}{}{Tengo un informe de Ulysses Grant. Debe ser entregado directamente al General Dixon.}
{252}{}{El Paladín Latham me dio el permiso de hablar con el general.}
{253}{}{Me espera el General Dixon, se trata del fuerte en Hermosillo.}
{254}{}{Parece que tu base necesita algo de materia prima, tengo una caravana cerca. Busco hacer un trato.}
{255}{}{Soy parte de una caravana, tengo objetos que podrían interesarte.}
{256}{}{No, porque no tratamos con caravaneros independientes.}
{257}{}{Que pena.}
{258}{}{Entiendo. Pero debes limpiar tu armadura, soldado. Pareces una lata oxidada.}
{259}{}{El Paladín Latham me dio el permiso de hablar con el intendente.}
