{100}{}{Ves la computadora del general.}
{101}{}{Ves la computadora del Paladín Supremo.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Regresar al menú principal}

{210}{}{Expediente del Soldado Corwin}
{211}{}{Nombre: Alvin Corwin. Rango: Iniciado. Unidad: Candidato a Paladín. Salud: Normal.}
{212}{}{(Usando la identidad del Paladín Dixon, emite una orden para que Alvin pueda salir del barco)}
{213}{}{Se aceptó la orden.}
{214}{}{Perfecto. Le daré las buenas noticias a Alvin.}

{220}{}{Abre el mensaje de Dixon.}
{221}{}{"Nuestro mundo necesita fuerza - fuerza de verdad - para levantarse por sí mismo y seguir adelante, y sólo la Hermandad puede hacer eso. Pero nos hemos hecho nada más que escondernos, escondiendo nuestro poder de un mundo en el que reina el caso. California se enfrentó a los supermutantes, y fuimos nosotros los que defendieron la civilización de la destrucción total. Y ahora, nuestra orden debe reclamar lo que necesita. Lost Hills necesita la tecnología y los recursos de Sonora, y nosotros nos encargaremos de ello."}
{222}{}{Misión: "La Bandera de la Nación".}
       #el título es referencia a la película "Jailhouse Rock" de 1955
{223}{}{"Si queremos dominar a la salvaje Arizona, tenemos que tomar decisiones firmes. Es un territorio muy dividido, por lo que debemos reunir a todos bajo un sólo líder - nosotros. Si instalamos gobiernos amistosos a la Hermandad en localizaciones críticas, aseguraremos nuestra influencia sobre la zona. En el caso de que algún lugareño malagradecido se resista, tendremos que corregirlos como sea necesario. Les espera la reeducación."}
{224}{}{Proyecto: Pato Rengo.}
       #es un término político en Estados Unidos
{225}{}{Nuestro plan en Fénix es simple: establecer una marioneta de autoridad incuestionable, dentro de ella habrá un asesor oculto dirigido por un representante de la Hermandad. Es necesario que nadie afuera de la Hermandad sepa quién es el que manda realmente."}
{226}{}{Operación: Viento Bélico}
{227}{}{Nuestro puesto de avanzada en Nogales será un baluarte, controlará la frontera Mexicana y monitoreará a las amenazas detrás de la frontera. Hemos recibido informes de que luchan contra el ejército Mexicano - eso es maravilloso. Que vengan; porque la Hermandad no le teme a nadie."}
{228}{}{Nuestro Objetivo Principal}
{229}{}{"Nuestro objetivo principal es claro: acumular tanto la tecnología de Sonora como recursos nucleares para llevarlos a Lost Hills. Los abundantes recursos de Arizona potenciarán nuestras defensas contra los supermutantes y futuras amenazas. Como el Paladín Supremo de esta operación, sostengo la autoridad de tomar cualquier decisión que sea necesaria para hacer de esto una realidad."}

{240}{}{Lee el diario de Dixon}
{241}{}{"...El cuartel general en California no me trajo a Arizona para ser un salvador. Mi objetivo es recuperar lo que ha sido desaprovechado por los ignorantes que no saben lo que tienen. Estas personas desperdician la tecnología y los recursos de la preguerra, y nos corresponde a nosotros asegurarnos de que no se pierda nada más."}
{242}{}{"...Puede que los escribas parloteen sobre la paz, pero esta misión siempre se trató de conquistar. Los lugareños se aferran a sus reliquias, y nos niegan lo que nos pertenece por derecho. La conquista de Fénix derramó mucha sangre, porque así tenía que ser. Es porque la fuerza de la Hermandad sólo trae la paz cuando se aplica a la debilidad."}
{243}{}{"...Es cierto que Lost Hills nos obstaculiza tales medidas. Pero ¿de qué otra forma creen que Arizona les otorgará lo que necesitan? Flagstaff envía el uranio de sus minas a los talleres de Two-Sun, eso sale al yermo y llega a nuestro Puerto. Haremos lo que sea para que siga así. Estos flojos del yermo tienen el lujo de pensar en la moralidad; pero yo tengo una guerra que ganar."}
{244}{}{"...Las tradiciones de Arizona están demasiado arraigadas, y su gente se aferra a ellas con la tenacidad de las malas hierbas. Tras años de esfuerzo, nos establecimos en Fénix bajo el disfraz de Aaron y su culto, y aún así tenemos disidentes. Pusimos a los Hojalateros de Two-Sun en su lugar, pero se mantiene como una alianza frágil. El tiempo apremia ahora; nos llevaremos lo necesario - es decir, todo."}
{245}{}{Cierra el diario de Dixon.}
{246}{}{Sigue leyendo.}
