{100}{}{Ves la computadora de los escribas.}
{101}{}{Ves una computadora con acceso a la red pública.}
{102}{}{Has copiado la librería de los escribas con éxito.}
{103}{}{Ya copiaste los contenidos de la librería, no es necesario hacerlo de nuevo.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Volver al menú principal}

{210}{}{Búsqueda de los refugios de Vault-Tec}
{211}{}{Nuestros últimos informes indican que los refugios 25 al 28 se encuentran alrededor de Fénix. El Alto Mando de la Hermandad del Acero ordenó que estos refugios sean localizados y evaluados, además de transportar sus recursos y equipamiento al cuartel general. Serán utilizados para nuestro bien.}
{212}{}{}
{213}{}{}
{214}{}{Refugio 24}
{215}{}{Localización: Parque Nacional Otay, San Diego, California. Estado: Desconocido. Población: Desconocida. Es probable que se encuentre en una zona con altos niveles de radiación.}
{216}{}{Refugio 25}
{217}{}{Localización: Fénix. Está en excelente estado. Ahora se encuentra bajo el control de la Hermandad y los Seguidores del Fuego Santo lo utilizan como una base. Ciertas piezas de equipamiento fueron transportadas hacia Puerto Peñasco.}
{218}{}{Refugio 26}
{219}{}{Se encontraron los escombros de un refugio al oeste de Fénix. Sufrió daños graves durante el bombardeo nuclear, por lo que el refugio y su equipamiento quedaron destruidos por completo.}
{220}{}{Refugio 27}
{221}{}{Localizado. Se encuentra en medio de una excavación por los Seguidores del Fuego Santo, bajo las órdenes del paladín Ulysses Grant.}
{222}{}{Refugio 28}
{223}{}{Localización y condición desconocidas.}

{230}{}{Desarrollo: Cartucho de Projectil Nanoestructurado}
{231}{}{Debido a la escasez de cartuchos perforadores, se empezó una producción limitada de cartuchos 10mm, hechos a partir de metal nanoestructurado.}
{232}{}{La producción de los cartuchos es llevada a cabo por los Hojalateros en Two-Sun, bajo un contrato comercial estándar.}
{233}{}{}
{234}{}{Autosuficiencia Alimentaria}
{235}{}{Gracias a las plantaciones en Casa Nueva, nuestras necesidades alimentarias están cubiertas. Por el momento, se están exportando los cultivos excedentes.}
{236}{}{Desarrollo de Armas Nucleares}
{237}{}{A petición del cuartel general, empezamos con el desarrollo de armas nucleares. La documentación de los planos está completa y el material requerido se está extrayendo.}
{238}{}{Por razones de seguridad, logística y eficacia, el montaje final de estas armas lo realizan los representantes de la Catedral del Fuego Santo en Fénix bajo una estricta supervisión de la Hermandad.}
