{110}{}{Ves unos torpedos nucleares.}
{111}{}{Esta debe ser un arma poderosísima.}
{112}{}{Estos torpedos nucleares están listos para el ataque. }
{113}{}{Es mejor que me vaya, rápido...}
{114}{}{Tendría sentido haber hecho esto antes, pero ahora estoy del lado de la Hermandad.}

{120}{}{Es un torpedo nuclear. El panel de control debería estar cerca.}
{121}{}{No hay nada que arreglar.}
{122}{}{Esto es demasiado complicado, puede que hayan otras formas de activarlos.}
{123}{}{Has activado el temporizador del torpedo.}
{124}{}{Has desactivado el temporizador del torpedo.}
{125}{}{No es posible desactivar el temporizador.}

{150}{}{Quedan }
{151}{}{ segundos para la explosión.}
