{100}{}{Ves a un esclavo fugitivo.}
{101}{}{Ves a uno de los fugitivos que hicieron de estas ruinas su hogar.}

{110}{}{Los Hojalateros pagarán por lo que han hecho.}
{111}{}{¿Los Hojalateros también se llevaron a tu familia? Sé como se siente...}
{112}{}{Si odias a los Hojalateros, estás entre amigos.}
{113}{}{¿Quieres unirte a nosotros?}
{114}{}{Únetenos, necesitamos más guerreros.}
{115}{}{¿Tienes algún arma? ¿Comida, agua?}
{116}{}{¿Qué estás mirando?}
{117}{}{Jamás escuché del Banco Nacional de Arizona.}
{118}{}{¿Dinero? Lo usamos para la fogata. ¿Acaso lo necesitas?}
{119}{}{Lo único que nos queda es luchar por la libertad.}
