{100}{}{Ves a Jeff.}
{101}{}{Estás viendo al líder de los esclavos fugitivos.}
{102}{}{Pronto iremos al norte y en el camino les diremos a todos la verdad sobre los Hojalateros.}

{200}{}{Me contaron de tu llegada, me dejaste perplejo. ¿Quién eres, y por qué estás aquí?}

{201}{}{Sólo estoy explorando las ruinas, busco algo valioso...}
{202}{}{Llegaste a nuestro escondite, esquivaste nuestras trampas y te aventuraste en estas ruinas. ¿En serio piensas que te creeré? Última oportunidad. ¿Por qué estás aquí?}
{203}{}{Te estoy diciendo la verdad.}
{204}{}{Hmm... Parece que eres un chatarrero experimentado, por tu piel, creo que has caminado mucho a través del yermo... Te creeré, por ahora.}
{1204}{}{Hmm... Parece que eres una chatarrera experimentada, por tu piel, creo que has caminado mucho a través del yermo... Te creeré, por ahora.}
{205}{}{Me alegra que me hayas entendido.}
{206}{}{¡Es obvio que viniste a espiarnos! ¡Prendan la hoguera, chicos! Te calcinaremos ahí encima.}
{207}{}{¡Oye, no! ¡No hagas eso!}
{208}{}{}
{209}{}{}

{210}{}{Los Hojalateros me tenían de esclavo, conseguí escapar y necesito ayuda.}
{1210}{}{Los Hojalateros me tenían de esclava, conseguí escapar y necesito ayuda.}
{211}{}{Todos escapamos de los Hojalateros. Y hoy, buscamos impartirle justicia a nuestros opresores. Quizás puedas ayudarnos.}
{212}{}{Tienes razón, creo que podemos.}

{220}{}{Vengo en nombre de los Hojalateros. Se encuentran investigando el ataque a una caravana.}
{221}{}{Sí, fuimos nosotros... y más que eso, fue un triunfo. Planeamos el asalto durante un mes y lo conseguimos. Y ahora, los Hojalateros saben que no son los únicos en el yermo. Los suministros que saqueamos ayudarán a nuestra causa.}
{222}{}{Ya veo.}
{223}{}{Pensándolo bien, ya no puedo dejarte ir. ¿Por qué debería? Dame una razón.}
{224}{}{Sólo hago mi trabajo, no me importa a quién estés atacando.}
{225}{}{No me harás nada, porque hoy vas a morir.}
{226}{}{Nosotros no luchamos por chapas, sino porque tenemos una causa - vamos a salvar al yermo de ese malvado 'Progreso'. (escupe) }
{227}{}{[Más]}
{228}{}{Pero, a lo que no podemos salvar es la escoria como tú. ¡Mátenlo, chicos!}
{1228}{}{Pero, a lo que no podemos salvar es la escoria como tú. ¡Mátenla, chicos!}
{229}{}{¡Espera, no!}
{230}{}{Hmm... puede que nos seas de ayuda, como un espía entre los Hojalateros.}
{1230}{}{Hmm... puede que nos seas de ayuda, como una espía entre los Hojalateros.}
{231}{}{Sí, por supuesto.}

{240}{}{Puedes quedarte en nuestro escondite, por ahora. Pero si nos traicionas, te arrepentirás.}
{241}{}{De acuerdo.}

#Re-dialogue
{250}{}{Ah, eres tú. ¿Tienes algo que reportar?}
{251}{}{No nada.}
{252}{}{Comprendo. No tengo más preguntas.}

{260}{}{¿De dónde vinieron todos ustedes? Me da curiosidad.}
{261}{}{Una vez, todos fuimos esclavos para los Hojalateros. Nos enviaron a la Zona Prohibida para buscar tecnología antigua, pero algunos conseguimos escapar. No podíamos llegar muy lejos, pero pudimos asentarnos en estas ruinas, sobrevivimos como podemos.}
{262}{}{¿Qué los enviaban a buscar?}
{263}{}{Tecnología antigua, hay mucha que ya no funciona, y otra era demasiado peligrosa como para acercarse. A los fantasmas de esa tecnología no les gustaba nuestra presencia y empezaron a matar a cualquiera que se acercara, el hecho de que solo fueran esclavos no era importante.}
{264}{}{¿Cómo escaparon de la Zona Prohibida?}
{265}{}{Todos tenemos una historia distinta, pero casi todos recibimos ayuda de alguien que estaba antes de nosotros. Soy el último de la vieja resistencia.}
{266}{}{¿Por qué no se van de aquí?}
{267}{}{Somos como un viejo refugio, aferrándonos a una semblanza de la vida que conocimos. Los Hojalateros han destruido todo lo que amámabamos, pero intentamos mantener eso vivo, ya sea por nosotros o por los que todavía pueden sobrevivir en el yermo.}
{268}{}{¿Con 'sobrevivir', te refieres a los viajeros que atacas?}
{269}{}{Sí. Nuestros enemigos reciben suministros a través de las caravanas del yermo. No siempre los matamos - asustarlos es suficiente para que mantengan la distancia.}

#Attempt to smoke slaves out of Two-Sun
{270}{}{¿Cómo puedo ayudar a tu resistencia?}
{1270}{}{¿Cómo puedo ayudar a tu resistencia?}
{271}{}{Necesitamos un espía entre ellos, regresa a la base de los Hojalateros y encuentra información acerca de sus caravanas. Registra las computadoras del hangar que tienen. Si tienes éxito, te daré una recompensa.}

{280}{}{La computadora ZAX ha expulsado a los Hojalateros. También tienes que irte.}
{281}{}{¿Entonces era verdad? Cuando se me informó al respecto, tenía mis dudas, pero ahora sé que es real. El yermo celebrará este día. Ahora podemos volver a nuestros hogares y empezar de nuevo. Gracias por ayudarnos.}
{282}{}{De nada.}

{283}{}{Hard está muerto y los Hojalateros están en un caos total. ¿No es hora de que vayas a casa?}
{284}{}{¿Entonces era verdad? Cuando se me informó al respecto, tenía mis dudas, pero ahora sé que es real. No es fácil deducir qué significa esto para los Hojalateros, pero no se recuperarán tan fácilmente. Ahora podemos volver a nuestros hogares y empezar de nuevo. Gracias por ayudarnos.}
{285}{}{No fue nada.}

{286}{}{Los Hojalateros están planeando un asalto, corre mientras puedas.}
{287}{}{Son sólo rumores, no voy a correr por eso.}
{288}{}{Eso es problema tuyo.}

{289}{}{(Los has convencido, los esclavos se preparan y abandonarán Two-Sun.)}
{290}{}{[Hecho]}
{291}{}{Si los Hojalateros atacan, morirás en este sótano. No vas a conseguir nada si te mueres aquí adentro.}
{292}{}{¡Tenemos que seguir luchando! ¡Hay que castigar a los Hojalateros!}
{293}{}{Si eso quieres, Hazlo de forma estratégica. Mancha su nombre y no permitas que comercien. Ahora mismo, ustedes no tienen ni la energía ni el poder para seguir luchando.}
{294}{}{Eso depende de ti.}
{295}{}{Puede que tengas razón... No lo tenemos fácil. No tenemos comida, ni medicamentos, incluso las armas que conseguimos de la caravana no nos dieron mucha ventaja. Tendré que hablar con los demás y ver qué se decide.}
{296}{}{Buena idea.}
{297}{}{Los Hojalateros están preparando un ataque, no tienes ninguna oportunidad.}
