{100}{}{Ves a Clark, el mercader.}
{101}{}{Estás viendo al líder de una caravana. Su piel está chamuscada, lo que evidencia las interminables millas que ha viajado bajo el caliente sol.}
{102}{}{Cuídate, ten un buen viaje.}
{103}{}{Ya llegamos, más adelante está asentada la Hermandad del Acero.}

{200}{}{¿Qué quieres?}
{201}{}{No te pareces a los demás Hojalateros. ¿No eres uno de ellos, cierto?}
{202}{}{Estás en lo correcto. Soy el líder de mi caravana, tengo un contrato especial con los Hojalateros.}
{203}{}{¿Te puedo hacer unas preguntas?}

{210}{}{¿Qué necesitas?}
{211}{}{Nada.}
{212}{}{Quiero hacerte algunas preguntas.}

{220}{}{¿Qué es lo que haces aquí?}
{221}{}{Debo transportar carga alrededor del desierto. Los Hojalateros me confían eso más que a nadie.}
{222}{}{¿Transportar cosas? ¿Quién necesitaría eso?}
{223}{}{Aunque suene aburrido, hay varios lugares en el yermo que nos esperan con ansias, y sí que pagan bien por la carga.}
{224}{}{¿También tratas con esclavos?}
{225}{}{No, ya no. Solían traer esclavos de Fénix para despejar las ruinas y construir asentamientos, pero ya no es necesario. Hoy en día se necesitan más esclavos en el norte.}
{226}{}{¿En dónde está esa Fénix de la que hablas?}
{227}{}{¿En serio no sabes? Te has perdido de mucho. Es una gran ciudad al norte de aquí, tienes que seguir la Interestatal 10, es imposible no verla.}
{1227}{}{¿En serio no sabes? Te has perdido de mucho. Es una gran ciudad al norte de aquí, tienes que seguir la Interestatal 10, es imposible no verla.}
{228}{}{Gracias.}

{230}{}{¿Quiénes son los Hojalateros?}
{231}{}{Son una especie de culto, adoran a la tecnología y el progreso. Sueñan con cargar su consciencia en cuerpos robóticos. Aunque suene imposible, ya han conseguido implantarse tecnología en sí mismos. Sus habilidades técnicas no tienen igual en toda Sonora.}
{232}{}{¿Sabes qué planean hoy en día?}
{233}{}{No lo sé; yo solo transporto cosas. Pero los Hojalateros están planeando algo muy grande, no lo dudo.}
{234}{}{¿Qué te hace pensar eso?}
{235}{}{Están comprando un montón de uranio y esclavos. Deben estar amasando tecnología antigua, y eso significa que están invirtiendo mucho. Seguro es en Fénix o en otros lados. Ya puedo saborear las ganancias de mi caravana en los años que vienen.}
{236}{}{Te vas a dirigir al puerto que explotó. ¿Por qué?}
{237}{}{Pues, ahí ya no queda casi nada. Pero las plantaciones de Casa Nueva están por allá. Aunque, está por verse cuanto tiempo van a durar sin la protección de la Hermandad. Tarde o temprano, caerán bajo el control de los Hojalateros, o deberán irse.}
{238}{}{Parece que sus vidas se harán más difíciles de lo que ya eran. Cambiemos de tema.}

{240}{}{¿Qué tan difícil es transportar tu cargamento a través del yermo?}
{241}{}{Ya somos expertos en eso. Sabemos adaptarnos y esperamos a la temporada correcta para viajar.}
{242}{}{¿A qué clase de peligros te enfrentas allá afuera?}
{243}{}{Para empezar, está la deshidratación junto a la falta de comida. Nos abastecemos de agua en Casa Grande, lo que nos deja llegar al golfo. Y ahí desalinizamos el agua marina.}
{244}{}{¿Qué hay de cazar animales?}
{245}{}{Lo único que sobrevive en el desierto son los escorpiones, parece que escogieron reproducirse en Sonora. No solemos toparnos con los forajidos; hay poca gente por estos lados.}
{246}{}{Me llama la atención lo que dices, cuéntame más.}
{247}{}{Gracias por la información.}

{300}{}{Necesito llegar al Puerto de Acero.}
{301}{}{Jamás he escuchado de ningún Puerto de Acero.}
{302}{}{No digas eso, puedes confiar en mí.}
{303}{}{No te preocupes, soy parte de la Hermandad.}
{304}{}{Soy un Seguidor del Fuego Santo, no temas.}
{1304}{}{Soy una Seguidora del Fuego Santo, no temas.}
{305}{}{Bueno, quizás sepas de otros sitios.}
{306}{}{Ya nadie va hacia allá, créeme. Parece que a la Hermandad le pasó algo malo, porque su nave explotó como una maldita bomba atómica. Lo único que queda por allá es un cráter radioactivo, no sobrevivió nadie.}
{307}{}{Vaya, eso es muy malo.}
{308}{}{No lo creo.}

{310}{}{Bueno, entonces estás de nuestro lado. Hay que ser cautelosos; la Hermandad tiene muchos enemigos.}
{311}{}{¿Puedo ir con tu caravana?}
{312}{}{Debes estar aquí a las 6 de la mañana, no tardes. Podrás llevar 150 libras de carga como máximo. Haremos una parada en Casa Nueva, es el único asentamiento de camino a la Hermandad.}
{313}{}{Tengo todo, ya podemos irnos.}
{314}{}{Bien, ahí nos vemos.}
{315}{}{¡No vamos a cargar tus cosas! Suelta la basura innecesaria que tengas, o nos iremos sin ti.}
{316}{}{Bueno, entonces debo lidiar con el peso extra.}
{317}{}{Lo que tú digas.}
{318}{}{Muy bien, entonces prepárate, no será un viaje fácil.}
{319}{}{[Empieza el viaje]}
{320}{}{Quizás, o quizás no. Deben ser menos de 150 libras.}
{321}{}{Está bien, voy a revisar mi mochila.}
{322}{}{Te pagaré 1.000 chapas si me llevas contigo.}
{323}{}{¿Contaste mal? No parece que tengas tantas chapas.}
{324}{}{Déjame ver...}

#Other locations
{400}{}{Vamos a pasar la noche acá adentro. Tienes tiempo para andar por ahí. Pero no duermas más de la cuenta, o nos iremos sin ti.}
{401}{}{¿Qué puedes contarme sobre este lugar?}
{402}{}{Estamos en Casa Nueva, es como un oasis en medio del desierto. Por estos lados, no hay mejor lugar en donde vivir. Pero... las reglas son un poco estrictas. Respeta a los ciudadanos, y cuidado con lo que dices.}
{403}{}{Hasta luego.}
{404}{}{[Espera a que le caravana se vaya]}
{405}{}{No me esperes, yo me quedaré aquí.}
{406}{}{Como quieras. Pero recuerda que el yermo de Sonora es duro, y el viaje será difícil, aunque estés en una caravana.}
{407}{}{Entiendo. Nos vemos.}
