{100}{}{Ves a una Hojalatera.}
{101}{}{Ves a una de las habitantes de Two-Sun. Parece ser más civilizada que los demás.}
{102}{}{Has mejorado tu reputación con los Hojalateros.}

# First dialogue
{200}{}{(Ves a una mujer calva con un amplificador óptico bajo su ojo izquierdo) Otro salvaje del yermo con primitivas nociones sobre el Progreso. Nuestra conversación será irrelevante, muévase.}
{1200}{}{(Ves a una mujer calva con un amplificador óptico bajo su ojo izquierdo) Otra salvaje del yermo con primitivas nociones sobre el Progreso. Nuestra conversación será irrelevante, muévase.}
{201}{}{Como digas.}
{202}{}{Creo que te estás perdiendo de mucho.}
{203}{}{Puede que te sorprenda mi opinión sobre el Progreso.}
{204}{}{Soy parte de la Hermandad del Acero, puede que eso te haga cambiar de parecer.}
{205}{}{Después de todo lo que he hecho, esperaba que confiaran más en mí.}

{206}{}{Mis datos no sugieren eso.}
{207}{}{Está bien}
{208}{}{(pausa) No estoy en desacuerdo.}
{209}{}{Veamos si tenemos algo en común.}

# Re-dialogue
{210}{}{Establece tu pregunta.}
{211}{}{No tengo nada que decir. Adiós.}
{212}{}{Tengo otra pregunta.}

{213}{}{¿Por qué no quieres hablar conmigo?}
{214}{}{Los extranjeros con un bajo coeficiente de desarrollo no merecen nuestra confianza. Una excepción yace en los beneficios comerciales, especialmente si se trata de productos alimenticios. ¿Posees algún nutriente?}
{215}{}{Déjame ver si tengo algo que comer en la mochila.}
{216}{}{No te daré nada.}
{217}{}{Creo que merezco unas respuestas por el regalo.}

# Questions
{220}{}{Los Hojalateros compran esclavos. ¿Por qué?}
{221}{}{Se requiere labor para lograr el Progreso. La ausencia de los esclavos ralentizarían nuestros avances. Eventualmente, reemplazaremos a los esclavos con robots, pero requiere de tiempo y recursos, cuya disponibilidad es baja.}
{222}{}{Háblame del 'Progreso'.}
{223}{}{Se trata de alcanzar una perfección social y tecnológica similar a los estándares de la preguerra. En esta época, el Progreso es esencial para la continua existencia de la humanidad como especie.}
{224}{}{Ya veo. Tengo otra pregunta.}
{225}{}{}
{226}{}{¿Sabes algo acerca de los esclavos de la Villa?}
{227}{}{No. Deberías conversar al respecto con el Maestro Hard, es nuestro líder.}
{228}{}{¿Estás de acuerdo con una práctica tan inhumana?}
{229}{}{Las consideraciones éticas son algo secundario. El Progreso exige sacrificios. El avance de la humanidad es más valioso que la vida de unos salvajes del yermo.}

{230}{}{¿Cuál es tu trabajo aquí?}
{231}{}{Me encargo de los trabajadores del hangar. Preparo nutrientes y mantengo el orden en el área residencial.}
{232}{}{Ah, ¿entonces los Hojalateros tienen familias?}
{233}{}{Familia... Muchos Hojalateros solían tener una familia. Ahora, tales lazos son irrelevantes.}
{234}{}{¿Por qué?}
{235}{}{Adoptamos niños del yermo y los programamos para que sirvan a nuestra colectiva. La personalidad es irrelevante. Una familia no es necesaria.}
{236}{}{Algunos Hojalateros parecen ser distintos a los demás.}
{237}{}{Nuestra sociedad está dividida en niveles. Cada nivel tiene su propio conjunto de conocimiento y tecnología. Sólo los veteranos reciben las operaciones caras y complejas.}

{240}{}{¿Por qué desconfías tanto de los extranjeros?}
{241}{}{La confianza es inmaterial. En cuanto a desarrollo, poseemos medidas superiores a casi cualquier habitante del yermo. Debido a esto, los forasteros únicamente contribuyen como esclavos, y ocasionalmente como contactos comerciales.}
{242}{}{Pero, ustedes tienen conexiones con otros asentamientos.}
{243}{}{Correcto... Hasta hace poco, éramos una comunidad cerrada, le restringíamos el acceso a cualquier extranjero.}
{244}{}{¿Y qué pasó?}
{245}{}{Escasez de alimentos, proyecciones matemáticas acerca de nuestro futuro y el contacto con una comunidad altamente desarrollada. Pero no puedo hablar al respecto con un extranjero.}
{246}{}{Interesante.}
