{110}{}{Soy un asistente personal a su servicio.}
{111}{}{Lo siento, no puedo ayudarle.}
{112}{}{Por favor, mantenga limpio el hangar.}
{113}{}{Usted no se encuentra en nuestra lista de empleados... es una pena.}
{114}{}{Por favor, abandone el hangar si no lo tiene permitido.}
{115}{}{No estoy programado para seguir sus órdenes. De verdad lo siento.}
{116}{}{Por favor, indique el propósito de su visita.}
