{100}{}{Ves a Romeo Six.}
{101}{}{Estás viendo a uno de los Hojalateros. Es muy joven, casi un adolescente.}
{102}{}{Utiliza la habilidad de Doctor para extraer el implante.}
{103}{}{Has conseguido remover el implante de su cuerpo, al seguir las instrucciones del Hojalatero.}
{104}{}{¿Un forastero? ¿Aquí? Quizás debería examinar mis armas...}

# First dialogue
{200}{}{(Ves a un Hojalatero de ojos enormes; te observa con cautela) Provienes del yermo, deberías ser consciente de que no nos agradan los forasteros en Two-Sun. No deberías agotar nuestra paciencia.}
{201}{}{}
{202}{}{Hola, pequeñín. Quiero hablar contigo.}
{203}{}{Aléjate, no tenemos permitido hablar contigo. (se da la vuelta y se aleja de ti)}
{204}{}{Eso no es muy amable de tu parte...}
{1204}{}{Esa no es forma de tratar a una señorita...}
{205}{}{Me lo dices como si no estuvieras muy convencido. ¿Te sientes sólo?}
{206}{}{(se detiene, desconcertado) La Colectiva considera que los forasteros están sub-desarrollados y por ende no es productivo comunicarse con ellos... a no ser que nos otorgue beneficios.}
{207}{}{Eso es lo que piensa la Colectiva. Pero, ¿qué piensas tú?}
{208}{}{Oye, ¿a quién le dices sub-desarrollado?}
{209}{}{Esa es la típica respuesta que esperaba de un primitivo. Incluso si tu aldea poseyera un generador de fusión y tus respectivas autoridades utilizaran armas láser, seguirías siendo lo mismo, un primitivo.}
{210}{}{Si la comunicación con un 'primitivo' no es productiva, entonces, ¿por qué me sigues hablando? ¿Acaso dudas lo que te dicen?}
{211}{}{He oído suficiente de esta basura. Adiós...}

{212}{}{¿Estás sugiriendo que partamos pronto?}
{213}{}{La Colectiva te considera un elemento destructivo y sugieren evitar el contacto.}
{214}{}{Claro, ganarse la confianza de ustedes no es para nada fácil. Adiós.}
{215}{}{¿Quién es el destructivo? ¿Tú, o yo? No toleraré esto, si vuelve a ocurrir.}
{216}{}{(indeciso) Primero... Primero, debes hablar con el Maestro Hard.}
{217}{}{Genial, lo tendré en cuenta.}
{218}{}{Sí... No...}
{219}{}{¿No?}

# Dialogue at the toilet
{220}{}{No puedo hablar en este momento. Nos vemos detrás del hotel a las 22:00.}
{221}{}{Vale.}
{222}{}{Este lugar no es el adecuado. Podemos vernos detrás del hotel.}
{223}{}{De acuerdo.}
{224}{}{Allí no nos escucharán.}
{225}{}{La última vez que hablamos de tu Colectiva, parecías estar indeciso. ¿Te preocupa alguna cosa?}
{226}{}{Creo que sí, me preocupa. La Colectiva nos enseña que nuestro pasado no es relevante, que debemos olvidarlo y vivir en el futuro por el bien del Progreso. Pero no puedo simplemente abandonar mi... mi... mi niñez.}
{227}{}{¿Tu infancia? ¿Así que no eres de aquí?}

{228}{}{La entrada a Two-Sun solía estar prohibida para los forasteros. Pero una vez que la población estuvo en declive, la Colectiva se vio obligada a reconstruir la población utilizando niños de otros asentamientos. Se me aceptó y reeducó mientras tenía cinco años de edad. Desde ese entonces que no he visto a mis pad... progenitores.}
{229}{}{Quizás pueda encontrar a tus padres, debo viajar mucho y quizás los encuentre.}

{230}{}{¿Harías eso? ¿De verdad? Genial... Mi expediente describe que mis progenitores fallecieron durante una guerra en Casa Grande, ve hacia allá y habla con sus habitantes. Sólo quiero descubrir lo que ocurrió el día que fuimos separados.}
{231}{}{¿Por qué no le preguntas a los demás Hojalateros y ya?}
{232}{}{Irrumpir en el orden no es algo que complazca a la Colectiva, si desobedeces la opinión de la mayoría, se te puede castigar de forma grave. Tales castigos ya se han llevado a cabo y no quiero averiguar cuánta paciencia la Colectiva es capaz de dispensarme.}
{233}{}{ }
{234}{}{ }
{235}{}{Quizás pueda ayudarte, pero viajar a otra ciudad no es nada fácil.}
{236}{}{Podría dispensar una parte de nuestra tecnología, si eso te interesa. Pero no esperes demasiado, no tengo acceso a los objetos más sofisticados.}
{237}{}{Vale, voy a buscar a tus padres.}
{238}{}{(se alegra) ¡Genial! Esto es... (esconde su sonrisa y hace una cara neutral) Estaría de lo más agradecido... Es mejor que nos separemos antes de levantar sospechas. No le digas a los demás acerca de esto.}
{239}{}{No hay de qué.}
{240}{}{La verdad es que no sé si vuelva a este lugar, lo siento.}
{241}{}{Eso es... una pena... Pero, si alguna vez te encuentras en Casa Grande, por favor, recuérdame. Es mejor que nos separemos, pretendamos que esta conversación jamás tuvo lugar.}
{242}{}{No hay de qué.}

{250}{}{(sorprendido) Eh, bueno... Podríamos... ¿Podríamos hablar en privado?}
{251}{}{No hay ningún problema con eso.}
{252}{}{Ah, así que ahora necesitas algo, ¿no?}
{253}{}{(mira a su alrededor) ¿Podríamos hablar en privado?}

{260}{}{Detrás del hotel, se ubica un baño, nos veremos en su interior a las 10:00 PM.}
{261}{}{Vale.}
{1261}{}{Ah, ¿una cita con un Hojalatero? Qué intrigante. Nos veremos allí.}
{262}{}{Eh, ¿no estarás sugiriendo que tengamos una cita ahí dentro, verdad? Claro que no.}

# Dialogue when the quest is open
{300}{}{¿Tienes algo que contarme?}
{301}{}{Volveré cuando tenga algo que decirte.}

# Quest - family died
{302}{}{He encontrado a tu familia, pero... fallecieron. Los Hojalateros no tuvieron nada que ver, no te preocupes.}
{303}{}{Justo lo que pensaba... La Colectiva siempre nos ha dejado claro que no debemos aferrarnos al pasado. Además, ¿quién sabe si hubiéramos podido entendernos después de tantos años de separación? Por fin puedo dejar esto atrás, gracias a ti. Ya no permitiré que mis sentimientos irrumpan con mis decisiones.}
{304}{}{Eso es decisión tuya.}

# Quest - GG found a family
{310}{}{Tu familia sigue viva en Casa Grande.}
{311}{}{¿¡Están vivos!? ¡Cuéntamelo todo!}
{312}{}{Quizás no te agrade su historia, según ellos, los Hojalateros te raptaron durante un asalto.}
{313}{}{¿¡Mis hermanos de metal me han mentido!? Es justo lo que temía... al Maestro Hard no le gustará que haya indagado en el tema. Mucho menos ahora...}
{314}{}{Hice lo que debía, lo que harás es decisión tuya.}
{315}{}{No, necesito pruebas, o nuestro trato se acabó.}
{316}{}{Vale. ¿Qué necesitas?}
{317}{}{Claro, ¿quieres volver con ellos?}
{318}{}{Hasta que resuelva esto, no puedo volver a Two-Sun. Necesito reencontrarme y hablar con mi familia, pero sé que el Maestro Hard no me dejará ir tan fácilmente.}
{319}{}{Hablaré con Hard, quizás tu familia pueda venir a Two-Sun.}
{320}{}{Ni siquiera yo puedo convencerlo. ¿Crees que tú podrás?}
{321}{}{Lo intentaré, espérame aquí.}

{322}{}{Tienes que salir de aquí.}
{323}{}{Vale, te ayudaré a escapar, ¿qué debemos hacer?}
{324}{}{Podría intentar unirme a una caravana, pero lo primordial es remover el chip subcutáneo de rastreo, se encuentra bajo mi cuello. ¡Ayúdame a extraerlo! No puedo hacer eso por mi cuenta.}
{325}{}{Bueno, hagámoslo...}

{326}{}{¿Cuál es tu plan?}
{1326}{}{¿Qué tienes pensado hacer?}
{327}{}{Espérame un poco más.}
{328}{}{Pero, entonces tu propia gente te va a castigar.}
{329}{}{Jamás he encajado aquí... Quizás sean mis emociones las que hablan, pero preferiría arriesgar mi posición y regresar con mi familia.}

# Quest - Hard was convinced
{330}{}{Hard está de acuerdo con que veas a tu familia. Ya no debes ir en contra de la Colectiva.}
{331}{}{¿¡Cómo conseguiste eso!? Ni siquiera sus socios más cercanos consideran que discutir con el Maestro Hard no es para nada fácil. Y ni siquiera eres uno de nosotros. Sorprendente... O sea, gracias. Por fin podré lidiar con esto, y es todo gracias a ti. Esto significa mucho para mí.}
{332}{}{Me alegra que esto haya tenido una solución.}

{335}{}{Tu chip ya no es ningún problema, puedes irte de Two-Sun.}
{336}{}{Ni siquiera me dolió. Sabía que llegar a un acuerdo con el Maestro Hard era imposible. Por fin podré lidiar con esto, y es todo gracias a ti.}
{337}{}{Cuídate.}

{340}{}{Creo que deberías saber esto, los Hojalateros no te raptaron, sino que tus padres te ofrecieron a cambio de que la bomba de agua fuera arreglada.}
{341}{}{Mis padres... ¿¡me *vendieron*!? Esto lo cambia todo... al Maestro Hard no le gustará que haya indagado en el pasado, más aún después de todo. Sin embargo, te lo agradezco, ahora puedo dejar esto atrás.}
{342}{}{Es momento de ponerle un fin a esto y como dices tú, dejarlo atrás.}
{343}{}{Es tu decisión.}

# Final dialogue
{400}{}{Gracias por toda tu ayuda.}
{401}{}{De nada.}

{410}{}{Me prometiste una recompensa.}
{411}{}{Claro, ¿qué necesitas?}
{412}{}{Dame un momento, necesito pensarlo.}
{413}{}{Toma, aquí tienes. Listo, nuestro trato ya está hecho.}
{414}{}{Un trato es un trato. Cuídate.}

{420}{}{Unas chapas me vendrían bien.}
{421}{}{Necesito unas células de microfusión.}
{422}{}{Un puño neumático, los Hojalateros son conocidos por ellos.}
{423}{}{Una de sus lanzas neumáticas.}
{424}{}{¿Podrías traerme unas gafas de visión nocturna?}
{425}{}{Una pistola láser, eso sería perfecto.}
{426}{}{De verdad me hacen falta unos explosivos.}

{430}{}{¿Qué tal si me das una célula de fusión nuclear para un generador?}
{431}{}{Oh, no, no puedo. Esas baterías son lo más valioso que fabricamos. Su producción y uso se planifican con un año de antelación.}
{432}{}{Hmm. Comprendo.}
