{100}{}{Ves a un explorador.}
{101}{}{Ves a un superviviente de la Hermandad, parece ser un explorador.}
{102}{}{Algún día, la Hermandad regresará a Arizona. Es solo cuestión de tiempo.}

#Dialogue
{200}{}{(mientras pasa por tu lado, el desconocido te observa con cautela) Hmm, creo que te he visto en otro lado.}
{201}{}{Quizás. No eres de aquí, ¿verdad?}
{202}{}{No. Y tú tampoco. Dos extranjeros en una ciudad desconocida. Que gran coincidencia, ¿no lo crees?}
{203}{}{Claro que sí. Pero tengo algo que hacer aquí. No te importa eso, ¿verdad?}
{204}{}{No. Adelante.}
{205}{}{Adiós.}
{206}{}{}
{207}{}{}
{208}{}{(te asiente la cabeza)}
{1208}{}{Después de ti.}
{209}{}{[Haz lo mismo.]}
{1209}{}{Qué amable.}

{210}{}{Ah, ya me acuerdo. Eres tú, te había visto hace poco antes de la explosión el Puerto de Acero. Que gran coincidencia, ¿no?}
{211}{}{¿Qué explosión? Yo no tuve nada que ver en eso.}
{212}{}{¿Y quién te está culpando?}
{213}{}{No lo sé.}
{214}{}{¿Y por qué tantos nervios? Relájate, dudo que alguien como tú haya podido esquivar las defensas de la nave y detonar los torpedos. Ni siquiera el personal de la base tenía acceso al área.}
{215}{}{Eh, bueno. Es sólo que, em, parecía que sospechabas de mi. Nos... nos vemos. Ten un buen día.}
{216}{}{¿Y qué tal si fui yo el que lo hizo explotar?}
{217}{}{Cualquiera podría decir que lo hizo. Pero, ¿por qué? No puedo creer que un salvaje del desierto pueda infiltrarse en una nave bien protegida y activar los torpedos. Eres un campesino, ¿cómo vas a adquirir tales habilidades?}
{1217}{}{Cualquiera podría decir que lo hizo. Pero, ¿por qué? No puedo creer que una ramera del desierto pueda infiltrarse en una nave bien protegida y activar los torpedos. Eres una campesina, ¿cómo vas a adquirir tales habilidades?}
{218}{}{Sé que suena fantasioso, igual que en las historietas viejas. Supongo que eso resuelve cualquier sospecha.}
{219}{}{Eso creo. Pero, es mejor que tenga cuidado contigo...}
{220}{}{Eso no será necesario. Adiós.}
{221}{}{Deberías esconderte luego de lo que pasó. La Hermandad pasó a la historia. Supéralo.}
{222}{}{Eso es cierto, pero Puerto Peñasco no era más que una base muy lejos del cuartel general. Puede que algún día regresemos.}
{223}{}{Pero eso no será pronto, y para ese entonces, nadie los querrá aquí. Piensa en ti mismo, soldado.}
{224}{}{Pensé que venir aquí era lo más seguro, pero parece que estaba mal. No volverás a saber de mí. Adiós.}
{1224}{}{Pensé que venir aquí era lo más seguro, pero parece que estaba mal. No volverás a saber de mí. Adiós.}
{225}{}{Adiós, explorador.}
{226}{}{Piérdete y no vuelvas nunca.}
