{100}{}{Ves a un esclavo.}
{101}{}{Ves a un trabajador forzado. Está exhausto, pero sigue vivo.}

{102}{}{¿Buscas a tus amigos? Probablemente ya los enviaron a la Zona Prohibida.}

{110}{}{¡Matáme, por favor! Ya no aguanto más...}
{111}{}{No tengo permitido hablarle a los forasteros.}
{112}{}{Para los Hojalateros, todos somos reemplazables.}
{113}{}{Solía estar en una pandilla, pero me capturaron y terminé aquí.}
{114}{}{Extraño a mi pandilla.}
{115}{}{Cuando estaba con mi pandilla, jamás pensaba en mis víctimas.}
{116}{}{Los Hojalateros están obsesionados con la tecnología antigua.}
{117}{}{Esconde esa computadora, o los Hojalateros te la arrancarán del brazo.}
{118}{}{La Zona Prohibida es un lugar letal.}
{119}{}{¿Tienes algo de comida?}
