{100}{}{Ves a un esclavo.}
{101}{}{Ves a un esclavo perplejo. No parece que comprenda en dónde está o qué ocurre.}

{110}{}{Los Hojalateros quieren que deshabilitemos los robots, ¿¡pero cómo demonios haremos eso!?}
{111}{}{¡Malditos Hojalateros! Me agarraron y me lanzaron a este infierno.}
{112}{}{Han muerto tantas personas. Seguramente no seremos los últimos.}
{113}{}{Andrés es la única razón por la que seguimos vivos. Pero ni siquiera eso nos va a durar.}
