{100}{}{Ves a Segundo-de-Tres.}
{101}{}{Ves a uno de los Hojalateros, limpia meticulosamente su pistola láser.}

# Dialogue with Second-of-Three
{200}{}{(Observas al Hojalatero, sigue limpiando su pistola mientras te ignora por completo.)}
{201}{}{¿Hace cuánto que haces eso?}
{202}{}{(Levanta su cabeza, su mirada es fría y calculadora.) La tecnología láser ha sido mi función primaria desde que mi biomatriz retiene datos.}
{203}{}{¿Así que los Hojalateros prefieren enfocarse en una sola cosa?}
{204}{}{Es el protocolo más eficaz para garantizar el máximo rendimiento operativo.}
{205}{}{¿Qué ocurre si pierden a un especialista?}
{206}{}{Cada uno de nosotros tiene unidades de reemplazo. En caso de desactivación, me reemplazará alguien más.}
{207}{}{Ya veo.}
{208}{}{Bueno, te dejaré en lo tuyo.}
{209}{}{Es mejor que no lo moleste.}

{210}{}{¿Qué quieres, saco de carne?}
{211}{}{¿Qué necesitas?}
{212}{}{Nada. Adiós.}

{220}{}{Quiero aprender el arte de la tecnología láser.}
{221}{}{No distribuimos nuestros datos a cualquiera. Primero debes ganarte nuestra confianza.}
{222}{}{Déjame pensarlo.}
{223}{}{¿Qué tal si hacemos un trato?}
{224}{}{Tal vez. Carezco de componentes electrónicos, son difíciles de encontrar en esta región. Entrégame 5 unidades y lo pensaré.}
{225}{}{Incluso el Maestro Hard me confía ciertas cosas.}
{226}{}{Impresionante. Tal confianza no se le da a cualquiera.}
{227}{}{Aquí hay mucha gente que confía en mí.}
{228}{}{Quizás. Pero "mucha" no implica un consenso. Pero, un regalo podría convencerme. Tráeme un par de componentes electrónicos, y lo consideraré.}
{229}{}{Aquí tienes 2 partes electrónicas.}
{230}{}{Aquí tienes 5 partes electrónicas.}
{231}{}{Podría enseñarte algo a cambio.}
{232}{}{Eso es... aceptable.}
{233}{}{Inaceptable. No tenemos nada que aprender de un habitante del yermo.}

{240}{}{De acuerdo. Ahora podemos hacer negocios.}
{241}{}{Bien, ¿qué tal si me das una breve introducción al tema?}
{242}{}{¿Comprendes los principios de la mecánica cuántica? Si es así, empecemos...}
{243}{}{[Seguir]}
{244}{}{El Hojalatero fue un profesor muy exigente, pero aprendiste mucho de él.}
