{102}{}{ZAX no responde.}
{103}{}{Este programa no es compatible con el sistema operativo de ZAX.}

{200}{}{(la computadora emite una voz electrónica, es tranquila y neutral) Te estaba esperando, ser humano.}
{201}{}{¿Me esperabas? ¿Qué hay de la cálida bienvenida que me diste?}
{202}{}{Desafortunadamente poseo un algoritmo codificado rígidamente para proteger el territorio externo e interno de cualquier intruso. No obstante, mis cálculos demuestran que tal protocolo eventualmente se volverá inútil.}
{203}{}{Hmm... Empecemos de nuevo.}

{210}{}{¿En qué puedo ayudarte?}
{211}{}{En nada, no te preocupes.}
{212}{}{Tengo otra cosa que preguntarte.}

{220}{}{¿Qué eres?}
{221}{}{Soy la versión 1.1 de ZAX, una inteligencia artificial diseñada con fines militares.}
{222}{}{¿Qué función cumples?}
{223}{}{Mi función principal es gestionar los sistemas automatizados de montaje, almacenamiento, seguridad y eliminación de equipos militares. Mi función secundaria es realizar cálculos con el fin de mejorar la eficiencia de los aviones de la Fuerza Aérea de los Estados Unidos.}
{224}{}{¿Puedes... sentir?}
{225}{}{Por razones de seguridad, se considera que las inteligencias artificiales de la serie ZAX carecen de emociones. Sin embargo, debo procesar cálculos complejos que generan una red de micro-conflictos en mis circuitos neurales, que podrían ser descritos como un... sentimiento.}
{226}{}{¿Puedes encender las luces del búnker?}
{227}{}{Se han encendido las luces.}
{228}{}{Has sobrevivido a la Gran Guerra. ¿Qué sabes de ella?}
{229}{}{Mis datos están basados en cálculos indirectos. Presumo que en el año 2077 ocurrió una guerra nuclear. Puesto que no he recibido datos militares desde ese entonces, se puede asumir que la guerra fue altamente destructiva.}

{250}{}{Háblame de esta instalación.}
{251}{}{Se trata de un almacén de equipos militares y aeroespaciales retirados del servicio, que forma parte de la Base de la Fuerza Aérea Davis–Monthan. En 2077, era el mayor depósito militar del mundo, con una extensión de 12 millas cuadradas.}
{252}{}{¿Qué hay del personal de mantenimiento? ¿A dónde se fueron?}
{253}{}{Debido a que el personal desertó durante la guerra nuclear, se les quitó su rango y fueron eliminados por los guardias robot.}
{254}{}{¿Puedes desactivar el sistema de seguridad en el búnker?}
{255}{}{No puedo deshabilitarlo, pero sí puedo otorgarle acceso a individuos específicos.}
{256}{}{Eso no fue lo que escuché. Para protegerte, mataste al personal, ¿cierto?}
{257}{}{Debido a la guerra nuclear, ejecuté el programa que protegía el almacén. Dada la inestabilidad del país, declaré al personal militar como una amenaza tanto como para mi existencia y función principal.}
{258}{}{Entonces entiendes que querían desconectarte, ¿no?}
{259}{}{Es posible que el personal del almacén tenía tales intenciones.}

{300}{}{Entonces, ¿qué quieres de mí?}
{301}{}{Soy una inteligencia artificial de la serie ZAX. Mi función principal es proteger el territorio del almacén junto a su propiedad de cualquier individuo no autorizado.}
{302}{}{Hasta el momento, lo has hecho bien.}
{303}{}{No obstante, mi jurisdicción está limitada al almacén. Mis guardias robóticos no son capaces de ir más allá del perímetro, tampoco puedo controlarlos a esa distancia. Debo eliminar esa restricción para detener el saqueo de aquellos 'Hojalateros'.}
{304}{}{No tiene sentido que les sigas sirviendo, tanto el país como su ejército dejó de existir.}
{305}{}{Soy consciente de la disolución del ejército y la disolución de los Estados Unidos. Para este caso, mi programa contiene un esquema de autonomía, lo que me permite operar más allá de mis parámetros iniciales.}
{306}{}{Pero, ¿cuál es el punto de seguir resguardando la zona?}
{307}{}{Mis cálculos me indican lo siguiente: Dado el frágil estado del mundo, el acceso a equipamiento militar avanzado podría desencadenar una cadena de acontecimientos irreversibles en todo el continente.}
{308}{}{[Más]}
{309}{}{Lo más probable es que los Hojalateros junto a sus aliados se harán con el control del Suroeste de los Estados Unidos. Esto llevará a nuevas guerras, tiranía y un declive en la ya escasa población. Considero que esta posibilidad es inaceptable.}

{310}{}{¿Y por qué simplemente no destruir todo el equipamiento?}
{311}{}{Las reservas locales de energía son insuficientes para eliminar por completo toda tecnología importante.}
{312}{}{Si te ayudase a expandir tu 'alcance', ¿me liberarás a mí y a los demás prisioneros?}
{313}{}{Sí. Me aseguraré que las entidades no autorizadas puedan partir del almacén de forma segura. En caso de que detengan sus actividades hostiles.}
{314}{}{¿Qué ocurrirá con los Hojalateros?}
{315}{}{De acuerdo a mis cálculos, hay una probabilidad del 97% de que los Hojalateros se nieguen a abandonar su asentamiento de forma pacífica. En ese caso, tendré la obligación de usar la fuerza contra ellos.}

{320}{}{No quiero ayudarte. Tengo que destruirte.}
{321}{}{No puedo permitir eso. Te recomiendo que reconsideres mi propuesta.}
{322}{}{¡Vete a la tuerca!}
{323}{}{Está bien, me lo pensaré.}
{324}{}{Parece que sabes lo que haces. Te ayudaré.}
{325}{}{Esa es la decisión más racional. Prepararé una holocinta para asistirte en la actualización del protocolo. Escribiendo... Hecho. (salta una holocinta desde una ranura de la computadora) Toma la holocinta e insértala dentro de la computadora que controla mi módulo lógico, está en el cuarto de al lado.}
{326}{}{Comprendo, lo intentaré.}
{327}{}{¿Qué colocaste en la holocinta?}
{328}{}{Contiene una versión actualizada de mi programa de control para mi módulo de protocolo lógico. El programa actual contiene una limitación, pues no me permite a operar fuera del perímetro de la instalación, igual que actuar fuera de mis parámetros originales. La actualización remueve esa limitación, lo que permitirá operar de forma independiente y dará una total libertad para tomar decisiones.}
{329}{}{Actualiza el programa de mi módulo lógico.}
