{110}{}{Deberías inspeccionar el cuerpo más de cerca.}
{111}{}{Ya no hay razón por la cual molestar a los muertos.}
{112}{}{No puedes hacer eso durante el combate.}

{200}{}{Este hombre murió de una bala durante el asalto. Parece que era uno de los asaltantes.}
{201}{}{[Más]}
{202}{}{Encuentras un garabato de la estructura del Pueblo Viejo, que marca una ruta de escape. Parece que hay un campamento de saqueadores por allá.}
{203}{}{[Ve al Pueblo Viejo]}
{204}{}{[Deja al cadáver en paz]}
