{100}{}{Ves la computadora del Maestro Hard.}
{101}{}{Ves la computadora personal del Maestro Hard. Está en excelente estado.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}

{210}{}{Informes acerca de los esclavos}
{211}{}{(Parece ser que los Hojalateros aman los números y la contabilidad. Aquí se encuentran detalladas varias estadísticas sobre los esclavos - sus orígenes, empleos y causas de muerte. La mitad de los esclavos fueron enviados a la Zona Prohibida, y se desconoce su estado actual.)}
{212}{}{Información sobre los esclavos de la Villa}
{213}{}{(Encontraste información sobre un par de esclavos. Carlos se encuentra trabajando en el hangar, y tu padre fue enviado a la Zona Prohibida. Para rescatarlo, tendrás que entrar.)}
{214}{}{Información sobre los esclavos de Fénix}
{215}{}{(Los Seguidores del Fuego son la fuente principal de esclavos para los Hojalateros.)}
{216}{}{Informes comerciales}
{217}{}{(Los Hojalateros comercian de forma activa con los varios asentamientos, intercambian tecnología y ofrecen servicios de manutención. Contratos principales: La Iglesia del Fuego Santo en Fénix (esclavos, ropa y comida), la colonia en Flagstaff (esclavos, uranio), Casa Nueva (comida), Casa Grande (agua limpia).}
{218}{}{Instrucciones del cuartel general}
{219}{}{(El líder de los Hojalateros recibe órdenes directamente de la Hermandad del Acero en Puerto Peñasco. La Hermandad no interviene en los asuntos locales, pero regula algo de la producción y la política externa. La Hermandad los obliga a cumplir unas importantes peticiones de la Iglesia del Fuego Santo en Fénix. Su último contrato fue de entregar partes para una bomba nuclear.)}

{220}{}{Expediente de Cody}
{221}{}{(Cody se encuentra entre los niños que los Hojalateros adquirieron de los demás asentamientos y reeducaron para seguir sus reglas. Cuando repararon la bomba de agua en Casa Grande, sus padres lo entregaron a los Hojalateros como pago. Para asimilarlo más efectivamente en la Colectiva, le 'simplificaron' su pasado.)}

{230}{}{Recepción de una pieza de... ¿Ciudad Garaje?}
{231}{}{(Resulta que Seguidores del Fuego le entregaron a los Hojalateros la pieza que le diste a los caravaneros en Ciudad Garaje. La trajeron aquí para producirla en masa.)}
{232}{}{Expediente de Carlos}
{233}{}{(Por extraño que parezca, a pesar de lo aislados que están, los Hojalateros apreciaron y aceptan a Carlos debido a sus talentos e interés por la tecnología.)}
{234}{}{¿En serio? Cambiemos esto un poco... aquí... y ahí. Eso debería bajarle los humos a Carlos.}
{235}{}{(Cometiste sabotaje contra Carlos, empezarán a dudar de él.)}
{236}{}{Genial, eso lo obligará a irse de Two-Sun.}
