{100}{}{Ves una computadora de emergencia.}
{101}{}{Ves una computadora, tiene un letrero: "Usar en caso de emergencia"}
{102}{}{ZAX se apoderó del sistema, ya no puedes ejecutar el protocolo de emergencia.}
{103}{}{La computadora no funciona.}
{104}{}{Conectaste el primer puerto. Introduce la segunda tarjeta de acceso.}
{105}{}{Conectaste el segundo puerto.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}

{210}{}{Ejecutar el protocolo de emergencia.}
{211}{}{¡Cuidado! El protocolo de emergencia desencadena una ráfaga de pulsos electromagnéticos para desactivar cualquier equipo electrónico dentro del búnker. Esto es irreversible y sólo debería usarse en una emergencia grave.}
{212}{}{¿Y esto no es una emergencia grave?}
{213}{}{Entendido.}
{214}{}{¿Está seguro de que desea iniciar con el protocolo de emergencia?}
{215}{}{No, cancelar.}
{216}{}{Sí, Hazlo.}
{217}{}{Por razones de seguridad, apague la computadora y quite las tarjetas de acceso.}
{218}{}{Iniciando el protocolo de emergencia...}
{219}{}{¡Apúrate!}
