{102}{}{¡No me empujes!}
{103}{}{¡No me toques!}
{104}{}{Tu armadura está asustando al niño.}

#Response - reputation >5
{110}{}{¿Vas a protegernos, verdad?}
{111}{}{¡Mata a los saqueadores! ¡Hazlos sufrir!}
{112}{}{No quiero que los saqueadores vuelvan.}
{113}{}{Todos los forasteros son malos. ¡Todos!}
{114}{}{¡Yo sólo quiero ver a mi mamá!}

#Response - reputation <-5
{115}{}{Das más miedo que los saqueadores.}
{116}{}{¡Aléjate de mí! Eres peor que ellos.}
{117}{}{Me dijeron que no le hablara a gente como tú.}
{118}{}{Los forasteros son malos, eso dicen los adultos.}
{119}{}{¡Yo sólo quiero ver a mi mamá!}

#Response - reputation from -5 to 5
{120}{}{¿Quién nos va a proteger si vuelven los saqueadores?}
{121}{}{Tenía mucho miedo... Todavía tiemblo.}
{122}{}{Tengo miedo de que vuelvan los saqueadores.}
{123}{}{¿Por qué los forasteros tienen que ser así?}
{124}{}{¡Sólo quiero ver a mi mamá!}
{125}{}{¿Quieres jugar conmigo?}
