{100}{}{Ves a un campesino.}
{1100}{}{Ves a una campesina.}
{101}{}{Ves a uno de tus paisanos.}
{1101}{}{Ves a una de tus paisanas.}
{102}{}{Algún día, te haré lo mismo.}
{103}{}{ }

#Floating lines
{110}{}{Alguien tiene que echar a los Chacales del desierto.}
{111}{}{Me hubiera encantado ver cómo echaban a esos malditos Chacales.}
{112}{}{¿Escuchaste lo que pasó con los Chacales? No podemos confiar en nadie, ni en los Rangers...}

{113}{}{Después de lo ocurrido, dudo que nos llevemos bien con los chatarreros.}
{114}{}{Ahora los babosos de Ciudad Garaje se enteraron de cómo hacemos las cosas.}
{115}{}{No perdonaré a los chatarreros.}

{116}{}{Nos vendría bien una ayuda de los Rangers.}
{117}{}{Incluso los Rangers están teniendo problemas.}
{118}{}{Los Rangers son duros, aunque si no compartimos, se irán.}

{119}{}{¡Ya le daremos su merecido a esos imbéciles de Flagstaff!}
{120}{}{Dicen que las cosas están muy mal en Flagstaff. ¡Vamos a celebrarlo!}
{121}{}{Flagstaff sigue expandiéndose, eso nos pone en peligro.}

{122}{}{Las caravanas siguen trayendo malas noticias del sureste.}
{123}{}{Creo que está ocurriendo algo en el sureste. Ojalá que no nos afecte.}
{124}{}{Parece que estallará una guerra en el sureste.}

{125}{}{Desearía que el Señor Andrés estuviera con nosotros.}
{126}{}{Nuestro nuevo líder no tiene la fuerza que se necesita para mandarnos.}
{127}{}{No deberíamos cuestionar las decisiones de nuestro líder.}

{128}{}{Ojalá que alguien rescate a la Señora María.}
{129}{}{Las cosas estarán difíciles después de lo que pasó con la Señora María.}
{130}{}{Gracias al cielo, ¡María ha vuelto!}

{131}{}{¡Gloria a nuestro salvador!}
{132}{}{El Señor Andrés crió a un héroe.}
{133}{}{El diputado de Andrés es muy prometedor.}

{134}{}{¡Shh! Ese mocoso bastardo de Andrés anda tramando algo.}
{135}{}{El mocoso del Señor Andrés es un demonio.}
{136}{}{En los tiempos difíciles, se necesita a un líder fuerte.}

{1131}{}{¡Gloria a nuestra salvadora!}
{1132}{}{El Señor Andrés crió a una heroína.}
{1133}{}{La diputada de Andrés es muy prometedora.}

{1134}{}{¡Shh! Esa mocosa estúpida del Señor Andrés anda tramando algo.}
{1135}{}{La mocosa del Señor Andrés es una diablilla.}
{1136}{}{En los tiempos difíciles, se necesita a un líder fuerte.}

#Response
{200}{}{Siempre te recibiremos con los brazos abiertos.}
{201}{}{Gracias, nos has salvado a todos.}
{202}{}{Eres una inspiración para cada uno de nosotros.}

{210}{}{Tengo cosas que hacer, lo siento.}
{211}{}{Estamos trabajando por el bien del pueblo, ¿y tú?}
{212}{}{Deja de interrumpirnos y ponte a trabajar.}

{220}{}{No quiero que asustes a los niños con esa cosa.}
{221}{}{¡Aléjate de mí!}
{222}{}{Asustarías a cualquiera con esa cosa.}
{223}{}{¿Por qué nos asustas con esa cosa? Deberías hacérselo a nuestros enemigos.}
{224}{}{¿Cómo te atreves a venir aquí con esa cosa puesta?}
{225}{}{¿Crees que esa armadura asustará a nuestros enemigos?}
{226}{}{Esa cosa parece una lata, ¿no te da calor?}
{227}{}{¿Por qué no te pones a limpiar el huerto con nosotros?}
{228}{}{Si esa armadura es tan fuerte, ¿por qué no la usas para arreglar las casas?}
{229}{}{Pareces un maldito tanque, no vayas a chocar con algo.}
