{100}{}{Ves a un merodeador.}
{101}{}{Ves a un forastero, registra el área buscando algo de valor.}

{110}{}{Nos vamos. Ni te molestes en seguirnos.}
{111}{}{Ya nos vamos, pero vendrán otros.}
{112}{}{Eso era todo, no queremos nada más.}
{113}{}{Ya no tenemos nada que hacer aquí.}

{200}{}{¡Oye! ¿Vives aquí? Entonces habla, queremos saber en dónde están las llaves del granero.}
{1200}{}{¡Oye! ¿Vives aquí? Entonces habla, queremos saber en dónde están las llaves del granero.}
{201}{}{¿Por qué quieren entrar ahí?}
{202}{}{Sabemos que hay mucha harina de maíz ahí dentro, y este es el único granero que no saquearon. Así que hagamos esto; tú encuentras las llaves, nos das la harina, y nadie saldrá herido.}
{203}{}{¿Tanto valor tiene para ti la harina?}
{204}{}{¿Acaso no sabes nada del yermo? No hay más que tierra estéril, y los únicos que consiguen tener buenas cosechas son ustedes. Hay rumores de que fertilizan la tierra con sangre humana. Pero sabes qué, no me importa. Sólo danos la harina y nos iremos. ¿Entendido?}
{205}{}{¿Así que ustedes no participaron en el asalto?}
{206}{}{No. Nos enteramos de que ocurrió, así que vinimos a llevarnos lo que hayan dejado. La comida es demasiado valiosa como para dejar que se pierda.}
{207}{}{Si fuera a darles la harina, ¿se marcharán?}
{208}{}{Claro, tienes mi palabra. Unas diez bolsas nos bastarán; no podemos llevarnos más.}
{209}{}{La Villa está lista para lincharlos, ¿saben? Ya están repartiendo las horcas en la plaza.}
{210}{}{Sí, claro. Los únicos que quedan en el pueblo son sólo niños y los viejos. ¿Crees que les tenemos miedo?}
{211}{}{Puede que sólo sean ancianos y unos niños, pero cuándo se forma una turba, las cosas se ponen feas.}
{212}{}{¡Mierda! Te dije que no valdría la pena venir hasta acá. Bueno, vámonos...}
{213}{}{Aquí están las diez bolsas. ¿Será suficiente para que nos dejen en paz?}
{214}{}{Nos basta. No quiero que nos persiga un montón de campesinos rabiosos. Es hora de irnos...}
{215}{}{Lo pensaré. Ya vengo.}
{216}{}{Sí, vete...}
{217}{}{Los merodeadores han abandonado la Villa pacíficamente.}
{218}{}{Trae la harina y nadie saldrá herido.}
{219}{}{Te estoy diciendo la verdad.}
{220}{}{¡Fuera de aquí!}
{221}{}{Bueno, ya lo veremos...}
{222}{}{Ya, ya entendí.}
{223}{}{La Villa se encuentra bajo la protección de los Rangers. Es mejor que se vayan.}
{224}{}{¿Los rangers? ¿Están aquí? Mierda, salgamos corriendo...}
{225}{}{¡No quiero volver a verlos!}
{226}{}{Lárguense y no vuelvan nunca.}
