{100}{}{Ves al hermano de Chris.}
{101}{}{Ves al hermanito de Chris.}
{102}{}{¿Cómo puedes controlar eso? Da miedo...}

{200}{}{Hola.}
{201}{}{Adiós.}
{202}{}{¿Qué estás haciendo?}
{203}{}{Ayudo a reconstruir la casa, se dañó durante el ataque.}
{204}{}{¿Has encontrado algo?}
{205}{}{Sí, los saqueadores soltaron unas cosas raras. (te enseña unos casquillos usados y unas balas de 10mm)}
{206}{}{Creo que me llevaré eso, no deberías tocar las cosas de los forasteros.}
{207}{}{No, nada.}

{210}{}{Hola, em, solo estoy flojeando...}
{211}{}{Me parece que le estás llevando un almuerzo a alguien.}
{212}{}{¿En serio piensas que me...? Está bien, te creeré, por ahora.}
{213}{}{¡Es mi comida!}
{214}{}{[Sigue al niño y averigua a dónde va]}
{215}{}{No te preocupes, te creo.}
{216}{}{Busco a tu hermano Chris, ¿sabes en dónde está?}
{217}{}{No. No sé.}
{218}{}{Está bien. Seguiré buscando.}
