{100}{}{Ves al emisario.}
{101}{}{Ves al emisario de la Hermandad del Acero.}
{102}{}{Puede dar por terminada nuestra alianza, emisario.}
{103}{}{Están bajo nuestra confiable protección.}

# First dialogue
{200}{}{Saludos, soy el emisario de la Hermandad del Acero. Entonces, ¿fuiste tú quien convenció a la tribu a una alianza? Bien hecho, ambos podremos beneficiarnos con nuestra cooperación.}
{201}{}{¿Eres el único que vino?}
{202}{}{No te preocupes, mi escuadrón está acampando en el yermo, no muy lejos. Pensamos que nuestra presencia podría... alarmar a los demás campesinos. Si es necesario, puedo llamarlos por radio.}
{203}{}{Gracias, emisario. Debo irme.}
{204}{}{Menos mal, porque o sino nuestra alianza se hubiera acabado antes de empezar siquiera.}

{210}{}{Saludos.}
{211}{}{Debo irme.}
