{110}{}{Este taller de barro es un orgulloso ejemplo de lo que puede hacer la artesanía local. Aún queda un poco de arcilla para hacer platos nuevos.}
{111}{}{Este taller de barro muestra lo mejor de las habilidades de la Villa, pero ya no queda arcilla.}
{112}{}{Conseguiste fabricar algunos utensilios, aunque nunca te habrían dejado entrar aquí.}
{113}{}{Parece que la Villa solía intercambiar su alfarería con los asentamientos vecinos...}
