{100}{}{Ves a Beatriz.}
{101}{}{Ves a una necrófaga con un vestido que anteriormente era lindo.}
{102}{}{}
{103}{}{¿Ves a ese guapetón detrás de la barra? Hace unos buenos huevos... Espero entiendas lo que quiero decir.}
{104}{}{Oye, ¿Qué le pasó a José? ¡No puede dejarnos plantados!}
{105}{}{¡Estoy tan feliz! ¡Tan, tan feliz!}

{200}{}{Hola, guapo. Has hecho un revuelo pasándote por aquí. ¿Cómo va todo?}
{1200}{}{Hola. Has hecho un revuelo por aquí. ¿Qué necesitas?}
{201}{}{Adiós.}
{202}{}{¿Quién eres?}
{203}{}{¿Que quién soy? ¡Soy Beatriz Aguirre! Mi nombre solía estar en cada marquesina de California. Ay, como han cambiado los tiempos.}
{204}{}{¿Qué estás haciendo aquí?}
{205}{}{Ese guapetón de la barra me prometió un trago. Es el único consuelo que me queda en la vida.}
{206}{}{Me envía José Solís. Está intentando volver a reunir a su grupo de mariachis.}
{207}{}{¿Así que el viejo está en sus andanzas de nuevo? ¡Me gusta! Bien, estoy dentro. Veamos qué tal nos sale.}
{208}{}{Te llamaré cuando sea el momento. Adiós.}
{209}{}{Quiere que vayas directo al Pueblo Viejo. ¿Puedes ir ahora?}
{210}{}{¡Adelante! ¡A nuestro destino!}
{211}{}{Sí, vamos.}
{212}{}{¡Ardo con el deseo de estar en el escenario otra vez! ¿Me ayudarás a llegar al Pueblo Viejo?}
{213}{}{Sí, vamos.}
{214}{}{Ahora no.}
{215}{}{¡Ardo con el deseo de estar en el escenario otra vez!}
{216}{}{Luego hablaremos de esto, Beatriz.}
{217}{}{Ven conmigo. El escenario del Pueblo Viejo te espera.}
{218}{}{Espérame aquí. Volveré pronto.}
{219}{}{Gracias por tu ayuda. Cantaré una canción tristona en tu honor.}
{220}{}{Buena suerte.}
