{100}{}{Ves a Fernando.}
{101}{}{Ves a un necrófago con un traje viejo. Le cuelga un bigote mexicano de un color grisáceo de la cara.}
{102}{}{Hola. Los robots no dejan que nadie entre a la estación, la resguardan como si fuera su mamita.}
{103}{}{Hola. ¿Que qué hago aquí? No mucho, como puedes ver.}
{104}{}{¿Qué está pasando? ¿Por qué cancelaron el concierto?}
{105}{}{¡Hola, compadre!}
{1105}{}{¡Mis respetos, señorita!}

{110}{}{Nos alejamos demasiado, el Pueblo Viejo está por el otro lado.}
{111}{}{¿Podría ser esta la legendaria Estación Fantasma?}
{112}{}{La estación volvió a la vida, y con ella la ciudad también. Es todo gracias a ti.}
{113}{}{Espero que Bonita empiece a funcionar pronto.}
{114}{}{¡Ten cuidado! Por aquí suelen haber robots de la patrulla fronteriza.}
{115}{}{Más adelante hay un acantilado que lleva al Río Otay.}
{116}{}{Mira por dónde pisas, el puente es peligroso.}
{117}{}{Lo creas o no, en los fines de semana por aquí todo estaba lleno. Y ahora no hay ni un alma.}
{118}{}{Esto es la cuenca del Río Otay. En sus días era hermoso.}
{119}{}{Ese edificio gigante de allá es un hospital militar. Ya lo saquearon hace tiempo.}
{120}{}{}
{121}{}{No tengo ganas de ir allá.}
{122}{}{Nos acercamos al epicentro de la explosión. No deberías estar mucho rato por acá.}
{123}{}{Antes de la guerra, Little Italy era conocida por sus cafeterías... pero también por sus gánsteres y proxenetas.}
{124}{}{¿Tomaremos un atajo por el parque? Buena idea, hay menos radiación, pero hay peligros.}

{200}{}{A su servicio, señor.}
{1200}{}{A su servicio, señorita.}
{201}{}{Adiós.}
{202}{}{¿Quién eres?}
{203}{}{Mi nombre es Fernando.}
{204}{}{¿Qué haces aquí?}
{205}{}{No mucho, como puedes ver.}
{206}{}{Me envió José Solís, intenta reunir de vuelta a su vieja banda de mariachis.}
{207}{}{Buena idea, estoy dentro. ¿Cuándo tocamos?}
{208}{}{Todavía no lo sé. Espérame aquí.}
{209}{}{Vamos ahora mismo. Te llevaré directo al Pueblo Viejo.}
{210}{}{Será difícil atravesar las ruinas yo sólo. Te sabes el camino, ¿cierto?}
{211}{}{Sí, vamos.}
{212}{}{No estará mal tocar en el escenario de nuevo. ¿Me llevarás al Pueblo Viejo?}
{213}{}{Sí, vamos.}
{214}{}{No, ahora mismo no.}
{215}{}{¿Sí?}
{216}{}{Nada. No importa.}
{217}{}{Ven conmigo. El escenario del Pueblo Viejo te espera.}
{218}{}{Espérame aquí. Ya vuelvo.}
{219}{}{Gracias por la ayuda, compadre. Tocaré una marcha fúnebre en tu honor.}
{1219}{}{Gracias por la ayuda, señorita. Tocaré una marcha fúnebre en su honor.}
{220}{}{Sí, pásala bien.}
