{100}{}{Ves a Gonzo.}
{101}{}{Ves a un necrófago resplandeciente con una mirada enloquecida. Parece ser hostil.}
{102}{}{Gonzo no te está poniendo atención.}
{103}{}{¡Argh-r-r!}
{104}{}{Fue culpa del necrófago. Gomer no tener nada que ver.}

{200}{}{Hrr-r-r... h-humano... necrófago... miedo...}
{201}{}{Soy tu amigo. Quiero ayudarte.}
{202}{}{... amigo... amor... vida...}
{203}{}{Sí, sí, tus amigos necrófagos están preocupados por ti. Vamos, ellos van a cuidar de ti.}
{204}{}{Gonzo... querer... ir amigos...}
{205}{}{Vamos ahora mismo, antes de que cambies de parecer.}
{206}{}{No, no, ahora no. Espérame aquí.}
{207}{}{¡Ahh, estás loco! ¡Me asustas!}
{208}{}{Vida. Y muerte. ¡Tu muerte!}
