{100}{}{Ves a Rutger.}
{101}{}{Ves al líder de los Comerciantes de Ultramar.}
{102}{}{¡Silencio! Hablaremos en el campamento.}
{103}{}{Rutger ha regresado al campamento caravanero.}
{104}{}{¡No te me acerques, mutante! ¡Te mataré, joder!}

{200}{}{Esperaba a ver cualquier cosa, excepto a un humano.}
{201}{}{Los necrófagos me enviaron a ayudarte.}
{202}{}{Los mutantes nos plantaron una emboscada. Por suerte, los vimos justo a tiempo y nos escondimos aquí. No piensan atacarnos por ahora, pero es sólo cuestión de tiempo. ¿Puedes sacarnos de aquí sin que se den cuenta?}
{203}{}{Creo que puedo. Después de todo, pude llegar aquí.}
{204}{}{Genial. Entonces vamos un paso a la vez. Primero rescata a mis subordinados.}
{205}{}{Vale.}
{206}{}{Voy a distraer a los mutantes mientras tú sacas a los guardias. Será más difícil escondernos de los supermutantes si estamos juntos.}
{207}{}{Vale.}
{208}{}{Soy el último, ¿Cierto? ¡Entonces vámonos de aquí!}
{209}{}{Vamos.}
{210}{}{Es demasiado peligroso si nos vamos ahora. Esperemos aquí un momento.}
{211}{}{Vi a los mutantes marcharse por la carretera. Pero podría ser una trampa, intenta rescatar a mis subordinados primero.}
{212}{}{Dudo que podamos salir de aquí sin ser vistos. ¿Y si atacamos en vez de esperarlos a ellos?}
{213}{}{No puedo arriesgar a que ellos mueran. Primero seamos listos. Primero, rescata a los guardias.}
{214}{}{Pronto habrán más humanos aquí que necrófagos. Parece que necesitas ayuda.}
