{100}{}{Ves a un necrófago.}
{101}{}{Ves a uno de los muchos necrófagos.}

{102}{}{El bar se siente aburrido sin música, ¿No crees?}
{103}{}{¡Gracias por la música!}

{110}{}{¿Conoces a Talius?}
{111}{}{Bueno, él no es como nosotros, es un mutante.}
{112}{}{Talius predica la palabra de Dios.}
{113}{}{Yo creía en Dios, e iba a misa los fines de semana.}
{114}{}{Pero luego de tantos años de inmortalidad, ya no creo en nada.}
{115}{}{No dejes que nadie se meta en tu alma.}
