{100}{}{Ves a un necrófago ciego.}
{101}{}{Ves a uno de los necrófagos, sentado en una silla de ruedas.}

{110}{}{¿Quién eres? Identíficate.}
{111}{}{Déjame tocar tu rostro.}
{112}{}{¿¡Un normalucho!? ¡No me toques!}
{113}{}{¡Por favor, no me hagas daño!}
{114}{}{¡Deja a Dayglow en paz!}

{120}{}{¿Quién eres? Identíficate.}
{121}{}{Conozco a todos los necrófagos en este infierno. Pero no te conozco.}
{122}{}{Eres un necrófago. Yo soy un necrófago. ¿Por qué no nos hemos visto antes?}
{123}{}{He estado en la oscuridad por una eternidad.}
{124}{}{¿Cómo es Dayglow? Descríbemela.}

