{100}{}{Ves a un Comerciante de Ultramar.}
{101}{}{Ves a uno de los guardias caravaneros.}
{102}{}{¡Silencio! Lo más importante ahora es escaparnos de estos jodidos mutantes.}
{103}{}{¡Demonios! Ahora sí podemos andar tranquilos.}
{104}{}{Vale, te sigo. Sabes cómo sacarnos de aquí sin que nos vean, ¿cierto?}
{105}{}{Sí, buena idea. Necesitamos ir despacio para que no nos vean.}
{106}{}{El Comerciante de Ultramar ya está a salvo.}
{107}{}{¿Qué demonios creen que hacen? ¡Un poco más y les partiré la cara!}

{110}{}{Gracias por salvarnos.}
{111}{}{Esos supermutantes nos habrían hecho polvo si no hubiera sido por ti.}
{112}{}{Fuiste un golpe de suerte.}
{113}{}{El camino de regreso será igual de difícil...}
{114}{}{Espero que haya un bar por aquí.}

{120}{}{Rutger está muerto. ¿Quién negociará con los necrófagos?}
{121}{}{Sin Rutger, el camino de vuelta será aún más jodido.}
{122}{}{Ahora que Rutger está muerto, seguramente ni nos paguen.}

{130}{}{Luego de la explosión en la isla, está claro que ya no es posible sacar NADA de ahí.}
{131}{}{Gustavo está intentando echarnos de aquí. ¡Está loco!}
{132}{}{Butler consiguió entrar a la base militar. ¡Pronto estaremos nadando en chapas!}
{133}{}{}
{134}{}{Los necrófagos se están escabullendo como las cucarachas al encender la luz. Nunca he visto nada igual. Al menos es bueno para el negocio.}
