{100}{}{Ves a Raymond, un necrófago autista.}
{101}{}{Ves a un necrófago. Está contando y ordenando cosas.}
{102}{}{El necrófago felizmente toma tu caja y la agrega a su colección.}
{103}{}{¡Esa es mi caja, Bern!}
{104}{}{¡Cajas! ¡Cajas! ¡Cajas!}
{105}{}{Robar el holodisco enoja mucho al necrófago. Nadie en San Isidro te va a perdonar por esto.}
{106}{}{¡DEVUÉLVEME MI CAJA, BERN!}
{107}{}{Has regresado el holodisco a su dueño. Tu reputación ha vuelto a la normalidad.}
{108}{}{¡Esa caja es MÍA, Bern!}

{110}{}{¡Bern! ¡Bern! ¡Bern!}
{111}{}{¡Estos tipos se quedarán aquí todo el día, Bern!}
{112}{}{¡No avisaron que nos iban a visitar, Bern!}
{113}{}{¡Nadie los invitó a pasar el fin de semana aquí, Bern!}
{114}{}{¡82! ¡82 moldadientes!}
{115}{}{Un moldadiente, dos moldadientes, tres moldadientes...}
{116}{}{Cinco. Tres. Cinco. Nueve. Dos. Seis. Dos.}
{117}{}{Una caja, dos cajas, tres cajas...}
{118}{}{Cajas, cajas, cajas...}
{119}{}{¡Devuélveme mis cajas!}
