{100}{}{Ves a un necrófago.}
{101}{}{Ves a un necrófago sin nada fuera de lo común.}

{102}{}{Ay, gracias, llegaste justo a tiempo.}
{103}{}{¡Oye, la comida está fría! Chale. Dámela.}
{104}{}{¿La pasas bien repartiendo comida? Gracias.}
{105}{}{¡Justo lo que quería!}
{106}{}{Gracias. Pero no tengo propina.}
{107}{}{(}
{108}{}{) de los clientes han recibido sus órdenes.}
{109}{}{Éste cliente ya recibió su orden.}

{110}{}{¡Virgencita! ¡Un humano!}
{111}{}{¿Un piel suave en Dayglow? ¡Lo veo y no lo creo!}
{112}{}{¿Qué se creerán estos normales?}
{113}{}{Justo lo que nos faltaba, más pieles suaves.}
{114}{}{Incluso aquí, los suavecitos nos molestan.}

{115}{}{Podemos confiar en éste normalucho.}
{116}{}{¿Un humano en Dayglow? ¡Estás loco!}
{117}{}{Los normales cometieron un error. Necesitan tiempo para abrir los ojos.}
{118}{}{Quizás no todos los pieles suaves sean malos.}
{119}{}{Sólo queremos vivir lejos de los pieles suaves.}

{120}{}{Incluso aquí, los suavecitos nos molestan.}
{121}{}{Vamos, adivina mi siguiente línea.}
{122}{}{Dayglow es una ciudad maravillosa.}
{123}{}{Qué mal que Harold no está con nosotros. Se fue al norte.}
{124}{}{¡Que nadie se mueva! Se me cayó el cerebro... Jeje, es mi chiste favorito.}
{125}{}{Extraño mi hogar en Necrópolis.}
{126}{}{Necrópolis debe estar más muerta que nunca.}
{127}{}{Siento escalofríos al recordar la mirada de Set.}
{128}{}{¿Que dónde está mi cabello? Me lo dejé en el 77. ¡Jajaja!}
{129}{}{A veces recuerdo algunas cosas de mi vida pasada.}

{130}{}{Todos los que pudieron están en la Isla Coronado.}
{131}{}{¡Hacía tiempo que no había tanto revuelo entre los necrófagos!}
{132}{}{Quién haya despejado la entrada a la Isla Coronado es nuestro héroe.}
{133}{}{¡Coronado está bajo nuestro control!}
{134}{}{¡La pasaremos bien con todos los juguetes nuevos!}

{135}{}{Tenía tantos planes en mente para la isla...}
{136}{}{Tener el control de Coronado sería mejor que comer unos tacos suaderos. Una pena.}
{137}{}{Ya no queda nada de la Isla Coronado.}
{138}{}{Explotó una vieja bomba en la isla. Me pregunto, ¿Alguien habrá metido mano?}
{139}{}{Tuve suerte de no estar parado en el puerto cuando explotó.}

{150}{}{¡Estoy en mi puesto, jefe! ¡Quieto como piedra!}
{151}{}{Mis respetos, oficial.}
{152}{}{Yo sí respeto la ley, oficial.}
{153}{}{Es bueno ver que aún existe la ley en el yermo... Ah, espera, ¡esa placa no es tuya!}
{154}{}{Debes tener unos cien años de servicio, ¿cierto?}
{155}{}{Algunas personas jugaron así con la ley. Empezaron la Tercera Guerra Mundial.}
{156}{}{Epa... ¿Estoy bajo arresto?}
