{100}{}{Ves a Jane.}
{101}{}{Ves a una necrófaga con un vestido común de la preguerra.}
{102}{}{Gracias por salvar a Donovan. Ya estábamos preparados para lo peor.}
{103}{}{Lo siento, estoy muy emocionada.}

{200}{}{(Jane) ... Frank, siento que algo le pasó. Ya debería de haber regresado... Oh, alguien nos está escuchando.}
{1200}{}{(Frank) ... Ya te lo dije, Jane. ¡Debe estar en problemas! Si no, ya debería estar aquí... Oye, deja de escucharnos, normalucho.}
{201}{}{Parece que están preocupados acerca de alguien.}
{202}{}{(Frank) No es asunto tuyo. humano. Esto es de necrófagos.}
{203}{}{[Siguiente]}
{204}{}{(Jane) Ay, perdona a Frank, está tenso.}
{205}{}{Pero, ¿qué pasó?}
{206}{}{Lo ignoraré, sólo por esta vez. Ahora dime, ¿qué demonios pasó?}
{207}{}{(Jane) Hemos perdido a nuestro amigo, Donovan. Fue a San Isidro y nunca regresó, y nadie por allá lo ha visto.}
{208}{}{[Siguiente]}
{209}{}{(Frank) Jane, ¿Por qué le hablas a éste normalucho? Ya tuvimos suficiente de ellos, no me sorprendería si Donovan falleció a mano de los carroñeros.}
{210}{}{[Siguiente]}
{211}{}{(Jane) Frank, es obvio que necesitamos ayuda.}
{212}{}{[Siguiente]}
{213}{}{(Frank) Hmm... ¿De verdad no tienes nada mejor que hacer, normalucho?  O nos ayudas o te largas de aquí. No quiero tratar con humanos, pero nos vendría bien algo de ayuda.}
{214}{}{Te ayudaré, te guste o no. Así te mostraré que no todos los humanos son malos.}
{215}{}{(Jane) ¡Ay, es un milagro! ¿Lo ves, Frank? Siempre se puede llegar a un acuerdo. Gracias, humano. Te estaremos esperando aquí.}
{216}{}{Ya veo. Hasta luego.}
{217}{}{La verdad, no me importan sus problemas. Adiós.}
{218}{}{(Frank) ¡Oye, oye, no te vayas así de rápido! Sólo ten en cuenta que Donovan debe estar en algún punto de las ruinas desde acá hasta San Isidro. Si lo ves... al menos dile que lo extrañamos, ¿bueno?}
{219}{}{Ya veo. Hasta luego.}
{220}{}{(Jane) ... Frank, siento que algo le tuvo que haber pasado, o si no ya habría vuelto... Oh, alguien nos está escuchando.}
{221}{}{[Siguiente]}
{222}{}{(Frank) Hmm, no me suena tu cara, pero estoy feliz de verte. ¿Nos darías un momento?}
{223}{}{¿Qué necesitan}
{224}{}{(Jane) Hemos perdido a nuestro amigo Donovan. Fue a San Isidro y nunca regresó, y nadie por allá lo ha visto.}
{225}{}{Déjame adivinar, tengo que ir a encontrarlo.}
{226}{}{Eres muy astuto para ser un necrófago. Mira, necesitamos tu ayuda. Donovan debe estar en algún punto de las ruinas desde acá hasta San Isidro. Si lo ves... al menos dile que lo extrañamos, ¿bueno?}
{227}{}{Está bien. Adiós.}

{230}{}{¿Tienes alguna noticia de Donovan?}
{231}{}{Todavía no, seguiré buscándolo.}
{232}{}{¿En dónde creen que debería estar?}
{233}{}{Se dirigía a San Isidro, pero no llegó y tampoco ha vuelto al Pueblo Viejo. Así que debería estar en algún punto del camino.}
{234}{}{Quizás se encontró una caja de cerveza y anda borracho en algún lado.}
{235}{}{Bien, seguiré buscando.}
{236}{}{¿De qué demonios hablas? Donovan era el cerebrito de nuestra operación...}
{237}{}{Tengo malas noticias. Encontré el cadáver de Donovan, está muerto.}
{238}{}{¿Por qué no me dijeron que era tan bajito? Fue difícil encontrarlo.}
{239}{}{(Jane) Oh, Dios mío, ¡Donovan, despierta! (Frank) ¡Donovan, deja de bromear! ¡Despierta!}
{240}{}{¿Acaso son estúpidos? Quedó más tieso que un árbol.}
{241}{}{Tienen que aceptar la verdad. Su cadáver está partido a la mitad, es imposible que siga vivo.}
{242}{}{Escucha, tienes que llevarlo a un doctor. Encuentra a Talius en San Isidro, él podrá ayudarlo, nosotros no llegaremos a tiempo.}
{243}{}{¿¡Se les cayó el cerebro de repente!? Quizás Talius pueda al menos explicarles que es imposible resucitar a una persona.}
{244}{}{¿Lo dices en serio? Si les ayuda a aceptar su muerte, lo llevaré.}
{245}{}{¡Deja de perder el tiempo! Lleva a Donovan con Talius.}
{246}{}{Ya, ya.}
