{100}{}{Ves a Gomer.}
{101}{}{Ves a un supermutante. Lleva puesto un casco del ejército y pantalones de camuflaje.}

{102}{}{¡No te atrevas a tocar a los Nocturnos, normalucho!}
{103}{}{¡Nunca te perdonaré por esto, normalucho!}
{104}{}{¡Yo estoy de su lado, hermanos!}
{105}{}{¿Mis hermanos están aquí? Jojojo, ya sabes de qué lado estoy.}
{106}{}{¡No te atrevas a tocar a los Nocturnos!}
{107}{}{¡Nunca te perdonaré por ésto!}
{108}{}{¡Yo estoy de su lado, hermanos!}
{109}{}{Veo a mis camaradas. Es mejor no enojarlos.}

{110}{}{¡El Maestro tenía razón, tendríamos que haberlos transformado a todos!}
{111}{}{Hola.}
{112}{}{[reclutar a compañeros]}
{113}{}{[quitar de compañeros]}
{114}{}{[enfundar arma]}
{115}{}{Adiós.}
{116}{}{Muy bien, no es necesario pelear. Gomer está de acuerdo.}
{117}{}{}
{118}{}{}
{119}{}{}

{150}{}{Aquí viven los muertos, aunque no les agraden los forasteros, no los atacan.}
{151}{}{Este es el campamento más grande de los necrófagos. Incluso hay normaluchos.}
{152}{}{Esto es el corazón de las ruinas. Apenas lo han explorado.}
{153}{}{Gomer no ha ido más allá del puesto de avanzada.}
{154}{}{¿Ves esa isla? Antes había una base militar en ella, pero la destruyeron.}
{155}{}{}
{156}{}{Si ves a un animal salvaje, no te preocupes, Gomer te protegerá.}
{157}{}{Gomer no puede hacer eso. Gomer ser muy grande.}
{158}{}{Has tratado mal a los necrófagos. Gomer ya no está en tu equipo.}
{159}{}{Gomer ha abandonado su lugar junto a ti hasta que arregles tu reputación.}

#First Dialogue
{200}{}{¿Un humano entre los necrófagos? ¡Qué sospechoso!}
{201}{}{No, yo... no importa. Sólo no me toques, grandulón. ¿Entendido?}
{202}{}{Incluso un humano regaña a Gomer. Los necrófagos tampoco querer ver a Gomer. ¡Gomer no ser necesitado por nadie!}
{203}{}{¡Oye, tranquilo! No quería enojarte, sólo pensé que los necrófagos no se llevaban bien con los supermutantes.}
{204}{}{Aquí tampoco son bienvenidos los humanos. Gomer fue expulsado de su escuadrón. Los necrófagos dijeron que cuidarían de Gomer si era bueno y ayudaba, Gomer lo intenta, pero sigue sin ser querido.}
{205}{}{¿Quién te necesita, montón de carne podrida?}
{206}{}{Gomer fue expulsado de su escuadrón. Los necrófagos dijeron que cuidarían de Gomer si era bueno y ayudaba, Gomer lo intenta, pero sigue sin ser querido.}
{207}{}{Triste, pero se entiende. }
{208}{}{¿Qué esperabas, cabeza hueca? Deberías haberte comportado mientras estabas en el escuadrón.}
{209}{}{Sólo un poco más y Gomer será respetado. Los necrófagos sabrán lo bueno que soy, ayudaré a los necrófagos aunque no quieran.}
{210}{}{Eso es genial, yo también ayudo a los necrófagos. Unamos fuerzas, así me proteges y yo te ayudo a ganar respeto.}
{211}{}{Tengo algo de lo qué ocuparme por aquí. ¿Y qué haces tú? ¿Los necrófagos y los supermutantes están del mismo lado?}
{212}{}{Los necrófagos jamás te aceptarán, olvídate de ellos y ayúdame a mí, necesito de tus músculos.}
{213}{}{Eso es muy noble de tu parte. Buena suerte, debo irme.}
{214}{}{Puedes irte, humano. No te haré daño, mientras dejes en paz a los necrófagos.}
{215}{}{Adiós, Gomer.}
{216}{}{Unamos fuerzas, así me proteges y yo te ayudo a ganar respeto.}
{217}{}{¿Un mutante y un humano en el mismo equipo? Eso es chistoso, pero si Gomer puede ser útil, él será feliz.}
{218}{}{Entonces ven conmigo, haremos un gran equipo.}
{219}{}{Genial. Volveré cuando necesite de tu ayuda.}
{220}{}{¿Te puedo ayudar en algo, hermano?}
{1220}{}{¿Te puedo ayudar en algo, hermana?}
{221}{}{No necesito tu ayuda en nada. Sólo no me toques, grandulón. ¿Entendido?}
{222}{}{Tú tampoco confiar en Gomer, necrófagos tampoco querer ver a Gomer. ¡Gomer no ser necesitado por nadie!}
{223}{}{¿Qué haces aquí? ¿Cómo terminaste entre los necrófagos?}
{224}{}{¡Esa es la actitud! Podríamos ayudarnos el uno al otro: tú me proteges, yo te ayudo a ganar respeto. ¿Trato hecho?}
{225}{}{Si Gomer puede ser útil a los necrófagos, él será feliz.}
{226}{}{Necesito tu ayuda, ven conmigo.}
{227}{}{¡El soldado Gomer dará su mejor esfuerzo!}
{228}{}{Tranquilo, soldado.}
{229}{}{Puede retirarse, soldado Gomer.}
{230}{}{Es una pena, Gomer quería ayudar. Pero no se olvide del soldado Gomer.}
{231}{}{Nos vemos.}
{232}{}{Enfunda tu arma, no la necesitamos ahora.}
{233}{}{¡Sí señor, enfundando el arma!}
{234}{}{Buen chico.}

{240}{}{Esperando sus órdenes, comandante.}
{241}{}{Tranquilo, soldado.}
{242}{}{¡Capitán! ¡El soldado Gomer está listo para ayudar!}

{250}{}{¿Quieres venir conmigo a Sonora? Me vendría bien tu ayuda.}
{251}{}{¿Ir con los humanos? De ninguna manera, los humanos nunca aceptarán a Gomer.}
{252}{}{Está bien, lo que tú digas.}
{253}{}{Tus camaradas están atacando a los caravaneros. ¿Puedes detenerlos?}
{254}{}{No escucharán a Gomer, echaron a Gomer del escuadrón, entonces Gomer no tiene autoridad sobre ellos. ¡Pero Gomer no permitirá que hagas daño a sus compañeros!}
{255}{}{Ya veo.}

{260}{}{Háblame de ti.}
{261}{}{Soy el soldado Gomer. ¿Por qué?}
{262}{}{Está bien, no hablemos de ello.}
{263}{}{¿Gomer es un nombre o un apodo?}
{264}{}{Es... em... ¡Lo olvidé por completo! Gomer no es un nombre real, es un término para la radio. No recuerdo mi verdadero nombre, no recuerdo nada desde la mutación.}
{265}{}{¿No recuerdas quién eras antes de la mutación?}
{266}{}{Exacto. Y Gomer no quiere recordarlo. Humanos patéticos, siguen revolcándose en sus problemas insignificantes. El Maestro intentó arreglar a los humanos, pero no pudo terminar con su trabajo.}
{267}{}{Puedes hablarlo conmigo. Sé que esos recuerdos deben de atormentarte, no puedes borrar los recuerdos de lo que eras.}
{268}{}{¿Crees que por eso Gomer es tan estúpido? ¿Por eso habla consigo mismo en la noche? A Gomer no le gusta recordar. Él era humano, él...}
{269}{}{[Consuélalo]}
{270}{}{[Búrlate]}
{271}{}{¿Cómo llegaste a Dayglow?}
{272}{}{Con mi escuadrón, caminamos por el desierto por un largo tiempo mientras nos perseguía la Hermandad... Agh, ¡los odio! Han matado a tantos de nuestros camaradas y nos exiliaron al yermo. Ya no tenía sentido volver, así que nos fuimos.}
{273}{}{[Continuar]}
{274}{}{En el camino, nos encontramos unos necrófagos, nos hablaron de Dayglow. También escapaban de los normaluchos. Los normales odian a todos.}
{275}{}{¿Y por qué no estás con tu escuadrón?}
{276}{}{Fue en tiempos de hambre. Gomer estaba tan hambriento que se comió todas las provisiones. Fue una vergüenza. Fue expulsado del escuadrón por eso, y no los ha visto desde entonces.}
{277}{}{¿Sabes en dónde está tu escuadrón?}
{278}{}{En las ruinas, en algún lado. Gomer sabrá si los escucha en la radio.}
{279}{}{Ahora que sabemos dónde está tu escuadrón, ¿quieres reencontrarte con ellos?}
{280}{}{Gomer los extraña, pero ellos no necesitan a Gomer.}
{281}{}{No te preocupes por eso, yo te ayudaré. Vamos.}
{282}{}{¿Lo escuchaste? El capitán está en problemas.}
{283}{}{¡Gomer está furioso! ¡Estúpidos humanos, han causado tantos problemas! ¡Van a pagar!}
{284}{}{¿Quieres rescatar al capitán aunque te hayan expulsado?}
{285}{}{Gomer está listo para tomar ese riesgo. ¡Vamos, humano! ¡A la carga!}
{286}{}{Está bien, vamos.}
{287}{}{Entiendo. Si no quieres, no trataremos con ellos.}
{288}{}{Tengo una radio, pero debido a los niveles de radiación, no podrá funcionar sin una estación funcional.}
{289}{}{Tengo una radio. ¿Probamos?}
{290}{}{Sería inútil, interfiere la radiación. Necesitamos una antena poderosa, quizás los necrófagos tengan una.}
{291}{}{Eso explica por qué no funciona la radio. Quizás podamos encontrar una antena.}
{292}{}{(Gomer ajusta la frecuencia y escucha cuidadosamente. Todas las venas de su cara se hinchan de la concentración. Finalmente habla: "Están en el Parque Balboa.")}
{293}{}{Bien, entonces vamos al parque.}
{294}{}{Había una estación de radio en San Isidro, vamos a probar allá.}
{295}{}{Hay una estación de radio por aquí. Vamos a probar.}
{296}{}{Es inútil, no funciona.}
{297}{}{Así es. No funciona.}
{298}{}{¡No se escucha nada! Tenemos que buscar otro sitio.}
{299}{}{Está bien.}

{300}{}{¡Es aquí! Los malditos paladines tienen al capitán ahí adentro.}
{301}{}{¿Cuál es el plan?}
{302}{}{¿Plan? ¡Gomer no necesita un plan! Gomer es más fuerte que cualquier paladín y pateará sus traseros. Ese es el plan.}
{303}{}{Buen plan, tan confiable como un reloj roto. ¡Vamos, Gomer! ¡Hazlos llorar!}
{304}{}{No, Gomer, no puedes matarlos. Es peligroso y tampoco está bien. Tenemos que rescatar al capitán sin herirlos. ¿Me entiendes?}
{305}{}{¡Grrr! ¡Malditos humanos! ¡Gomer quiere pelear, no se esconderá de ellos!}
{306}{}{Si lo piensas bien, tu idea es simple y confiable. ¡Vamos, Gomer! ¡Destroza a esos bastardos!}
{307}{}{¡De ninguna manera! No hay oportunidad alguna si nos lanzamos de cabeza. Vamos a explorar el área primero.}
{308}{}{Si Gomer ve a un paladín, no se echará para atrás. Tenlo en mente, humano.}
{309}{}{Está bien, lo tendré en cuenta.}
{310}{}{Sabes, sería mejor si voy a echar una mirada mientras me esperas. Es una orden, Gomer.}
{311}{}{Gomer agradece que hayas salvado al capitán. No podría haberlo hecho sin ti. Gracias.}
{312}{}{¿Un mutante dando las gracias? ¡Eso es nuevo!}
{313}{}{Todavía no me lo agradezcas, nos falta hablar con tu escuadrón.}
{314}{}{Sí. Gomer debe hablar con el escuadrón.}
{315}{}{Entonces vamos al campamento.}
{316}{}{Bien, ¿qué hay del capitán?}
{317}{}{Resiste, Gomer. El capitán ha muerto, igual que tu escuadrón.}
{318}{}{¡MALDITA HERMANDAD! ¡LOS ODIO! ¡LOS ODIO!}
{319}{}{Creo que es mejor si te dejo en paz un momento.}
{320}{}{Lo siento, Gomer. El capitán ha muerto.}
{321}{}{¿Qué planeas hacer sin tu escuadrón?}
{322}{}{Gomer trabajará duro en las minas de los necrófagos, ellos necesitan sus músculos. ¡Los necrófagos no se arrepentirán de tenerlo en su servicio! Sí, Gomer será de ayuda, será feliz de ser de ayuda. Eso es lo que quería Gomer.}
{323}{}{Ya veo. Bueno, espero me acompañes por un tiempo, antes de que vuelva a Sonora.}
{324}{}{Tu escuadrón está listo para tenerte de vuelta.}
{325}{}{¿Los camaradas perdonaron a Gomer? ¡Esto hace a Gomer muy feliz! Pero Gomer ya prometió ayudar a los necrófagos. ¿Y puede justificarse su confianza si antes falló? Dime, humano, ¿qué debería hacer Gomer? ¿Cuál es la mejor elección para Gomer?}
{326}{}{Creo que deberías quedarte con el escuadrón. Sólo entre los tuyos te sentirás verdaderamente feliz. Y no le debes nada a los necrófagos, ni ellos a ti.}
{327}{}{Quédate con los necrófagos y ayudalos a reconstruir la ciudad, tu fuerza les será de mucha ayuda. Tu escuadrón ya te abandonó una vez; quizás lo hagan de nuevo y no sabes qué les pasará en el camino.}
{328}{}{¡Gomer hará todo lo posible para no volver a perder su confianza! El escuadrón no se arrepentirá de tenerlo de vuelta. Sí, Gomer estará en paz entre su gente. Será útil y feliz. Eso es lo que quería Gomer.}
{329}{}{Es bueno que hayamos resuelto tu problema. Espero que te quedes conmigo un tiempo más antes de que tu escuadrón se marche de Dayglow.}

