{100}{}{Ves a un necrófago llamado Zerah.}
{101}{}{Ves a un necrófago común y corriente. Parece que está algo abatido por su encuentro con los carroñeros.}
{102}{}{Z-z-z...}
{103}{}{¡Déjame en paz!}
{104}{}{Zerah decía la verdad, habían }
{105}{}{ billetes aquí adentro.}
{106}{}{Diagnosticas lo siguiente: Está muerto.}
{107}{}{Buena idea.}

{200}{}{¿Y quién eres tú?}
{201}{}{Oh, hermano mío, ayúdame. Estos bastardos me quieren matar.}
{1201}{}{Oh, hermana mía, ayúdame. Estos bastardos me quieren matar.}
{202}{}{Voy a desatarte... Y nos iremos de aquí. ¡Ven, y no hagas ruido!}
{203}{}{Veo que estás en aprietos. Puedo ayudarte, si me dices en dónde escondiste las chapas.}
{204}{}{¡Te lo diré! Pero primero sácame de aquí.}
{205}{}{No me importas. Cállate y quédate ahí.}
{206}{}{¡Oigan, chicos! ¡Hay un normalucho por aquí!}
{207}{}{Pedazo de...}
{208}{}{¡Cállate!}

{210}{}{Gracias, hermano. Una vez más, queda demostrado que los normaluchos no son de confianza.}
{1210}{}{Gracias, hermana. Una vez más, queda demostrado que los normaluchos no son de confianza.}
{211}{}{Gracias por salvarme el culo. Jamás pensé que a un normalucho le importaría.}
{212}{}{¿Qué querían esos saqueadores de ti?}
{213}{}{Son sólo chatarreros, no quieren arriesgarse a meterse en las ruinas, así que le roban a los que sí. Pero no conozco de ningún alijo secreto.}
{214}{}{Lo importante es que estás a salvo. Ten más cuidado por aquí de ahora en adelante.}
{215}{}{Eres un mentiroso. ¡Dime en dónde está el alijo!}
{216}{}{¡Ya, ya, cálmate! Dejé todos mis billetes en el buzón de la entrada del hospital mientras me perseguían los chatarreros. Era todo lo que tenía.}
{217}{}{Iré a revisar. Reza porque sigan ahí.}
{218}{}{Puedes irte.}
{219}{}{¡Silencio! ¡Podrían oírnos! Primero lleguemos a la calle.}
{220}{}{Vale.}
{221}{}{No te preocupes. Todos los chatarreros están muertos.}

