{100}{}{Ves a un guardia necrófago.}
{101}{}{Ves a un necrófago que porta armadura de combate.}
{102}{}{No toleramos competidores. ¡Fuera de aquí!}
{103}{}{Aunque fueras un oficial fronterizo, no tendrías ninguna autoridad aquí.}
{104}{}{¿Tienes permitido estar aquí?}
{105}{}{Se nos avecinan grandes cambios.}

{200}{}{Te lo diré una sola vez, normalucho. No eres bienvenido aquí. Pero si te comportas, nadie te hará daño. ¿Entendido? Muy bien. Ahora dime qué quieres.}
{201}{}{Bienvenido, hermano. ¿Te han recibido bien en San Isidro? ¿Necesitas algo?}
{1201}{}{Bienvenida, hermana. ¿Te han recibido bien en San Isidro? ¿Necesitas algo?}
{202}{}{Te quiero hacer unas preguntas sobre Dayglow.}
{203}{}{¿Qué necesitas?}
{204}{}{Nada. Por ahora.}
{205}{}{Habla.}
{206}{}{Tengo que irme. Gracias por tu tiempo.}
{207}{}{Entendido. Tengo más preguntas.}
{208}{}{}
{209}{}{}
{210}{}{Háblame de ti.}
{211}{}{Soy Robert Newsom, sargento retirado. Antes de la guerra, mantenía el orden en las calles de Bakersfield, y ahora mantengo el orden en Dayglow. Me encanta mi trabajo, y no dejaré que nadie haga alboroto en mi territorio.}
{212}{}{¿Qué piensas de Gustavo?}
{213}{}{Es muy adecuado para el papel de alcalde, y los necrófagos le tienen respeto. Al menos aquí en San Isidro. Pero en el Pueblo Viejo no todos son tan razonables.}
{214}{}{¿Quién dirige el Pueblo Viejo?}
{215}{}{John Butler. Es un viejo veterano del ejército, así que está muy mal de la cabeza. Ha reunido a su alrededor no sólo a necrófagos, también a supermutantes y algunos normaluchos. Todos necesitan su ayuda para algo.}
{216}{}{¿Cuál es la relación entre Gustavo y Butler?}
{217}{}{Últimamente han tenido muchos desacuerdos. Pero dudo que eso quiebre su amistad.}
{218}{}{}
{219}{}{}
{220}{}{Háblame del área.}
{221}{}{San Isidro y el Pueblo Viejo son los asentamientos necrófagos más grandes. Entre estos dos hay ruinas radioactivas y algunos parques quemados, en ambos te encontrarás a los chatarreros y algunos monstruos.}
{222}{}{[Siguiente]}
{223}{}{Los ataques nucleares golpearon en su mayoría a la base militar y la zona industrial. El centro de San Diego también sufrió mucho. Ruinas, niveles altos de radiación, esqueletos - te encontrarás todo eso allá afuera. También hay robots del ejército por todos lados. Se perdieron después de que saltaran las alarmas en la base militar.}
{224}{}{Dime cómo puedo llegar a Chula Vista.}
{225}{}{Tienes que cruzar el valle del Río Otay. Hacia allá queda un sólo puente, pero lo patrullan robots y está minado. Así que o das la vuelta o pasas por el valle. Pero hay unos monstruos horrendos en el valle.}
{226}{}{¿Cómo puedo llegar a la Presa Bonita.}
{227}{}{Sigue la Autopista Federal 805 hasta llegar a la señal, y te vas a la derecha.}
{228}{}{¿Qué debo hacer para llegar al Pueblo Viejo?}
{229}{}{Ir derecho a través de las ruinas es muy difícil. Es más fácil pasar por la Ruta 805 y pasar por el Parque Balboa, pero ten cuidado con los monstruos del parque. En el parque vas hacia la izquierda y llegas a Little Italy, y vas al norte.}
{230}{}{¿Quiénes son los carroñeros y qué relación tienen con ellos?}
{231}{}{Son eso, chatarreros, sólo los llamamos así para diferenciarlos. Buscan fragmentos del Viejo Mundo, y casi nunca saben para qué son. Entonces lo venden a las caravanas y a los necrófagos nos dejan las migajas. También matan a quién sea que se interponga en su camino. Gustavo quiere echarlos de nuestras ruinas, pero Butler los quiere domesticar al darles el Sello de Set a los más obedientes.}
{232}{}{¿Se llevan bien con los supermutantes?}
{233}{}{¿Los supermutantes? El ejército del Maestro se dividió en muchos grupos y se esparcieron por las ruinas, hay muchos por ahí. Algunos son agresivos, unos cooperan con nosotros, pero otros están por su cuenta. Son como almas perdidas.}

{241}{}{Estoy buscando el escuadrón de Gomer. ¿Has oído algo de ellos?}
{242}{}{Escuché que unos supermutantes establecieron un campamento en el Parque Balboa. No son agresivos, la verdad es lo opuesto. Quizás es el escuadrón que estás buscando.}
{243}{}{Muchas gracias.}

