{100}{}{Ves a un mercenario.}
{101}{}{Ves a uno de los carroñeros, están dispuestos a hacer lo que sea por dinero.}

{110}{}{El Sr. De Santi pagará bien por tu cabeza.}
{111}{}{¡No deberías haberte metido con el Sr. De Santi!}
{112}{}{Aquellos que van en contra del Sr. De Santi no viven mucho.}
{113}{}{¡Has decepcionado terriblemente al Sr. De Santi!}
{114}{}{No es nada personal. Alguien le puso precio a tu cabeza.}
