{100}{}{Ves a un necrófago chatarrero.}
{101}{}{Ves a un necrófago. Está inspeccionando sus hallazgos.}

{200}{}{¡Oye, quédate ahí y no te me acerques! ¡Estas cosas son mías, yo las encontré!}
{201}{}{*Eran* tuyas, ahora me pertenecen.}
{202}{}{Claro, como digas. Son tus cosas.}
{203}{}{Es raro ver a un normalucho por aquí... Bueno, es raro en estos días. Antes, habían muchos caminando por éstas mismas calles. Ahora sus huesos están desparramados por todos lados.}
{204}{}{¿Qué estás haciendo aquí?}
{205}{}{Estoy buscando algo de valor en estas ruinas. Los carroñeros raramente llegan hasta acá, gracias al robot fronterizo. Pero alguien nos hizo un gran favor al desactivarlo.}
{206}{}{Te deseo suerte en tu búsqueda. Adiós.}
{207}{}{¿Has encontrado algo interesante?}
{208}{}{Sí, mira...}
{209}{}{[Trueque]}
{210}{}{Hola, normalucho. ¿Estás buscando algo? Quizás tenga guardado lo que buscas. Casi estoy regalando lo que tengo, y tú mereces un descuento.}
{211}{}{Por el momento, nada.}
{212}{}{Muéstrame lo que tienes...}
{213}{}{Tendrás que volver en otro momento. Quizás en unos días haya encontrado algo útil.}
{214}{}{Adiós.}
{215}{}{Oye, hazme un favor y no te metas en mis cosas, ¿Vale? ¡Son mías!}
{216}{}{Hmm, así que ya no soy el único que anda por aquí... Antes, habían muchas personas caminando por estas mismas calles. Ahora sus huesos están desparramados por todos lados.}
