{100}{}{Ves al comandante de los Nocturnos.}
{101}{}{Ves a un supermutante Nocturno.}
{102}{}{Gracias, humano. Te has ganado mis respetos. Sé que algún día nos encontraremos de nuevo, adiós.}
{103}{}{¡Gomer está feliz! ¡Muy feliz!}

{200}{}{¡Déjame, humano! Espera... no eres de la Hermandad, ¿cierto?}
{201}{}{Escucha, no hay tiempo para explicar, pero quiero ayudarte. Sólo sígueme y escóndete de los paladines.}
{202}{}{Siéntate, grandulón, espérame aquí.}
{203}{}{¿Así que Gomer te acompaña? Eso es raro... He visto mucho, pero esto es nuevo.}
{204}{}{No entiendo qué estás planeando, humano. Pero más te vale que no intentes engañarme.}
{205}{}{Hablaremos de esto luego. Vámonos.}
{206}{}{Estás libre.}
{207}{}{Explícate, humano. ¿De qué se trata esto? ¿Por qué ayudas a un Nocturno? ¿Quién te envió?}
{208}{}{Fue Gomer. Quería ayudar a su escuadrón para que perdonen sus errores.}
{209}{}{¿Gomer? ¡Ja! Hasta el más tonto puede sorprenderte a veces. Me tomaste desprevenido, humano. Ahora lo entiendo, Gomer ve que eres fuerte. Está bien, que Gomer decida si quiere quedarse contigo o con los Nocturnos. Mientras se decide, yo voy de vuelta al campamento. Adiós, pequeño.}
{210}{}{Sí, ahí nos vemos.}
