{100}{}{Ves a un paladín.}
{101}{}{Ves a un paladín de la Hermandad del Acero.}
{102}{}{Saludos, hermano.}
{1102}{}{Saludos, hermana.}

{110}{}{¿Qué demonios está pasando!}
{111}{}{¡Maldita alarma!}
{112}{}{¿Por qué demonios hay tanto ruido?}
{113}{}{Hmm, esto es raro.}
{114}{}{¿Eh? ¿Se activó sola?}
{115}{}{¡Maldita alarma!}

{120}{}{¡Que tecnología tan estúpida!}
{121}{}{¡Ya basta con el ruido!}
{122}{}{¿Cómo la apago?}
{123}{}{Que mal que no hay ningún caballero aquí cerca...}
{124}{}{¿Cómo demonios funciona esta cosa?}
{125}{}{¡Juro que sería más fácil reventarla que apagarla!}

{130}{}{Esto es raro. ¿Por qué se activó?}
{131}{}{Al menos la alarma dejó de sonar.}
{132}{}{Es sorprendente que todavía funcione.}
{133}{}{Creo que por fin se apagó.}

{200}{}{¡Alto! No puedes pasar, abandona el área. Ahora.}
{201}{}{Ya, ya. Me largo.}
{202}{}{¡Inténtalo, perro!}
{203}{}{Yo también pertenezco a la Hermandad. Escriba }
{204}{}{Yo también pertenezco a la Hermandad. Caballero }
{205}{}{Yo también pertenezco a la Hermandad. Paladín }
{206}{}{Yo también pertenezco a la Hermandad. Explorador }
{207}{}{, división de Sonora.}
{208}{}{Me alegro de verte, hermano. Puedes quedarte con nosotros, bajo nuestra protección.}
{1208}{}{Me alegro de verte, hermana. Puedes quedarte con nosotros, bajo nuestra protección.}
{209}{}{¿Puedo preguntarte qué están haciendo aquí?}
{210}{}{Tenemos una pequeña misión entre manos. Capturamos a un capitán supermutante y está bajo interrogación. Al acabar, lo mataremos. No te preocupes, está bajo custodia.}
{211}{}{Ah, eso es maravilloso. Felicitaciones.}
{212}{}{¡Detente! Te lo diré otra vez, no puedes estar aquí. Vete. Inmediatamente.}
{213}{}{No me hagas enojar, último aviso. NO. PUEDES. ESTAR. AQUÍ.}
{214}{}{¡Suficiente! ¡No soporto a los idiotas como tú! ¡Te daré una golpiza!}
{215}{}{Ay, eso va a doler...}
{216}{}{¡En tus sueños, imbécil!}
{217}{}{Sé a quién tienes encerrado. Y puedo decirte en dónde está su escuadrón.}
{218}{}{¡Entonces habla! Cualquier información será valiosa para nosotros.}
{219}{}{Su escuadrón está localizado en el parque Balboa.}
{220}{}{Nunca hay que pensarlo dos veces con los supermutantes, son un mal que debe ser erradicado. Gracias por la información, apreciamos tu ayuda.}
{221}{}{De nada.}
{222}{}{¿Y qué harás con los supermutantes?}
{223}{}{Nunca hay que pensarlo dos veces con los supermutantes, son un mal que debe ser erradicado. ¿En dónde están?}
{224}{}{¿Erradicarlos? ¡Eres un demente! No dejaré que les hagas daño.}
{225}{}{Pronto enviaré un equipo para eliminar a los verdecitos. Gracias por la información, apreciamos tu ayuda.}

{226}{}{¿Pero qué...? ¿Cómo pudiste...? ¡Nadie escapará mientras yo esté aquí!}

