{200}{}{Ay, no había dormido tan bien en años.}
{201}{}{¿Qué estabas haciendo ahí dentro?}
{202}{}{¿Por qué demonios estabas ahí? ¡Pensé que alguien había escondido un cuerpo adentro!}
{1202}{}{¿Por qué demonios estabas ahí? ¡Pensé que alguien había escondido un cuerpo adentro!}
{203}{}{Me había escondido de los supermutantes, y me dormí. ¿Cuánto tiempo habrá pasado? Seguramente un par de semanas. Bueno, iré a dormirme a la ciudad.}
{204}{}{Cuídate.}
{205}{}{No te duermas en el camino, extraña criatura.}
{206}{}{Quiero dormir...}
