{100}{}{Ves a un Señor Oficial.}
{101}{}{Este robot lleva puesta una placa muy desgastada. Parece representar algún tipo de autoridad por aquí.}
{102}{}{Esté alerta, ciudadano. Actualmente no es seguro estar en la carretera.}

{110}{}{¡Alto! Está infringiendo las normas de tráfico.}
{111}{}{Estar parado en la carretera infringe la legislación vigente.}
{112}{}{Está prohibido estar en la carretera fuera de un vehículo.}
{113}{}{Está detenido. Abandone la carretera y acuéstese boca abajo en el suelo.}
{114}{}{Usted vendrá conmigo a la estación de policía.}
{115}{}{Ríndase. No puede escapar de la justicia.}
{116}{}{No quiero dañarlo. Usted ha causado este problema para sí mismo.}
{117}{}{Mi programación requiere que lo detenga.}
{118}{}{Puede presentar todas sus quejas en presencia de un abogado.}
{119}{}{No permitiré que escape hasta que pague la multa.}
{120}{}{Es mi deber detenerlo antes de que cause un accidente de tráfico.}

