{100}{}{Ves a un carroñero.}
{101}{}{Ves a un carroñero.}
{102}{}{Este es nuestro territorio. Piérdete.}
{103}{}{Trabajamos con De Santi. Si necesitas algo, habla con él.}

{200}{}{Este es nuestro territorio. Piérdete.}
{201}{}{Lo siento. Me voy de aquí inmediatamente.}
{202}{}{¿Y si me niego? ¿Sólo eres capaz de intimidar, verdad?}
{203}{}{Este no es tu territorio. Es el territorio del Sr. De Santi.}
{204}{}{¿Quién es ese? ¿Otro necrófago decrépito? ¿Por qué debería importarnos?}
{205}{}{Están operando ilegalmente, ¿cierto? De Santi puede otorgarte el Sello de Set, si trabajan para él.}
{206}{}{¡No necesitamos el Sello de Set! Si fuera así, ya lo tendríamos. ¿Entendido?}
{207}{}{Hablar contigo es inútil. Los idiotas como tú sólo entienden a los golpes...}
{208}{}{[Lárgate]}
