{100}{}{Ves a la asistente del baño.}
{101}{}{Ves a una necrófaga en una vieja bata de baño.}

{110}{}{Puedo darte un masaje en la espalda, tesoro. Sólo debes pagarle al administrador primero.}
{111}{}{¿Quieres tomar un baño? Lavaré TODAS las partes de tu cuerpo.}
{112}{}{Tenemos agua de radio, baños de radón, jacuzzis de uranio y duchas de plutonio. Elige lo que más te guste.}
{113}{}{Un buen exfoliante cuesta dinero. Y mi buena actitud cuesta aún más.}
{114}{}{Puedes olvidar todos tus problemas conmigo, dulzura.}
{115}{}{Vamos, quítate los pantalones. Sé dónde tocar y dónde no.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
