{100}{}{Ves a Derrick.}
{101}{}{Ves a un necrófago. Mira cuidadosamente a quienes pasan por la calle.}
{102}{}{Mi negocio colapsó cuando falleció De Santi.}
{103}{}{¡Ya! ¡Ya! Trabajaré para él. ¡Pero no me hagas daño!}
{104}{}{Derrick no buscará otra pelea.}

{200}{}{Oye, normalucho, ¿a dónde vas?}
{201}{}{No es asunto tuyo.}
{202}{}{Bueno, como digas.}
{203}{}{Adiós.}
{204}{}{Quizás al Pueblo Viejo, o a ese hotel de ahí, o quizás a ningún lado. ¿Por qué lo preguntas?}
{205}{}{¿Por qué lo preguntas?}
{206}{}{Te puedo dar un aventón. ¿O acaso vas al spa? Es sólo para necrófagos, así que no recomiendo que un normalucho lo visite, además es aburrido. Pero yo te puedo dar algo para relajarte a un precio mucho más bajo. Echa un ojo, no te arrepentirás.}
{207}{}{Bien, déjame ver qué vendes.}
{208}{}{Te puedo dar un aventón. ¿O acaso vas al spa? Es sólo para necrófagos. Pero te advierto, los precios son más caros que mi esposa cuando estaba viva.  Pero yo te puedo dar algo para relajarte a un precio mucho más bajo. Echa un ojo, no te arrepentirás.}
{209}{}{Hmm, lo tendré en mente.}
{210}{}{Buenas, ¿a dónde vas?}
{211}{}{Volverás por más.}
{212}{}{Por supuesto, adiós.}
{213}{}{Lo dudo mucho.}
{214}{}{¿A qué te refieres con "dar un aventón"?}

{220}{}{Tú otra vez. ¿Qué quieres ahora?}
{221}{}{Nada en especial. Adiós.}
{222}{}{Muéstrame lo que tienes.}
{223}{}{"Dónde" no es la pregunta, es "qué". Muéstrame lo que realmente vendes.}

{230}{}{Llamaste demasiado la atención, Derrick. Al Sr. De Santi no le gusta que te aproveches de su clientela.}
{231}{}{Esto es una calle libre. Quiero hacer negocios aquí, y lo haré.}
{232}{}{¿No te da miedo que esta calle termine siendo tu tumba?}
{233}{}{Puedo entender que admires a un bandido del Viejo Oeste, se enfrentaban en duelos honestos. Pero De Santi solo era un chiquitín entre los bandidos de Bakersfield. Y así es como se quedó, no me asusta.}
{234}{}{Ah, bueno. No me quiero meter en ésto.}
{235}{}{Hablas demasiado. Tendré que darte una lección, Derrick.}
{236}{}{Te arrepentirás de ésto. Algún día.}
{237}{}{Tienes una elección - mueres, o trabajas para De Santi. Espero tu respuesta. Uno...}
{238}{}{Oye, oye, no te vas a ensuciar las manos por un matón como él, ¿cierto?}
{239}{}{No, sólo bromeaba. Adiós, Derrick.}
{240}{}{Mientras me pague, no me importa. Pierdo el tiempo contigo, ¡es hora de acabar con ésto!}
{241}{}{Dos...}
{242}{}{¡Oye, oye, oye! ¿De Santi me quiere muerto de verdad? ¿En serio? ¡Mierda!}
{243}{}{¡Tres!}
{244}{}{¡Ya! ¡Ya! Trabajaré para él. ¡Pero no me hagas daño!}
{245}{}{Demasiado tarde, Derrick. Ya me irritaste demasiado, tendré que castigarte.}
{246}{}{Genial, y no intentes nada estúpido. De Santi es tu jefe ahora.}

{250}{}{Dijiste que podías "dar un aventón".}
{251}{}{Bueno, hace tiempo que no tengo un auto. Pero conozco las rutas rápidas y seguras, ¿a dónde quieres ir?}
{252}{}{[A San Isidro por }
{253}{}{[A la Presa Bonita por }
{254}{}{ chapas]}
{255}{}{Mejor camino.}
{256}{}{¿No tienes dinero, verdad? Una pena.}
{257}{}{Sí, mejor voy caminando.}
{258}{}{Espera, tengo que preguntarte algo más.}
{259}{}{[A Chula Vista por }

