{100}{}{Ves a Flores.}
{101}{}{Ves a un supermutante con un físico enorme.}
{102}{}{¡Querer comida!}
{103}{}{Bienvenido a... eh, me olvidé.}
{104}{}{Claro. Los necrófagos y mutantes deben cuidarse entre sí.}
{105}{}{Ñam ñam... ¡No es suficiente!}
{106}{}{¡Ahora estoy lleno!}

{200}{}{¡Tú! No tenerme miedo... Ven cerca... No comerte... ¡Argh! ¡Te atrapé, tontito ratón! Oh, escapó...}
{201}{}{¿A quién intentas atrapar, grandulón?}
{202}{}{¡Yo querer comida! ¿Tú tener? Hmm, tienes mucha carnita encima... ¡Pero no! ¡No poder comerte! Necrófagos no aceptarme entonces.}
{203}{}{¿Así que tú eres Flores? El Sr. De Santi te ofrece un trabajo. Si aceptas, tendrás mucha comida.}
{204}{}{¡Querer comida! Primero darme, luego hablar.}
{205}{}{Vale.}
{206}{}{Ñam ñam ñam... ¡No es suficiente!}
{207}{}{¿Quieres más? Entonces ve a trabajar para De Santi.}
{208}{}{Ir De Santi. De Santi tener que ser buen necrófago. ¡Yo ir!}
{209}{}{Creo que puedes llegar por ti mismo. Nos vemos en Little Italy.}
