{100}{}{Ves a Cabot, un necrófago comerciante.}
{101}{}{Ves al comerciante del Pueblo Viejo.}
{102}{}{No atiendo a los traidores. Fuera de mi tienda.}
{103}{}{Mira, si no te gusta nuestro hogar, entonces vete de vuelta al yermo, pendejo.}

{200}{}{Hola, humano. Soy Cabot, y ésta es mi tienda. Si necesitas algo, dime.}
{201}{}{Hola, Cabot. ¿Qué estás vendiendo?}
{202}{}{Me llegan cosas de toda Dayglow, pero las caravanas se lo llevan casi todo al norte.}
{203}{}{¿Por qué?}
{204}{}{En el Pueblo Viejo, creemos que debemos ayudar a las personas a reconstruir la civilización con cosas viejas y sabiduría... Bueno, al menos eso dice Butler. Yo sólo quiero hacer dinero. Soy un comerciante, y siempre lo he sido.}
{205}{}{Déjame ver que tipo de chatarra tienes.}
{206}{}{Me gustaría echarle un ojo a esas viejas reliquias. Déjame ver lo que vendes.}
{207}{}{Lo siento humano, pero no esperes ningún descuento. Tendrás los mismos precios que los demás normaluchos.}
{208}{}{Bueno, como quieras.}
{209}{}{Para los mutantes y los necrófagos, tengo precios más baratos. Son más... razonables, digamos. Verás, no pensamos muy bien de los normales por aquí. Aún así, te venderé cosas a un precio justo.}
{210}{}{Ah, gracias, amigo mío.}
{211}{}{¡Tengo lo mejor que puedes encontrar en los escombros de la gran ciudad!}
{212}{}{Adiós.}
{213}{}{¿Te puedo hacer unas preguntas?}

{220}{}{¿Qué buscas, amigo mío?}
{1220}{}{¿Qué buscas, amiga mía?}
{221}{}{¿Qué quieres, niño?}
{222}{}{¿Qué quieres ahora?}
{223}{}{Adiós.}
{224}{}{Necesito comprar algo.}

{230}{}{Todavía no encuentras el inyector de Rutger, ¿verdad?}
{231}{}{¡Te juro que estaba por acá! Busqué en todas las cajas, pero no lo encontré.}
{232}{}{¿Lo habrá visto alguien más?}
{233}{}{Hmm, el mensajero que lo trajo era Steve Morgan. Creo que fue a gastarse las chapas en el bar. No lo he visto desde ese entonces.}
{234}{}{Veré si lo encuentro por allá. Adiós.}

{240}{}{Busco a un necrófago llamado Rupert. ¿Sabes dónde está?}
{241}{}{¿Rupert? Llegó a Dayglow hace un mes, pero no lo he visto desde ese entonces.}
{242}{}{Bueno, olvídalo.}
{243}{}{¿Lo habrás visto con alguien más antes de que desapareció?}
{244}{}{No lo sé.}
{245}{}{¿A dónde fue?}
{246}{}{No sé.}
{247}{}{¿Dijo lo que planeaba hacer?}
{248}{}{No sé. Bueno... me dijo que estaba cansado y que quería relajarse.}
{249}{}{¿Y qué le dijiste?}
{250}{}{Bueno, le conté del spa del hotel "La Pensione". No lo he visto desde ese día.}
{251}{}{¿El que está en Little Italy? Gracias.}

{260}{}{¿Sabes en dónde puedo conseguir un programa para un Señor Mañoso?}
{261}{}{Pregúntale a Phil en la biblioteca. Tiene un cerebro muy grande, a lo mejor se le ocurra algo.}
{262}{}{Gracias.}

{270}{}{Alguien me dejó un holodisco encriptado.}
{271}{}{¿Alguien? ¿Ni siquiera sabes cómo se llama?}
{272}{}{Bueno, no se presentó.}
{273}{}{Entiendo. Sí, lo tengo aquí. Dame tu Pip-Boy, veamos si carga.}
{274}{}{[Seguir]}
{275}{}{(Insertas el holodisco e inicias el proceso de desencriptación. Resulta que el mensaje está encriptado específicamente para tu Pip-Boy.)}
{276}{}{[Lee el mensaje]}
{277}{}{"Lamento no haber podido hablar contigo. Estaba demasiado ocupado, pero sé que lo harás bien sin mí."}
{278}{}{[Seguir]}
{279}{}{"Hay un desacuerdo entre Gustavo y Butler acerca del futuro de Dayglow. No sé cuál de los dos tiene más razón. Lo importante es que otras personas no terminen heridas por ello. Dayglow no es sólo un montón de ruinas, está llena de cosas del Viejo Mundo, y algunas pueden ser extremadamente peligrosas. No podemos dejar que caiga en las manos equivocadas."}
{280}{}{[Seguir]}
{281}{}{"Además de los humanos y los necrófagos, hay otra fuerza que busca estos recursos - la Hermandad del Acero. Están encerrados en un viejo silo para misiles. Intenta contactarlos y decide si deberíamos dejar que tomen el control por aquí. Los puedes encontrar a través de una radio o un transmisor. Aquí tienes su frecuencia y el código que usan."}
{282}{}{[Seguir]}
{283}{}{"Una última cosa. Escondí un alijo en el Parque Balboa, en una vieja cañería cerca de la subestación del monorriel. Creo que te será útil. Hasta que nos veamos de nuevo."}
{284}{}{[Saca el holodisco]}
{285}{}{[Leélo de nuevo]}

