{110}{}{Es necesario usar la fuerza bruta.}
{111}{}{Esta válvula está cerrada. No tienes la fuerza suficiente para girarla aunque sea unos centímetros.}
{112}{}{Un golpe a la pipa quitó años de óxido. Ahora quizás puedas mover la maldita válvula.}
{113}{}{¡Sólo un poco más!}
{114}{}{¡Necesitas poner más fuerza!}
{115}{}{Parece que la válvula se ha movido un milímetro.}
{116}{}{Parece que la válvula ha empezado a ceder.}
{117}{}{La válvula está abierta.}
{118}{}{¡Por fin!}
{119}{}{¡Agh!}
{120}{}{¡Arrgh!}
