{110}{}{La estación de radio ya funciona, gracias a ti.}
{111}{}{Este equipo está funcionando a su máxima capacidad.}
{112}{}{Los necrófagos de San Isidro usan la estación de radio para comunicarse con el resto de Dayglow.}
{113}{}{Este equipo no necesita ser reparado.}
{114}{}{Envías una señal de alto al fuego a los robots fronterizos de San Isidro.}
##You transmit data about the new transponder to the naval base. The automation grants landing permission.
{115}{}{Transmites los datos del nuevo transpondedor a la base militar. El sistema de seguridad de la isla ahora permite el desembarque.}

{116}{}{No hay corriente eléctrica.}
