{110}{}{Esta estación de radio todavía funciona.}
{111}{}{Esta estación de radio dejó de funcionar hace poco.}
{112}{}{No es necesario reparar la estación. Pero sin una antena, es inútil. Déjala aquí por ahora.}
{113}{}{Has extraído el amplificador y partes necesarias para la radio en San Isidro.}
{114}{}{El equipamiento de la estación de radio está en buenas condiciones. Pero por alguna razón, la señal no transmite.}
{115}{}{Es inútil. Esta estación de radio tiene problemas transmitiendo.}
