{200}{}{La estación está lista para ser operada. Introduce los materiales necesarios y ejecuta el programa que desees.}
{201}{}{Apaga la estación.}
{202}{}{Regresar.}
{203}{}{Deberías enfundar tu arma.}

{210}{}{Materiales necesarios: }
{211}{}{, }
{212}{}{.}
{213}{}{Introduce los materiales y ejecuta el programa.}
{214}{}{El programa ha finalizado. Recoge el objeto de la bandeja.}
{215}{}{Apaga la estación.}
{216}{}{Regresa a la lista general}
{217}{}{Cancelar y regresar a la lista general}
{218}{}{No hay material suficiente.}
{219}{}{Regresar a la sección anterior.}
{220}{}{Has recibido: }
{221}{}{, }
{222}{}{ piezas.}
{223}{}{Sección de reparación}
{224}{}{Sección de química}
{225}{}{Sección de munición}
{226}{}{}

{250}{}{Chapas caseras}
{251}{}{Rad-Away casero}
{252}{}{Estimulante casero}
{253}{}{Antídoto casero}
{254}{}{Combustible de lanzallamas}
{255}{}{Cóctel Molotov}
{256}{}{Granada de pulso electromagnético}

{260}{}{Reciclar los cuetes para crear bengalas}
{261}{}{Mejorar las bengalas normales a bengalas modificadas (2 por 1).}
{262}{}{Mejorar las bengalas normales a bengalas reforzadas (3 por 1).}
{263}{}{Mejorar las bengalas modificadas a bengalas reforzadas (3 por 1).}
{264}{}{Convertir cartucho de escopeta tipo normal a cartucho tipo bala}
{265}{}{Convertir cartucho de escopeta tipo bala a tipo normal}

{270}{}{Limpia la tierra de la placa fronteriza}
{271}{}{Reemplaza el cristal de la pistola láser}
{272}{}{Repara el módulo dañado del monorriel}

