{100}{}{Esta es una computadora de servicio.}
{101}{}{La computadora está conectada a la base de datos del refugio.}
{102}{}{Estudiar la historia del refugio ha incrementado tu experiencia.}

#Dialog
{200}{}{Acceso concedido. Introducir comando.}
{201}{}{Cerrar sesión:}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Regresar al menú principal}
{205}{}{Cancelar}

{210}{}{Lee los informes del servicio de seguridad.}
{211}{}{Selecciona un mes para leer sus informes}
{212}{}{Febrero de 2131}
{213}{}{"Hemos recopilado datos de los últimos grupos de reconocimiento."}
{214}{}{"Grupo Alfa: Fue enviado al centro de la ciudad de San Diego, no nos han contactado de vuelta. Su último mensaje mencionaba altos niveles de radiación y destrucción significativa de la zona urbana."}
{215}{}{"Grupo Beta: Exploró el puerto y regresó antes de lo previsto, ni siquiera llegó a la mitad del recorrido. Nos informaron de altos niveles de radiación y destrucción significativa. Todos los puentes hacia la Isla Coronado fueron destruidos, y todos los barcos ya sean militares o civiles se han hundido o están dañados de forma grave. Se observó una alta actividad robótica en la costa, seguramente de alguna base militar. Los miembros del grupo padecen envenenamiento radioactivo."}
{216}{}{"Grupo Gamma: Exploró las ruinas hacia el sur, regresaron con una pequeña cantidad de artículos útiles y provisiones de la preguerra. Informan de destrucción moderada y niveles radioactivos altos."}
{217}{}{"Grupo Delta: Exploró las ruinas hacia el este, informaron de una disminución en la actividad radioactiva y destrucción menor. Encontraron animales desconocidos de tamaño y formas inusuales. Parte del grupo falleció."}
{218}{}{"Ninguno de los grupos encontró supervivientes o rastros de su presencia."}
{219}{}{Regresa a la lista general.}
{220}{}{Abril de 2131}
{221}{}{"Grupo Zeta: Ha regresado de la instalación de investigación West-Tek. Del grupo entero, sólo regresó uno. El superviviente informa de un nivel radioactivo extremadamente alto y destrucción significativa de la instalación. También se encontraron robots de seguridad y animales de formas desconocidas alrededor de la instalación."}
{222}{}{"El examen médico demostró que el explorador sufre una grave enfermedad por radiación y mutaciones inusuales, y se espera que fallezca pronto. No se recomienda futura exploración de la instalación de West-Tek."}
{223}{}{Mayo de 2132}
{224}{}{"Grupo Épsilon: Ha regresado de Los Ángeles. El grupo informa de una serie de asentamientos y campamentos pequeños, al más grande le llaman Adytum. Está habitada por personas que sobrevivieron al resultado de la guerra nuclear en diversas partes del sur de California. Esta gente sobrevive rebuscando en las ruinas objetos de la preguerra y comerciándolos."}
{225}{}{"También se sabe de una gran ciudad llamada El Eje, al norte de Adytum, pero no hay suficiente información sobre ella."}
{226}{}{"Los exploradores tienen opiniones contradictorias sobre la población local. Algunos del grupo temen a los forasteros, mientras que otros expresan su deseo de unirse a ellos en un solo asentamiento. Es probable que muchos exploradores estén experimentando un choque cultural."}
