{100}{}{Ves una puerta oxidada.}
{101}{}{Esta puerta del almacén está profundamente oxidada.}
{102}{}{Esta puerta se encuentra profundamente oxidada.}
{103}{}{No se mueve.}
{104}{}{La puerta está oxidada. Tendrás que usar la fuerza bruta, o un método más técnico.}
{105}{}{La puerta no pudo resistir tus esfuerzos.}
{106}{}{Unas hojuelas de óxido se desprendieron del acero, pero la puerta sigue ahí.}
{107}{}{¡Agh!}
