{110}{}{    }
{111}{}{Habla, hermano.}
{112}{}{Lo hicieron. Los necrófagos de verdad lo hicieron, pudieron activar la planta eléctrica.}
{113}{}{¡No puedo creerlo! Ahora tenemos menos tiempo aún.}
{114}{}{Entonces, ¿deberíamos capturar la presa? No estaría bien dejarles tanto poder a esos tipos...}
{115}{}{No, eso sólo va a distraernos de nuestro objetivo.}
{116}{}{Además, los necrófagos necesitan la estación para su ciudad. Es dudoso que la usen para el mal.}
{117}{}{Necesitamos actuar rápido. Regresemos a la base, allí tendremos que hablarlo todo.}

