#Regular random lines
#Important: leave lines with spaces!
{110}{}{Moo}
{111}{}{M-moo}
{112}{}{*Mugido*}
{113}{}{Mooooo}
{114}{}{ }
{115}{}{ }
{116}{}{ }
{117}{}{ }
{118}{}{ }
{119}{}{ }

#Replicas with low Intelligence GG
{120}{}{*Mugido*}
{121}{}{*Ji ji*}
{122}{}{¿Qué pedo, güey?}
{123}{}{Es mejor tener dos cabezas.}
{124}{}{¿Nos escuchas?}
{125}{}{Puede leernos la mente.}
{126}{}{¿Acaso nos está escuchando?}
{127}{}{Sabemos lo que estás pensando.}
{128}{}{Parece que está drogado.}
{129}{}{No voy a hablar con él.}
{130}{}{Si él puede oírnos, estamos en problemas.}
{131}{}{Dejémoslo ir.}
{132}{}{Pero le dirá a los demás.}
{133}{}{Nadie le va a creer.}
{134}{}{Tienes razón, ignorémoslo.}
{135}{}{Otro vagabundo más.}
{136}{}{¿Crees que sea peligroso?}
{137}{}{Cállate.}
{138}{}{No nos escucha.}
{139}{}{Basta, nos pones en peligro.}
{140}{}{Ya, dejen de pensar.}
{141}{}{Ese tipo me da pena.}
{142}{}{La gente es tan frágil.}
{143}{}{Los humanos son unos salvajes.}
{144}{}{No entiendo por qué los humanos se odian tanto.}
{145}{}{Es mejor que no toquemos a esa cosa.}
{146}{}{Nos va a escuchar.}
{147}{}{Cree que se lo está imaginando.}
{148}{}{Que hombre más tonto}
{149}{}{Contemplaré la eternidad.}
{150}{}{¡Ja! Esta criatura posee una inteligencia casi nula.}
{151}{}{Intuyo que esta pobre criatura sufrió una lobotomía.}

{1120}{}{*Bufido*}
{1121}{}{*Ji ji*}
{1122}{}{Hola, chiquita.}
{1123}{}{Es mejor tener dos cabezas.}
{1124}{}{¿Nos escuchas?}
{1125}{}{Puede leernos la mente.}
{1126}{}{¿Acaso nos está escuchando?}
{1127}{}{Sabemos lo que estás pensando.}
{1128}{}{Parece que está drogada.}
{1129}{}{No voy a hablar con ella.}
{1130}{}{Si ella puede oírnos, estamos en problemas.}
{1131}{}{Dejémosla ir.}
{1132}{}{Pero le dirá a los demás.}
{1133}{}{Nadie le va a creer.}
{1134}{}{Tienes razón, ignorémoslo.}
{1135}{}{Otra vieja más.}
{1136}{}{¿Crees que sea peligrosa?}
{1137}{}{Cállate.}
{1138}{}{No nos escucha.}
{1139}{}{Basta, nos pones en peligro.}
{1140}{}{Ya, dejen de pensar.}
{1141}{}{Esa muchacha me da tanta pena.}
{1142}{}{La gente es tan frágil.}
{1143}{}{Los humanos son unos salvajes.}
{1144}{}{No entiendo por qué los humanos se odian tanto.}
{1145}{}{Es mejor que no toquemos a esa cosa.}
{1146}{}{Nos va a escuchar.}
{1147}{}{Cree que se lo está imaginando.}
{1148}{}{Niña tonta.}
{1149}{}{Contemplaré la eternidad.}
{1150}{}{¡Ja! Esta criatura posee una inteligencia casi nula.}
{1151}{}{Parece ser que esta pobre criatura sufrió una lobotomía.}
