{100}{}{Ves a un caníbal.}
{101}{}{Ves a un hombre extraño. Tiene una sonrisa hambrienta mientras te observa.}

{110}{}{Tu cuerpo podría alimentar a mi familia entera.}
{111}{}{Tus nalgas serán un buen filete.}
{112}{}{Serás mi almuerzo.}
{113}{}{¡Dame tu carne, tengo hambre!}
{114}{}{Tu jugosa carne me ayudará a sobrevivir unos meses.}
{115}{}{Lo último que comeré serán tus menudencias. Tus ojos y cerebro vienen primero.}
{116}{}{¿Tienes alguna idea de cuántas personas podrías alimentar con tu carne?}
{117}{}{Lo siento, pero te daré un mordisco. No es nada personal.}
{118}{}{No es nada personal, solo tengo hambre.}
{119}{}{No te preocupes, no muerdo... solo haré eso después de rostizarte.}
