{100}{}{Ves a un mercader.}
{101}{}{Ves a un líder de caravana.}
{102}{}{Enfunda tu arma si quieres hablarnos.}

{200}{}{Hola, viajero. Cada vez se hace más difícil ir de sitio a sitio sin que te asalten.}
{1200}{}{Hola, viajera. Cada vez se hace más difícil ir de sitio a sitio sin que te asalten.}
{201}{}{Hmm. Hay algunos rumores sobre una mala persona, y te pareces a su descripción...}
{202}{}{¡Gracias a Dios que estás con nosotros! Me alegra haberme encontrado contigo. ¿Cómo te puedo ayudar?}
{203}{}{Solo estoy pasando por aquí.}
{204}{}{Necesito comprar suministros. ¿Tienes algo que vender?}
{205}{}{Por supuesto, es mi trabajo. Mira lo que tengo.}
{206}{}{Veamos...}
{207}{}{Ten un buen día.}
{208}{}{Adiós.}

{210}{}{¿Con qué te puedo ayudar?}
{211}{}{Adiós.}
