{100}{}{Ves a un ermitaño.}
{101}{}{Ves a un hombre peludo y harapiento. Parece que no se ha bañado en años.}
{102}{}{¡Me amenazas! ¡Wah!}

{200}{}{Hmm... Hace tiempo que no hablo con nadie. Hablar es difícil.}
{201}{}{No quiero hablar tampoco. Es mejor que partamos caminos.}

{210}{}{Fue una buena charla. Ahora vete. Estoy cansado.}
{211}{}{Hablar me da dolores de cabeza.}
{212}{}{Ya hablamos mucho por hoy. Suficiente.}
{213}{}{Adiós.}

{220}{}{¿Por qué vives aquí, así de solo?}
{221}{}{Quiero estar solo. Paz.}
{222}{}{¿Hay algún asentamiento cerca?}
{223}{}{Hermosillo está por allá. (apunta) No vayas. Peligroso.}
{224}{}{Two-Sun está por allá. (apunta) No vayas. Peligroso.}
{225}{}{¿Tienes algo que podamos intercambiar?}
{226}{}{Algo. Aquí está.}
{227}{}{Bueno, debo irme.}
{228}{}{Santa Ana está por allá. (apunta) Buen lugar.}
