{100}{}{Ves a un viajero.}
{101}{}{Ves a un hombre con barba, lleva una chaqueta sucia y raída con una escopeta recortada en su cinturón. Te observa con recelo.}

{200}{}{Mantén la distancia, el perro muerde. ¿De dónde eres?}
{201}{}{Soy de una aldea en el norte de Arizona. ¿Y tú?}
{202}{}{Soy del sur de California. Estoy viajando.}
{203}{}{¿Puedo hacerte algunas preguntas?}
{204}{}{Ya veo. Bueno, es mejor que sigamos con nuestras vidas. Adiós, viajero.}

{210}{}{¿Qué tienes en mente?}  
{211}{}{Tengo que irme.}
{212}{}{Ten cuidado ahí afuera. Me topé con necrófagos y ratas gigantes más veces de la que me gustaría. Mantente alerta, y buena suerte.}  
{213}{}{Adiós.}

{220}{}{¿A dónde vas?}
{221}{}{Ningún lado en específico. Solo estoy viajando, espero encontrar algún sitio libre de la guerra o la codicia humana. Y si no queda ninguno... tendré que hacerlo yo.}  
{222}{}{¿Tienes noticias de California?}
{223}{}{Las cosas se han puesto difíciles. El ejército supermutante ya desapareció, casi todos en Necrópolis se fueron al sur, y parece que habrá otra guerra de comerciantes en el Eje. Hay demasiada gente en el Cementerio, así que la gente se está yendo, buscando otro lugar en donde vivir.}  
{224}{}{¿Por qué tienes un perro?}
{225}{}{Me lo encontré en la carretera y me empezó a seguir. Primero pensé en cocinarlo, pero resulta que un perro es de mucha ayuda para viajar.}  
{226}{}{¿Quieres comerciar?}
{227}{}{Claro, veamos lo que tienes.}
{228}{}{¿Sabes si hay algún asentamiento por aquí?}
{229}{}{Por lo que escuché, hacia el este no hay nada más que desierto. La verdad, me sorprende haber encontrado a alguien en primer lugar. Pero, también escuché que los Rangers están al noreste. La gente sabe de ellos hasta en California.}  
{230}{}{¿Algo más?}
{231}{}{Me advirtieron sobre las ruinas hacia el oeste, el Infierno, es un lugar mortal en donde una persona corriente no tendrá ninguna oportunidad. Si piensas en ir hacia allá, piénsatelo dos veces.}  
