{100}{}{Ves a un patrullero.}
{101}{}{Ves a un soldado en un típico equipamiento militar.}

{110}{}{¡Un intruso!}
{111}{}{¡Veo un intruso!}
{112}{}{¿Eres gringo, no?}
{113}{}{Esto es territorio de México, gringo.}
{114}{}{¿Qué estás buscando?}
{115}{}{¿Vienes del norte?}
{116}{}{Esto es Nuevo México.}
{117}{}{¡Ésta es nuestra tierra!}
{118}{}{¡Guarda tus armas!}
{119}{}{No nos caen bien los gringos.}
{120}{}{¿Quién demonios eres?}

{210}{}{«¡Traidor!»}
{211}{}{«¡Maldito seas!»}
{212}{}{«Que bueno que no eres gringo.»}
{213}{}{«¡Bienvenido a México!»}
{214}{}{«¿Qué estás buscando? ¿Te ayudo?»}
{215}{}{«¿Eres del norte? ¿Qué hay por allá?»}
{216}{}{«Esto es Nuevo México, pero extraño el sur.»}
{217}{}{«Ésta es nuestra tierra, nada de gringos.»}
{218}{}{«Guarda el arma, por favor.»}
{219}{}{«Ojalá no llegue ni un pinche gringo.»}
{220}{}{«¿Quién eres?»}
