{110}{}{¿Quiere escuchar un chiste, señor McClellan?}
{111}{}{Buenos días, señorita McClellan.}
{112}{}{¡Eres un maldito, mataste a la señorita McClellan!}
{113}{}{¡Sal de aquí! ¡No dejaré que les hagas daño!}
{114}{}{¡Sálvese, señorita McClellan! ¡Escóndase en el sótano con los niños!}
{115}{}{¡Seré leal hasta la muerte!}
{116}{}{Lo siento, pero el Sr. McClellan llevó a caminar al perro.}
{117}{}{¡Un ladrón! ¡Maestro, escóndase y cierre la puerta!}
{118}{}{¿¡Qué le hiciste al perro de mis dueños!?}
{119}{}{¿Qué fue ese destello? ¿...Señor McClellan? ¿Está bien? ¡Señor McClellan!}
{120}{}{No puedo herir a los miembros de la familia. Pero tú no eres parte de ella.}
{121}{}{Me programaron para obedecer únicamente a las órdenes de la familia McClellan.}
{122}{}{Debo cuidarme, pues soy propiedad de la familia.}
{123}{}{Parece que va a llover.}
{124}{}{¡Tu sangre me lubricará los brazos, plebeyo asqueroso!}
{125}{}{Activando el protocolo de Limpieza Profunda.}
{126}{}{¿Quiere que agregue el cráneo de este simio a su colección, señor McClellan?}
{127}{}{¿Deberíamos cocinar al intruso con ajo o con mostaza, señorita McClellan?}
{128}{}{Eso es una infracción, vas a pagarnos la multa.}
