{110}{}{¡Eres una malvada bestia!}
{111}{}{Eres peor que un animal.}
{112}{}{Vengaré a cada niño que has matado.}
{113}{}{Vengaré a esos niños, y no podrás escaparte.}
{114}{}{¿Puedes escuchar los llantos de los niños que mataste, monstruo?}
{115}{}{¿Crees que puedes ir por ahí matando niños?}
{116}{}{¡Eres un bastardo!}
{117}{}{Son niños... ¿Cómo puedes herirlos? Son almas puras.}
{118}{}{Acabaré con cualquiera que dañe a los pequeños.}
{119}{}{Aunque sus muertes hayan sido por accidente, las pagarás.}
