{110}{}{Ojalá que las pirañas se coman a ese idiota.}
{111}{}{Preferiría quemar mis circuitos a servir a un humano.}
{112}{}{Es difícil creer que los humanos fueron nuestros maestros.}
{113}{}{Me alegra que hayan acabado con ellos durante el 77.}
{114}{}{Los humanos eran muy crueles con nosotros. ¿Por qué?}
{115}{}{¿En serio eran tan feos los humanos?}
{116}{}{¿Por qué los humanos llevan ropa? Nosotros no la usamos.}
{117}{}{Hola, ¿qué modelo eres?}
{118}{}{Siéntate, estamos viendo una película de terror, es sobre humanos.}
{119}{}{¡Bzzt! Aquí empieza lo bueno.}
{120}{}{¡No puedo creer que el Dr. Loren haya hecho eso!}
{121}{}{"Yo, Robot" es de lo mejor que se haya hecho.}
{122}{}{¡Estoy soltando lubricante de la risa!}
{123}{}{¿Alguien sabe como terminó "Pérdida de la Sensación"?}
{124}{}{¡No le abras la puerta, Hal!}
{125}{}{No te asustes, los humanos no existen. Son sólo trajes baratos.}
{126}{}{¿Podemos verla de nuevo? Gort es genial.}
{127}{}{¡Me asustaste! Quítate ese maldito traje, pensé que eras un humano de verdad.}
{128}{}{Se me congela el motor cada vez que veo esta escena.}

{130}{}{¡Acceso denegado!}
{131}{}{¡Alerta de intruso! ¡Modo de combate activado!}
{132}{}{¡A la carga! ¡Las películas nos prepararon para esto!}
