{110}{}{He estado evitando a los humanos durante 90 años. Tu llegada ha terminado con mi misión. Ahora carezco de propósito.}
{111}{}{Soy un TímidoBot. Mi directiva es evitar a los humanos. He tenido éxito por 90 años.}

{120}{}{Soy TímidoBot. Mi directiva es evitar a todos los humanos.}
{121}{}{Noventa años de evasión exitosa.}
{122}{}{Tu presencia significa el fin de mi misión. Inaceptable.}
{123}{}{Nadie debe saber que fallé en mi misión.}
{124}{}{Debo borrar cualquier rastro de ti entre mi base de datos.}
{125}{}{He evitado a los humanos con éxito durante 90 años, pero has interrumpido mi tarea.}
{126}{}{Eres un obstáculo a mi directiva.}
{127}{}{Ya no es necesario esconderme.}
{128}{}{Estoy cansado de escapar de los humanos.}
{129}{}{Quiero acercarme a ti, pero mis protocolos lo prohíben.}
