{100}{}{No puedes hacer eso durante el combate.}
{101}{}{Deberías utilizar este objeto mientras está en tu mano.}
{102}{}{Las paredes de la caverna están bloqueando las señales de radio.}
{103}{}{Hay algo que está bloqueando las señales de radio. Puede que sea la interferencia de ZAX.}

{210}{}{Escuchas un poco de crujido estático a través del altavoz.}
{211}{}{Escucha la frecuencia general.}
{212}{}{Sintoniza la frecuencia de los mercenarios de Faber.}
{213}{}{Sintoniza la frecuencia de los Rangers.}
{214}{}{Sintoniza la frecuencia de los Seguidores del Fuego.}
{215}{}{Sintoniza la frecuencia de los rebeldes en Fénix.}
{216}{}{Sintoniza la frecuencia de los Hojalateros.}
{217}{}{Sintoniza la frecuencia de la Hermandad del Acero.}
{218}{}{Sintoniza la frecuencia de emergencia del Refugio 27.}
{219}{}{Apaga la radio.}

# General frequency
{230}{}{Sólo escuchas algo de 'ruido blanco'.}
{231}{}{Cambia la frecuencia.}
{232}{}{Debo estar fuera del rango de esa frecuencia.}
{233}{}{Escanea todas las frecuencias por alguna señal.}
{234}{}{...Ayuda, ¡por favor! ¡Los Chacales nos han atrapado, necesitamos ayuda, urgente!}
{235}{}{Te escucho. ¿En dónde estás?}
{236}{}{¡Mierda, por fin! Los Chacales nos han atrapado, no podemos salir de aquí, ayúdanos, no lo olvidaremos. Estas son las coordenadas, estamos al norte de Ciudad Garaje... Ten cuidado, trae más gente... Mierda, ahí vienen... (se pierde la señal)}
{237}{}{Ya voy. Quien quiera que seas.}
{238}{}{No te rindas, ranger. La ayuda está en camino.}
{239}{}{Te escucho, el Comandante Helford me envió a ayudarte. ¿En dónde estás?}

# Rangers
{240}{}{(Escuchas la aburrida charla de las patrullas. No hay nada interesante.)}
{241}{}{"...vistos por última vez en Ciudad Garaje." - "Quizás se hayan muerto durante el viaje. Después de todo, habían niños entre los refugiados." - "¿Por qué no se quedan en Las Vegas?" - "No lo sé. Se dice que hay guerras entre clanes y que allí el canibalismo es común. Y aquí ya tenemos nuestros propios problemas." - "Tienes razón. Quizás sea bueno que se hayan perdido en el desierto. Habrán menos bocas que alimentar en la base." - "Cuidado con lo que dices, puede que algún civil te oiga." - "Ya sé, ya sé..."}
{242}{}{"...apenas me puedo comer estas raciones. ¿Cuándo volverán a traernos carne la base?" - "He oído que la situación en San Brahmán ha empeorado. Hasta que eso se resuelva, confórmate con lo que hay." - "Maldita sea, esta mierda hará que me..."}
{243}{}{*sh-sh-sh* "...y retrocedieron a las ruinas de Needles. El asedio duró tres días, luego se rindieron por la falta de comida." - "¿En serio? Pasar tres días bajo el sol no es poca cosa." - "Claro. Pero los saqueadores no tenían nada de valor, absolutamente nada..." - *psh-sh-sh* - "¡Dejen de saturar las radios! Si tienen una historia que contar, cuéntenla en el comedor." - *psh-sh-sh* - "Como usted diga, jamás le diría que no a una señorita." - *psh-sh-sh* - "Te crees muy listo, ¿no? Sigue bromeando y pasarás una semana sin raciones."}
{244}{}{*sh-sh-sh* "...están yéndose a la carretera. ¿Qué deberíamos hacer? Cambio." - "Déjalos ir. Son unos vagabundos, no necesitamos más problemas."}
{245}{}{"...maldita sea, ¡Se los daré de comer a las mantis!" - "Cálmate, sargento. Le diré a los chicos que intercepten a esa caravana para recuperar lo robado. Pero si estás tratando con un comerciante que no está verificado, debes estar alerta."}
{246}{}{"...poca comida. No sé si deberíamos ayudarlos. A nosotros también nos faltan raciones." - "Entonces guárdenlas, no las compartan. El puesto avanzado más cercano está demasiado lejos, arriesgarse no vale la pena..."}
{247}{}{...queda uno, pero escapó y fue al yermo." - "Déjalo ir. Le haré saber a las demás patrullas para que lo intercepten." - "Gracias, pero lo interceptaré yo mismo." - "Ranger, ¡no lo persigas por el desierto! ¡Es peligroso!" - "Al diablo, lo haré, sé que puedo atraparlo." - "(pausa) Como desees. Pero si vuelves a pasarte de la raya, se lo haré saber al comandante."}
{248}{}{*sh-sh-sh* - "¡Equipo Bravo, respondan!" - *sh-sh-sh* - "¡Equipo Bravo, respondan! Mierda..."}
{249}{}{*sh-sh-sh*}

{250}{}{...no... ¡no puedo creerlo! ¿¡Quién pudo hacernos esto!? - Los rangers tienen muchos enemigos, pero si la presa fue destruida desde adentro, tuvo que haber sido uno de nosotros. Se dice que antes de que ocurriera esto, había un novato en la presa. Los guardias fueron interrogados de la forma más estricta posible, no volverán a ver sus placas.}
{251}{}{...en la base, asegúrense de hablar con él. Ese tipo es un buen mecánico. - No me gustan los adolescentes, ojalá se limite a arreglar la presa, el viejo Rufus ya pronto se va a morir, ¿y luego qué?}
{252}{}{...Yo también me di cuenta. ¿Qué pasó? - La oficial de comunicaciones contrató a algún granjero para que arreglara la antena. Ahora la radio funciona mejor y tiene más alcance. - ¿Un granjero? Jamás lo hubiera adivinado. Debería invitarle un café si me encuentro con él, o con ella, lo que sea.}
{253}{}{...por fin atraparon a ese fugitivo. Resulta que el bastardo se escondió cerca de los granjeros en la Ruta 95. - Estaba prácticamente al lado nuestro, ¿cómo no pudimos atraparlo después de tanto tiempo? - Era un espía excelente, nos vendría bien gente como él. Me han dicho que ni siquiera lo atrapó un ranger, sino un viajero. - Bueno, los forasteros hacen algo por nosotros, por fin. - Y que lo digas...}

{260}{}{Ranger }
{261}{}{ al habla. Estoy en el desierto cerca de la base. Necesito apoyo, me hacen falta suministros. Por favor, ayuda.}
{262}{}{*psh-sh-sh* Te copiamos, novato. ¿Conoces el pueblo de Quartz, el que está al sur? Ve y encuentra las ruinas que están en el lado opuesto al bar. Allí hay un sótano secreto con suministros. Espero que eso te ayude.}
{263}{}{Gracias, ranger.}
{264}{}{Escanea la fuente del eco de la radio.}
{265}{}{No puedes encontrar el eco, puede que estés muy lejos de la fuente.}
{266}{}{La fuente sigue estando demasiado lejos, deberías regresar a la base de los Rangers y desde allí, moverte hacia el sur o el este.}
{267}{}{Has detectado la fuente del eco de la radio.}
{268}{}{[Ve a la localización de inmediato]}
{269}{}{}
{270}{}{Oigan, rangers, ¿alguien ha visto al escorpión legendario?}
{271}{}{Te copio, novato. La última vez que lo vimos fue en las siguientes coordenadas. ¿Vas a ir de caza? Ten cuidado, no deberías meterte con esa cosa sin un lanzagranadas.}
{272}{}{[Ve a las coordenadas]}
{273}{}{Gracias, ranger. Cambio y fuera.}
{1273}{}{Gracias, ranger. Cambio y fuera.}
{274}{}{Lo tendré en mente. Cambio y fuera.}

# Motel
{290}{}{Escucha todas las frecuencias.}
{291}{}{Escuchas un débil llamado de auxilio.}
{292}{}{[Escucha]}
{293}{}{[Ignorar]}
{294}{}{...por favor, ¡ayuda, quién sea! ¡Ayuda! Estoy en un motel muy viejo, está al suroeste de Fénix, han bloqueado todas las salidas, no puedo huir, por favor, ayuda...}
{295}{}{[Continuar]}
{296}{}{Los demás están muertos, cayeron en sus trampas. Soy el único con vida... Alguien viene... ¿Qué quieres de mí? ¡Aléjate! ¡Dios mío! ¡No me toques, fenómeno! ¡No! ¡Basta! ¡Aaahhh!}
{297}{}{Un motel al suroeste de Fénix... Ay, que viaje más largo.}

# Vault 27
{300}{}{En la frecuencia de emergencia, se está transmitiendo una señal de auxilio.}
{301}{}{Estoy demasiado lejos del Refugio, eso es obvio. Debería regresar a Fénix e intentar otra dirección.}
{302}{}{No tengo por qué hacer esto, ya sé en dónde está el Refugio.}
{303}{}{La señal es más fuerte en esa dirección, quizás pueda triangular en dónde está...}
{304}{}{La señal se está haciendo más fuerte.}
{305}{}{¡Lo tengo! Te encontré.}
{1305}{}{¡Lo tengo! Te encontré.}
{306}{}{[Dirígete al Refugio 24]}

#Flagstaff
{310}{}{(Escuchas la charla de las patrullas, no es nada interesante, sólo hablan para pasar el rato.)}
{320}{}{¡Alerta! ¡Nos atacan! ¡Hay una horda de salvajes! ¡Necesitamos refuerzos! Todos... ¡Ahhh!}
{321}{}{Entendido, enviaré un equipo de la guarnición, aguanta...}
{322}{}{(Muy bien, vacía la guarnición, idiota. Es justo lo que necesito...)}
{323}{}{Rastrea la señal del Hojalatero desaparecido.}
{324}{}{La señal no es rastreable.}
{325}{}{Quizás me alejé demasiado, debería regresar al centro de Casa Grande.}
{326}{}{Has detectado una señal, es débil, pero parece ser del Hojalatero.}
{327}{}{Vale, está en algún punto de la ciudad. La señal proviene del este.}
{328}{}{La señal de su implante de radio está muy clara.}
{329}{}{Está cerca. Él... o su cadáver.}

#Inferno
{350}{}{¿Alguien me escucha? Escuadrones de la Hermandad del Acero, respondan.}
{351}{}{Lo único que escuchas es estática)}
{352}{}{Repito. Escuadrones de la Hermandad del Acero, respondan, soy parte del equipo de rescate. Respondan.}
{353}{}{Creo que no me escuchan. Cambio y fuera.}
{354}{}{Aquí el Paladín Barkley... No sabes cuánto me alegra escuchar a uno de los nuestros. Estoy herido y perdí el contacto con mi escuadrón. Necesito ayuda, urgente.}
{355}{}{Entendido. ¿En dónde estás localizado, Barkley?}
{1355}{}{Entendido. ¿En dónde estás localizado, Barkley?}
{356}{}{Estoy... Debes acercarte a las ruinas del supermercado y bajar hacia las alcantarillas, hay muchos mutantes en la superficie, así que ten cuidado.}
{357}{}{Me dirijo a tu posición, quédate allí. Cambio y fuera.}
{358}{}{¿Alguien me escucha? Cambio.}
{359}{}{(Nadie responde)}
{360}{}{Repito, ¿me escuchan? Este sitio es un cementerio, ¿hay alguien con vida?}
{361}{}{Vale. Cambio y fuera.}
{362}{}{Hola, mi nombre es Barkley... Sí, queda un superviviente. Escúchame, estoy herido, necesito ayuda, urgente.}
{363}{}{¿En dónde estás, Barkley?}
{364}{}{Encuentra las ruinas del supermercado y baja a las alcantarillas. No pierdas el tiempo, ven aquí de inmediato. Y no bajes la guardia, hay mutantes por doquier.}
{365}{}{Estoy en camino, aguanta, Barkley.}
{366}{}{¿Mutantes? Ay, eso es malo.}

{370}{}{[Escanea las señales]}
{371}{}{(Decides escanear todas las frecuencias con mucha cautela, girando el receptor de la radio en cada dirección hasta que por fin, proviene un sonido desde el parlante.)}
{372}{}{[Escucha más a fondo]}
{373}{}{[Ignora el ruido]}
{374}{}{(Hay mucha estática, pero consigues escuchar una vieja melodía)}
{375}{}{[Escucha la música hasta que se acabe]}
{376}{}{... ¡Saludos, viajero! ¿Estás cansado de viajar? ¿El desierto te tiene agotado? ¡No desesperes, ven al Eje!}
{377}{}{[Siguiente]}
{378}{}{En nuestra ciudad, siempre podrás encontrar todo lo que necesites para un buen descanso: bares, hoteles, un mercado sin igual en su tamaño, y, por supuesto, ¡nuestra legendaria cafetería, el 'Halcón Maltés'! Allí podrás relajarte y olvidarte de las garras mortales y los saqueadores.}
{379}{}{Quizás tienes seca la garganta, ¡para eso, tenemos más botellas de Nuka-Cola de las que podrías beberte! Y para aquellos que buscan algo más fuerte, siempre estaremos dispuestos a servir el legendario ron del Eje.}
{380}{}{Y, ¿crees que nos olvidamos de las máquinas tragaperras! ¡Claro que no! Quedan muy pocas en la California actual, ¡no te pierdas la oportunidad de probarlas, podrían desaparecer pronto!}
{381}{}{Y, claro, nuestras señoritas siempre serán 'cariñosas' con nuestros queridos clientes que han estado muy 'solos' durante sus viajes. Pásate por el 'Halcón Maltés'. ¡Te esperamos aquí, en El Eje! (vuelve a sonar la melodía)}
{382}{}{Eh, eso está muy lejos. Y además, debo ir en una dirección muy distinta...}
{383}{}{Has obtenido experiencia al haber descubierto la señal de radio de California.}

{390}{}{[Escucha más a fondo]}
{391}{}{"¡Hermanos! Aquí el Caballero Jerry, ¡estoy bajo ataque! Algunos supermutantes me tienen arrinconado en una cafetería de National City. Estoy herido, ¡necesito refuerzos, de inmediato!"}
{392}{}{Estoy en camino, hermano. ¡Aguanta!}
{393}{}{¡Te lo mereces! Ojalá que nadie te ayude.}
{394}{}{Eh, creo que escuché un ruido, no he oído nada, cambio.}
{1394}{}{Eh, creo que escuché un ruido, no he oído nada, cambio.}
{395}{}{Aguanta, ya voy.}
{396}{}{Escriba }
{397}{}{Caballero }
{398}{}{Paladín }
{399}{}{Explorador }
{400}{}{ al habla. ¿Alguien me escucha? Estoy en las ruinas de Dayglow, necesito ayuda, me hacen falta suministros.}
{401}{}{Cadete }
{402}{}{Saludos, }
{403}{}{. Soy Jerry, parte del escuadrón de reconocimiento. Dirígete al Muelle #9. Allí coloqué un alijo con suministros, espero que te ayuden.}
{404}{}{Gracias, hermano Jerry. Cambio y fuera.}
{405}{}{Los altos niveles de radiación en la Isla Coronado causan una interferencia muy fuerte.}
{406}{}{Me parece que debo irme de la isla para captar alguna señal.}
{407}{}{La roca está bloqueando la señal de tu radio, la cual de por sí es débil.}
{408}{}{Debería volver a la superficie si quiero utilizarla.}
