{110}{}{Aquí hay mucha información valiosa de la preguerra. Echarle un ojo sería una buena idea.}
{111}{}{Parece que no eres capaz de entender información tan compleja.}
{112}{}{Estos libros están más allá de tu capacidad mental.}
{113}{}{Te pasaste el día entero aprendiendo valiosa información de la preguerra. Todo está mucho más claro.}
{114}{}{Ojeaste las notas, pero no aprendiste nada nuevo.}
{115}{}{Ahora tienes acceso a la computadora de la librería.}

{121}{}{Al predicador no le hará ninguna gracia que leas sus libros sin su permiso.}
{122}{}{La computadora de la librería necesita una tarjeta de acceso.}
{123}{}{Ponerte a leer en una sala llena de gas tóxico no es la mejor idea que has tenido.}
{124}{}{A los Seguidores no les será de agrado que eches un ojo sin su permiso.}
{125}{}{Los escribas de la Hermandad no te han otorgado acceso a la base de datos.}
{126}{}{A los cultistas no les gustará que leas sus libros sin permiso.}
