{110}{}{Esa habilidad no te ayudará aquí.}
{111}{}{¿Quieres ponerte a cavar en medio de una pelea? Claro que no.}
{112}{}{Con músculos como los tuyos, ni puedes levantar la pala.}
{114}{}{Necesitas una herramienta para cavar esto.}
{115}{}{Alguien enterró a un perro aquí. Es evidente que tenían prisa.}
{116}{}{No es tan fácil rellenar un agujero como este.}
{117}{}{Mientras cavas, la tumba colapsa de repente y te arrastra hacia las profundidades.}
{118}{}{Chingada madre...}
{119}{}{Ay...}
{120}{}{El agujero es muy, muy profundo.}
