{110}{}{Parece que este  }
{111}{}{ sufrió un cortocircuito. Pero debería poder repararse.}
{112}{}{Este }
{113}{}{ está funcionando. Y seguirá así por un tiempo.}
{114}{}{Ya reparaste el }
{115}{}{.}
{116}{}{Has reparado esta }
{117}{}{. Ahora iluminará por un buen tiempo.}
{118}{}{No conseguiste repararlo. Quizás debas mejorar tu habilidad de Reparar.}
{119}{}{Hiciste algo mal. Inténtalo de nuevo.}
{120}{}{ se ha descompuesto permanentemente por tu incompetencia.}
