{110}{}{Este mini-laboratorio está lleno de componentes. Necesitas conocimiento científico para utilizarlos.}
{111}{}{El mini-laboratorio está vacío. Es inútil.}
{112}{}{Deberías haber pasado más tiempo leyendo tus libros de química.}
{113}{}{Luego de mucho trabajo, fabricaste un estimulante.}
{114}{}{Luego de mucho trabajo, fabricaste dos estimulantes.}
{115}{}{Luego de mucho trabajo, fabricaste tres estimulantes.}
{116}{}{Fabricaste algo de combustible.}
