{110}{}{¡Una trampa!}
{111}{}{Descubriste una trampa.}
{112}{}{ cayó en una trampa.}
{113}{}{Tus habilidades te salvaron de una peligrosa trampa.}
{114}{}{}
{115}{}{Esta trampa parece ser muy peligrosa.}
{116}{}{Has desactivado la trampa.}
{117}{}{Te preocupa que no podrás colocar apropiadamente la trampa.}
{118}{}{Has colocado la trampa.}
{119}{}{La trampa está segura por ahora.}
{120}{}{La trampa es demasiado peligrosa. Debes neutralizarla primero.}
{121}{}{Desactivaste el emisor.}
{122}{}{Eres incapaz de desactivar el emisor.}
{123}{}{Este es un buen lugar para colocar una trampa.}
{124}{}{Esto podría ser una buena trampa.}
