{100}{}{Terminaste en medio de un derrumbe. Por esta vez te pudiste salvar.}
{101}{}{Las montañas intentaron detenerte, pero esquivaste las rocas con facilidad.}
{110}{}{Cruzaste unas tierras irradiadas y recibiste una alta dosis de radiación.}
{120}{}{¡Acabaste en medio de una despiadada tormenta de polvo!}
{130}{}{Intentas encontrar agua, pero no tienes éxito.}
{131}{}{Luego de una dura búsqueda, encontraste algo de agua.}
{132}{}{Conseguiste mantenerte hidratado, gracias a tu propio suministro de agua.}
{133}{}{Te has mantenido hidratado, gracias a tu confiable cantimplora.}
{134}{}{Parece que hubo un accidente de tráfico. ¡Es el precio de saltarse las luces rojas!}
