# 
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Текстовые метки и сообщения, используемые FISSION
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

#
# Настройки
#

#
# Сообщения
#

{100}{}{Отключение Широкого экрана отключит}
{101}{}{расширенные настройки.}
{102}{}{Вы уверены, что продолжить?}
{103}{}{Изменения графики вступят в силу}
{104}{}{после перезапуска.}
{105}{}{Режим Игровой зоны 'Ориг.' отключит}

#
# Доп. Заголовки
#

{124}{}{ЭКРАН}
{125}{}{РАСТЯЖЕНИЕ}
{126}{}{КАЧЕСТВО}
{127}{}{ИГРОВАЯ ЗОНА}
{128}{}{} #Leave blank
{129}{}{} #Leave blank

#
# Доп. Метки
#

{225}{}{Выкл}
{226}{}{Полный экран}        
{227}{}{Выкл}        
{228}{}{Широкий экран} 
{229}{}{Выкл}           
{230}{}{Растянуть} 
{231}{}{Выкл}
{232}{}{Соотношение сторон}
{233}{}{Выкл}         
{234}{}{Высокое качество}        
{235}{}{Выкл}
{236}{}{Квадратные пиксели}
{237}{}{Ориг}      
{238}{}{Умолч}        
{239}{}{Больш}  
{240}{}{Огр}  

#
# Fission About
#

{300}{}{F.I.S.S.I.O.N.}
{301}{}{Гибкая изометрическая система симуляции}
{302}{}{для интерактивной открытой ядерной ролевой игры}

