/*

Shelf Fixes mod for Fallout: Sonora by Lexx (from Fallout et tu)
----------------------------------------------------------------

Requires sfall 4.1.7/3.8.17 or higher

*/

#include "..\headers\define.h"
#include "..\headers\sfall\sfall.h"

#define obj_weight(x)  proto_data(obj_pid(x), it_weight)

procedure start;
procedure InventoryMove_handler;

procedure start begin
   if (game_loaded) then begin
      register_hook_proc(HOOK_INVENTORYMOVE, InventoryMove_handler);
   end
end

procedure InventoryMove_handler begin
   variable
      slot := get_sfall_arg,
      item := get_sfall_arg,
      pid, scenery_hex, scenery_ptr;

   // Prevent player from picking up objects that should never be able to be picked up
   // Is needed if player uses cheat mods to increase inventory size
   if (slot == 7) then begin // picking up items
      if (obj_weight(item) > 999) then set_sfall_return(0); // block
   end

   // If player uses a bookshelf corner object, reroute the use action to the actual bookshelf
   pid := obj_pid(item);
   if (pid == 237 or pid == 239) then begin // FSonora specific PIDs
      reg_anim_clear(dude_obj);
      scenery_hex := tile_num_in_direction(tile_num(item), 5, 2);
      scenery_ptr := tile_contains_pid_obj(scenery_hex, dude_elevation, pid - 1); // actual bookshelf PID
      if (scenery_ptr > 0) then begin
         set_self(dude_obj);
         pickup_obj(scenery_ptr);
         set_self(0);
      end
   end
end
