#
#
#
#
#
{0}{}{Préférences de jeu}
{1}{}{Réglages de l'écran}

{50}{}{Réglages de l'écran}
{51}{}{Personnalisé}
{52}{}{Largeur}
{53}{}{Hauteur}
{54}{}{Valider}
{55}{}{Annuler}
{56}{}{Fallout doit redémarrer pour appliquer ces paramètres.}
{57}{}{Voulez-vous redémarrer Fallout maintenant ?}
{58}{}{Vrai}
{59}{}{Faux}
{60}{}{}

{100}{}{Haute résolution}
{101}{}{RESOLUTION}
{102}{}{Couleurs}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Modifier l'image de la barre latérale}
{107}{}{Inverser la liste}
{108}{}{Fenêtré}
{109}{}{Touche de défilement}
{110}{}{Mise à l'échelle X2}
{111}{}{Taux de rafraîchissement}

{130}{}{Touche Fenêtre}
{131}{}{Sélection}
{132}{}{Nom}

{140}{}{Mode graphique :}
{141}{}{Basique}
{142}{}{Mode Sfall DirectX 9 :}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Traitement matériel des Vertex :}
{149}{}{Version des Shaders 2.0 :}

{150}{}{Mise à l'échelle du panneau}
{151}{}{Aucun}
{152}{}{Adapter}
{153}{}{Remplir}

{154}{}{Films}
{155}{}{Démarrage}
{156}{}{Aide}
{157}{}{Mort}
{158}{}{Fin}
{159}{}{Menu}

{200}{}{Sfall}
{201}{}{ECHELLE : RES.}
{202}{}{MODE DX-9}
{203}{}{Désactivé}
{204}{}{Plein écran}
{205}{}{Fenêtré}
{206}{}{Blitting GPU}
{207}{}{Ce paramètre n'a aucun effet en mode graphique de base.}

{250}{}{Ignorer la limite de défilement}
{253}{}{Plage du Path Finding}
{254}{}{Normal}
{255}{}{Max}
{256}{}{Autoriser le brouillard de guerre}
{257}{}{Visibilité du brouillard}
{258}{}{Sombre}
{259}{}{Plus lumineux}

{300}{}{PRESSER LA TOUCHE A ou ESC pour annuler.}

{500}{}{Paramètres du patch haute résolution.}
{501}{}{Configurer la résolution de l'écran, le mode couleur et le taux de rafraîchissement pour le mode plein écran.}
{502}{}{Configurer ici la sortie couleur plein écran.}
{503}{}{Définissez ici le taux de rafraîchissement du plein écran. Réglez cette valeur sur « 0 » pour le réglage par défaut du pilote.}
{504}{}{Personnalisez la largeur du plein écran en cliquant sur la case numérique.}
{505}{}{Personnalisez la hauteur du plein écran en cliquant sur la case numérique.}
{506}{}{Activer ou désactiver le mode fenêtré.}
{507}{}{En mode fenêtré, c'est la touche que vous devez maintenir enfoncée lorsque vous utilisez la souris pour faire défiler les cartes du jeu et du monde.}
{508}{}{Appuyez sur le bouton rouge pour sélectionner une autre touche, ou cliquez sur la case numérique pour modifier le code Windows Virtual key.}
{509}{}{Le nom de la touche actuellement sélectionnée.}
{510}{}{Activer la mise à l'échelle X2. Cela augmentera également la résolution minimale à 1280x960. Le mode fenêtre nécessitant plus d'espace pour son cadre.}
{511}{}{Activer ou désactiver le brouillard de guerre. Pour obtenir les meilleurs résultats, il convient de l'activer avant d'entrer sur une carte pour la première fois.}
{512}{}{Ajustez le niveau de luminosité et la visibilité de la souris sur les sols, les murs et le décor sous le brouillard.}
{513}{}{Les sols, les murs et les décors seront toujours visibles et la fonction « regarder » de la souris fonctionnera normalement.}
{514}{}{Les sols, les murs et les décors seront assombris et ne répondront pas à la fonction « regarder » de la souris tant qu'ils n'auront pas été découverts.}
{515}{}{Lorsque cette option est activée, le défilement loin du personnage joueur est illimité. Cela fonctionne bien si l'option Fog Of War est activée.}
{516}{}{Augmentez le nombre de nœuds de recherche pour étendre la distance de recherche de chemin. 20 niveaux par incréments de 2000 nœuds.}
{517}{}{2000 nœuds de recherche de chemin (valeur d'origine). Remarque : chaque niveau nécessite 156,25 Ko de mémoire supplémentaire.}
{518}{}{40 000 nœuds de recherche de chemin. Remarque : nécessite 3 200 000 octets (3 125 Ko) de mémoire.}
{519}{}{Ajustez l'affichage de certains écrans.}
{520}{}{Taille originale.}
{521}{}{Étiré pour s'adapter à la taille de l'écran tout en conservant le format d'origine.}
{522}{}{Étiré pour remplir l'écran. Remarque : un espace restera en bas de l'écran si les sous-titres sont activés.}
{523}{}{Cliquez ci-dessous pour faire défiler les options de la barre latérale de l'interface du jeu.}
{524}{}{Appliquez les modifications et quittez.}
{525}{}{Quitter sans sauvegarder.}


