{100}{}{You see a fugitive.}
{101}{}{You see a man in a business suit. He's bleeding.}
{102}{}{Please save... I have gold... a lot of gold...}

{198}{}{(A man in a business suit stumbles towards you; he focuses his bloodshot eyes on you, takes in your armor, then shakes his head in dazed confusion.)}
{199}{}{(A man in a business suit stumbles towards you; his bloodshot eyes focus on you, then he recoils in horror. He stands shakily before you, swaying slightly.)}
{200}{}{(A man in a business suit stumbles towards you; his head is bleeding, and he can barely stand on his feet.)}
{201}{}{You look like crap, buddy.}
{202}{}{My god, you're hurt bad!}
{203}{}{P-please... help... (falls at your feet, clinging to you with all his might) I'll give everything... I have gold... (falls to the ground) A lot... gold...}
{204}{}{Hey, man. Gold isn't really worth anything anymore. ...Can you hear me?}
{205}{}{Uh... everything will be fine, hang in there...}
