{110}{}{En este momento, el bote solo es adecuado para navegar al fondo del mar. El casco necesita ser reparado y el motor necesita energía.}
{111}{}{El motor no arranca. El medidor indica que la célula de energía está agotada.}
{112}{}{El bote ya está listo para zarpar. Utiliza la habilidad de Ciencia para navegar.}
{113}{}{Arreglaste las grietas y agujeros en el casco.}
{114}{}{La célula ha sido recargada. Hay suficiente energía para una ida y vuelta.}
{115}{}{La célula ya fue recargada.}
{116}{}{Ya no tienes ningún lugar a donde ir.}
{117}{}{El bote no puede resistir tanto peso. Vacía todo lo innecesario de tu inventario.}
{118}{}{Puedes llevar el bote de vuelta a la costa. Utiliza la habilidad de Ciencia para regresar y asegúrate de haber explorado todo.}
{119}{}{Este bote tiene suficiente combustible para regresar a la costa.}
