{100}{}{Ves una terminal de seguridad.}
{101}{}{Ves una terminal con acceso a la red pública.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Regresar al menú principal}

{210}{}{Activar torretas de seguridad.}
{211}{}{Usuario desconocido. Acceso bloqueado. Contacte al administrador.}
{212}{}{Acceso concedido. Cuidado: La torreta de seguridad protegerá la plataforma contra los objetivos hostiles. ¿Le gustaría activar la torreta?}
{213}{}{Sí.}
{214}{}{No.}
{215}{}{Torreta activada.}
{216}{}{Vale.}
{217}{}{Desactivar torreta.}
{218}{}{Torreta desactivada}
{219}{}{Encender la iluminación del piso.}
{220}{}{Iluminación encendida.}
{221}{}{Enciende las luces de aterrizaje de la plataforma.}
