{100}{}{Ves una computadora.}
{101}{}{Ves una computadora con acceso a la red pública de la plataforma.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Regresar al menú principal}

{210}{}{Aviso general.}
{211}{}{¡Atención a todo el personal! La dirección de la compañía ha decidido modernizar las plataformas y ahora serán automatizadas por completo. Sólo unos pocos se quedaran a bordo para monitorear los sistemas, mientras que el resto serán despedidos. Es una medida esencial para mejorar la eficiencia, reducir gastos, y defendernos mejor ante el espionaje industrial.}
{212}{}{Lamentamos cualquier inconveniente causado por la reducción de plantilla y ofrecerá compensación de acuerdo con sus contratos de trabajo. La transición entre la mano de obra humana y el sistema automatizado se implementará de forma gradual entre los siguientes tres meses.}
{213}{}{Además, les avisamos que en este periodo habrá un nuevo protocolo de seguridad. Se le entregará una identificación a todos los empleados para evitar accidentes.}
{214}{}{Lista de plataformas petrolíferas en el Mar de Cortés.}
{215}{}{(Encuentras una lista con cada plataforma. Casi todas están cerradas, parece que el petróleo estaba a punto de acabarse antes de que empezara la Gran Guerra. En el horizonte, puedes ver un montón de plataformas oxidadas.)}
