{100}{}{Ves a Ruiz.}
{101}{}{Ves a Ruiz. Lleva un pañuelo y una capa ligera.}
{102}{}{Cava.}
{103}{}{No pongas a prueba mi paciencia.}
{104}{}{Si encuentro otro mapa del tesoro, hablaré contigo.}
{105}{}{¿Cómo están, amigos?}
{106}{}{¿Cómo estás, amigo?}
{1106}{}{¿Cómo estás, amiga?}

{200}{}{Vaya, vaya, ¿qué tenemos por aquí?}
{201}{}{Esto no te pertenece. Lárgate.}
{202}{}{Piénsatelo bien, pendejo. Nadie vendrá a ayudarte. Además, yo encontré el tesoro, me pertenece. ¿Serías tan amable de hacerte a un lado e IRTE A LA MIERDA?}
{1202}{}{Piénsatelo bien, vieja. Nadie vendrá a ayudarte. Además, yo encontré el tesoro, me pertenece. ¿Serías tan amable ser una niña buena e IRTE A LA MIERDA?}
{203}{}{Oblígame, enano gonorriento.}
{204}{}{Ah, claro. Es tuyo, después de todo.}
{205}{}{Piénsatelo bien, gringo. Nadie vendrá a ayudarte. Además, yo encontré el tesoro, me pertenece. ¿Serías tan amable de hacerte a un lado e IRTE A LA MIERDA?}
{1205}{}{Señorita, piénselo bien. Nadie vendrá a ayudarte. Además, yo encontré el tesoro, me pertenece. ¿Serías tan amable ser una niña buena e IRTE A LA MIERDA?}
{206}{}{Ah, claro, es todo tuyo.}
{207}{}{¿Eso era todo? No es casi nada. Qué viejo más tacaño, pensé que habría más. Ojalá pudiera llevarme todo, pero tengo que compartir el tesoro. Elige lo que quieras.}
{208}{}{Los 50 dólares de la preguerra.}
{209}{}{El revólver de combate.}
{210}{}{Las 3 dosis de Rad-X.}
{211}{}{Me quedaré con todo. ¡Aléjate de mis cosas!}
{212}{}{¿Y si mejor te mato? Con tu reputación, hasta podrían tirarnos flores.}
{213}{}{¡Estás muerto!}
{214}{}{No puedo quitarme la sensación de que perdimos dinero. Nos vemos.}
{215}{}{Adiós.}
