{100}{}{Ves a un pescador.}
{101}{}{Ves a uno de los aldeanos en su rutina diaria.}

{110}{}{Hola.}

{200}{}{Hola, joven. ¿Te ayudo en algo?}
{1200}{}{Mis respetos, señorita. ¿La ayudo en algo?}
{201}{}{Creo que nada.}
{202}{}{¡Tremendo incendio! ¡El cielo estaba negro por el humo!}
{203}{}{Sí, fue impresionante.}

{210}{}{Sólo me preguntaba qué estás haciendo.}
{211}{}{Me relajo mientras disfruto del mar. Tal vez debería revisar las redes.}
{212}{}{Me relajo mientras disfruto del mar. Podría ir a buscar moluscos.}
{213}{}{Me relajo mientras disfruto del mar. Quizás podría ir por un trago.}
{214}{}{Me parece una buena idea. Adiós.}

{220}{}{Estoy intentando hacer que funcione esta belleza. Pero sí que necesita mucho mantenimiento.}
{221}{}{¿Qué le pasa al bote?}
{222}{}{Tiene agujeros, grietas, óxido... Y no hay nada con qué cargar la batería. Hay que dedicarle mucho esfuerzo, además, sin botes el pueblo entero se quedará sin trabajo. Así que necesito hacer que funcione de nuevo.}
{223}{}{Déjame verla, quizás pueda ayudar...}
{224}{}{Ya veo. ¿Te puedo preguntar algo?}

{230}{}{Tengo unas preguntas que hacerte.}
{231}{}{Claro, ¿qué pasa?}
{232}{}{¿En dónde están los demás botes?}
{233}{}{Ahora mismo, la tenemos difícil. Tenemos un sólo bote que sale a pescar. Hay un par más, pero no llegan lejos. Ya perdimos tres; uno nunca volvió de la plataforma, el otro se dio vuelta y se hundió durante una tormenta, y dicen que el tercero fue arrastrado al fondo del mar por un monstruo marino. Aunque dudo de la última.}
{234}{}{¿Cómo obtienen el combustible de los botes?}
{235}{}{Recibimos algunas de Puerto Peñasco. Y si no tenemos, hay que remar con las manos.}
{236}{}{¿Qué sabes de la plataforma petrolífera?}
{237}{}{Es terrorífica. Primero, aparecieron unas... criaturas mutantes. Y ahora está soltando un veneno negro en el mar. Sería genial deshacerse de ella, pero, ¿cómo?}
{238}{}{Sí, eso está bien.}
{239}{}{Gracias por la charla, nos vemos.}
{240}{}{Háblame del capitán.}
{241}{}{¿Qué clase de... criaturas?}
{242}{}{Son unas criaturas asquerosas que flotan... les dicen "nómadas". Hicieron un nido en la plataforma petrolífera y atacan a cualquier pescador que se les acerque. Apenas conseguimos escaparnos de ellos cuando fuimos a revisar. Tuvimos suerte, parece que son menos activos durante el día.}
