{100}{}{Ves a Chatto.}
{101}{}{Estás viendo a un joven de mirada preocupada.}
{102}{}{Vaya, ¿es esto una de esas cosas que hacen en la Ciudad? ¡Por el Brahmán!}
{103}{}{¡El viejo está mal de la cabeza!}
{104}{}{Voy a cambiar. Prometo que protegeré a mi tribu de los forasteros de Fénix hasta el final.}

{200}{}{Agh, Mangas finalmente me dejó tranquilo. Esto debe parecerte una locura, pero no pienses que todos somos así. Ese viejo simplemente está mal de la cabeza.}
{201}{}{¿Quién eres?}
{202}{}{Soy un guerrero de la tribu, mi nombre es Chatto.}
{203}{}{Oye, Chatto. ¿Por qué ese viejo está tan enfadado contigo?}
{204}{}{Mangas ha decidido que él, como uno de los ancianos, puede decirle a todos qué está mal y qué está bien. ¿Por qué no puedo decidir eso yo mismo? ¡Yo también seré uno de los futuros líderes!}
{205}{}{¿Futuro líder? ¿Pues cuál es el verdadero?}
{206}{}{Es mi padre, su nombre es Jerónimo, es el Gran Jefe de la tribu. Puede que ya hayas oído de él, es una leyenda. Fue quien reunió a las tribus y fundó San Brahmán, pero a veces, los demás líderes sienten celos por él ya que no fueron los primeros hacer eso.}
{1206}{}{Es mi padre, su nombre es Jerónimo, es el Gran Jefe de la tribu. Puede que ya hayas oído de él, es una leyenda. Fue quien reunió a las tribus y fundó San Brahmán, pero a veces, los demás líderes sienten celos por él ya que no fueron los primeros en hacer eso.}
{207}{}{¿Y qué harás una vez que te hagas el jefe de la tribu?}
{208}{}{¡Al Brahmán Oscuro con las tradiciones y estas guerras interminables! Debemos hacer las paces con Fénix - por nuestra seguridad y nuestro futuro. Hacer esto podría presentarnos muchas oportunidades. Ten en cuenta las armas de los forasteros, las herramientas que podrían ayudarnos a trabajar, incluso la comunicación por radio nos vendría bien...}
{209}{}{Sigue...}
{210}{}{¿Qué nos ofrecen los rangers? Lo único que harían es protegernos de los saqueadores y de animales salvajes. Hay muchos jóvenes que me apoyan, estamos cansados de los ancianos y sus mismas palabras de siempre. Ellos fueron los que nos metieron en una guerra. Es hora de que la tribu cambie.}
{211}{}{Eres muy ambicioso para ser tan joven. Ojalá que entiendas lo que estás haciendo. Nos vemos.}

{220}{}{Hola, viajero. ¿Mi tribu te ha tratado bien? Si alguien te llega a molestar, dímelo.}
{1220}{}{Hola, viajera. ¿Mi tribu te ha tratado bien? Si alguien te llega a molestar, dímelo.}
{221}{}{Hola, viajero.}
{1221}{}{Hola, viajera.}
{222}{}{Estoy bien, sólo quería saludarte. Nos vemos.}
{223}{}{Estás haciendo lo correcto. Adiós.}
{224}{}{En mi opinión, eso es muy suave, pero es decisión tuya.}
{225}{}{Los rebeldes han capturado la Catedral en Fénix y Aaron ha muerto. Ahora nada se opone a los Rangers.}

{230}{}{Chatto, ¿no crees que es tu momento de tomar el control de la tribu?}
{231}{}{He estado pensando en esto durante mucho tiempo. Los viejos no dejan dar mi voz durante los consejos. Creen que los jóvenes deben luchar y seguir ciegamente las palabras de sus mayores.}
{232}{}{Pero tú no estás de acuerdo con ellos, ¿verdad?}
{233}{}{¡Ellos no lo entienden! La vida en Fénix ya no es tan enferma y débil como solía ser. Hemos perdido nuestra grandeza, mientras ellos ganaron la suya. Ahora los citadinos tienen armas y tecnologías poderosas.}
{234}{}{A este ritmo, Fénix acabará con la tribu.}
{235}{}{¡Así es! La única forma en que podremos sobrevivir es aliarnos con Fénix para poder superar a su gente. Nosotros también podríamos obtener armas y esas tecnologías.}
{236}{}{Exacto. Entonces, ¿qué estás esperando?}
{237}{}{Los ancianos no quieren cambiar sus costumbres. Solo saben que la tecnología es malvada, y solo saben vivir según los caprichos de la naturaleza.}
{238}{}{Oh, ya veo. Bueno, entonces no tengo nada más que decir. Adiós.}
{239}{}{Necesitas hacerles entrar en razón, Chatto.}
{240}{}{Pero, ¿qué puedo hacer? Mientras mi padre esté vivo, los ancianos no me permitirán decir lo que pienso durante los consejos.}
{241}{}{Bueno, eso te deja con pocas opciones. Buena suerte.}
{242}{}{Será demasiado tarde una vez que llegues al poder. Elimina a tu padre, Chatto.}
{243}{}{¿Cómo? ¿Matar a mi padre? ¡Por el Brahmán Oscuro! No haré eso.}
{244}{}{Lo siento. Olvida que dije eso.}
{245}{}{Está bien, entonces lo haré yo. Alguien necesita demostrarte lo que es la firmeza.}
{246}{}{Espera... Sus aposentos están dentro del Santuario, ¿planeas cometer un acto de violencia allí? No, después de tal suceso, yo jamás podría ocupar su lugar.}
{247}{}{¿Se te ocurre algo mejor? ¿Qué tal si usamos veneno?}
{248}{}{El veneno de los escorpiones no funcionará... La tribu entera se acostumbra a este veneno desde su juventud. Pero, si alguien es tratado con una droga de la preguerra, suele llevar a un final trágico. Por lo tanto, somos débiles en contra de los medicamentos antiguos.}
{249}{}{Quizás pueda conseguir drogas de la preguerra en Fénix. Adiós, Chatto.}
{250}{}{Te estás arriesgando a perder esta oportunidad, debes tomar el puesto de tu padre en el consejo. Ya sabes lo que debes hacer, Chatto.}
{251}{}{¿Quieres que... mate a mi padre...? Estás diciendo lo impensable...}
{252}{}{Lo siento, olvida lo que dije.}
{253}{}{Hazlo por el futuro de tu tribu. Tu padre y el resto de los ancianos están llevando a la tribu hacia el abismo.}
{254}{}{(Mira sus manos mientras reflexiona sobre tus palabras por un largo tiempo, tiempo después y sin decir nada, levanta la cabeza y se dirige al Santuario.)}
{255}{}{No te preocupes, Chatto. Tú y yo nunca tuvimos esta conversación.}
{256}{}{Fénix está llevando la esclavitud hacia cada rincón del sur de Arizona. La Villa es una de sus víctimas.}
{257}{}{Fénix ha trabajado junto a los Hojalateros, ellos utilizan esclavos de varias tribus. No puedes confiar en ninguno de ellos.}
{258}{}{Queda una persona que interfiere contigo y la tribu, ¿qué harás con el ranger?}
{259}{}{Debo expulsarlo del pueblo, pero podrá irse de aquí en paz.}

{260}{}{¿Qué está ocurriendo? Vi que los chamanes estaban corriendo hacia el santuario...}
{261}{}{Tu padre ha... fallecido. Es tu turno de liderar la tribu. Ya sabes qué hacer.}
{262}{}{¿Él... ha muerto? Pero... necesito tiempo para pensar esto.}
{263}{}{Claro. Piensa bien qué hacer a continuación.}
{264}{}{Si te apresuras, podrás tomar el poder en la tribu. Esta es tu oportunidad de aliarte con Fénix, justo como querías.}
{265}{}{¡Tienes razón! Esta es mi oportunidad. Y no dejaré que esos viejos tontos lo arruinen todo de nuevo. (corre hacia el santuario)}
{266}{}{¡Ve, Chatto!}
{267}{}{Quizás hayas oído acerca de la explosión que hubo en Fénix. ¿Esos son los aliados que quieres?}
{268}{}{Entonces te interesará saber lo que ocurrió en Quartz, escúchame bien...}
{269}{}{La colonia de Flagstaff utiliza a los esclavos en trabajos forzados. Todo lo que hacen es dictado por Fénix.}

{270}{}{Ahora guiaré a la tribu por un camino distinto, los ancianos ya no podrán detenerme.}
{271}{}{Creo que sabes lo que debes hacer. Adiós.}
{272}{}{Entonces, ¿estás listo para aliarte con los misionarios de Fénix?}
{273}{}{Eso es justo lo que haré. Dile al Comandante Crook que estoy listo para fumar la pipa de la paz junto a él... O, a sentarnos a negociar. Creo que así le dicen en la ciudad, ¿no?}
{274}{}{Te deseo suerte a ti y a tu pueblo, Jefe.}
{275}{}{De acuerdo, adiós.}
{276}{}{Por cierto, sería bueno reabrir la ruta de caravanas a Ciudad Garaje. ¿Qué opinas?}
{277}{}{Esa colonia es de Fénix, ¿no es así? Está al norte y creo que venden objetos viejos de las ruinas. Sí, creo que la tribu podría aprovechar eso y conseguir cosas nuevas. Háblale a Ronnie acerca de esto.}

{278}{}{¿Sabes leer, no? Quiero que leas el diario del comandante de los misionarios. Pude robárselo de su campamento.}
{279}{}{¿...Qué? ¿Qué ha escrito? ¿Qué significa? Feos y sucios salvajes... quiere expulsarnos a una reserva... quiere civilizarnos a base de látigo... ¿Este es el plan que le propone a su líder? Maldita sea, es como si el mismísimo Brahmán Oscuro haya venido a nublar mi mente.}
{280}{}{Chatto, los ancianos y los rangers no están contentos contigo y tu gente.}
{281}{}{Lo sé. Si no, no tendría que luchar esta batalla. Los ancianos están equivocados, la tribu DEBE cambiar. El mundo ha cambiado. La tribu no sobrevivirá si no cambiamos.}
{282}{}{Claro, no estoy en desacuerdo.}
{283}{}{Quizás simplemente no están listos para cambiar.}
{284}{}{¿Y cuándo llegará ese día? ¿Cuándo se irán los viejos a los Pastos Celestiales? Para ese entonces, el Imperio de Fénix nos habrá aplastado con sus armas y tecnología.}
{285}{}{¿Qué hace falta para que abras los ojos sobre esto?}
{286}{}{Demuéstrame que los Rangers son la mejor opción. ¿Quizás ya han demostrado su valor en el yermo? O dime qué mal nos traería aliarse con Fénix. ¿Tienes ejemplos que me hagan cambiar de opinión? Puede que los misionarios tengan planes malvados para San Brahmán, pero hasta que no sepa la verdad, no cambiaré de idea.}
{287}{}{Está bien. Voy a investigar eso.}
{288}{}{Te estás adelantando a todos, Chatto. Eres igual que un brahmán que se separa de la manada. No sabes a dónde estás yendo.}
{289}{}{No lo creo...}
{290}{}{Un brahmán es un animal de manada. Es su única forma de protegerse de los peligros. El brahmán solitario está condenado a morir.}
{291}{}{(suspiro) Entonces, ¿qué debería hacer? Por favor, muéstrame tu sabiduría, porque tú y yo nos parecemos, viajero. ¿Debería quedarme en el campamento y proteger sus viejas tradiciones? ¿O debería seguir luchando contra unos ancianos tontos que viven en el pasado?}
{1291}{}{(suspiro) Entonces, ¿qué debería hacer? Por favor, muéstrame tu sabiduría, porque tú y yo nos parecemos, viajera. ¿Debería quedarme en el campamento y proteger sus viejas tradiciones? ¿O debería seguir luchando contra unos ancianos tontos que viven en el pasado?}
{292}{}{No lo sé, Chatto. Yo también me hago esa pregunta. Dejemos esto por ahora, ¿de acuerdo?}
{293}{}{Has un voto por una alianza con los Rangers. Tú y tus compañeros deben regresar a la tribu.}
{294}{}{Quizás tengas razón. Ya no lo sé... Está bien, hablaré con los demás e intentaré calmarlos.}
{1294}{}{Quizás tengas razón. Ya no lo sé... Está bien, hablaré con los demás e intentaré calmarlos.}
{295}{}{Ve, Chatto.}
{296}{}{Tuve la oportunidad de visitar Flagstaff. Allí había una tribu, justo como la tuya, pero Fénix la exterminó y robó sus terrenos para crear una colonia.}
{297}{}{¿Dices la verdad? ¿Por el bien de su colonia, Fénix destruyó una tribu entera? (niega con la cabeza) Hmm... Debo tener ojos sólo para ver lo que quiero ver. Durante una guerra, todos buscan el beneficio propio.}
{298}{}{¿Ya no te interesa tanto la alianza con Fénix, verdad?}
{299}{}{La verdad es que no tengo la historia del todo clara. No importa.}
{300}{}{Si tienes dudas, vamos a lanzar una moneda. Que el Espíritu del Yermo decida por ti.}
{301}{}{No voy a dejar que la suerte decida esto.}
{302}{}{Como tú desees.}
{303}{}{De acuerdo, vamos a lanzar una moneda... ¿Qué es esto? La moneda está del lado de los Rangers.}
{304}{}{De acuerdo, vamos a lanzar una moneda... ¿Qué es esto? La moneda está del lado de Fénix.}
{305}{}{La verdad es que no deberíamos dejarle algo tan importante a la suerte. Olvídalo.}
{306}{}{Vamos a lanzar una moneda, que el Espíritu del Yermo decida por ti.}
