{101}{}{Ves a un niño con cabello negro y largo.}

{110}{}{Sólo eres un forastero.}
{111}{}{¿Me contarías de tu tribu?}
{112}{}{¿Tu tribu es grande como la nuestra?}
{113}{}{Cuéntame una historia.}
{114}{}{Los chamanes dicen que eres una buena persona.}

{120}{}{¡Fuera del pueblo, eres malo!}
{121}{}{Tu tribu es débil.}
{122}{}{¿Tu tribu es igual de mierda que tú?}
{123}{}{Dile eso a los citadinos de al lado.}
{124}{}{Los chamanes dicen que hay un espíritu malvado dentro tuyo.}

{130}{}{¿De qué tribu eres?}
{131}{}{Nuestra tribu es mejor que tu tribu.}
{132}{}{¿Qué le pasó a tu tribu?}
{133}{}{Cuéntame una historia de las otras tierras.}
{134}{}{Los chamanes dicen que no se te puede escuchar.}
