{101}{}{Ves a un niño de la tribu, está cubierto de tierra.}

{200}{}{¿Quién es? ¿Humano? ¡Humano! ¡Ayuda, salvarnos, ayuda!}
{201}{}{Tus mayores te prohibieron entrar aquí, ¿verdad?}
{202}{}{¿Cómo acabaste aquí abajo?}
{203}{}{Nosotros explorar catacumbas cuando oír rugido grande, y techo caerse. No ver salida.}
{204}{}{¿Rugido?}
{205}{}{¡Shh! ¡Espíritu malo! ¡Ser grande, ser de miedo! No salir por él. ¡Tú ayudarnos! ¡Por favor!}
{206}{}{Está bien, vayámonos de aquí.}
{207}{}{Primero, tenemos que salir de aquí. Y luego conocerás a la poderosa chancla.}

{210}{}{¡Tú ser malo! ¡Persona mala! ¡Monstruo comerte!}
{211}{}{Cállate la boca...}

{220}{}{Nosotros no morir, ¿cierto?}
{221}{}{¿Moriremos? ¿Moriremos?}
{222}{}{¡Tú protegernos de espíritu malo!}
{223}{}{Sígueme. ¡No te alejes!}
{224}{}{Quédate aquí y no te muevas. Iré a echar un ojo.}

{230}{}{¡Hurra! ¡Ser libres! ¡Estar salvados!}
{231}{}{Ya están a salvo.}
{232}{}{¡Tú ser salvador! Brahmán Divino enviarte a nosotros. ¿Quién pensar que desconocido salvarnos? Tu tribu debe ser buena. Toma cosas, nosotros encontrar abajo. (te entrega balas de 10mm, cartuchos de escopeta, una granada y un encendedor) ¡Gloria a salvador!}
{1232}{}{¡Tú ser salvadora! Brahmán Divino enviarte a nosotros. ¿Quién pensar que desconocida salvarnos? Tu tribu debe ser buena. Toma cosas, nosotros encontrar abajo. (te entrega balas de 10mm, cartuchos de escopeta, una granada y un encendedor) ¡Gloria a salvadora!}
{233}{}{No pierdan el tiempo, vuelvan al pueblo de inmediato.}
