{100}{}{Ves a un guerrero tribal.}
{101}{}{Ves a un hombre de tez oscura con pinturas de guerra sobre todo su cuerpo.}

{120}{}{Yo peleo por mi tribu. ¿Y tú?}
{121}{}{Si me muero, terminaré en las Grandes Pastos Celestiales.}
{122}{}{El Brahmán Divino me protege en la batalla.}
{123}{}{Podemos ganar si luchamos juntos.}
{124}{}{¿De qué lado estás?}
{125}{}{La tribu recuerda nuestras victorias.}
{126}{}{Defenderé el pueblo de los saqueadores hasta mi último aliento.}
{127}{}{Que mis enemigos tiemblen ante mi escudo.}
{128}{}{Este está hecho del hueso de brahmán sagrado, me protege.}
{129}{}{El chamán me dijo que encantó mis amuletos.}
