{100}{}{Ves al anciano Genaro.}
{101}{}{Estás viendo a un chamán vestido con un atuendo tradicional.}
{102}{}{Ve en paz, extraño espíritu de hierro.}

{200}{}{Te saludo a ti y a tu tribu. ¿Eres tú de quien toda San Brahmán está hablando? No sé qué trato darte, pero tu presencia no me molesta.}
{201}{}{¿En serio? Para ser un salvaje, confías mucho.}
{202}{}{Genial. A diferencia de los demás de tu tribu, hablas distinto.}
{203}{}{Suelo tratar con los forasteros del este, a diferencia de los demás clanes de la tribu. El tiempo dirá si se puede confiar en ti.}
{204}{}{De acuerdo. Gracias por tu hospitalidad.}
{205}{}{Hmph. Esto no es una bienvenida muy cálida.}

{210}{}{¡Esa cosa que estás montando ha asustado a todos mis brahmanes! Para la siguiente vez, elije otra ruta, idiota.}
{1210}{}{¡Esa cosa que estás montando ha asustado a todos mis brahmanes! Para la siguiente vez, elije otra ruta, mujer.}
{211}{}{Perdona, no quería asustarlos.}
{1211}{}{Perdona, no quería asustarlos.}
{212}{}{Eso no es problema mío. No es mi culpa que tus brahmanes sean tan miedosos.}

{220}{}{Veo que no planeas irte pronto de nuestro pueblo. ¿Qué te trae por aquí, amigo?}
{221}{}{Veo que no planeas irte pronto de nuestro pueblo. ¿Qué tienes en mente?}
{222}{}{Te salido, amigo de la tribu. ¿En qué puedo ayudarte?}
{223}{}{Adiós, Genaro.}

{230}{}{Quiero que apoyes una alianza con los misionarios de Fénix.}
{231}{}{A diferencia de los demás ancianos, no le deseo mal a los forasteros de Fénix. Mi clan ha pasado mucho tiempo junto a ellos al comerciar juntos. Pero no estoy listo para llevar la contraria al resto de la tribu. Quizás no sea el momento adecuado.}
{232}{}{Si no podemos convencer a los ancianos, habrá una guerra.}
{233}{}{Estás subestimando a la tribu. Nuestros guerreros han librado muchas batallas a través del Yermo Sonorense. El ejército de Fénix tendría que estar en guerra durante años, si es que tienen la valentía de atacarnos.}
{234}{}{Tienes razón. Olvida lo que dije.}
{1234}{}{Tienes razón. Olvida lo que dije.}
{235}{}{Estás condenando a tu tribu a la guerra. Recuerda mis palabras.}
{236}{}{Quizás sea tu voz la que necesitamos para cambiar las cosas. No quieres una guerra contra Fénix, ¿cierto?}
{237}{}{La tribu es capaz de defenderse, pero esta guerra jamás tendría fin. Y algún día terminará en la derrota, pues los misionarios adquieren más y más tecnología.}
{238}{}{¿Entonces estás de acuerdo?}
{239}{}{En lo personal, no estoy en contra de comerciar con Fénix. El mundo ha cambiado y los demás ancianos no entienden eso. Es mejor entrar a esta nueva era con todas nuestras fuerzas que condenar a nuestra gente a una guerra sin fin. Durante el Consejo de Ancianos, podrás contar con mi apoyo.}
{240}{}{Estás tomando la decisión correcta, Genaro.}
{241}{}{Bueno, entiendo lo que quieres decir...}
{242}{}{Fuiste el que salvó a los niños y al rebaño al expulsar a ese espíritu malvado. ¿Cómo podría decirte que no, después de haber hecho eso?}
{1242}{}{Fuiste la que salvó a los niños y al rebaño al expulsar a ese espíritu malvado. ¿Cómo podría decirte que no, después de haber hecho eso?}
{243}{}{Entonces, ¿puedo confiar en ti?}
{244}{}{Quizás el Brahmán Divino me haya castigado, le ha quitado la vida a nuestros brahmanes sagrados justo antes de la celebración del Día del Sol. Esto es una señal. Me indica que tomé el camino equivocado.}
{245}{}{Ahora sabes lo que debes hacer, ¿no es así?}
{246}{}{Genial, pero no apresuremos las cosas. Hasta luego.}
{247}{}{Esto es muy... triste. Pero no apresuremos las cosas, ¿bien?}

{250}{}{Háblame de ti.}
{251}{}{Soy el anciano de los clanes occidentales de nuestra tribu. Y mi nombre es Genaro.}
{252}{}{Hola, Genaro.}
{253}{}{¿Quién está a cargo de los demás?}
{254}{}{Jerónimo es el Gran Jefe de nuestra tribu. Es un guerrero sabio y experimentado, es el gran unificador de la tribu. Lo encontrarás en el edificio grande, el que tiene columnas.}
{255}{}{¿Qué estás haciendo aquí?}
{256}{}{Paso mucho tiempo en San Brahmán. Debo atender a los brahmanes después de su pastoreo, debo prepararlos para su destino y finalmente, organizo las celebraciones para el Día del Sol. Y cada vez tengo más y más trabajo; apenas soporto el peso de mi labor.}
{257}{}{Entiendo.}
{258}{}{Quizás pueda ayudarte.}
{259}{}{Asumo que has trabajado recolectando maíz, así que trabajar la tierra no debería serte ningún problema. Lleva esta pala al corral y limpia el... excremento de brahmán. Mientras los brahmanes no estén libres, deben mantenerse limpios. Especialmente aquellos a los que he escogido para la celebración del Día del Sol.}
{260}{}{De acuerdo, lo haré. Ojalá que me des de comer carne fresca después de esto.}
{261}{}{¿Qué? ¿Limpiar el corral?}
{262}{}{¿No es esto un quehacer habitual para ti? Bueno, no tengo más trabajo que ofrecerte. Es poco probable que seas capaz de curar las pieles o cuidar a los brahmanes. Para ser sincero, intento que los forasteros nunca entren al corral. Es una pena que no aprecies la confianza que te estoy demostrando.}
{263}{}{Creo que te estás burlando de mí.}
{264}{}{He limpiado el corral.}
{265}{}{Ya veo. Lo has hecho bien.}
{1265}{}{Ya veo. Lo has hecho bien.}
{266}{}{¿Lo dices en serio? ¡El corral está limpio, pero yo estoy hasta el cuello de mierda!}
{267}{}{Ah, gracias. Me encanta hacer un trabajo bien hecho.}
{268}{}{Por este trabajo, no será un problema ofrecerte comida, además de un lugar en el que dormir dentro de mi tienda. Llévate esta cecina. Dejará a tu estómago satisfecho y se conserva bien durante un largo tiempo.}
{269}{}{Gracias.}
{270}{}{Más te vale que no te rías a mis espaldas.}

{280}{}{Habíamos oído rumores en la Villa, sobre una tribu que tiene de rebaño a animales de dos cabezas.}
{281}{}{¿Hmm?}
{282}{}{Esas historias nos confundían mucho. ¿Cómo consiguieron domesticar a los brahmanes salvajes?}
{283}{}{Ah, olvídalo.}
{284}{}{No siempre fueron así. Hace muchas generaciones, los brahmanes eran animales domésticos. Las leyendas cuentan que los Cielos castigaron a la gente por sus ofensas, al hacer que los animales fueran salvajes.}
{285}{}{Te escucho, Genaro.}
{286}{}{Los brahmanes rondaron por el desierto, se negaron a volver a los corrales y se escondían de la gente. Su temperamento se volvió uno salvaje. Pero nuestros ancestros domesticaron a unos brahmanes a través de oraciones y ofrendas al Brahmán Divino.}
{287}{}{Gracias por contarme esta historia.}
{288}{}{¿Por qué un brahmán necesita una segunda cabeza?}
{289}{}{(se encoge de hombros, sorprendido) El Brahmán Divino obra de maneras misteriosas. Pero pienso que dos brahmanes se unieron en un sólo cuerpo, para protegerse mejor de las personas y de las bestias.}
{290}{}{Eso tiene sentido, dos cabezas son mejores que una.}
{291}{}{Le buscas una explicación divina a una deformidad. Eso no es nada bueno...}

{300}{}{¿Puedo comprarles un brahmán?}
{301}{}{Guárdate tus ridículas chapas. Debido a la guerra, hemos parado el comercio de brahmanes, igual que el de carnes y pieles.}
{302}{}{Vaya, eso es una pena. ¿Podemos hablar de otra cosa?}
{303}{}{La guerra se acabó y el comercio se ha reanudado. ¿Buscas comprar un brahmán entero? Eso te costará mucho.}
{304}{}{Sí, necesito un brahmán vivo y entero.}
{305}{}{Sólo tenemos tres brahmanes a la venta dentro del corral - Brisa, Río y Sierra. Pero primero, muéstrame que tienes para intercambiar. Luego, llévale esta fruta y dásela al brahmán que gustes llevarte.}
{306}{}{Gracias, Genaro.}

{310}{}{¿Puedes contarme qué es esa Ciudad Enterrada de la que hablan los demás?}
{311}{}{No entres ahí por tu cuenta. El lugar está plagado de espíritus malvados. A veces se encuentran huesos de animales allí, ocasionalmente incluso restos humanos. Los espíritus no pueden revelarme el secreto de este lugar.}
{312}{}{¿Es por eso que le prohíbes a los niños que entren ahí?}
{313}{}{Sí. ¿Quién sabe que antigua maldad está merodeando en las oscuras y moribundas catacumbas del viejo pueblo?}
{314}{}{Comprendo. Gracias por la explicación.}
{315}{}{Ahí viene nuestro héroe. Los niños me lo confesaron y me hicieron saber de tus hazañas en la Ciudad Enterrada. ¿Qué encontraste ahí?}
{1315}{}{Ahí viene nuestra heroína. Los niños me lo confesaron y me hicieron saber de tus hazañas en la Ciudad Enterrada. ¿Qué encontraste ahí?}
{316}{}{Encontré a un monstruo. Estaba acechando tanto a brahmanes como a personas.}
{317}{}{¡Un monstruo! Desde hace tiempo que hemos intentado descubrir quién estaba robando nuestro rebaño, pero ese espíritu malvado fue habilidoso y eludió mi vista de águila. Y todavía está ahí, acechándonos.}
{318}{}{He... 'exorcizado' al espíritu. Ya no será un problema.}
{319}{}{¡Alabados sean los cielos! El mismísimo Brahmán Divino tuvo que haberte enviado con nosotros. Gracias, puedo verte como una amistad. Recordaremos tus hazañas por generaciones.}
{320}{}{Ya me lo imagino, los niños alrededor de una fogata y un anciano hablándoles de mí... Pero debo irme. Todavía quedan muchas vidas que salvar.}
