{100}{}{Ves a Ronnie.}
{101}{}{Estás viendo a un curtidor. Limpia un pedazo de cuero de manera profesional.}
{102}{}{Escúchame, espíritu de hierro, nuestro pueblo es pacífico, déjalo en paz.}

{200}{}{Saludos, forastero. Ojalá que hayas venido aquí con buenas intenciones.}
{1200}{}{Saludos, forastero. Ojalá que hayas venido aquí con buenas intenciones.}
{201}{}{Claro, pero, ¿quién eres? ¿Y qué es este lugar?}
{202}{}{Sí, sólo quería hablar contigo.}
{203}{}{Soy Ronnie y este es mi curtiduría.}
{204}{}{Parece que te asentaste muy bien aquí, Ronnie.}
{205}{}{Así es, solía viajar por el desierto de Sonora y era un pastor de brahmanes como los demás. Ahora me quedo aquí y preparo el cuero para los demás miembros de la tribu y para comerciarlo.}
{206}{}{Suena a que es un trabajo importante.}
{207}{}{Debe ser un negocio rentable.}
{208}{}{Comprendo. Ahora mismo yo no necesito nada de cuero. Adiós.}

{210}{}{¿Cómo puedo ayudarte?}
{211}{}{Nos vemos luego.}
{212}{}{Ah, puedo reconocer mi trabajo cuando lo veo. Yo marco toda la armadura que fabrico con un 'símbolo' especial.}
{213}{}{Bienvenido, Ranger. Ustedes son amigos de nuestra tribu. ¿En qué te ayudo?}
{214}{}{Ah, otro embajador de esa extraña religión. ¿Y ahora qué quiere tu iglesia de mi tribu?}

{220}{}{¿Por qué dejaron de comerciar con Ciudad Garaje?}
{221}{}{Los ancianos tomaron esa decisión. No les gusta que los forasteros le traigan la discordia a nuestras vidas, además de que nos engañan y roban nuestros brahmanes. Así que detuvimos las rutas comerciales con Fénix y todas sus colonias.}
{222}{}{¿Y eso aplica a Ciudad Garaje?}
{223}{}{Los sacerdotes saben lo que hacen, habla con ellos. No puedo comerciar con esa ciudad hasta que ellos estén de acuerdo.}
{224}{}{Comprendo, intentaré convencerlos..}
{225}{}{El Jefe Jerónimo ha decidido reanudar el comercio con Ciudad Garaje.}
{226}{}{El Jefe Chatto ha decidido reanudar el comercio con Ciudad Garaje.}
{227}{}{Todavía no hay ningún Gran Jefe, no te pierdas la oportunidad de vender tus productos.}
{228}{}{Espero que todo esto sea la voluntad del Brahmán Divino. Dile a los ciudadanos de Ciudad Garaje que envíen a alguien para hacer un trato.}
{229}{}{Suena bien.}

{230}{}{¿Podrías fabricarme unas bolsas de cuero para mi motocicleta?}
{231}{}{Claro, ese es mi oficio. Lo haré lo mejor que pueda y tu motocicleta se convertirá en una caravana. Pero esa labor me lleva tiempo y esfuerzo. ¿Qué puedes darme a cambio?}
{232}{}{Veamos...}
{233}{}{Mi taller está cerrado para los forasteros. Yo solo trabajo para la tribu y para los forasteros que se ganaron la confianza de los ancianos.}
{234}{}{¿Así que primero tendré que lidiar con todo lo que está pasando aquí?}
{235}{}{Hablaré con ellos más tarde.}

{240}{}{Quiero echarle un vistazo a tus bienes. ¿Puedo?}
{241}{}{No voy a comerciar con los forasteros hasta que la guerra se haya acabado. Esa es la decisión del Jefe Jerónimo.}
{242}{}{De acuerdo, me las arreglaré sin ti.}
{243}{}{La guerra ha acabado. Podemos comerciar, amigo mío.}
{244}{}{Puede que el jefe esté demasiado ocupado como para hablarme de eso. Bueno, esto es lo que tengo. ¿Quizás necesitas algo hecho a mano?}
{245}{}{Gracias, déjame ver.}
{246}{}{No seas así, somos vecinos, no desconocidos.}
{247}{}{Lo siento, pero no iré en contra del jefe.}
{248}{}{Ya veo.}
{249}{}{Los vecinos deberían vivir en paz. Tu tribu y mi Villa deberían comerciar entre sí.}
{250}{}{Estoy de acuerdo contigo. El Jefe Jerónimo solo mencionó a Fénix y sus colonias y eso no incluye a la Villa. Bueno, esto es lo que tengo. ¿Quizás necesitas algo hecho a mano?}
{251}{}{Gracias, déjame ver.}
{252}{}{Ronnie, ¿acaso no soy de confianza?}
{253}{}{Lo siento, no quería ofenderte con mis palabras. No eres parte de aquellos que engañaron y perjudicaron a nuestra tribu. Esto es lo que tengo. ¿Quizás necesitas algo hecho a mano?}
{254}{}{Gracias, déjame ver.}

{260}{}{Saludos, héroe. Toda nuestra tribu agradece tus hazañas. Te doy esta arma como muestra de mi gratitud. Los chamanes la dotaron del poder del Brahmán Divino.}
{1260}{}{Saludos, heroína. Toda nuestra tribu agradece tus hazañas. Te doy esta arma como muestra de mi gratitud. Los chamanes la dotaron del poder del Brahmán Divino.}
{261}{}{Hmm, es un arma interesante.}
{262}{}{Pero, su poder no es ilimitado. Su energía divina se acabará y tendrás que cambiar las... eh... ba-te-rí-as...}
{263}{}{Gracias, Ronnie.}

{270}{}{Gracias a tu ayuda, la guerra se ha acabado. Ahora San Brahmán reanudará las rutas comerciales hacia Fénix. Así que puedo abrirle las puertas de mi taller a todos.}
{271}{}{Gracias a tu ayuda, la guerra se ha acabado. San Brahmán ya no confía en el Imperio de Fénix y en sus colonias. Pero, seguiremos abiertos a nuestros amigos y los Rangers.}
{272}{}{[Más]}
{273}{}{Si necesitas productos de cuero, háblame.}
{274}{}{Lo tendré en cuenta.}

{280}{}{Hmm. Cerca de Ciudad Garaje, un bandido atacó a nuestros pastores. Y tú coincides con su descripción.}
{281}{}{No sé de qué estás hablando. No tuve nada que ver en eso.}
{282}{}{¡Ja! Incluso los niños que se han mojado los pantalones dicen que sus pies están secos. Vete.}
{283}{}{Está bien...}
{284}{}{Sí, pero fue un malentendido. Pensábamos que eran brahmanes salvajes.}
{285}{}{Deberías habértelo pensado antes de actuar. Tienes suerte de que los pastores no salieron heridos, porque o si no, el pueblo entero estaría enojado contigo. Pero es bueno que puedas admitir tus errores. Ahora sé que debo tener cuidado contigo.}
{286}{}{Eh, bueno...}
{287}{}{Voy a reflexionar sobre esto, eres sabio.}
{288}{}{Deberías darle esas lecciones a los niños babosos de tu tribu, imbécil.}

{290}{}{Mangas me ha pedido que destruya la producción de tequila en Fénix.}
{291}{}{¿Quién se cree que es? El chamán no puede privarnos de nuestras alegrías tan fácilmente, a nadie le gustará esto. Al menos Mangas no puede decidir por todos los clanes a la vez; no es un Gran Jefe.}
{292}{}{¿Así que estás en contra de su idea?}
{293}{}{Esto es asunto de todos, no sólo de los ancianos. No deberíamos hacer caso a los deseos de ese viejo amargado. Para mí, es mejor conseguir una caja del aguardiente de Fénix. Podría hallarle algún uso durante la celebración del Día del Sol.}
{294}{}{Pero, ¿cuál es el problema con conseguir más alcohol?}
{295}{}{¿No lo sabes? Debido a la guerra, detuvimos nuestro comercio con Fénix. Sabemos cómo hacer aguardiente casero a partir de los cactus, pero el aguardiente de verdad, el 'tequila' de la ciudad, es mucho mejor.}
{296}{}{¿Cuántas botellas necesitas?}
{297}{}{Hmm... diez botellas de aguard... tequila, y el mismo número de botellas de cerveza.}
{298}{}{De acuerdo, debo pensar en quién apoyaré en esta discusión.}
{299}{}{¿Podrías recordarme cuántas botellas de alcohol te hacen falta?}
{300}{}{Tengo la cantidad de alcohol exacta para ti.}
{301}{}{¡Que tu nombre sea alabado por el Brahmán Solar! Con estos suministros, nuestra festividad no será opacado por la guerra a nuestro alrededor, te lo agradezco. Si necesitas productos de cuero, recuérdame. Te haré lo que necesites por un precio más bajo.}
{302}{}{Lo tendré en cuenta. Adiós, Ronnie.}

{310}{}{¿Qué estás vendiendo? }
{311}{}{Puedo fabricar muchas cosas, a partir del cuero de brahmán. Pero en su mayoría, estos artículos son usados por mi tribu. Ya no hago negocios con Fénix y sus colonias, pero los Rangers tienen permitido encargarme cosas.}
{312}{}{Ya veo.}
{313}{}{¿Qué objetos fabricas?}
{314}{}{Ropa, cinturones, bolsos y otras cosas. También hago armaduras para los Rangers.}
{315}{}{¿Qué problema tienen con Fénix?}
{316}{}{Por un tiempo, solíamos vivir en paz. Pero estos últimos años, los caras-pálidas de la gran ciudad han venido aquí con armas, para controlarnos o quitarnos lo que nos pertenece. La tribu no les aguantará esto.}
{317}{}{¿Así que tienen una buena relación con los Rangers?}
{318}{}{Nos ayudan a defendernos de los invasores de Fénix. Y siempre han sido buenos clientes para mi taller.}
{319}{}{¿A quién apoyas en esta disputa?}
{320}{}{Para mí, es difícil hablar con sabiduría. Hasta ahora los Rangers nos han tratado bien, pero pienso que quizás sus intenciones no son puras. También tienen sus propios intereses en este conflicto.}
{321}{}{[Más]}
{322}{}{Pero, por mucho tiempo, vivimos en paz junto a Fénix y comerciábamos con ellos, hasta que las cosas empeoraron. Si no tuviera a un tirano codicioso a cargo, Fénix nos daría más oportunidades.}
{323}{}{Ya veo.}
