{100}{}{Ves a un ranger.}
{101}{}{Ves a un ranger listo para la batalla. Está observando el pueblo.}

{110}{}{¿Así que es gracias a ti que nos aliamos a la tribu? Bien hecho.}
{111}{}{Estás haciendo un muy buen trabajo.}
{112}{}{El general nos mandó a proteger al jefe.}
{113}{}{¿Estás de nuestro lado, cierto?}
{114}{}{Nuestro líder te está esperando. Pasa.}
{115}{}{Puedes pasar.}
{116}{}{*Te da un saludo militar*}

{120}{}{No deberías haber venido aquí.}

