{100}{}{Ves a un cantinero.}
{101}{}{Ves a un cantinero sin nada fuera de lo común.}
{102}{}{Lo siento, pero no puedo dejar que te sientes con... esa cosa.}

{110}{}{¡Bienvenido seas! Ven, refréscate la garganta, se nota que has tenido un día largo.}
{111}{}{Hola, ¿qué quieres para beber?}
{112}{}{Pensé que vería a más gente por aquí, pero al menos estás tú.}
{113}{}{Aquí somos todos amigos, así que no tengas miedo de hablar, no mordemos.}
{114}{}{¡Un cliente! ¡Por fin! Ha sido un día muy tranquilo.}

{200}{}{¡Saludos, compadre! Gracias por venir.}
{1200}{}{Bienvenida, señorita. Gracias por venir.}
{201}{}{Pensé que el bar estaba abandonado.}
{202}{}{Sí, este lugar parecía un pueblo fantasma. Pero la ciudad está mejor que antes, así que me dije '¿Por qué no abrir el bar otra vez?'}
{203}{}{¿Y el alcalde no te dijo nada?}
{204}{}{Antes solía a sacar a la gente de acá, pero últimamente está más alegre. No sé qué le pasó, pero puse todo en orden antes de que cambiara de parecer.}
{205}{}{Entiendo. ¿Me sirves un trago?}

{210}{}{¡Por supuesto! Toma asiento. Mi selección no es amplia, pero te refrescará la garganta.}
{211}{}{Tengo que irme, nos vemos.}
