{100}{}{Ves a un saqueador.}
{101}{}{Ves a uno de los forajidos. Este tipo en particular tuvo que haber salido del infierno mismo.}

{110}{}{Si no nos pagan, alguien se va a morir, y habrá mucha sangre.}
{111}{}{No vinimos a hacer un pícnic.}
{112}{}{Dile a ese bastardo de Bustos que cuente las chapas si quiere a su hijita en una sola pieza.}
{113}{}{No quiero destripar a la niña, pero si me obligan, lo haré.}
{114}{}{¿Qué dijo Bustos? Dime o disparo.}
{115}{}{Se me está agotando la paciencia, y cuando eso pasa, la gente muere.}
{116}{}{Mis dedos desean volarle la cabeza a alguien.}
{117}{}{}
{118}{}{Síguenos y estarás agarrando tus dedos del suelo.}
{119}{}{Piérdete, o te mataré a ti primero.}
