{100}{}{Ves a un pueblerino.}
{101}{}{Ves a uno de los lugareños.}
{102}{}{ }

{110}{}{Z-z-z}
{111}{}{Hrrr}
{112}{}{. . .}

{120}{}{Esta es la segunda vez en la semana que los forajidos atacan una caravana.}
{121}{}{Esos forajidos no muestran piedad.}
{122}{}{Escuché que vieron a algunos forajidos por aquí.}
{123}{}{Los forajidos podrían apoderarse de la maldita ciudad si así lo quisieran.}
{124}{}{Hay menos caravanas, gracias a los malditos Escudos Azules.}

{125}{}{¿Cuánto tiempo durará esta alianza con los Escudos Azules?}
{126}{}{¿Somos amigos con los Escudos Azules? No puede ser.}
{127}{}{No me acercaré a los Escudos Azules después de lo que hicieron.}
{128}{}{¿Los Escudos Azules están comerciando? El mundo se volvió loco.}
{129}{}{No podemos confiar en los Escudos Azules, algún día nos traicionarán.}

{130}{}{Los Escudos Azules recibieron su merecido.}
{131}{}{Ben y su pandilla no eran tan duros, ¿cierto?}
{132}{}{La banda de Ben no será ningún problema por un tiempo.}
{133}{}{Ojalá que esto acabe con el problema de los forajidos.}
{134}{}{Ahora que los bandidos no son un problema, hay más caravanas.}

{135}{}{Si no hay Ben, no hay banda. Así de simple.}
{136}{}{Le dieron su merecido a Ben.}
{137}{}{Ben era un buen tipo, lo recuerdo.}
{138}{}{Sigo sin saber por qué Ben decidió ser un bandido.}
{139}{}{Ben ya no da tanto miedo, ahora es sólo un cadáver podrido.}

{140}{}{Esos Hojalateros me dan miedo.}
{141}{}{¿Quién haría equipo con una máquina?}
{142}{}{Los Hojalateros nos desprecian.}
{143}{}{Habrían menos caravanas sin los Hojalateros.}
{144}{}{Al menos la carretera es más segura con los Hojalateros.}

{145}{}{La ciudad se empobrecerá, hay menos comercio.}
{146}{}{Hay menos caravanas, ya no están los Hojalateros.}
{147}{}{No me agradaban los Hojalateros, pero eran útiles.}
{148}{}{Por fin, alguien acabó con Two-Sun.}
{149}{}{Two-Sun jamás se levantará otra vez, jamás.}

{150}{}{La Gran Ciudad atrae a la gente, igual que una polilla y una luz.}
{151}{}{Ojalá pudiera visitar Fénix.}
{152}{}{Últimamente he escuchado mucho de Fénix.}
{153}{}{Dicen que hay un casino en Fénix, ¿cómo será eso?}
{154}{}{La idea de las chapas vino de Fénix, jamás había visto algo así.}

{155}{}{}
{156}{}{La casa de baños está funcionando otra vez.}
{157}{}{Desde que cerro la casa de baños, he tenido una capa de mugre.}
{158}{}{Alguien ha estado cavando las tumbas. Que miedo.}
{159}{}{Se retrasó la caravana de los correos, mataron al gerente en Fénix.}

{160}{}{Esos cultistas me dan nervios.}
{162}{}{No puedo entender a esos Seguidores del Fuego.}
{163}{}{Seguidores del Fuego, Hojalateros, Escudos Azules... ¿somos los únicos cuerdos?}
{161}{}{Ese cultista intentó enseñarme como escribir. Que idiotas, jaja.}
{164}{}{Los Seguidores del Fuego se hacen los devotos, pero esconden cuchillos bajo sus túnicas.}

{165}{}{Los caravaneros dicen que hubo una gran explosión en Fénix.}
{166}{}{Te digo, la Catedral de los Seguidores desapareció.}
{167}{}{Ahora hay un agujero enorme en Fénix, en donde solía estar la Catedral.}
{168}{}{Si vas a Fénix, aléjate de los cultistas.}
{169}{}{Jamás me agradaron los cultistas, pero el comercio será malo sin ellos.}

{170}{}{Hay escorpiones gigantes cerca de los rieles, de nuevo.}
{171}{}{Estoy aburrido de comer iguanas.}
{172}{}{¿Cuándo nos van a traer algo bueno las caravanas?}
{173}{}{El agua por sí sola no basta.}
{174}{}{Extraño el bar, nadie podrá reemplazar al dueño.}
{175}{}{La gente va y viene, pero yo me quedo.}
{176}{}{Tenemos que estar juntos, o terminaremos igual que los de antes.}
{177}{}{¿Has visto al forastero? Si se entera...}
{178}{}{Ni siquiera lo menciones. ¿A quién le importa?}
{179}{}{}

{180}{}{Desde que llegó ese forastero, las cosas se fueron al traste.}
{181}{}{Debemos unirnos y echar a ese forastero.}
{182}{}{¿Qué demonios está haciendo ese forastero?}
{183}{}{El viento nos trajo otro forastero.}
{184}{}{El pueblo se está llenando de forasteros.}
{185}{}{Es mejor evitar a ese forastero.}
{186}{}{No me agrada ese chico nuevo, no me agrada nadie que sea nuevo.}
{187}{}{Desde que llegó ese forastero, las cosas han mejorado.}
{188}{}{Le debemos mucho a ese forastero.}
{189}{}{No puedo creer todo el bien que ha hecho ese forastero.}

{1180}{}{Desde que llegó esa forastera, las cosas se fueron al traste.}
{1181}{}{Debemos unirnos y echar a esa forastera.}
{1182}{}{¿Qué demonios está haciendo esa forastera?}
{1183}{}{El viento nos trajo a otra forastera.}
{1184}{}{El pueblo se está llenando de forasteros.}
{1185}{}{Es mejor evitar a esa forastera.}
{1186}{}{No me agrada esa chica nueva, no me agrada nadie que sea nuevo.}
{1187}{}{Desde que llegó esa forastera, las cosas han mejorado.}
{1188}{}{Le debemos mucho a esa forastera.}
{1189}{}{No puedo creer todo el bien que ha hecho esa forastera.}

{190}{}{Bustos era un tirano, pero la ciudad es débil sin él.}
{191}{}{Todos temían a Don Bustos.}
{192}{}{Bustos está muerto, se viene una guerra por su trono.}
{193}{}{¿Sullivan y Bustos están en las suyas?}
{194}{}{Bustos tiene la buena vida mientras apenas sobrevivimos.}
{195}{}{Es mejor que no hables mal de Don Bustos.}
{196}{}{El Don silencia a cualquiera que sea una inconveniencia.}
{197}{}{El único que sabía arreglar la bomba de agua era John Sullivan.}
{198}{}{¿Y ahora quién está a cargo de la bomba de agua?}
{199}{}{El gerente de la bomba era más duro que las piedras.}

#Responses
{200}{}{Hola. ¿De dónde eres?}
{201}{}{Lo siento, pero no tengo ganas de hablar.}
{202}{}{No tengo tiempo, perdón.}
{203}{}{Habla con alguien más.}
{204}{}{Estás en un pueblo pequeño, nos conocemos todos.}
{205}{}{Cuéntame de ti... mejor no.}
{206}{}{No te quedarás, ¿verdad?}
{207}{}{Buena suerte.}
{208}{}{No me hagas preguntas, por favor.}
{209}{}{Puede que sólo estés de paso, pero yo debo quedarme aquí.}

{210}{}{Sal de aquí mientras puedas.}
{211}{}{No te queremos aquí.}
{212}{}{Sal de nuestro pueblo. Ahora.}
{213}{}{No necesitamos a gente como tú.}
{214}{}{Da un paso más y te arrepentirás.}
{215}{}{Piérdete de inmediato.}
{216}{}{Lárgate o llamaré a mi gente.}
{217}{}{Ojalá que te encuentre una bala loca.}
{218}{}{No sé cómo te toleran los demás.}
{219}{}{Piérdete. Me agotas la paciencia.}

{220}{}{Hola, ¿qué tal?}
{221}{}{Perdona si no te recibimos como se debía.}
{222}{}{Eres el héroe de todos.}
{223}{}{Déjame darte la mano.}
{224}{}{Mi casa es tu casa.}
{225}{}{¡Ah, eres tú! Es bueno verte.}
{226}{}{¿Piensas en quedarte?}
{227}{}{No sé que haríamos sin ti.}
{228}{}{Tenemos suerte de que estés con nosotros.}
{229}{}{Gracias por todo.}

{1220}{}{Hola, ¿qué tal?}
{1221}{}{Perdona si no te recibimos como se debía.}
{1222}{}{Eres la heroína de todos.}
{1223}{}{Déjeme darle un abrazo, señorita.}
{1224}{}{Mi casa es tu casa.}
{1225}{}{¡Ah, eres tú! Es bueno verte.}
{1226}{}{¿Piensas en quedarte?}
{1227}{}{No sé que haríamos sin ti.}
{1228}{}{Tenemos suerte de que estés con nosotros.}
{1229}{}{Gracias por todo.}
