{100}{}{Ves a un ciudadano.}
{101}{}{Ves a un ciudadano de aspecto rudo, está claro que su vida lo tiene desgastado.}

{200}{}{¿Qué quieres?}
{201}{}{Me preguntaba cómo es vivir por aquí.}
{202}{}{Una mierda, igual que en todos lados. Al menos hay agua limpia, algo es algo.}
{203}{}{¿Y entonces por qué hay tan pocas personas?}
{204}{}{Eres un forastero, así que escúchame. Casa Grande tiene un pasado difícil, y es mejor dejar las cosas como están. ¿Lo entiendes?}
{1204}{}{Eres una forastera, así que escúchame. Casa Grande tiene un pasado difícil, y es mejor dejar las cosas como están. ¿Lo entiendes?}
{205}{}{Me suena a que te arrepientes de algo.}
{206}{}{Todos perdimos algo. Nosotros perdimos nuestro hijo y a nuestra casa. No es fácil abrirse y hablar de estas cosas, así que no esperes que los demás lo hagan.}
{207}{}{Lo entiendo, perdón por molestarte. Adiós.}
{208}{}{Que lugar tan miserable. Te dejo.}
{209}{}{Lo que sea.}

{210}{}{¿Tú otra vez?}
{211}{}{Relájate, sólo estoy de paso.}

{220}{}{Busco a la familia de un niño llamado Cody.}
{221}{}{¿Cody? Nuestro pequeño se llamaba así... No he sabido de él desde que los Hojalateros se lo llevaron.}
{222}{}{Parece que es el mismo Cody.}
{223}{}{¿Está vivo? Pensábamos que... Pero, los Hojalateros tienen una mala reputación. ¿Se encuentra bien?}
{224}{}{Le lavaron el cerebro y lo obligan a trabajar, pero parece estar bien.}
{225}{}{Es lo que temía. Pero ahora es uno de ellos, ahora trabaja y probablemente se olvidó de nosotros. Es mejor dejarlo así. Ojalá que no nos odie.}
{226}{}{Tendremos que ver eso. Adiós.}

{230}{}{Escuché que a Cody no se lo llevaron, sino que tú lo vendiste.}
{231}{}{¡Cállate! ¿Quién te crees para meterte en nuestras vidas?}
{232}{}{Oye, cálmate...}
{233}{}{¡No teníamos elección! Nos estábamos muriendo de sed y había que arreglar la bomba, aunque tuviéramos que dar nuestros niños a cambio. Y ahora llegas a recordarnos el pasado. Déjanos en paz.}
{234}{}{Tienes razón, no debería juzgarlos. Adiós.}
{235}{}{Espero que Cody se encuentre en un lugar mejor.}
