{100}{}{Ves a Don Bustos.}
{101}{}{Estás viendo a un hombre con un traje respetable pero raído. Sus sienes grises parecen insinuar un pasado difícil.}
{102}{}{Había oído hablar acerca de esa armadura, pero no pensé que fuera real.}
{103}{}{No voy a tolerar a un repugnante Escudo Azul en mi ciudad.}
{104}{}{Les aconsejo a los dos que se vayan de la ciudad. De inmediato.}

#First meeting
{200}{}{(Apenas entras a la oficina del alcalde, un desagradable aroma a alcohol invade tu nariz. Al mirar a tu alrededor, terminas dándote cuenta de que hay un hombre sentado en la silla, cubre su rostro pero termina viéndote a través de sus dedos. Tras una corta pausa, termina diciendo: "¿Eh"?)}
{201}{}{¿En dónde está el alcalde? Me gustaría hablar con él.}
{202}{}{(Luego de dar un suspiro profundo, el hombre se reclina en su silla, claramente está cansado). Lo tienes en frente tuyo. ¿Quién eres?}
{203}{}{¿Tú eres el alcalde? Y eso que pareces un borracho que se gastó el sueldo en el bar.}
{204}{}{Dejemos esto claro, soy el alcalde de esta ciudad y mi posición es legítima. Si no piensas en reconocer a la autoridad local o aceptar nuestras reglas, entonces quiero que abandones Casa Grande de inmediato. Mi ciudad no necesita a un buscapleitos. ¿Lo entendiste?}
{205}{}{Sí, lo entiendo.}
{206}{}{Perdón, Sr. Alcalde. No voy a causar ningún problema.}
{207}{}{Muy bien. ¿De dónde vienes?}
{1207}{}{Muy bien. ¿De dónde vienes?}
{208}{}{Me llamo }
{209}{}{, estoy viajando por el yermo.}
{210}{}{De acuerdo, }
{211}{}{. ¿Y de dónde vienes?}
{212}{}{¿Por qué te importa tanto?}
{213}{}{Porque en una ciudad de este tamaño, todos quieren saber con quién están tratando y cuánto pueden confiar en ti. Y para ser sinceros, nadie te conoce.}
{214}{}{A nadie debería importarle mis orígenes.}
{215}{}{Entonces, ¿no quieres aceptar nuestras reglas? Estás andando por un camino que no te conviene, forastero. En ese caso, ¿podrías explicarme qué demonios estás haciendo aquí?}
{1215}{}{Entonces, ¿no quieres aceptar nuestras reglas? Está andando por un camino que no le conviene, señorita. En ese caso, ¿podrías explicarme qué demonios estás haciendo aquí?}
{216}{}{Soy de una aldea, está lejos de aquí. Simplemente le llamamos la Villa.}
{217}{}{Jamás he oído hablar de ella, pero digamos que es verdad. ¿Qué vienes a hacer en mi ciudad, si estás tan lejos de casa?}
{218}{}{Estoy viajando, eso es todo. ¿Puedo pasar la noche aquí?}
{219}{}{No tengo problema con eso. Lo normal es que los visitantes pasen la noche cerca de la bomba de agua, dentro de los barracones, junto a las caravanas.}
{220}{}{Gracias, Sr. Alcalde.}
{221}{}{¿Qué clase de ciudad estás gobernando si ni siquiera tiene un motel? Bueno, tendré que conformarme con los barracones. Adiós, Sr. Alcalde.}
{222}{}{Bustos. Mi nombre es Alfred Bustos. Vete, ya perdí mucho tiempo hablando contigo.}
{223}{}{[Hecho]}

{224}{}{Estoy buscando a mi gente, fueron capturados por unos esclavistas.}
{225}{}{(levanta una ceja) ¿Esclavos? ¿Estás por tu cuenta, no?}
{226}{}{¿Sabrá algo acerca de ellos, por casualidad?}
{227}{}{De vez en cuando, los esclavistas transportan a sus esclavos a través de mi ciudad. Pero, no les pregunto de dónde los consiguen.}
{228}{}{¿Hacia dónde los llevan?}
{229}{}{Depende, a algunos los llevan para que trabajen en el sur. En otros casos, simplemente transportan las maletas de sus dueños... Escúchame, forastero... ¿cómo te llamas?}
{1229}{}{Depende, a algunos los llevan para que trabajen en el sur. En otros casos, simplemente transportan las maletas de sus dueños... Escúcheme, señorita... ¿cómo se llamas?}
{230}{}{Olvídalo.}
{231}{}{.}
{232}{}{Los esclavistas tienen un poder formidable, si se llevaron a tu familia, no tienes ninguna oportunidad de darles su libertad de vuelta. Además, mi ciudad se sustenta de los caravaneros. No te atrevas a desestabilizar ese orden.}
{233}{}{Ni los esclavistas ni tú me dan miedo. Adiós, alcalde.}
{234}{}{Sólo quiero a mi familia de vuelta. Sé que debe entender eso, Sr. Alcalde.}

{235}{}{No nos queda espacio para los forasteros en la ciudad. Puedes ir a pasar la noche junto a la bomba de agua, dentro de los barracones, allí también encontrarás a los caravaneros mientras descansan.}
{236}{}{Bustos. Mi nombre es Alfred Bustos. Bienvenido a mi ciudad.}
{237}{}{Necesito hablar con el alcalde de esta ciudad, soy parte de la Iglesia del Fuego Santo.}
{238}{}{Qué sorpresa, lo normal es que se me avise si debo recibir a un embajador de la Iglesia.}
{239}{}{Adelante, siéntete como en casa.}
{240}{}{¿Ahora qué?}
{241}{}{¿Tú otra vez? ¿Qué quieres ahora?}
{242}{}{¿Tú otra vez? Te dije que te largaras de mi ciudad.}
{1242}{}{¿Usted otra vez? Le dije que se fuera de mi ciudad, señorita.}
{243}{}{Adiós, Don Bustos.}
{244}{}{(Apenas entras a la oficina, te das cuenta de que el alcalde está cansado y se apoya sobre la mesa. En su otra mano se encuentra una botella de tequila. al ver el color de tu túnica, deja salir un "Oh...") Qué sorpresa. Se me suele avisar si tendré la visita de un embajador de la Iglesia.}
{245}{}{Sólo estoy de visita.}
{246}{}{Claro, claro. Siéntete como en casa. ¿Estás pensando en ir hacia Two-Sun? ¿Puedo hacer algo para ayudarte?}
{247}{}{¿Habrá pasado alguna caravana esclavista por la ciudad? Me interesa saberlo.}
{248}{}{Sí, últimamente los Hojalateros han estado consiguiendo esclavos, seguramente tienen una tarea importante para ellos. Han pasado muchas caravanas de ese tipo por mi ciudad, pero no les pregunto de dónde los consiguen.}
{249}{}{Entonces, debo ir a Two-Sun... Gracias, Sr. Alcalde. Nos vemos.}

#Bath
{250}{}{Tengo que hablar contigo, se trata de la casa de baños.}
{251}{}{Ese el edificio abandonado que está cruzando la calle. ¿Por qué te importa?}
{252}{}{Curiosidad, eso era todo. No le haré perder más tiempo, Sr. Alcalde.}
{253}{}{Resulta que hay un hombre que busca su reapertura.}
{254}{}{Ya discutí este asunto con él. Nuestra ciudad es pequeña y todos se conocen entre sí, nuestra gente ha formado relaciones entre sí durante años y hay muchos que se sienten incómodos si a su barrio llega un forastero con un pasado cuestionable. No toleraré a un estafador en mi ciudad.}
{255}{}{Hmm. ¿Y en dónde está el verdadero dueño de la casa de baños?}
{256}{}{Quizás fue devorado por los escorpiones, nuestra área está infestada con esas criaturas.}
{257}{}{Eso es una pena, tendré que contarle que no estás de acuerdo.}
{258}{}{Un momento. Antes de que te vayas, quiero dejarte claro que no me gusta que la gente se meta en los asuntos de otros, porque no les incumben.}
{259}{}{Ah, vale, tendré eso en cuenta.}
{260}{}{Ya veo. Podría deshacerme de ese tipo, si no te agrado.}
{261}{}{Me parece bien, te pagaré 100 chapas, pero no quiero que le digas que te pagué por esto. Mi reputación podría verse dañada.}
{262}{}{Puede contar conmigo, Sr. Alcalde.}
{263}{}{En ese caso, me gustaría comprar la casa de baños por 250 chapas.}
{264}{}{Es un precio justo. Tráeme las chapas y firmaré el documento de venta.}
{265}{}{De acuerdo, nos vemos luego.}
{266}{}{Aquí tiene las chapas, Sr. Alcalde.}
{267}{}{Espero que entiendas en qué te estás metiendo.}
{268}{}{Gracias, Sr. Alcalde.}
{269}{}{Tiene una carta que confirma que es el dueño de la casa de baños.}
{270}{}{Nadie sabe de dónde la sacó. Me estás agotando la paciencia.}
{271}{}{Perdón, Sr. Alcalde.}
{272}{}{Eso es muy injusto de tu parte.}
{273}{}{Tiene una carta que confirma que es el dueño de la casa de baños, puedo asegurarte de que su identidad es real.}
{274}{}{De acuerdo, me has convencido. Pero hazle saber a ese canalla que nadie lo quería aquí.}
{275}{}{Como usted diga, Sr. Alcalde.}
{276}{}{¿Sabes? No eres muy buen vecino que digamos.}
{277}{}{Casa Grande tuvo una guerra y eso fue hace poco. ¿Acaso te da miedo que haya venido a vengarse?}
{278}{}{(suspiro) Yo no maté al dueño de la casa de baños, los culpables fueron otros... pero, fue en medio de la guerra que yo empecé.}
{279}{}{Me parece que ese tipo ya lo sabe, pero creo que lo único que le interesa es hacer negocios.}
{280}{}{Te estarías arriesgando mucho si aceptas esto, le diré que rechazaste.}
{281}{}{¿Lo dices en serio? Entonces, valdrá la pena hablar con él. Pero dudo que esto pueda enmendar mis pecados.}
{282}{}{Genial, iré a hablar con él.}
{283}{}{Nos conocemos bien, te puedo garantizar que puedes confiar en él. }
{284}{}{En ese caso, deberías hablar con él. Pero dudo que esto pueda enmendar mis pecados.}
{285}{}{Eso es bueno, iré a hablar con él.}
{286}{}{... No me sorprende que alguien con un nombre así sea incapaz de quedarse quieto. }
{287}{}{Si esto es una broma, no da risa. Si te haces o te ocurre algo, pensarán que soy yo, porque nadie se dará cuenta de que en una ciudad hay dos personas que se llaman igual. Esto será muy desagradable... }

{290}{}{Ese tipo ya no volverá a molestarte.}
{291}{}{Muy bien hecho, no me gusta ensuciarme las manos.}
{292}{}{[Más]}
{293}{}{Todo trabajo debería tener una remuneración decente, ¿no lo crees? Toma, te has ganado tus 100 chapas. Pero recuerda que yo no tuve nada que ver este... 'accidente'.}
{294}{}{Nadie se enterará de esto, Sr. Alcalde.}
{295}{}{No me conviene llevarme mal con alguien que podría ser mi cliente.}

#Stop the dialogue
{300}{}{No sé qué era lo que querías conseguir, pero te acabas de ganar un enemigo. Fuera de mi ciudad, no necesito que hayan imbéciles como tú.}
{301}{}{[Sal del edificio]}
{302}{}{(Los guardias te llevan a la salida.)}

{308}{}{Oye. ¿Puedes creerlo? Algún idiota ha estado excavando las tumbas de nuestro cementerio. Quizás se te ocurra quién pueda ser el culpable.}
{309}{}{¿Alguien le está robando a los muertos? ¿De verdad? Yo no sé ni madres acerca de eso.}
{310}{}{Te recuerdo. Es sospechoso que justo después de que llegaste a la ciudad, alguien empezó a excavar las tumbas del cementerio.}
{311}{}{Es una coincidencia muy rara, ¿no crees?}
{312}{}{¿Y qué? ¿Acaso me estás acusando de algo?}
{313}{}{No creo que en las coincidencias. Si fuera a aparecer la más pequeña evidencia en tu contra, entonces te espera un castigo muy grave. Recuerda eso y no hagas nada estúpido.}
{314}{}{Ay, qué miedito.}
{315}{}{Debes estar demente si vas a comportarte así en frente del alcalde. Se suele ser muy clemente con los idiotas, pero en mi ciudad, eso no es así. Los problemas jamás dejan de aparecer, así que estamos cansados de ellos. Por lo tanto, no me agotes la paciencia, ¿bien?}
{316}{}{Ya veo.}
{317}{}{No tuve nada que ver con esto, Sr. Alcalde.}
{318}{}{De acuerdo, te creeré, por ahora. No me decepciones.}
{319}{}{Por supuesto, Don Bustos. No hay ningún problema.}

{320}{}{Los guardias me dijeron que arreglaste la farola de la calle.}
{1320}{}{Los guardias me dijeron que arreglaste la farola de la calle.}
{321}{}{Sí, fui yo.}
{322}{}{Para ser sincero, no sé por qué lo hiciste. Pero si querías causarme una buena impresión, lo conseguiste. Gracias.}
{1322}{}{Para ser sincero, no sé por qué lo hiciste. Pero si querías causarme una buena impresión, lo conseguiste. Gracias.}
{323}{}{¿Sólo me vas a dar las gracias? ¿No me darás nada?}
{324}{}{No te pedí que lo hicieras, pero puedes llevarte un poco de agua limpia como recompensa.}
{325}{}{Gracias, Sr. Alcalde.}
{326}{}{¿Esta es tu forma de dar las gracias? Dios mío.}
{327}{}{Me gusta la tecnología antigua, eso es todo. De nada.}
{328}{}{Has mejorado tu reputación ante el alcalde, y por lo tanto, también ante el resto de la ciudad.}
{329}{}{Bien.}

{330}{}{Tu llegada sólo nos ha traído problemas.}
{331}{}{¿Lo dices en serio?}
{332}{}{¿De qué estás hablando?}
{333}{}{Se encontró el cadáver de uno de los ciudadanos cerca de la estación de tren. ¿Qué sabes al respecto de eso?}
{334}{}{No, no sé nada.}
{335}{}{De acuerdo. Todavía nos falta descubrir qué pasó allí, así que si sabes algo, no te calles. Vete, tengo trabajo que hacer.}
{336}{}{[Deja en paz al alcalde]}
{337}{}{Una de nuestras ciudadanas ha desaparecido, la última vez que la vieron fue cerca de la estación de tren mientras atrapaba iguanas. ¿Sabes algo acerca de esto?}
{338}{}{Lo más seguro es que los escorpiones se la hayan comido, hay muchos en esa zona.}
{339}{}{Es lo más probable. Sin embargo, resulta que sabes que hay escorpiones por allá... Si llegas a enterar de algo, quiero que me lo digas. Andando, tengo cosas que hacer.}
{340}{}{Quizás nunca podría haber llegado a la ciudad en primer lugar, lo más seguro es que hayan sido los escorpiones.}
{341}{}{Tal vez. Bueno, es probable. Puedes irte, por el momento.}
{342}{}{[Hecho]}

#Questions
{350}{}{Estoy buscando a un Hojalatero, vino aquí como un embajador.}
{351}{}{¿Acaso no regresó a Two-Sun? ¿Cómo voy a saber en dónde está?}
{352}{}{¿Entonces estuvo aquí?}
{353}{}{Sí, pero se fue sin decir nada. Pensé que se había ido.}
{354}{}{¿Y no creíste que eso era extraño?}
{355}{}{Los Hojalateros nos ven como simples mortales, creen que somos algo parecido a los salvajes. Son gente extraña, porque nunca sabes qué esperar de ellos Así que cuando nuestro huésped se fue sin decir nada, no me preocupé. Estoy seguro de que ya está con su gente.}
{356}{}{No, no regresó a Two-Sun. El Maestro Hard me pidió que lo encontrara.}
{357}{}{Ah, entiendo. Bueno, te dije todo lo que sé. Tendrás que preguntar en otro lado.}
{358}{}{Eso haré. Adiós.}
{359}{}{Esto es sospechoso. Me sorprendería que usted no tenga nada que ver con su desaparición, alcalde.}
{360}{}{Me parece que a los lugareños no les agradan los Hojalateros. ¿Quién podría hacerles daño?}
{361}{}{Alto ahí, mercenario. Los Hojalateros han reparado la bomba de agua y gracias a ellos nos llegan caravanas de forma regular, les debemos eso. Ninguno de nosotros se atrevería a ponerles un dedo encima.}
{1361}{}{Alto ahí, mercenaria. Los Hojalateros han reparado la bomba de agua y gracias a ellos nos llegan caravanas de forma regular, les debemos eso. Ninguno de nosotros se atrevería a ponerles un dedo encima.}
{362}{}{De todas formas, voy a investigar esto. Adiós.}
{363}{}{Sólo me hace sospechar más si está tan confiado, alcalde.}
{364}{}{¿No piensas que es raro que haya desaparecido?}
{365}{}{¿De verdad llegó a Casa Grande?}
{366}{}{Jamás regresó a Two-Sun, por eso me pidieron que lo encontrara.}
{367}{}{Estoy perdiendo el tiempo, iré a buscar al Hojalatero en otro lado.}
{368}{}{Seguro que sí. Perdona, no quería distraerte de tus asuntos.}
{1368}{}{Seguro que sí. Perdona, no quería distraerte de tus asuntos.}
{369}{}{¿En dónde se quedó, durante su visita?}

{370}{}{Quería preguntarte sobre la ciudad, sigo sin conocerla bien.}
{371}{}{Casa Grande es mi tesoro. ¿Qué quieres saber de ella?}
{372}{}{Lo único que te diré es que la salida está por allá.}
{373}{}{No hay nadie que conozca a Casa Grande como yo. ¿Qué necesitas saber?}
{374}{}{Ya sé lo suficiente. Hasta luego.}
{375}{}{Dame un poco más de tu tiempo.}
{376}{}{Más al este, hay una choza que solía pertenecer a un destilador de alcohol. A los Hojalateros no les gusta tener cerca a la gente... 'normal'.}

{380}{}{¿Qué se puede hacer en esta ciudad?}
{381}{}{Casa Grande es una ciudad pequeña, a pesar del nombre. Solíamos tener un salón, era famoso en el área gracias a que tenía alcohol casero y música. Pero, el bar cerró y la rocola está rota, así que la gente debe entrenarse por su cuenta.}
{382}{}{¿Qué pasó?}
{383}{}{Ocurrió un tiroteo dentro del bar, pero eso ya está en el pasado. Sólo quiero que tengas en cuenta que el bar cerró.}
{384}{}{Tú y yo sabemos que eso no fue un tiroteo.}
{385}{}{Hablas demasiado. Bueno, lo que ocurrió fue que en el bar, mi gente pudo deshacerse de un clan enemigo. Es una pena, pero el cantinero murió a causa de una bala perdida. Era un buen tipo.}
{386}{}{Gracias por ser honesto con tu respuesta. Pero, mejor cambiemos de tema.}
{387}{}{¿Su propio alcohol? ¿En serio?}
{388}{}{Sí, es producido localmente. Quizás jamás hayas probado esta bebida, es maravillosa. Nuestro destilador nos abastecía con cerveza y también la intercambiaba con Fénix. Ah, si no fuera por esos malditos escorpiones, él seguiría beneficiando a la tesorería de la ciudad con sus ingresos.}
{389}{}{He visto que Fénix ha producido tequila.}
{390}{}{¿En serio? A veces las caravanas vienen de sur y transportan jarabe de agave y lo llevan hacia Fénix. Ese competidor en específico era un gran problema para nuestro destilador. Y de hecho, ahora nos encontramos comprando el alcohol de Fénix.}
{391}{}{Esto es un poco triste, dejemos de hablar de ello y cambiemos de tema.}
{392}{}{¿Hay alguna tienda en esta ciudad?}
{393}{}{Ve hacia la bomba de agua si necesitas reabastecerte. Los caravaneros suelen traernos el resto de los bienes, están en el estacionamiento de aquí cerca.}
{394}{}{¿Por qué hay tantas caravanas en este lugar?}
{395}{}{Porque tenemos muchísima agua y somos un punto en la ruta entre Fénix y Two-Sun. Esta situación nos conviene, excepto por los condenados forajidos.}
{396}{}{He oído un rumor de que los Hojalateros ya no existen. ¿Cómo crees que se verá afectada Casa Grande?}
{397}{}{Hay más asentamientos en el sur y todavía podemos comerciar agua. Además, hay muchos saqueadores y forajidos que se apresuraron a ir al sur apenas se enteraron de los rumores. Por el momento, podremos mantenernos a flote. Pero, ¿qué nos deparará el futuro?}
{398}{}{Se dice que la Iglesia del Fuego Santo de Fénix fue destruida.}
{399}{}{Sí, y eso es un problema. En cierto modo, la Iglesia apoyaba a esta ruta comercial de forma muy activa. Habrán menos caravanas sin ellos, pero alguien tomará su lugar, en algún punto.}
{400}{}{¿Quiénes son esos forajidos?}
{401}{}{Verás todo tipo de chusma junto a la Interestatal 10. Sólo son unos saqueadores que en vez de atacar ciudades, se dedican a asaltar caravanas y a otros viajeros. Cada vez que atacan una caravana sufrimos pérdidas graves.}
{402}{}{¿Has intentado atraparlos?}
{403}{}{¿A quiénes? ¿A esa docena de bandas disparejas que nunca dejan de cambiar? Es una lucha interminable, si matas a uno, aparecen tres más. Lo importante es enfocarnos en que el interior de la ciudad sea segura.}
{404}{}{Olvidémonos de los forajidos, tengo más preguntas.}
{405}{}{Esa bomba de agua me llama la atención.}
{406}{}{Ve hacia la bomba y habla con Sullivan, la conoce como la palma de su mano.}
{407}{}{Ve hacia la bomba y pregúntale a alguien de allá.}
{408}{}{Me parece bien. Ya vuelvo.}
{409}{}{Eso es una buena idea, iré hacia allá de inmediato.}
{410}{}{Cuéntame acerca de ese tal Sullivan. ¿Quién es?}
{411}{}{No me gusta hablar acerca de mis hombres con un forastero. Si quieres conocer a Sullivan, habla con él, cara a cara.}
{412}{}{Tengo una última pregunta.}
{413}{}{Iré a hablar con él de una vez. Adiós.}
{414}{}{Háblame sobre Sullivan. ¿Es una buena persona?}
{415}{}{Para mí, él es como un hermano ya que empezamos esto juntos. Yo sabía como negociar con los demás y él sabía cómo arreglar problemas. Sin John, las cosas no hubieran sido nada fáciles.}
{416}{}{Sí que parece que son hermanos. Pero, tu ciudad me interesa más.}
{417}{}{Cuando se trata de negocios, la palabra 'hermano' pierde todo su significado.}
{418}{}{Voy a pretender que no dijiste eso. Quizás en la gran ciudad sea así, pero aquí las chapas y la amistad van de la mano. Yo valoro mucho a John, es una persona en la que puedo confiar, no hay nadie como él en Casa Grande.}
{419}{}{¿Sullivan era tu amigo, no?}
{420}{}{Ni siquiera menciones su nombre. Habíamos empezado esto juntos, jamás me había esperado una traición de ese tipo. Ya ni siquiera quiero saber de él.}
{421}{}{¿No habías dicho que en Casa Grande no había nadie como él?}
{422}{}{Esto tuvo que haberte dolido mucho, es mejor que no lo mencione.}
{423}{}{(da un golpe a la mesa) Sullivan... Fue un villano y recibió su merecido. Lo único que puedo hacer es borrar a ese traidor de mi vida, es mejor que cierres la boca antes de que nuestra relación se dañe para siempre.}
{424}{}{Perdona, es mejor que ya no hablemos de esto.}
{425}{}{Los problemas de tu pasado siguen allí, no puedes pretender que no existen. Hablemos de otro tema.}
{426}{}{Por culpa tuya, la muerte es muy común en tu ciudad. Tus historias me dan miedo y ya he oído suficiente.}
{427}{}{}
{428}{}{No debería haberse metido en esto en primer lugar. Adiós, alcalde.}
{429}{}{Su argumento es débil, alcalde. Muy débil.}

{430}{}{El cementerio de la ciudad es muy grande para una ciudad tan pequeña.}
{431}{}{Es mejor que te alejes de ese sitio. Y no vayas a meterte en cosas que no te conciernen.}
{432}{}{Lo siento, no volveré a hacerlo.}
{433}{}{Quiero saber qué ocurrió, de todas formas.}
{434}{}{Un poco de todo - saqueadores, escorpiones... Pero, ya basta. ¿Acaso crees que a la gente le gusta que te metas en su pasado?}
{435}{}{Sé lo que ocurrió aquí, te apoderaste de Casa Grande a la fuerza.}
{436}{}{Ese saqueador me dijo que mataste a la mitad de población para llegar al poder.}
{437}{}{A grandes males, grandes remedios. Si no hubiera empezado esa lucha en ese entonces, la hubiera empezado alguien más. Es el estado natural de las cosas.}
{438}{}{¿Entonces lo que hiciste era inevitable?}
{439}{}{Había demasiada gente para los pocos recursos que teníamos. Esta ciudad se sustenta al bombear agua y sirviendo como campamento para las caravanas, no hay nada más que pueda dejarnos vivir en este desierto. Y como resultado, hubo muchos que no encontraron su lugar en la ciudad, por lo que empezaron a haber bandidos y guerras de clanes.}
{440}{}{Ah, así que por eso siempre andas borracho.}
{441}{}{Ya entiendo por qué necesitas tantos guardaespaldas.}
{442}{}{El pasado a veces no se suelta. Es la cruz que me tocó cargar.}
{443}{}{Tuve la oportunidad de visitar un sitio en donde restauraban una fábrica del Viejo Mundo. También hubo gente que murió en la lucha por ella.}
{444}{}{¿Lo dices en serio? Bueno, me sirve como una pequeña consolación. Aunque, me alegra que el yermo por fin esté pasando por un cambio de imagen. Me pregunto si podré ver a un Corvega en acción, igual que en las revistas de antaño.}
{445}{}{Eres un monstruo. ¿Cómo pudiste haber matado a decenas de personas para tu propio beneficio?}
{446}{}{Si hablar de esto te pesa, entonces hablemos de otra cosa.}
{447}{}{Tendré que seguir con la cabeza en alto. Adiós.}
{448}{}{Cierra tu boca y escúchame de una vez. YO SOY EL ALCALDE DE ESTA CIUDAD. Yo me hago responsable por ella. Y no permitiré que NADIE hable mal de MI ciudad. ¿Quién te crees que eres para juzgarme? Eres otro vagabundo más. Así que sigue con tu camino.}
{449}{}{Tienes razón, yo sólo estoy de paso. Adiós, Alcalde.}
{1449}{}{Tienes razón, yo sólo estoy de paso. Adiós, Alcalde.}

#First quest
{450}{}{¿Hay algún trabajo que pueda hacer aquí? Me vendría bien ganarme unas chapas mientras esté aquí.}
{451}{}{No tengo ningún trabajo que ofrecerte.}
{452}{}{Comprendo. ¿Podrías responderme unas dudas, entonces?}
{453}{}{De acuerdo, iré a preguntárselo a las demás personas de la ciudad.}
{454}{}{No tengo ningún trabajo que ofrecerte... Sin embargo, podrías resolverme un problema.}
{455}{}{¿De qué se trata?}
{456}{}{Unos forajidos asaltaron a una caravana que pasaba por la estación de tren, agarraron el cargamento y se encerraron en la estación. No parece que vayan a irse de ahí, es como si quisieran provocarnos o ver qué haremos. Ve hacia allá y descubre qué es lo que quieren.}
{457}{}{Pero tienes guardias, ¿acaso están de adorno?}
{458}{}{¿No hay algún sheriff que pueda lidiar con cosas así?}
{459}{}{Es una caja con unas cosas viejas, nadie quiere arriesgarse la vida por algo así. Sólo deseamos que los forajidos se cansen de estar encerrados ahí y que eventualmente se vayan por decisión propia.}
{460}{}{Me hacen falta chapas, pero no tanto como para arriesgar mi pellejo. Pídeselo a otra persona.}
{461}{}{De acuerdo, me encargaré de los forajidos.}
{462}{}{Genial. Ve al sur, la estación está hacia allá.}
{463}{}{Prepara esas chapas, porque esos saqueadores se arrepentirán de haberse metido contigo.}

{470}{}{Ah, ahí estás. Pasa, siéntate. Luego de ese desastre del bar, quería tomarme un trago y tomar un respiro. Sírvete algo, si quieres. Es lo menos que puedo hacer, porque mi hija y yo podemos seguir libres gracias a ti.}
{471}{}{Lo que pasó fue extraño. Oiga, Don, ¿por qué esos forajidos querían atacar a la ciudad?}
{472}{}{Los forajidos como ellos suelen quedarse junto a las carreteras para asaltar a los viajeros, en general evitan las ciudades y los pueblos. Pero estos bandidos sabían qué hacer, porque su líder solía vivir aquí, en Casa Grande... Pero, es una larga historia, y todavía no te he pagado por tu ayuda.}
{473}{}{[Más]}
{474}{}{Voy a darte 250 chapas. Puedes ganar más.}
{475}{}{¿Más? ¿Cuántas más?}
{476}{}{Te escucho. ¿Qué problema tienes ahora?}
{477}{}{Ustedes están libres, pero es obvio que ellos querían hacerte daño a ti.}
{478}{}{Hablas mucho, para ser un mercenario. Como creo que ya sabes, los forajidos como ellos suelen quedarse junto a las carreteras para asaltar a los viajeros. Pero, los forajidos que viste en el bar tenían cuentas que saldar conmigo, era personal. Pero, es una larga historia, y todavía no te he pagado por tu ayuda.}
{479}{}{[Más]}
{480}{}{Ahí estás... Pasa. Necesito un trago después de... de lo que pasó.}
{481}{}{Tu hija está muerta. Lo siento, en serio.}
{482}{}{¡Los maldigo a todos! En una ocasión, cometí el error de exiliar a algunos ciudadanos de aquí, en vez de ejecutarlos. Y ahora han regresado. Y mi hija... La única que me opción que me queda es vengarme de una forma despiadada y brutal de esos malditos forajidos...}
{483}{}{[Más]}
{484}{}{¿Crees que el alcohol arreglará tus problemas? No funciona así.}
{485}{}{¿Qué demonios vas a saber tú...? (suspira y se calma) Como sea. En una ocasión, cometí el error de exiliar a algunos ciudadanos de aquí, en vez de ejecutarlos. Y ahora han regresado, como forajidos. Ahora debo acabar con ellos de una vez por todas...}
{486}{}{[Más]}
{487}{}{Parece que te hacen falta las chapas, ¿eh? No te pagaré por lo que ocurrió en el bar, pero si tengo otro trabajo por el que podría pagarte.}
{488}{}{¿Qué es lo que debo hacer?}
{489}{}{Esos saqueadores que viste en el bar formaban parte del clan de forajidos más grandes de la región - los Escudos Azules. A la hora de cometer crímenes son despiadados, por lo que son infames. Hace poco asaltaron a una caravana, por lo que adquirieron armas de la mejor calidad. Así que ahora son una amenaza para la ciudad entera.}
{490}{}{Por cómo lo dices, quieres detenerlos. Pero, ¿cómo?}
{491}{}{Mata a su líder, se llama Ben. Te daré 500 chapas a cambio de su cabeza. Tráemela.}
{492}{}{Durante un largo tiempo, he estado buscando a una persona inteligente, alguien como tú, alguien que pueda encontrar su guarida y acabar con su líder. Su nombre es Ben, si lo eliminas, el clan se hará pedazos y nos dejarán en paz, al menos durante un tiempo.}
{493}{}{No tienes que explicármelo todo. ¿Cuántas chapas me darás?}

#Second quest
{500}{}{Los forajidos son como los carroñeros - forman manadas y merodean por la carretera para cazar presas fáciles. Los clanes pequeños no representan ninguna amenaza a nuestra ciudad, pero hay uno más grande que el resto.}
{501}{}{Déjame adivinar, ¿esos tipos son los que secuestraron a tu hija?}
{502}{}{Sí, y no es la primera vez que vienen a por nosotros. Son parte del clan de los Escudos Azules. Se les conoce en toda la región porque son despiadados en sus crímenes. Ese clan está lleno de la escoria más violenta y desesperada de toda Arizona.}
{503}{}{Esto no será nada fácil, soy sólo una persona, ¿en serio crees que podré con todos ellos?}
{504}{}{Al diablo con el trasfondo de esto, sólo dime cómo encontrarlos.}
{505}{}{No es necesario lidiar con toda su banda. Voy a darte 500 chapas por la cabeza de Ben, su líder. Si llegas a destruir su tanque de combustible, te daré el mismo monto.}
{506}{}{Tantas muertes me atormentarían por años. No puedo hacer esto.}
{507}{}{Bueno, es una pena. Pensaba que tenía a un verdadero héroe en frente mío. Sin embargo, no lo decidas ahora. El problema no se resolverá por sí mismo y siempre estoy dispuesto a remunerar un trabajo bien hecho.}
{508}{}{Adiós.}
{509}{}{Genial, ve preparando un lugar en donde poner la cabeza de Ben.}
{510}{}{Tráeme su cabeza y te recompensaré. Buena suerte.}
{511}{}{Adiós.}
{512}{}{Necesito más información acerca de los Escudos Azules.}

{520}{}{Quiero hablarte acerca de los Escudos Azules.}
{521}{}{¿Sí?}
{522}{}{No he hecho nada. Sólo quería decirte que todavía estoy en ello. Adiós.}
{523}{}{Este clan es muy fuerte, ¿por qué?}
{524}{}{Resulta que los Hojalateros tienen máquinas que producen muy buen equipo, los bandidos asaltaron una de sus caravanas y ahora están bien equipados. Además, cuentan con una enorme reserva de gasolina. Nuestra ciudad se verá amenazada si siguen volviéndose más poderosos.}
{525}{}{¿En dónde consiguieron tanto combustible?}
{526}{}{Se dice que se apoderaron de un viejo almacén de combustible y lo utilizan como su base. Dependen de la gasolina. Casi parecen coches.}
{527}{}{Háblame sobre el líder de los Escudos Azules.}
{528}{}{Se llama Ben, solía vivir aquí, pero lo expulsé de la ciudad junto a su banda. Por eso lo conozco.}
{529}{}{¿Por qué importa tanto matar a su líder?}
{530}{}{El clan se desmoronará sin un líder, o al menos nos dejarán en paz un tiempo.}
{531}{}{¿Cuál es el punto de destruir su tanque de combustible?}
{532}{}{La gasolina es lo que los mantiene vivos, es tanto un arma como una forma de sobrevivir, porque es un recurso valioso y podrían usarlo para comerciar en el futuro. Además, la destrucción del tanque le hará daño a la estructura del fuerte en sí. Un ataque de ese tipo dejaría al clan en pedazos.}
{533}{}{¿Cómo sabrás si hice explotar el tanque de combustible?}
{534}{}{Tengo binoculares, si lo haces, podré usarlos y ver el humo. Además, ojos y orejas por todos lados; tal cosa no se le puede esconder a los demás.}
{535}{}{¿En dónde está la base de los Escudos Azules?}
{536}{}{Según los caravaneros, se encuentra al noreste de nosotros, en algún lado.}
{537}{}{¿Por qué hay ciudadanos de Casa Grande entre los Escudos Azules?}
{538}{}{Es una larga historia, un poco vieja. Mi primera acción como alcalde fue desalojar a toda la escoria de nuestra ciudad. Resulta que algunos sobrevivieron y empezaron a aterrorizar a todos en las carreteras,}
{539}{}{Ya he oído suficiente. Nos vemos luego, Don.}
{1539}{}{Ya he oído suficiente. Nos vemos luego, Don.}
{540}{}{Te he traído una cabeza. ¿La reconoces?}
{541}{}{(mira a la cabeza en silencio, su rostro revela desprecio y odio, luego la suelta) Tiren a este pedazo de basura al yermo, que los escorpiones se coman al último líder de los Escudos Azules.}
{542}{}{Como usted diga, Don.}
{543}{}{No, no la toquen. La colgaré sobre los rieles, en la entrada a la ciudad. De esa forma, todos sabrán lo que les espera si van en contra de las autoridades.}
{544}{}{Buena idea.}
{545}{}{Claro, pero no te olvides de mencionar quién lo mató.}
{546}{}{Aprecio a la gente que es capaz de hacer bien sus trabajos. Mereces una recompensa. (saca algunas chapas de la caja fuerte) En total, son 500 chapas, lo que acordamos. Déjame sólo, quiero descansar.}
{547}{}{Adiós, Don.}
{548}{}{Oye, ¿qué hay de mi recompensa? ¿Crees que arrastré su cabeza por el yermo para nada?}
{549}{}{Claro, es tu derecho, te lo has ganado honestamente... (saca algunas chapas de la caja fuerte) En total, son 500 chapas, lo que acordamos. Déjame sólo, quiero descansar.}

{550}{}{He conseguido destruir el tanque de combustible de los Escudos Azules. Eso debilitará a la banda.}
{1550}{}{He conseguido destruir el tanque de combustible de los Escudos Azules. Eso debilitará a la banda.}
{551}{}{Entonces, los rumores eran ciertos. Mientras los caravaneros transitaban la ruta comercial, pudieron ver una nube de humo en el cielo. Si el tanque de combustible fue destruido, eso quiere decir que se avecinan tiempos difíciles para los Escudos Azules.}
{552}{}{Ejem. No hice esto gratis, ¿se te olvidó nuestro trato?}
{553}{}{Por supuesto, tu recompensa - 500 chapas. Y, gracias. Le has hecho un favor invaluable a la ciudad.}
{554}{}{De nada, Don. Tu ciudad tendrá futuro, mientras tenga chapas que recompensar.}
{555}{}{Aprendí a las malas lo que ocurre si permites que alguien te haga daño a ti o a tu familia. Digamos que detener a los Escudos Azules era mi deber.}
{556}{}{¿Lo dices en serio? Ahora entiendo de dónde sacas tanta fuerza para pelear. Espero que puedas librar a tu gente de la esclavitud, lo digo en serio. Tengo tu recompensa, las 500 chapas. Y... gracias. Le has hecho un favor invaluable a nuestra ciudad.}
{557}{}{Adiós, Don Bustos.}
{558}{}{Así será. Los saqueadores están debilitados y es posible que se traicionen entre sí, o que se separen.}
{559}{}{Has hecho un buen trabajo, por lo que no me importa darte las 500 chapas. Y... gracias. Le has hecho un favor invaluable a nuestra ciudad.}
{560}{}{De nada, Don Bustos.}

{569}{}{Los forajidos hacen que tu ciudad sufra, si haces esto, habrán menos de los que preocuparte.}
{570}{}{He oído que atrapaste a uno de los forajidos.}
{571}{}{Así es. Lo tenemos entre rejas, porque primero debemos sacarle toda la información acerca de su banda que sea posible, luego podremos ejecutarlo públicamente.}
{572}{}{¿Estás seguro de que es un criminal?}
{573}{}{Algunos ciudadanos lo reconocieron como un forajido. Yo les creo. Además, llevaba puestas unas señales de tráfico, cosa que los forajidos suelen hacer para protegerse durante los ataques.}
{574}{}{Enhorabuena, Alcalde. Tengo que irme.}
{575}{}{Tengo que hablar con él, quizás tenga algo interesante que contarme.}
{576}{}{Está encerrado en el primer piso. Le diré a los guardias que te pueden dejar pasar.}
{577}{}{Tienes al tipo equivocado, déjalo ir.}
{578}{}{¿Qué? ¿Crees que debería confiar en tu palabra y dejarlo libre? No lo creo. Sin embargo, será interesante oír lo que tienes que decirme.}
{579}{}{Mi trabajo era decírtelo, el resto depende de ti.}
{580}{}{Ese era mi testimonio, ¿no te basta?}
{581}{}{No. Confío en mi gente, pero no en ti.}
{582}{}{La decisión es tuya. Adiós.}
{583}{}{Pues, eh... habíamos trabajado en la misma caravana. No es ninguna amenaza, te lo juro.}
{584}{}{Hmm. Te seré honesto, no sé quién es o de dónde vino, pero nuestros ciudadanos siempre ven a un forastero como un enemigo. Vale, dejaré que ese tipo se vaya, pero con una condición. Debe irse de mi ciudad, tiene una hora para hacerlo.}
{585}{}{Gracias, Sr. Alcalde.}
{586}{}{Puedo ofrecerte un colateral, te daré 100 chapas para que lo dejes libre.}
{587}{}{Eso es razonable. Sin embargo, dile que tiene una hora para irse de aquí.}
{588}{}{Gracias, Sr. Alcalde.}
{589}{}{Eso es razonable.}
{590}{}{Dame un momento, te traeré las chapas.}
{591}{}{Los Escudos Azules han propuesto formar una alianza contigo, ya han hecho un acuerdo con los Hojalateros.}
{592}{}{¿Qué? ¿O sea que los Hojalateros los están protegiendo? ¡Eso es indignante!}
{593}{}{Los Hojalateros los han reconocido como un asentamiento pacífico e independiente.}
{594}{}{Demonios, he actuado demasiado lento. Al menos, supongo que la banda nos dejará en paz a nosotros y a las caravanas durante algún tiempo. Pero no se puede confiar en esos bandidos, hay muchos que tienen una venganza personal en mi contra, o con toda Casa Grande.}
{595}{}{No tienes ninguna otra opción, si te resistes, los Hojalateros no lo tolerarán.}
{596}{}{Eso es obvio. Voy a tomar en cuenta tus logros y firmaré el acuerdo. Pero haré todo lo que esté en mi poder para que los Escudos lo paguen muy caro.}
{597}{}{Voy a contarle esto a Ben. Adiós.}
{598}{}{Ni de loco voy a formar una alianza con ellos. Sal de aquí y dile a Ben que los Hojalateros no podrán protegerlo a él y a su banda de la justicia.}
{599}{}{Le diré a Ben lo que acababas de decir. Adiós.}
