{100}{}{Ves a un guardaespaldas.}
{101}{}{Ves a un hombre, está equipado para luchar. Te observa con cautela.}
{102}{}{Es mejor que vuelvas con los Hojalateros, no queremos a gente como tú.}

{110}{}{El Don no tiene tiempo para idiotas como tú.}
{111}{}{¿Qué estás mirando?}
{112}{}{¿Necesitas algo?}
{113}{}{Ni se te ocurra robarnos.}
{114}{}{Parece que quieres causarnos problemas.}
{115}{}{Tienes que estar desesperado si llegaste hasta acá.}
{116}{}{¿Quieres pelear?}

{120}{}{Don Bustos está adentro.}
{121}{}{¿Quieres ver al alcalde, verdad? Está bien, puedes pasar.}
{122}{}{Está bien, pasa. Pero compórtate.}
{123}{}{No te atrevas a molestar al Don.}
{124}{}{Puedes entrar, pero no te quitaré los ojos de encima.}

{130}{}{Genial, tendré que buscar trabajo.}
{131}{}{La ciudad será mucho más peligrosa, ya no tenemos alcalde.}
{132}{}{Demonios, el Don pagaba bien. Y encima había agua, y mucha.}
{133}{}{Puede que Bustos haya sido un tirano, pero pagaba bien, y nunca se retrasaba al darme el sueldo.}
{134}{}{Bueno, adiós a mi trabajo.}

{140}{}{Estás en el sitio equivocado, saqueador de mierda.}
{141}{}{Un momento, ¿eres uno de los Escudos Azules?}
{142}{}{Malditos saqueadores, andan por ahí pensando que la ciudad es suya.}
{143}{}{No puedo creer que los Escudos Azules estén negociando con nosotros...}