{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia de la bomba de agua. No parece saber qué hacer con su vida.}

{110}{}{¿Qué quieres?}
{111}{}{Es mejor que salgas de nuestro territorio.}
{112}{}{Si quieres agua, habla con el vendedor de la entrada.}
{113}{}{Habla con el jefe.}
{114}{}{¿Conoces al alcalde?}
{115}{}{Aquí encontrarás el agua más limpia del yermo.}
{116}{}{Aquí le cortamos las manos a los ladrones, así que ni se te ocurra.}
{117}{}{Siempre estamos alerta.}
{118}{}{Mantener la bomba a salvo se vuelve cansino.}
{119}{}{Los forajidos afectan nuestro negocio.}
{120}{}{Es mejor que evites a los forajidos.}
