{100}{}{Ves a un mercader de agua.}
{101}{}{Estás viendo a un hombre inusualmente limpio. No tiene que ensuciarse con un trabajo como este.}
{102}{}{¿Eres uno de los Hojalateros? Entonces no asustes a la gente con ese pedazo de hojalata.}
{103}{}{Sal de aquí antes de que te dispare, los forajidos no tienen lugar en esta ciudad.}
{104}{}{Este es el precio de tu codicia, perra.}
{105}{}{¿Recuerdas lo que dijiste? Esto es lo que recibes a cambio de tu codicia.}
{106}{}{De ahora en adelante, la selección de bienes que el mercader tiene disponible será más extensa.}
{107}{}{No puedo hablarle a dos personas al mismo tiempo.}

#First dialogue
{200}{}{(te entrecierra los ojos mientras se seca las manos con una toalla mugrienta) Creo que no te he visto antes. ¿Llegaste hace poco?}
{201}{}{Sí, soy de otro lugar. ¿Qué es este lugar?}
{202}{}{¿Cómo crees? Yo nací y me críe aquí...}
{1202}{}{¿Cómo crees? Yo nací y me críe aquí...}
{203}{}{Sí, ya entendí. Pero te haré saber que a la gente de por aquí no les agradan los bromistas. En estos momentos, la vida no está como para reírse.}
{204}{}{Ah, perdona. Fue tonto de mi parte. ¿Qué es este lugar?}
{205}{}{Ya me di cuenta, por cómo me miras. Cálmate, amigo. De todos modos, ¿en dónde estoy?}
{1205}{}{Ya me di cuenta, por cómo me miras. Cálmate, amigo. De todos modos, ¿en dónde estoy?}
{206}{}{Estás en la bomba de agua. Extraemos agua del subsuelo y se la vendemos a aquellos que la necesiten. La embotellamos en esta sección. ¿Necesitas agua?}
{207}{}{No, estoy buscando otra cosa.}
{208}{}{Estoy demasiado ocupado como para chacharear. No me distraigas de mi trabajo.}
{209}{}{Esta no es la mejor bienvenida que he tenido...}
{210}{}{Sí, necesito agua, y rápido.}
{211}{}{Todos necesitan agua, eso está claro. Pero si quieres beber, tienes que pagar. En este lugar, nada es gratis.}
{212}{}{Está bien, volveré cuando deba reabastecerme. Hasta luego.}
{213}{}{Soy parte de los rangers, si me das un sorbo, estarías haciendo una buena acción.}
{214}{}{(te da una mala cara) ¿Así que estás con los Rangers? No recuerdo que ustedes nos hayan hecho algún favor. Pero los caravaneros no dejan de hablar de ustedes.}
{215}{}{[Más]}
{216}{}{Está bien. Aquí tienes un poco de agua, pero no me pidas más. Esto es un negocio, no una caridad.}
{217}{}{Gracias, te lo agradezco.}
{218}{}{¡Agua! ¡Agua! Me muero de sed...}
{219}{}{¿De verdad piensas que me voy a creer eso? Esto es patético.}
{220}{}{No olvidaré tu codicia. Algún día, lo pagarás caro.}
{221}{}{Fuera de aquí.}
{222}{}{[Hecho]}
{223}{}{Sí, no fue mi mejor actuación. Adiós.}
{224}{}{¿En serio no le darás un poco de agua a un ranger? No pido mucho.}
{225}{}{¡Agua! ¡Agua! Me muero de sed...}
{226}{}{Dios mío, ¿cuántas millas has caminado bajo este ardiente sol? Está bien, toma un poco de agua. Pero no te mueras aquí adentro.}
{227}{}{Muchísimas gracias...}
{1227}{}{Muchísimas gracias...}

{230}{}{Oye, espera un momento. Déjame verte el cuello. Vamos, muéstrame.}
{231}{}{¿De qué se trata esto?}
{232}{}{Perdona si parezco un entrometido, pero hay muchos esclavos que han escapado de Two-Sun debido a la caída de los Hojalateros. No puedo confiar en ellos, sólo quiero asegurarme de que le estoy hablando a una persona libre.}
{233}{}{Tienes agallas, ¿lo sabías?}
{234}{}{No quiero problemas.}
{235}{}{No tienes marcas de collar. Eso es bueno... para los dos.}
{236}{}{Así es. Bajo otras circunstancias, esto habría terminado mal para ti.}
{237}{}{No hay problema, lo entiendo. Todo está bien.}
{238}{}{No estoy aquí para llevarme bien contigo.}
{239}{}{Sigamos con nuestras vidas, ¿bien? Me voy, puedes darlo por hecho.}
{240}{}{Vaya, vaya, un esclavo fugitivo. ¿Qué debería hacer contigo?}
{241}{}{Supongo que nada. ¿Y si me voy?}
{242}{}{Sí, piérdete. Sal del pueblo y no vuelvas nunca.¿}
{243}{}{[Hecho]}
{244}{}{¿Quién te crees que eres? No es asunto tuyo.}
{245}{}{Ah, quien lo hubiera dicho. Tenemos un fugitivo en nuestras manos. ¿Acaso intentas arruinar mi reputación?}
{246}{}{¿Ya volviste? Te aviso que subimos el precio del agua.}
{247}{}{¿Por qué la subida?}
{248}{}{Tenemos que arreglárnoslas. La ruta de las caravanas está hecha un desastre porque los Hojalateros ya no están. Debemos acumular chapas, de lo contrario, el comercio será inútil.}
{249}{}{Comprendo.}

# Water Exchange
{250}{}{¿Necesitas agua?}
{251}{}{Estoy bien, gracias.}
{252}{}{Sí, por supuesto.}
{253}{}{Necesito reabastecerme de agua.}
{254}{}{Sí, necesito llenar mis reservas.}
{255}{}{Aquí tienes. Úsalo sabiamente.}
{256}{}{Gracias, adiós.}

{257}{}{No, necesito respuestas.}
{258}{}{Mira, yo estoy aquí para vender agua. Si tienes preguntas, háblale a mi jefe o alguien más.}
{259}{}{Está bien, adiós.}
{260}{}{Estoy rastreando a una caravana esclavista...}
{261}{}{Intento encontrar a un Hojalatero...}
{262}{}{No sé ni mierdas sobre eso. ¿Necesitas agua o no?}
{263}{}{No, sólo estoy rondando por aquí.}
{264}{}{¿Quién está a cargo de este sitio?}
{265}{}{John Sullivan. Debe estar en la sala de generadores arreglando algo, otra vez.}
{266}{}{De acuerdo, gracias.}
{267}{}{¿Cómo te las estás arreglando sin tu jefe?}
{268}{}{Me estoy haciendo cargo de todo por él. Me hizo un favor al 'renunciar'.}
{269}{}{Entiendo. Gracias.}

{270}{}{Gracias por lidiar con ese demente, ha sido un problema durante un buen rato. Ojalá que esto le sirva de advertencia a los demás.}
{271}{}{No hay problema.}
{272}{}{Eso no fue nada fácil.}
{273}{}{Te daré un poco de agua limpia. Pero no corras la voz acerca de esto.}
{274}{}{Comprendo, no diré nada.}
{1274}{}{Comprendo, no diré nada.}
{275}{}{No pierdas el tiempo con ese lunático, hace tiempo que se merecía eso. Esto le servirá de ejemplo a los demás.}
{276}{}{Este lugar es un manicomio.}
{277}{}{No sé que pensar.}
{278}{}{Si no quieres problemas, no se le cuentes a los demás.}
{279}{}{Gracias por lidiar con ese psicópata, pensé que iba a atacarme. Te daré un poco de agua. Pero, no le cuentes esto a nadie, ¿bien?}
{280}{}{¿Por qué ese tipo quería atacarte?}
{281}{}{Es mejor que no lo sepas, confía en mí. Hace tiempo, hubo una guerra de clanes para apoderarse de esta bomba de agua. Él pensaba que deberíamos compartir el agua.}
{282}{}{Algo me dice que no me estás contando todos los detalles.}
{283}{}{Uno de sus familiares murió en esa guerra... Pero como te dije, no es asunto tuyo. Y ya quedó en el pasado.}
{284}{}{Ese pasado casi termina con tu vida. Piénsalo un poco.}
{285}{}{Deberíamos enfocarnos en el futuro, no hay por qué pensar en el pasado. Cuídate.}

# Water Dealings
{300}{}{Necesito una gran cantidad de agua.}
{301}{}{No vendemos agua al por mayor a cualquiera.}
{302}{}{Entonces olvídalo.}
{303}{}{¿Qué clase de regla es esa?}
{304}{}{Debemos conservar nuestras reservas para los clientes habituales, en especial con la calor que hace.}
{305}{}{Yo también tengo un negocio. ¿Qué tal si me pones en la lista de socios?}
{306}{}{¿Un negocio, dices? Me parece que eres un vagabundo. Llévate unas botellas y estarás bien.}
{307}{}{¿Qué es esta tontería?}
{308}{}{Sabes qué, olvídalo. Por mis principios, no voy a comprar nada. Adiós.}
{309}{}{De acuerdo, el que sabe eres tú.}
{310}{}{Estoy buscando más socios comerciales. Empecemos con una orden pequeña.}
{311}{}{Hmm. Está bien. Veamos como resulta esto.}
{312}{}{No te arrepentirás, socio.}
{313}{}{¡Por el ardor de la fisión nuclear! ¿No le negarías algo a un Seguidor, verdad?}
{314}{}{Ah, ¿estás en esa iglesia? Ustedes pagan bien. De acuerdo, te agregaré a la lista.}
{315}{}{Que el Fuego Santo esté contigo.}
{316}{}{No seas así, amigo. Estamos en esto juntos. ¿Para qué necesitas reglas?}
{317}{}{No te conozco muy bien.}
{318}{}{Entonces el momento de apoyar a los lugareños. ¿Qué dices?}
{319}{}{Ja, claro. Lo que sea por ti.}
{1319}{}{Ja, claro. Lo que sea por ti.}
{320}{}{Muchas gracias.}
{321}{}{Le vendes agua a Two-Sun, a Hard no le gustará que me trates así.}
{322}{}{Ah, los caravaneros han hablado de ti, te conozco. No hay otro forastero que se haya ganado el apoyo de los Hojalateros. Está bien, hagamos negocios.}
{323}{}{No te arrepentirás de esto, socio.}
{324}{}{He arreglado el filtro de la bomba. ¿Acaso no merezco más agua?}
{325}{}{¿Así que fuiste tú? Buen trabajo, esto cambia las cosas.}
{326}{}{Entonces, véndeme cuanto puedas.}

{330}{}{Oye, escuché que dejaste tieso al líder de los Escudos Azules. ¿Es cierto eso?}
{1330}{}{Oye, escuché que dejaste tieso al líder de los Escudos Azules. ¿Es cierto eso?}
{331}{}{Oye, ¿en serio reventaste el tanque de los Escudos Azules?}
{332}{}{Sí, es cierto.}
{333}{}{¿Por qué? ¿Algún problema?}
{334}{}{Maldita sea, eres el héroe del pueblo. Si te hace falta agua, te daré un buen descuento.}
{1334}{}{Maldita sea, eres la heroína del pueblo. Si te hace falta agua, te daré un buen descuento.}
{335}{}{Lo agradezco mucho.}
{336}{}{Deberías haberlo dicho desde un principio.}
{337}{}{El mercader de agua te ofrecerá un descuento del 50% al comprar sus bienes.}
