{100}{}{Ves a un forajido veterano.}
{101}{}{Este hombre pertenece a uno de los clanes de forajidos, es un nómada de la carretera.}
{102}{}{Ten cuidado allá afuera.}

{200}{}{Gracias por ayudarme, llevaban días siguiéndome. Pero, ¿por qué me ayudaste?}
{1200}{}{Gracias por ayudarme, llevaban días siguiéndome. Pero, ¿por qué me ayudaste?}
{201}{}{Intento ayudar siempre que pueda.}
{202}{}{Ja, no te hagas el bonachón. Siempre buscamos el beneficio propio. Pero si estás dispuesto a jugarte la vida por un desconocido, no me quejo. Hmm, ¿te interesa venir a la base? Puede que nuestro jefe quiera hablar contigo.}
{203}{}{¿Base? ¿Quiénes son ustedes?}
{204}{}{Somos los Escudos Azules, nos llamamos así por las señales de tráfico en las carreteras. ¿No te suena? Ve a nuestra base, está por allá. Nuestro líder se llama Ben, habla con él.}
{205}{}{Me parece bien. Ten cuidado allá afuera.}
{206}{}{Me gustaría unirme a ustedes.}
{207}{}{¡Ja! No es una buena idea, pero si de verdad quieres, Hazlo. Los únicos que se unen son los que tocaron fondo en la "civilización". De todas formas, Ben es nuestro líder y él decide qué hacer contigo. Habla con él.}
{208}{}{Hablaré con él.}
{209}{}{Nuestra base está por allá. Habla con Ben. Cuídate.}
{210}{}{Tú también.}
{211}{}{Gracias por ayudarme, esos bastardos llevaban días siguiéndome.}
{1211}{}{Gracias por ayudarme, esos bastardos llevaban días siguiéndome.}
{212}{}{¿Por qué te seguían?}
{213}{}{Eran cazarrecompensas. A veces los contratan en Fénix o en Casa Grande para sacarnos de las carreteras, ¡pero nos pertenecen! No lo conseguirán.}
{214}{}{Ya veo.}
{215}{}{Les haré saber de ésto a Ben y a los demás. Nos vemos en la base.}
{216}{}{Ten cuidado allá afuera.}

