{100}{}{Ves a una chica.}
{101}{}{Ves a una chica del café.}
{102}{}{¡Fuera de aquí!}

{110}{}{¿Ya te vas?}
{111}{}{Toma tu tiempo, pronto sacaremos la cena del horno.}
{112}{}{¿Quieres una taza de café?}
{113}{}{Tus mejillas sugieren que necesitas proteína.}
{114}{}{Debes quedarte a probar nuestro menú.}
{115}{}{Por favor, toma un asiento y relájate.}
{116}{}{Los viajeros siempre serán bienvenidos por aquí.}
{117}{}{¿Necesitas un lugar en donde descansar?}
{118}{}{¿Gustas de un masaje?}
{119}{}{¿Te han dicho lo bien que te hicieron?}
{120}{}{¿Te cansó el viaje?}
{121}{}{Siempre es bueno ver caras nuevas.}
{122}{}{Ven, siéntate, puedes olvidarte de tus problemas.}
{123}{}{Puedes relajarte con nosotros, no te preocupes.}
{124}{}{No temas, estás a salvo con nosotros.}
