{100}{}{Ves a un colono.}
{101}{}{Ves a uno de los propietarios de la cafetería.}
{102}{}{Será mejor que te vayas, antes de que cambie de parecer.}
{103}{}{Algo me huele mal respecto a esta familia.}
{104}{}{Vaya, ese sí que está jugoso. Cariño, tráeme el cuchillo y la tabla.}
{105}{}{Sacaste la basura de la cafetería.}
{106}{}{Deberías ser más amable con tus huéspedes.}

{198}{}{Je, miren lo que tenemos aquí. ¡Esa armadura que llevas está genial! Es muy grato ver caras nuevas por estos lados. ¿De dónde vienes, forastero?}
{199}{}{Oigan, miren esto, ¡uno de esos necrófagos de más al oeste! Es muy grato ver a un... em, a una cara nueva por estos lados. ¿De dónde vienes, forastero?}
{200}{}{¡Tenemos visitas! Jeje, es muy grato ver caras nuevas por estos lados. ¿De dónde vienes, forastero?}
{201}{}{Soy de un pueblo pequeño, está lejos.}
{202}{}{No es asunto tuyo. ¿Entendido?}
{203}{}{Llevamos aquí mucho tiempo. Tenemos unos cuartos libres si necesitas un lugar donde quedarte. Y tenemos pozole en la olla. Sé que no te haría mal una probada, incluso creo que te gustará.}
{204}{}{¿Pozole...? Hm, me lo pensaré.}

{210}{}{¿Con qué te puedo ayudar?}
{211}{}{Sólo estoy descansando.}
{212}{}{¿Puedo ir a echar un vistazo por aquí?}
{213}{}{Pues, claro, pero no entres al cuarto de atrás. Es privado.}
{214}{}{Claro, no me voy a meter en donde no me llaman.}
{215}{}{Eso suena tenebroso. Lo tendré en cuenta.}
{216}{}{¿Cómo puedes vivir en un desierto tan árido?}
{217}{}{Si se quiere, se puede. Atrapamos lagartos, escorpiones y otros bichos. Y el yermo tiene más de lo que piensas, si sabes en dónde buscar. A veces los viajeros nos dejan algunos regalitos, como balas. Nos deja salir adelante.}
{218}{}{¿Ustedes viven solos?}
{219}{}{No siempre ha sido así, antes teníamos a Mamá y Papá, pero el desierto se los llevó. De vez en cuando nos llegan visitas - viajeros, caravanas. Supongo que les da curiosidad probar la comida.}
{220}{}{Es raro encontrar a alguien tan amable estos días.}
{221}{}{Así es. Al mundo ya no le queda confianza, pero es nuestra tradición. No juzgamos, y mucho menos traicionamos.}
{222}{}{Esta cafetería es muy vieja. ¿Hace cuánto que vives aquí?}
{223}{}{Lleva en la familia más tiempo del que puedo recordar. Esta cafetería tiene historias que contar hasta el último rincón.}
{224}{}{¿Por qué te importa tanto el cuarto de atrás?}
{225}{}{Es nuestro espacio privado, ahí guardamos nuestras cosas, lo normal. Allí echamos la siesta, y nos gusta que esté... tranquilo. No queremos que la gente se meta en donde no debe. Es todo lo que pedimos a cambio.}
{226}{}{De casualidad, ¿tendrás algo que podamos intercambiar?}
{227}{}{¿Que si tengo algo? Mira a tu alrededor, dime si algo te llama la atención. ¿Qué te falta?}
{228}{}{¿Aceptas chapas?}
{229}{}{¿Chapas? ¿Qué es esa babosada? Son basura y las tiré hace años. No me hagas perder el tiempo.}
{230}{}{¿Puedo preguntarte otra cosa?}
{231}{}{¿Qué tienes en mente?}
{232}{}{Nada, iré a descansar.}

{250}{}{Vaya, vaya... debería haberte puesto a dormir desde un principio. Es lo que siempre le digo a mi hermana. "No te pongas a charlar con un extraño"}
{251}{}{Siempre he pensado que no puedes confiar en la gente amable. Tenía razón.}
{1251}{}{Siempre he pensado que no puedes confiar en la gente amable. Tenía razón.}
{252}{}{¿Qué vas a saber tú?  Vivimos en medio del desierto, donde no hay nada, ni cultivos, ni animales, no hay nada más que polvo. Lo único que nos mantiene con vida son los viajeros.}
{253}{}{¿Entonces por qué no sales de aquí? Hay muchas ciudades allá afuera...}
{254}{}{¡Pffft! ¿Ciudades? ¡Ja! Esas son mentiras inventadas por idiotas. He vivido aquí toda mi vida, ¿por qué me iría buscando algo que ni debe existir? Jamás, nos quedaremos aquí.}
{255}{}{Entonces no eres más que un pendejo.}
{256}{}{Quizás lo sea, pero este pendejo ha matado a más de cien de los tuyos. Y cuando te entierre, yo seguiré aquí.}
{257}{}{No hay que llegar a los golpes...}
{258}{}{Tuviste tu oportunidad, y la arruinaste...}
{1258}{}{Tuviste tu oportunidad, y la arruinaste..}
{259}{}{¿Entonces así sobrevives? ¿Matas a viajeros y los echas a la olla?}
{260}{}{Pues esta conversación sólo llevará a una cosa, tu muerte.}
{261}{}{Voy a librar al yermo de monstruos como tu familia.}
{262}{}{Espera, estás cometiendo un error...}
{263}{}{Te estoy diciendo la verdad. Hay ciudades en el yermo, y tienen mucho espacio para tu familia. Quedarse aquí sólo resultará en tu muerte.}
{264}{}{Hm, ciudades... Los forasteros siempre están hablando de ellas. Quizás sean reales... ¿Podrías probarme que de verdad existen?}
{265}{}{Sí, pero después de esto, quiero que me dejes ir. ¿De acuerdo?}
{266}{}{Olvídalo, la gente como tú no tiene lugar en la civilización.}
{267}{}{Vaya, vaya... ¿Pero qué tenemos aquí? ¿Un ratero, no? Seguro que en las ciudades le deben cortar las manos a la gente como tú. Creo que lo voy a intentar, debe doler un chingo.}
{268}{}{Arderás en el infierno, maldito caníbal.}
