{100}{}{Ves a un fugitivo.}
{101}{}{Ves a un hombre en un traje de negocios. Está sangrando.}
{102}{}{Por favor... Ayúdame... Tengo oro... Mucho oro...}

{198}{}{(Un hombre en un traje de negocios tambalea hacia ti; enfoca sus ojos ensangrentados en tu armadura, para después demostrar una total confusión.)}
{199}{}{(Un hombre en un traje de negocios tambalea hacia ti; enfoca sus ojos ensangrentados en ti, para después echarse atrás del miedo. Está parado ante ti, a punto de desmayarse.)}
{200}{}{(Un hombre en un traje de negocios tambalea hacia ti; su cabeza sangra, y apenas puede pararse.)}
{201}{}{Estás hecho mierda, compañero.}
{202}{}{¡Dios mío, estás herido!}
{203}{}{P-por favor... Ayúdame... (cae y toma tus piernas, y agarra su traje con todas sus fuerzas) Te daré todo... Tengo oro... (cae al piso) Mucho... oro...}
{204}{}{Pero, el oro ya no vale nada... ¿Me estás escuchando?}
{205}{}{Eh... Todo estará bien, aguanta...}
