{100}{}{Ves a Harvey.}

{110}{}{¡Harvey odiar gente!}
{111}{}{¡Pelea, insectito!}
{112}{}{La gente odia a cosas como yo.}
{113}{}{¿Por qué no nos dejas en paz?}
{114}{}{¡Los normales nos siguen a todos lados!}
{115}{}{¡Los normales siempre nos disparan primero!}
{116}{}{¡Maestro, dame la fuerza para proteger este lugar de los normaluchos!}
{117}{}{Levi no quiere a los humanos en nuestra ciudad.}
{118}{}{¡Harvey protegerá la ciudad de los normales!}
{119}{}{Harvey es bueno. Harvey lo intenta, por Levi.}

{120}{}{Levi me ordenó proteger la ciudad de los humanos.}
{121}{}{Lo siento, pero no puedes quedarte.}
{122}{}{Harvey recuerda a quienes ayudaron a Levi. Harvey lo agradece.}
{123}{}{Harvey es bueno. Harvey protege la ciudad de los humanos.}
{124}{}{¿Veneras a Levi tanto como yo?}
{125}{}{¿Honras al Maestro?}
{126}{}{Extraño al Maestro...}
{127}{}{¡Harvey!}
{128}{}{}
{129}{}{}
