{100}{}{Ves a Lamont.}
{101}{}{Ves a un hombre enjuto de mirada vacía.}
{102}{}{Sal mientras puedas...}

{198}{}{¿Quién... qué? ¿Eres un robot, o un hombre? ¡Di algo! Por favor, no seas otra alucinación... ¡Y n-no toques las plantas! ¡Son peligrosas!}
{199}{}{¿Quién...? Oh, Dios mío, ¿más pesadillas? ¿Ahora hasta los segadores me atormentan? Espera, ¿puedes hablar? ¡Di algo! Por favor, no seas otra alucinación... ¡Y n-no toques las plantas! ¡Son peligrosas!}
{200}{}{¿Quién anda ahí? ¡Di algo! Por favor, no seas otra alucinación... ¡Y n-no toques las plantas! ¡Son peligrosas!}
{201}{}{Cálmate.}
{202}{}{Soy Lamont. Tengo una granja en un cañón, por aquí cerca. Mejor dicho, tenía una.}
{203}{}{¿Por qué? ¿Allá también crecieron estas plantas?}
{204}{}{Son peores que las mantis... (mira asustado a su alrededor) ¡Esas plantas están por todos lados!}
{205}{}{Son solo unas plantas rodadoras...}

{210}{}{Tenía una granja por aquí cerca, tenía.}
{211}{}{Sí, ya me lo dijiste.}
{212}{}{Ah, cierto... Ya no queda nada de mi granja, nada que valga la pena. Es mejor que te alejes. Pero no tengo a ningún otro lugar a donde irme.}
{213}{}{Un momento. Si te causan tantos problemas, ¿por qué te quedaste?}
{214}{}{Eh... curiosidad, supongo. No son como las rodadoras normales, así que me quedé mirando... pero las miré demasiado.}
{215}{}{¿Así que ya no puedes irte?}
{216}{}{No. Ni tú ni yo. Nadie puede irse.}
{217}{}{¿Estás loco...?}

{220}{}{No hay salida. Ninguna. ELLOS no lo permitirán.}
{221}{}{¿"Ellos"? ¿Quiénes?}
{222}{}{Todo empezó hace unas semanas cuando esa... "cosa", se estrelló contra el suelo.}
{223}{}{¿Cosa?}
{224}{}{No sé lo que era. Quizás un meteorito. Vi que algo brilló en el cielo, y luego se estrelló.}
{225}{}{¿Fuiste a investigar?}
{226}{}{Fui por la mañana, pero no había ni un cráter en el piso. Y ahí fue cuando empezó.}
{227}{}{Sigue hablando.}
{228}{}{Al principio no me preocupé, pensé que de repente las rodadoras se habían hecho más grandes. Y luego... empezaron a actuar como si estuvieran vivas. Bloquearon el camino y me agarraron la pierna cuando intenté irme. No lo he vuelto a intentar...}
{229}{}{Hmm.}
{230}{}{Sal mientras puedas, todavía puedes escapar. ¡Corre!}
{231}{}{Hmm...}