{100}{}{Ves a Paul.}
{101}{}{Ves a un hombre muy desnutrido.}

{198}{}{¡Vaya! ¿Un paladín, aquí adentro? Espera... ¿en dónde conseguiste esa armadura? Bueno, como sea que hayas llegado aquí, ten cuidado, los mutantes te matarán si te ven.}
{199}{}{¡Vaya! ¿Un segador...? No, debes ser un necrófago... ¿cómo entraste aquí? Este sitio no es para los de tu tipo. Los mutantes te matarán si te ven.}
{200}{}{¿¡Qué!? ¿Cómo entraste aquí? No deberías quedarte, los mutantes te matarán si te ven.}
{201}{}{¿Te dejaron con vida, no? ¿Quién eres?}
{202}{}{Lo sé, así que cierra la boca y no hagas ruido.}

{210}{}{Te estás arriesgando.}
{211}{}{No cuentes conmigo si te atrapan.}
{212}{}{¿Por qué sigues aquí?}
{213}{}{¿Qué tal?}
{214}{}{Todavía tienes tiempo de salir de aquí.}
{219}{}{Nos vemos.}

{220}{}{¿Quién eres?}
{221}{}{Me llamo Paul. Me encargo de que la plataforma siga funcionando.}
{222}{}{Eso es impresionante. ¿Cómo sabes qué tocar para hacer funcionar esta tecnología?}
{223}{}{No te creo. Nadie sabe cómo operar tecnología tan vieja.}
{224}{}{Pues, soy un ingeniero. Me entrenaron para esto durante toda mi vida.}
{225}{}{¿En serio? ¿En dónde te entrenaron?}
{226}{}{¿Has oído de la Hermandad del Acero? Es una orden antigua y soy un Caballero, por lo que saber de tecnología es lo mío. A pesar de que me especializo en armas de energía, tuve que aprender cómo operar esta cosa a la fuerza .}
{227}{}{Hace poco que me uní a la Hermandad. Encantado de conocerte, hermano.}
{1227}{}{Hace poco que me uní a la Hermandad. Encantada de conocerte, hermano.}
{228}{}{Te creeré, no es que pueda llevarte la contraria. Pero en nuestra historia, hemos admitido a una sola persona en la Hermandad, y sus hazañas eran... legendarias, para ser honestos.}

{230}{}{¿Cómo acabaste aquí?}
{231}{}{Fui capturado por supermutantes cerca de Necrópolis. Primero me quisieron matar, pero al descubrir que era un ingeniero me dejaron vivir para que los ayudara con este lugar. Desde ese día he sido un prisionero.}
{232}{}{¿Necrópolis? ¿En dónde queda eso?}
{233}{}{Está en California, no me sorprende que no lo sepas; estamos lejos de allá.}
{234}{}{Háblame acerca de la Hermandad del Acero.}
{235}{}{Durante muchos años, nos mantuvimos en nuestro búnker, pero cuando California estaba en riesgo de una invasión mutante, tuvimos que actuar. Derrotamos a su ejército gracias a la valentía de nuestros hermanos y hermanas, por lo que estamos cazando a los supervivientes.}
{236}{}{Pero si estaban dentro del búnker, ¿cómo descubrieron al ejército enemigo?}
{237}{}{Para serte honesto, un desconocido nos ayudó. Después de eso, hicimos de él un iniciado. Fue el que saboteó su base principal en Mariposa. Pero oficialmente, la Hermandad tiene el crédito de acabar con el ejército en sí. Es justo, considerando las batallas que se libraron.}
{238}{}{Odio a la Hermandad, ustedes no son más que unos invasores codiciosos.}
{239}{}{No eres la primera persona que piensa eso - y no serás la última. Pero si no hubiera sido por nosotros, el yermo no tendría ninguna oportunidad para amenazas como los supermutantes o los garras mortales. La Hermandad es necesaria, te guste o no.}

{240}{}{¿Sabes hacia dónde se dirigen los supermutantes?}
{241}{}{Ni siquiera ellos mismos lo saben. El capitán les prometió encontrar una tierra próspera en donde construir un estado para los mutantes.}
{242}{}{¿Has intentado escapar?}
{243}{}{Ya perdí esa oportunidad, hay desierto por todos lados, me atraparían tarde o temprano. Incluso si fuera a salir corriendo, no sería capaz de llegar a Lost Hills. Ni siquiera sé en dónde estamos.}
{244}{}{Nos encontramos en el Desierto de Sonora.}
{245}{}{¿Sonora? Quizás no todo está perdido. Sé que tenemos un puesto avanzado en Rocky Point... Creo que ustedes le llaman Puerto Peñasco. Ellos me ayudarán.}
{246}{}{¿Entonces qué estamos esperando?}
{247}{}{Primero, tenemos que desactivar esta plataforma. Hay un reactor en el nivel inferior, es como el 'corazón' de la base. Si lo desactivas, la plataforma dejará de funcionar por completo.}
{248}{}{Me ocuparé de ello.}
{249}{}{El reactor fue desactivado.}

{250}{}{El reactor está muerto, es hora de salir de aquí.}
{251}{}{Como ingeniero, me duele ver algo tan complejo ser destruido. Pero tenía que hacerse. Los mutantes no podrán repararlo, y aquí afuera, no significan un peligro para nadie.}
{252}{}{Vámonos.}
{253}{}{No hagas ruido...}
{254}{}{Es hora de escapar.}
{255}{}{Ya eres libre.}
{256}{}{No sé cómo llegaré con mis hermanos en Rocky Point, tengo que recordar todo lo que me enseñaron en Lost Hills. Gracias, si sobrevivo, le diré a la Hermandad lo que hiciste por mí.}
{257}{}{Ten un buen viaje.}
{258}{}{Lo siento, pero no puedo dejarte ir. La Hermandad es malvada, y tengo que matarte... ¡Sufrirás el mismo destino que tus amigos en Puerto Peñasco!}
{1258}{}{Lo siento, pero no puedo dejarte ir. La Hermandad es malvada, y tengo que matarte... ¡Sufrirás el mismo destino que tus amigos en Puerto Peñasco!}
{259}{}{Los mutantes están muertos. Puedes irte.}
{260}{}{Eso es impresionante, esta cosa no llegará lejos sin gente adentro. Sí que sabes lo que haces, nos habría venido bien gente como tú durante la Gran Guerra Mutante.}
{261}{}{Vámonos de aquí.}
