{100}{}{Ves a un mutante.}
{101}{}{Ante ti se encuentra un supermutante, es inmenso.}
{102}{}{ }

{120}{}{¡Por el Maestro!}
{121}{}{No me mires, odio cuando hacen eso.}

{150}{}{¿Nosotros ya llegar a Tejas?}
{151}{}{No, el Capitán decir que seguir en Arizona.}
{152}{}{¡Arrr! Ser más lentos que necrófago sin patas y cuchillo en el culo.}
{153}{}{No poder ir más rápido, ser malo para la fortaleza.}
{154}{}{¡Yo no querer esperar! Capitán prometer conquistas y batalla gloriosa.}
{155}{}{¿Tú recordar por qué irnos de Mariposa?}
{156}{}{Recodar. No ser estúpido. Pero a Maestro no le gustaría esto.}
{157}{}{Eso ser cierto. Pero Maestro ya no estar...}
{158}{}{¡Grrr! ¡Tener que haber peleado, no correr!}
{159}{}{Demasiados haber morido. El Capitán saber lo que hace.}
{160}{}{Sí, Capitán estar a cargo. ¡Pero yo querer ser capitán!}
{161}{}{¿Y qué pensar hacer tú?}
{162}{}{Yo volver y aplastar Lost Hills. Y aplastar toda ciudad de camino.}
{163}{}{Por eso tu no ser capitán. El capitán ser inteligente. Tú ser tonto.}
{164}{}{¡Tú callarte! ¡Yo no ser tonto!}
{165}{}{Eso estar bien, el Capitán arreglar tu cerebro a golpes.}
{166}{}{¡Grr!}
