{100}{}{Ves a un esclavo, sus ojos están repletos con la desesperación.}
{101}{}{Ves a un esclavo. Sus manos son un desastre ensangrentado de callosidades, los moretones cubren sus hombros por las cuerdas que una vez lo ataron.}
{102}{}{Parece ser incapaz de hablar, debe haber perdido la voz al gritar tanto.}

{110}{}{O-oh...}
{111}{}{Agh...}
{112}{}{Eh...}
{113}{}{No...}
{114}{}{¿Qué?}
{115}{}{Aléjate de mí.}
{116}{}{No me hables.}
{117}{}{Quiero que me disparen.}
{118}{}{}
{119}{}{}