{100}{}{Ves a un escriba.}
{101}{}{Ves a uno de los escribas de la Hermandad del Acero.}
{102}{}{Muchas gracias.}

{200}{}{Muchas gracias por ayudarme. Los saqueadores querían sacarme información sobre la Hermandad. Pero gracias a ti, no pasó nada.}
{201}{}{¿Qué clase de Hermandad?}
{202}{}{Ah, así que no sabes. La Hermandad es una vieja orden dedicada a preservar y estudiar tecnología del Viejo Mundo. Nuestra base está localizada en un viejo puerto, entre las ruinas de Puerto Peñasco.}
{203}{}{Ya veo.}
{204}{}{Gracias por salvarme. Cuando vuelva a la base, me aseguraré de mencionarte.}
{205}{}{Genial. Nos vemos.}
{206}{}{Eres un hermano, no podía dejar que te pasara eso.}
{207}{}{¿¡Eres de la Hermandad!? ¡Te voy a matar!}
