{100}{}{Ves a un cíborg.}
{101}{}{Ves a un Hojalatero cuya mente ha sido corrompida por la tecnología.}

{110}{}{Error de sistema... ¡Qué dolor de cabeza!}
{111}{}{¡Error! ¡Basta con los números! ¡No aguanto más!}
{112}{}{¿Por qué? ¿Por qué? ¿Por qué?}
{113}{}{Hay números en todos lados... ¡Sólo hay datos!}
{114}{}{Directiva: Eliminar al objetivo.}
{115}{}{Soy una máquina. Soy una máquina. No soy humano...}
{116}{}{¡La voz en mi cabeza está irrumpiendo el programa!}
{117}{}{No soy más que una variable en un enorme algoritmo. ¡No interfieras!}
{118}{}{¡Corrompiste mi programa!}
{119}{}{¡Mereces que te borren de la base de datos!}
