{100}{}{Ves al cliente de un bar. Está nervioso y un poco borracho.}
{101}{}{Ves a un colono, está nervioso y bebe una cerveza. Parece que el alcohol hace su trabajo.}
{102}{}{¡Atrás!}
{103}{}{¡Basta, es suficiente! ¡Soy el malo, es todo mi culpa!}
{104}{}{Ah, sí que tienes potencial.}
{105}{}{Digamos que fue un empate.}
{106}{}{Creo que tuviste una buena derrota, tráeme una bebida.}
{107}{}{Parece que nos quieres presumir tu armadurita brillosa.}

{200}{}{¡Tú! No te conozco. ¿No eres de aquí, cierto? Entonces tráeme un trago, rápido.}
{201}{}{¿Y por qué debería hacer eso?}
{1201}{}{¿Y por qué debería hacer eso?}
{202}{}{Mira, no quiero problemas. Déjame en paz.}
{1202}{}{Mira, no quiero problemas. Déjame en paz.}
{203}{}{Muérete.}

{204}{}{¡Porque ves a la personificación del poder y el orden en esta ciudad! Yo trabajo para Roy Faber. Así que cómprame una cerveza, o te las verás conmigo.}
{205}{}{No quiero tener problemas, aléjate de mí.}
{206}{}{Perro que ladra no muerde. Hace tiempo que no te dan una golpiza, ¿verdad?}

{207}{}{¡Ya! Pueblerino estúpido, sal corriendo de aquí si tienes cerebro. Esta ciudad no es lugar para gente como tú.}
{1207}{}{No voy a tocar a una niña pueblerina como tú. Vete, vuelve a tu pueblo.}
{208}{}{Ya, ya. Tú eres el que manda.}
{209}{}{Eres un maleducado, así que si querías una pelea, yo te la voy a dar.}

{210}{}{¿Cómo? ¡Eres un bocazas! ¡Tienes mierda por cerebro! Me las vas a pagar...}
{211}{}{Bueno, pero en la cara no...}
{212}{}{Sorpréndeme.}

{213}{}{Yo también trabajo para él, así que cierra la boca.}
{214}{}{(rechina los dientes) Mierda... (vuelve a mirar la botella, con tristeza en su rostro)}
{215}{}{Quédate ahí, idiota.}

{216}{}{¡Faber murió! ¿Me escuchaste? ¡Está muerto!}
{217}{}{Ya, ya lo entendí. Con calma...}
{218}{}{Sí que eres un ganador. Golpeas borrachos porque eres un lacayo, y nada más.}
{219}{}{No, o sea... Yo... Yo... ¡Vete a la mierda!}

{220}{}{¿Qué te pasa?}
{221}{}{Nada.}
{222}{}{Eso pensaba.}
{223}{}{Piérdete.}
{224}{}{Será un placer.}
{225}{}{¡Aléjate de mí!}
{226}{}{No, claro que no.}
{227}{}{Ustedes secuestraron a mis parientes de la Villa. Necesito que me ayudes a liberarlos.}
{228}{}{¿¡Cómo!? No puedes hacer eso, Faber jamás dejaría ir prisioneros así como así. ¿Y planear una fuga? Es imposible. Lo único que harás será matarlos a todos.}
{229}{}{¿Por qué sería imposible?}
{230}{}{Aunque pueda fugarse un prisionero, los collares acabarán con ellos. Podrán saborear la libertad por un rato, y luego... ¡Boom! Adiós cabeza.}
{231}{}{Eso es horrible...}
{232}{}{Los collares se deshabilitan en la estación de radio, pero sólo dos personas saben hacer eso: Faber y el cerebrito. Así que sería imposible, o casi imposible.}
{233}{}{Entonces, haré lo que sea necesario cuando llegue el momento.}
