{100}{}{Ves a un niño.}
{101}{}{Ves al hijo de algún colono.}
{102}{}{¡Les diré a todos lo que hiciste!}
{103}{}{Z-z-z...}
{104}{}{Está por allá en la entrada, en medio de las ruinas.}

#Response
{110}{}{¡Hola!}
{111}{}{¿Quieres jugar conmigo?}
{112}{}{Te ves amigable.}
{113}{}{No tengo nada mejor que hacer.}
{114}{}{No me dejan ir a las ruinas.}

{1110}{}{¡Hola!}
{1111}{}{¿Quieres jugar conmigo?}
{1112}{}{Te ves amigable.}
{1113}{}{No tengo nada mejor que hacer.}
{1114}{}{No me dejan ir a las ruinas.}

{115}{}{¡No te me acerques!}
{116}{}{Me dijeron que no te hable.}
{117}{}{¡Eres malo!}
{118}{}{Déjame en paz o voy a gritar.}
{119}{}{¿Es cierto que comes bebés?}

{120}{}{Hola.}
{121}{}{Hola.}
{122}{}{Hola.}
{123}{}{Hola.}
{124}{}{Hola.}

{200}{}{H-hola. ¿Buscas a alguien?}
{201}{}{No, a nadie, cálmate.}
{202}{}{Sí, busco a unos pequeños ladrones.}
{203}{}{¡No robamos nada! ¡No fuimos nosotros!}
{204}{}{¿En serio?}
{205}{}{Sí... en serio...}
{206}{}{Sé que robaste las cosas de la señorita Brandley. Pero no temas, no le diré a nadie.}
{207}{}{Queríamos... Queríamos ayudar a Papá. No tiene dinero para pagar la cosa y puede que nos echen. Y esa vieja fea siempre tiene chapas. Pero no tenía casi nada en su monedero.}
{208}{}{¿En dónde dejaste sus cosas?}
{209}{}{Deja de mentirme o las cosas se pondrán feas, niño.}
{210}{}{Las tiramos en las ruinas en la entrada de la ciudad. Habían algunas notas de amor, y unas cuentas... No le dirás a nadie, ¿cierto? Solo queríamos ayudar a Papá. ¡No volverá a suceder!}
{211}{}{No te preocupes, lo entiendo.}
{212}{}{¿Cuántas chapas encontraste en su monedero? Dámelas y te perdonaré.}
{213}{}{Aquí tiene, señor... Eran cinco chapas.}
{1213}{}{Aquí tiene, señor... Eran cinco chapas.}
{214}{}{Muy bien, adiós.}
