{100}{}{Ves a un colono.}
{101}{}{Ves a un ciudadano de la colonia.}
{102}{}{Tengo sueño, déjame en paz.}
{103}{}{Z-z-z...}
{104}{}{...}
{105}{}{ }
{106}{}{*Bostezo*}
{107}{}{¿De dónde eres?}
{108}{}{Tengo sueño, déjame dormir.}

#Floating remarks (they are responses when you try to speak)
{110}{}{¿Sabías que hay toque de queda? No puedes salir a la calle si es de noche.}
{111}{}{Estás en la ciudad más segura de Arizona.}
{112}{}{A veces extraño cómo se veían las luces de Fénix por las noches.}
{113}{}{Me entran escalofríos cuando miro a Faber.}
{114}{}{Dicen que hay saqueadores en las ruinas hacia el este.}
{115}{}{¿Cuándo llegará la siguiente caravana?}
{116}{}{Jamás confíes en los sirvientes.}
{117}{}{Me da miedo ir a la guarnición.}
{118}{}{No te olvides ir al sermón de la tarde.}
{119}{}{Los impuestos son altos, pero vale la pena.}
{120}{}{¿Has ido al Pico de Humphreys? La vista es hermosa.}

{150}{}{Me da miedo salir a la calle.}
{151}{}{Hasta un nido de escorpiones es más seguro que este lugar.}
{152}{}{No debería haberme mudado aquí.}
{153}{}{¿Cómo pudimos confiar en Faber?}
{154}{}{Dicen que hay saqueadores en las ruinas hacia el este.}
{155}{}{Hay menos caravanas que nunca.}
{156}{}{¿Contratarías a una sirvienta? Yo no.}
{157}{}{No iré a la guarnición, de ninguna manera.}
{158}{}{Deberíamos dejar que el pastor le hable a los saqueadores.}
{159}{}{¿Para qué pagamos impuestos?}
{160}{}{Apenas empiecen los problemas, me iré corriendo al Pico de Humphreys.}
