{100}{}{Ves a Joshua, el mercader.}
{101}{}{Estás viendo al gerente de la caravana. Su piel está bronceada gracias a sus interminables viajes bajo el sol.}
{102}{}{Ojalá que tengas un buen viaje.}
{103}{}{Estás en Fénix, la ciudad más grande del yermo. No bajes la guardia, nunca.}

{200}{}{¿Qué pasó ahora?}
{201}{}{Adiós.}

#First dialogue
{210}{}{¿Buscas a alguien?}
{211}{}{Puede ser. ¿Quién eres?}
{212}{}{Sí, pero no creo que esté acá. Adiós.}
{213}{}{En caso de que busques trabajo, no te puedo ayudar. Sólo tratamos con la administración de la mina.}
{214}{}{Y, ¿a qué te dedicas?}
{215}{}{Nos encargamos de transportar carga pesada. ¿Por qué preguntas?}
{216}{}{Nada, sólo pregunto.}
{217}{}{Nada.}
{218}{}{¿Tienes un minuto? Quiero saber más de tu trabajo.}

#Questions
{220}{}{Adelante. ¿Qué quieres saber?}

{221}{}{¿Cuál es la ruta de tu caravana?}
{222}{}{Nuestro destino es la ciudad de Fénix en el sur. Por el camino, revisamos las paradas pequeñas por la Ruta 17 y pasamos al lado de San Brahmán.}
{223}{}{Háblame sobre San Brahmán.}
{224}{}{Es un pueblo que puedes encontrar de camino a Fénix, los lugareños suelen pastorear ganado y ven a los forasteros como los compradores de brahmanes.}
{225}{}{Háblame acerca de Fénix.}
{226}{}{Es la ciudad más grande que conozco. Todo lo que encontrarías en el yermo, lo puedes encontrar ahí, pero debes tener cuidado. La ciudad no es segura, el hecho de que los Seguidores del Fuego se hayan apoderado de la ciudad no ha cambiado eso.}
{227}{}{Nuestra ruta es hacia el sur. ¿Por qué debería contarte más?}
{228}{}{¿Seguidores del Fuego?}
{229}{}{Son gente extraña. Adoran a la energía atómica de la preguerra - eso es lo que entendí. Eran demasiadas palabras y no me entraron en la cabeza. Pero que eso no te engañe - Fénix se transformó en una ciudad de verdad gracias a su control.}

{230}{}{¿Qué clase de carga estás llevando?}
{231}{}{Uranio. Lo extraen de esta mina.}
{232}{}{¿Quién lo necesita?}
{233}{}{Cualquiera que tenga maquinaria que funcione con energía nuclear. Pero los Seguidores en Fénix compran el uranio y luego lo venden a compradores pequeños a un precio cinco veces más alto.}
{234}{}{Pero, el uranio causa envenenamiento radiactivo, ¿no?}
{235}{}{Sí... si te lo comes para el desayuno, almuerzo y la cena. El mineral es inofensivo y apenas radioactivo hasta que refinan y lo colocan en el reactor. En ese entonces es mejor alejarse lo máximo posible.}

{236}{}{¿Te das cuenta de que la gente a la que ayudas son esclavistas?}
{237}{}{¿Estás hablando de Faber y sus mercenarios? No me importa. Yo y mis chicos necesitamos un trabajo, la colonia nos da un trabajo y un sueldo. Eso es suficiente para mí.}
{238}{}{Te pagaré 30 chapas.}
{239}{}{Bueno, eso cambia las cosas.}
{240}{}{Cuéntame más.}
{241}{}{Con esos bolsillos, no te daría ni la hora.}
{242}{}{Ay, parece que se me cayeron...}
{243}{}{Un culto local que adora a la energía atómica. Es cierto que quedó poco de ellos tras la destrucción de su templo. Sea como sea, Fénix se transformó en una ciudad de verdad bajo su control.}

#Amendments for emergency situations
{250}{}{...Ya te dije que no iremos a ningún lado... Espera, no eres parte de la administración, ¿verdad? Olvida lo que dije.}
{251}{}{¿Hay un problema con la caravana?}
{252}{}{¿No sabes qué pasó? La mina se fue al traste, igual que nosotros.}
{253}{}{¿Qué le pasó a la mina?}
{254}{}{Adiós.}
{255}{}{La mina fue destruida, despejarla llevará mucho tiempo y esfuerzo. Dudo que este lugar tenga un futuro.}
{256}{}{En Fénix, enviaron a los Seguidores con su dios y la mina perdió a su principal cliente. Es obvio que todavía hay una demanda por el mineral, hay asentamientos dispuestos a comprarlo, pero no es suficiente para mantener a la mina a flote.}
{257}{}{Exterminaron a la guarnición de Flagstaff, los prisioneros escaparon y el capataz está muerto. Ya ni siquiera sabemos por quién estamos trabando. Parece que ya nadie necesita nuestros servicios.}
{258}{}{Pero ustedes son caravaneros, ¿de verdad les importa por quién están trabajando?}
{259}{}{No, pero a los demás sí. Debido a nuestra conexión con los Seguidores y los mercenarios de Faber, no habrá mucha gente que quiera tratar con nosotros. Nuestros competidores siempre nos tuvieron envidia. Si establecemos rutas nuevas, será muy difícil, si es que es posible en primer lugar.}
{260}{}{¿Entonces no saldrán de aquí?}
{261}{}{Exacto. Debemos quedarnos en Flagstaff hasta que las cosas mejoren. No sabemos qué hacer, pero ya se nos ocurrirá algo.}

#Journey to the South
{300}{}{Oye, vamos al mismo sitio. ¿Puedo ir con ustedes hacia Fénix?}
{301}{}{No solemos traer gente con nosotros, nuestros clientes prefieren que la caravana esté segura.}
{302}{}{¿Al menos me puedes responder unas preguntas?}
{303}{}{Me parece justo.}
{304}{}{Fénix no es un lugar muy simpático, ahí dejan gente colgada en las farolas. Todavía estamos pensando en qué hacer.}
{305}{}{Parece que estás en una situación difícil.}
{306}{}{Tienes suerte de que no estamos en Fénix, ahí sí que no soportan a los estafadores.}
{307}{}{Eh, claro.}

{310}{}{¿Te convencerán unas 500 chapas?}
{311}{}{De acuerdo, si me pagas 500 podrás unirte a la caravana. Pero hay reglas.}
{312}{}{Claro, aquí tienes. ¿Qué reglas tienes?}
{313}{}{Quizás otro día.}
{314}{}{}
{315}{}{Me parece bien. No eres alguien común, así que haré una excepción. Pero hay reglas.}
{316}{}{¿Cuáles son tus reglas?}
{317}{}{Quizás otro día.}
{318}{}{Mis experiencias me ha enseñado que no debo confiar en los desconocidos.}
{319}{}{Ya veo. Adiós.}

{320}{}{Primero, tu equipaje no puede pasar de las 50 libras. Segundo, vamos a pasar la noche en San Brahmán antes de ir a Fénix. ¿Te parece bien? Si es así, háblame al tener todo listo.}
{321}{}{Suena bien. Voy a prepararme.}
{322}{}{Pero te vendría bien tener un par de manos extra. ¿No puedo ir a su lado y ya?}
{323}{}{Una ayuda más en la carretera no es algo que deberías dejar pasar.}

{330}{}{Me gustaría unirme a la caravana.}
{331}{}{No pondremos a la caravana en riesgo con tu equipaje. Tira la basura que tengas y hablamos.}
{332}{}{¿En serio traerás todo eso? Lo siento, pero eso nos hará viajar más lento. Trae 50 libras o menos.}
{333}{}{De acuerdo, llevaré menos cosas.}
{334}{}{Yo me encargaré de mis cosas, no retrasaré la caravana.}
{335}{}{Antes de viajar, tengo algunas preguntas.}
{336}{}{De acuerdo, pero nadie cuidará tus cosas ni te vamos a esperar. Si te quedas atrás, es cosa tuya.}
{337}{}{No hay problema.}
{338}{}{(Después de pasar la noche con los guardias, te diriges al sur)}
{339}{}{[Empieza el viaje]}

#Other locations
{400}{}{Vamos a pasar el día aquí. Puedes ir a explorar, pero recuerda que no te vamos a esperar si te atrasas.}
{401}{}{¿Qué puedes decirme de San Brahmán?}
{402}{}{Es una ciudad de pastores de brahmán. Son cautelosos con los forasteros, pero siempre están dispuestos a comerciar. Recuerda que si quieres hacer un trato con ellos, debes comportarte.}
{403}{}{Me aseguraré de estar aquí a tiempo.}
{404}{}{[Espera hasta que la caravana vaya hacia Fénix]}
{405}{}{Váyanse sin mí, podré llegar por mi cuenta.}
{406}{}{Cuídate.}
{407}{}{Tú también. Hasta luego.}
