{100}{}{Ves a Randy.}
{101}{}{Ves a un granjero, puedes notar la mugre en su piel. Su hedor es muy fuerte.}
{102}{}{Están por allá, ten cuidado.}
{103}{}{Estoy feliz de verte, pero debo seguir trabajando.}

#Dialogue - on the city map
{200}{}{(al mirar sus ojos, notas que están llenos de tristeza) Hola, forastero. Si me vas a robar, te diré de inmediato que no tengo nada.}
{1200}{}{(al mirar sus ojos, notas que están llenos de tristeza) Hola, forastera. Si me vas a robar, te diré de inmediato que no tengo nada.}
{201}{}{Eso es lo que siempre dicen. Muéstrame lo que tienes.}
{202}{}{Lo digo en serio, no tengo nada. Unos saqueadores me sacaron de mi propio hogar. Así que me dejaron pobre y sin mi casa.}
{203}{}{Agh, con sólo verte me dan ganas de vomitar.}
{204}{}{Siento oír eso. Tengo unas preguntas que hacerte.}
{205}{}{Estás muy tenso. No te preocupes, no quiero hacerte nada.}
{206}{}{Lo siento, perdí la confianza en los demás luego de que unos saqueadores me quitaron mi granja. Ahora no tengo ni dinero, ni hogar.}
{207}{}{Eso es muy triste. ¿Puedo sentarme contigo?}
{208}{}{Entonces no me sirves. Deja de chillar, perdedor.}
{209}{}{No tengo más peguntas.}
{210}{}{¿Sí?}
{211}{}{No es nada. Adiós.}
{212}{}{¿Quién eres?}
{213}{}{Me llamo Randy. Llegué a Flagstaff junto a los demás colonos hace unos años y establecí una pequeña granja, estaba alejado de los demás. Dudo que te importe saber el resto.}
{214}{}{Entonces, ¿te arrebataron tu hogar?}
{215}{}{Sí, esos idiotas saben cómo tender una emboscada. En un abrir y cerrar de ojos, me habían atrapado. Registraron la casa entera buscando comida, después me corrieron de mi hogar y dijeron que ya no me pertenecía.}
{216}{}{¿Has intentado sacarlos de ahí?}
{217}{}{Un granjero contra tres saqueadores no va a terminar bien. Es mejor perder una casa que tu vida.}
{218}{}{¿Por qué no pedirle ayuda a la guarnición?}
{219}{}{Porque entonces tendría que darles casi toda mi cosecha durante diez años, esas son sus condiciones. Pero mi granja apenas puede alimentar a un par de personas, nadie más.}
{220}{}{Puedo encargarme de los saqueadores, a cambio de comida.}
{221}{}{Tu historia es similar a la mía. Quiero ayudarte.}
{222}{}{Háblame de ti.}
{223}{}{Entonces, ¿los saqueadores se apoderaron de tu casa?}
{224}{}{Sí, claro. La granja no tiene mucha comida disponible, y en todo caso, se la comerá alguien más.}
{225}{}{Llévame hacia allá..}
{226}{}{Es una buena oferta, pero no quiero meterme con ellos.}
{227}{}{¿Así que los sacarás de ahí? Eso sería de gran ayuda, ojalá que sepas cómo defenderte, porque no será nada fácil hacerlo por las buenas.}
{228}{}{Ya se me ocurrirá algo. Vamos.}
{229}{}{Tienes razón, esto es demasiado para una sola persona. No puedo ayudarte, lo siento.}

#Dialogue - on the farm map
{300}{}{Están allá adentro, ten cuidado.}
{301}{}{Espérame aquí.}

{310}{}{¿Así que esta es tu granja?}
{311}{}{Por supuesto. Ese es mi hogar y ese es mi huerto.}
{312}{}{¿Vives sólo?}
{313}{}{Sí, desde hace poco. Antes éramos más, pero a uno lo mataron unos ladrones que querían la cosecha, otro murió por una infección. Así que me quedé sólo, pero eso no importa, no quiero irme de aquí.}
{314}{}{¿Por qué te importa tanto la granja? Hay muchos terrenos y casas abandonadas en los alrededores.}
{315}{}{¡Porque la granja es fértil gracias a nuestro sudor y sangre! Me esforcé mucho trabajando en ella para dársela a unos bandidos. De todas formas, algún día saldrán de ahí.}
{316}{}{¿Qué hay del cartel de la entrada? Dice 'Hermanos Morrison'.}
{317}{}{(confundido) Morrison... No importa. Ese cartel debe tener unos cien años. ¡Ahora, la granja es mía!}
{318}{}{¿Sabes algo al respecto de los saqueadores?}
{319}{}{Ellos vivían aquí antes de que llegáramos nosotros. Son unos salvajes, nada más. No pudieron adaptarse a su nueva vida, pero sí aprendieron a robarnos. Los guardias de la guarnición expulsaron casi a todos, pero este grupo resultó ser el más resistente.}
{320}{}{No me habías contado ese detalle.}
{321}{}{¿Y qué? Escúchame, son saqueadores. Lo único que hacen es llevarse lo que no les pertenece. Eso es todo lo que importa.}

{350}{}{Ya están muertos, Randy. Puedes volver a casa.}
{351}{}{No puedo creerlo, lo conseguiste. Hm, me vendría bien alguien como tú... ¿No quieres venirte a vivir conmigo?}
{352}{}{Yo también tengo un hogar, y está en peligro.}
{353}{}{¿A esta pocilga? Ni en tus sueños, en mi pueblo tenemos huertos mucho más grandes.}
{354}{}{Pues, si eso quieres... Lo entiendo. Gracias por la ayuda, buena suerte.}
{355}{}{No tan rápido, entrégame toda la comida que tengas.}
{356}{}{De nada. Adiós.}
{1356}{}{De nada. Adiós.}
{357}{}{Claro, debí adivinarlo. Un ladrón se jode al otro y el ciclo continua. Algunas cosas nunca cambian, ¿no? Puedes llevarte lo que haya en el refrigerador.}
{358}{}{Gracias, sé que la cosecha estará fresca.}
{359}{}{No volverán a molestarte, puedes volver a casa.}
