{100}{}{Ves al operador de la máquina.}
{101}{}{Ves al operador de la máquina procesadora.}

# Dialogue
{200}{}{(no aparta la vista de su trabajo) ¿Eh? ¿Qué quieres?}
{201}{}{Nada.}
{202}{}{(sigue trabajando) No me hagas perder el tiempo, habla.}
{203}{}{Adiós.}
{204}{}{Espera, tengo más preguntas.}

{210}{}{Cuéntame acerca de tu trabajo.}
{211}{}{¿Qué puedo decirte? Agarro el mineral, lo pongo en la máquina, la cual lo tritura y lo limpia. El mineral purificado entra en la máquina de flotación y el resto son desperdicios. Eso.}
{212}{}{¿Para qué purificas el mineral?}
{213}{}{El uranio no debe contener impurezas; si las contiene, no otorga la energía necesaria. Para serte honesto, no entiendo la maquinaria por completo.}
{214}{}{¿Siquiera es seguro trabajar con el uranio?}
{215}{}{Si te refieres a la radiación, no es ningún problema hasta que purificas el mineral. Lo que sí es peligroso, es herirte con esta vieja y estúpida máquina.}

{220}{}{¿De dónde vino toda la maquinaria?}
{221}{}{Son lo que quedó del Viejo Mundo. Aunque son pequeñeces comparado con la maquinaria que tenían puesta acá en ese entonces.}
{222}{}{¿Así que en la preguerra también minaban y procesaban el uranio?}
{223}{}{Sí, los túneles están bien conservados, pero algunas máquinas y los edificios están desbaratados por completo.}
{224}{}{Tiene que haber algo más grande detrás de todo esto, ¿no lo crees?}
{225}{}{¿Eh? ¿De qué estás hablando?}
{226}{}{Estaba pensando en voz alta, olvídalo.}
{227}{}{Piénsalo, ¿por qué alguien vendría y arreglaría estas máquinas, así sin más? ¿Quién tiene el conocimiento para hacer eso?}
{228}{}{Tienes razón. Han dicho que antes de crear la colonia, Faber trajo a algunos tipos que repararon y configuraron las máquinas. Después de eso decidió traer a gente acá y empezar a trabajar. Nadie de estos lados sabe hacer algo así.}
{229}{}{Eso es muy interesante. Tengo otras preguntas.}

{230}{}{¿Estás aquí por voluntad propia?}
{231}{}{Sí, pero es porque no tengo a ningún lado a donde ir, por lo que estoy dispuesto a ser esclavo.}
{232}{}{¿Qué opinas de la esclavitud?}
{233}{}{No sé, puede que esté mal obligar a otros a trabajar por ti. Pero todos estamos metidos en el mismo problema.}

{240}{}{Han colapsado la mina, ¿qué harás ahora?}
{241}{}{No lo sé, haré lo que me digan. No tengo ningún otro lugar a donde irme.}
{242}{}{Látigo no volverá a molestar a nadie. Ve a mirar afuera.}

{250}{}{¿Es normal que el capataz golpee a los prisioneros?}
{251}{}{(suspira) Ese Látigo... es un psicópata. Se desquita con todos, conmigo igual, pero no tanto. Ojalá pudiera deshacerme de él, pero Faber es el que escoge a los guardias.}
{252}{}{¿Qué hay del administrador? ¿No puede hacer nada al respecto?}
{253}{}{No sé por qué te digo esto, pero Látigo lo obliga a reescribir sus informes, así queda registrado que los trabajadores se hirieron durante un derrumbe o tuvieron un accidente. No debe querer que su reputación se arruine, pero también mantiene al administrador bajo su control.}
{254}{}{Pero, ¿qué propósito tiene para golpear a los esclavos?}
{255}{}{Ninguno. Látigo es una mala persona. Pienso que Faber escogió a un guardia tan duro como él para controlar a los prisioneros pues últimamente han habido muchos problemas con ellos. Además, Roy y Látigo están en buenos términos, pero dudo que Faber sepa la verdad.}
{256}{}{Podría encargarme de él si eso le haría la vida más fácil a los prisioneros y a ti.}
{257}{}{¿Qué? ¿Lo dices en serio? ¿Matarás a alguien en nombre de unos prisioneros? Ni siquiera los mercenarios de la guarnición son tan agresivos. Incluso alguien peor que Látigo podría tomar su lugar. Como sea, no me metas en esto. ¡No tengo nada que ver!}
{258}{}{Eso está bien, matar a alguien como él no me pesará la consciencia.}
{259}{}{Puede que tengas razón, quizás debería buscar una alternativa más 'legal'.}
{260}{}{Le diré a Faber lo que está pasando con él, dudo que le guste.}
{261}{}{Dudo que te haga caso, pero no me metas en esto. ¡Yo no tengo nada que ver!}
{262}{}{Vale la pena intentarlo. Adiós.}
{263}{}{Entonces me encargaré de Látigo, dejaré su cadáver en la entrada.}
{264}{}{¿Qué piensas del nuevo capataz?}
{265}{}{Mucho mejor que el anterior. No sobrepiensa las cosas y tiene autocontrol. Gracias por deshacerte de Látigo.}
{266}{}{Fue fácil.}
{267}{}{Tengo buenas noticias, Látigo no volverá a molestarte ni a ti ni a nadie más.}
{268}{}{Lo... ¿lo mataste? Vaya. En todo caso, eso no resuelve nuestro problema, porque después de Látigo, seguramente traerán a alguien peor. ¿Siquiera lo pensaste antes de matarlo? Suficiente, yo no escuché nada, y no tuve nada que ver con ello.}
{1268}{}{Lo... ¿lo mataste? Vaya. En todo caso, eso no resuelve nuestro problema, porque después de Látigo, seguramente traerán a alguien peor. ¿Siquiera lo pensaste antes de matarlo? Suficiente, yo no escuché nada, y no tuve nada que ver con ello.}
{269}{}{¿No deberías estar agradecido? Hm.}
