{100}{}{Ves a un minero.}
{101}{}{Ves a un hombre sucio con una falta de modales.}

#Responses
{110}{}{*Empieza a toser con fuerza*}
{111}{}{La mina es lo único que mantiene con vida.}
{112}{}{Cada jornada en la mina podría ser la última.}
{113}{}{El día se nos hará largo.}
{114}{}{Las ratas topo son enormes.}
{115}{}{Las ratas topo se comen el cuerpo, pero dejan intactas la cabeza y la ropa.}
{116}{}{¡Te lo juro, el Rey Rata es real!}
{117}{}{Me estoy muriendo de hambre.}
{118}{}{Oye, ¿no sabrás como desactivar nuestros collares?}
{119}{}{Una vez que entras, estás aquí para siempre.}
