{100}{}{Ves a un sirviente.}
{101}{}{Ves a un sirviente, su escuálida figura está llena de moretones.}
{102}{}{¿Puedo irme? ¿En serio?}
{103}{}{¡Ayuda! ¡Mi dueño me quiere matar!}

#First dialogue
{200}{}{(Mira a su alrededor muy confuso) Mi dueño está... ¿muerto?}
{201}{}{Deberías sentirte feliz, ¿no?}
{202}{}{¿¡Y qué voy a hacer sin mi dueño!? No puedo creerlo... ¡Ya sé! ¡Tengo que encontrar a un nuevo dueño! Tengo que regresar al corral. No hay de otra...}
{203}{}{Parece que esta es la única vida que conoces. Cuídate.}
{204}{}{(el sirviente se pone a tus pies, y te hace una reverencia) ¡Gracias, señor! ¡Se lo agradezco muchísimo! ¡Gracias!}
{1204}{}{(el sirviente se pone a tus pies, y te hace una reverencia) ¡Gracias, señorita! ¡Se lo agradezco muchísimo! ¡Gracias!}
{205}{}{Oye, relájate, no fue nada. Hay algo que quiero preguntarte.}
{206}{}{Parece que no estás acostumbrado a que sean buenos contigo. Volveré cuando te hayas calmado.}
{207}{}{¡Quítame tus cochinas manos de encima! ¡Aléjate!}

{210}{}{¿Sí, señor?}
{1210}{}{¿Sí, señorita?}
{211}{}{Eres libre.}
{212}{}{Tengo otra pregunta.}
{213}{}{Tengo que irme. Adiós.}

{220}{}{¿Por qué te golpeaba tu dueño?}
{221}{}{Porque perdí una chapa, señor. Me envió a hacer las compras y se me tuvo que haber caído, soy un mugroso, es lo que soy.}
{1221}{}{Porque perdí una chapa, señorita. Me envió a hacer las compras y se me tuvo que haber caído, soy un mugroso, es lo que soy.}
{222}{}{¿Te golpeó porque se te cayó una chapa?}
{223}{}{Una chapa es mucho, señor. Puede comprar la mitad de una iguana con una chapa. Pero... (te da una mirada de reojo, antes de mirar al piso de nuevo) Usted tiene razón, señor. Es muy poco, pero mi dueño estaba enojado por sus deudas y por cómo está la ciudad.}
{1223}{}{Una chapa es mucho, señorita. Puede comprar la mitad de una iguana con una chapa. Pero... (te da una mirada de reojo, antes de mirar al piso de nuevo) Usted tiene razón, señorita. Es muy poco, pero mi dueño estaba enojado por sus deudas y por cómo está la ciudad.}
{224}{}{Entonces es obvio que las cosas andan mal por aquí.}

{230}{}{Estoy buscando a mis parientes, los esclavizaron, igual que a ti.}
{231}{}{Encierran a todos los esclavos en un corral hasta que tengan trabajo. El corral está en la guarnición, sólo siga la calle principal.}
{232}{}{¿Sabes cómo podría ayudarlos a escapar?}
{233}{}{¿Escapar? Eso es imposible, señor. Hay guardias por toda la ciudad, harían sonar la alarma, y los prisioneros usan collares. Pero podría negociar con el carcelero. Escuché que busca a alguien que trabaje para él.}
{1233}{}{¿Escapar? Eso es imposible, señorita. Hay guardias por toda la ciudad, harían sonar la alarma, y los prisioneros usan collares. Pero podría negociar con el carcelero. Escuché que busca a alguien que trabaje para él.}
{234}{}{Así que podría resolver esto sin mancharme las manos. Eso es bueno.}

{240}{}{¿Cómo terminaste siendo un esclavo?}
{241}{}{Me vendieron, así que pasé de dueño a dueño hasta que llegué acá.}
{242}{}{¿Has sido un esclavo toda tu vida?}
{243}{}{Sí, señor. Excepto en mis primeros años... en ese entonces me cuidaba yo sólo.}
{1243}{}{Sí, señorita. Excepto en mis primeros años... en ese entonces me cuidaba yo sólo.}
{244}{}{Que triste.}
