{100}{}{Ves a un guardia.}
{101}{}{Ves a un mercenario resguardando la entrada al corral.}
{102}{}{Eso sería... ahora.}
{103}{}{Podrías meterte al corral mientras el guardia está distraído.}
{104}{}{Hrrr... ¿Eh? Entra...}
{105}{}{¡Alto ahí! Esto es un área restringida, solo se permite el acceso con el permiso de Faber.}
{106}{}{¡Te lo advertí!}
{107}{}{Te estamos mirando, no causes problemas.}

#Responses - good attitude
{110}{}{Te estoy mirando.}
{111}{}{No intentes entrar sin permiso.}
{112}{}{¿Quieres abrir la puerta? Inténtalo y te mueres.}
{113}{}{Sólo se entra con el permiso del carcelero.}
{114}{}{No puedes pasar.}

{120}{}{Así es, puedes pasar.}
{121}{}{Puedes entrar al corral.}
{122}{}{Adelante, la puerta está abierta.}
{123}{}{¿Tienes permiso de pasar? Entonces pasa.}
