{100}{}{Ves a un prisionero.}
{101}{}{Ves a un hombre de aspecto desagradable. Se le ve triste y exhausto.}

#Response
{110}{}{Una vez que estás acá, no hay escapatoria.}
{111}{}{Ni se te ocurra salir corriendo.}
{112}{}{Oye, ¿sabes cómo sacarme el collar?}
{113}{}{Mi familia ni siquiera sabe que estoy aquí.}
{114}{}{¿Cuándo nos darán de comer?}
{115}{}{¿Tienes algo para comer? Me estoy muriendo...}
{116}{}{¿Qué está pasando allá afuera?}
{117}{}{El capataz es duro con nosotros.}
{118}{}{¡Estoy tan cansado que me quiero morir!}
{119}{}{Hola.}
