{100}{}{Ves a Cerebrito.}
{101}{}{Ves a un hombre que se encuentra haciendo cálculos, es delgado y utiliza gafas.}
{102}{}{Por fin... se acabó...}

#Floating lines
{110}{}{Eh... ¿Y cuánto es ocho veces seis?}
{111}{}{No tengo ni idea de qué significan esos números.}
{112}{}{Ojalá me den más rata frita si termino temprano.}
{113}{}{Se cortó la luz, de nuevo.}
{114}{}{Se nos acabará el hierro en lo que queda de año.}
{115}{}{No creo que eso se trate de ruido blanco...}
{116}{}{A veces escucho cosas raras en las frecuencias bajas.}
{117}{}{Tengo que actualizar los códigos de las patrullas.}
{118}{}{La última patrulla jamás volvió a contactarnos.}
{119}{}{Parece que tenemos un error en el sistema.}

#Dialogue
{200}{}{(conforme te acercas, se ajusta las gafas y voltea a verte) Oh, no puede ser, ¿qué haces aquí?}
{201}{}{Estoy buscando a mis parientes, son campesinos de la Villa. ¿Sabes algo al respecto?}
{202}{}{Sí... Sí, escuché de ellos. Los mercenarios arrastraron a un montón de campesinos y los encerraron en el corral junto a los demás prisioneros. Ni siquiera lo pienses - un intento de rescate terminará muy mal.}
{203}{}{¿Qué otras opciones tengo para entrar al corral?}
{204}{}{Puede que Faber te deje pasar si cuentas con muchas chapas. Pero desconozco si te dejará salir... Los guardias la tienen fácil trabajando ahí, prueba a ganarte la confianza de alguno de ellos.}
{205}{}{Un momento, tengo más preguntas.}
{206}{}{Me encargaré del resto por mí mismo.}
{1206}{}{Me encargaré del resto por mí misma.}
{207}{}{¿Sucede algo?}

{208}{}{¿Qué es este lugar?}
{209}{}{Es una estación de radio, nos permite comunicarnos a larga distancia con las patrullas. Pero tú deberías irte, no tienes permitida la entrada.}
{210}{}{¿De dónde sacaron todas las máquinas?}
{211}{}{Ni idea, ya estaban aquí cuando me trajeron.}
{212}{}{Eso es interesante, ¿en qué frecuencias se comunican los mercenarios?}
{213}{}{No te diré eso, de ninguna manera. Pregúntale al jefe si tanto lo quieres saber.}
{214}{}{No me irrites, cuatro ojos. ¡Dímelo de inmediato!}
{215}{}{¡No grites! Nos van a escuchar... Mira, aquí tienes las frecuencias para las patrullas, y esta es para los carceleros. ¡Pero no le digas a nadie!}
{216}{}{De acuerdo.}
{217}{}{¡Voy a gritar y así todos sabrán que estás acá!}
{218}{}{Oye, cálmate, no hagas eso.}

{219}{}{¿Tanta máquina necesitan para comunicarse?}
{220}{}{Sí, así es... pero también controlan los collares.}
{221}{}{¿Eso quiere decir que sabes cómo desactivarlos?}
{222}{}{Necesitas un código de acceso para la terminal. Los únicos que lo tienen son Faber y yo, y no te lo voy a decir.}
{223}{}{No seas así, Hazlo por toda la gente que está en tu misma situación. Es tu oportunidad para salir de aquí.}
{224}{}{¿Acaso perdiste la cabeza? Si nos descubre algún carcelero, nos llegará algo peor que la muerte. No quiero problemas, así que vete de aquí antes de que nos vean hablando.}
{225}{}{Quizás... quizás tienes razón. No sé si puedo confiar en ti... puede que esto acabe con nuestras vidas. Este es el código, ¡pero ten cuidado!}
{226}{}{Hiciste lo correcto.}
{227}{}{Las máquinas se ven fuera de lugar aquí dentro.}
{228}{}{¿Y cómo voy a saber eso? Lo único que hago es apretar botones.}
{229}{}{Puede ser. El edificio está hecho polvo, pero los equipos parecen ser nuevos. Y es obvio que la antena es nueva.}
{230}{}{Hablemos de esto en otro momento.}
{231}{}{Adiós}

{250}{}{¿Quién eres?}
{251}{}{Me apodaron Cerebrito, no era apto para trabajar en la mina, así que me asignaron a monitorear la comunicación por radio.}
{252}{}{¿Deseas la libertad?}
{253}{}{¿Ser libre? Pero... ¿qué voy a hacer allá afuera? Puede que el jefe sea malo, pero nos alimenta y nos defiende contra los saqueadores. ¿Qué haría sin él?}
{254}{}{¡Maldito soplón! ¡Le dijiste a Faber que te hice preguntas!}
{255}{}{¡E-espera! ¡Ten piedad, no me pegues, sólo soy un esclavo! ¿Qué querías que hiciera? No tienes ninguna oportunidad contra ellos, y yo tengo que vivir acá hasta el fin de mis días. ¡Estaría muerto si me hubiera quedado callado!}
{256}{}{Más te vale que te calles, maldito pendejo, o te meteré las gafas por la garganta.}
{1256}{}{Más te vale que te calles, maldito pendejo, o te meteré las gafas por la garganta.}
{257}{}{Te dejaré ir. No debería haber confiado en el primer tipo que me encontré.}
{258}{}{Antes era una estación de radio, pero dejó de funcionar, así que ahora es un almacén. Pero, no deberías estar aquí.}

{260}{}{Faber ha muerto. Eres libre.}
{261}{}{¿¡Por qué me haces esto, Dios!? ¡Toda Flagstaff colapsará sin él! ¡Los mercenarios se mataran entre sí para ocupar su puesto! ¡Luego empezarán los disturbios y llegarán bandidos! ¿Tienes idea de cuánto esfuerzo les llevó establecer este lugar? Gracias por liberarme, pero nunca necesité eso.}
{262}{}{Hmm...}
{263}{}{¿Por qué no te fuiste con los demás prisioneros?}
{264}{}{¿Y a dónde voy a ir? ¿Al yermo? No duraría ni un minuto. ¿A la ciudad? Nadie me necesita ahí. Esta prisión era el único sitio en donde apreciaban mis talentos, me daban de comer y me protegían. Piensa lo que quieras, pero estaba contento con eso.}
{265}{}{Eso es irónico. Entonces quédate ahí.}
