{100}{}{Ves a un mercenario.}
{101}{}{Ves a un mercenario, impone el orden en la colonia.}
{102}{}{*Murmura algo en voz baja*}

#Responses - good attitude
{110}{}{No te quitaré los ojos de encima.}
{111}{}{¿Te interesa ser un guardia?}
{112}{}{¿Qué necesitas?}
{113}{}{Aquí recibimos a cualquiera con los brazos abiertos... si sabes a lo que me refiero.}
{114}{}{Este es un buen lugar para ganarse la vida.}
{115}{}{Escuché que el asalto a la Villa salió muy rentable.}
{116}{}{No andes de ocioso.}
{117}{}{No hables con los prisioneros.}
{118}{}{Es mejor que no molestes al jefe si anda de mal humor.}
{119}{}{Habla con el jefe si necesitas algo, yo soy sólo un guardia.}

#Responses - bad attitude
{120}{}{Te estoy vigilando.}
{121}{}{No aguanto a la gente como tú.}
{122}{}{¿Buscas problemas?}
{123}{}{Ve a hacer algo con tu vida, anda.}
{124}{}{No me molestes.}
{125}{}{Estás en un área restringida, lárgate.}
{126}{}{Nadie te invitó a la ciudad.}
{127}{}{¿Quieres entrar al corral? Te puedo ayudar en eso...}
{128}{}{Será mejor que me dejes en paz.}
{129}{}{No salgas a la calle luego del toque de queda.}
