{100}{}{Ves a un cazador.}
{101}{}{Ves a un hombre que parece estar exhausto.}
{102}{}{¡Shh! Abre la puerta, y no dejes que te vean.}
{103}{}{El cazador fue rescatado exitosamente.}

{200}{}{Llegaste justo a tiempo. ¡No hagas ruido! Esos salvajes tienen el oído bien abierto. ¿Vienes de Flagstaff?}
{201}{}{Sí, el cantinero quería saber qué estaba ocurriendo aquí.}
{202}{}{Estamos mal, muy mal. Los salvajes mataron a los demás cazadores y me encerraron acá, parece que me tendrán para la cena.}
{203}{}{La verdad no, me perdí y buscaba un lugar en donde pasar la noche.}
{1203}{}{La verdad no, me perdí y buscaba un lugar en donde pasar la noche.}
{204}{}{Entonces, bienvenido a Winon, No puedo ofrecerte un café, lo siento. Los salvajes mataron a los demás cazadores y me encerraron, parece que me tendrán para la cena.}
{205}{}{Eso es terrible.}
{206}{}{}
{207}{}{¿Me ayudarás a escapar? ¡Pero no hagas ruido! No podremos contra ellos, son demasiados.}
{208}{}{Todavía no, no es un buen momento.}
{209}{}{Lo siento, pero tendrás que esperar un poco más.}
{210}{}{De acuerdo, salgamos de aquí.}
{211}{}{Llévame a Flagstaff, ¿vale? Te seguiré.}
{212}{}{Comprendo.}

{220}{}{¿Por qué crees que atacaron los salvajes?}
{221}{}{¿Acaso no es obvio? Querían arrebatarnos nuestras cosas y demostrar quién manda. Esta tribu nos guarda rencor.}
{222}{}{Ya hablamos lo suficiente.}
{223}{}{¿Rencor? ¿Por qué?}
{224}{}{Todo empezó cuando Faber estableció la colonia en Flagstaff, expulsó a la tribu local de sus hogares. Mató a algunos y exilió a otros, pero este grupo en particular se quedó para vengarse de la colonia. En resumen, son salvajes.}
{225}{}{Ellos usan lanzas, ¿cómo los derrotaron?}
{226}{}{Nos emboscaron mientras dormíamos, son más adeptos en esas tácticas que los citadinos como nosotros.}
{227}{}{Háblame de este lugar.}
{228}{}{Son tierras salvajes, hay poca gente, pero muchas bestias. Hay bosques y montañas por donde veas. Tendimos trampas alrededor del campamento, así que mira por donde pisas.}
{229}{}{¿Podrías indicarme en dónde están las trampas?}
{230}{}{Están en el matorral del bosque cerca de la entrada al campamento, ten cuidado.}
{231}{}{Gracias.}
{232}{}{¿Tienes alguna idea de quiénes son los salvajes?}
{233}{}{Son un clan que pertenecía a una tribu de por aquí. Ahora son pocos. Faber exterminó a la mayoría y llevo al exilio a los demás. Estos pocos tuvieron que haber vuelto para cazar, hay muchos animales por aquí.}
{234}{}{¿Se te ocurre cómo podríamos ahuyentarlos?}
{235}{}{Con una escopeta, o con ayuda de la guarnición. Son muy supersticiosos, los tótems que hay por ahí son prueba de ello.}
{236}{}{¿Cuál es la ciudad más cercana?}
{237}{}{Flagstaff, es una colonia minera al suroeste de aquí.}
{238}{}{Gracias.}

{240}{}{Ya estás a salvo.}
{241}{}{Menos mal, ya estamos lejos. Esos malditos salvajes... ¡los odio! Gracias por ayudarme, les contaré a todos en Flagstaff lo que hiciste.}
{242}{}{Buena suerte.}
