{100}{}{Ves a la computadora de Faber.}
{101}{}{Ves una computadora muy antigua. Es sorprendente que siga funcionando.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}

{210}{}{Petición de prisioneros nuevos}
{211}{}{Informe de la administración de la mina: "Debido a la falta de mano de obra, nos pasamos del plazo de nuevo. La mina está matando a los prisioneros demasiado rápido. Tenemos que encontrar nuevos trabajadores en los asentamientos cercanos. Hay rumores de unas tribus salvajes hacia el oeste, valdría la pena investigarlos."}
{212}{}{Informe sobre la expedición al oeste}
{213}{}{Los mercenarios regresaron con prisioneros nuevos. Los campesinos de la Villa son sorprendentemente fuertes, saludables y vigorosos. Los demás salvajes son menos impresionantes pero son mejores que los prisioneros sureños. La Villa también tenía suministros y otros objetos útiles. Pasamos por Ciudad Garaje de camino; los lugareños nos ofrecieron oportunidades comerciales que vale la pena considerar.}
{214}{}{Incidente en la mina}
{215}{}{Un grupo de prisioneros de la Villa desapareció en la mina. Una de dos, o subestimé a estos paletos, o nuestras defensas son inadecuadas. Debemos imponer castigos más duros.}
{216}{}{Envío de prisioneros a Fénix}
{217}{}{Los Seguidores del Fuego compraron a los prisioneros más fuertes de la Villa y a unos salvajes. Eran nuestras existencias de mayor valor, a cambio, recibimos algunas armas y munición que nos hacían mucha falta. Fue un buen trato.}
{218}{}{Disminución en los suministros de carne}
{219}{}{Dado a los problemas en San Brahmán, han disminuido los suministros de carne. Tenemos que cazar ratas topo y establecer un campamento trampero en las montañas. Es otro gasto que no esperaba, pero también es una oportunidad de desarrollo.}
{220}{}{Excavación en Navajo completada}
{221}{}{El campamento militar Navajo fue mayormente inútil. Casi todos los recursos fueron destruidos en las explosiones de los almacenes. Extraer los recursos restantes no es lucrativo por las pérdidas laborales. Tenemos que cerrar el campamento. Teníamos altas expectativas para él...}
{222}{}{Nota personal}
{223}{}{Cuando fundé esta colonia, esperaba cumplir con esa idea del Nuevo Mundo. Pero a nuestros visitantes sólo les importan las chapas. Son unos bastardos, ¡les impondré nuevas leyes y los haré cambiar!}
