{110}{}{Sobre el vidrio de la máquina hay un cartel. "La máquina de pinball está descompuesta."}
{111}{}{"¡Saludos, piloto estelar! ¡Inserta una moneda y entra al increíble mundo del Espacio!"}
{112}{}{Has conseguido reparar las partes rotas de la máquina de pinball. Al dueño del bar le gustará saberlo.}

{120}{}{Por alguna razón, esto ya no es divertido.}
{121}{}{Siento nauseas con sólo ver la máquina.}
{122}{}{Para jugar, inserta una moneda en la máquina.}
{123}{}{¡Mmm-hmm! Se ve genial.}
{124}{}{"¡Oye, pilotito! Deberías darle los controles a un piloto más experimentado."}
{125}{}{No tengo *ninguna* oportunidad contra esta cosa.}
{126}{}{"¡Piloto! El médico a bordo no te dejará tomar el control si estás en ese estado."}
{127}{}{No estoy en condiciones de jugar.}

#Phrases when playing
{130}{}{¡Bien hecho, piloto! ¡Ganaste }
{131}{}{ puntos!}
{132}{}{Puntaje total: }
{133}{}{.}
{134}{}{}
{135}{}{¡Hacia el infinito y más allá!}
{136}{}{¡Les mostraré a todos lo bien que vuelo!}
{137}{}{¡Vamos, pelotita!}
{138}{}{¡Quiero ganar!}
{139}{}{¡Vamos! ¡Más rápido!}
{140}{}{¡Qué viaje tan difícil! ¡Perdiste }
{141}{}{ puntos!}
{142}{}{.}
{145}{}{¡No! ¡Mierda!}
{146}{}{¡Estúpida máquina!}
{147}{}{¡No puede ser! ¡Eres un pedazo de chatarra!}
{148}{}{¡Máquina de mierda, te odio!}
{149}{}{¡Noooo!}
{150}{}{"¡Ese fue un fantástico vuelo, capitán! Has conquistado la galaxia. ¡Siéntete orgulloso!"}
{151}{}{Por fin... Pero, es raro... gané, pero se siente vacío.}
{152}{}{¡Tuviste un ataque de epilepsia mientras jugabas!}
