{110}{}{Parece que esta tecnología antigua era capaz de volar muy alto. Muy alto.}
{111}{}{Es otro viejo pedazo de chatarra en otro viejo edificio.}
{112}{}{Ya quitaste todo lo que podría ser útil de ésta reliquia.}

{113}{}{Eso no te ayudará con esto.}
{114}{}{A pesar de que no tenía sentido, colocaste las piezas en donde debían estar.}
{115}{}{Jamás había hecho algo tan raro.}
{116}{}{Órale, nuestros ancestros sí que eran inteligentes.}
