{100}{}{Ves a un borracho.}
{101}{}{Ves a un cliente. Ha bebido más de la cuenta y está haciendo el ridículo.}

{110}{}{No te...*hic*...conozco}
{111}{}{Ese, asiento...está ocupado.}
{112}{}{*Hic*}
{113}{}{No te voy a dar mis chelas. ¿Me escuchas?}
{114}{}{Fuera... de aquí.}
{115}{}{*Hic*...Si quieres...caernos bien...compra una cerveza para cada uno.}
{116}{}{Ni siquiera le... prestarías chapas a un amigo.}
{117}{}{¡No toques eso!}
{118}{}{*Hic*...No te invité... anda a otra mesa.}
{119}{}{No bebo...con desconocidos.}

{120}{}{Oye, gracias... por la bebida.}
{121}{}{Me...me agradas.}
{122}{}{Eres bueno...*hic*...para un paleto.}
{123}{}{¿Cómo te... te llamabas? Encantado... de conocerte.}
{124}{}{La mejor forma de hacer amigos... ¡es bebiendo! ¡Lo estás haciendo bien!}

{130}{}{Es mejor que...*hic*... te largues. En... en serio.}
{131}{}{¡Sal de acá!}
{132}{}{¿Buscas problemas?}
{133}{}{¡No te queremos acá!}
{134}{}{Paleto de mierda...¡fuera!}
{135}{}{¿No encuentras la puerta? Te la... ¡te la pondré en la cara!}

{140}{}{Siéntate... eres bienvenido.}
{141}{}{¿Cómo te... va, amiguito?}
{142}{}{Sigo igual...sigo igual. ¿Tú?}
{143}{}{Ay, ni me... ni preguntes. Pero... ¿y tú?}
{144}{}{Mi vida... está tan vacía como esta botella.}
