{100}{}{Ves a un cliente del bar.}
{101}{}{Ves a un hombre relajado.}
{102}{}{Oye amigo, ¿me compras un trago, como muestra de nuestra amistad?}
{1102}{}{Señorita, ¿me invitaría un trago, como muestra de nuestra amistad?}
{103}{}{Gracias por la cerveza, amigo.}
{1103}{}{Gracias por la cerveza, señorita.}
{104}{}{Ya no tengo nada para apostar. Quizás otro día.}

{200}{}{Mira lo que tengo. Es un estimulante, te ayudará con cualquier problema médico - una vez que lo inyectas, será como si la herida nunca hubiera estado ahí. ¿Lo quieres?}
{201}{}{¿Cómo funciona?}
{202}{}{Es medicina de la preguerra, así que no sé cómo funciona o qué componentes tiene. Pero sirve, no está vencido.}
{203}{}{Podría serme útil... ¿qué quieres a cambio?}
{204}{}{Sí. ¿A cuánto lo vendes?}
{205}{}{No lo sé, es difícil encontrar algo valioso en esta ciudad, aunque tengas las chapas. ¿Y si jugamos a las cartas? Apuesta 10 chapas y yo apostaré el estimulante. Así me entretengo, al menos.}
{206}{}{No me gustan las apuestas.}
{207}{}{No me interesa.}
{208}{}{Está bien, acepto. ¿Listo para perder?}
{209}{}{Primero, las chapas.}
{210}{}{Claro, apenas las tenga. Adiós..}
{211}{}{¡Genial! Pero no es tan simple como parece. Todos piensan que depende de la suerte, pero saber las reglas y saber contar es igual de importante, veamos...}
{212}{}{Empecemos de una vez.}
{213}{}{Hablas demasiado.}
{214}{}{Mira, tengo un as. ¿Dije que la suerte no lo es todo, verdad? Ahora las chapas son mías.}
{215}{}{Demonios, no me olvidaré de ésto. O de ti.}
{216}{}{Bueno, tú ganas. Al menos fue un juego limpio.}
{217}{}{Mira, tengo un rey... ¿Eh? ¿De dónde sacaste un as? ¡Chinga tu madre, hiciste trampa!}
{218}{}{Oye, jugué limpiamente. Todos lo vieron.}
{219}{}{Bueno, tú ganas. Pero no creas que estaré feliz de verte por acá.}
{220}{}{Ja ja, me llevo tu estimulante y las chapas. Adiós, amigo.}
{221}{}{Silencio, perdedor. Me gané el estimulante.}
