{100}{}{Ves al líder de los pastores.}
{101}{}{Ves a un forastero de ropa harapienta.}

{111}{}{Llévate al brahmán, forastero. Ojalá que no vuelva a verte.}
{1111}{}{Llévate al brahmán, forastera. Ojalá que no vuelva a verte.}
{112}{}{Espero que jamás volvamos a vernos.}

{200}{}{No te acerques al brahmán. ¿Qué querer tú de nosotros?}
{1200}{}{No te acerques al brahmán, mujer. ¿Qué querer tú?}
{201}{}{Necesito a tu brahmán... mejor dicho, Ciudad Garaje necesita a tu brahmán.}
{202}{}{No, es un animal sagrado, no se lo daremos a un desconocido. Vete.}
{203}{}{Bueno, me voy.}
{204}{}{Entonces, tendremos que quitártelo a la fuerza.}

{220}{}{¿Cómo domesticaste a un animal así?}
{221}{}{Nació entre hombres, hijo de un brahmán que también vivía entre un pueblo. Mi pueblo.}
{222}{}{¿Eres de San Brahmán?}
{223}{}{Yo ser del Clan Cuerno Norteño. Las ciudades ser ruidosas, y eso no nos gusta; sólo vamos a San Brahmán si necesitar intercambiar algo.}
{224}{}{Ya veo. Bueno, no te molesto.}
{225}{}{Jamás pensé que era posible domesticar un animal salvaje.}
{226}{}{Nosotros haber ocultado secretos a los forasteros durante generaciones. Si tú pasar por San Brahmán, tu ver todo con ojos propios.}
{227}{}{Ya veo. Bueno, adiós.}

{230}{}{Por allá hay unos chatarreros, si no les das tu brahmán, se lo llevarán a la fuerza.}
{231}{}{Los caras pálidas siempre estar amenazando. Tú decirles que nos defenderemos. Ellos no podrán derrotar a los protegidos por el Espíritu del Yermo.}
{232}{}{Si valoras tu vida, entrega al brahmán.}
{233}{}{Nosotros no tener miedo.}
{234}{}{¡Malditos caras pálidas! Nos vamos. Pero que la carne de este sagrado animal te enferme. ¡Arrrgh!}
{235}{}{Hiciste lo correcto.}
{236}{}{Confía en mí, intento salvarte el pellejo. Soy de la Villa, somos amigos de las tribus de San Brahmán.}
{237}{}{Yo haber escuchado de la Villa. Si tú decir que ellos nos matarán, tener que creer. Dile a los caras pálidas que no nos toquen.}
{238}{}{No podrás contra ellos. Dales el brahmán, o morirás.}
{239}{}{Trato de evitar que haya violencia.}

{240}{}{¿Y si te compro el brahmán?}
{241}{}{(se miran entre sí) ¿Qué puedes ofrecernos?}
{242}{}{Veamos...}
{243}{}{La verdad, no tengo nada. Perdón por la molestia.}
{244}{}{Te ofrezco... ¡la muerte!}
{245}{}{Los pastores ya no serán un obstáculo ante tus planes.}
{246}{}{Ahora, nosotros irnos.}
{1246}{}{Ahora, nosotros irnos.}
{247}{}{[Hecho]}
