{100}{}{Ves a un brahmán.}
{101}{}{Ves a un brahmán, busca pastar en la poca vegetación que encuentra.}
{102}{}{¡Moo!}
{103}{}{¿Moo?}
{104}{}{Estás demasiado lejos. El brahmán te perdió de vista.}
{105}{}{¿?}

{200}{}{¿Moo?}
{201}{}{No te preocupes, solo estoy echando un ojo.}
{202}{}{Sígueme, animal, te daré algo rico para comer.}
{203}{}{¡Moo!}
{204}{}{No, no me sigas. ¡Fuera! Brahmán descerebrado...}
{205}{}{Vamos, vamos, estúpido brahmán...}
