{100}{}{Ves a Trayvon.}
{101}{}{Ves a un hombre de piel oscura con la ropa sucia.}
{110}{}{No me hables.}

# Floating replicas during disassembly
{111}{}{¿Qué tienes en mente?}
{112}{}{¿En serio pensaste que podrías escapar?}
{113}{}{¡Ustedes jamás me agradaron, hijos de puta!}
{114}{}{¿Qué demonios está ocurriendo aquí?}
{115}{}{Agárrenlos o se nos van a escapar.}
{116}{}{No se saldrán con la suya.}
{117}{}{¿Qué tienen que decir en su defensa?}
{118}{}{No pienso dejarlos ir.}
{119}{}{Ese fue tu último error.}

# Dialogue during a skirmish
{200}{}{(se desarrolla una situación tensa - una multitud de chatarreros han rodeado a otro grupo y están a punto de golpearlos; pero tu presencia interrumpe sus planes) ¿Quién eres?}
{201}{}{Me envió el Sr. Kogan. ¿Qué carajo está pasando aquí?}
{202}{}{Estamos a punto de darles una lección a los chicos de Lucas. Estos pendejos se creen mucho, se ponen a robarnos y trabajan en nuestro territorio.}
{203}{}{Pero, ¿ustedes no son parte del mismo grupo?}
{204}{}{Ambos trabajábamos para el Sr. Kogan y su cartel. Pero cada clan tiene su propio territorio; nosotros pusimos la línea, y Lucas la cruzó.}
{205}{}{¿Qué hicieron, exactamente?}
{206}{}{Nos robaron el decodificador que el Sr. Kogan nos entregó, y luego se escaparon de la ciudad. Atrapamos a este par de pendejos, y ahora se las verán con nosotros.}

{207}{}{Entiendo. Haz lo que debas.}
{208}{}{Entonces ve a hablarle al jefe y cuéntaselo todo. No podemos dejar esto así... ¡Quieto! ¿¡A dónde crees que vas!? (aprovechando la situación, los otros dos chatarreros intentan escaparse)}
{209}{}{Hm...}

{210}{}{¿De verdad piensas que matarlos vale la pena? Ustedes son de la misma ciudad y el mismo grupo.}
{211}{}{Claro que sí, la ciudad está muriendo. Lo único que tenemos son las ruinas y las fábricas del norte. Pero Lucas no quiere compartir y quiere todo para él mismo. ¡Tenemos que hacer algo!}
{212}{}{Tienes razón, haz lo que tengas que hacer.}

{213}{}{Déjalos ir, ¿por qué derramar más sangre?}
{214}{}{No puedo dejar que Lucas se apodere de mi territorio.}
{215}{}{Sé que no puedo convencerte. Adiós.}
{216}{}{Me parece bien. Hazlo.}

{217}{}{¿Cómo? ¿Y dejarlos ir para que vayan con Lucas? ¡Eso sería estúpido!}
{218}{}{Tienes razón, sería una babosada. Haz lo que quieras.}
{219}{}{Cálmate, si haces esto, habrás acabado con dos vidas y todo seguirá igual.}
{220}{}{Creo que estás en lo cierto. ¿Y si nos ayudas a recuperar la fábrica? Lo dudo... (pausa) Demonios. Déjenlos ir.}
{221}{}{Bien hecho, hablaré con el Sr. Kogan al respecto.}
{222}{}{Bien pensado.}

{230}{}{¿Quién eres?}
{231}{}{Me envió el Sr. Kogan. ¿Qué está pasando?}
{232}{}{Lucas es una rata asquerosa. Nos robó el decodificador que el Sr. Kogan nos entregó y se escondió en la fábrica. ¡Pero esa fábrica es nuestro territorio!}
{233}{}{Comprendo. Se lo diré al jefe.}

# Regular dialogue
{300}{}{Hola, ¿necesitas algo?}
{301}{}{Adiós.}
{302}{}{¡No puede ser! ¿¡Cómo es posible que Kogan haya elegido a Lucas y no a nosotros!? ¡Hemos trabajado años con él, y no nos da ningún crédito! No tengo por qué aguantar esto. ¡Algún día los echaremos de aquí!}
{303}{}{Buena idea. Estoy de tu lado.}
{304}{}{Ahora Lucas es el que manda. Aguántate.}
{305}{}{¡No puede ser! Yo y mis hombres trabajamos muchos años para Kogan. No nos trataba bien, pero al menos confiábamos en él. ¡Y ahora llega Lucas y se apodera de todo! Esto es una mierda.}
