{100}{}{Ves a un comprador.}
{101}{}{Ves a un mercader, parece que ha estado en la carretera durante muchos días.}

{110}{}{¿Dónde está tu jefe? Dile que se apure, no vamos a quedarnos en este basurero.}
{111}{}{El comprador no quiere hablarte.}
{112}{}{Es un buen trato para un vertedero como este.}
{113}{}{Un lugar tan miserable como este no trae más que decepción. Tendré que irme con las manos vacías.}
{114}{}{¡Demonios! ¿Qué está haciendo un Seguidor del Fuego en un lugar así?}
{115}{}{Hmm, no esperaba ver una servoarmadura de verdad en un lugar así. Interesante.}
