{100}{}{Ves a Todd.}
{101}{}{Ves a uno de los ciudadanos de Ciudad Garaje.}
{102}{}{Hola. Gracias por ayudarme con los coyotes.}

{200}{}{Hola, no eres de por aquí, ¿cierto? ¿De dónde eres?}
{201}{}{Sólo estoy de visita. ¿Por qué lo preguntas?}
{202}{}{Ya no es común ver a un desconocido en nuestra ciudad. Me llamo Todd.}
{203}{}{Un gusto.}
{204}{}{Si estás intentando agradarme, lo estás haciendo muy mal.}

{210}{}{¿Qué quieres?}
{211}{}{Habla, te escucho.}
{212}{}{No es nada. Nos vemos.}

{220}{}{¿A qué te dedicas, Todd?}
{221}{}{Soy un experto en recolectar y refinar hierro, me he pasado muchos años perfeccionando mis habilidades.}
{222}{}{Debe ser un negocio muy rentable.}
{223}{}{Ya veo.}
{224}{}{No realmente. La mina está por cerrar, y no hay trabajo aquí. Además, hay unos animales cerca de mi remolque.}
{225}{}{¿Qué animales?}
{226}{}{Esos malditos coyotes. No sé qué olieron, pero había una manada entera. Me da miedo acercarme, pero mis herramientas están ahí adentro. ¿Puedes ayudarme? Te daré cinco chapas por cada coyote que mates.}
{227}{}{De acuerdo.}
{228}{}{No soy cazador, pero lo pensaré.}
{1228}{}{No soy cazadora, pero lo pensaré.}
{229}{}{No realmente. La mina está por cerrar, y no hay trabajo aquí. Además, es un trabajo difícil y te ensucias mucho.}
{230}{}{Comprendo.}
{231}{}{Puedo deshacerme de los coyotes, pero primero quiero hacerte unas preguntas.}
{232}{}{¿En dónde queda tu remolque?}
{233}{}{Dirígete hacia la fábrica de Wattz Electronics y gira a la izquierda.}
{234}{}{Entendido. Tengo una pregunta que hacerte.}
{235}{}{Lo haré de inmediato.}
{236}{}{Ya no te molestarán los coyotes.}
{237}{}{¡Genial! Debo pagarte, ¿cierto? Si no, me molestarás todo el día...}
{238}{}{Estas chapas están realmente limpias... ¿De dónde las sacaste?}
{239}{}{Adiós.}
{240}{}{Están muy bien conservadas. ¿Por qué te importa? Sólo agárralas y úsalas.}
{241}{}{Hmm...}
{242}{}{Déjame adivinar, ¿las creaste a partir de la chatarra que recoges de la fábrica, cierto?}
{243}{}{¡Baja la voz! ¿De verdad te importa de dónde vengan? Las chapas viejas ya están oxidadas, pero aquí tienes unas limpias, eso es mejor. Toma, y cierra la boca... Nadie te creerá, de todas formas.}
{244}{}{No te culpo, pero ten más cuidado.}
{245}{}{Mi silencio no es gratis. Me olvidaré de esto, por... 100 chapas.}
{246}{}{¿Sabes cuánto esfuerzo tengo que poner para hacer una sola chapa? Ya, toma, llévatelas. ¡Pero no le digas a nadie!}
{247}{}{Como quieras.}

{250}{}{Háblame de Ciudad Garaje.}
{251}{}{Esto es un campamento de chatarreros, aquí sacamos objetos viejos de las ruinas, los reparamos y los vendemos a los sureños.}
{252}{}{Eso suena bien.}
{253}{}{Lo era, pero nuestra mina pronto estará vacía. Tendremos que abandonar la ciudad, a no ser que encontremos otra fuente de ingresos.}
{254}{}{¿Qué recibes a cambio de tu trabajo? ¿Elotes?}
{255}{}{¡Chapas, genio! ¡Chapas! Las usamos de la misma manera que usábamos el dinero en la antigüedad. De hecho, una billetera no me vendría mal. Recuerda esto, para sobrevivir en una ciudad, necesitarás chapas.}
{256}{}{Parece que sabes muchas cosas. ¿Te puedo hacer otra pregunta?}
{257}{}{Gracias, no tengo más dudas. Adiós.}
{258}{}{De acuerdo. Tengo más preguntas.}
