{100}{}{Ves a un chatarrero.}
{101}{}{Ves a un hombre, el trabajo y el tiempo lo han desgastado.}
{102}{}{*Se agarra el pecho*}
{103}{}{Arch...}
{104}{}{El trato fue un éxito. Es hora de darle las noticias a Eugene.}
{105}{}{No me molestes.}

#First dialogue
{200}{}{¿Qué quieres, forastero?}
{1200}{}{¿Qué quieres, forastera?}
{201}{}{¿Hay algún problema?}
{202}{}{(escupe, casi por accidente) No estamos acostumbrados a los mariquitas por acá, perdón.}
{203}{}{Eh, bueno...}
{204}{}{Parece que tuviste mucha practica escupiendo. Adiós, imbécil.}

#Re-dialogue
{210}{}{¿Qué quieres?}
{211}{}{Nada.}
{212}{}{¿Qué puedes contarme acerca de la ciudad?}
{213}{}{No tengo tiempo para un burro como tú.}
{214}{}{¿Por qué tienes una estrella tachada en la puerta?}
{215}{}{Por los Rangers. Esos malditos ladrones quieren llevarse lo mejor que tengo - a mi hijo. Intento protegerlo de esa tontería.}
{216}{}{¿Por qué quieren a tu hijo?}
{217}{}{Reclutan a los jóvenes y los entrenan como guerreros o exploradores. No trabajé como esclavo en esta ciudad para que mi hijo sea un asesino. Que aprenda a ser un chatarrero como yo, así trabajará para él mismo, no para alguien más.}
{218}{}{¿Quiénes son los Rangers?}
{219}{}{Son una banda de metiches que quieren apoderarse del área entera. Prometen mantener la seguridad y el orden a cambio de recursos y reclutas.}
{220}{}{¿Y cuál es la trampa?}
{221}{}{Suena bien.}
{222}{}{La vida te enseña que no puedes confiar en gente así, porque guardan todo para ellos mismos y solo comparten las sobras. Son como saqueadores, pero te hablan bonito.}
{223}{}{Ya veo.}
{224}{}{Comprendo.}

#Quest
{250}{}{Estoy aquí para llevar a tu hijo con los Rangers.}
{251}{}{¡Lárgate, lamebotas! Lo único que te llevarás será una palanca en la cabeza.}
{1251}{}{¡Lárgate, puta! Lo único que te llevarás será una palanca en la cabeza.}
{252}{}{¿Eso quieres enseñarle? ¿Que aprenda usar una palanca como un arma, en vez de una herramienta?}
{253}{}{¡Fuera, te dije!}
{254}{}{...Él podrá hacer más cosas con los Rangers. Podrá trabajar con máquinas complejas en vez de buscar entre la basura.}
{255}{}{¡*Yo* sé lo que es mejor para él!}
{256}{}{La ciudad morirá tarde o temprano, y lo único que quedará para Eugene será la basura.}
{257}{}{Quizás tengas razón, pero... ¿Y qué? ¿Cómo puedo saber que los Rangers quieren lo mejor para él? ¡No les creo!}
{258}{}{Confía en tu hijo. Si no, lo verás envejecer en este basural. ¿Es eso lo que quieres? Al menos con los Rangers tendrá un futuro.}
{259}{}{Bueno, sí que sabes convencer a la gente... Llévate a Eugene y llévatelo a un lugar 'mejor'. Pero recuerda esto - si le pasa algo, ¡me las pagarás con tu sangre!}
{260}{}{No te preocupes, estará en buenas manos.}
{261}{}{No puedo convencerte.}
{262}{}{¡Una palabra más y te juro que será la última!}
{263}{}{Escúchame - es lo mejor para él.}

{270}{}{Podría pagarte por él. ¿Cuánto quieres por el contrato?}
{271}{}{Él vale mucho para mí, ni en tu vida entera tendrías suficiente para comprármelo.}
{272}{}{Primero, déjame hacerte una oferta...}
{273}{}{Olvídalo.}
{274}{}{¡Ja! Piérdete.}
{275}{}{[Hecho]}
{276}{}{Es la primera vez que ese niño me trae algo bueno. ¿Qué es eso? ¿Un contrato? ¡Ni sé escribir! No importa, pondré una cruz y ya. Llévate a mi hijo, pero si llega a pasar algo, ¡te voy a matar! ¿Me escuchas?}
{277}{}{Claro.}
{278}{}{(se rasca la mejilla mientras lo piensa)}
{279}{}{[Más]}
