{100}{}{Ves a Lucas.}
{101}{}{Ves a Lucas.}
{102}{}{La transacción fue un éxito.}

{110}{}{No bajes la guardia, no podemos dejar que Kogan o Trayvon interfieran con la caravana.}
{111}{}{Mierda... Ve a ocuparte de Kogan mientras me encargo de la caravana.}
{112}{}{Regresa a la fábrica, podemos hablar allá.}
{113}{}{Es mejor que te largues. Ahora.}
{114}{}{Está bien, nos vamos. Kogan no volverá a escuchar de nosotros.}

{120}{}{No hay moros en la costa.}
{121}{}{Demonios, es Kogan y sus hombres. Diles que se larguen de aquí.}
{122}{}{Ya acabamos, puedes volver a la fábrica, espérame allá.}

{200}{}{Nuestro problema no es contigo. Sal de aquí y no te haremos nada.}
{201}{}{Kogan te lo advierte, no interfieras.}
{202}{}{Dile al gordinflón que está acabado. Ahora mandamos nosotros.}
{203}{}{Cometiste el mayor error de tu vida al ir contra Kogan. Las vas a pagar. ¡Ahora!}
{204}{}{Bueno, iré a hablar con él.}
{205}{}{¡Chicos! ¡Es hora de pelear!}
{206}{}{¡Vamos!}
{207}{}{No deberías haber traicionado a Kogan. No eres rival para él.}
{208}{}{No teníamos otra opción. Ya no había trabajo y la ciudad se estaba llenando. Parece que lo único que nos queda es escondernos en algún lado. Encontraremos algún sitio en el yermo.}
{209}{}{Buena idea.}
{210}{}{Sólo un idiota iría en contra de Kogan.}
