{100}{}{Ves a un chatarrero.}
{101}{}{Ves a un maleducado y arisco habitante de Ciudad Garaje.}
{102}{}{¿Qué estás mirando?}
{103}{}{Si nos estás mintiendo acerca de los Chacales, te va a costar un ojo.}
{104}{}{Nos dejaste atrás, perra. Las vas a pagar.}

#Floating lines
{110}{}{Ahí está el bastardo.}
{111}{}{Sí, ese es.}
{112}{}{Nos abandonó, como una perra.}
{113}{}{Deberíamos destriparlo.}
{114}{}{Lo haremos pagar...}
{115}{}{La siguiente vez que lo vea...}
