{100}{}{Ves una computadora.}
{101}{}{Ves a una computadora muy vieja.}

#Dialogue
{200}{}{«Introducir comando»}
{201}{}{«Cerrar sesión»}
{202}{}{«Regresar»}

{210}{}{«Informe trimestral del fuerte»}
{211}{}{«Informe 2162 para el cuartel general en Monterrey. El destacamento del General Sarabia entró en el inhabitado Hermosillo y organizó una base temporal. Una semana despues, llegó la orden de acantonamiento permanente.»}
{212}{}{«Fuerte en El Paso»}
{213}{}{(Este informe detalla los suministros y los códigos de comunicación para otro fuerte en el Paso, parece que están en medio de una batalla.)}
{214}{}{«Metas y objetivos»}
{215}{}{«El objetivo principal es mantener la posición y expandir el territorio del nuevo estado..»}
{216}{}{«Evaluación de la situación»}
{217}{}{«Según los últimos datos, la principal amenaza para el fuerte es la Hermandad del Acero en las ruinas de Puerto Peñasco y un asentamiento de Hojalateros cerca de Two-Sun. El fuerte esta entrenando exploradores para estudiar las fuerzas de estos posibles oponentes.»}
{218}{}{«Copiar datos del ordenador al holodisco»}
{219}{}{«Datos archivados copiados»}
{220}{}{(Has copiado los datos, deberías llevarlo de vuelta a la base.)}

{300}{}{Introducir comando}
{301}{}{Cerrar sesión}
{302}{}{Regresar}

{310}{}{Informe trimestral del fuerte}
{311}{}{(Informe 2162 para el cuartel general en Monterrey. El destacamento del General Sarabia entró en el inhabitado Hermosillo y organizó una base temporal. Una semana despues, llegó la orden de acantonamiento permanente.)}
{312}{}{Fuerte en El Paso}
{313}{}{(Este informe detalla los suministros y los códigos de comunicación para otro fuerte en El Paso, parece que están en medio de una batalla.)}
{314}{}{Metas y objetivos}
{315}{}{(El objetivo principal es mantener la posición y expandir el territorio del nuevo estado.)}
{316}{}{Evaluación de la situación actual}
{317}{}{(Según los últimos datos, la principal amenaza para el fuerte es la Hermandad del Acero en las ruinas de Puerto Peñasco y un asentamiento de Hojalateros cerca de Two-Sun. El fuerte esta entrenando exploradores para estudiar las fuerzas de estos posibles oponentes.)}
{318}{}{Copiar datos del ordenador al holodisco}
{319}{}{Datos archivados copiados}
