{100}{}{Ves una máquina tragaperras.}

{110}{}{Esta máquina está fuera de servicio.}
{111}{}{Para seguir jugando, inserte una moneda.}
{112}{}{Después de que una sencilla melodía resonara en la sala, ¡La máquina tragaperras cobró vida!}

{120}{}{¿Por qué estresarse de nuevo? La máquina ya no tiene cupones.}
{121}{}{Ya tuve suficiente.}
{122}{}{Estás demasiado débil como para ponerte a jugar.}
{123}{}{Primero lo primero, debo curarme.}
{124}{}{Gracias a su edad, la máquina tiene problemas para responder a tus controles. Con habilidades como las tuyas, ganar sería imposible.}
{125}{}{Esto no será nada fácil.}

{130}{}{Derrotaste a la máquina con }
{131}{}{ puntos.}
{132}{}{Has ganado }
{133}{}{ puntos de 1.000}
{134}{}{¡Sí!}
{135}{}{¡Genial!}
{136}{}{¡Fantástico!}
{137}{}{¡Jaja!}
{138}{}{¡Nadie me puede vencer!}
{139}{}{Nadie es mejor que yo en ésto.}
{140}{}{Perdiste. La máquina te quitó }
{141}{}{ puntos.}
{142}{}{¡No, espera!}
{143}{}{¡No!}
{144}{}{¡Carajo!}
{145}{}{¡Chingada madre!}
{146}{}{¡Mierda!}
{147}{}{¡NOOOO!}
{148}{}{¡La máquina está arreglada!}
{149}{}{Me estoy enojando de verdad.}

{200}{}{¡Felicitaciones, has ganado! ¡Eres nuestro primer ganador! Escoge tu premio.}
{201}{}{Me llevaré el cupón de Superfuerza.}
{202}{}{Me llevaré el cupón de Ultra Percepción.}
{203}{}{Me llevaré el cupón de Giga Resistencia.}
{204}{}{Me llevaré el cupón de Extra Atractividad.}
{205}{}{Me llevaré el cupón de Megainteligencia.}
{206}{}{Me llevaré el cupón de Híper Agilidad.}
{207}{}{Me llevaré el cupón de Multi-Suerte.}
{208}{}{No necesito nada de ésto.}
