{100}{}{Ves a una Chacal.}
{101}{}{Ves a una perra de la tribu Chacal. Sobrevivió al ataque de los rangers, si es que a esto se le puede llamar vida.}
{102}{}{¿Qué voy a hacer ahora?}

#Response
{200}{}{¡No! ¡Ten piedad! ¡No me mates!}
{201}{}{Te dejaré vivir. Por ahora.}
{202}{}{Cuéntame lo que pasó.}
{203}{}{¡Fueron los Rangers! Nos atacaron con sus escupefuegos, mataron a todos los hombres, todas las mujeres, y todos los cachorros...}
{204}{}{¿Cómo sobreviviste?}
{205}{}{Atrapaba iguanas para mis cachorros en el yermo. Y cuando llegaron, miré desde lejos... ¡Malditos Rangers!}
{206}{}{¿Y dejaste a tus niños solos?}
{207}{}{Yo... (cae al suelo, arrodillada) No pude... Tenía miedo y hambre...}
{208}{}{Tendrás que vivir con esa carga. Me voy.}
