{100}{}{Ves a Bestia Nocturna.}
{101}{}{Ves a un guardia de los Chacales, protege el almacén de la tribu con su vida.}
{102}{}{¿Q-qué clase de b-broma es esta!?}

#Replicas floating
{120}{}{Nadie se atreve a quitarme mi lugar.}
{121}{}{Sólo yo puedo resguardar el almacén, ¡sólo yo!}
{122}{}{¡Haré pedazos a cualquiera que intente entrar aquí!}
{123}{}{La tribu me necesita.}
{124}{}{La Perra Loca me pidió que resguardará el almacén. Así que lo haré.}
{125}{}{Dicen que hay un forastero por aquí.}
{126}{}{¡Grrr! ¡Huelo a alguien!}
{127}{}{*Olfatea*}
{128}{}{Huelo a un forastero.}
{129}{}{A este lugar le faltan los gritos de dolor de los forasteros.}

#Response
{200}{}{¡Fuera de aquí! ¡Aquí no hay lugar para los forasteros!}
{201}{}{Ya me voy.}
