{100}{}{Hay un saqueador bloquéandote el paso.}
{101}{}{Ves a un Escudo Azul que te resulta familiar, atacó el bar de Casa Grande.}
{102}{}{No deberías estar aquí. Lárgate y haré de que nunca nos vimos.}

{200}{}{Qué sorpresa, tú otra vez. ¿Cómo está el Don y su niñita malcriada?}
{201}{}{Han estado ocupados. ¿Y tú sigues robando y secuestrando gente?}
{202}{}{Sí, he estado en eso. Pero hay más que eso, Ben tiene un plan. Háblale, quizás puedas serle de ayuda.}
{203}{}{Está bien, iré con él.}
{204}{}{Espérate. Lo he estado pensando, no sé por qué nos ayudaste en el bar, pero te ganaste mi respeto. Les conté a los demás lo que hiciste, así que serán más amables contigo. Toma, un arma y algunas balas. Puede que no quieras herir a los demás, pero deberías cuidarte las espaldas.}
{205}{}{Gracias.}
{206}{}{Te haré un último favor. Un superviviente de verdad no dice "gracias" o "por favor". Recuérdalo.}
{207}{}{Bueno. Adiós.}
{208}{}{Creo que me será de ayuda.}
{209}{}{Te deseo suerte. Que el polvo de la carretera deje ciegos a tus adversarios.}

{210}{}{Hola. ¿Cómo estás?}
{211}{}{Creo que bien. Nos vemos.}
