{100}{}{Ves a una de las víctimas de los caníbales.}
{101}{}{Ves a un hombre muy cansado.}
{102}{}{Este lugar es muchísimo mejor que el motel. Nunca me volveré a meter en uno.}

{200}{}{¡Ahh! ¡No me hagas nada!}
{201}{}{No quiero hacerte daño, cálmate.}
{202}{}{¡Cállate, idiota! O nos van a escuchar.}
{203}{}{¿Eh? No eres un mutante... Ay... No sabes lo feliz que estoy de verte...}
{204}{}{¿Por qué te encerraron los mutantes?}
{205}{}{¿Acaso no es obvio? ¡Son caníbales! Colocan trampas para atrapar a la gente y luego se los comen.}
{206}{}{Eso es horrible.}

{210}{}{¡Tenemos que salir de aquí! Mataron a los demás... ¡Nos harán lo mismo!}
{211}{}{Espérame aquí, iré a echar un vistazo.}
{212}{}{Está bien, te llevaré a Fénix. Vamos, pero no hagas ruido.}
{213}{}{Tengo mucho miedo. Hay que salir de aquí.}
{214}{}{Entonces no perdamos el tiempo, vámonos.}
{215}{}{Escóndete y no hagas ruido, ya vengo.}

{220}{}{Ya estamos a salvo. Me salvaste, pensé que terminaría en un taco. Gracias. Les contaré a todos que me salvaste.}
{221}{}{Sólo quería ayudarte. Nos vemos.}
