{100}{}{Ves a un prisionero.}
{101}{}{Ves a un saqueador castigado por la justicia.}
{102}{}{P-p-puta...}
{103}{}{*Cof cof*}
{104}{}{Te veo en la base, si es que sobrevivimos.}

{200}{}{(En el suelo yace un saqueador semidesnudo; su cuerpo está repleto de moretones) ¿Qué es lo que quieres? Ya dije todo lo que sabía.}

{210}{}{¿Qué quieres?}
{211}{}{Yo haré las preguntas aquí.}
{212}{}{Bueno, entonces habla. No diré nada.}
{213}{}{Me envió Ben, quiere salvarte.}
{214}{}{Entonces ayúdame, si es que puedes. O, quizás me estás mintiendo.}
{215}{}{Quédate ahí.}
{216}{}{¿Me vas a dejar así?}

{220}{}{¿Por qué te encerraron?}
{221}{}{Porque soy un peligro, nada más. El alcalde quiere respuestas, pero no hace las preguntas correctas.}
{222}{}{¿Qué es lo que quiere el alcalde?}
{223}{}{Lo único que escuché es de un tal Ben y de su base. No sé de qué hablas.}
{224}{}{¿Cómo te atraparon?}
{225}{}{Estaba de camino a la ciudad y me vieron unos lugareños. Pensaron que era uno de los forajidos y alertaron al alcalde.}
{226}{}{¿Sabes cómo podría sacarte de aquí?}
{227}{}{Debes convencer al alcalde de que soy inocente. O, dame un arma y saldré de aquí yo sólo.}
{228}{}{Te tengo malas noticias, Ben me dijo que acabara contigo si es que no encontramos como sacarte de ahí.}
{229}{}{(te muestra el dedo de al medio) Vete a la mierda.}
{1229}{}{(te muestra el dedo de al medio) Vete a la mierda.}
{230}{}{Ahora sí que te vas a pudrir ahí adentro.}
{231}{}{Eso no te ayuda en nada.}
{232}{}{Tendremos que escapar a la fuerza, no hay otra opción. Vámonos.}
{233}{}{Genial, este lugar es una mugre. Pero no intentes hacerte el héroe, sólo tengo que salir de la ciudad y estaré bien.}
{234}{}{Salgamos de aquí.}
{235}{}{Quédate aquí, veré qué hay más adelante.}

{250}{}{Puedes irte, el alcalde lo permitió.}
{251}{}{¿En serio? Mira, necesito que me acompañes, o los demás pueblerinos me van a matar.}
{252}{}{Entonces vamos.}
{253}{}{Iré sólo, así será más fácil cubrir mi rastro.}
{254}{}{Como quieras. Por cierto, Ben dijo que te matará si les dices una sola palabra.}
{255}{}{(tiembla) Si Ben no estuviera tan decidido en vengarse, yo no estaría metido aquí. Quería que encontrara un punto débil en las defensas de la ciudad. Pero, aquí todos se conocen, así que me descubrieron de inmediato. Ahora tendré que volver con las manos vacías.}
{256}{}{¿Crees que estará molesto?}
{257}{}{Es obvio que sí. Pero si no vuelvo, me marcará como un traidor. Y eso es peor aún.}
{258}{}{Estás jodido. Buena suerte.}
{259}{}{Quizás lo entenderá.}
{260}{}{Es mejor que salgamos de aquí antes de que nos atrapen.}
{261}{}{De acuerdo, salgamos de aquí.}
{262}{}{Parece que estamos a salvo. Por un momento pensé en abandonarte y salir corriendo. ¿En serio te envió Ben? No te había visto antes.}
{263}{}{Sí, soy nuevo en la banda. Es por eso que me envió a rescatarte.}
