{100}{}{Ves a un forajido.}
{101}{}{Ves a uno de los Escudos Azules.}
{102}{}{No está dispuesto a cooperar contigo.}

{110}{}{Hola, ¿cómo te va?}
{111}{}{Ten cuidado allá afuera.}
{112}{}{Eres más fuerte de lo que pensábamos.}
{113}{}{No puedo creer que ahora seamos guardias.}
{114}{}{Ahora tenemos la carretera bajo nuestro control.}
{115}{}{Nos trajiste suerte.}
{116}{}{Ben confía en ti.}

{120}{}{Deja de mirarme o te arrepentirás.}
{121}{}{¿Qué mierda quieres?}
{122}{}{*Te escupe en los pies*}
{123}{}{No importa si Ben te dejó pasar, no eres uno de los nuestros.}
{124}{}{Me aburro. Cuéntame un chiste.}
{125}{}{No deberías estar aquí.}
{126}{}{No nos jodas.}

{130}{}{¿Quién mierda eres? ¿Un Hojalatero?}
{131}{}{Es él, no digan nada.}
{132}{}{Me gustaría tener una armadura como la tuya.}

{199}{}{ }
{200}{}{¿Qué estás mirando?}
{201}{}{A ti, perra.}
{202}{}{Detesto cuando me dicen así.}
{203}{}{Bueno, aguántate, PERRA.}
{204}{}{Ten cuidado con lo que dices, o te voy a...}
{205}{}{¿Qué? Ah, ¿me vas a pegar?}
{206}{}{Si vuelves a abrir la boca, te voy a...}
{207}{}{¿Qué me harás, bebé? ¿Quieres que te cachetee? Porque hasta podría nalguearte...}
{208}{}{¡Cállate de una vez!}
{209}{}{¡Cállate!}
{210}{}{*Agh*}
{211}{}{No, no, perdóname... Lo siento, me dejé llevar.}
{212}{}{Sí, ya me di cuenta.}
{213}{}{. . .}
