{100}{}{Ves a un prisionero.}
{101}{}{Parece que los saqueadores lo tienen esclavizado.}
{102}{}{¿Soy libre? ¿¡De verdad!?}

{110}{}{Me capturaron y me tienen trabajando.}
{111}{}{¿Tú también estás en una pandilla?}
{112}{}{Ya no aguanto más. No me queda fuerza.}
{113}{}{¿Cuándo me dejarán en paz?}
{114}{}{Ayúdame. Eres mejor que ellos.}

{120}{}{Me capturaron y me tienen trabajando.}
{121}{}{¿También estás en una pandilla?}
{122}{}{Mátame, ya no aguanto más.}
{123}{}{¿Cuándo me dejarán en paz?}
{124}{}{Mátame, por favor.}

{200}{}{Hola.}
{201}{}{Adiós.}

{210}{}{Hola.}
{211}{}{Adiós.}
