{100}{}{Ves a Teresa.}
{101}{}{Estás viendo a una mujer de pelo corto y de mirada severa, lleva puesta una túnica.}
{102}{}{Perdona, pero necesito descansar antes de dar mis clases.}
{103}{}{¿Cómo te atreves a asustar a los niños con tu terrorífica armadura?}
{104}{}{La escuela no es ningún lugar para las armas.}

{200}{}{Hola. ¿Qué te trae por aquí?}
{201}{}{¿Qué es este lugar?}
{202}{}{Es triste que la gente haya olvidado lo que significa la palabra 'escuela'. Esto es una escuela y aquí le enseñamos habilidades básicas a los niños, como la alfabetización y las matemáticas. Puede que seamos la única escuela en Sonora y Arizona.}
{203}{}{Pero, ¿para qué necesitan eso?}
{204}{}{Para que el mundo no vuelva a la Edad de Piedra. Ya no quedan escuelas ni universidades en el yermo. El conocimiento antiguo se ha olvidado, y el conocimiento nuevo no se acumula porque la gente está ocupada sobreviviendo. Un enfoque científico podría resolver este problema.}
{205}{}{¿Quién crees que soy? ¡Sé lo que es una escuela!}
{206}{}{Está bien, pero a juzgar por ese tono, no parece que hayas ido a una.}
{1206}{}{Está bien, pero a juzgar por ese tono, no parece que hayas ido a una.}
{207}{}{¡Una escuela de verdad! ¡Esto es sorprendente! Pensaba que no quedó ninguna después de la Gran Guerra.}
{208}{}{Así es, no quedó nada. Tuvimos que trabajar duro para traer de vuelta esta vieja tradición. Al principio, hubo muchos residentes que ni siquiera querían dejar que sus niños atendieran.}
{209}{}{Pero, ¿quién eres? ¿Por qué le enseñas a escribir y a contar?}
{210}{}{¿Quién eres como para enseñarles a escribir y a contar?}
{211}{}{Qué interesante. ¿Y quién creó esta escuela?}
{212}{}{Somos los Seguidores del Apocalipsis. Nuestra misión es traer el conocimiento a Sonora.}
{213}{}{Ya veo.}
{214}{}{Yo me crucé con los Seguidores del Fuego, también tienen una biblioteca y educan a los niños.}
{215}{}{Esos locos no saben de qué están hablando. ¿Qué pueden enseñar con la fe retorcida a la que siguen? No confundas una escuela científica con una teológica. Nosotros somos los Seguidores del Apocalipsis, y somos los verdaderos portadores de la ciencia de la preguerra.}
{216}{}{¿En serio?}
{217}{}{No debes confiar en fanáticos religiosos como ellos, quién sabe qué ideología retorcida está controlando sus mentes.}
{218}{}{De acuerdo.}

{220}{}{Bueno, ¿qué quieres saber?}
{221}{}{Ya sé lo suficiente. Adiós.}
{222}{}{Un momento, dejemos esto claro - aquí se enseñan conocimientos, no las artes marciales. En nuestra escuela no toleramos la violencia, así que guarda tus armas. Y quítate esa sonrisa de la cara. Te lo advertí.}
{223}{}{Estoy de acuerdo, no estoy en esta escuela para eso.}
{224}{}{Y yo te advierto que deberías tener cuidado conmigo. Por si acaso.}

{230}{}{Háblame sobre los Seguidores.}
{231}{}{Nosotros empezamos como un grupo pequeño entre las ruinas de San Diego. Pero era imposible vivir allí, así que nos transferimos al Cementerio de Los Angeles. Y allí, establecimos un cuartel general en una biblioteca que apenas se mantenía en pie. Hoy en día sigue allí.}
{232}{}{Sigue, te escucho.}
{233}{}{Mira esta foto vieja. La tomaron hace cien años, en el Infierno.}
{234}{}{¿Y esto qué es...? ¡Dios mío, eso es increíble! Si esa fecha es correcta, esto es un artefacto histórico.}
{235}{}{Parece que aprecias mucho estas cosas.}
{236}{}{No hemos visto un sólo documento de la Gran Guerra. Dicen que la Guerra duró unas horas, mientras explotaban miles de bombas nucleares por el planeta. Hay muchos documentos que no sobrevivieron, y los libros se han vuelto muy poco comunes.}
{237}{}{[Más]}
{238}{}{Y aquí tenemos evidencia directa de cómo se veía la explosión nuclear en Mexicali... Bueno, ese era el nombre de la ciudad antes de la Guerra.}
{239}{}{Hoy se llama Infierno. ¿Quieres comprarla?}
{240}{}{¡Por supuesto! Por el bien de la ciencia.}
{241}{}{Quédatela, consideralo como una donación para la escuela.}
{242}{}{Te lo agradezco mucho. Agregaremos tu nombre a nuestra lista de benefactores.}
{243}{}{No tan rápido. Me esforcé mucho en conseguir esta foto y además para traerla aquí.}
{244}{}{Está bien. Déjame reunir un conjunto de medicamentos, es lo más valioso que tiene nuestro pueblo.}
{245}{}{Me parece bien, es un trato justo. Gracias.}
{246}{}{Te daré la foto, pero a cambio, quiero que me cuentes sobre cómo se desarrollaron los Seguidores.}
{247}{}{Oh, es todo un honor.}
{248}{}{Desde nuestros inicios, se nos han unido muchas personas. Algunos, como yo, viajan a tierras lejanas como misionarios para establecer nuevos templos de la ciencia.}
{249}{}{¿Templos de la ciencia? ¿Así que sí son una organización religiosa?}
{250}{}{No, sólo es una forma de referirse a ellos. La religión y la ciencia rara vez se entrelazan. No las llamamos iglesias pues las iglesias promueven las discusiones sobre Dios y menosprecian a los no creyentes. Pero los templos, por otro lado...}
{251}{}{Gracias por hablarme de ello.}

{260}{}{¿De dónde vienen estos libros viejos?}
{261}{}{En su mayoría, los traen las caravanas. También recolectamos lo que fue preservado entre las ruinas de los alrededores, fue hace mucho tiempo.}
{262}{}{Ya veo.}
{263}{}{Por desgracia, estas cuatro estanterías no son nada comparadas a la biblioteca del Cementerio. La mayoría de estos libros no son muy útiles para educar o para la ciencia.}
{264}{}{Podría traerte los libros que encuentre durante mis viajes.}
{265}{}{Oh, eso sería maravilloso. Apreciaremos cada uno que encuentres. Y te pagaremos por ellos, por supuesto.}
{266}{}{Lo tendré en cuenta. Adiós.}
{267}{}{Tengo un libro viejo para tu biblioteca.}
{268}{}{Magnífico. ¿En dónde está?}
{269}{}{Está en otro lugar. Lo traeré pronto.}
{270}{}{Sólo tengo un libro.}
{271}{}{Tengo dos libros.}
{272}{}{He traído tres libros, aquí están.}
{273}{}{Puedes tener todos mis libros, son un montón.}
{274}{}{Muchísimas gracias, esta es tu paga - }
{275}{}{ chapas.}
{276}{}{Si encuentro más, los traeré. Adiós.}
{277}{}{Guarda tus chapas, les servirán a tu escuela. Esto es una donación.}
{278}{}{Gracias, esto será de mucha ayuda para nuestra escuela.}
{279}{}{Adiós.}

{280}{}{¿En dónde puedo conseguir libros viejos?}
{281}{}{Hemos explorado las ruinas de los alrededores junto a nuestros mercenarios, dudo que quede algún depósito de libros viejos por aquí cerca. Pero hay un lugar que los tiene, pero es de acceso restringido: es la base militar en Puerto.}
{282}{}{¿Por qué habrían libros en una base militar?}
{283}{}{Para ser exactos, no son libros, sino sus versiones electrónicas. Sé de esto gracias a la comunicación con los escribas de la Hermandad del Acero. Pero se rehúsan a compartir su conocimiento.}
{284}{}{Que tacaños.}
{285}{}{Quizás tengan sus razones.}
{286}{}{Pero esos libros les pertenecen a toda la humanidad, no a unos pocos privilegiados. ¿Crees que puedas infiltrarte en la base y copiar los textos? Te daré una holocinta vacía para este propósito, a cambio te pagaré.}
{287}{}{No iré hacia allá. Lo siento.}
{288}{}{Está bien, lo haré. Dame la holocinta.}
{289}{}{¡Gracias! Aquí tienes la holocinta. Por el bien de nuestra escuela, debes copiar al menos los textos más importantes y útiles. Buena suerte.}
{290}{}{Adiós.}
{291}{}{Hemos explorado las ruinas de los alrededores junto a nuestros mercenarios, dudo que quede algún depósito de libros viejos por aquí cerca.}
{292}{}{Ya veo, tendré que buscar en un lugar más lejano.}
{293}{}{He conseguido copiar los libros de la Hermandad.}
{294}{}{¡Esas son muy buenas noticias! Necesitamos libros de cualquier tipo, la Hermandad no tiene ningún principio moral por el cual esconderlos del público.}
{295}{}{Aquí tienes la holocinta.}
{296}{}{Te daré 100 chapas a cambio de ella. Muchísimas gracias.}
{297}{}{De nada.}
