{100}{}{Ves a Wang Chong.}
{101}{}{Ves un gran árbol en pleno florecer. El patrón en su corteza es similar al de un rostro. Un momento...}
{102}{}{*Cof cof*}
{103}{}{Es difícil hablar con todo este humo, necesitamos aire fresco, y rápido.}

{110}{}{*Hrrr*}
{111}{}{*Z-z-z*}
{112}{}{Ven aquí, dulce mantis, sí, entra en mi boca.}
{113}{}{Ñam, que insecto tan delicioso...}
{114}{}{Mis raíces detectan a un desconocido...}
{115}{}{Hmm, esos pasos no son nuevos.}
{116}{}{¿Qué es esto? ¿De qué hablas?}
{117}{}{Herbert, Bob, Néstor - han crecido tanto.}
{118}{}{Ya entiendo lo mucho que extrañan el sol.}
{119}{}{Necesitamos más humanos como fertilizante.}
{120}{}{Oh-oh...}
{121}{}{*Suspiro*}

{150}{}{¡Al ataque, mis amigos verdecitos!}
{151}{}{¡Agárrenlos y háganlos pedazos!}
{152}{}{¡Muestren su poder!}
{153}{}{¡Mátenlos con sus afiladas patitas!}

{200}{}{Ah... Uh... *Bostezo* ¿Por cuánto tiempo dormí...? Cielos... Ah, tenemos visitas... Así que por eso me despertaron mis sirvientes.}
{201}{}{¿Quién eres...? Mejor dicho. ¿Qué eres?}
{202}{}{Pero qué... ¡Una planta que habla!}
{203}{}{Soy... Soy Wang Chong, el científico que cultivó estos jardines del paraíso mismo. ¿Y tú eres? Ah, ya lo sé. La gente como tú es atraída por el aroma del néctar igual que una estúpida mariposa, sólo para ser devorada por una planta carnívora. Cometiste un gran error al venir aquí.}
{204}{}{¿Por qué?}
{205}{}{Sabes, si no estuviera tan obsesionado con la ciencia y el futuro de este mundo, me habría ido de aquí hace mucho tiempo. Pero ahora, este es mi hogar, en donde descansaré para siempre. Del polvo venimos y al polvo vamos.}
{206}{}{¿De qué hablas?}
{207}{}{Ah, el ciclo incesante de la naturaleza. No somos más que terrones de barro pegajoso. Mírame ahora, arraigado al suelo donde una vez vagaba libremente como una planta rodadora arrastrada por el viento.}
{208}{}{Hablas mucho para ser una planta.}
{209}{}{Eso es cómico. No puedo usar ni brazos o piernas, pero mi mente sigue ahí. Lo hago lo mejor que puedo para no volverme loco. He tenido mucho, mucho tiempo, para reflexionar acerca de mí mismo y el mundo a mi alrededor.}
{210}{}{Lo siento mucho. ¿Estás adolorido?}
{211}{}{No, ya no. Mi cuerpo es ahora un huésped de esporas y células vegetales. No puedo usar ni brazos o piernas, pero mi mente sigue astuta. Lo hago lo mejor que puedo para no perder la cabeza. He tenido mucho, mucho tiempo, para reflexionar acerca de mí mismo y el mundo a mi alrededor.}
{212}{}{Me entristece verte así. Pero tengo cosas que hacer aquí. Adiós.}
{213}{}{¡No! ¡Espera! Era igual de insensato e imprudente cuando entré a esta cúpula, ansioso de probar el fruto prohibido de los Antiguos. Me apresuré, cometí errores, y ahora este valle es un paraíso para los mutantes. Si esto sigue así, el yermo entero será transformado. Todos presenciarán el nacimiento de un nuevo mundo, pero no habrá espacio para ellos en él.}
{214}{}{Estoy aquí de parte de Néstor. Necesito algunos documentos y químicos para luchar contra la infección.}
{215}{}{No quiero exponerme a esa misma infección. ¿Existe algún medicamento que actúe en su contra?}
{216}{}{¿Infección? ¿Quieres decir que los demás se siguen aferrando a los vestigios del Viejo Mundo? ¡Oh, qué ciego era cuando entré a esta cúpula por primera vez, ansioso de probar los frutos de los Antiguos! Me apresuré, cometí errores, y ahora este valle es un paraíso para los mutantes. Si no le ponemos fin a esto, el yermo cambiará, y no habrá lugar para los humanos en ese nuevo mundo.}
{217}{}{¿Cómo puede ser eso? ¿Acaso no es posible detener la infección?}
{218}{}{Sí, es posible. Pero si los registros del laboratorio y los materiales de la instalación caen en manos de los Seguidores, eventualmente seguirán investigando, y el desastre se repetirá una vez más.}
{219}{}{Entonces, ¿qué sugieres?}
{220}{}{¡Necesitamos destruir TODA la instalación! El fuego detendrá a la infección y así no se esparcirá por el resto del valle. Esta cúpula es su 'criadero' principal.}
{221}{}{Comprendo, debo detener la infección. Lo haré.}
{222}{}{Muy bien. Encuentra los tubos de gas, no será fácil causar un incendio, pero alguien ya lo intentó. Busca su cadáver en los invernaderos y toma sus explosivos.}
{223}{}{Claro. Lo intentaré.}
{224}{}{Eso es demasiado arriesgado. Adiós, Wang Chong.}
{225}{}{Estás perdiendo la cabeza. En el yermo no existe un lugar más colorido y próspero que esta cúpula. Debe de haber una forma de frenar la infección sin destruirlo todo.}
{226}{}{¡Idiota! He buscado formas de limitar la propagación de las esporas, ¡pero no hay forma de saber con certeza si funcionará! ¿Y si la propagación de las mutaciones continúa? Si se extiende demasiado, puede que nunca se detenga. ¡Encuentra las tuberías de gas y Hazlas explotar! Es la única manera.}

{230}{}{*Suspiro profundo*}
{231}{}{*Z-z-z*}
{232}{}{*Hrrr*}
{233}{}{Lo que sea que sea esto, duerme como un tronco... Literalmente.}
