{100}{}{Ves a Alexandra.}
{101}{}{Ves a una chica feliz que no parece entender en dónde se encuentra.}
{102}{}{Lo siento, pero no puedes traer armas aquí.}
{103}{}{Lo siento, pero no puedes entrar con esa armadura.}
{104}{}{Quiero... hnnnn... dormir. Vuelve en la mañana...}

{200}{}{Vaya, ¡hola! Es la primera vez que te veo.}
{201}{}{Soy }
{202}{}{. ¿Y tú?}
{203}{}{Lo mismo digo. ¿Quién eres?}
{204}{}{Me llamo Alexandra Titova. Soy la asistente de Néstor. Encanta de conocerte.}
{205}{}{Ese es un apellido muy raro.}
{206}{}{Que nombre tan ridículo.}
{207}{}{Mis ancestros eran de otra parte del mundo, pero eso ya no importa. Mi apellido no es más que un vestigio del pasado.}
{208}{}{Ya entiendo.}
{209}{}{Un vestigio de la locura, si me lo preguntas.}

{220}{}{¿Te puedo ayudar en algo?}
{221}{}{No necesito nada. Adiós.}
{222}{}{¿Qué está ocurriendo? ¿Por qué hay tanta gente en la plaza?}
{223}{}{Los demás están muy preocupados con la explosión en Puerto Peñasco. No sabemos cómo vamos a sobrevivir sin la ayuda de la Hermandad. Ojalá que se calmen pronto y no se les ocurra empezar una revolución.}
{224}{}{Así que eso ocurre, ya entiendo...}
{225}{}{Necesito medicamentos.}

{230}{}{Háblame de Néstor.}
{231}{}{Pues, es el único doctor de la ciudad. También es un nerd, pero es un buen tipo.}
{232}{}{¿Y qué hay de ti?}
{233}{}{Yo estoy aprendiendo de él, todavía me falta mucho para ser una doctora. Pero sé cómo coser una herida...}
{234}{}{Comprendo.}
{235}{}{¿Qué es este lugar?}
{236}{}{Se trata de la Clínica Caritativa de los Seguidores del Apocalipsis de San Diego.}
{237}{}{Ah, eso explica el olor.}
{238}{}{¡Un hospital de verdad! ¿Entonces puedo recibir atención médica aquí adentro?}
{239}{}{Debemos tratar a cualquiera que lo necesite, además de que llevamos a cabo experimentos y fabricamos medicamentos. Es por eso que huele un poquito mal, pero te acostumbras.}
{240}{}{¿Puedo comprarles medicamentos? Me vendría bien un antídoto, por si acaso.}
{241}{}{Por supuesto, sólo dime lo que necesitas. Pero esperamos que a cambio puedas darle algo útil a nuestro hospital.}
{242}{}{Genial. Lo tendré en mente.}
{243}{}{¡Eres tú! Nosotros la estamos pasando mal.}
{1243}{}{¡Eres tú! Nosotros la estamos pasando mal.}
{244}{}{¿A qué te refieres?}
{245}{}{Imagínatelo, ¡explotó la fortaleza de la Hermandad! Me dijeron que la explosión parecía la de una bomba nuclear. Sin ellos, la economía de Casa Grande irá cuesta abajo. Y tendremos que gastar muchas chapas para proteger la ciudad...}
{246}{}{¿Y?}
{247}{}{Y, eso quiere decir que los precios han subido, incluido el servicio de nuestra clínica.}
{248}{}{Comprendo. Lo tendré en cuenta.}

{250}{}{Oye, ¿no tendrás algo más fuerte que vendajes y estimulantes?}
{251}{}{¿Cómo qué?}
{252}{}{No, no es nada, olvídalo.}
{253}{}{Ya sabes, medicina antigua, de la preguerra. Es mucho mejor que la de hoy.}
{254}{}{Sí, pienso lo mismo que tú. Pero tenemos prohibido vender medicina vieja y otros químicos como el Psico y Esteroides. No se consideran seguros.}
{255}{}{Entonces no vale la pena hablar al respecto. Hablemos de otra cosa..}
{256}{}{Sí, lo sé, pero es eso lo que quiero. ¿De verdad no puedo conseguir aunque sea una muestra? Es para una investigación científica.}
{257}{}{No sé que metas tendrá tu experimento, pero esas son mis instrucciones. Si no te gusta, habla con Néstor.}
{258}{}{Está bien, entonces insistir no servirá de nada. Adiós.}
{259}{}{No digas eso. ¡Te puedo dar un montón de chapas!}
{260}{}{Hm. Necesitas aire fresco, la puerta está por allá.}
{261}{}{Deberías pensártelo de nuevo, si sabes lo que te conviene.}
{262}{}{Bueno, no quiero problemas. Me voy.}
{263}{}{Piénsalo, ¿qué le sirve a tu clínica tener esos medicamentos, si nadie los compra o los usa?}
{264}{}{Sí, tienes razón... Hm, puede que Néstor haga una excepción para ti. Nos faltan chapas.}
{265}{}{Gracias.}
{266}{}{Por favor, haz una excepción. No le diré a nadie.}
{267}{}{Néstor lo permite, se puede decir que ya soy uno de ustedes.}
{268}{}{Necesito una dosis para... cómo se llamaba... un experimento, sí.}
{269}{}{Mis intereses son de exclusivo índole científico, compañera. Los científicos deberían colaborar entre sí, eso lo sabemos los dos.}
{270}{}{Te sorprenderá saber esto, pero esto es un gran problema en Fénix. Yo conozco personalmente a un drogadicto de los barrios bajos.}
{271}{}{Pobrecitos. Y es así como la ciencia sufre gracias a la estupidez de otro. Todos creen que la medicina causa la drogadicción, pero no, es culpa de la gente.}
{272}{}{Por supuesto. Pero, ¿podrías darme una muestra, aunque sea? Es de interés científico.}
{273}{}{No debería seguir hablando de esto. Tengo otra pregunta.}
{274}{}{Diana sabe que no haría nada estúpido.}
