{100}{}{Ves a Carlos.}
{101}{}{Parece ser uno de los campesinos de la Villa, pero se ve... distinto.}
{102}{}{Hola. Estoy feliz de verte.}
{103}{}{No me hables, toda la ciudad te odia.}

{200}{}{¡Qué sorpresa! Me alegra verte, }
{201}{}{.}
{202}{}{¿Cómo te trataron los Seguidores?}
{203}{}{Me recibieron con los brazos abiertos. Son buena gente, a diferencia de los Hojalateros.}
{204}{}{¿Ya te acostumbraste a Casa Nueva?}
{205}{}{Tengo mucho trabajo que hacer por aquí. Además, firmé un contrato de varios años... Bueno, lo marqué con una cruz. Así que ahora tengo un hogar y cómo sobrevivir. No me voy a morir de hambre, lo cuál es bueno.}
{206}{}{Genial, me alegra que estés bien aquí.}
{207}{}{Me dieron un kit de primeros auxilios, pero no creo que sea necesario por aquí. Ten, sé que lo necesitarás más que yo.}
{208}{}{Gracias, Carlos. Nos vemos.}

{210}{}{Hola, }
{211}{}{. Me alegra verte.}
{212}{}{Yo igual. Adiós, Carlos.}
