{100}{}{Ves a Chip.}
{101}{}{Ves a un niño. Parece ser el único.}
{102}{}{¿Eso es un arma? Está bonita. Pero, ¿tienes permiso para llevarla?}
{103}{}{¿Esa es una servoarmadura? ¡Qué chingón! Pensé que Frank me estaba mintiendo.}
{104}{}{¿Qué haces?}
{105}{}{Extraño a Meñique.}
{106}{}{¡Eres malo! ¿Por qué hiciste eso?}
{1106}{}{¡Eres mala! ¿Por qué hiciste eso!}

# Floating phrases
{110}{}{¡Hola, Meñique!}
{111}{}{Meñique, ¡siéntate!}
{112}{}{Que animal más tonto.}
{113}{}{¡Meñique, no!}
{114}{}{¡Estás rayando el piso!}
{115}{}{Meñique, deja de morder los muebles.}
{116}{}{Mi papá me va a castigar...}
{117}{}{Espera, te traeré agua.}
{118}{}{¿Tienes hambre?}
{119}{}{¿Quieres comer algo rico?}
{120}{}{Mira, tengo una pierna de mantis.}
{121}{}{Muy bien, Meñique. Buen chico.}
{122}{}{Aquí tienes un premio.}
{123}{}{¿Quieres más?}
{124}{}{¡Dame la patita!}

{130}{}{¡Meñique!}
{131}{}{Deja de chillar, Meñique.}
{132}{}{Has hecho un desmadre por toda la casa.}
{133}{}{Te van a escuchar los vecinos.}
{134}{}{¡No me rasguñes!}
{135}{}{Me preocupas.}
{136}{}{¿Qué te pasa?}
{137}{}{¿Tienes sed?}
{138}{}{¡Mira lo que hiciste?}
{139}{}{¿Qué te duele?}

{200}{}{Hola. ¿Vienes a ver a mi papá? Está en su oficina.}
{201}{}{En efecto. ¿Eres su hijo?}
{202}{}{Sí, soy Chip.}
{203}{}{De acuerdo.}
{204}{}{¿Y quién es ese?}
{205}{}{Es... Es Meñique. Lo estoy cuidando...}
{206}{}{Hmm. Curioso.}

# Dialogue
{210}{}{¿Qué estás haciendo?}
{211}{}{Pensé que te habían corrido del pueblo.}
{212}{}{Oye, ¿sabías que todos hablan de ti? Eso es genial.}
{213}{}{Meñique ha estado muy alegre, parece que está mejor.}
{214}{}{Cuida a Meñique, por favor.}

{219}{}{Adiós, Chip.}

{220}{}{¿Sabes en dónde está tu papá?}
{221}{}{Debe estar en la oficina. Como siempre. Suele estar sentado ahí con sus papeles, y me echa para que no lo moleste.}
{222}{}{Es mejor que no lo 'molestes'.}

{230}{}{Tienes una mascota muy inusual.}
{231}{}{Se llama Meñique, es un buen chico, pero los demás no lo quieren en el pueblo.}
{232}{}{¿Por qué?}
{233}{}{Se inventan mil cosas. Que es peligroso, que tiene infecciones, que se come los cultivos. No hace nada de eso. Frank es el más enojado al respecto, amenaza con que matará a Meñique siempre que puede.}
{234}{}{Las ratas cerdo sí pueden ser peligrosas.}
{235}{}{¡Pero Meñique no es así! No ha hecho nada malo. Solo rasguña la puerta cuando es de noche. Y hace poco que se enfermó, todos lo quieren ver muerto, pero necesita ayuda.}
{236}{}{Quizás sea lo mejor. Adiós.}
{237}{}{Eso es muy malo. Tú puedes, pequeño.}
{238}{}{Déjame observar a esta criatura, quizás pueda ayudarla a recuperarse.}
{239}{}{Tuve que operar a Meñique, pero ya está mejor.}
{240}{}{¿A poco lo arreglaste? ¡Es cierto! ¡Eres genial! Gracias, muchas gracias. Creo que le agradas, puedes jugar con él si quieres. Pero no te alejes de la plantación, o se irá al desierto.}
{241}{}{Me alegra haberte ayudado. Diviértete con tu amiguito, Chip.}
{1241}{}{Me alegra haberte ayudado. Diviértete con tu amiguito, Chip.}
{242}{}{Eso no es justo.}
{243}{}{Quiero llevar a Meñique a pasear.}
{244}{}{Si quiere ir contigo, no tengo problema. Pero no lo lleves demasiado lejos.}
{245}{}{Gracias, solo caminaremos un poco por el pueblo.}
