{100}{}{Ves a un niño.}
{101}{}{Ves a un niño inesperadamente limpio y arreglado.}
{102}{}{¡No me empujes!}

{110}{}{Hola, salvaje.}
{111}{}{¿De dónde eres?}
{112}{}{¿Jugarás conmigo?}
{113}{}{Mamá y Papá no están.}
{114}{}{¿Por qué tengo que hacer el trabajo de los adultos?}
{115}{}{Tienes suerte, no tienes que trabajar.}
{116}{}{Quiero dormir.}
{117}{}{La noche es linda, pero hay que dormir en la noche.}
{118}{}{¿Tú igual creces plantas?}
{119}{}{Quiero ver otras ciudades.}

{120}{}{Z-z-z}
{121}{}{*Hrrr*}

{130}{}{Tra-la-la, tra-la-la. No te escucho.}
{131}{}{Vuelve al desierto.}
{132}{}{Déjame en paz.}
{133}{}{Dicen que eres un criminal.}
{134}{}{¿Eres un ladrón?}

{1130}{}{Tra-la-la, tra-la-la. No te escucho.}
{1131}{}{Vuelve al desierto.}
{1132}{}{Déjame en paz.}
{1133}{}{Dicen que eres una criminal.}
{1134}{}{¿Eres una ladrona?}
