{100}{}{Ves a un ciudadano de Casa Nueva.}
{101}{}{Ves a un ciudadano. Si lo comparas con la gente de los demás asentamientos, está saludable y bien alimentado.}

{110}{}{Hola. ¿De dónde eres?}
{111}{}{Es mejor que no te pases por la plantación, o pensarán que eres un ladrón.}
{112}{}{Tengo que trabajar y no puedo hablar, lo siento.}
{113}{}{Me encantaría ponerme a charlar, pero no tengo tiempo.}
{114}{}{Sigue las reglas y no tendrás problemas.}

{120}{}{Si no me dejas en paz, voy a gritar.}
{121}{}{¿Estás loco? ¡Es de noche!}
{122}{}{No me toques.}
{123}{}{Aléjate o llamaré a los guardias.}
{124}{}{Eres un maleducado. Todos los forasteros son así...}
{125}{}{No deberíamos estar hablando. Vete.}
{126}{}{Mira, ya hay toque de queda. Nos meterás en problemas.}

{130}{}{¡Hola! ¡Cómo estás?}
{131}{}{Deberíamos unir nuestros pueblos.}
{132}{}{Siéntete como en casa.}
{133}{}{¿Quieres pasarte a cenar?}
{134}{}{Los campesinos debemos cuidarnos los unos a los otros.}

{140}{}{¿Qué haremos ahora?}
{141}{}{Sin la Hermandad, somos presa fácil para los saqueadores.}
{142}{}{¡Álvaro tiene que decirnos qué hacer!}
{143}{}{¡Al carajo con la prohibición de armas!}
{144}{}{No podemos seguir así, tenemos que armarnos.}
{145}{}{Hemos soportado esta opresión durante demasiado tiempo. ¡Basta ya!}
{146}{}{¡Ahora NOSOTROS mandaremos aquí!}
{147}{}{¡Hay que darle un rifle a cada familia!}
