{100}{}{Ves al Alcalde Álvaro.}
{101}{}{Estás viendo a un mexicano de aspecto frágil, bigote fino y expresión compungida.}
{102}{}{Guarda esa cosa de inmediato, no se permiten armas en este pueblo.}
{103}{}{Somos una comunidad pacífica, no hay por qué caminar aquí con esa cosa, asustas a los demás.}
{104}{}{¿Acaso pasó algo? ¡Ve a la cama, ándale! Durante la noche, el pueblo está en toque de queda.}
{105}{}{Me exigen que tome decisiones. ¿Qué quieren que haga? ¡Yo sólo firmaba papeles para la Hermandad!}

#First meeting
{200}{}{¡Ah, una cara nueva en nuestro hogar! Que agradable sorpresa... Saludos. Se podría decir que soy el alcalde de este pueblo. Mi nombre es Álvaro.}
{2200}{}{¡Ah, una cara nueva en nuestro pueblo! ¡A LA MADRE, Y QUÉ CARA! ¿Sabes cómo te tienen que ver los demás? Soy el alcalde de esta ciudad y te pido que te vayas tan pronto como acabes lo que hayas venido a hacer. Y por cierto, me llamo Álvaro.}
{201}{}{Hola, Alcalde.}
{202}{}{Hmm. ¿No te quieres presentar? No voy a obligarte, debes tener tus razones.}
{203}{}{Sí, así es.}
{204}{}{Soy }
{205}{}{. Es un gusto, Señor Álvaro.}
{206}{}{Y tienes buenos modales. Tú y yo nos llevaremos bien.}
{207}{}{Gracias por darme la bienvenida.}
{208}{}{Esto es penoso, alcalde. ¿Llamas a esto un pueblo?}
{209}{}{Eh, sí, sé que no es tan grande como Fénix o su cercanía. No he visto lo que hay más allá del Desierto Sonorense. Pero, piénsalo - ¿no es este lugar pacífico?}
{210}{}{Eso creo.}
{211}{}{Pero este lugar es terrible - no hay civilización..}
{212}{}{¿Puedo saber hacia dónde vas?}
{213}{}{No lo sé, adonde me lleve el viento.}
{214}{}{Bueno, está bien, te creeré. La verdad no es asunto mío.}
{215}{}{Gracias por entenderlo.}
{216}{}{Eso es todo.}
{217}{}{Puedes sentirte agusto para pasar la noche en nuestro pueblo, pero también debes seguir las reglas. No nos vienes a causar problemas, ¿cierto?}
{218}{}{Claro que no. Y agradezco tu oferta.}
{219}{}{Si no me molestan, no muerdo. Recuérdalo.}
{220}{}{Soy parte de la Hermandad del Acero, tengo mi insignia.}
{221}{}{¡Ah, te doy la bienvenida! No te había reconocido... Em... Siempre estaremos felices de recibir a nuestros defensores. Siéntase agusto.}
{222}{}{Gracias.}
{223}{}{De inmediato.}
{224}{}{Voy hacia Puerto Peñasco, tengo cosas que hacer allí.}
{225}{}{Eso me sorprende, los únicos que van hacia allá sin permiso son las caravanas. Pero si no quieres hablar, no voy a insistir.}
{226}{}{Gracias por entenderlo.}
{227}{}{Como dicen, el que mucho habla, mucho yerra.}
{228}{}{No es asunto tuyo.}
{229}{}{Bueno, digamos que de verdad no es asunto mío. De todas formas, recuerda respetar a los demás y evita las peleas - somos un pueblo pacífico.}
{230}{}{Lo siento, no debí haber respondido así - el viaje me ha cansado...}
{231}{}{Si no quieres tener problemas, no los empieces. ¿Bien?}
{232}{}{Fue un gusto hablar contigo, pero tengo mucho papeleo que hacer.}
{233}{}{Nos vemos luego.}
{234}{}{¿Nos llamamos igual? Que chistoso. Estoy seguro de que nos llevaremos bien.}

{239}{}{Eso quiere decir que tu pueblo está condenado. Deberías salir de aquí antes de que venga una turba.}
{240}{}{(mientras está sentado, tiene sus manos en la cabeza e ignora a todos a su alrededor) Agh...}
{241}{}{Te ves terrible. ¿Pasó algo?}
{242}{}{Todo está perdido... Solíamos sobrevivir gracias a la Hermandad del Acero. Y hace poco nos llegó un mensajero con terribles noticias...}
{243}{}{Sí, lo sé - la Hermandad fue destruida. Quizás haya sido una explosión en su almacén de municiones.}
{244}{}{¿Qué deberíamos hacer ahora? ¿Quién nos protegerá? ¿Quién nos dirá qué hacer?}
{245}{}{¿Y qué hay de los Seguidores?}
{246}{}{Ellos no son guerreros y son tan pocos para todos los problemas que hay. No hay esperanza, todo está perdido... todo...}
{247}{}{¡Póntelos bien, Álvaro! Eres el alcalde, todo está en tus manos. Ya estás libre de la opresión y el control total. ¿No crees que eso es genial?}
{248}{}{Sí... claro... ¿Pero qué clase de alcalde soy? Yo sólo hacía papeleo bajo la supervisión de la Hermandad. Ahora tendremos que sobrevivir por nuestra cuenta. No será fácil.}
{249}{}{Tendrás éxito, yo creo en ti.}

#Repeated meeting
{250}{}{Disculpa, pero hoy tengo mucho papeleo que hacer.}
{251}{}{Adiós.}
{252}{}{¿En qué puedo ayudarle, joven?}
{253}{}{Ahí estás, eres nuestro héroe, compadre. ¿En qué te ayudo?}
{1253}{}{Ahí está, usted es nuestra salvadora, señorita. ¿En qué le ayudo?}
{254}{}{Nos vemos}

{260}{}{Se rumorea que aquí ha estado desapareciendo gente. ¿Es cierto eso?}
{261}{}{¿Quién te dijo eso?}
{262}{}{No te lo diré.}
{263}{}{Ah, ¿está claro que aquí nadie desaparece! Sólo unos criminales que escaparon cuando construíamos el pueblo.}
{264}{}{Ya veo.}
{265}{}{Ojalá que no andes por ahí contando rumores tan feos, que no son verdad.}
{266}{}{Claro, no hay problema.}
{267}{}{Lo haré sólo si descubro que estás mintiendo. Adiós, señor alcalde.}
{268}{}{La señora Rosalía. Me dijo que has prohibido la búsqueda de su esposo.}
{269}{}{Que pendej- Es decir, que tontería. No he prohibido la búsqueda, si quiere buscar, que lo haga. Pero seguro no encuentra a su marido porque se fue del pueblo, de tanto que ching- molesta esa señora.}
{270}{}{Ya veo.}
{271}{}{No hay problema - esa bruja se está volviendo loca.}

{280}{}{Por favor, cuéntame sobre este lugar.}
{281}{}{Somos una comunidad pacífica de campesinos. La mitad del pueblo trabaja en las plantaciones y el resto en actividades igual de pacíficas. Los Seguidores tienen su propia escuela por aquí.}
{282}{}{Gracias por la respuesta.}
{283}{}{¿Qué cosechan aquí?}
{284}{}{En su mayoría es elote y agave ardiente, todo el pueblo se sustenta con estas cosechas.}
{285}{}{¿Entonces comercian con las demás ciudades?}
{286}{}{La cosecha sólo nos basta para satisfacer nuestras necesidades y las de asentamientos cercanos. Hay una caravana de Fénix que viene a menudo, por el jarabe de agave.}
{287}{}{Por cierto, ¿qué asentamientos hay por aquí?}
{288}{}{Ya veo.}
{289}{}{Puerto Peñasco está al oeste y Two-Sun al este. Eso es todo, excepto por un par de aldeas pequeñas y unos puestos avanzados aquí y allá. Pero son pasajeros, difícilmente vale la pena tomarlos en cuenta.}
{290}{}{Gracias.}
{291}{}{Este lugar es un verdadero oasis en el desierto. ¿Cómo es esto posible?}
{292}{}{Le agradecemos a los Seguidores del Apocalipsis por su amabilidad e inteligencia. Ellos han desarrollado variedades de plantas que pueden prosperar en un desierto árido.}
{293}{}{¿Las demás ciudades también compran sus cosechas?}
{294}{}{¿Quiénes son los Seguidores?}
{295}{}{Por cierto, ¿quiénes son esos Seguidores?}
{296}{}{Los Seguidores del Apocalipsis... Es un nombre raro, pero ya nos acostumbramos. Ellos llevan a cabo investigaciones científicas, educan a los niños y curan enfermedades. Es gracias a sus experimentos que la plantación está allí. Pero te conviene mucho más hablar con ellos en persona.}
{297}{}{He oído de otro grupo - los Seguidores del Fuego, están en Fénix.}
{298}{}{He escuchado hablar de ellos, pero jamás los he visto. A excepción de las caravanas que vienen de Fénix.}
{299}{}{Por cierto, ¿por qué has vetado el alcohol en este lugar?}
{300}{}{¿Por qué vetaste el alcohol en el pueblo?}
{301}{}{Técnicamente, sólo está vetado el alcohol fuerte. Hay demasiado trabajo que hacer como para distraerse con el entretenimiento. Los campesinos tienen algunos días libres para hacer lo que les de la gana después de cada cosecha.}
{302}{}{Aquí no hay guardias, eso es interesante. ¿Acaso no tienes miedo de los esclavistas o los saqueadores?}
{303}{}{Respecto a tu comunidad 'pacífica' - ¿no le tienes miedo a los esclavistas o los saqueadores?}
{304}{}{¿Por qué deberíamos tener miedo? Nuestros patrones imponen el orden en estas tierras. Somos un pueblo pacífico que sólo hace cosas pacíficas. Ni siquiera tenemos permitido tener armas. Así que no hay nada que temer.}
{305}{}{Sí, tienes todo un oasis en este lugar. ¿Cómo fue que este lugar llegó a ser así?}
{306}{}{¿Patrones? ¿Quiénes son?}
{307}{}{Un momento, ¿no sabes de la base militar en Puerto Peñasco? Entonces no debería hablarte sobre esto, pero que sepas que hay alguien que nos defiende.}
{308}{}{Ya sabes de quién estamos hablando - de la Hermandad del Acero. Ellos son los maestros de estas tierras.}

{310}{}{¿Qué opinas de la Hermandad del Acero?}
{311}{}{Son nuestros patrones, no podríamos sobrevivir sin ellos.}
{312}{}{Ya veo.}
{313}{}{¿Lo dices en serio?}
{314}{}{Te lo digo de corazón.}
{315}{}{Eso es bueno.}
{316}{}{Está bien - supongo que te creeré.}
{317}{}{No hay nada de felicidad o admiración en lo que dices.}
{318}{}{¿Te puedo ser honesto, no? No nos gusta hablarlo, pero la verdad es que aquí todos somos peones. Somos esclavos de por vida, para serte honesto. Para que nos protejan y den un lugar en donde vivir, tendríamos que pagar impuestos que no podemos permitirnos.}
{319}{}{Te escucho...}
{320}{}{No nos alcanzan las chapas, así que la gente firma un contrato de servidumbre y básicamente se venden de por vida.}
{321}{}{Eso es triste.}
{322}{}{Es justo lo que pensaba.}
{323}{}{Pero no es tan malo. Se nos da vía libre en todo lo que no contradiga las leyes y los intereses de la Hermandad del Acero. Y la neta, es que si necesitamos ayuda y protección en la que podamos confiar. Al fin y al cabo, la Hermandad ocupa comida y una ruta comercial. No habría nada de eso sin nosotros.}
{324}{}{¿Y estás bien con esta situación?}
{325}{}{¡No tenemos otra opción! Es gracias a la Hermandad y los Hojalateros que hemos construido un pueblo tan hermoso y cultivado tantas cosechas. Sin su ayuda, seguiríamos sobreviviendo miserablemente como chatarreros en medio del desierto.}
{326}{}{Eso es cierto, no hay mucha elección. No sabría que elegir en una situación así.}
{327}{}{Para mí es difícil entender cómo podrías abandonar tu libertad y entrar a una jaula. Eso es un error. Adiós.}
{328}{}{Sé de la infección y cómo se ha ocultado. Además de la presión en los aldeanos y las reglas, regulaciones y prohibiciones. ¿No es eso tu tiranía si la Hermandad no tiene nada que ver?}
{329}{}{Si no puedes ser un Garra Mortal, al menos puedes fingir ser una rata cerdo. ¿Es eso lo que quieres decir, debilucho?}

{330}{}{¿Sabías que la mascota de tu hijo está muriendo?}
{331}{}{Sí... Ya estoy hasta la madre de los lloriqueos y ruidos que la rata hace por la noche. Le dije a Chip que no debería tener a un animal en casa, pero no me escucha. Y ahora tengo que aguantar y lidiar con las quejas de los vecinos.}
{332}{}{¿Y qué les hizo Meñique a ustedes?}
{333}{}{Bueno... para decir la verdad, nada en particular, sólo los ruidos que hace en la noche. Su apariencia es algo intimidante y eso es suficiente. Si fuera útil, quizás la opinión que tienen los demás sobre Meñique sería distinta.}
{334}{}{Eso es una observación interesante.}

{340}{}{Hay un asentamiento llamado Santa Ana, quieren empezar a comerciar contigo.}
{341}{}{¿Santa Ana? No había oído ese nombre en años. Esa aldea solía evitar cualquier tipo de contacto con nosotros. ¿Qué cambió?}
{342}{}{Digamos que cambiaron de líder.}
{343}{}{Ah, eso sí que es intrigante, voy a alistar una caravana. Quizás podamos encontrar trabajadores en la gente de Santa Ana, nos hacen falta. Gracias por hacérmelo saber.}
{344}{}{De nada.}

{350}{}{Tienes un acento interesante, Álvaro.}
{351}{}{He usado nuestra jerga toda mi vida, sólo he dejado de usarla ahora que estoy más viejo, a veces se me escapa. Eso no es nada raro, en estos lados.}
{352}{}{Ya veo. Perdón si fue incómodo.}
{353}{}{No hay problema, hablas chistoso.}
{354}{}{«Te entiendo, compadre. Te entiendo.»}
{355}{}{Me hace feliz ver a alguien como yo, pero eso no quiere decir que seamos amigos. Al menos aquí, la mitad de la gente tiene algún acento... Pero, me alegra ver a otra persona que tiene mis mismas raíces.}
{356}{}{Genial, hablemos de otra cosa, si no te importa.}
