{100}{}{Ves a Arthur Carrington.}
{101}{}{Ves al arqueólogo del Refugio 27.}

#First dialogue
{200}{}{Es bueno verte, eres un héroe.}
{1200}{}{Es bueno verte, eres una heroína.}
{201}{}{Veo que ya te sientes cómodo. ¿Me darías un minuto de tu tiempo?}
{202}{}{¿Sí?}
{203}{}{Adiós.}
{204}{}{Quiero hacerte otra pregunta.}

{220}{}{¿Qué haces?}
{221}{}{Me pidieron que le enseñara a los niños a leer y escribir. Es una experiencia inusual, pero es mejor que trabajar en la plantación. No me permiten participar en ningún experimento de verdad. Lo que me frustra pues dirigí varios proyectos grandes en el pasado.}
{222}{}{Creo que te ganarás su confianza con el tiempo. Intenta ir lento por ahora.}
{223}{}{¿Qué piensas de los Seguidores?}
{224}{}{Al principio, admiraba su búsqueda por el conocimiento. Pero su amabilidad es desconcertante. No puedes simplemente ayudar a todos y compartir tu conocimiento indiscriminadamente. Muchos no lo merecen, y aunque sea así su estupidez no les permite reconocer los beneficios que les otorga eso.}
{225}{}{Tienen diferentes puntos de vista sobre la misma cosa. Eso está bien.}
