{100}{}{Ves el panel del control climático.}
{101}{}{Ves el panel para controlar el microclima de los invernaderos.}
{102}{}{No funciona.}

{110}{}{El sistema de control climático no funciona. Le debe faltar corriente.}
{111}{}{El sistema de control climático está funcionando normalmente.}
{112}{}{Encendiste la ventilación del domo central.}
{113}{}{Encendiste la ventilación del invernado del este.}
{114}{}{Encendiste la ventilación del invernado del oeste.}
