{100}{}{}
{101}{}{}
{102}{}{!Trampa: cabezas 3D habilitadas.}
{103}{}{!Trampa: cabezas 3D deshabilitadas.}

# Using items on GG
{110}{}{Es un objeto curioso, valdrá la pena encontrarle un uso.}
{111}{}{Esto se aprovecha mejor cuando estás al aire libre.}
{112}{}{Pagarte un sueldo no tiene sentido, pero se siente bien.}
{113}{}{Has recibido una chapa.}
{114}{}{Deberías venderle esto a los advenedizos del área.}
{118}{}{Debes utilizar este objeto desde tus manos.}
{119}{}{Debes utilizar este objeto desde tu inventario o desde tus manos.}

{120}{}{Tras ver tanta chatarra inútil, no puedes evitar pensar que quizás, el mundo necesita otra guerra nuclear.}
{121}{}{Esta actualización sólo funcionará con el módulo lógico de ZAX.}
{122}{}{No parece que seas una bomba nuclear.}
{123}{}{Deberías utilizar estas contraseñas en computadoras y otros sistemas electrónicos.}
{124}{}{Has hecho pedazos a la carta, intentando olvidar todo lo que te haya enlazado con el culto de los Seguidores del Fuego.}
{125}{}{Deberías presentarle esta carta a los Seguidores del Fuego en Fénix.}
{126}{}{Malditos cultistas...}
{127}{}{Ya no quiero pensar en ellos.}
{128}{}{Si bebes este líquido en su forma pura, te dolerá la panza.}
{129}{}{¡Oye, ten cuidado! Casi te rebanas el cuello.}
{1129}{}{¡Oye, ten cuidado! Casi te rebanas el cuello.}

{130}{}{Prender llamas a tu cabellera no es la mejor idea que has tenido.}
{131}{}{Te has cambiado las botas. Esto te permitirá caminar de forma segura sobre sustancias ácidas y ardientes, pero sólo durante unos minutos.}
{132}{}{Por el momento, eso no es necesario, las botas se encuentran en buenas condiciones.}
{133}{}{Por el momento, eso no es necesario, las gafas todavía funcionan.}
{134}{}{Al colocarte estas extrañas gafas, sientes que te has transportado a un mundo distinto.}
{135}{}{La batería de las gafas de visión nocturna se agotan, por lo que se han apagado.}
{136}{}{Para sentirte a la moda, prueba a colocar las gafas de sol en tus manos.}
{1136}{}{Para sentirte a la moda, prueba a colocar las gafas de sol en tus manos.}
{137}{}{Esto todavía no es necesario, la máscara de gas ya da suficiente protección.}
{138}{}{Has reemplazado tu máscara de gas, te protegerá del gas y el polvo durante algunos minutos.}
{139}{}{Sí, deberías colocártelo en la cabeza y asustar a los niños. Eso será divertido.}

# Reset items
{140}{}{A tus parientes no les gustará que andes tirando las reliquias familiares.}
{141}{}{Los mendigos estarán muy contentos de hallar tus chapas.}
{142}{}{Te imaginas como un filántropo, por lo que lanzas dinero a la nada.}
{143}{}{Estas chanclas te ayudarán a caminar sobre las sustancias corrosivas, pero no durante mucho tiempo.}
{144}{}{Has colocado el señuelo.}

# Different lines
{150}{}{El objeto radioactivo que se encuentra en tu inventario está emanando un poco de calor.}
{151}{}{Tu Pip-Boy te muestra tu nivel de exposición: }
{152}{}{No puedes hacer eso en medio del combate.}
{153}{}{Probando, uno, dos. La radio funciona.}
{154}{}{Tus piernas no consiguen soportar el gigantesco peso de tu mochila.}
{155}{}{¡Qué dolor!}
{156}{}{No deberías hacer eso.}
{157}{}{¡Eso podría ser peligroso! Tu imprudencia casi te ha matado, piensa en cómo se sentiría la Abuela Adonisia...}
{158}{}{Deberías buscar zapatos más duraderos, respecto a estos, podrías venderlos en el mercado más cercano.}
{159}{}{Para desensamblar este objeto, te hace falta una mesa de trabajo.}
{160}{}{Necesitas obtener TODAS las partes del mapa.}
{161}{}{Has obtenido todas las partes del mapa del tesoro. Parece que está enterrado cerca de las ruinas del faro.}

# Achievements
{200}{}{Tu reputación se hace más conocida.}
{201}{}{Te estás volviendo más infame.}
{202}{}{Una alta dosis de radiación reducirá tu salud, permanentemente.}
{203}{}{Hay una alta dosis de radiación en tu cuerpo, la cual está reduciendo tu salud otra vez de forma permanente.}
{204}{}{Estoy empeorando.}
{205}{}{Estoy empeorando, MUCHO.}
{206}{}{Al haber sobrevivido un gran número de golpizas, has obtenido el logro de Luchador.}
{207}{}{Creo que me estoy acostumbrando al dolor.}
{208}{}{Debido a tu vil traición, se te ha quitado tu rango en la Hermandad del Acero.}
{209}{}{Debido a tu vil traición, se te ha expulsado de los Rangers.}
{210}{}{Debido a tu vil traición, se te ha expulsado de los Escudos Azules.}
{211}{}{Debido a tu vil traición, se te ha expulsado de los Seguidores del Fuego.}
{212}{}{Tras un largo viaje, te has ganado el título de Pacifista.}
{213}{}{Has perdido tu título de Pacifista. Pero no es demasiado tarde, todavía puedes regresar al buen camino.}
