{100}{}{+}
{101}{}{-}

# Use with hands
{110}{}{La motocicleta no irá a ningún lado si no tiene combustible.}
{111}{}{Tengo que recargarla.}
{112}{}{La motocicleta no arranca, su ordenador está bloqueado y necesita una llave.}
{113}{}{Hmm, parece que necesito una llave, o aplicar lo que sé.}
{114}{}{No es el mejor momento para subirte.}
{115}{}{Tengo algo de lo que ocuparme primero.}
{116}{}{¡Le robaste la motocicleta a los forajidos! No les gustará eso.}
{117}{}{La motocicleta solo tiene espacio para dos pasajeros.}

# Using items
{200}{}{Acceso concedido. La motocicleta está lista para ser conducida.}
{201}{}{Esto no ayudará.}
{202}{}{Este vehículo usa otro tipo de combustible.}
{203}{}{La motocicleta no necesita aceite por ahora.}
{204}{}{No hay que reemplazar ninguna parte en la motocicleta por ahora.}
{205}{}{El ordenador no necesita ser reparado todavía.}
{206}{}{El cráneo se verá genial en el volante, le dejará claro a los demás que no se metan contigo.}
{207}{}{No puedes hacer eso, la motocicleta no es tuya.}
{208}{}{El volante ya tiene un cráneo.}
{209}{}{Reparaste el foco. Ahora iluminará tu camino.}
{210}{}{Ya reparaste la luz de la motocicleta.}
{211}{}{Esto le iría mejor al maletero.}

# Using skills
{300}{}{Ya es necesario hacer eso.}
{301}{}{El ordenador ya está bajo tu control.}
{302}{}{Esto es demasiado difícil para ti, intenta encontrar la llave.}
{303}{}{Ya no hay nada que arreglar.}
{304}{}{Esto no necesita mantenimiento. Pero todavía no revisas si el maletero sí.}
{305}{}{No puedes reparar la motocicleta hasta que sea tuya.}
