{100}{}{Ves una sombra.}
{101}{}{Ves a un hombre desfigurado de piel pálida. Tiene una mirada loca y agresiva.}
{102}{}{¿?}
{103}{}{No querrer matarrte. No me obliiigues.}

#Dialogue
{200}{}{(Al caminar por la alcantarilla, sientes que te observan. Al darte la vuelta, ves una sombra pálida de ojos brillantes. Se está acercando.)}
{201}{}{¡Alto ahí! ¿Quién... qué eres...?}
{202}{}{¡Aléjate! ¿Quién demonios eres?}
{203}{}{¿¡Qué...!? Muere, hijo de...}

{210}{}{(Escuchas una tenebrosa carcajada, y la sombra salta sobre ti...)}

{211}{}{Oh, mierda...}
{212}{}{(Escuchas una risa corta y siniestra. Se asoma un hombre desfigurado con la piel pálida, tiene una mirada penetrante y hambrienta.) Patético humano...}
{213}{}{Escúchame, tú y yo nos parecemos. Mírame la cara... También se ríen de mí.}
{214}{}{¿De qué hablas, fenómeno?}
{215}{}{(Con un tono burlón) Eestúupido humaano...}
{216}{}{Oye... ¡aléjate!}
{217}{}{¿Se ríiiien, verdad? Síiii... Nooos... acordamos. Geente. Soool. Taaantas malas palabras...}
{218}{}{Sí, claro, es feo allá arriba. Todos son tan... eh... maleducados.}
{219}{}{Parece que lo has tenido difícil.}
{220}{}{Pensaron que no podríiiiamos sobrevivir. Pero noooo... (Se ríe) Estúuupidos.}
{221}{}{Entonces, ¿los de arriba te exiliaron aquí?}
{222}{}{(Su rostro se contorsiona con amargos recuerdos) Gueeerra... Bombas... (Hace rechinar sus dientes y agarra su cabeza) ¡Lo recordaaamos! Las casas ardíiiian. La gente arrrdía. Quejidos. Gritos. Nosotros abajo, y sobreviviiiir.}
{223}{}{Eso fue hace mucho, ¿verdad?}
{224}{}{Ya entiendo por qué te ves así.}
{225}{}{(De repente, mira a su alrededor) ¡Lily! Está perdida... (Nuevamente agarra su cabeza, pero de repente recuerda algo) No, murió. La matéee... Sí. Ella sufría... Hiiice lo que debíiia. ¡Lily! ¡Lily! (Sale corriendo, gritando "¡Lily!")}
{226}{}{Eh, ten un buen día.}
{227}{}{Muy bien. Lárgate, fenómeno.}
