{100}{}{Ves a Theodore.}
{101}{}{Estás viendo a un hombre con la piel quemada, lleva un mono de trabajo desgastado con un símbolo de la preguerra.}
{102}{}{¡Seguridad! ¡Un intruso!}
{103}{}{Hablaremos cuando llegue la Retribución Electromagnética de Ralph.}
{104}{}{Tengo mucho que hacer. Gracias por tu visita, viejo. Por cierto, ¿quién eres?}
{105}{}{Ay, no me siento bien...}

{110}{}{ }
{111}{}{¡Jefe! ¡Theodore! ¡Tenemos problemas!}
{112}{}{¿Qué pasó? Intento dormir...}
{113}{}{Ralph y los demás se encerraron en el cuarto de control. ¡Esta vez lo hace en serio!}
{114}{}{¿Ralph? Te dije que lo trajeras aquí. AQUÍ. ¿Te lo tengo que repetir?}
{115}{}{No, jefe, está encerrado y no deja que nadie entre. ¡Hay que hacer algo!}

{200}{}{Vaya, vaya. Aquí está el primer mensajero del mal. ¿O no? No sé que día es, debo darle cuerda al reloj.}
{201}{}{Eh, no entiendo qué quieres decir... No soy de esta ciudad, estoy buscando a mi familia.}
{202}{}{Hmm, ¿lo dices en serio? Bueno, en este siglo he escuchado unas cien historias así. Perdón si dudo de ti, pero estos días viene bien ser cauteloso.}
{203}{}{¿Acaso pasó algo?}
{204}{}{Explotó una de las tuberías del sistema de enfriamiento del reactor. Explotó igual que un gusano asqueroso. Ya cortamos el flujo, pero las reservas del reactor no durarán mucho. Pronto se sobrecalentará y tendremos que apagarlo.}
{205}{}{Eso no suena bien. ¿Puede arreglarse?}
{206}{}{Claro, pero nosotros no podemos. Esto no es una fábrica, es una planta nuclear. Necesitaremos partes y equipo, y encontrarlas no será fácil... (te mira de pies a cabeza) ¿Crees que puedas hacerlo? La paga es buena.}
{207}{}{No, no creo que sea capaz de ello.}
{208}{}{Yo tampoco lo creo, jeje. Sólo encuéntranos los materiales para repararla. Así de fácil. Al sur de aquí hay una fábrica, dirígete hacia allá y pregúntale a los lugareños.}
{209}{}{Me lo pensaré.}
{210}{}{Eso está demasiado lejos. Lo siento, pero no.}
{211}{}{Claro, nunca me vendrán mal unas chapas.}
{212}{}{Genial, cuento contigo, pero mantén nuestro trato en secreto... Hmmm. Esos asquerosos gusanos marinos, intentan morderte con esos dientes de cobre...}
{213}{}{Eh... adiós.}
{214}{}{Y recuerda que no debes decirle a nadie de nuestro trato. Y mucho menos a esos Seguidores del Fuego, están locos.}

{215}{}{Bueno, lo entiendo. Pero si vas hacia allá, o te cruzas con algunas partes que podamos usar, ya sabes con quién hablar.}
{216}{}{Claro. Adiós.}



{220}{}{Sí, sí, te escucho.}
{221}{}{Adiós.}
{222}{}{Estoy esperando los resultados. Recuerda que te pagaremos por esto.}

{230}{}{¿Te puedo hacer algunas preguntas sobre esta central eléctrica?}
{231}{}{No me hagas perder el tiempo, ya te hice un favor al dejarte entrar.}
{2231}{}{¡Tú ya lo sabes todo, rayito de sol!}
{232}{}{Está bien.}
{233}{}{He reparado el sistema de enfriamiento.}
{234}{}{¡Gracias al Amperio, lo conseguiste! No me lo creo. ¿Cómo lo hiciste?}
{235}{}{Tuve que meterle mano el día entero.}
{236}{}{Tienes piquito de oro, normalucho. Pero tu llegada fue un rato después del sabotaje, no creo que sea una coincidencia.}
{2236}{}{Sí que sabes lo que haces, caracortada. Pero tu llegada fue un rato después del sabotaje, no creo que sea una coincidencia.}
{237}{}{¿Cómo que 'sabotaje'?}
{238}{}{Hemos examinado el lugar del accidente. ¿Y qué descubrimos? Que el sistema fue reventado con dinamita. ¿Cómo explicas eso, resbaloso piel suave?}
{2238}{}{Hemos examinado el lugar del accidente. ¿Y qué descubrimos? Que el sistema fue reventado con dinamita. ¿Cómo explicas eso, verdusco y podrido amigo?}
{239}{}{Yo no tuve nada que ver en esto. Tú me dejaste pasar, y luego...}
{240}{}{Basta de tonterías, cariñito. Hagamos una cosa - encuentra a los culpables detrás del sabotaje y veremos si te pagan o no.}
{241}{}{Dame mis chapas, maldito fenómeno. O si no, te enviaré directo con tus ancestros.}
{242}{}{¿Y cómo pretendes que haga eso? ¡Los intrusos pudieron haberse infiltrado por cualquier sitio!}
{243}{}{Bien pensado. Ahora ve a investigar y no me hables si no sabes nada. ¡Jujuju! ¡Es divertido saltar cojeando!}
{244}{}{Bueno... eh, me voy. Adiós.}
{245}{}{¡Yo sé de la ley! ¿Y tú? Así que no vayas a contradecir al oficial a cargo.}
{246}{}{Espera... ¿Qué?}
{247}{}{Tuve suficiente, anciano estúpido. ¡Te haré entrar en razón!}

{250}{}{He averiguado quién saboteó el sistema de enfriamiento.}
{251}{}{Vaya, eso es interesante, es como esas historias de detectives... Y, ¿quién fue?}
{252}{}{Bueno, la verdad es que no sé, sólo me desesperé... Eh, mejor me voy.}
{253}{}{Fue llevado a cabo por los Cardenales Rojos bajo las ordenes de los Seguidores. Y tuvieron la ayuda de tu leal asistente, Ralph.}
{254}{}{¡Que me desenchufen los circuitos! ¿Por qué se metería en esto?}
{255}{}{No lo sé, pero eso fue lo que ocurrió.}
{256}{}{La Iglesia quería forzarlos a un contrato poco favorable. Sobre Ralph... es posible que piense que es su momento de tomar el mando como jefe de la planta.}
{257}{}{¡Seguridad! Traigan a Ralph. Y no le quiten los ojos de encima, no tengan clemencia... Se ha vuelto loco. Igual que una cereza madura. ¿Sabes cuánto trabajo me tomó poner en marcha esta planta eléctrica?}
{258}{}{Eh... no, no sé..}
{259}{}{Fue increíblemente difícil, ¿cierto?}
{260}{}{Oh, sí. Había problemas por doquier. Ralph cree que los cultistas lo harán mejor si toman el mando. Pero por experiencia propia, no puedes dejar que los ideólogos lleguen al poder. Me encanta poner multas a los que se aparcan mal. Te hace sentir tan... poderoso.}
{261}{}{De acuerdo...}
{262}{}{Los ideólogos son peligrosos.}

{270}{}{¿Qué tiene en la cabeza ese viejo libertino? Encárgate de Ralph. Todo este asunto se está volviendo muy peligroso.}
{271}{}{Me ocuparé de ello.}
{272}{}{Lo mejor es hablar con él.}

{280}{}{Aquí está nuestro héroe. Eres el empleado del mes de la central eléctrica, tristemente ya no tengo más premios. Pero no te preocupes, sé cómo recompensarte. Habla con el intendente, te dejará elegir alguna cosa del cuarto de suministros.}
{1280}{}{Aquí está nuestro heroína. Eres la empleada del mes de la central eléctrica, tristemente ya no tengo más premios. Pero no te preocupes, sé cómo recompensarte. Habla con el intendente, te dejará elegir alguna cosa del cuarto de suministros.}
{281}{}{Estoy feliz de haber sido de ayuda.}
{1281}{}{Estoy feliz de haber sido de ayuda.}
{282}{}{Estás mal de la cabeza, después de todo lo visto, es sorprendente que puedas vivir así. Y eres el que está cargo.}
{283}{}{¿Qué? ¿Miasmas? Sí, son un problema. Intenté lavármelo, pero el olor empeoró. No te preocupas por nadie más, sólo por ti.}
{284}{}{Adiós, viejo.}
{285}{}{Ojalá que nunca volvamos a vernos.}
