{100}{}{Ves a un monje.}
{101}{}{Ves a un hombre que lleva puesta una túnica. Claramente no está aquí por casualidad.}
{102}{}{Mereces estar en el desierto, salvaje.}
{1102}{}{Mereces estar en el desierto, salvaje.}
{103}{}{Que el Fuego Santo te bendiga.}
{104}{}{Te arriesgas mucho al venir aquí, mereces que te ahorquen.}

{199}{}{No tengo la menor idea. Fue una coincidencia, supongo. Adiós.}

{200}{}{Saludos, joven. ¿Cómo acabaste entre estos necrófagos?}
{201}{}{No tengo la menor idea. Fue una coincidencia, supongo. ¿Quién eres?}
{202}{}{Ah, yo solo soy un peregrino de la Iglesia del Fuego Santo. Nuestra religión adora el conocimiento antiguo y busca el renacimiento de nuestro mundo. Esta central nuclear es muy importante para nuestra misión. Sería un desastre que cayera en las manos equivocadas.}
{203}{}{No tienes nada que temer, Ralph ha tomado el mando. Piensa en tratar con la iglesia de nuevo. Sé que ustedes quedarán contentos.}
{204}{}{¡Alabado sea el Átomo! ¿Será que debo darte las gracias? ¿Sí? Bueno, el mundo se ha vuelto un lugar mejor gracias a tu ayuda. Se lo agradezco, joven. Ven a nuestra iglesia cuando tengas tiempo.}
{1204}{}{¡Alabado sea el Átomo! ¿Será que debo darte las gracias? ¿Sí? Bueno, el mundo se ha vuelto un lugar mejor gracias a tu ayuda. Gracias, jovencita. Ven a nuestra iglesia cuando tengas tiempo.}
{205}{}{Por supuesto. Adiós.}

{250}{}{Nuestros planes colapsaron, igual que el Viejo Mundo. Fuiste tú, ¿verdad? ¿Por qué haces esto?}
{251}{}{No me agradas tú, ni tu 'iglesia'.}
{252}{}{¿No te agrada la idea del Renacimiento? ¿La idea de un nuevo comienzo para la civilización? ¿O acaso aborreces a nuestra iglesia y sus símbolos? ¿Sus ceremonias? En cualquier caso, eres un animal egocéntrico, una molécula sin valor. La Iglesia le otorgó el Conocimiento al mundo. Con nuestra ayuda, se hizo la luz dentro de cada hogar y una vez más, la gente aprende a leer. ¿Y tú? ¿Qué es lo que intentas conseguir?}
{253}{}{Gracias a tu 'renacimiento', atacaron mi hogar y esclavizaron a mi pueblo. Eso es razón suficiente.}
{254}{}{Entonces, lo único que te motiva es la venganza. En ese caso, no tenemos nada de qué hablar. Un animal como tú no entiende las palabras, únicamente el látigo. Regresa al desierto y sigue viviendo como un salvaje. La gente como tú no encajará en el Nuevo Mundo. Vete de aquí.}
{255}{}{Primero te voy a quebrar el cuello, santurrón.}
{256}{}{Será un placer, esta ciudad está llena de crímenes y pecados. No quiero volver jamás.}
{257}{}{Ralph me pagaba menos. Eso.}
{258}{}{¿Así que las chapas son tu guía y lo que determina tu moralidad? En ese caso, eres un idiota egocéntrico. La Iglesia le otorgó el Conocimiento al mundo. Con nuestra ayuda, se hizo la luz dentro de cada hogar y una vez más, la gente aprende a leer. Dime, ¿qué le darás tú a la ciudad con ese montón de chapas?}
{259}{}{Hice un trato, eso es todo. El mundo se construyó a base de tratos.}
{260}{}{Quizás. O quizás el Viejo Mundo colapsó gracias a la codicia que hoy demuestras. Es por eso que la gente como tú no encajará en el Nuevo Mundo. De ahora en adelante, la Iglesia del Fuego Santo no permitirá tu presencia en esta ciudad. Es mejor que te vayas, ahora. Es tu primer y único aviso.}
{261}{}{Primero, lidiaré contigo.}
{262}{}{Con gusto, no quiero quedarme en una ciudad con tiranos como tú.}
{263}{}{No puedo dejar que vivas.}
