{100}{}{Ves a un necrófago de la central eléctrica.}
{101}{}{Ves a un hombre con la piel quemada y podrida, lleva un uniforme de trabajo hecho jirones que está adornado con un símbolo de la preguerra.}

{200}{}{¡Santo Ohmio! No me asustes así. Esa piel pálida que tienes te hace ver como un fantasma...}
{201}{}{¿Dices que soy un muerto? ¿Te has visto en el espejo?}
{202}{}{Lo siento, no era mi intención.}
{203}{}{Jaja, solo bromeaba. Estamos cerca de la muerte, no nos viene mal bromear así... Soy Herbert, soy el encargado de la sala de suministros.}
{204}{}{¿Suministros? Puede que tengas algo que me interese.}
{205}{}{¡Santo Ohmio! ¡Un nuevo! Me alegra ver que crece el número de mutantes.}
{206}{}{¿Me dijiste mutante? ¡Discúlpate!}
{207}{}{Es bueno ver a otros como yo.}

{210}{}{¿Qué necesitas, viajero?}
{211}{}{Por hoy, nada. Adiós, Herbert.}
{212}{}{Me vendrían bien algunas baterías, ¿tienes algo a la venta?}
{213}{}{Lo siento, pero solo le vendo a caravanas que tengan un contrato.}
{214}{}{Está bien. Adiós, Herbert.}
{215}{}{¿Qué necesitas, compadre?}
{1215}{}{Hola, señorita. ¿Con qué la ayudo?}
{216}{}{Los mutantes deberíamos cuidarnos las espaldas. ¿No crees?}
{217}{}{Pues... Claro. El jefe me prohibió venderle a la gente, pero no dijo nada de los mutantes. Si necesitas algo, dime, intentaré ayudarte. ¿Y sabes qué? Te daré un descuento por ser un necrófago, le cargo más a los normaluchos.}
{218}{}{Muchas gracias, amigo mío.}

{220}{}{Ayudé a tu jefe con un trabajo y me dijo que me pagarías.}
{221}{}{Sí, claro, lo recuerdo. Escoge tu recompensa.}
{222}{}{Déjame pensarlo. Ya vuelvo.}
{223}{}{Claro, firma aquí y aquí... Sólo bromeo. Seguro ni sabes escribir. Por cierto, si necesitas baterías, habla conmigo. El jefe me dio el permiso de comerciar contigo.}
{224}{}{Genial. Lo tendré en cuenta. Nos vemos, Herbert.}
{225}{}{250 chapas.}
{226}{}{Una pistola láser.}
{227}{}{3 dosis de Rad-X.}
