{100}{}{Ves a un niño de los barrios bajos.}
{101}{}{Ves a un niño de los barrios bajos. La vida le ha enseñado mucho.}

{110}{}{Hola.}
{111}{}{¿Tienes un arma?}
{112}{}{Papá prometió conseguir un arma. Entonces mataré a todos los que me trataron mal.}
{113}{}{Cuando crezca, quiero convertirme en un proxeneta.}
{114}{}{¿Cómo estás?}
{115}{}{No te conozco.}
{116}{}{¿Qué quieres?}
{117}{}{No me toques.}
{118}{}{No me permiten hablar con extraños.}
{119}{}{¿Qué vas a darme?}
