{100}{}{Ves a Steve.}
{101}{}{Ves a un fanático de las peleas.}
{102}{}{Dios mío, sabía que los Hojalateros eran buenos, pero sabía que eran capaces de esto...}
{103}{}{La carta me fue de mucha ayuda. Gracias.}
{104}{}{¿También apuestas?}

#First Dialogue
{200}{}{Tú también apostarás en la pelea, ¿no?}
{201}{}{No. Busco a un tipo llamado Steve. Vive en la casa de enfrente.}
{202}{}{Un momento, ¡eres tú! Tus peleas fueron impresionantes. Pero, ¿por qué dejaste tu carrera? Si apuesto por ti, ganaría un montón de chapas.}
{203}{}{Porque eso no dependía de mí.}
{204}{}{Ah, lo entiendo. Al pequeñín no le gusta perder chapas, ¿verdad? Entonces, olvídalo.}
{205}{}{Busco a un tipo llamado Steve, vive en la casa de enfrente.}
{206}{}{Porque no, así que no lo vuelvas a preguntar.}
{207}{}{Ya, cálmate, no quería enojarte.}
{208}{}{Como sea. Sólo dime si conoces a ese tal Steve, el que vive en la casa de la otra calle.}
{209}{}{Soy yo. ¿Qué quieres?}
{210}{}{Soy parte del Sonora Express. Tengo una carta con tu nombre, firma aquí.}
{211}{}{¿Acaso bromeas? Apenas sé leer. ¿Quién me va a escribir?}
{212}{}{Supongo que no eres el Steve al que busco. Adiós.}
{213}{}{Espera, no te vayas. Firmaré, ¿te basta con mi huella? Genial, dámela...}
{214}{}{[Más]}
{215}{}{No sé quién te escribió. Pero el envío cuesta cinco chapas.}
{216}{}{¿Y te tengo que pagar? De ninguna manera. Es obvio que esto es una estafa, y no voy a caer.}
{217}{}{Bueno, entonces tómala. Sólo me está haciendo bulto en la mochila.}
{218}{}{Interesante. Bueno, ten las chapas. Ojalá que valga la pena.}
{219}{}{Aquí tienes.}
{220}{}{No hay problema. Sólo firma y toma la carta.}
{221}{}{¿Qué pasa? ¿También vienes a apostar?}
{222}{}{No, sólo estoy buscando a quien entregarle la carta, pero parece que la perdí.}
{223}{}{Sí, es un problema.}
{224}{}{Eh, iré a buscarla. Adiós.}

{227}{}{Hola. Todavía intento ganarme unas chapas con las apuestas, pero no me resulta. Parece que debería irme de esta ciudad, es fea y muy ruidosa.}
{228}{}{¿Cómo? No es tan mala, es mucho mejor que vivir en un pueblo. Adiós.}
{229}{}{Sí, tienes razón. La vida es mucho más simple y tranquila allá afuera, en el yermo. Nos vemos.}

{230}{}{(toma la carta, la abre y empieza a leer) Eh... veamos...}
{231}{}{¿La carta era para ti, no?}
{232}{}{Es de mi tío en Casa Grande. Parece que quiere verme. Gracias, esto era muy importante.}
{233}{}{¿Qué dice?}
{234}{}{Entonces no hay nada de qué preocuparse. Te deseo lo mejor.}
