{100}{}{Ves a un residente de los barrios bajos.}
{101}{}{Ves a un residente de los barrios bajos de Fénix.}
{102}{}{¡Algún bastardo la mató!}
{103}{}{Quiero hablar, pero tengo demasiada hambre.}
{104}{}{Gracias por darnos de comer, señor.}
{1104}{}{Gracias por darnos de comer, señora.}

{110}{}{¿Cómo estás?}
{111}{}{¿Te va bien?}
{112}{}{No ha cambiado nada, todo sigue igual.}
{113}{}{Puedes volver cuando quieras.}

{200}{}{Hola, ¿te ayudo en algo?}
{201}{}{Dudo que puedas ayudarme.}

{210}{}{¿Quién eres?}
{211}{}{Soy Fred. Me mudé aquí junto a mi esposa, teníamos un rancho de brahmanes en el desierto, pero quebramos por culpa de las sequías y los ataques de los saqueadores, así que veremos si tenemos suerte en la gran ciudad.}
{212}{}{Adiós, Fred.}

{220}{}{¿Por qué vives aquí?}
{221}{}{No es tan malo, es mejor que dormir en la calle. Incluso Vernon hizo un trato con una pandilla para que protejan el sitio. Pero para vivir aquí, hay que pagar un tributo o ganarte un lugar.}
{222}{}{¿Quién es Vernon?}
{223}{}{Es el gerente de la casa, su oficina está al fondo del pasillo, a la derecha.}
{224}{}{¿Qué clase de pandilla?}
{225}{}{Llevan chaquetas de cuero y peinados feos, son unos tipos muy sospechosos. Se apropiaron de un gimnasio viejo hacia el norte. Deberías evitarlos.}
{226}{}{Ya veo.}
{227}{}{¿Cuál era tu nombre?}
{228}{}{¿Quién eres?}

{230}{}{¿Qué puedes contarme de éste lugar?}
{231}{}{Muchos consideran que esto es el peor lugar para vivir de la ciudad. Pero sólo somos un par de campesinos, hasta un lugar así es mejor que estar allá afuera.}
