{100}{}{Ves a un crupier de las cartas.}
{101}{}{Ves a un hombre bien vestido barajando hábilmente las cartas.}
{102}{}{Eh, señor, no puede jugar si tiene puesto... eso...}
{103}{}{Lo lamento, señor, pero no tengo permitido atenderlo.}
{1103}{}{Lo lamento, señorita, pero no tengo permitido atenderla.}

#Acquaintance

{200}{}{(Un hombre pulcro de mirada seria baraja hábilmente unas cartas en la mesa) ¿Jugará al nuclearjack?}
{201}{}{Otro día.}
{202}{}{No, no sé las reglas.}
{203}{}{Claro, pero primero, explícame las reglas.}
{204}{}{Es una variación del blackjack. Consiste en sumar 21 puntos con las menos cartas posibles. Las cartas con bombas nucleares le dan un toque nuevo. Si obtienes 21 puntos, puedes "bombardear" el mazo. Necesita más inteligencia que la ruleta o las tragaperras. Y la apuesta es más alta si te arriesgas.}
{205}{}{Por supuesto.}
{206}{}{¿Jugarás?}
{207}{}{Sí.}
{208}{}{No.}

#Betting

{210}{}{Empezamos. Pongan sus apuestas.}
{211}{}{ fichas)}
{212}{}{No jugaré.}
{213}{}{Me encantaría jugar, pero no tengo fichas.}
{1213}{}{Me encantaría jugar, pero no tengo fichas.}
{214}{}{Apostaré 10 fichas.}
{215}{}{Apostaré 20 fichas.}
{216}{}{Apostaré 30 fichas.}
{217}{}{Apostaré 40 fichas.}
{218}{}{Las apuestas ya están. Aquí están sus cartas.}
{219}{}{Empecemos.}

{220}{}{¿Me recuerdas cuál es el último puntaje?}
{221}{}{El puntaje es de }
{222}{}{ a }
{223}{}{ a tu favor.}
{224}{}{ a favor del casino.}
{225}{}{Bien. Sigamos.}
{226}{}{Apostaré 50 fichas.}

{230}{}{(El crupier coloca dos cartas cara abajo, coloca una boca arriba, que tiene un valor de }
{231}{}{ puntos)}
{232}{}{Dame dos cartas.}
{233}{}{(Te dieron un par de cartas con un valor de }
{234}{}{ puntos)}
{235}{}{[Más]}
{236}{}{(Tus cartas tienen un valor de }
{237}{}{ puntos. Las cartas del crupier tienen }
{238}{}{ puntos.) ¿Qué harás?}

{240}{}{Me retiro.}
{241}{}{El primer jugador se retiró. Perdiste la mitad de la apuesta.}
{242}{}{Adiós, caballeros.}
{243}{}{Doblo la apuesta.}
{244}{}{Doblar la apuesta sólo se puede hacer una vez en la partida.}
{245}{}{Doblar la apuesta.}
{246}{}{[Sigue jugando]}
{247}{}{Paso.}
{248}{}{El primer jugador ha pasado. Seguimos con la partida...}
{249}{}{[Sigue jugando]}
{250}{}{Más.}
{251}{}{El primer jugador roba una carta...}
{252}{}{[Sigue jugando]}

{260}{}{¡Nuclearjack para el Jugador 1! ¿Te gustaría jugar de nuevo?}
{261}{}{No, gracias.}
{262}{}{Claro que sí.}
{263}{}{Nuclearjack para el casino. Perdiste tu apuesta. ¿Quieres asegurarte?}
{264}{}{Sí.}
{265}{}{No, no es buena idea.}
{266}{}{Perdiste, Jugador 1. Perdiste la apuesta, ¿quieres asegurarte?}
{267}{}{Casino: Pierde. ¿Quieres seguir?}
{268}{}{Empate. Los jugadores mantendrán sus apuestas. ¿Quieres seguir?}
{269}{}{Alcanzaste al límite de cartas.}
