{100}{}{Ves a Verónica.}
{101}{}{Ves a una cantante muy bonita.}
{102}{}{Está muy ocupada como para hablar contigo.}

# NOTA DEL TRADUCTOR AL ESPAÑOL: Originalmente era "Nature Boy" de 1947, pero la cambié a Cien Años de Pedro Infante
{110}{}{~ Pasaste a mi lado ~}
{111}{}{~ Con gran indiferencia ~}
{112}{}{~ Tus ojos ni siquiera, voltearon hacia mí ~}
{113}{}{~ Te vi sin que me vieras ~}
{114}{}{~ Te hablé sin que me oyeras ~}
{115}{}{~ Y toda mi amargura, se ahogó dentro de mí ~}
{116}{}{~ Me duele hasta la vida, saber que me olvidaste ~}
{117}{}{~ Pensar que ni desprecio ~}
{118}{}{~ Merezca, yo de ti ~}
{119}{}{~ Y, sin embargo, sigues ~}
{120}{}{~ Unida a mi existencia ~}
{121}{}{~ Y si vivo cien años ~}
{122}{}{~ Cien años, pienso en ti ~}

# NOTA DEL TRADUCTOR AL ESPAÑOL: Originalmente era Mexicali Rose/Rosa de Mexicali de 1923, pero la cambié a Adonde irán de María Luisa Landín
{150}{}{~ Yo quisiera saber, a dónde irán a dar ~}
{151}{}{~ Las tristezas del mundo, los cantos y los sueños ~}
{152}{}{~ A dónde irán también, todos nuestros lamentos ~}
{153}{}{~ Nuestros tristes juramentos, quién sabe a dónde irán ~}
{154}{}{~ A dónde irán las almas, las almas que han sufrido ~}
{155}{}{~ Las almas que han tenido, un infierno, esta vida ~}
{156}{}{~ Sólo el amor sincero, sí tiene a dónde ir ~}
{157}{}{~ Él va con Dios al cielo, dónde nunca podrá morir... ~}

# Dialogue
{200}{}{Hola.}
{201}{}{Adiós}

{210}{}{Hola.}
{211}{}{Adiós.}
