{100}{}{Ves a la cajera.}
{101}{}{Estás viendo a una cajera, sorprende con lo eficiente que es. Parece que fue bien entrenada en cada una de sus tareas.}
{102}{}{L-lo siento, pero debe quitarse eso... V-voy a llamar a seguridad...}

{105}{}{¡Seguridad! ¡Se metió un bandido!}
{106}{}{¡Seguridad! ¡Alerta de intruso!}
{107}{}{Sal de aquí, de inmediato.}
{108}{}{No puedes estar aquí, sólo se permiten a los trabajadores.}
{109}{}{}

# First dialogue
{200}{}{Buenas, caballero. ¿Es su primera vez aquí?}
{1200}{}{Hola, señorita. ¿Es su primera vez aquí?}
{201}{}{Sí, ¿me puedes explicar las reglas del casino?}
{202}{}{Los crupiers de cada juego le explicarán las reglas. Mi trabajo es intercambiar chapas por fichas, dentro de nuestro casino son utilizadas como dinero. Siempre podrá cambiarlas de vuelta, sólo debe hablar conmigo.}
{203}{}{Entiendo.}
{204}{}{No realmente. Me llevo bien con Don Diego, recuérdalo.}
{205}{}{Ah, lo lamento, nadie me habló de usted. Pero recuerde que las reglas del casino son las mismas para todos, incluidos los amigos de Don Diego.}
{206}{}{Hm. Ya veo.}
{209}{}{Soy miembro honorario del club, deberías hacer una excepción, creo yo.}

# Re-dialogue
{210}{}{¿En qué puedo ayudarle?}
{211}{}{Gracias, eso es todo.}
{212}{}{Em... ¿sí?}
{213}{}{¿El casino sigue abierto?}
{214}{}{Oh, por supuesto. Aún hay reparaciones en el interior dada la explosión de la Catedral, pero puede seguir disfrutando como de costumbre... si es que ignora el desorden.}
{215}{}{¿Desastre? ¿Te das cuenta de que vivimos en un yermo post-apocalíptico, cierto? Nadie se molestará con un poco de desorden.}
{216}{}{¿Así que el casino estará todo mugroso? Suficiente, me voy.}
{217}{}{Lo lamento, pero no tengo permitido atenderle. Sólo puedo intercambiar sus fichas si le queda alguna. Por favor, hable con el gerente si tiene algún problema.}
{218}{}{¿¡Qué!? El servicio de este lugar es terrible.}
{219}{}{Entonces me iré a otro casino. Adiós.}

# Disclosure of goods for collateral
{220}{}{¿Puedo hacer un depósito o intercambiar algunas cosas?}
{221}{}{Me temo que eso no está en el mejor interés del casino. Preferimos las chapas, pero a veces hacemos excepciones.}
{222}{}{Bien, olvídalo.}
{223}{}{¿Será que los amigos de Don Diego se encuentran entre esas excepciones?}
{224}{}{Por supuesto, podemos hacer una excepción por ti. Pero ten en cuenta que el límite de chapas para ese propósito está restringido.}
{225}{}{Gracias, lo tendré en cuenta.}
{226}{}{Sí, pero no me han hecho saber que *tú* eres una excepción.}
{227}{}{No importa.}
{228}{}{Soy comerciante, puedo asegurarle que hacer negocios será conveniente.}
{229}{}{Ya veo, entonces creo que podemos hacer una excepción contigo. Pero tenga en cuenta que el límite de chapas para ese propósito está restringido.}
{230}{}{Gracias, entonces recordaré que tienes chapas.}
{231}{}{Te creo, pero en nuestro casino, preferimos las chapas. Puedes intercambiar tus objetos en el mercado de afuera.}
{232}{}{No deberías rechazar mi oferta.}
{233}{}{¿Acaso mi nombre no significa nada en esta ciudad?}
{234}{}{Claro, tiene toda la razón. De ahora en adelante puede contar con un depósito.}
{235}{}{Gracias, entonces recordaré que tienes chapas.}
{236}{}{Lo siento, pero tu reputación no significa mucho en esta ciudad.}
{237}{}{¿Qué quieres decir, perra?}
{238}{}{Lo siento, pero no puedo ayudarle.}
{239}{}{De acuerdo.}

# Game denial
{240}{}{Lamento informarle que el gerente me dijo que no puedo atenderle más.}
{241}{}{¿Cómo? ¿Ya no podré jugar aquí?}
{242}{}{Está loco. ¿Qué significa eso?}
{243}{}{Lo siento, pero esas son mis ordenes. Por favor, dirija sus quejas al gerente. Puedo intercambiar las fichas que le queden, pero tengo prohibido entregarle fichas nuevas.}
{244}{}{En ese caso, iré a hablar con el gerente. Ya vengo.}
{245}{}{Ya era obvio que este lugar tampoco era honesto. Maldito casino...}
{246}{}{¡Espere! Em, lo siento... señor...}
{1246}{}{¡Espere! Em, lo siento... señorita...}
{247}{}{¿Pasa algo?}

# Exchange
{250}{}{Quiero intercambiar mis chapas por fichas.}
{251}{}{¿Cuántas chapas le gustaría intercambiar?}
{252}{}{10 chapas.}
{253}{}{50 chapas.}
{254}{}{100 chapas.}
{255}{}{500 chapas.}
{256}{}{1000 chapas.}
{257}{}{Hm, ninguna.}
{258}{}{Aquí tiene. (has recibido fichas del casino a cambio de tus chapas)}
{259}{}{Gracias.}
{260}{}{No tiene las chapas suficientes.}
{261}{}{Entiendo.}
{262}{}{Aquí tiene. (has recibido chapas a cambio de las fichas del casino)}
{263}{}{Gracias.}
{264}{}{No tiene las fichas suficientes.}
{265}{}{Gracias.}
{266}{}{No tiene el dinero suficiente.}
{267}{}{Todas mis chapas.}
{268}{}{Aquí tiene. (has recibido chapas a cambio del dinero de la preguerra)}
{269}{}{Gracias.}

{270}{}{Quiero intercambiar mis fichas por chapas.}
{271}{}{¿Cuántas fichas quiere intercambiar?}
{272}{}{10 fichas.}
{273}{}{50 fichas.}
{274}{}{100 fichas.}
{275}{}{500 fichas.}
{276}{}{1000 fichas.}
{277}{}{Pensándolo bien, no quiero.}
{278}{}{Todas mis fichas.}

{280}{}{¿Por qué son tan importantes las chapas?}
{281}{}{Las chapas son una moneda, similar al dinero de la preguerra. Se utilizan para intercambiar bienes, pero a diferencia de los dólares, los Seguidores del Fuego establecen la tasa de cambio de las chapas. Es una de las sabias ideas que los Seguidores trajeron a Fénix.}
{282}{}{Entonces, ¿aceptan dinero de la preguerra?}
{283}{}{Sí, es posible. Los dólares no tienen el mismo valor que antes, pero traen cierta incertidumbre hacia la tasa de cambio de las chapas. ¿Quieres intercambiar los tuyos?}
{284}{}{No, gracias. Pero lo recordaré.}
{285}{}{}
{286}{}{Sí, suena bien.}
{287}{}{Es una posibilidad. Pero ten en cuenta que su valor cayó a la mitad de lo que era. Los Seguidores del Fuego solían controlar la tasa de cambio, pero desde el incidente de la Catedral, no pueden seguir cumpliendo eso.}
{288}{}{Entiendo.}
{289}{}{Intercambiaré todos mis dólares.}

{290}{}{Quiero intercambiar dinero de la preguerra por chapas.}
{291}{}{¿Cuántos dólares quiere cambiar?}
{292}{}{1 dólar.}
{293}{}{2 dólares.}
{294}{}{3 dólares.}
{295}{}{4 dólares.}
{296}{}{5 dólares.}
{297}{}{10 dólares.}
{298}{}{50 dólares.}
{299}{}{Ninguno.}
