{100}{}{Ves a un cliente.}
{101}{}{Estás viendo a un cliente. Ha bebido más de la cuenta y está empezando a ponerse demasiado hablador.}

#Before drinking alcohol
{200}{}{(Ves a un hombre sonriente con un gran bigote. Su piel bronceada y su sombrero de vaquero delatan su afición por los viajes, y su mirada sobria insinúa que no hay nada de alcohol en su sistema.)}
{201}{}{[Siéntate junto a él en la barra]}
{202}{}{(se gira a verte con una sonrisa amistosa) Oye, compadre, ¿me invitas un trago? Ese bandido de ahí, el que tiene un sólo brazo, me quitó todo mi dinero.}
{1202}{}{(se gira a verte con una sonrisa amistosa) Oiga, señorita, ¿me invita un trago? Ese bandido de ahí, el que tiene un sólo brazo, me quitó todo mi dinero.}
{203}{}{Apenas nos conocemos, ¿y quieres que te invite algo? No estoy loco, señor.}
{1203}{}{¿Le pides un trago a una señorita? ¿No te da vergüenza?}
{204}{}{Lo que tú digas, compadre. Pero si te sientas junto a alguien en un bar, prepárate para que te pidan un trago.}
{1204}{}{Usted gana, señorita. Lamento si este viejo fue torpe. Pero esa maldita máquina tragaperras me quitó mis últimas chapas. Tampoco puedo invitarte un trago, belleza.}
{205}{}{Ten cuidado o la siguiente vez podríamos llegar a los golpes.}
{1205}{}{Adiós, perdedor.}
{206}{}{Claro que no, piérdete.}
{207}{}{Lo siento, pero no puedo. Quizás otro día.}
{208}{}{Lo entiendo.}
{209}{}{[Vuelve a tus asuntos]}
{210}{}{De acuerdo, te traeré un trago...}
{211}{}{Alguien de por aquí las debe tener de acero. Por cierto, mi petición sigue en pie.}
{1211}{}{Alguien de por aquí debe tener nervios de acero. Por cierto, mi petición sigue en pie.}

#After drinking alcohol
# Quote from the movie "Prison Rock" 1957: "It's like angels are dancing on the tip of the tongue. It's a shame to even swallow this bourbon."
{220}{}{(toma un sorbo) Ah, es como si los ángeles estuvieran bailando en la punta de mi lengua. Es una pena beberlo, ojalá durara para siempre. }
{221}{}{Lo dices como si tuvieras mucha experiencia.}
{222}{}{Ah, este viajero ha recorrido muchas millas alrededor de Fénix y las rutas de caravanas. ¿Te interesa?}
{223}{}{La verdad es que no, pero, te escucho.}
{224}{}{Claro. Háblame acerca de tus viajes.}
{225}{}{Gracias por el trago.}
{226}{}{Diviértete, yo iré a tomar aire.}
{227}{}{Espero lo disfrutes, amigo.}
{228}{}{Quizás deberías disfrutarlo callado.}
{229}{}{Gracias, un forastero que comparte contigo no es algo que veas todos los días.}

#Story
{230}{}{Yo trabajo para las caravanas como mercenario, y a veces viajo sólo en busca de... riquezas. Todos me conocen como un tirador excelente y un superviviente del desierto. Así que, siempre consigo trabajo si lo necesito. Pero, viajar... cada vez se hace más peligroso.}
{231}{}{¿A qué te refieres? ¿Por qué ese cambio?}
{232}{}{¿Solía ser seguro?}
{233}{}{Las tormentas de polvo cada vez son más frecuentes. Algunos dicen que hace años, era peor. Pero hoy en día, si el tiempo es malo, pueden desaparecer asentamientos enteros, y si te atrapa una tormenta en medio del desierto, tus probabilidades de sobrevivir son como tirar una moneda, en el mejor de los casos. Y, ¿qué crees? También hay tornados gigantes y del oeste vienen nubes de polvo brillante, es venenoso. Es como si la naturaleza no quisiera dar el mundo de vuelta a los hombres.}
{234}{}{Sí, no hay nada peor que una tormenta de polvo de las graves.}
{235}{}{Ja, ¿no se supone que eres un superviviente? ¿Te da miedo el viento, en serio?}

{236}{}{Las tormentas de polvo no son lo peor que te encontrarás en el yermo. Las puedes ver y las evades. Pero, ¿y la gente? Eso es mucho peor. En las rutas de caravanas, solíamos hallar cuerpos - los saqueadores les habían quitado todo lo valioso, incluyendo su carne. No dejaron nada.}
{237}{}{Yo también lo haría. Es el yermo, la comida es comida, ¿no?}
{1237}{}{Yo también lo haría. Es el yermo, la comida es comida, ¿no?}
{238}{}{¿En serio? Yo no lo haría. La carne humana es más peligrosa que las hojas o los bichos, pero, si te estuvieras muriendo de hambre, yo no juzgaría.}
{239}{}{¿Por qué me cuentas esto?}
{240}{}{Eso es asqueroso. Aunque te estés muriendo de hambre, ¿qué clase de salvaje haría algo así?}
{241}{}{Hay muchos salvajes allá afuera, en especial esa banda de forajidos en la Ruta 10. Actúan como si la carretera fuera suya, les pagas el peaje, o mueres. Algunos ni siquiera te lo preguntan - simplemente te lo quitan todo.}
{242}{}{¿Por qué me cuentas esto?}
{243}{}{Exageras. El desierto no puede ser tan malo.}
{244}{}{Ah, claro que hay lugares 'civilizados' allí afuera, pero los puedes contar con una sola mano. La mayoría no dejan pasar a los viajeros y mantienen un perfil bajo, intentando sobrevivir en las peores condiciones.}
{245}{}{¿Por qué me cuentas esto?}

{250}{}{(suspira y toma un sorbo después de una pequeña pausa) Bueno... hubo una vez en la que...}
{251}{}{Anda, compadre, te escucho. Para eso es un bar.}
{1251}{}{Oh, gran superviviente, ¿qué es lo que pesa su consciencia?}
{252}{}{Ja, pensé que ya habíamos terminado de hablar, pero, apenas empezamos.}
{253}{}{...Habíamos ido hacia el pueblo de Gila Bend para comerciar, pero el lugar estaba abandonado. Tuvimos que regresar a Fénix con las manos vacías, en el camino de vuelta se nos acabaron los suministros, y... el desierto no nos dio ningún respiro. No habían animales, ni plantas. Nada más que calor, además, las arenas estaban cambiando de sitio y eso nos confundía al viajar.}
{254}{}{¿Cómo salieron de ahí?}
{255}{}{Nos topamos con este tipo que había venido de Fénix, salió de ahí y buscaba un nuevo hogar. A diferencia de nosotros, él tenía comida.}
{256}{}{¿Y qué pasó? ¿Lo asaltaron?}
{257}{}{Uno de los guardias... perdió la cabeza. No pudo aguantar el hambre y apuñaló 27 veces al pobre tipo. Y nosotros sólo... miramos. No movimos ni un dedo.}
{258}{}{Oye, finalmente, pudieron salir de ahí. No puedes controlar las acciones de otras personas.}
{259}{}{¿Eso piensas? No estoy seguro. Pero, ¿sabes qué? Me alegra que decidí hablar contigo. Me siento un poco mejor... A pesar de que... pude haberlo detenido... Y quizás... si lo hubiera planeado mejor, no nos hubiéramos estado muriendo de hambre en primer lugar. Esto me atormentará por un largo tiempo.}
{260}{}{En el yermo, la supervivencia es la única regla que hay, la moral no significa nada. Intenta olvidarlo.}
{261}{}{Después de escuchar esto, prefiero pretender que no te conozco. Piérdete, bandido.}
{262}{}{¿Cómo sabes cuántas veces lo apuñaló?}
{263}{}{Las estaba contando.}
{264}{}{Y te quedaste ahí parado... No me sorprende que te estés pudriendo en este bar. Ojalá que nunca encuentres la paz.}
{265}{}{Sí... tienes razón. Pero, los bares son para eso, ¿que no? Para hablar de cosas que te rompen por dentro.}
{266}{}{Olvídalo, yo iré a... jugar a la ruleta.}
{267}{}{Ojalá que nunca volvamos a vernos.}

{268}{}{Nos cruzamos con un motel. Era viejo, pero no parecía estar abandonado del todo. De hecho, las puertas del restaurante estaban abiertas, tenía un póster de... Nuka Cola, y nos atraía.}
{269}{}{¿Había alguien adentro?}
{270}{}{Había comida y agua, nos estábamos muriendo de hambre y teníamos la garganta seca... todos entraron de inmediato, bebieron y comieron como locos. Yo intenté advertirles, pero resulta que el agua estaba... envenenada... y el sitio estaba lleno de trampas. Fui el único que salió con vida.}
{271}{}{¿Quién pudo haber hecho algo así?}
{272}{}{¿Saqueadores? ¿Caníbales? ¿O quizás las almas de aquellos que murieron durante la Gran Guerra? No lo sé. Pero hay... historias... rumores acerca del motel fantasma.}
{273}{}{A pesar de todo, mantuviste la calma en un lugar tan horrendo y sobreviviste.}
{274}{}{¿En serio crees que debería sentirme orgulloso de eso? Supongo que escogí bien a una persona con quien beber. Me siento un poco mejor. Pero desearía que hubiera podido salvar a mis demás amigos de la caravana.}
{275}{}{Fue un momento difícil. No te agüites.}
{276}{}{Bueno, no sé si pueda confiar en ti. Es difícil de creer.}
{277}{}{O quizás, nunca hubo un motel. Fuiste la única persona que sobrevivió... quizás todo fue una trampa que les colocaste tú.}
{278}{}{No eres el primero que dice eso. Los demás hablan a mis espaldas, diciendo que abandoné o que incluso maté a mis amigos. Pero eso no tiene sentido, en el desierto, es más difícil sobrevivir sólo que con un grupo.}
{1278}{}{No eres el primero que dice eso. Los demás hablan a mis espaldas, diciendo que abandoné o que incluso maté a mis amigos. Pero eso no tiene sentido, en el desierto, es más difícil sobrevivir sólo que con un grupo.}


{280}{}{No puedo olvidar esa historia del motel fantasma. ¿En dónde queda, exactamente?}
{281}{}{Ya te puedes imaginar lo asustado que estaba yo. Ese maldito motel está allá afuera, en medio del desierto, escondido entre las arenas. Ni siquiera pude encontrarlo en un mapa - solo sé que está... acechando... en algún lado al suroeste de Fénix.}
{282}{}{Sólo quería saber como evitar esa pesadilla. Cuídate.}
{283}{}{¿Te ayudaría si fuera a buscarlo?}
{284}{}{No hay manera de revivir a los muertos, pero puede que salves a otros viajeros. Sólo ten cuidado - ese lugar está... maldito, y sería una pena que tu alma también se pierda allí.}
{285}{}{No puede estar maldito, no seas así.}
{286}{}{¿Me puedes recordar en qué dirección estaba el motel?}
{287}{}{Está allá afuera, en algún lado del desierto. No podría señalarlo en un mapa. Solo sé que está en el suroeste de Fénix - a unos tres o quizás cuatro días.}
{288}{}{Claro. Gracias.}
{289}{}{Sobre ese motel tenebroso del que me hablaste... Era un infierno, me da escalofríos si pienso en él.}
{290}{}{¡¿Cómo!? ¿Lo encontraste?}
{291}{}{Sí, los dueños eran una familia de caníbales. Esos bastardos fueron astutos, pero ya no le harán daño a nadie.}
{292}{}{Eso es un alivio... Siento que me han quitado un peso del alma. De verdad me alegra que hayas vengado a mis amigos - y probablemente a un montón de otras pobres víctimas. Te lo agradezco, en serio. Te invito esta botella.}
{293}{}{Para eso estamos.}

