{100}{}{Ves a un viejo amigo.}
{101}{}{Ves a uno de los Seguidores del Fuego.}

{200}{}{(Ves a alguien que te resulta familiar, solía espiar a los rangers; ahora se ve triste y sin fuerzas, su mirada está apagada, y su mala educación es cosa del pasado)}
{201}{}{Vaya, vaya, no esperaba verte aquí.}
{202}{}{(Sus ojos se ven nublados y se levantan con pesadez, apenas distinguiéndote) Tú... te recuerdo. El Fuego Santo nos tuvo que haber reunido ese día. Gracias a ti, encontré a los Seguidores. Gracias.}
{203}{}{Eh, lo que tú digas. Me alegra haberte ayudado 'espiritualmente'.}
{204}{}{Jamás pensé que llegarías hasta acá. Qué sorpresa.}

{210}{}{Tengo que rezar. Por favor, déjame.}
{211}{}{Adiós.}

{220}{}{¿Cómo escapaste de la Presa Parker?}
{221}{}{No me preguntes eso. Es cosa del pasado.}
{222}{}{Entonces dejaré que sigas... rezando, o lo que sea.}
{223}{}{¿Cómo te va, ahora que eres un acólito de los Seguidores?}
{224}{}{Trabajamos y rezamos. Es todo lo que un hombre necesita. Hasta el día en el que esté listo para un trabajo más importante. Sólo mi mentor puede determinar eso.}
{225}{}{Hmm, déjame verte los ojos.}
{226}{}{¿Qué haces? No andes tocando a la gente, campesino.}
{227}{}{Está bien... adiós.}
{228}{}{¿Te están drogando, verdad?}
{229}{}{Sí... nos dan pastillas con el almuerzo, para que nos relajemos. Es parte de nuestra iniciación, ¿sabes? Tenemos que sacar la arrogancia de nuestras mentes... o eso me dijo mi mentor... Agh, necesito ir al baño...}
{230}{}{Me parece... bien. Nos vemos.}
