{100}{}{Ves a un vagabundo.}
{101}{}{Ves a un vagabundo que deambula por la plaza sin rumbo.}
{102}{}{Ves a un vagabundo harapiento que alaba a la iglesia.}
{103}{}{Ves a un enfermo que apenas puede caminar por el área.}
{104}{}{Ves a un refugiado que camina sin rumbo alguno.}

#Floating lines
#- beggar
{110}{}{Déjame sólo, por favor.}
{111}{}{Ya no sé que haré.}
{112}{}{La gente como yo no tiene ninguna oportunidad en esta ciudad.}
{113}{}{¿Te importa si me acuesto aquí?}
{114}{}{Quiero escapar de mi vida, pero no sé cómo.}
{115}{}{El Fénix vuela... y yo me caigo.}
{116}{}{¿Tienes comida para una pobre alma como yo?}
{117}{}{Unas chapas, por favor. Te juro que las pagaré de vuelta.}
{118}{}{Tengo un bebé, necesito dinero para su medicina. Ayúdame, por favor.}
{119}{}{Me muero de hambre, hasta una cola de rata sería suficiente.}
{120}{}{¿De dónde eres? Si te me quieres unir, no tengo más espacio.}
{121}{}{Estoy esperando a los Seguidores, nos dan comida.}
{122}{}{A veces la catedral viene a darnos sus migajas, después de la cena.}
{123}{}{Pero para eso hay que besarle las patas al cura.}
{124}{}{¡Alabado sea el Fuego! Aquí somos todos hermanos, ¿cierto? Ves, yo igual soy un creyente.}

#- adept
{130}{}{Quiero ser un acólito como ellos, pero no me dejan.}
{131}{}{Lo juro, ¡yo también seré un acólito!}
{132}{}{Tienes que rezar mucho para que te acepte la iglesia.}
{133}{}{¡Paz y amor! ¡El Fuego Santo!}
{134}{}{¿Tú también crees en algo?}
{135}{}{¿Y en qué crees TÚ?}
{136}{}{¡Alabado sea el Fuego Santo!}
{137}{}{¡Alabado sea Fénix! ¡Alabado sea Aaron!}
{138}{}{¡Te amo Aaron! ¡Alabado sea Aaron, el Señor de Fénix!}
{139}{}{Mi vida le pertenece a Aaron.}

#- sick or disabled
{150}{}{Llegué a la ciudad esperando a que me ayudaran, estoy enfermo.}
{151}{}{Mi enfermedad no tiene cura, pero los monjes prometieron ayudarme.}
{152}{}{Dicen que los monjes tienen antiguos poderes curativos.}
{153}{}{Todos los días le rezo a Aaron para que mis heridas mejoren.}
{154}{}{Le di todos mis ahorros a la iglesia, pero sigo igual de enfermo.}
{155}{}{Los monjes me están curando con oraciones. ¡Me siento más fuerte! Ah... no era nada.}
{156}{}{Los monjes me dijeron que para limpiar mi alma, debo entregarle todo a la iglesia.}
{157}{}{Supongo que no soy más que un insecto, ¿no?}
{158}{}{Siempre le pido a los demás creyentes que me ayuden.}
{159}{}{Los Seguidores son los únicos que saben curar como lo hacían antes de la Gran Guerra.}

#- refugee
{170}{}{Llegué hasta aquí para que la iglesia me admitiera.}
{171}{}{Me contaron que la iglesia ayudaba a los refugiados, pero no es el caso.}
{172}{}{Nos escapamos de los saqueadores, pero la iglesia no nos ayuda.}
{173}{}{¿No se supone que los Seguidores deberían ayudarnos?}
{174}{}{Parece que los monjes comen muy bien. Quizás esconden algo.}
{175}{}{Sólo me siento a salvo cerca de la catedral.}
{176}{}{Los Seguidores son un grupo muy extraño.}
{177}{}{No hacen más que prometer el cielo en la tierra.}
{178}{}{Nos dicen que deberíamos tener miedo, pero no entiendo del qué.}
{179}{}{Predicar es muy fácil cuando tienes comida que regalar.}
