{100}{}{Ves a un pastor.} 
{101}{}{Ves a uno de los Seguidores del Fuego, está enfocado en dar la misa.} 
{102}{}{El pastor está demasiado concentrado en la misa como para verte.}

{110}{}{Esto es un desafío del Santo Átomo.} 
{111}{}{Estoy seguro de que el Fuego Santo volverá a nuestra Catedral.} 
{112}{}{No permitan que la oscuridad los distraiga de su fe. Para nosotros, no es un obstáculo.} 
{113}{}{Mírense, les asustan las sombras. ¡Y se hacen llamar creyentes!}

#Prayer (see "Canticle to Leibowitz" by W. Miller, page 22)
{120}{}{¡Hermanos y hermanas! Empecemos con nuestra oración.}
{121}{}{Alabemos al Fuego Santo, porque ha purificado el mundo para devolverle su forma original.}
{122}{}{A spiritu fornicationis, Domine, libera nos.}
{123}{}{De los rayos y la tempestad, Fuego Santo, líbranos.}
{124}{}{Del azote del terremoto, Fuego Santo, líbranos.}
{125}{}{Del epicentro y el hipocentro, Fuego Santo, líbranos.}
{126}{}{De la peste, el hambre y la guerra, Fuego Santo, líbranos.}
{127}{}{De la tierra asolada, Fuego Santo, líbranos.}
{128}{}{De la lluvia de cobalto, Fuego Santo, líbranos.}
{129}{}{De la lluvia de estroncio, Fuego Santo, líbranos.}
{130}{}{De la caída del cesio, Fuego Santo, líbranos.}
{131}{}{De la maldición de la Radiactividad, Fuego Santo, líbranos.}
{132}{}{De procrear monstruos, Fuego Santo, líbranos.}
{133}{}{De la maldición de los deformes, Fuego Santo, líbranos.}
{134}{}{A morte perpetua, Domine, libera nos.}
{135}{}{Peccatores, te rogamus, audi nos.}
{136}{}{Que nos otorgues tu clemencia, te imploramos, escúchanos.}
{137}{}{Que no impongas la penitencia, te rogamus, audi nos.}
