{100}{}{Ves a un mendigo.}
{101}{}{Ves a un habitante promedio de las calles.}
{102}{}{Te has convertido en testigo de un crimen.}
{103}{}{¿Por qué pierdo el tiempo? ¡Hay que ocuparse de los testigos!}

{110}{}{¿Soy un... asesino?}
{111}{}{¡No quería hacerlo!}
{112}{}{Ella me obligó.}
{113}{}{Si ella no me hubiera mostrado sus chapas...}
{114}{}{¿Por qué hice eso?}
{115}{}{Parece que la maté.}
{116}{}{¡Dios mío, acabo de matar a alguien!}
{117}{}{Ya no se puede hacer nada.}
{118}{}{No se lo dirás a nadie, ¿verdad?}
{119}{}{Parece que tendré que irme de la ciudad.}
