{100}{}{Ves a la mujer de Diego.}
{101}{}{Ves a una de las esposas de Don Diego.}

{110}{}{¿Qué te hace pensar que puedes entrar así sin más?}  
{111}{}{No tienes lugar aquí.}  
{112}{}{Si mi esposo se entera, será un problema para todos.}  
{113}{}{Será mejor que te vayas, ahora.}  
{114}{}{A Diego no le gustará que estés aquí.}  
{115}{}{Si tienes algo que tratar con Diego, ve a hablarlo con él.}  
  
{1110}{}{Ni siquiera pienses que te nos puedes unir.}  
{1111}{}{Cariño, ya no tenemos más espacio.}  
{1112}{}{¿Piensas en ser parte de la familia?}  
{1113}{}{Deberías irte mientras puedes.}  
{1114}{}{No necesitamos más competencia.}  
{1115}{}{Diego es nuestro, ni pienses que lo compartiremos contigo.}  
  
{120}{}{No sabemos qué hacer.}  
{121}{}{Diego nos mantenía a salvo.}  
{122}{}{Sin mi esposo, todo se desmorona.}  
{123}{}{Nadie ha conseguido tomar el control desde que Diego murió.}  
{124}{}{Ay, Diego... ¿quién te quitó de nuestro lado?}  

