{100}{}{Ves a un ciudadano de Fénix.}
{101}{}{Estás viendo a un habitante común de Fénix. Parece estar tenso, como si esperara a alguien.}
{102}{}{Muévete.}

{200}{}{¿A dónde vas, cultista? ¿Vas a salir corriendo de acá? Bien pensado, déjame ayudarte.}
{1200}{}{¿A dónde vas, cultista? ¿Vas a salir corriendo de acá? Bien pensado, déjame ayudarte.}
{201}{}{¿En serio? Eso es muy... amable de tu parte.}
{202}{}{Te equivocaste de persona.}
{203}{}{No, sabemos que eres uno de los Seguidores. ¿Y adivina qué? Estamos cansados de esa 'magia nuclear' que tienen ustedes. Piérdete, eres basura.}
{204}{}{¡No, no, ya no soy parte de ellos!}
{205}{}{¡Cállate! Después de que explotó la Catedral, la mitad de Fénix fue destruida. No vamos a parar hasta que cada cultista se haya ido, ¿me escuchas?}
{206}{}{Sí, ya entendí.}
{207}{}{Bien. Ahora piérdete. Si nos causas problemas, te colgaremos.}
{208}{}{Sí, claro...}
{209}{}{No, no entendí. Repítemelo, pendejo.}
{210}{}{No te lo voy a repetir, idiota...}
{211}{}{Oye, ¿qué haces? Para...}
{212}{}{Uno a la vez, chicos.}
{213}{}{Espera, estamos del mismo lado. Yo fui quien causó la explosión.}
{214}{}{¿Qué...? ¿Acaso me ves la cara de idiota? Eso es lo más estúpido que he escuchado.}
{215}{}{Es la verdad. Los cultistas fundaron a quienes se llevaron a mi familia. Esa explosión fue mi venganza.}
{216}{}{Ehh... Aunque sea verdad, eso no quita que hayas destruido a Fénix. ¿Crees que eso nos hará sentir mejor? Sal de aquí, si vuelves, no saldrás con vida. ¿Entendido?}
{217}{}{No hay problema. No volverás a verme.}
{218}{}{No me hables así, o terminarás muerto.}
{219}{}{Piensa lo que quieras.}
{220}{}{Parece que este pendejo sigue sin entendernos. Habrá que hacerlo por las malas...}
{1220}{}{Parece que esta pendeja sigue sin entendernos. Habrá que hacerlo por las malas..}
{221}{}{Oye, no te pongas así...}
{222}{}{Ese fue tu último error.}
{223}{}{¿Me estás amenazando? Los que hacen eso terminan muertos, y rápido.}

{230}{}{Oye, tú, ¿por qué tienes la piel quemada?}
{231}{}{¿Eh? ¿A ti que te importa?}
{232}{}{¿Quién te hizo esto? Se dice que debajo de la Catedral experimentaban para crear soldados de élite. Tú estuviste ahí.}
{233}{}{No es lo que piensas. Soy víctima de la radiación, buscaba una cura dentro de la Catedral.}
{1233}{}{No es lo que piensas. Soy víctima de la radiación, buscaba una cura dentro de la Catedral.}
{234}{}{Hm... Estamos buscando a los supervivientes del culto para sacarlos de aquí. No te metas en nuestro camino.}
{235}{}{Claro, no quiero problemas.}
{236}{}{Puaj... (Te mira de pies a cabeza con obvio repudio) Puedes irte.}
{237}{}{...}
{238}{}{Debo resaltar mucho, ¿no? ¿Qué problema tienen con los Seguidores del Fuego?}
{239}{}{Queremos erradicar a todos los cultistas. Ahora que explotó la Catedral, no los queremos aquí. A ti tampoco.}
{240}{}{¿Por qué tanta hostilidad? Los Seguidores enseñaban la tolerancia y el amor, ¿no?}
{241}{}{Eso era lo que decían, pero estaban construyendo una bomba nuclear en su sótano secreto. No se puede confiar en gente así... De todas formas, nadie te quiere acá. Sal de nuestra ciudad, asqueroso mutante.}
{242}{}{Es mejor que no me ponga a discutir. Adiós, chicos.}
{243}{}{Asqueroso mutante... ¿Sabes? Te arrancaré los ojos de las cuencas y me comeré tu cerebro.}
{244}{}{Chicos, es mejor que matemos a este fenómeno, le haremos un favor al mundo...}
{245}{}{Oye, no deberíamos pelear...}
{246}{}{Es tu funeral...}
{247}{}{Eso es justo lo que pasó, soy una víctima, no soy uno de ellos.}
{248}{}{No te creo. No dejen que escape, chicos...}
{1248}{}{No te creo. No dejen que escape, chicos...}
{249}{}{En la cara no, por favor...}
{250}{}{Quizás digas la verdad... Puedes irte, pero si nos enteramos de que eres un cultista, terminarás igual que ellos, en la hoguera.}

{260}{}{Alto ahí, no quiero pelear contigo, pero te lo advierto. Sabemos que eras parte de los Seguidores, ya no los queremos en nuestra ciudad. Vete y no vuelvas nunca. Si lo haces, no importa qué arma o armadura tengas, no sobrevivirás.}
{261}{}{Lo entiendo, no regresaré a esta ciudad. Adiós.}
{262}{}{No me iré a ningún lado. ¿Por qué no me muestras lo que puedes hacer?}
{263}{}{(se miran entre sí, con nervios) No queremos problemas. Eh... todavía. Pero si es, em... necesario, te haremos desaparecer mañana.}
{264}{}{Demasiado tarde, idiota. Lo quieras o no, pelearemos ahora.}
{265}{}{Me estás confundiendo con alguien más.}
{266}{}{¿En serio? No lo creo, sal de nuestra ciudad. No queremos pelear, pero si es, eh, necesario, lo haremos.}
{267}{}{¿No quieres pelear? Que pena, yo sí.}
{268}{}{Bueno, me lo pensaré. Adiós.}
