{100}{}{¡Ves un fantasma!}
{101}{}{Ves... el alma de un hombre que ardió en el fuego nuclear.}

{102}{}{¿Qué demonios es esto?}
{103}{}{Eso no fue real, ¿Verdad?}
{104}{}{Estoy enloqueciendo... ¿Cierto?}
{105}{}{¡Hay almas por todas partes!}

{110}{}{¡Mira lo que haz hecho!}
{111}{}{¡Esto es culpa tuya!}
{112}{}{¿Por qué nos hiciste esto?}
{113}{}{¿Por qué nos mataste?}
{114}{}{Te atormentaremos por el resto de tu vida.}
{115}{}{¡Asesino!}

{1110}{}{¡Mira lo que haz hecho!}
{1111}{}{¡Esto es culpa tuya!}
{1112}{}{¿Por qué nos hiciste esto?}
{1113}{}{¿Por qué nos asesinaste?}
{1114}{}{Te atormentaremos por el resto de tu vida}
{1115}{}{¡Asesina!}
