{100}{}{Ves a un transeúnte.}
{101}{}{Ves a un asaltante.}
{102}{}{Ves a un transeúnte de ropa sospechosa, intenta no llamar la atención.}
{103}{}{Ves a un asaltante callejero. Mantén la distancia.}
{104}{}{¿Me estás siguiendo?}
{105}{}{El asaltante salió corriendo como un cobarde.}

# Dialogue
{200}{}{(Mientras caminas por la calle, te percatas de que te siguen. Un joven de atuendo ordinario te ha estado siguiendo un tiempo. Cuando te metes en un callejón oscuro, corre hacia ti y desenfunda lo que parece ser una pistola.)}
{201}{}{[Más]}
{202}{}{¡Alto! Suelta las chapas o te disparo.}
{203}{}{Oye, cálmate...}
{204}{}{¡Las chapas! ¡Dámelas! ¡Voy a disparar, lo juro! (Su rostro está tapado con una bufanda, pero puedes ver la desesperación en sus ojos)}
{205}{}{¡Las chapas! ¡Dámelas ahora!}
{206}{}{Quítamelas, perra.}
{207}{}{¿Qué...? Tengo un arma, está cargada. ¿Me escuchas? No me hagas hacer esto.}
{208}{}{Entonces te obligaré. ¡Defiéndete!}

{210}{}{Toma 30 chapas, no me dispares.}
{211}{}{Dámelas... (Toma las chapas y da una vuelta) Ahora lárgate, si te das la vuelta, te mato.}
{212}{}{Lo que tú digas...}
{213}{}{[Atácalo]}
{214}{}{Sólo tengo una chapa. Llévatela.}
{215}{}{Tengo dos chapas, no tengo más, lo juro.}
{216}{}{Llévate mis tres chapas, es todo lo que tengo.}
{217}{}{Carajo... Vete, si te das la vuelta, estás muerto.}
{218}{}{¡No me dispares! Llévate todas mis chapas.}

{220}{}{No tengo chapas, te lo juro.}
{221}{}{No me hagas enojar, perra asquerosa. ¡DAME LAS CHAPAS!}
{222}{}{De verdad, no tengo nada. Revisa mis bolsillos si quieres.}
{223}{}{Puta madre... (Mira a su alrededor, nervioso) Sólo... sólo sal corriendo y no mires atrás.}
{224}{}{¡Aléjate o te disparo!}
{225}{}{Oye, tranquilo.}
{226}{}{Entonces dispárame, cobarde.}
{227}{}{Me estás agotando la paciencia, idiota.}

{230}{}{Escúchame, ¿eres hombre o mujer?}
{231}{}{¿Pero qué...? ¡No me hagas enojar o TE MATO!}
{232}{}{Lo digo en serio, por esa bufanda que llevas no puedo saberlo.}
{233}{}{Si abres la boca de nuevo, estás muerto. ¡SACA LAS MALDITAS CHAPAS!}
{234}{}{Eh, quizás podamos hablarlo.}
{235}{}{Apunta a la cabeza. Es tu única oportunidad.}
{236}{}{¿Pero quién mierda...? (El ladrón empieza a ponerse nervioso y mira a su alrededor con nervios) No... no te des la vuelta, o te disparo. ¡Lo digo en serio, te mataré!}
{237}{}{Claro, lo que tú digas...}
{238}{}{¡Entonces dispárame, maldito cobarde!}
{239}{}{Estás cometiendo un error, pequeñín. ¿Sabes quién soy yo? Derroté a Mario, el invicto.}
{240}{}{No puede ser... No quiero matarte. Está bien, vete, y no mires atrás. ¿Me escuchas?}
{241}{}{Claro, tú eres el jefe.}
{242}{}{No tan rápido, me vas a pagar el pato...}
{243}{}{¿Cómo te atreves a molestar a un monje? ¡La Llama Nuclear te consumirá como castigo, maldito gusano!}
{244}{}{Eres patético. A los forajidos nos gusta colgar a gente como tú y ver como se desangran.}
{245}{}{Sólo te dejaré claro que estás asaltando a un ranger, no te saldrás con la tuya.}
{246}{}{El que va a morir eres tú, no yo.}
