{100}{}{Ves a George Crook.}
{101}{}{Ves a un viejo amigo - es George Crook, ya regresó de San Brahmán. Se ve feliz, y muy borracho.}
{102}{}{¿Y cómo saliste de esa, compadre? ¡Bar-r-dak!}
{103}{}{Demonios...}

{200}{}{Agh, déjame en paz. Me duele la cabeza.}
{201}{}{Déjame dormir un poquito más, la cama está suave...}
{202}{}{Luego de todas esas botellas de tequila, tengo que dormir...}
{203}{}{Tengo que descansar...}
{204}{}{*Hic*}
{205}{}{Tráeme agua... o a lo mejor un revólver.}
{206}{}{Necesito una siesta, nada más.}
{207}{}{Cinco minutitos más y voy...}
{208}{}{}
{209}{}{}

{210}{}{¡Eres tú! Acómpañame, quédate un rato, toma algo para beber.}
{211}{}{¿Recuerdas cómo le ganamos a los salvajes? ¡Fue asombroso!}
{212}{}{¿Y qué hay de cuando le dimos su merecido a su jefe? Eso fue genial.}
{213}{}{Y ahora todos esos indios nos tienen miedo, a ti y a mí.}
{214}{}{¿Aaron te recompensó bien, verdad?}
{215}{}{¿Qué tal si bebes conmigo y dejamos un desastre aquí dentro?}
{216}{}{Oigan, ¿me pueden traer a la chica esa que está cantando?}
{217}{}{Siento que voy a mear agua hirviendo...}
{218}{}{Cuídate la espalda, amigo...}
{219}{}{¿¡Quién quiere pelear!?}

{1210}{}{¡Eres tú! Acómpañame, quédate un rato, toma algo para beber.}
{1211}{}{¿Recuerdas cómo le ganamos a los salvajes? ¡Fue asombroso!}
{1212}{}{¿Y qué hay de cuando le dimos su merecido a su jefe? Eso fue genial.}
{1213}{}{Y ahora todos esos indios nos tienen miedo, a ti y a mí.}
{1214}{}{¿Aaron te recompensó bien, verdad?}
{1215}{}{¿Qué tal si bebes conmigo y dejamos un desastre aquí dentro?}
{1216}{}{Oigan, ¿me pueden traer a la chica esa que está cantando?}
{1217}{}{Siento que voy a mear agua hirviendo...}
{1218}{}{Cuídate la espalda, amiga...}
{1219}{}{¿¡Quién quiere pelear!?}
