{100}{}{Ves a uno de los hombres de Diego.}
{101}{}{Ves a Miguel.}
{102}{}{Estás viendo a un hombre encantador con un bigote. Se te hace extrañamente familiar.}
{103}{}{Estás viendo a tu tío Miguel, quien escapó de la Villa.}

{110}{}{Alto ahí, ¿quién eres?}
{111}{}{¿Quién eres?}
{112}{}{¿Quién te dejó entrar?}
{113}{}{¿Qué estás haciendo aquí?}
{114}{}{Da un paso más y llamaré a los guardias.}
{115}{}{No me digas que te escondes de los guardias.}
{116}{}{Se me hace que te conozco...}
{117}{}{¿Nos conocemos?}
{118}{}{Oye, ¿nos conocemos de algún lado?}
{119}{}{}

{120}{}{Estoy ocupado con, em, una investigación importante. Sí, eso.}
{121}{}{Me estoy dedicando a la ciencia, niño.}
{122}{}{¿Qué sabes tú acerca de los aceleradores de plasma? Sí, eso pensaba...}
{123}{}{Has algo útil y tráeme un vaso de tequila.}
{124}{}{Si me molestas, te voy a tirar a la calle.}
{125}{}{He estado llevando a cabo muchas investigaciones. No lo entenderías.}
{126}{}{¡Hoy me iré de peda! ¡Sí!}
{127}{}{}
{128}{}{}
{129}{}{}

#First meeting
{200}{}{Oye, ¿quién te dejó pasar? Esta es un área restringida... ¿¡}
{201}{}{!? ¡No manches!, eres }
{202}{}{, pero...}
{203}{}{Tío Miguel, ¿eres tú? ¡Hace tanto que no nos vemos!}
{204}{}{¡Ay, has crecido tanto! No te había reconocido. Todavía tienes los rasgos de tu viejo... Pero, ¡qué sorpresa! ¿Qué te trae por aquí?}
{1204}{}{¡Ay, has crecido tanto! No te había reconocido. Todavía tienes los rasgos de tu madre... Pero, ¡qué sorpresa! ¿Qué te trae por aquí?}
{205}{}{Estoy buscando a mi padre, es una larga historia. La versión corta es que unos esclavistas lo raptaron a él y a los demás aldeanos.}
{206}{}{¿¡Cómo!? Que malas noticias. Pero, la neta, no sé nada al respecto... De todas formas, es una buena idea que te vayas de la ciudad mientras puedas.}
{207}{}{Pero, acabamos de reencontrarnos... ¿Por qué...? Tío, ¡tuve que recorrer el yermo durante semanas para llegar hasta acá!}
{1207}{}{Pero, acabamos de reencontrarnos... ¿Por qué...? Tío, ¡tuve que recorrer el yermo durante semanas para llegar hasta acá!}
{208}{}{¿Tienes la menor idea de qué está pasando a tu alrededor, chamaco? Esto no es la Villa - Fénix tiene sus propias reglas. No quiero que te metas en problemas. Si mi patrón se entera de esto, será malo, para los dos.}
{209}{}{Tu jefe no se va a enterar de nada... Don Diego está muerto. Tuvo un 'accidente'.}
{210}{}{¿Fue culpa tuya? ¡Pendejo! Yo dependía de Diego para sobrevivir acá. ¿Qué voy a hacer ahora?}
{1210}{}{¿Fue culpa tuya? ¡Pendeja! Yo dependía de Diego para sobrevivir acá. ¿Qué voy a hacer ahora?}
{211}{}{Me parece que te tenía comiendo de su mano...}
{212}{}{No deberías haber venido aquí, ahora todo pende de un hilo. Es cierto que Diego era un criminal, pero él fue quien levantó a esta ciudad del suelo. ¿Y ahora qué? Lo más seguro es que los Seguidores del Fuego se apoderen del casino. ¿Siquiera entiendes lo que eso significa? Puedo ver en tus ojos que no, no lo sabes.}
{213}{}{Eso no importa. ¿Me ayudarás a encontrarlo? A tu hermano, a mi padre, lo que sea.}
{214}{}{Mira, me siento cómodo aquí y no quiero problemas. Hace años que no veo ni hablo con tu viejo. Busca ayuda en otro lado, quizás con los Seguidores del Fuego, ellos contratan a mercenarios de toda Arizona para llevar sus misiones a cabo.}
{215}{}{Bueno. Adiós, 'Tío' Miguel.}
{216}{}{No te preocupes de eso, ya hice todo lo que tenía que hacer aquí - ya mero me voy de Fénix.}
{217}{}{¿Eso piensas? Me da que para la Villa, los problemas apenas están empezando. Todo este asunto de los esclavistas no desaparecerá así sin más. Me pregunto cómo la Villa va a lidiar con eso...}
{218}{}{Nos las vamos a arreglar. Adiós, Tío.}
{219}{}{No te preocupes de eso, estoy en buenos términos con Don Diego.}
{220}{}{¿En serio? Tu padre es mucho menos astuto que tú. Él no quería saber nada acerca de las oportunidades que el mundo le presentaba a la Villa. Y aquí estás, ganándote el favor de una de las personas más importantes de Fénix. Me impresionas.}
{221}{}{Entonces, ¿me ayudarás a encontrar a mi padre?}
{222}{}{Debo seguir con mi búsqueda. Adiós, Tío Miguel.}
{223}{}{¿Acaso eres el esclavo de Don Diego? O sea, ¿es tu dueño, o algo así?}
{224}{}{¿Su esclavo? No... No, nada de ese estilo. Pero él podría esclavizar a cualquiera, si le da la gana. Es una persona muy importante, prácticamente es el dueño de la zona.}
{225}{}{Entonces me das la razón. Quizás me pueda ayudar a encontrar a mi padre.?}
{226}{}{Te está yendo bien. Es hora de que regrese a la Villa; ya hice todo lo que vine a hacer aquí.}

{230}{}{Oye, ¿quién te dejó pasar? Esto es un área restringida... ¿¡}
{1230}{}{Oye, ¿quién te dejó pasar? Esto es un área restringida... ¿¡}
{231}{}{!? No lo puedo creer, ¡mi sobrino favorito! Estoy feliz de verte, después de todo lo ocurrido.}
{1231}{}{!? No lo puedo creer, ¡mi sobrino favorito! Estoy feliz de verte, después de todo lo ocurrido.}
{232}{}{Hace mucho que no nos vemos, Tío Miguel.}
{233}{}{Y como has crecido. Me acuerdo que apenas estabas a la altura de la mesa. Desde ese entonces, todo ha cambiado, y mucho.}
{234}{}{Claro que sí. Te traigo noticias, acerca de la Villa, de mi padre, de unos saqueadores.}
{235}{}{Espera, para serte honesto, ya sabía sobre ti y de tu misión. Cuando llegaste a Fénix, la verdad quería encontrarte y ayudarte. Pero lo dudé. Sentía que ya había superado a la Villa y ahora me arrepiento de haber sido tan descuidado.}
{236}{}{La verdad es que la Villa ha cambiado mucho.}
{237}{}{¡Y necesitaba ese cambio! He oído sobre cómo salvaste a la Villa aunque todo estuviera en contra tuya, ¡y me sorprende! La neta, pensaba que esos ancianos llevarían a la Villa al fracaso. Y casi lo hicieron, pero tú los detuviste.}
{238}{}{¡Y necesitaba ese cambio! ...Pero me parece que no pudiste convencer a esos ancianos de lo necesario que era cambiar, ¿no? Puedo verlo en tus ojos, la Villa necesita más gente como tú y yo.}
{239}{}{Lo dices como si jamás hubieras tenido mucha esperanza para la Villa.}
{240}{}{Es por eso que me fui. Me volví un vagabundo y corté todos mis lazos con el pasado. Cuando vives acá, en el mundo real, sólo piensas en el presente. Para entender eso, tienes que salir de tu jaula y verlo todo. Y eso mismo hiciste. Bien hecho.}
{241}{}{Gracias, Tío Miguel.}
{242}{}{No hay de qué. Pero, ya es hora de que vayas a salvar al mundo. Yo agradecería que no le cuentes de mi pasado a los demás acá en el casino.}
{243}{}{Ya veo. Adiós, Tío Miguel.}
{244}{}{Puede que hayas visto el mundo 'real'. Pero te olvidaste de lo más importante, tu familia, y lo dejaste a valerse por sí mismos cuando pudiste haber ayudado.}
{245}{}{Buen punto. No te llevaré la contraria. Pero, ya es hora de que vayas a salvar al mundo. Yo agradecería que no le cuentes de mi pasado a los demás acá en el casino.}
{246}{}{Ya veo. Adiós, Miguel.}

#Re-dialogue
{300}{}{Mientras estés en el casino, has como que no me conoces.}
{301}{}{Adiós.}

{310}{}{¿Sabes lo que ocurrió en la Villa?}
{311}{}{Me enteré de algunas noticias.}
{312}{}{¿Se te ocurre en dónde podrían tener retenida a nuestra gente?}
{313}{}{No sé en dónde, exactamente. Puede que los Seguidores del Fuego tengan esa información, están en la Catedral.}
{314}{}{¿Qué tienen que ver los Seguidores?}
{315}{}{Los mercenarios usan esclavos como mano de obra y esencialmente trabajan para los Seguidores, quienes son los que realmente respaldan toda la trata de esclavos, la mayoría de personas no se da cuenta de eso. Pero sólo mira la colonia de Flagstaff, fue fundada por la catedral, o los Hojalateros que tienen un contrato y trabajan con los Seguidores. Hoy en día, se necesitan esclavos por todos lados.}
{316}{}{Esclavizaron a tu familia y los obligan a trabajar. ¿Por qué te lo tomas con tanta calma?}
{317}{}{Todo esto es culpa de mi hermano. Si me hubiera escuchado desde un principio, esta tragedia jamás habría pasado.}
{318}{}{Ya veo. Cambiemos de tema.}

{320}{}{Cuéntame acerca de tu escape de la Villa.}
{321}{}{¿ESCAPE? ¿Así es como te lo contó mi hermano? Sabía que iba a cambiar las cosas para que yo pareciera el malo de la historia... Escúchame, querido sobrino, yo no quería irme, a mí me EXPULSARON. Y la verdad, qué bueno.}
{1321}{}{¿ESCAPE? ¿Así es como te lo contó mi hermano? Sabía que iba a cambiar las cosas para que yo pareciera el malo de la historia... Escúchame, querida sobrina, yo no quería irme, a mí me EXPULSARON. Y la verdad, qué bueno.}
{322}{}{¿Por qué te echaron?}
{323}{}{Después de que murió nuestro viejo, tu papá, el querido Andrés, pasó a ser el jefe de la Villa al ser el hermano mayor. Se mantuvo firme a las tradiciones, pero yo tenía ideas nuevas. Incluso en ese entonces yo sabía que la Villa tenía que cambiar.}
{324}{}{¿Por qué?}
{325}{}{Hasta en ese entonces, nos habíamos cruzado con saqueadores del yermo, los rangers y caravanas de ciudades vecinas. Sabíamos que había vida afuera de nuestro valle. Pero Andrés le escondió eso al resto de los aldeanos, igual que los ancianos que estuvieron al mando antes de él.}
{326}{}{¿Y discutieron sobre esto?}
{327}{}{Estábamos en desacuerdo acerca del futuro de la Villa. Yo quería hacer conexiones con los pueblos de los alrededores, comerciar, usar la tecnología de la preguerra para cultivar, pero él ni siquiera quiso considerarlo. Según él, no era el momento, que se me había metido el demonio... Al final, le dijé que le diría la verdad a todos y me echó de la Villa.}
{328}{}{¿Qué pasó después?}
{329}{}{Me fui, llegué a la ciudad de al lado... Ciudad Garaje. Había un gremio de chatarreros, extraían chatarra de la 'mina', y me gané una buena cantidad de chapas. También aprendí acerca de la tecnología antigua. Las ruinas de Ciudad Garaje empezaron a tener menos chatarra y me fui directo a Fénix.}
{330}{}{Sigue.}
{331}{}{¡Y aquí fue en donde vi toda la grandeza de la civilización? Pero incluso acá, la gente no aprecia las cosas viejas. Tuve suerte de que Don Diego me contratara. Necesitaba a alguien que tuviera conocimiento de la tecnología antigua para poner el casino en marcha, y he estado acá desde ese entonces.}
{332}{}{Y ahora lo único que haces es beber y sumergirte en el placer, ¿no?}
{333}{}{Un momento, sobrino. Me he esforzado mucho para vivir cómodamente y mi máquina siempre está lista para funcionar.}
{1333}{}{Un momento, sobrina. Me he esforzado mucho para vivir cómodamente y mi máquina siempre está lista para funcionar.}
{334}{}{¿Máquina? ¿Qué clase de máquina?}
{335}{}{¿Te refieres a esa 'máquina' en tus pantalones?}
{336}{}{Eh... Cómo te lo digo... Don Diego me encarga chambas más técnicas.}
{337}{}{¿Cómo qué?}
{338}{}{Perdona, pero al jefe no le gusta que hable acerca de esto.}
{339}{}{Ya veo. Entonces cambiemos de tema.}
{340}{}{Eh, ¿esta historia va a acabar en algún punto?}
{341}{}{"Tecnología antigua"... te refieres a las máquinas tragaperras, ¿cierto?}
{342}{}{Jeje, eres listo, sobrino. Digamos que a Diego le gusta saber de cualquier cosa que pueda ganarle chapas, poder e influencia. Tuvo muchísima suerte al encontrarme, para él, soy invaluable.}
{1342}{}{Jeje, eres listo, sobrino. Digamos que a Diego le gusta saber de cualquier cosa que pueda ganarle chapas, poder e influencia. Tuvo muchísima suerte al encontrarme, para él, soy invaluable.}
{343}{}{¿Y qué clase de trabajo haces para él?}
