{100}{}{Ves a un rebelde.}
{101}{}{Ves a un hombre con un pasamontañas. Parece esconderse de alguien.}
{102}{}{No hay moros en la costa. Puedo regresar sólo, nos vemos en la base.}
{103}{}{Gracias por ayudarme. Podremos liberar a Fénix, juntos.}
{104}{}{Tienes las ruinas de una gran ciudad en frente tuyo. Los niveles de radiación deben ser altos.}

#First dialogue
{200}{}{¿Quién...? ¿Quién eres?}
{201}{}{Me envían Elisa y Marcos, perdieron el contacto contigo.}
{202}{}{Por fin, ¡pero mantén el silencio! Podrían escucharnos, no sé cómo me descubrieron los monjes, son más inteligentes de lo que parecen. ¿Me ayudarás a regresar a la base?}
{203}{}{¿Qué hay de tu misión?}
{204}{}{Olvídalo, tenemos que esquivar a los cultistas. El amplificador está en el edificio cruzando la calle, pero ir hacia allá es demasiado peligroso.}
{205}{}{Entonces, tenemos que irnos.}
{206}{}{Pero es imposible esquivarlos sin ser visto... Hmm, ¿cómo lo hiciste?}
{207}{}{Tendremos que pelear. ¿Estás listo? Vámonos.}
{208}{}{Hay que acabar con tu misión primero. Espérame aquí.}

#Re-dialogue
{210}{}{Tenemos que volver a la base, y estar seguros de que nadie nos siga.}
{211}{}{Entendido, vámonos.}
{212}{}{Espérame aquí, iré a echar un vistazo más adelante.}
{213}{}{Vamos, nos están esperando en la base.}
{214}{}{Quédate aquí mientras registro el área.}
{215}{}{¿Me podrías decir cuál era tu misión?}
{216}{}{Tenía que colocar un amplificador de señal en ese edificio de allá. Sigue ahí, pero tuve que dejar mis cosas para que no me atraparan. No puedo volver, es demasiado arriesgado. Puede que hayan tendido una emboscada.}
{217}{}{No hay moros en la costa, puedo volver sólo. Nos vemos en la base.}
{218}{}{Nos vemos.}
{219}{}{Gracias, puedo volver sólo. Me salvaste el pellejo.}

