{100}{}{Ves a un rebelde.}
{101}{}{Ves a una persona con pasamontañas, está ocupado revisando su equipamiento.}
{102}{}{Ves a una persona con pasamontañas, claramente está listo para luchar por sus ideales.}
{103}{}{Ves a una persona con pasamontañas, parece listo para luchar.}
{104}{}{Ves a una persona con pasamontañas, comienza a flexionar sus nudillos al verte.}

{110}{}{Hmm...}
{111}{}{Ni siquiera nuestro cuartel general es seguro.}
{112}{}{Ganaremos.}
{113}{}{Malditos fanáticos.}
{114}{}{Esos fanáticos van a recibir su merecido.}
{115}{}{No me gusta lo que están haciendo.}
{116}{}{Cuando lleguemos al poder, Fénix será diferente.}
{117}{}{Es hora de que salgamos de las sombras.}
{118}{}{Me da que se me metió un hongo en los pulmones por vivir aquí abajo.}
{119}{}{Este es el mejor lugar para nuestra sede, por ahora.}

