{100}{}{Ves a uno de los Cardenales Rojos.}
{101}{}{Ves a un bandido con un elegante corte de pelo y el emblema de una pandilla en la espalda.}
{102}{}{Ojalá tuviera una armadura como la tuya, toda la ciudad se inclinaría ante mí.}

{110}{}{¿Buscas problemas?}
{111}{}{¿Quién eres, de todos modos?}
{112}{}{Nuestro territorio - nuestras reglas.}
{113}{}{Todos se inclinan ante nosotros por aquí.}
{114}{}{Cuidado con lo que dices.}
{115}{}{Cállate si no quieres un puño en tu cara.}
{116}{}{¿Sabes siquiera quiénes somos?}
{117}{}{¿Tienes una opinión? Métetela por el culo.}
{118}{}{¿Qué estás haciendo aquí?}
{119}{}{¿Buscas algo en nuestro territorio?}

{120}{}{Maldita sea, no deberíamos haber dudado de ti.}
{121}{}{Eres más duro de lo que pareces.}
{122}{}{Oye, ¿cómo te trata la vida?}
{123}{}{¿Te invito una cerveza?}
{124}{}{Si necesitas a alguien para un "trabajito", cuenta conmigo.}
{125}{}{Si todo se va a la mierda, cuenta conmigo.}
{126}{}{Aquí somos todos parte de la pandilla. Siéntete como en casa.}
{127}{}{}
{128}{}{}
{129}{}{}
