{100}{}{Ves a Rico.}
{101}{}{Ves a un hombre corpulento de rostro apagado, pero su presencia impone respeto.}

#Response
{110}{}{¿Qué te pasa?}
{111}{}{Conmigo no, háblale al enano.}
{112}{}{Angelo es el jefe.}
{113}{}{¿Qué quieres?}
{114}{}{Fallé, de nuevo.}
{115}{}{Tengo hambre.}
{116}{}{Manos en dónde pueda verlas.}
{117}{}{¿Estás en un aprieto, verdad?}
{118}{}{¡Sentado! Dije, ¡SENTADO!}
{119}{}{¡Muérdeme, vamos!}
{120}{}{*Gruñido*}
{121}{}{*Se da un estirón*}
{122}{}{Hueles a bebé.}
{123}{}{No me esperes.}
{124}{}{Cierra la boca.}
{125}{}{Es hora de la siesta.}
{126}{}{¿Necesitas un entrenador personal o algo así?}
{127}{}{Ajá.}
{128}{}{La salida está por allá.}
{129}{}{Atrás.}
{130}{}{*Te da una mirada vacía*}
{131}{}{¿Necesitas algo?}

#Random phrases
{150}{}{(Envidioso) Fue una pelea genial.}
{151}{}{Peleas como un perro rabioso.}
{152}{}{¿Quién te enseñó a pelear así?}
{153}{}{¡No me pegues!}
{154}{}{Eres un despiadado.}
{155}{}{No estoy a tu nivel.}
{156}{}{No pelearé contigo.}
{157}{}{No eres humano, sino una bestia.}
{158}{}{Necesito un entrenador.}
{159}{}{Mátame.}
{160}{}{*Gruñe*}
{161}{}{*Te da una sonrisita*}
{162}{}{*Asiente con la cabeza*}

#Emotional outbursts
{200}{}{*Llora como un bebé}
{201}{}{¡Ange-e-looo!}
{202}{}{¡Ange-elo! ¡Ange-elo!}
{203}{}{*Chilla*}
{204}{}{Oooohhh...}
{205}{}{*Se le caen las lágrimas*}
{206}{}{¡No me mires! ¡NO ME MIRES!}
{207}{}{¡Te mataré! ¡Los mataré a todos!}
{208}{}{¡Putas! ¡SON UNAS PUTAS!}
{209}{}{Angelo fue inteligente, yo fui un tonto.}
{210}{}{¿¡Quién lo hizo!?}
{211}{}{¡DIME QUIÉN LO HIZO!}
{212}{}{¿¡Quién mató a mi Angelo!?}
{213}{}{*Toma una profunda bocanada de aire*}
