{100}{}{Ves a tu oponente.}
{101}{}{Ves a Savage.}
{102}{}{Ves a Canelo.}
{103}{}{Ves a Big Mario.}
{104}{}{Ves a un Supermutante.}

{105}{}{Ves a tu oponente. Parece insinuar que apostó por ti.}
{106}{}{Ves a tu oponente. Parece estar insinuando que no eres rival para él.}
{107}{}{Ves a tu oponente. Sólo te ve como un rival.}
{108}{}{Ves a tu oponente. Y en sus ojos, una rabia indescriptible.}
{109}{}{Ves a tu oponente. Para tu desgracia.}

#Respuesta
{110}{}{¡MUERE!}
