{100}{}{Ves a un fanático.}
{101}{}{Ves a un hombre indiferente que espera a la siguiente pelea.}
{102}{}{Ves a un hombre de aspecto salvaje. Está gritando con todas sus fuerzas.}

#Response
{110}{}{Ojalá que la pelea empiece pronto.}
{111}{}{¿Qué te pareció la última pelea que hubo?}
{112}{}{Iron Mike dejó de entrenar luchadores.}
{113}{}{Desde que Iron Mike se fue, todas las peleas han sido aburridas.}
{114}{}{Me aburro... ¿para cuándo es la siguiente pelea?}
{115}{}{Apostaré por ese tipo de allá.}
{116}{}{¿Por quién vas a apostar?}
{117}{}{Sé que con esta pelea voy a ganar en grande.}
{118}{}{}
{119}{}{}

{150}{}{¡Hola, campeón!}
{151}{}{¿Cómo estás?}
{152}{}{¿Eres tú? ¿De verdad?}
{153}{}{¡Eres mi ídolo! ¡No puedo creer que estés hablando conmigo!}
{154}{}{¿Por qué dejaste de pelear?}
{155}{}{¡Golpéame! ¡Le presumiré a todos que lo hiciste!}
{156}{}{¿Me dejas tocar tus músculos?}
{157}{}{Gracias a ti, gané unas buenas chapas.}
{158}{}{}
{159}{}{}

{1150}{}{¡Hola, campeona!}
{1151}{}{¿Cómo estás?}
{1152}{}{¿Eres tú? ¿De verdad?}
{1153}{}{¡Eres mi ídolo! ¡No puedo creer que estés hablando conmigo!}
{1154}{}{¿Por qué dejaste de pelear?}
{1155}{}{¡Golpéame! ¡Le presumiré a todos que lo hiciste!}
{1156}{}{¿Me dejas tocar tus músculos?}
{1157}{}{Gracias a ti, gané unas buenas chapas.}
{1158}{}{}
{1159}{}{}

{160}{}{Hola.}
{161}{}{Te crees muy fuerte, ¿verdad?}
{162}{}{Oye, cálmate.}
{163}{}{Peleas bien, pero yo aposté por el otro tipo. Eran mis últimas chapas...}
{164}{}{¿Por qué dejaste tu carrera?}
{165}{}{Te reto a golpearme.}
{166}{}{Tus bíceps son demasiado grandes, ¿no?}
{167}{}{Me debes unas chapas, perdí un montón gracias a ti.}
{168}{}{}
{169}{}{}

#Random phrases outside of combat
{170}{}{¿Para cuándo es la pelea?}
{171}{}{Me aburro.}
{172}{}{Hacen falta luchadores.}
{173}{}{ }
{174}{}{ }
{175}{}{ }
{176}{}{ }
{177}{}{ }
{178}{}{ }
{179}{}{ }

#Random phrases during battle
{180}{}{¡Apuesto por el de allá!}
{181}{}{¡Dale en el riñón!}
{182}{}{¡Mátalo!}
{183}{}{¡Te amo!}
{184}{}{¡Pégale en el costado! ¡En el costado!}
{185}{}{¡Defiéndete!}
{186}{}{Qué pelea más aburrida.}
{187}{}{Esto es inolvidable.}
{188}{}{Me estoy muriendo de calor.}
{189}{}{*Silba*}
{190}{}{*Grita*}
{191}{}{¡Duérmelo de una vez!}
{192}{}{¡Así se hace!}
{193}{}{¡Dale en la cabeza!}

{194}{}{, ¡mátalo!}
{195}{}{Tú puedes, }
{196}{}{Nadie te supera, }
{197}{}{Acaba con él, }
{198}{}{Aposté por ti, }
{199}{}{Reviéntalo, }