{100}{}{Ves a un okupa.}
{101}{}{Ves a un hombre delgado que lleva puesta ropa sucia.}
{102}{}{*Nom nom*}
{103}{}{¡Fueron los Cardenales! ¡Ellos hicieron volar la planta eléctrica!}

#Diálogo
{200}{}{¡Dios mío, me asustaste! Jamás veo gente por aquí abajo.}
{201}{}{Lo siento, no quería asustarte. ¿Qué estás haciendo aquí?}
{1201}{}{Lo siento, no quería asustarte. ¿Qué estás haciendo aquí?}
{202}{}{¡Imbécil! ¡Casi me das un ataque! ¿Qué haces aquí, siquiera?}
{203}{}{Estoy atrapando a las ratas. Son rápidas, astutas y no suelen caer en mis trampas. A veces tengo que esperar horas para emboscar una.}
{204}{}{Te deseo suerte en esta ardua tarea. Adiós.}
{205}{}{Si has estado aquí parado, debes saber quién entró a la parte este del alcantarillado, ¿verdad?}
{206}{}{Sí, ¿pero qué me darás si te digo?}
{207}{}{Te daré algo de comer. Espera aquí, iré por algo...}
{208}{}{Ya te he dado comida suficiente. Ahora cuéntamelo.}
{209}{}{Aquí tienes diez chapas.}
{210}{}{Bien, muchas gracias.}
{211}{}{Cuéntame lo que sabes.}
{212}{}{Lo siento, no tengo dinero.}
{213}{}{Si me lo cuentas, te dejaré vivir, pedazo de mierda.}
{214}{}{¡Lárgate! ¡O te echaré a las ratas encima! ¡Vete! ¡Vete!}
{215}{}{Eso ya lo veremos. }
{216}{}{Parece que tendré que ensuciarme las manos. ¡Dime qué viste!}
{217}{}{Te perdonaré la vida, hijo de puta.}
{218}{}{¡Ten piedad! ¡Te lo contaré todo!}
{219}{}{Vamos, habla.}
{220}{}{Fueron los Cardenales. Estaban acompañados por un monje y un necrófago. Dijeron que querían explotar unas tuberías para engañar al jefe de la planta. Parece que tenían una relación complicada, pero no entendí nada.}
{221}{}{Muy bien, te dejaré vivir, por ahora.}
{222}{}{Gracias, amigo mío. Me has ayudado mucho.}

{250}{}{Hola. Últimamente veo a mucha gente pasarse por aquí.}
{251}{}{Gracias por darme de comer. ¿Me darías un segundo platillo?}
{252}{}{¿Qué haces aquí?}
{253}{}{Adiós.}
