{100}{}{Ves a Tripas.}
{101}{}{Ves a un hombre delgado con ropa sucia.}
{102}{}{*Nom nom* ¡Eso estaba delicioso! Ahora sí podemos hablar.}
{103}{}{Eh, ¿Cómo te las arreglaste para bajar esa cosa? Es jodidamente enorme.}

{110}{}{El okupa está demasiado hambriento como para hablarte.}
{111}{}{¿Tienes comida?}
{112}{}{¿Me compartirías algo de comida?}
{113}{}{Un almuerzo para un mendigo, por favor.}
{114}{}{El que está aquí, es uno de nosotros. Lo que quiere decir que todos comparten lo que tienen.}
{115}{}{Los nuevos deben compartir algo. Esa es la regla.}

#Dialogue
{200}{}{Gracias por darme de comer. Pocos turistas se pasan por aquí, y si alguien se aparece, no es nada bueno. ¿No nos vas a causar problemas, cierto?}
{201}{}{Depende, responde todas mis preguntas y estarás bien.}
{202}{}{No te preocupes, amigo mío.}

{210}{}{Entonces, ¿Qué te trae por aquí, piel limpia?}
{1210}{}{Entonces, ¿Qué te trae por aquí, piel limpia?}
{211}{}{Adiós.}
{212}{}{Creo que has tenido suficiente. Adiós.}
{213}{}{Qué interesante. ¿Podrías contarme otra cosa?}

{220}{}{¿Quién eres?}
{221}{}{Los de la superficie nos llaman okupas. No tenemos hogar, ni trabajo, ni amigos allá arriba. Vivimos aquí, en el subterráneo.}
{222}{}{¿Tienes algún líder?}
{223}{}{No, todos somos iguales por aquí.}
{224}{}{¿Quién eres?}
{225}{}{Mis amigos me llaman El Tripas. Pero puedes llamarme Señor Hidalgo. Jeje. Es un chiste, ¿Lo entiendes? ¿No? Mira... No, olvídalo.}
{226}{}{¿Cuánto tiempo llevas viviendo aquí abajo?}
{227}{}{¿Cuánto tiempo llevas viviendo aquí abajo, Tripas?}
{228}{}{He atrapado ratas aquí desde que era niño, y cuando habían problemas, mi familia se escondía aquí abajo. Ahora no quiero volver a subir.}

{230}{}{¿Por qué vives bajo tierra?}
{231}{}{Es agradable vivir aquí, una vez que te acostumbras. Allá arriba, la gente se mata a disparos, pero aquí abajo somos todos iguales. ¿Lo entiendes, no? Nos ayudamos y compartimos lo que tenemos. Nuestra vida es así.}
{232}{}{¿Cómo sobrevives aquí?}
{233}{}{Atrapamos ratas y recolectamos hongos. A veces vamos a la superficie y los intercambiamos por algo que necesitemos.}
{234}{}{Ah, así que de aquí saca las ratas el tipo del mercado...}
{235}{}{Somos los mejores en esto, nadie atrapa ratas como nosotros.}
{236}{}{Eso es sorprendente. Me gustaría saber más de ustedes.}
{237}{}{Vale, he escuchado suficiente.}

{240}{}{¿Has visto algo interesante aquí abajo?}
{241}{}{No realmente. Pero últimamente, se pasan muchos extraños por aquí, también empezamos a escuchar ruidos raros.}
{242}{}{¿Ruidos?}
{243}{}{Eso creo. Por lo general, aquí abajo es tranquilo, pero a veces hay un ruido, como muchas voces hablando por la tubería. Algunos piensan que es un fantasma, jeje. Pero no les creo.}
{244}{}{¿Un fantasma? Cuéntame más.}
{245}{}{Dicen que había un noble padre de familia que se escondió aquí abajo durante la Guerra. Pero el hambre quebró su espíritu, primero se comió a su esposa, y luego a su hijo. Cuando llegó su hora, su espíritu quedó vagando las alcantarillas en búsqueda de su familia perdida. (mira a su alrededor) ¿Lo oyes? A veces, creo que podría ser real.}
{246}{}{Es una historia triste. Tengo más preguntas que hacerte.}
{247}{}{No hay nada más estúpido que una historia de fantasmas. No quiero escucharte hablar más.}
{248}{}{¿Crees que los fantasmas existen? ¿En serio?}

{250}{}{¿Sabes cómo entrar en las profundidades del subterráneo?}
{251}{}{No se puede desde aquí, tendrás que volver a la superficie y encontrar otra entrada. Pero créeme, es mejor que no bajes sin alguien que te cubra la espalda.}
{252}{}{¿Qué hay ahí dentro?}
{253}{}{Monstruos, derrumbes, fosas tóxicas; lo que se te ocurra. Incluso nosotros no sabemos todos los secretos que encierran las profundidades. Pero, últimamente, hemos encontrado más y más cadáveres de los pieles limpias. No sé qué es lo que buscan.}
{254}{}{Vaya, conoces este lugar como la palma de tu mano. ¿Podrías contarme algo más?}
{255}{}{Eso es todo, me voy a la superficie. Ahora mismo.}
