{100}{}{Ves a un okupa.}
{101}{}{Ves a un okupa muy sucio con un hedor horrendo.}

# Diálogo flotante
{110}{}{¿Qué? ¿Qué pasó?}
{111}{}{¿Me estás escuchando?}
{112}{}{Huelo a alguien... Parece que tenemos invitados.}
{113}{}{Parece que hay un turista por aquí.}
{114}{}{No es temporada de ratas todavía.}
{115}{}{Tengo que ir a revisar las trampas para las ratas.}
{116}{}{Se me está cayendo la piel... Otra vez.}
{117}{}{Agh. Voy a vomitar...}
{118}{}{*se rasca la piel con pereza*}
{119}{}{*Cof cof cof*}

# Respuestas

# - El jugador tiene lentes de hojalatero
{130}{}{Buena elección. Estarás más atento con esas gafas.}
{131}{}{Ojalá tuviera gafas como esas, me quebré la pierna la semana pasada. Dos veces.}
{132}{}{Ven a vivir aquí abajo con nosotros, no te harán falta las gafas.}
{133}{}{Quédate aquí abajo un tiempo, y te acostumbrarás a la oscuridad como nosotros.}
{134}{}{¿Puedes ver a través de la ropa con esas gafas?}

# - Jugador furtivo
{135}{}{¿Por qué te escondes?}
{136}{}{¿Te escondes de alguien?}
{137}{}{Por mucho que finjas ser parte del muro, puedo verte.}
{138}{}{¿Siempre vas por la vida escondiéndote?}
{139}{}{Un turista borracho, otra vez.}

# - Respuestas generales
{150}{}{Hola.}
{151}{}{¿Qué estás buscando, guapo?}
{152}{}{¿Un tipo nuevo? No importa.}
{153}{}{¿Estás perdido? Esto no es la ciudad, eso está arriba.}
{154}{}{Es raro encontrarse turistas por aquí abajo.}

{155}{}{Es agradable estar aquí. En serio.}
{156}{}{Si nos llevamos bien, compartimos la comida.}
{157}{}{¡Shh! ¡Baja la voz!}
{158}{}{¿Lo escuchas? Es la ciudad, está respirando.}
{159}{}{Usualmente es tranquilo por aquí... hasta que llega alguien de arriba.}

{160}{}{Hola.}
{161}{}{¿Qué estás buscando, guapa?}
{162}{}{¿Una chica nueva? No importa.}
{163}{}{¿Estás perdida? Esto no es la ciudad, eso está arriba.}
{164}{}{Es raro encontrarse turistas aquí abajo.}

