{100}{}{Ves a un apostador.}
{101}{}{Ves a un cliente del casino. Parece que se quejará del servicio y del mundo entero.}
{102}{}{Déjame en paz. Quiero emborracharme y ver cómo la ciudad arde.}

{110}{}{¿Cómo se atreven a dejarme en la calle?}
{111}{}{¡Exijo una disculpa!}
{112}{}{Si no fuera por mí, toda la ciudad estaría en la basura.}
{113}{}{¿Siquiera saben quién soy?}
{114}{}{¿Crees que es chistoso? ¿Te estás riendo de mí?}

{200}{}{(le grita al casino) ¡Me van a oír! ¡Me van a oír, avaros de mierda!}
{201}{}{¿Qué está pasando?}
{202}{}{Otro más, genial. ¿Te quieres sacar la lotería allá dentro, verdad? Olvídalo. Son todos unos ladrones.}
{203}{}{¿Estás borracho o algo así?}
{204}{}{¿Borracho? Me tomé unas chelas, igual que la mitad de la ciudad. Incluyendo a las mujeres y niños.}
{205}{}{Ya veo.}
{206}{}{¿Seguro? Bah, olvídalo. Trabajaba para la caravana más importante, y ahora ni me dan descuentos en ésta pocilga. Son unos malagradecidos...}
{207}{}{¿Qué caravana era?}
{208}{}{La que llevaba el mineral a Two-Sun, y ahora los carros se están oxidando bajo el sol, y estoy sin trabajo. Gracias a algún imbécil.}
{209}{}{No creo que esa haya sido su intención.}
{210}{}{¡Chinga tu madre! (se va caminando)}
{1210}{}{¡Chinga tu madre, perra! (se va caminando)}
{211}{}{Hmph...}
{212}{}{Te lo mereces, si tratabas con ellos.}
{213}{}{¿Los Hojalateros? Sí, gracias a ellos hay tecnología en la ciudad... vaya bastardos. Bah, no lo entenderías. (se va caminando, mientras habla sólo)}
{214}{}{Lo que tú digas.}
