{102}{}{Acceso concedido.}
{103}{}{La única respuesta que recibes es el silencio.}
{104}{}{Presionas los botones, pero no ocurre nada. El intercomunicador parece estar descompuesto.}
{105}{}{Eso no será de ayuda.}
{106}{}{Nadie responde tus llamadas.}

{200}{}{Presionas los botones, pero no ocurre nada.}
{201}{}{¿Hola? ¿Hay alguien ahí?}
{202}{}{La única respuesta que recibes es el silencio.}
{203}{}{Salir.}
{204}{}{[TRAMPA: abrir]}
{205}{}{(Escuchas un clic, y la puerta se abre.)}
{206}{}{Parece que aquí viven unos mudos...}
{207}{}{Vengo de parte de los rangers.}
{208}{}{Matthias me envió para ayudar al Partido de la Liberación.}
