{100}{}{Ves un tablón de anuncios.}
{101}{}{Ves un tablón con varias notas y noticias.}
{102}{}{es un tablón de noticias. Vale la pena echarle un ojo.}

{200}{}{(Ves un tablón de anuncios lleno de notas)}
{201}{}{Irte.}
{202}{}{Ya veo.}
{203}{}{Regresar.}

{210}{}{Áreas peligrosas.}
{211}{}{(Examinas un mapa de Fénix, que marca las áreas más peligrosas. Las destacadas son: "Necrófagos en la central eléctrica", "Cardenales Rojos", "Ruinas Irradiadas")}

{220}{}{¡Cuidado con los forajidos!}
{221}{}{Cuidado con los saqueadores en las carreteras 10 y 17. Atacan a viajeros y caravanas sin piedad ni remordimiento. Ni siquiera intente negociar con ellos.}

{230}{}{Banda criminal 'Los Panchos'}
{231}{}{¡Cuidado! Se buscan a varios criminales peligrosos - los líderes de la banda Los Panchos. (Se incluyen retratos) Se pagarán 500 chapas por cada cabeza.}
{232}{}{Hernando Avilés.}
{233}{}{[Tachado] Hernando Avilés.}
{234}{}{Solía ser un guardia de seguridad. Mató a su patrón y a su familia entera durante un robo. Luego, viajó por el desierto y se unió a Los Panchos. Es calmado y de cabeza fría, gusta de hablar con sus víctimas antes de matarlas.}
{235}{}{Chucho Navarro.}
{236}{}{[Tachado] Chucho Navarro.}
{237}{}{Debido a sus deudas, fue capturado y esclavizado, luego consiguió escapar. Conocido por su afición a la tortura. Es inestable mentalmente.}
{238}{}{Eydie Gormé.}
{239}{}{[Tachado] Eydie Gormé.}
{240}{}{Era una cantante. Robó el casino en donde trabajaba, desapareció junto a sus cómplices en el desierto y se unió a Los Panchos. Ascendió al rango de jefa a través de crueldad, inestabilidad emocional y un gusto por el canibalismo.}

{250}{}{Se busca: Gil McCord.}
{251}{}{Se busca al viejo tirador, Gil McCord, por ataques contra miembros del gremio de mercenarios. Se ofrecen 750 chapas, vivo o muerto.}
{252}{}{[Tachado] Gil McCord.}

{260}{}{Se busca: }
{261}{}{ , de la Villa... ¿Qué?}
{262}{}{Se busca debido a sus numerosos crímenes contra el pueblo de Fénix. Cualquier contacto con esta persona podría costarte la vida.}
{263}{}{Se busca por sus numerosos crímenes contra la Iglesia del Fuego Santo. Cualquier contacto con este hereje puede costarle su reputación y bienestar.}
