{110}{}{Esta radio no funciona.}
{111}{}{Has deshabilitado el transmisor de la radio. Los Seguidores del Fuego ya no tendrán comunicaciones por radio.}

# Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{El transmisor de la radio no funciona.}
{204}{}{La estación de radio no funciona, pues la catedral se encuentra sin electricidad.}

{210}{}{Copia las frecuencias de radio y el código. Así podré escuchar las conversaciones de los Seguidores en la radio.}
{211}{}{Se han copiado las frecuencias de radio.}
{212}{}{Examinar el historial de transmisiones. Me pregunto si alguien sabrá algo de los ataques contra los monjes.}
{213}{}{Encontraste un rastro de una transmisión encriptada. El código de acceso de la terminal pertenecía a Matthias, el prior.}
{214}{}{Parece que no eres el santo que todos creen...}

{220}{}{Escucha las comunicaciones por radio sobre el agente en los Cardenales Rojos.}
{221}{}{"...Tengo información para Aaron, los Cardenales Rojos han empezado a moverse."}
{222}{}{[Más]}
{223}{}{"Se más específico, por favor. Cada detalle es importante para nosotros."}
{224}{}{[Más]}
{225}{}{"Orris envió a uno de sus hombres a negociar un contrato para que le suministren armas. Busca fortalecer su posición en los barrios bajos. Yo se los dije, pero no me escucharon."}
{226}{}{[Más]}
{227}{}{"¿Dónde tomará lugar la negociación?"}
{228}{}{[Más]}
{229}{}{"En la alcantarilla cerca de la entrada a la ciudad. Probablemente encontrarán a un mensajero falso, pero eso no importa. Tenemos que detener ese trato, cueste lo que cueste, porque causará una guerra civil en los barrios bajos."}
{230}{}{[Más]}
{231}{}{"Entendido, enviaremos un agente. Ten cuidado, Murphy, porque Orris no debe sospechar en lo más mínimo que eres trabajas para nosotros. Cambio y fuera."}
{232}{}{¿Qué? ¿Murphy es un agente de la Catedral? No me lo esperaba...}
{233}{}{¿Cómo? Primero Ralph, y ahora Murphy. Hay traidores por todos lados.}

{250}{}{Escucha las conversaciones de radio sobre el sabotaje a la central eléctrica.}
{251}{}{"Informa, ¿cuál es el estado de la operación?"}
{252}{}{[Más]}
{253}{}{"Gracias al Átomo, todo salió bien. Los Cardenales cumplieron con su parte del trato. Se introdujeron en el subterráneo de la central eléctrica y volaron por los aires el sistema de enfriamiento tal como les indicamos. No representa una amenaza para la ciudad."}
{254}{}{[Más]}
{255}{}{"Ahora todo depende de Ralph y tus diplómatas. No pierdas la oportunidad, porque parece que encontraron a alguien que reparará el sistema. Dudo que lo consiga, pero no hay razón por la que retrasarse."}
{256}{}{[Más]}
{257}{}{"Entendido. No dejes de informarnos, que el Fuego esté contigo."}
{258}{}{¿Cómo? ¿Ralph está tratando con la Catedral? Vaya, vaya...}
{259}{}{¿Qué? ¿Lo dices en serio? Primero Murphy, y ahora Ralph. Hay traidores por todos lados.}
