{100}{}{Ves a Louis.}
{101}{}{Ves a un habitante del Refugio 25.}
{102}{}{Como digas...}
{103}{}{¡Hazlo, te lo ruego!}
{104}{}{Si así lo desea, señor...}
{1104}{}{Si así lo desea, señora...}

{200}{}{(Ves a un hombre con una caja de herramientas. Al verte, retrocede y, mirándose a los pies, dice: "E-es un honor".)}
{201}{}{Un momento, ¿quién eres tú?}
{202}{}{M-mi nombre es Louis... si eso está bien.}
{203}{}{¿Qué haces aquí, Louis?}
{204}{}{E-estoy revisando las t-tuberías... si no le importa.}
{205}{}{Deberías dejar de balbucear.}
{206}{}{Pido disculpas, a-amo. Me iré de inmediato, señor.}
{1206}{}{Pido disculpas, señora. Me iré de inmediato, señora.}
{207}{}{Tómate tu tiempo. Quiero preguntarte algo.}
{208}{}{Eh, está bien.}
{209}{}{Te pregunto quién eres, no cómo te llamas.}

{210}{}{¿En qué puedo ayudarte?}
{211}{}{No puedes, por el momento.}
{212}{}{Basta de eso.}

{220}{}{Háblame de ti.}
{221}{}{(desconcertado) Soy Louis... Nací aquí... Y crecí aquí.}
{222}{}{¿Eso es todo?}
{223}{}{Le pido disculpas, amo. He pasado mi vida entera haciéndole mantenimiento a este refugio. No tengo nada más que contarle acerca de mí.}
{1223}{}{Le pido disculpas, señorita. He pasado mi vida entera haciéndole mantenimiento a este refugio. No tengo nada más que contarle acerca de mí.}
{224}{}{¿Alguna vez has salido del refugio?}
{225}{}{A-a veces subo a la Catedral... pero nunca he estado en la ciudad.}
{226}{}{Parece que estás atado a este lugar.}
{227}{}{R-rezo a nuestro Señor Supremo, porque me permite vivir y me da un trabajo. ¡Salve el Señor Supremo!}
{228}{}{Entonces no eres libre. Tengo otra pregunta.}

{230}{}{¿Quieres escapar de aquí?}
{231}{}{¡De ninguna manera, señor! Si salgo del refugio, me muero. El Señor Supremo dice eso, para mí es obvio.}
{1231}{}{¡De ninguna manera, señora! Si salgo del refugio, me muero. El Señor Supremo dice eso, para mí es obvio.}
{232}{}{Te asusta mucho hablar del tema.}
{233}{}{¡Me disculpo, señor! He estado aquí durante toda mi vida... Yo no sé como puedo vivir allá afuera. ¡Tengo miedo, señor!}
{1233}{}{¡Me disculpo, señorita! He estado aquí durante toda mi vida... Yo no sé como puedo vivir allá afuera. ¡Tengo miedo, señorita!}
{234}{}{Ya veo. Tengo una duda, ¿me la puedes responder?}
{235}{}{¿Qué haces aquí?}
{236}{}{Por el bien del Fuego Santo, yo le sirvo humildemente al Señor Supremo de Fénix y a su Asesor. Ellos me confiaron el mantenimiento de este lugar, es mi labor.}
{237}{}{Ya veo.}
{238}{}{Eso no es lo que piensas, es obvio.}
{239}{}{(Mira a sus pies, sin saber qué decir; parece que los Seguidores del Fuego lo han hecho pedazos.)}

{240}{}{Háblame del refugio.}
{241}{}{Refugio número 25, construido por Vault-Tec para proteger a sus habitantes de la guerra nuclear y sus consecuencias...}
{242}{}{Espera, ¿y entonces cómo entraron los Seguidores del Fuego?}
{243}{}{(su expresión revela que no debería hablar de esto) Ellos... entraron y... e-empezaron a vivir aquí.}
{244}{}{Hay algo que no me estás diciendo.}
{245}{}{N-nuestra computadora tiene un registro histórico, puedes leerlo, es verdad.}
{246}{}{Le echaré un vistazo. Pero primero, cuéntame más del refugio.}
{247}{}{A ellos no les gusta hablar de eso... Los cultistas capturaron el refugio, sólo me dejaron vivo para repararlo.}
{248}{}{Esto es triste. Hablemos de otra cosa.}

{250}{}{Conoces el refugio como la palma de tu mano, ¿verdad?}
{251}{}{(sonriendo irónicamente) Así es, señor, lo conozco muy bien.}
{1251}{}{(sonriendo irónicamente) Así es, señorita, lo conozco muy bien.}
{252}{}{Algunas puertas están cerradas. ¿Sabes cómo abrirlas?}
{253}{}{N-necesitas una tarjeta de acceso. Todas tienen un nivel de autorización, la de seguridad tiene el más alto.}
{254}{}{¿Habían otros refugios?}
{255}{}{¡Sí, y muchos! Los científicos en el laboratorio saben de ellos.}
{256}{}{El refugio era libre, ¿no? Cuéntame como era.}
{257}{}{Era... hermoso. Vivíamos juntos, había paz y amistad, teníamos comida y energía para todos. Nadie quería salir. Pero luego llegaron... ellos. Usaron una señal para abrir la puerta y luego entraron. Los Seguidores llegaron un tiempo después, e hicieron del refugio su base.}
{260}{}{Tráeme agua, quiero que esté limpia.}
{261}{}{(se va y regresa poco después) Su agua, señor.}
{1261}{}{(se va y regresa poco después) Su agua, señorita.}
{262}{}{Ahora lárgate.}
{263}{}{Gracias.}
{264}{}{Como usted guste.}
{265}{}{¿Siempre haces lo que te dicen los demás?}
{266}{}{(te mira por un momento, asombrado, pero inmediatamente mira hacia abajo)}
{267}{}{¿Siempre haces lo que te dicen los demás?}
{268}{}{No hay extraños en el refugio. Sólo los Seguidores del Fuego Santo. Debo serles útil, esa es mi misión...}
{269}{}{¿Y eso te gusta?}
{270}{}{El Asesor me dice qué debo pensar.}
{271}{}{¿Entonces no sirves al Señor Supremo de Fénix?}
{272}{}{Solo si no va en contra de lo que dice el Asesor.}
{273}{}{Hablemos de otra cosa, mientras ellos no te están mirando.}
{274}{}{Ya veo. Adiós.}

{280}{}{Louis, no te gusta la vida que tienes. ¿Quieres que acabe?}
{281}{}{Lo he pensado. Se fueron todos mis seres queridos. No puedo salir del refugio, incluso si abrieran la puerta y me echaran. ¿Qué puedo hacer? Nada más que ser útil para el Asesor...}
{282}{}{Pero en el fondo, tú no quieres eso, ¿verdad?}
{283}{}{Espera, no deberíamos hablar de esto. Hablemos de otra cosa.}
{284}{}{Bueno, parece que solo eres un perdedor. Disfrútalo.}
{285}{}{Soy patético... ¡Patético! Esta gente nunca se preocupó por mí. ¡Me ven como un esclavo y siempre lo seré!}
{286}{}{Tu sufrimiento debería haber terminado hace mucho tiempo. Ayúdame, podemos destruir este refugio si trabajamos juntos.}
{287}{}{Yo... ¡Por favor, déjame hacer mis deberes por el bien del Fuego Sagrado!}
{288}{}{Entonces quédate aquí, perdedor.}
{289}{}{¿Destruirlo? Por supuesto... ¡Cómo no se me ocurrió antes!}
{290}{}{¿Tienes alguna idea?}
{291}{}{Abajo hay una bomba atómica. Ya está por terminarse, los científicos están esperando unos componentes faltantes, pero ya se puede activar y... (tartamudea y comienza a sudar)}
{292}{}{¿Y qué? ¿Y hacerla explotar? Eso es exactamente lo que tenemos que hacer, Louis. Dime cómo encenderla.}
{293}{}{La oficina del profesor tiene algunas partes, sin ellas, detonar la bomba es imposible...}
{294}{}{Necesitaré una tarjeta de acceso para entrar a su oficina.}
{295}{}{Sí... Toma. Esta tarjeta tiene un alto nivel de autorización. Rezaré por ti...}
{296}{}{Gracias, Louis. Has ayudado enormemente no solo a mí, sino a todo el yermo. Hasta la vista.}
{297}{}{Sabes, es muy fácil ganarse tu confianza, Louis. Iré a contarle al Asesor de esto. Adiós, idiota.}
{298}{}{De todos modos, ¿Por qué necesitan una bomba de uranio?}
{299}{}{N-no lo sé, pero después de que esté completa, piensan enviarla a algún lugar al suroeste, a través del desierto.}
