{100}{}{Ves a un cirujano.}
{101}{}{Ves a un cirujano con una bata manchada de sangre.}
{102}{}{Si no me apuro, ningún tipo de medicina me ayudará con esto...}

# Primer diálogo
{200}{}{¿Cuál es tu problema?}
{201}{}{¿Siempre tienes una actitud tan arrogante hacia los pacientes?}
{202}{}{(se quita los guantes y se frota las manos) Mira, soy un solo tipo, y tengo muchos pacientes que atender. ¿Te crees especial, acaso?}
{1202}{}{(se quita los guantes y se frota las manos) Mira, soy un solo tipo, y tengo muchos pacientes que atender. ¿Te crees especial, acaso?}
{203}{}{No lo sé... ¿Qué me haría especial?}
{1203}{}{No lo sé... ¿Qué me haría especial?}
{204}{}{Que seas parte de los Seguidores... o que tengas muchas chapas. Bueno, ¿necesitas algo?}
{205}{}{Supongo.}
{206}{}{No, no es nada, solo tenía curiosidad.}

# Diálogo repetido
{210}{}{¿Cuál es tu problema?}
{211}{}{Ninguno.}

# Curación
{220}{}{Necesito curación.}
{221}{}{Bueno, veamos. ¿Qué quieres que revise?}
{222}{}{Lesiones.}
{223}{}{Trauma físico.}
{224}{}{Radiación.}
{225}{}{Envenenamiento.}
{226}{}{Olvídalo, sanará por sí mismo.}
{227}{}{Nada fuera de lo normal. Puedo curarte. Pero no eres un Seguidor, así que tendrás que hacer una donación, serán }
{228}{}{ chapas.}
{229}{}{Aquí tienes.}
{230}{}{Nada fuera de lo normal. Podemos curarte.}
{231}{}{Una pena. En ese caso, no puedo ayudarte.}
{232}{}{¿Cómo...?}
{233}{}{Olvídalo, sanará por sí mismo.}
{234}{}{Alabado sea el Fuego Santo. Ahora, vete, tengo otros pacientes que atender.}
{235}{}{Necesito algo más, doctor.}
{236}{}{Adelante, doctor.}
{237}{}{Con mucho gusto.}

{240}{}{¿Has visto algún campesino de la Villa?}
{241}{}{Hmm, uno de los esclavos mencionó a la Villa durante su examen.}
{242}{}{¿Qué le pasó?}
{243}{}{No lo sé. Los informes sobre traslados de esclavos se guardan en la Catedral. Mi trabajo es examinarlos médicamente, nada más.}
{244}{}{Ya veo.}
