{100}{}{Ves una consola.}
{101}{}{Ves la consola de las celdas. Puedes controlar los campos de fuerza de la prisión a través de ella.}
{102}{}{Desactivaste los campos de fuerza de las celdas.}
{103}{}{No tienes el nivel de seguridad suficiente.}

{200}{}{Introducir comando:}
{201}{}{Desactivar el campo de fuerza de la celda 1}
{202}{}{Activar el campo de fuerza de la celda 1}
{203}{}{Desactivar el campo de fuerza de la celda 2}
{204}{}{Activar el campo de fuerza de la celda 2}
{205}{}{Desactivar el campo de fuerza de la celda 3}
{206}{}{Activar el campo de fuerza de la celda 3}
{207}{}{Regresar}
{208}{}{Cerrar sesión}
