{100}{}{Ves a un niño.}
{101}{}{Ves a un niño. Huele a tierra y pescado.}

{110}{}{Garth mata a gente como tú.}
{111}{}{No me toques}
{112}{}{¿De dónde saliste?}
{113}{}{Hablas muy chistoso.}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{*Bostezo*}
{119}{}{Z-z-z}

{120}{}{¿Cuándo llegaste?}  
{121}{}{¿De dónde vienes?}  
{122}{}{¿Quieres jugar?}  
{123}{}{¿Conoces algún lugar que sea genial?}  
{124}{}{Hay un monstruo en el fondo del embalse.}  
{125}{}{Si nadas en el agua de allá, te crecerán cuernos como a un demonio.}  
{126}{}{¿Tienes algo rico para comer?}  
{127}{}{El pescado apesta.}  
{128}{}{Estoy buscando algo que nos sirva.}  
{129}{}{ }  

{130}{}{¿Eso es una motocicleta, verdad?}  
{131}{}{¡No puede ser! ¿Esa cosa se conduce sola?}  
{132}{}{¿Sabes de cosas viejas? Eres como Rufus.}  
{133}{}{¿La puedes conducir?}  
{134}{}{¿Crees que la moto pueda atrapar peces o predecir el clima?}  
{135}{}{Los rangers deberían tener motos..}  
{136}{}{¿En dónde conseguiste una moto?}  
