{100}{}{Ves a un ciudadano.}
{101}{}{Ves a uno de los pocos ciudadanos del Acueducto.}

{110}{}{Necesito descansar.}  
{111}{}{Mañana tenemos que revisar las redes bien temprano.}  
{112}{}{Hrrr...}  
{113}{}{Es muy tarde como para hablar.}  
{114}{}{¿Qué está pasando?}  
{115}{}{¿Cómo se te ocurre levantar a la gente a estas horas?}  
{116}{}{Si me vuelves a despertar, te arrepentirás...}  
{117}{}{}
{118}{}{}
{119}{}{}

{120}{}{Sabemos quién eres. Lárgate.}  
{121}{}{No te queremos aquí.}  
{122}{}{Todos sabemos qué tipo de persona eres. Y no queremos eso.}  
{123}{}{Fuera de aquí.}  
{124}{}{Lárgate o los rangers se encargarán de ti.}  
{125}{}{Si nos molestas, Garth te hará pagar.}  
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

{130}{}{Bienvenido al Acueducto.}  
{131}{}{¿Piensas en quedarte?}  
{132}{}{Hola.}  
{133}{}{Me alegra verte.}  
{134}{}{¿En dónde te vas a quedar?}  
{135}{}{Tengo una habitación libre si la quieres.}  
{136}{}{¿Te enviaron los rangers?}  
{137}{}{Necesitamos más gente como tú.}  
{138}{}{¿Me ayudas a limpiar las redes?}  
{139}{}{Nos vendría bien que te quedes.}  

{140}{}{Lo siento, pero la gente se pone nerviosa con los nuevos.}  
{141}{}{¿Qué quieres?}  
{142}{}{No sé nada, y no tengo nada para darte.}  
{143}{}{No me molestes.}  
{144}{}{Ha sido un día pesado, hablemos luego.}  
{145}{}{Parece que estaré ordenando las redes todo el día. De nuevo.}  
{146}{}{¿Sientes el olor? Sólo es pescado y agua. Te acostumbras.}  
{147}{}{Dicen que hay un monstruo en el Colorado.}  
{148}{}{Ten cuidado si vas a nadar, el Monstruo de Arizona está allá afuera.}  
{149}{}{Las redes no atraparon nada... otra vez.}  