{100}{}{Ves a un poblador.}
{101}{}{Ves a uno de los habitantes del Acueducto.}

{200}{}{Es muy tarde para visitarme, ¿no crees?}
{201}{}{Sólo quería...}
{202}{}{¡Sáquese de aquí!}
{203}{}{Está bien, nos vemos.}

{210}{}{No tengo tiempo, lo siento. Habla con Garth o alguien menos ocupado.}
{211}{}{Estoy ocupado, habla con alguien más.}
{212}{}{Acabo de enterarme de que Garth estaba detrás de las desapariciones. Ya entiendo por qué no nos quería cerca del acueducto. Pero, ¿y ahora quién nos va a cuidar?}
{213}{}{Así que eres un ranger, ¿cómo estás?}
{214}{}{Adiós.}

{220}{}{¿Qué estás haciendo?}
{221}{}{Me estoy alistando para un gran viaje de pesca en el embalse de la presa. Será muy duro.}
{222}{}{¿Quién construyó el acueducto?}
{223}{}{No lo sé, si te soy sincero. Quizás hayan sido los rangers, desde siempre que está ahí.}
{224}{}{¿Qué piensas de Garth?}
{225}{}{Un tipo fuerte e inquebrantable. Siempre nos cuida las espaldas, nos protege de los forajidos, saqueadores y de las alimañas. Vive en la casa de allá.}
{226}{}{¿Cómo es la vida bajo la protección de los rangers?}
{227}{}{Es genial. Nos protegen de los saqueadores y los animales, y nosotros les pagamos con un poco de nuestra comida. No tengo quejas.}
{228}{}{¿Sabes algo acerca de las desapariciones?}
{229}{}{Parece que alguna bestia se los comió. En el valle hay lobos y ratas cerdo, los forasteros no lo saben.}
{230}{}{Escuché que tienen una epidemia.}
{231}{}{Sí, algún tipo de fiebre golpeó a unos pocos. Algunos han mejorado, pero los demás siguen mal. El tipo que vive en la choza de allá está de lo peor.}

{240}{}{Hablo por la gente de Ciudad Garaje. Tienen un serio problema, les falta comida.}
{241}{}{Hmm. Escuché que la ciudad está llena de chatarreros. Pero nosotros sólo necesitamos partes para arreglar los botes de vez en cuando. Además, dicen que por allá aborrecen a los rangers. Deben estar muy mal si quieren tratar con nosotros.}
{242}{}{Entonces, ¿qué tal si hacen un trato con Ciudad Garaje? Ustedes dan pescado y ellos las partes.}
{243}{}{Tendré que convencer a los rangers para que estén de acuerdo. Pero si hay beneficios, dudo que se nieguen. Podemos enviar una caravana con pez seco, aunque sea una ciudad fea y apestosa.}
{244}{}{Ellos se mueren de hambre y tú piensas en cómo te vas a beneficiar de eso. Supongo que así son las cosas.}
{245}{}{Genial, les diré que están de acuerdo.}
