{100}{}{Ves a la Ranger Agatha.}
{101}{}{Ves a una ranger veterana, está equipada con una armadura de combate.}
{102}{}{Esa armadura es impresionante, hasta casi tengo envidia.}

#First dialogue
{200}{}{Los civiles no pueden estar caminando por la base. Si tienes alguna pregunta, ve al centro de información. Es el edificio de afuera, junto a la carretera.}
{201}{}{Está bien.}
{202}{}{Tranquilo, Ranger. Es bueno verte en nuestra base. Si tienes alguna duda, pregunta.}
{203}{}{Gracias, capitana.}
{204}{}{¡Atención, Ranger! O sigues el protocolo o te largas de aquí. No tengo tiempo para gente como tú.}
{205}{}{Parece que mi reputación te enoja. ¿Podemos hablar?}
{206}{}{(Ves a una mujer formidable con una armadura de combate. Su comportamiento militar se ve acentuado por una voz áspera, además de un corte de pelo corto y rígido.)}
{207}{}{¿Te puedo hacer una pregunta?}

#Re-dialogue
{210}{}{Bien, ¿qué pasa, viajero?}
{1210}{}{Bien, ¿qué pasa, viajera?}
{211}{}{¿Qué pasa, Ranger?}
{212}{}{Hasta luego.}

{213}{}{Hmm... (te observa con confusión, al ser necrófago) ¿Te... enfermaste, o algo así? No vayas a contagiar a los demás con lo que sea que tengas.}
{214}{}{No te preocupes por eso.}

{220}{}{Así que tú eres el de la motocicleta, tienes a todos los cadetes emocionados. ¿En dónde la conseguiste?}
{1220}{}{Así que tú eres la de la motocicleta, tienes a todos los cadetes emocionados. ¿En dónde la conseguiste?}
{221}{}{Es un trofeo.}
{222}{}{Un trofeo ganado en batalla se merece respeto. (se ajusta la armadura, con orgullo)}
{223}{}{Pensé que lo apreciarías.}
{224}{}{Fue un regalo.}
{225}{}{Si tú lo dices, tendré que creerte.}
{226}{}{Así es.}
{227}{}{¿Qué tal si vamos a dar un paseo en mi motocicleta, preciosa?}

#Questions
{230}{}{Tengo unas preguntas que hacerte. ¿Puedo?}
{231}{}{Mi nombre es Agatha, superviso al equipo de entrenamiento.}
{232}{}{}
{233}{}{}
{234}{}{Es como si los Rangers fueran una familia para ti, los cadetes son como los niños.}
{235}{}{Se podría decir que sí. Pero cuando el deber llama, los motivos personales no importan.}
{236}{}{¿Puedo hacerte otra pregunta?}
{237}{}{¿En dónde conseguiste esa armadura de combate?}
{238}{}{Es un trofeo de una operación de combate. Tuve que repintarla para que no me confundieran con un enemigo.}
{239}{}{¿Qué quieren decir esas rayas?}
{240}{}{Es la marca de una veterana, hijo. Cuando un Ranger ha estado impartiendo la justicia en el Yermo por un largo tiempo, reciben esta insignia de distinción. Me gané la mía después de servir muchos años.}
{1240}{}{Es la marca de una veterana, señorita. Cuando un Ranger ha estado impartiendo la justicia en el Yermo por un largo tiempo, reciben esta insignia de distinción. Me gané la mía después de servir muchos años.}
{241}{}{¿Qué haces aquí?}
{242}{}{Últimamente he estado llevando a cabo el entrenamiento básico para los cadetes.}
{243}{}{¿Una veterana, con los novatos?}
{244}{}{He tenido una buena cantidad de batallas. Es hora de pasarle mis habilidades a los jóvenes.}
{245}{}{¿Por qué le rapaste la cabeza a los cadetes?}
{246}{}{Para que las personas como tú lo pregunten. Y para bajarle la vanidad a los jóvenes.}
{247}{}{Ah, entiendo. Es parte de la disciplina mental.}
{248}{}{No, no es disciplina. Es para inculcarles fortaleza y autocontrol. Además, es bueno para la higiene.}
{249}{}{Pues, no puedo contradecirte en eso.}

#Education
{250}{}{¿Puedes entrenarme?}
{251}{}{¿Crees que voy a entregarte una ametralladora porque sí? Entrenamos a nuestros propios cadetes, y tú no estás en la lista.}
{252}{}{Entonces cambiemos de tema.}
{253}{}{No sólo puedes, sino que debes. Sin embargo, se me informó de que eres un caso especial, así que llevaremos a cabo un curso comprimido de entrenamiento básico.}
{1253}{}{No sólo puedes, sino que debes. Sin embargo, se me informó de que eres un caso especial, así que llevaremos a cabo un curso comprimido de entrenamiento básico.}
{254}{}{Estoy preparado para el curso.}
{1254}{}{Estoy preparada para el curso.}
{255}{}{De acuerdo, pero ahora mismo eso está en pausa. Tengo otros deberes que hacer.}
{256}{}{Está bien, empecemos con los fundamentos de la supervivencia. Todo ranger necesita eso.}
{257}{}{De acuerdo.}
{258}{}{Ahora, vamos a pasar las habilidades de combate. Cubriremos un poco de todo, pero cada ranger tiene sus preferencias. ¿Cuál es la tuya?}
{259}{}{}
{260}{}{Me vendrá bien entrenar con un revólver. (Armas Pequeñas)}
{261}{}{Debería enfocarme en usar un rifle. (Armas Grandes)}
{262}{}{Quiero aprender el Lanzamiento Ranger. (Armas Arrojadizas)}
{263}{}{Voy a utilizar el combate improvisado. (Desarmado)}
{264}{}{Debería prestar atención a usar un cuchillo. (Armas Melee)}
{265}{}{¡Prepárate, Ranger! ¡Ve al campo de entrenamiento! Veamos lo que tienes.}  
{266}{}{¡Pongámonos con ello!}

#Personal Story
{270}{}{¿Cómo te convertiste en una ranger?}
{271}{}{Cuéntame sobre cómo te uniste a los rangers.}
{272}{}{No soy una persona muy abierta, para ser exactos..}
{273}{}{Está bien, no hay problema.}
{1273}{}{Está bien, no hay problema.}
{274}{}{La verdad es que me da curiosidad.}
{275}{}{Entonces te interesa, ¿no? Bueno, es una vieja historia. Era sólo una niña cuando los saqueadores atacaron nuestro campamento...}
{276}{}{Adelante te escucho.}
{277}{}{Eh, ahora no, cuéntamelo luego.}
{278}{}{Conseguí escabullirme entre las ruinas y esperé a que acabara el ataque. Una vez que terminaron, ya no quedaba nadie.}
{279}{}{Suena a que fue difícil.}
{280}{}{Te entró el instinto de superviviente, ¿no?}
{281}{}{Al inicio, estaba perdida. Pero después me enojé y juré que vengaría a mi familia.}
{282}{}{¿Conseguiste vengarte?}
{283}{}{¿Pensabas en eliminar a una pandilla entera? Tienes agallas.}
{284}{}{Me pasé un tiempo perfeccionando mis habilidades. A buscar entre las ruinas, a explorar, eventualmente los eliminé uno por uno. Me llevó un tiempo.}
{285}{}{Fuiste más lista que ellos, es impresionante.}
{286}{}{Los trucos de ese tipo son para cobardes. Pero, eras sólo una niña...}
{287}{}{Pero el yermo está lleno de monstruos y me di cuenta que me convertía en uno, luego de desparramar tanta sangre. El yermo no necesitaba eso, necesitaba el orden. Los Rangers son los únicos que pueden impartir eso. Después de acabar con los saqueadores, no pensé dos veces en unirme.}
{288}{}{Eso es una gran historia.}
{289}{}{Esa historia me es familiar. Yo conocí a alguien que se escondió de los saqueadores y la comunidad no se lo perdonó.}

# Cadet Presley
{300}{}{¿Por qué no permites que el cadete Presley vaya en una misión?}
{301}{}{¡Tomó un rifle del almacén! Incluso si estuviera listo para usar un rifle, alguien tiene que bajarle los humos. Eso le vendría bien a muchos cadetes.}
{302}{}{Entonces, ¿es muy testarudo?}
{303}{}{Más que eso, es ambicioso e impaciente. Los rangers de su tipo no duran mucho y suelen terminar mal.}
{304}{}{Quizás estás siendo muy dura con él.}
{305}{}{¿Y qué, acaso debería consentirlo? Esa no es la forma de convertir un adolescente en un guerrero. Si no es capaz de soportar esta presión, no tiene lo que hace falta para ser un Ranger de verdad.}
{306}{}{¿Por qué no les das la oportunidad de demostrar de qué es capaz?}
{307}{}{Podría dejarlo ir para que enfrente la dura realidad. Pero no puedo cambiar de parecer en frente de los demás cadetes, o perderé su respeto. ¿Entendido?}
{308}{}{Tú sabes cómo entrenarlos mejor. Yo me voy.}
{309}{}{Quizás pueda sacar al cadete Presley, bajo el pretexto de una escolta.}
{310}{}{No sé por qué te metes, pero... puede que sea lo mejor. Voy a asignar a Presley para que te escolte, también le diré al intendente que puede recuperar su equipamiento.}
{311}{}{Genial, iré a contarle las buenas noticias.}
{312}{}{Así está mejor.}
{313}{}{¿En dónde está el cadete Presley? Eres la última persona con la que fue visto.}
{1313}{}{¿En dónde está el cadete Presley? Eres la última persona con la que fue visto.}
{314}{}{Murió mientras cumplía con su deber.}
{315}{}{¡Carajo! ¡No sé por qué confié en un imbécil como tú! ¡Fuera de mi vista o perderé la paciencia!}
{1315}{}{¡Carajo! ¡No sé por qué confié en un imbécil como tú! ¡Fuera de mi vista o perderé la paciencia!}
{316}{}{Em...}

{320}{}{¿Sabías que al intendente le faltan algunas armas de la armería?}
{321}{}{Sí, y estás intentando resolver esto, ¿verdad? Pero, ¿sabes qué? Ese acumulador necesita limpiar ese polvoriento almacén. Porque no creeré ni por un segundo que mis cadetes son capaces de robar.}
{322}{}{[Más]}
{323}{}{Y no dejaré que nadie los acuse de algo. ¿Lo entendiste? Tengo que seguir entrenándolos.}
{324}{}{Claro, no hay problema.}
{325}{}{Sí, lo que tú digas.}
