{100}{}{Ves a un cadete.}
{101}{}{Ves a uno de los reclutas.}

{110}{}{Dicen que pelear allá afuera es más fácil que pasar este maldito entrenamiento.}  
{111}{}{La capitana Agatha es una maldita bestia, no es humana.}  
{112}{}{El Comandante Helford parece de otro mundo. Lo admiro.}  
{113}{}{Dicen que el general está cubierto de pelo, por eso siempre lleva la gabardina.}  
{114}{}{Ojalá supiéramos que demonios estaba ocurriendo en California.}  
{115}{}{De verdad quiero ir a almorzar.}  
{116}{}{¿Cómo voy a dormir luego de escuchar todas esas historias de monstruos?}  
{117}{}{El entrenamiento terminará algún día... ¿cierto?}  
{118}{}{Si te soy honesto, esto no es tan malo.}  
{119}{}{¿Piensas en unirte?}  

