{100}{}{Ves al Cadete Burke.}
{101}{}{Ves a un cadete delgado e inexperto. Era de esperarse que lo pusieran aquí.}

{200}{}{(Ves a un joven con el cuello delgado; al verte, es incapaz de mantener el contacto visual y da una sonrisa forzada repetidamente) Eh, adiós, o sea, ¡hola! ¿Con qué lo, em, ayudo hoy?}
{201}{}{¿Qué es este lugar?}
{202}{}{Esto es el centro de, em, información... o sea, el área de recepción, creo... (cambia a una postura recta) Pero, aquí es donde, eh... ¡Aquí es donde recibimos a los forasteros, señor!}
{1202}{}{Esto es el centro de, em, información... o sea, el área de recepción, creo... (cambia a una postura recta) Pero, aquí es donde, eh... ¡Aquí es donde recibimos a los forasteros, señorita!}

{203}{}{¿"Recibimos" ¿Quiénes son ustedes?}
{204}{}{(expresión confundida) Em, los Rangers... O sea... (se pone recto) ¡Cadete Burke a su, eh, servicio! Si necesita a un ranger, tendrá que agendar una hora.}
{205}{}{¿Quién está detrás de esa puerta?}
{206}{}{El Comandante Helford... Pero, eh, usted no tiene una hora agendada, así que, no puedo, eh, o sea...}
{207}{}{Genial, quizás él me puede ayudar.}
{208}{}{Un momento, ¡espere!}
{209}{}{[Hecho]}

{210}{}{Necesito hablar con tu jefe.}
{211}{}{¿El General? Oh, oh no, no puede ver al General...}
{212}{}{¿Y entonces a quién puedo hablarle?}
{213}{}{El Comandante Helford está, eh, detrás de esa puerta... Pero, tú tienes, o sea, usted tiene que agendar una hora, no puedo dejar que...}
{214}{}{Genial, quizás él me puede ayudar.}
{215}{}{Eh, ¡espere!}
{216}{}{[Hecho]}

{220}{}{Sólo no me metas en problemas.}
{221}{}{No lo haré.}
{222}{}{Em, lo felicito por su ascenso. Yo aún tengo que, eh, esperar muchos años hasta ser un ranger.}
{223}{}{Buena suerte.}
