{100}{}{Ves a un anciano.}
{101}{}{Ves a un hombre enjuto de manos callosas. Su piel está chamuscada por trabajar bajo el sol.}

#Responses after dialogue
{110}{}{Creo que ya fue suficiente.}
{111}{}{Tengo que volver a la granja.}
{112}{}{Gracias por escucharme.}
{113}{}{Los muertos pueden esperarme, la cosecha no.}
{114}{}{Perdóname, me puse sentimental.}

#Dialogue
{200}{}{(Ves a un anciano, se encuentra pensativo ante una tumba)}
{201}{}{[Siguiente]}
{210}{}{¿Qué quieres?}
{211}{}{Nada, no importa.}
{212}{}{Ya veo.}
{213}{}{.}
{220}{}{¿Quién eres, viejo?}
{221}{}{¿Viejo? Ja, apenas tengo cuarenta... Pero parece que soy más viejo que las montañas. Soy un granjero, vivo a un par de millas.}
{222}{}{Entonces, ¿no eres parte de los rangers?}
{223}{}{No seas ridículo. Con mi edad y manos como estas, ¿cómo podría ser un ranger? Trabajo en la granja, perseguir saqueadores no es lo mío.}
{224}{}{Pasé al lado de una granja en el camino hasta acá.}
{225}{}{Hay algunas granjas y ranchos en el área. Los rangers nos cuidan, pero se llevan su parte de la cosecha. A veces nos dejan con nada más que lo necesario para sobrevivir... Pero las cosas están mejorando. La tierra se recupera poco a poco de la Gran Catástrofe.}
{226}{}{¿La Gran Catástrofe?}
{227}{}{Un día tomaba té con el General y me lo contó. Hace cien años, cuando cayeron las bombas, estas tierras quedaron cubiertas de nubes radioactivas, llenas de lluvia ácida. Las nubes venían del este, oeste y el sur, dependía del viento. En esos días, las cosas estaban mal por todos lados. Dijeron que la tierra fue estéril durante generaciones, y que sólo los cactus podían sobrevivir gracias a sus raíces. Sólo en estos últimos tiempos han mejorado las cosas.}
{230}{}{¿Qué haces aquí?}
{231}{}{¿Qué crees que hacemos los viejos en un cementerio? Recuerdo los viejos días. Esta es la tumba de mi hijo, la inscripción en su tumba ya casi no está, pero aún tengo la cabeza como para recordar su nombre y en dónde está enterrado.}
{232}{}{¿Cómo murió?}
{233}{}{Los jóvenes son impacientes, trabajar la tierra los cansa. Pero la tierra sólo es generosa a quienes la trabajan duro durante años. Ocurrió eso con mi Jacob, se unió a los rangers porque no quería trabajar. Mientras patrullaba, se encontró con unos saqueadores.}
{234}{}{¿Crees que fue culpa de los rangers?}
{235}{}{No lo pienso así. Los Rangers hacen algo noble - traen el orden al yermo. Es cierto que muere gente en el proceso. No puedes salvar a todos, ayudas a uno y hieres a otro. Así funciona la justicia.}
{240}{}{¿De quiénes son estas tumbas?}
{241}{}{Los rangers tienen una tradición para enterrar a los suyos. Los entierran y colocan una bala en la tumba, suele ser una bala de revólver. Si no hay de revólver, cualquiera funciona, si no hay ni eso, utilizan un casquillo. Es su forma de decir que no deberías perder el espíritu, incluso en la muerte.}
