{100}{}{Ves a un barquero junto a las aguas.}
{101}{}{Ves a un paleto calvo, tiene una sonrisa retorcida en el rostro.}
{102}{}{Tú sí sabes como hacer feliz a un viejo.}

#First Dialogue
{200}{}{¿Qué te trae por aquí?}
{201}{}{Quizás necesite tu ayuda.}
{202}{}{Bueno, mi nombre es Jo. Vivo acá, al lado de la barcaza. Si quieres pasar al otro lado, es muy fácil... pero no es gratis.}
{1202}{}{Bueno, mi nombre es Jo. Vivo acá, al lado de la barcaza. Si quieres pasar al otro lado, es muy fácil... pero no es gratis.}
{203}{}{Me lo pensaré.}

#Re-Dialogue
{210}{}{Hola.}
{211}{}{Hasta luego.}
{220}{}{¿Cómo es vivir aquí?}
{221}{}{No tengo quejas. No es un lugar tranquilo, viene gente a diario - rangers, pescadores o simplemente viajeros. Todos pagan lo que se debe para ir al otro lado. Y eso me da lo necesario para sobrevivir.}
{222}{}{[Seguir]}
{223}{}{Los lobos y las ratas cerdo nunca me dejan en paz, eso es obvio, pero he vivido aquí por años y ya sé lidiar con ellos. Tengo trampas en el bosque, así que no te salgas del camino para que no deba sacarte de un apuro.}
{224}{}{Háblame de la barcaza.}
{225}{}{Los rangers me dieron la idea, y la construí. La he cuidado desde ese entonces. Si alguien necesita cruzar el río, yo los ayudo.}
{226}{}{¿Por qué cruzaría alguien el río?}
{227}{}{Los rangers suelen patrullar por ahí. Pero también hay mucha gente que viaja a otros lados, buscando un lugar mejor en donde vivir. Pero déjame decirte que vayas a donde vayas, la vida es difícil en todos lados.}
{228}{}{¿A los rangers no les molesta que cobres?}
{229}{}{No les molesta, porque les tengo que pagar impuestos. Una vez al mes, les entrego lo que me hayan pagado - pieles, carne, cosas que se encontraron por ahí. A veces ni siquiera sé con qué demonios me pagaron, pero los rangers se encargan de eso.}
{230}{}{¿Cómo te afectó la destrucción de la presa?}
{231}{}{Fue un desastre, mi cabaña está hecha polvo y ni me imagino quién haría tal cosa. Pero en lo personal, ha sido un milagro - la barcaza me está haciendo más dinero que nunca.}
{232}{}{Qué interesante. Tengo otra pregunta.}
{233}{}{Tengo otra duda.}
{250}{}{Tengo a algunas personas que necesitan cruzar el río.}
{251}{}{Pues que paguen, es barato. Y si no pagan, ahí se quedan. No les daré la manivela.}
{252}{}{¿Cuánto cuesta?}
{253}{}{Te lo pido en nombre de los rangers.}
{254}{}{Mierda, otro día más en el que salgo perdiendo... Toma, llevate la manivela, pero que ellos la giren.}
{1254}{}{Mierda, otro día más en el que salgo perdiendo... Toma, llevate la manivela, pero que ellos la giren..}
{255}{}{Gracias.}
{256}{}{Eres un angelito.}
{257}{}{Espérame, veré si tienen las chapas para pagarlo.}
{258}{}{Sólo dame la manivela, o te arrepentirás.}
{259}{}{Muy bien, ¡a ver esas manos! He matado lobos yo sólo, ¿crees que me das miedo?}
{260}{}{¡Basta ya!}
{261}{}{No soy de los que regatean, ¿sabes?}
{262}{}{[Más]}
