{100}{}{Ves al cadete Presley.}
{101}{}{Estás viendo a uno de los reclutas nuevos.}
{102}{}{Descansa en paz, cadete Presley.}
{103}{}{¡Cadete, no es el momento de morirse!}
{104}{}{Te deseo suerte en tus viajes.}
{105}{}{La cabaña de los Milton está allá, pero debemos encontrar la entrada a la caverna.}
{106}{}{¿Tienes algún problema con la familia Milton?}

#First dialogue
{200}{}{(Ves a un cadete joven, claramente está de mal humor; está sentado como si esperase a que algo ocurra, de vez en cuando patea una lata para aliviar su tensión)}
{201}{}{¿Por qué no estás en fila con los demás?}
{202}{}{La capitana Agatha me me reprendió por no seguir sus órdenes. ¿A ti qué te importa?}
{203}{}{No eres bueno siguiendo reglas, ¿verdad?}
{204}{}{Carajo, ¡es sólo que estaba cansado de estas malditas sesiones de entrenamiento! Quiero misiones de verdad, no fingir que le estamos disparando a unos coyotes.}
{205}{}{Parece que eres muy ambicioso.}
{206}{}{Quizás. Pero yo creo que esperar tres años para tener un desafío de verdad no tiene sentido. Si Agatha no me encarga una misión y me regresa mi equipamiento, voy a salir con una maldita lanza.}
{207}{}{Lo que tú digas. Por ahora, iré a hablar con ella.}
{208}{}{No eres más que un mocoso egocéntrico. Adiós, perdedor.}
{209}{}{No me hables así, novato.}

#Re-Dialogue
{210}{}{¿Qué?}
{211}{}{Nada. Adiós.}
{220}{}{¿Por qué te llevaste el rifle del almacén?}
{221}{}{Las armas sólo se entregan durante las misiones y los entrenamientos, también debes conservar tu munición. Quería irme con el rifle hacia la caverna en Giers Wash, pero el intendente no tardó en darse cuenta de mi plan.}
{222}{}{¿Qué tiene de importante esa caverna?}
{223}{}{Los lugareños dicen que hay un montón de roedores viviendo ahí adentro y que le hacen daño a los aldeanos. Pero los Rangers están muy ocupados como para una pequeñez de ese tipo y los comandantes se rehúsan a enviar a los cadetes a lidiar con ello, dicen que no estamos listos.}
{224}{}{[Seguir]}
{225}{}{Quería resolver el problema sólo, por mi cuenta, así podría demostrarle a estos viejos testarudos lo mucho que se equivocan. ¡Deberíamos estar haciendo algo, no hacer el ridículo aquí adentro!}
{226}{}{Eres muy dedicado, eso es respetable.}
{227}{}{Me parece que sólo quieres demostrar *tus* capacidades.}
{228}{}{¿Qué era eso que decías sobre la caverna en Giers Wash?}
{230}{}{¿Cómo es tu relación con los demás cadetes?}
{231}{}{Depende de quien sea. Algunos me hacen enojar así que intento ignorarlos.}
{232}{}{De acuerdo.}
{233}{}{Se honesto. ¿Alguna vez has matado a... una persona?}
{234}{}{Aún no. Lo mejor a lo que un cadete puede aspirar es que te manden a exterminar unos lobos. Pero *voy* a matar a la escoria criminal, se supone que cada Ranger debe hacerlo.}
{235}{}{Jamás lo había pensado.}

#Quest
{300}{}{Acerca de la cueva, quizás podríamos ir juntos hacia allá.}
{301}{}{¿En serio? Pero, ¿por qué te importa? ¿Por qué arriesgar tu pellejo?}
{302}{}{Quiero ser parte de la acción, será divertido.}
{303}{}{Claro. Pero no nos dejarán usar armas de verdad, también tenemos que conservar munición. Y usar armas de balines sólo sirve contra objetivos que ya están muertos.}
{304}{}{Quiero ayudar a los Rangers para que se enfrenten al yermo.}
{305}{}{Buscas hacer amigos aquí adentro, ¿verdad? Bien pensado. En el yermo, a cualquiera le viene bien un aliado fuerte.}
{306}{}{Agatha me pidió que te vigile.}
{307}{}{¿De verdad? ¿Cree que soy un niño y que no puedo matar unas alimañas por mi cuenta? Aunque... un acompañante no me vendrá mal... también harías de testigo, sólo por si acaso.}
{308}{}{¿Entonces?}
{309}{}{¡Sí! Está bien... Pero sin armas, no puedo ir.}
{310}{}{Tu equipamiento está en la mesa del intendente. Fue gracias a mí.}
{311}{}{¿¡Qué!? ¿Cómo hiciste eso? Genial, iré a la intendencia de inmediato. Tú también deberías alistarte. Nos vemos afuera, junto al centro de información.}
{312}{}{Ahí nos vemos.}
{320}{}{Ya podemos irnos. ¿Tienes todo lo necesario?}
{321}{}{Espérame un rato.}
{322}{}{¿Qué crees que deberíamos llevar?}
{323}{}{En la caverna estará oscuro, así que un par de bengalas vendrán bien. También habrán muchas ratas cerdo. Por su cuenta no son ninguna amenaza, pero en grupo pueden ser un peligro. Contra un grupo así, una escopeta funcionará. Pero para ser sincero, no tengo ni las mínima idea de dónde conseguir una.}
{324}{}{Creo que vale la pena tenerlo en cuenta.}
{325}{}{Entonces, vamos.}
{326}{}{¿Por qué volvimos? ¿Te olvidaste de algo?}
{1326}{}{¿Por qué volvimos? ¿Te olvidaste de algo?}
{327}{}{No te preocupes, no me tardaré.}
{328}{}{De acuerdo, pero Hazlo rápido.}
{329}{}{Está bien.}
{330}{}{¿Con un grupo así? Entrar en grupo no es la mejor estrategia para una caverna estrecha. Y sólo asustaremos a los animales, alguien de tu grupo debería quedarse atrás.}
{331}{}{Lo hablaré con mi acompañante.}
{332}{}{Escúchame, es sobre los Milton. Vamos a decir que no tuvimos nada que ver con eso, ¿bien? Sabía que era mala idea meterme en esto. No creo que la cabeza de esa rata haya valido la pena. Adiós.}
{333}{}{Adiós, Presley.}
{334}{}{¿Por qué...? ¿Por qué hizo eso?}
{335}{}{¿Estás bien?}
{336}{}{No lo sé... Ese bandido... Tenía un arma, podría haber encontrado otra forma de sobrevivir, pero atacó a una familia indefensa. ¿Por qué lo hizo?}
{337}{}{Es la única forma que conocía.}
{338}{}{Y yo soy igual a él, ¿cierto? Ahora entiendo el por qué teníamos que pasar por nuestro entrenamiento, el por qué no nos asignan las misiones de verdad. De ahora en adelante, me tomaré más en serio lo que digan los veteranos.}
{339}{}{Gracias a esto, te volviste un poco más sabio. Adiós, cadete.}
{340}{}{Esto es uno de los principios del yermo - es matar o que te maten. Yo iré de vuelta al desierto.}
{341}{}{Fue genial, ¿no es así? Le voy a mostrar esta cabeza a los demás en el comedor. Te deseo suerte en tus viajes.}
{342}{}{Adiós, Presley.}
{350}{}{Cuídate la espalda.}
{351}{}{Vamos.}
{352}{}{Y, ¿cuál es nuestro objetivo?}
{353}{}{Encontrar y a cazar a Nat-Aani. Los lugareños le pusieron ese nombre a la rata más grande y peligrosa de esta cueva.}
{354}{}{¿Qué significa ese nombre?}
{355}{}{Que es el líder de la manada, lo que quiere decir que es el más fuerte y feroz de todos.}
{356}{}{¿Qué sabes sobre la familia Milton?}
{357}{}{¿Por qué te importan? Pues, son normales, son pobres, viven aquí. Sobreviven pescando y recolectando. No hay mucho que decir sobre ellos.}
{358}{}{No hablemos de esto, ¿bien?}
{359}{}{¿Qué carajo ocurrió contigo y los Miltons? Jamás habían sido así de agresivos.}

{360}{}{¡Lo hicimos! Le cortaré la cabeza a esta rata y se la mostraré a los ancianos de la base. ¡Eso les mostrará que estoy listo para una misión seria de verdad!}
{361}{}{¿Esa es la única razón por la que quisiste hacer esto?}
{362}{}{Obvio. ¿Por qué más ayudaría a estos pobres? Son inútiles, y no importa lo que hagas, no te darán recompensas ni te subirán el rango. Pero por algo así, como mínimo me darán raciones dobles. ¡Ja!}
{363}{}{Hmm. Salgamos de aquí.}

{364}{}{¿¡Cómo!? Esto es una broma, ¿no? ¡No esperaba que tuviera que pelear con un bandido!}
{365}{}{¿Qué pasa, cadete? Hace un momento te estabas bañando en sangre, le cortaste la cabeza a esa rata.}
{366}{}{¡Eso es distinto! Agh, mierda, que mal momento para venir aquí... ¿Y ahora qué hacemos?}
{367}{}{Hay que hacer algo. Si esperamos, él escapará o se va a atrincherar. En ese caso, lo más seguro es que alguien muera.}
{368}{}{Exacto. Ahora mismo, tenemos la ventaja. Él no se esperaba que fuéramos a venir. Pero, debemos tener cuidado - un hombre no es un animal, es más inteligente que eso.}
{369}{}{Vamos.}
{370}{}{No podemos lidiar con él, sólo somos dos. Hay que salir corriendo a la base.}
{371}{}{Exacto, pero si hacemos eso, tendrá tiempo para prepararse y puede que hasta mate a alguien si entramos. Sería mejor salir corriendo de aquí y dejar esto en secreto.}
{372}{}{Vámonos.}
