{100}{}{Ves al Jason, el ranger.}
{101}{}{Ves al ranger que rescataste de los Chacales. Parece que se encuentra mejor.}

{200}{}{Así que nos volvemos a encontrar. Me salvaste la vida, gracias.}
{201}{}{Te ves mucho mejor que en la guarida de los Chacales.}
{202}{}{Fue un viaje difícil, pero nos entrenaron para esa clase de cosas. Mira, necesitamos más gente como tú. ¡Únetenos! Sé que no es mucho, pero le conté al Comandante Helford sobre ti. Deberías hablar con él.}
{203}{}{Lo pensaré.}
{204}{}{Fue un viaje difícil, pero nos entrenaron para esa clase de cosas. Por cierto, vi tu nombre en la lista de reclutas. Te felicito por unirte a los rangers. Sé que ayudarás a la gente del yermo.}
{205}{}{Gracias por darme la bienvenida. Debo irme.}
{206}{}{Ustedes hablan tanto, ni siquiera me dieron un rifle. Adiós.}

{210}{}{Me alegra verte. ¿Cómo estás?}
{1210}{}{Me alegra verte. ¿Cómo estás?}
{211}{}{Nos vemos luego.}
{212}{}{¿Qué piensas de la alianza entre los Rangers y los Chacales?}
{213}{}{Después de lo que pasé, parece un mal sueño. ¡¿En qué demonios estaban pensando?! Pero... mi trabajo es seguir órdenes, no cuestionarlas.}
{214}{}{Ya veo.}
