{100}{}{Ves a la ranger Agatha.}
{101}{}{Ves a una ranger veterana con una armadura de combate.}
{102}{}{Parece que Agatha está ocupada. Deberías esperar a que termine antes de hablarle.}
{103}{}{No quiero hablar contigo.}
{104}{}{Agatha ignora tu presencia.}

#Cut-scene of an argument with the general:
{110}{}{¡Esto es una locura!}  
{111}{}{¿¡Tienes la menor idea de a cuántos rangers han matado los Chacales!? ¡Seguro se los comieron a todos!}  
{112}{}{¡Tenemos que quitar a esos bastardos de la faz de la tierra!}  
{113}{}{¡A cada uno de ellos!}  
{114}{}{¡Y a ti se te ocurre aliarte con ellos!}  
{115}{}{¡Es asqueroso!}  
{116}{}{Puedes sermonearme todo lo que quieras por faltarte el respeto.}  
{117}{}{Pero los demás rangers piensan lo mismo. ¡Ésto está mal!}  
{118}{}{Una alianza no cambiará lo que son, son unos salvajes...}  
{119}{}{...y de ninguna manera nos regresará a nuestros muertos.}  
{120}{}{¡No toleraré esto!}  


{200}{}{¡Tú! ¡Todo es culpa tuya! Los Chacales han sembrado el caos en el norte durante años, mataron a muchos de nuestros rangers más valientes. Esto es una abominación, no toleraré una alianza con esos salvajes. ¡Lárgate de mi vista!}
{201}{}{Aprende a perdonar. Quizás cambies de parecer cuando veas los beneficios que nos traerá esta alianza.}
{202}{}{Tu forma de pensar es demasiado violenta como para reconocer que un alto al fuego es lo mejor. Quédate ciega, mujer.}
