{100}{}{Ves al Ranger Stark.}
{101}{}{Estás viendo al Soldado Stark.}
{102}{}{Gracias, Doc. Pensé que me quedaría cojo por el resto de mi vida.}

#First dialogue
{200}{}{(el ranger está aburrido, pero cobra vida al ver que un forastero entra al comedor; te invita cordialmente a su mesa) ¡Hola, forastero! Es la primera vez que te veo. ¿De dónde eres?}
{1200}{}{(el ranger está aburrido, pero cobra vida al ver que una forastera entra al comedor; te invita cordialmente a su mesa) ¡Hola, forastera! Es la primera vez que te veo. ¿De dónde eres?}
{201}{}{De un pueblo del norte, se llama Villa.}
{202}{}{Bueno, he patrullado en otras direcciones, pero he escuchado un poco sobre la Villa. ¿Son ustedes los que consiguen tener cosechas en medio del desierto? Eso es maravilloso. Pensé que era la típica mentira que cuentan en el comedor.}
{203}{}{¿Y tú eres...?}
{204}{}{No es asunto tuyo.}
{205}{}{Oye, no estaba siendo grosero contigo, ¿cierto? Pero entiendo que desconfíes de mí. Si no quieres, no me digas.}
{206}{}{¿Quién eres?}
{207}{}{Soy Stark, un soldado de los Rangers, si entiendes lo que es eso.}
{208}{}{Hola, Stark. ¿Podemos hablar un momento?}
{209}{}{Hola, Stark. Adiós, Stark.}

#Re-dialogue
{210}{}{Tienes toda mi atención.}
{211}{}{Adiós.}
{212}{}{Tengo otra pregunta.}

#Questions
{220}{}{¿Por qué viven encima de una presa?}
{221}{}{¿Cómo? Este lugar es perfecto - nos protege contra los enemigos y el mal tiempo. Nadie sería capaz de atacarnos o espiarnos.}  
{222}{}{¿De verdad es tan seguro este lugar?}
{223}{}{Esta presa seguirá aquí por un par de siglos más. Al menos eso dice el Viejo Rufus. ¿Y qué es lo peor que podría pasar? Es un pedazo de concreto en medio de las montañas.}
{224}{}{¿Quién es el Viejo Rufus?}
{225}{}{Es el supervisor de la presa. Ha estado en ese cargo por unos doce años y un poco más. Aunque muchos creen que no hace nada para ganarse sus raciones. Siempre está en la central eléctrica, si quieres hablarle.}
{226}{}{¿Así que todos los Rangers de Arizona viven aquí?}
{227}{}{Claro que no, este cuartel sólo te aloja por un tiempo. Sólo puedes conseguir una cama aquí adentro por un tiempo limitado o bajo algún caso especial. Y cuando no estás aquí, tienes que encontrarte algún lugar por ahí, igual que cualquier Ranger de verdad.}  

{230}{}{Tengo una duda, ¿cómo se une alguien a los cadetes?}
{231}{}{Hay unas cuantas formas. Por lo general, necesitamos una recomendación de alguien en quien confiemos, por ejemplo - comerciantes, líderes de asentamientos aliados, u otros Rangers. Si no tienes eso, tendrás que demostrar lo que vales a través de tus acciones.}  
{232}{}{¿Cuánto tiempo dura el entrenamiento?}
{233}{}{Al menos unos cinco años, pero depende mucho del cadete. Para ganarte un ascenso, debes ganártelo a través de méritos de verdad ahí afuera.}  
{234}{}{¿También eres un cadete?}
{235}{}{¿Yo? No, no. Pero tengo que darle una mano a los nuevos. Esa es nuestra costumbre - si no puedes ayudar ahí afuera, ayuda dentro de la base.}
{236}{}{¿Qué te impide participar en las misiones?}
{237}{}{¿Esa pierna te impide ser útil en una misión, cierto?}
{238}{}{(da una palmada a su pierna, está vendada) Esos malditos lobos, me atacaron mientras patrullaba el río Colorado. Me distraje, y pague el precio.}
{239}{}{Quizás pueda ayudarte y echarle un vistazo.}
{240}{}{Si me pagas, quizás pueda revisar tu pierna.}
{241}{}{Ah, eso es una pena. Hablemos de un tema menos negativo.}
{242}{}{¿En serio? Lo apreciaría mucho. Pero, ¿sabes lo que haces, verdad?}
{243}{}{Déjame ver...}
{244}{}{Usa tus habilidades médicas o medicamentos para tratar la herida.}

{250}{}{Un ranger tan experimentado como tú debe tener muchas historias que contar.}
{251}{}{Siempre le pregunto a los viajeros lo que han visto, jamás me pierdo esa oportunidad. Aunque es cierto que la mayoría exageran sus historias, al menos un poco.}

{270}{}{Habías hablado de unos lobos. ¿Qué otras criaturas hay por el Colorado?}
{271}{}{Bueno, posee una fauna muy diversa, a diferencia del desierto.}
{272}{}{¿Como por ejemplo?}
{273}{}{Sí, me he dado cuenta.}
{274}{}{Entre los matorrales, puedes encontrar lagartos cornudos del tamaño de un perro. A simple vista, no parecen ser una amenaza, pero sus cuerpos son pinchudos y hace que sea difícil luchar cuerpo a cuerpo. Y por si fuera poco, son muy inteligentes y unos maestros del camuflaje.}  
{275}{}{Que interesante... cuéntame más.}
{276}{}{Hay criaturas así por todo el yermo, no son nada especial.}
{277}{}{¿Esa no es la más aterradora, sabes? Las cavernas son el hogar de los murciélagos bulldog - son unos verdaderos diablillos. Te esperan en la salida de la cueva y salen volando con velocidad, ni siquiera te dan tiempo a entender qué está pasando. Una de esas cosas es capaz de agarrar a un adulto y arrastrarlo al interior de la cueva. Y hasta ahí llegaste.}
{278}{}{¿Lo dices en serio? Eso me da un poco de miedo.}
{279}{}{Esto es difícil de creer. ¿Y dices que son criaturas locales?}
{280}{}{Entre las rocas del Colorado, puedes encontrar ciempiés de hasta dos metros de largo. Pueden escupir un veneno que te matará en segundos. Su caparazón es tan duro que ni siquiera un cuchillo lo penetra, y sus mandíbulas son tan fuertes que podrían partir a un hombre a la mitad.}
{281}{}{¡Santa madre de...! ¿Estas cosas de verdad existen?}
{282}{}{Me parece que estás exagerando un poco, ¿no crees?}
{283}{}{También he oído rumores acerca de mariposas hipnóticas que te pinchan y sobre armadillos que utilizan vehículos viejos como caparazones. Pero, en mis viajes, yo sólo he visto lobos, lagartos y ratas.}
{284}{}{Gracias por contarme esto, fue muy... educacional.}
{285}{}{Mantén los ojos bien abiertos.}
{286}{}{Hablemos un poco más.}
{287}{}{Entonces nos vemos luego, debo irme.}
{288}{}{Tu charla me está aburriendo. ¿Acaso intentas asustar a todos los que hablan contigo?}
{289}{}{Bueno... Todo lo que te conté, lo escuché de otras personas, no me culpes. Pero, hay muchas criaturas agresivas por ahí, eso no lo dudes. Cuídate la espalda.}
{290}{}{Cuéntame sobre las criaturas del Río Colorado.}

#Promotion Party
{310}{}{¡Vaya, es la nueva *estrella*, en persona!}
{311}{}{Sí, conseguir esta placa no fue nada fácil. Pero, ¿cómo te enteraste?}
{312}{}{En esta base, los rumores no tardan en ir de boca a boca. Pero, ¿sabes qué? No esperes que te de un regalo. ¡Los demás se pasan años intentando ganarse su placa, y tú llegas y la agarras!}
{313}{}{Pude ver que no te agradé cuando nos conocimos, pero la verdad no me importa.}  
{314}{}{Ojalá que algún día cambies de parecer acerca de mí.}
{315}{}{Sí, sí.}
{316}{}{¿Estás ocupado? ¿Tienes un momento?}
{317}{}{Creo que ya me voy.}
{318}{}{Disfruta tu día. Por hoy, eres un héroe.}
{1318}{}{Disfruta tu día. Por hoy, eres una estrella.}

{320}{}{¿Te estás burlando de mí?}
{321}{}{¿Apenas te das cuenta? Quizás sea porque nadie te está haciendo un desfile. Los demás nos quebramos la espalda durante años para ganarnos la placa, y tú llegaste así sin más y la agarraste. Así que no esperes que te lo celebre.}  
{322}{}{En esta base, los rumores no tardan en ir de boca a boca. Me alegro por ti. No hay muchas personas que puedan subir de rango tan rápidamente - de hecho, nadie lo hace. En honor a ti, déjame darte un poco de mis suministros. ¡Bien hecho!}  
{323}{}{Gracias, una fiesta sobre la presa es lo que siempre he querido.}
{324}{}{No hay mucho que celebrar por una placa, pero me llevaré las frutas.}

{330}{}{Oye, ¿tus historias son todas falsas, o son reales?}
{331}{}{Bueno... hay una historia que definitivamente no es ficción. ¿Te interesa?}
{332}{}{Te escucho.}
{333}{}{En otro momento.}
{334}{}{Hay un escorpión gigante allá afuera, vive en el desierto - es más grande que cualquier otro que hayamos visto. Se dice que esta bestia ya ha devorado a varios grupos de viajeros. Si lo encuentras y lo cazas, le estarías haciendo un favor a todo el mundo.}  
{335}{}{Pensándolo bien, no quiero saber de esto.}
{336}{}{Pero, todos los escorpiones son gigantes, ¿no?}
{337}{}{¡Sí, pero ese opaca a todos los demás en cuanto a tamaño!}
{338}{}{¿Por qué los Rangers no lo han rastreado y eliminado?}
{339}{}{Esta bestia merodea en el yermo, en donde hasta un Ranger experimentado tiene problemas sobreviviendo. Sale a cazar y al quedar satisfecho, vuelve a esconderse. Para toparte con él, deberás volverte su presa - de una forma u otra.}  
{340}{}{Pero, ¿por qué piensas que esto es cierto y no es ficción?}
{341}{}{Porque lo vi con mis propios ojos - no soy el único. Una vez lo rastreamos en el desierto, entre Quartz y San Brahmán. Hizo pedazos a varios de nosotros y apenas salimos de ahí con vida. Luego de eso, estaba claro que era mejor evitar al escorpión.}  
{342}{}{De acuerdo, intentaré encontrar y matar a esa cosa.}
{343}{}{¿De verdad? Cuanta dedicación, te felicito. Pero si terminas siendo el desayuno de esa cosa, es culpa tuya.}
{344}{}{No hay problema, te traeré un recuerdo.}
{345}{}{Demonios, parece que debo alejarme de esa cosa. Gracias por el aviso.}
{346}{}{Así es.}
{347}{}{Gracias.}

{350}{}{Quiero hablarte acerca del escorpión legendario.}
{351}{}{Ah, ya no quieres salir al yermo después de tal historia, ¿verdad?}
{352}{}{Cambiemos de tema.}
{353}{}{He matado al escorpión.}
{1353}{}{He matado al escorpión.}
{354}{}{¿¡Lo dices en serio!? Pero, claramente no debes tener pruebas, ¿cierto?}
{355}{}{Será fácil ver el cadáver en medio del desierto. Envía una patrulla a investigar - te dirán que es cierto.}  
{356}{}{Hmm, podemos hacer eso. Si es verdad, te doy las gracias de parte de los Rangers. Le has hecho un gran servicio al Yermo entero.}  
{1356}{}{Hmm, podemos hacer eso. Si es verdad, te doy las gracias de parte de los Rangers. Le has hecho un gran servicio al Yermo entero.}  
{357}{}{Pensé que los servicios de este tipo merecían una recompensa.}  
{358}{}{Y yo pensé que una historia así necesitaba pruebas. ¿Cierto?}  
{359}{}{Demonios... Es demasiado tarde como para ir a buscar evidencia. Tendré que conformarme con que me menciones en tus historias.}  
{360}{}{Eso me basta.}  
{361}{}{Lo único que tengo para mostrar es esta lanza - estaba atascada en su caparazón.}  
{362}{}{¡Que me parta un rayo! Recuerdo esa lanza... ¿En *serio* cazaste a esta bestia? Pero, ¿cómo?}  
{363}{}{Era grande, pero lentísimo.}  
{364}{}{La gente como tú debe ser una especie distinta. Llévate unas balas y este viejo revólver, como muestra de gratitud. No digas que no - ya tengo las armas necesarias para asustar a cualquier mutante. Gracias, de nuevo.}  
{365}{}{De nada.}

