{100}{}{Ves a la señorita Milton.}
{101}{}{Ves a la matriarca de la familia Milton.}

#Dialogue
{110}{}{Por favor, ¡sálvanos de las malditas ratas!}  
{111}{}{¡Détenlo antes de que mate a alguien!}  
{112}{}{Te debemos la vida. Si no hubieras estado ahí, nos habría matado.}  
{113}{}{Gracias por la ayuda. Ahora vete, tengo que enterrar a mi esposo.}  
{114}{}{¡Los rangers son unos buenos para nada! ¡Fuera de aquí!}  
{115}{}{¡Atrás! ¡No te me acerques!}  
{116}{}{Gracias por la ayuda. Ojalá que el espíritu de Nat-Aani no vuelva para vengarse.}  
