{100}{}{Ves a un bandido.}
{101}{}{Ves a un peligroso criminal que porta una escopeta, listo para usarla si es necesario.}

{110}{}{¡Quédate ahí y no abras la boca!}
{111}{}{¿En dónde se metió ese maldito niño?}
{112}{}{Si el niño no vuelve pronto, tendré que volarle los sesos a alguien.}
{113}{}{¿Te sientes con suerte, viejo?}
{114}{}{¿Dónde tienen las chapas?}
{115}{}{¡Chingada madre, ni tienen comida!}
{116}{}{¿¡Con quién se creen que se metieron, pendejos!?}
{117}{}{Si el niñito no vuelve con comida, tendré que cortarles los dedos.}
{118}{}{Los dedos son buena carnada.}
{119}{}{}

#Dialogue
{200}{}{¡Alto ahí! ¡Manos arriba!}
{201}{}{Ya estás muerto.}
{202}{}{Estás rodeado, ríndete o te arrepentirás.}
{203}{}{(toma una pausa para pensárselo) ¡Carajo!}
{1203}{}{(toma una pausa para pensárselo) ¡Carajo!}
{204}{}{Vamos...}
{205}{}{(se toma un momento para pensárselo y sale corriendo)}
{206}{}{Así es, piérdete.}
{207}{}{Ya escaparon tus rehenes. Ríndete o estás muerto.}
{208}{}{¿Cómo...? Mierda... No lo olvides, tengo un arma. Me iré de este valle y ustedes se quedarán callados. ¿Entendido?}
{209}{}{Piérdete.}
