{100}{}{Ves al Sr. Milton.}
{101}{}{Ves al patriarca de la familia Milton.}

#Dialogue
{110}{}{No tenemos mucho que dar a cambio, pero no nos vas a dejar a la merced de las ratas, ¿verdad?}  
{111}{}{¡Deténlo! ¿¡No se supone que los rangers tienen que ayudarnos!}  
{112}{}{No sabes cuanto agradezco que nos hayas salvado. Tienes mi respeto.}  
{113}{}{Agradezco tu ayuda, pero eso no me devolverá a mi esposa.}  
{114}{}{¿¡Para qué son buenos, malditos rangers!? ¡Váyanse y déjenme tranquilo!}  
{115}{}{¡Aléjate de mí!}  
{116}{}{¿Mataste a Nat-Aani? ¡Qué alivio!}  
