{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}

{210}{}{Revisar estado de la estación.}
{211}{}{Unidad hidráulica 1: Activa. Unidad hidráulica 2: Activa. Unidad hidráulica 3: Inactiva. Esclusas bajas: 1,2,3,5. Esclusas altas: 4.}
{212}{}{Bajar Esclusa 4. Será divertido ver como el agua inunda la presa.}
{213}{}{¡Peligro! Esto desactivará la presa. Esto cambiará el régimen hidrológico del embalse. ¿Está seguro?}
{214}{}{Estoy seguro.}
{215}{}{La esclusa 4 ahora está baja. ¡Atención! Todas las esclusas están bajas.}
{216}{}{Es hora de salir corriendo.}
{217}{}{¿Qué? ¡No, no es necesario bajarla! Cancelar.}
