{110}{}{Es una buena idea, si quieres suicidarte.}
{111}{}{No puedes hacer eso durante el combate.}
{112}{}{Los rangers que están de servicio te aconsejan que no entres.}
{113}{}{Los rangers te dieron acceso únicamente a ti, a tus compañeros no.}
{114}{}{[Sigilo 120] Tus distracciones son en vano.}
{115}{}{Los rangers que están de servicio te prohíben entrar con la servoarmadura.}

{120}{}{No podrás hacer eso sin que te vean. Tendrás que negociar con los guardias.}
{121}{}{Esto no tiene sentido.}
{122}{}{Esta puerta no parece ser peligrosa.}
{123}{}{Una puerta casera muy resistente. ¿Le habrán pagado bien al que la hizo?}
{124}{}{No es necesario reparar esto.}
{125}{}{No es necesario reparar esto. No se puede decir lo mismo de la presa detrás de la puerta.}
