{100}{}{Ves a Corwin.}
{101}{}{Ves al cocinero. Está cantando una canción bastante vieja.}
{102}{}{¿No ves que estoy cocinando? No puedo hablar ahora.}
{103}{}{¿?}

# NOTA DEL TRADUCTOR AL ESPAÑOL: La canción original era de la película de 1950 'Vaya par de Soldados', pero la reemplace por 'Guadalajara en un Llano' de Negrete, no había versión en español de la otra
{110}{}{~ Guadalajara en un llano ~}
{111}{}{~ México en una laguna ~}
{112}{}{~ Me he de comer esa tuna ~}
{113}{}{~ Aunque me espine la mano ~}
{114}{}{~ La águila siendo animal se retrató en el dinero ~}
{115}{}{~ Para subir al nopal ~}
{116}{}{~ Pidió permiso primero ~}
{117}{}{~ Dicen que soy hombre malo, malo y mal averiguado ~}
{118}{}{~ Porque me comí un durazno ~}
{119}{}{~ De corazón colorado ~}

{200}{}{~ No sé cómo fui a quererte, ni cómo te fui adorando... ~}
{201}{}{Hola.}
{202}{}{¡Ahh! ¿Qué? ¿Qué pasó? No me vuelvas a asustar así.}
{203}{}{¿Qué estás haciendo?}
{204}{}{Estaba cantando...}
{205}{}{¿Llamas a eso cantar?}
{206}{}{No te gusta hacerlo, ¿verdad?}
{207}{}{La verdad es que no.}
{208}{}{Es que no conozco mis tonos... ¿Quién eres? Es la primera vez que te veo.}
{209}{}{No es asunto tuyo, soldado. Sigue cocinando.}
{210}{}{No te preocupes por eso, lo importante es disfrutarlo.}
{211}{}{¡Así es! ¿Y quién eres tú? No te había visto antes.}
{212}{}{Me uní a la Hermandad hace poco.}
{213}{}{Ah, felicitaciones. Debo seguir cocinando, ¿te importa?}
{214}{}{Se te está quemando la comida, soldado. Adiós.}
{215}{}{No soy parte de la Hermandad, tengo un pase.}
{216}{}{Bueno, no es problema mío. Pero si eres un civil, no puedes estar en la cocina.}
{217}{}{Está bien, ya me voy.}
{218}{}{[No lo molestes]}
{219}{}{Nos vemos luego.}

{220}{}{Señor, sí, señor... Ah, eres tú.}
{221}{}{¿De verdad tienes permiso de estar a bordo?}
{222}{}{Tu sí que tienes suerte, puedes irte al yermo cuando te de la gana. Yo hace años que no salgo.}
{223}{}{~ Por unos ojitos negros, negritos como mi suerte ~}
{224}{}{~ Viajera que vas por cielo y por mar, dejando en los corazones ~}
{225}{}{Dile al doctor que no estoy, me dan miedo las agujas.}
{226}{}{"¡Apúrate, Corwin!" "¡Lava las ollas, Corwin!", "¡Se te quemó el arroz, Corwin!" Babosos...}

{229}{}{Hola... O sea, ¡Iniciado Corwin reportándose, señor!}
{1229}{}{Hola... O sea, ¡Iniciado Corwin reportándose, señorita!}

{230}{}{Me dijeron que aquí podía venir a almorzar. Soy un nuevo recluta.}
{231}{}{Ah, bienvenido a bordo. Aquí tienes tu almuerzo, si quieres comer más, tendrás que pagar con tus propias chapas.}
{232}{}{Gracias, Iniciado.}
{233}{}{Pensé que la Hermandad nos daría comida de verdad, en vez de... esto.}
{234}{}{¿Me puedes vender un poco de comida?}
{235}{}{De ninguna manera, sólo tengo permitido vender la comida excedente a la Hermandad.}
{236}{}{Entonces olvídalo.}
{237}{}{Te iba a dar unas chapas extra, pero ya perdiste tu oportunidad. Idiota.}
{238}{}{No seas así, sé que debes tener comida extra.}
{239}{}{Mira, esto te puede meter en problemas. Y ni siquiera eres uno de nosotros. Piérdete y no me molestes.}
{240}{}{Tonto, acabas de perder la oportunidad de hacerte rico. Adiós.}
{241}{}{}
{242}{}{Anda, nadie se dará cuenta de que faltaron un par de platos. Además, te ganarás unas chapas.}
{243}{}{Vale, pero no puedo venderte mucho. Sólo mantén la boca cerrada.}
{244}{}{Claro. Será un secreto, Corwin.}
{245}{}{Está bien, tengo permiso.}
{246}{}{De acuerdo...}
{247}{}{Gracias.}

{250}{}{¿Cuál es tu nombre, soldado?}
{251}{}{Soy Alvin Corwin. Me encargo de la cocina.}
{252}{}{Trabajar en la cocina debe ser muy vergonzoso para un paladín.}
{253}{}{Sí, pero no soy un paladín. Ni siquiera he decidido quién quiero ser.}
{254}{}{¿Eres un paladín o un escriba?}
{255}{}{Ninguno. Todavía no escojo una división.}
{256}{}{Pero, ¿entonces por qué no estás entrenando?}
{257}{}{Estoy cumpliendo con mi condena. Me perdí el entrenamiento matutino porque me pasé toda la mañana buscando al sargento...}
{258}{}{Eso pensaba. Si fueras un buen soldado, no te tendrían en la cocina.}
{259}{}{¿Me estás tomando el pelo? Buscaba al sargento, pues quería un permiso para bajar a tierra, pero no lo encontré en ningún lado.}
{260}{}{El entrenamiento es muy duro para ti, ¿verdad?}
{261}{}{Sólo necesito un descanso. Hace mucho que no tengo un descanso.}
{262}{}{Eso me parece injusto. ¿Siquiera fue tu culpa?}
{263}{}{Exacto. De verdad necesitaba un descanso, pero no encontré a nadie que lo firmara. Busqué por toda la nave.}
{264}{}{¿Y si yo fuera a conseguirte el permiso para bajar a tierra? ¿Qué me darías a cambio?}
{265}{}{¿Harías eso por mí? Puedo pagarte con comida o compartirte mi munición.}
{266}{}{Consideralo hecho.}
{267}{}{Pensándolo bien, no tengo ningún contacto o autoridad en la nave. No creo que sea capaz de ello.}
{268}{}{Podría intentar que te firmen el permiso.}
{269}{}{¿En serio? Eres mi última oportunidad.}
{270}{}{Haré lo que pueda.}
{271}{}{Ahora que lo pienso, no creo que pueda hacerlo.}
{272}{}{Acerca de tu descanso...}
{273}{}{¿Lo conseguiste?}
{274}{}{La verdad no.}
{275}{}{¿Por qué querrías bajar a tierra? Por aquí solo hay desierto.}
{276}{}{En el noreste hay un asentamiento llamado Casa Nueva. Nuestros soldados patrullan el área, dentro y fuera. Es un buen pueblo - la gente es agradable, el aire es fresco. No es como el montón de chatarra en el que estamos parados. Al mediodía, hace tanto calor que podría andar en calzoncillos.}
{277}{}{Comprendo. Buena suerte.}
{278}{}{Todavía no. Pero no tengo claro en cómo puedo conseguir el permiso. ¿Alguna idea?}
{279}{}{Pero... ¿Cómo puedo conseguir el permiso?}
{280}{}{¿Por qué querrías bajar a tierra? No hay más que desierto allá afuera.}
{281}{}{Si lo supiera, ya lo hubiera intentado. Por lo general, el único que puede firmar tal cosa es alguien de alto rango. También pueden asignarte en alguna patrulla, pero no les agrada enviar a un novato como yo. Prefieren que me quede moviendo cajas.}
{282}{}{Lo conseguí, tienes cuatro días.}
{283}{}{No puede ser, ¿lo dices en serio?}
{284}{}{Claro, sólo quería ayudarte.}
{285}{}{Lo digo en serio. Pero, todo tiene un precio.}
{286}{}{Necesito las chapas para el descanso. ¿Qué tal si te entrego mi cartuchos? De todas formas, jamás me fueron de ayuda.}
{287}{}{Trato hecho, les encontraré algún uso.}
{288}{}{Gracias. Se lo diré al sargento y estará verde de la envidia.}
{289}{}{Pásala bien.}

{300}{}{¿Qué haces de comer, soldado?}
{301}{}{Frijoles, señor.}
{1301}{}{Frijoles, señorita.}
{302}{}{¿Frijoles? ¿Nada más?}
{303}{}{Sí, los novatos recibimos malas raciones. Los paladines comen lo mejor.}
{304}{}{¿Es por eso que todos andan con la cara larga?}
{305}{}{Tienen sus razones, supongo. Aunque yo soy el que debe cocinar. Ahora tenemos pescado, carne y harina de maíz, pero cuando estamos bajos de suministros, apenas sobrevivimos. Haría lo que sea por un buen filete...}
{306}{}{No he visto muchos filetes en el yermo.}
{307}{}{Espera, tú sales del barco, ¿podrías traernos café? Juntaremos dinero y compraremos las latas que traigas.}
{308}{}{Me parece bien. Si encuentro algo, es tuyo.}
{309}{}{El café es muy raro de encontrar, dudo que encuentre.}
{310}{}{No puedo ayudarte con eso. Adiós.}
{311}{}{Mira lo que tengo, una lata con café de verdad.}
{312}{}{¡Genial! ¡Te la compro! Te daré }
{313}{}{ chapas por esa lata.}
{314}{}{Lo siento, pero no hay trato. Yo también quiero, no te la voy a dar.}
{315}{}{Es un trato justo. Los demás comerciantes me pagarán menos.}
{316}{}{Gracias, con gusto compraré más latas si las traes.}
{317}{}{Eso haré.}
{318}{}{Tómala, es gratis. Es mi muestra de gratitud para la Hermandad.}
{319}{}{¡Muchas gracias! Sé que los demás lo agradecerán.}
{320}{}{De nada. Espero que lo disfruten.}
{321}{}{Fideos, señor.}
{1321}{}{Fideos, señorita.}
{322}{}{¿Fideos? ¿Nada más?}
