{100}{}{Ves al instructor.}
{101}{}{Ves a un paladín novato, se la pasa gritando órdenes y soplando el silbato siempre que pueda.}

{200}{}{¿Eres un civil? ¡Entonces cállate!}
{201}{}{Lo que tú digas.}
{202}{}{Espera. ¿Qué es este lugar?}
{203}{}{¡Es el cuarto de entrenamiento, eso es obvio! ¿Para qué crees que tienes ojo, gusano?}
{204}{}{Para... absorber la luz, señor.}
{205}{}{¡Idiota! ¡Sal de aquí y no vuelvas nunca!}
{1205}{}{¡Estúpida! ¡Sal de aquí y no vuelvas nunca!}
{206}{}{Señor, sí señor...}
{207}{}{Eh, sólo buscaba el, eh, el baño...}
{208}{}{¿En serio? ¿Puedo unirme?}
{209}{}{Espera, también quiero entrenar.}
{210}{}{¡Idiota! Esto es una base militar, ni siquiera permitimos a los civiles.}
{1210}{}{¡Estúpida! Esto es una base militar, ni siquiera permitimos a los civiles.}
{211}{}{Bueno, entonces me voy. Adiós.}
{212}{}{¿Podemos ahorrarnos esto? Tengo muchas chapas, ¿qué tal si te doy mil y me dejas entrenar?}
{213}{}{Hmm... Bueno, veamos cuánto resistes, gusano. ¿Qué buscas aprender, de todas formas?}
{214}{}{Eso no importa, primero tengo que ir por las chapas.}
{215}{}{Entrenamiento en Armas Pequeñas.}
{216}{}{Entrenamiento en Armas Grandes.}
{217}{}{Entrenamiento en Armas de Energía.}
{218}{}{Entrenamiento en combate Desarmado.}
{219}{}{Entrenamiento en Armas Melee.}
{220}{}{Entrenamiento en como Lanzar granadas y cuchillos.}
{221}{}{Quizás debería tomar una de tus lecciones, todo Paladín de la Hermandad debería entrenarse.}
{222}{}{Quizás debería tomar una de tus lecciones, todo Explorador de la Hermandad debería entrenarse.}
{223}{}{¿Así que eres uno de los nuestros? ¡Para MÍ, no eres más que un pedazo de mierda en mi suela! ¡Dime tu rango, soldado!}
{1223}{}{Así que eres uno de los nuestros? ¡Para MÍ, no eres más que una vieja que ni sabe barrer el piso! ¡Dime tu rango!}
{224}{}{Yo, eh... Necesito hablar con el comandante. Ya vengo, señor.}
{225}{}{¡No vas a llorar, ni mear, ni llamar a tu mamá a no ser yo te diga! Ponte al frente de la fila. ¡A marchar!}
{226}{}{¡Señor, sí señor!}
