{100}{}{Ves a Cacarizo.}
{101}{}{Ves a un necrófago. Parece estar muy adolorido, si no hubiera sido por tu motocicleta, estaría un poco mejor.}
{102}{}{¿De dónde sacaste tu licencia, señorito? ¿De una caja de cereal?}
{1102}{}{¿De dónde sacaste tu licencia, mujer? ¿De una caja de cereal?}
{103}{}{¡Oh, mierda!}

{110}{}{¡Ahhh! ¡Qué dolor!}
{111}{}{¡Ay! ¡Mi cadera!}
{112}{}{¿Alguien ha visto mi vesícula?}
{113}{}{¡Mi columna! ¡Mi columna!}
{114}{}{Un doctor...}
{115}{}{¿Alguien me puede dar un estimulante?}
{116}{}{¿Por qué a mí?}
{117}{}{Primero un camión, luego una camioneta, ahora una moto....}
{118}{}{Esto me empieza a parecer aburrido...}
{119}{}{}

{200}{}{¡Ayy, eso dolió! ¿Por qué siempre termino bajo las ruedas!}
{201}{}{Lo siento, ¿estás bien?}
{202}{}{¿Que si estoy bien? Solo tengo unos huesos rotos, la cadera fracturada, y la vejiga rota... Estoy como nuevo.}
{203}{}{Lo siento mucho, fue un accidente.}
{204}{}{¡Claro! Les dije a esos idiotas que necesitábamos señales de tráfico. ¡Y nadie me escucha! Fue como esa vez que me atropelló un camión de Nuka-Cola. ¡Habían chapas por todos lados!}
{205}{}{Eso es... terrible.}
{206}{}{¿Chapas por todos lados? ¡Órale! Imagina encontrarte con eso en medio del desierto.}
{207}{}{Agh... Mira, me apena cortarte la charla, pero necesito levantarme. ¿Me vas a ayudar o qué?}
{208}{}{¿En serio?}
{209}{}{¿Estás seguro? Quizás deberías quedarte ahí...}
{210}{}{No te preocupes. Eventualmente, todo sana. Pásala bien.}
{211}{}{Adiós.}
{212}{}{Oops...}
{213}{}{¿Te vas a quedar ahí parado? ¿Y si me haces primeros auxilios? ¿Boca a boca? ¿No? Bueno, me las voy a arreglar.}
{214}{}{Gracias a Dios, pensé que estarías peor. Nos vemos.}
{215}{}{¡Ahh! ¡Poca madre, apenas me puedo mover! De verdad, duele. Al menos las he tenido peores... Como cuando me atropelló el camión de Nuka-Cola, las chapas salieron volando.}
