{100}{}{Ves a Paul.}
{101}{}{Ves a un hombre de aspecto demacrado.}

{200}{}{Es bueno verte, amigo mío. ¿Recuerdas cuando nos escapamos de esos supermutantes? Fue una locura.}
{1200}{}{Es bueno verte, hermana. ¿Recuerdas cuando nos escapamos de esos supermutantes? Fue una locura.}
{201}{}{Sí que fue un buen día.}
{202}{}{Les conté a todos en la Hermandad y es obvio que ahora les agradas más. Quiero darte las gracias, así que toma, tres estimulantes y una pistola láser con algo de munición. Ten cuidado allá afuera.}
{203}{}{Gracias, te deseo suerte.}

{210}{}{Bienvenido a bordo. ¿Te puedo ayudar en algo?}
{211}{}{Nada, gracias.}

{220}{}{¿Me recordarías cuál es tu rango?}
{221}{}{Soy el Caballero Paul. Solía ser el líder del Departamento de Investigación de Armas de Energía. Luego me enviaron al yermo para que ayudara a los paladines. Eventualmente fui capturado por los supermutantes.}
{222}{}{¿Crees que pueda conseguir un arma por aquí?}
{223}{}{Habla con el intendente, no tengo algún arma que pueda darte, pero... si encuentras un rifle de plasma, tráemelo.}
{224}{}{Espero que disfrutes de tu trabajo.}
{225}{}{Gracias, tengo que irme.}
{226}{}{Tengo que irme. Adiós.}
{227}{}{Gracias, nos vemos.}
{228}{}{Gracias por decírmelo, nos vemos.}
{229}{}{}
{230}{}{¿Me ayudarías a salvar a mi pueblo?}
{231}{}{Lo siento, pero tengo trabajo que hacer aquí. Ya tuve suficientes aventuras.}
{232}{}{¿Tienes alguna parte de servoarmadura?}
{233}{}{No... No soy bueno con las servoarmaduras, habla con el intendente, quizás tenga alguna parte de repuesto. Aunque si no le agradas, no será nada fácil.}
{234}{}{¿Es mi única opción?}
{235}{}{Pues... dicen que los Hojalateros saben cómo hacerlo, pero creo que te cobrarán muy caro.}
{236}{}{Tengo un rifle de plasma. ¿Crees que puedas mejorarlo?}
{237}{}{¡Es un Winchester P94! Es un arma genial, siempre he admirado su potencia y fiabilidad. Pensaba que era imposible mejorar algo así.}
{238}{}{¿Pero?}
{239}{}{Pero... Una vez, un hombre me mostró una mejora que tenía en su rifle. El plasma se calentaba más rápido de lo normal. Creo que podría imitarlo.}
{240}{}{¡Claro! Aquí lo tienes}
{241}{}{No, gracias. Podrías quebrar algo...}
