{100}{}{Ves a un paladín.}
{101}{}{Pelo corto, armadura, brazos como troncos - ves a un paladín de la Hermandad del Acero.}

{200}{}{Todo está bien, cambio.}
{201}{}{¿Cómo te va? Aquí está tranquilo.}
{202}{}{Me alegra verte. Pero, ¿por qué no estás patrullando?}
{203}{}{¿Quieres salir a patrullar? Habla con el Paladín Latham.}
{204}{}{No hay ningún paladín más experimentado que el General Dixon. Es por eso que está aquí.}
{205}{}{Necesitamos más soldados como tú.}
{206}{}{Bienvenido a la Hermandad.}
{207}{}{*Saludo militar*}
{208}{}{}
{209}{}{}

{210}{}{Vuelve al yermo, salvaje.}
{211}{}{La curiosidad mató al gato, ¿lo sabías?}
{212}{}{No deberías andar por aquí como si fuera tu casa.}
{213}{}{¿Tienes permiso de estar aquí? Tienes suerte...}
{214}{}{Dame una sola razón y te lanzaré por la borda.}
{215}{}{Mi estrategia es muy simple - ataca primero antes de que te den por la espalda..}
{216}{}{¿Quién demonios te dejó pasar?}
{217}{}{¿Así que dejamos que un civil se pase por la nave? Esto es un caos...}
{218}{}{No muerdo, a no ser me des una razón.}
{219}{}{}

{220}{}{En la Hermandad, tenemos un dicho: "El mejor aliado es el que está muerto."}
{221}{}{Un momento, ¿tienes un pase? Muéstramelo...}
{222}{}{Más te vale que no me hagas enojar, maldito paleto.}
{223}{}{¿Llegas sin avisarnos y nos exiges respuestas? Estás mal de la cabeza.}
{224}{}{Quédate aquí y no te muevas hasta que sepa quién eres y como evadiste a los guardias.}
{225}{}{Vaya, vaya, así que tenemos una rata...}
{226}{}{No hablo con civiles.}
{227}{}{¿El centinela sabe que estás aquí?}
{228}{}{¿Un forastero? Tienes cinco segundos para decirme qué haces aquí, o si no...}
{229}{}{¿Siquiera sabes lo que es un buque?}

{230}{}{¿Pasa algo?}
{231}{}{Deberías hablar con el comandante.}
{232}{}{Esto es un área restringida, no puedes estar aquí sin permiso.}
{233}{}{¿Qué te trae a la Hermandad?}
{234}{}{¿Quieres unirte a la Hermandad?}
{235}{}{No solemos aceptar a los forasteros, pero han habido algunas excepciones.}
{236}{}{¿De dónde eres?}
