{100}{}{Ves a un escriba.}
{101}{}{Ves a un escriba de la Hermandad del Acero.}

{210}{}{¿Qué estás haciendo aquí? ¿Quién te autorizó?}
{211}{}{No me distraigas, estoy en medio de una importante investigación.}
{212}{}{Bienvenido a la Hermandad. Ahora, ve a hacer algo útil.}
{213}{}{¿Te interesa hablar de ciencia?}
{214}{}{¿Crees que tu mente está preparada para entrar en los misterios de la física cuántica?}
{215}{}{¿Aceptas las enseñanzas del gran Isaac Newton, que recibió un golpe en la cabeza con una manzana, que simbolizaba nuestra ignorancia, malentendidos y más profundos miedos?}
