{100}{}{Ves a Young.}
{101}{}{Ves a un niño de unos cinco años.}
{102}{}{Cuando crezca, ¡quiero usar una armadura como esa!}
{103}{}{¡Aléjate! ¡Me defenderé!}

{200}{}{Hola, no te había visto antes.}
{201}{}{Y no me volverás a ver. Adiós.}
{202}{}{Por supuesto que no, yo vengo del yermo.}
{203}{}{¿Vives en el desierto? Eso es raro. ¿Cómo te llamas?}
{204}{}{Primero dime tu nombre.}
{205}{}{Me llamo }
{206}{}{. ¿Y tú?}
{207}{}{Hola, pequeñín, ¿cómo te llamas?}
{208}{}{Dime tu nombre, mocoso.}
{209}{}{Mi nombre es Young, señor.}
{1209}{}{Mi nombre es Young, señorita.}
{210}{}{Tienes un nombre bonito, Young. Es muy único.}
{211}{}{Mis papas me pusieron así, no sé por qué.}
{212}{}{¿A qué idiota se le ocurrió llamarte así?}
{213}{}{Mis papas me pusieron así, y no son idiotas, son mejores que los tontos como tú.}
{214}{}{Ahora que lo pienso, ¿dónde están tus padres?}
{215}{}{Por aquí, en algún lado. Mi papá es el Paladín Latham. Mi mamá debe estar en la orilla, lavando la ropa.}
{216}{}{¿Tu mamá lava los calzoncillos de los paladines?}
{217}{}{No tiene ningún rango, no es una paladín.}
{218}{}{¿Tu mamá es una paladín también?}
{219}{}{Claro que no, señor. No tiene ningún rango.}
{1219}{}{Claro que no, señorita. No tiene ningún rango.}
{220}{}{Un momento, ¿entonces eres hijo de un paladín y una campesina? ¿Siquiera está permitido eso?}
{221}{}{¡Mi papá es el mejor! ¡Puede hacer lo que sea!}
{222}{}{Ustedes tienen unas costumbres muy interesantes.}

{250}{}{Ah, hola.}
{251}{}{¡Señor, sí señor!}
{252}{}{¿En serio eres parte de la Hermandad?}
{253}{}{¿Cuál es tu rango?}
{254}{}{}
{255}{}{Adiós, jovenzuelo.}

{260}{}{¿Me puedes recordar quién eres?}
{261}{}{Soy Young. Mi papá es un paladín, y mi mamá es una campesina. ¿Entendido?}
{262}{}{Entendido.}
{263}{}{¿Cuál es tu trabajo en esta nave?}
{264}{}{Yo hago todo tipo de cosas. Siempre me encargan algo. Que traiga esto, que lleve lo otro.}
{265}{}{Ya veo.}
{266}{}{¿Y qué haces ahora?}
{267}{}{Busco mi juguete. Es pequeño, tiene cuatro patas. Si lo encuentras, tráemelo, ¿sí?}
{268}{}{No estoy de humor para eso.}
{269}{}{Intentaré ayudarte. ¿Te acuerdas en dónde lo dejaste?}
{270}{}{He estado corriendo por toda la cubierta y no lo he visto. No sé dónde está.}
{271}{}{Entonces, no está en la cubierta... Algo es algo.}
{272}{}{Encontré este juguete, ¿es tuyo?}
{273}{}{¡Sí! ¡Es ese!}
{274}{}{Aquí tienes, que no se te vuelva a perder.}
{275}{}{Gracias, señor...}
{1275}{}{Gracias señorita...}
{276}{}{De nada.}
{277}{}{En el yermo, la costumbre es pagarle a alguien por su trabajo. ¿Qué me darás a cambio?}
{278}{}{(saca una tarjeta magnética de su bolsillo con mucha inseguridad)}
{279}{}{¿Una tarjeta para las puertas? ¿Nada más? Bueno, dámela.}

{280}{}{Sal de aquí. Las cosas se van a poner feas.}
{281}{}{¿De qué está hablando, señor?}
{1281}{}{¿De qué está hablando, señorita?}
{282}{}{¡No pierdas el tiempo! Si no te escondes en las ruinas, te va a doler mucho.}
{283}{}{¡Bromeaba! Jaja. No te preocupes.}
{284}{}{*lloriquea*}
{285}{}{Gra... gracias...}
