{110}{}{No es posible cancelar el lanzamiento.}
{111}{}{Ahora soy parte de la Hermandad, no tiene sentido hacer eso.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Cancelar}
{204}{}{Aceptar}
{205}{}{Aceptar los parámetros especificados}
{206}{}{Siguiente}

{210}{}{Establecer parámetros para los torpedos}
{211}{}{Especifique los parámetros.}
{212}{}{Cancelar todo.}
{213}{}{Deja de introducir comandos y cierra la sesión.}
{214}{}{Regresa a los valores predeterminados.}

{220}{}{Ángulo actual OBJETIVO-NOSOTROS.}
{221}{}{Ángulo actual SOMOS EL OBJETIVO.}
{222}{}{Ángulo actual: }
{223}{}{ grados.}
{224}{}{+10 grados.}
{225}{}{+1 grado.}
{226}{}{-1 grado.}
{227}{}{-10 grados.}
{228}{}{Ajustar el ángulo de visión.}

{230}{}{Distancia al objetivo.}
{231}{}{Distancia estimada: }
{232}{}{ yardas.}
{233}{}{+100 yardas.}
{234}{}{+10 yardas.}
{235}{}{+1 yarda.}
{236}{}{-1 yarda.}
{237}{}{-10 yardas.}
{238}{}{-100 yardas.}

{240}{}{Modo ráfaga.}
{241}{}{Modo actual: }
{242}{}{ Ángulo de dispersión: }
{243}{}{Un torpedo.}
{244}{}{Dos torpedos.}
{245}{}{Todos los torpedos.}
{246}{}{}
{247}{}{Ángulo de dispersión: }
{248}{}{0.5 grados.}
{249}{}{1 grado.}
{250}{}{1.5 grados.}
{251}{}{2 grados.}

{260}{}{Velocidad del torpedo.}
{261}{}{Velocidad actual: }
{262}{}{ nudos.}
{263}{}{+5 nudos.}
{264}{}{-5 nudos.}

{270}{}{Profundidad de la explosión}
{271}{}{Profundidad de la explosión: }
{272}{}{ yardas.}
{273}{}{+1 yarda.}
{274}{}{-1 yarda.}

{280}{}{Tipo de espoleta.}
{281}{}{Tipo de espoleta: }
{282}{}{no definida.}
{283}{}{Contacto.}
{284}{}{Magnética.}
{285}{}{Temporizada.}

{290}{}{Colocar el temporizador para activar los torpedos.}
{291}{}{Tiempo restante ante la explosión: }
{292}{}{ segundos.}
{293}{}{+10 segundos.}
{294}{}{-10 segundos.}

{300}{}{Lanzar los torpedos.}
{301}{}{¡Cuidado! ¡El mecanismo de las puertas no responde!}
{302}{}{Perfecto, eso quiere decir que explotarán aquí dentro. Activa los torpedos.}
{303}{}{Oh, no, no, eso no. ¡Cancelar, cancelar!}
{304}{}{Torpedos listos. Faltan... }
{305}{}{ segundos para el lanzamiento.}
{306}{}{Hora de abandonar el bote...}
{307}{}{Presiona botones al azar.}
{308}{}{Oh-oh, parece que empezó una cuenta regresiva...}
