{100}{}{Ves al Maestro Hard.}
{101}{}{Ves al líder de los Hojalateros. Parece tener más metal que carne.}
{102}{}{Vuelve a tu existencia virtual.}

# First Dialogue
{200}{}{(Frente a ti, hay algo que es mitad hombre, mitad máquina; su voz es como raspar metal contra una roca) Un viajero del yermo... No estás en mi base de datos. Identifícate.}
{201}{}{Vengo de la Villa, sólo estoy buscando a mis parientes, puede que estén aquí.}
{202}{}{La Villa... Reconozco ese nombre, está entre mis datos. Algunos de nuestros esclavos vienen de allá. ¿Pero quién eres tú para hacerme preguntas?}
{203}{}{La verdad, no soy nadie especial.}
{204}{}{Eres un ser directo y audaz. Tales rasgos se deben tomar en cuenta. Por lo tanto, permitiré que tú, una mera criatura del yermo, pueda probarse ante nosotros... como un voluntario.}
{205}{}{Estoy con los Seguidores del Fuego.}
{206}{}{Algunas de nuestras unidades proceden de ese culto. Pero estás bajo los Dos Soles, así que los protocolos difieren. Puedes quedarte en nuestra ciudad, pero no distraigas a mis unidades de sus funciones críticas.}
{207}{}{Soy representante de la Hermandad del Acero.}
{208}{}{La Hermandad... Nos proporcionaron energía eléctrica y con conocimiento de tecnologías que se encontraban perdidas. Eres otro portador del metal, ¿cómo podemos ayudarte?}
{1208}{}{La Hermandad... Nos proporcionaron energía eléctrica y con conocimiento de tecnologías que se encontraban perdidas. Eres otra portadora del metal, ¿cómo podemos ayudarte?}
{209}{}{Estoy aquí porque busco a mis parientes, son campesinos de la Villa. ¿Están aquí?}
{210}{}{(procesando datos) Campesinos de la Villa... Llegas demasiado tarde, ya los asignamos a la Zona Prohibida. Se encuentran excavando su antigua tecnología.}
{211}{}{Tengo que hacerte unas preguntas.}
{212}{}{Estoy en una misión para la Iglesia del Fuego Santo, para Puerto Peñasco.}
{213}{}{Eres un lunático. Tengo que detenerte antes de que arrastres al yermo entero hacia la esclavitud.}
{214}{}{No tienes idea a quién estás desafiando, idiota. Arrodíllate, o te asimilaremos...}
{1214}{}{No comprendes a quién tienes en frente, estúpida. Arrodíllate, o te asimilaremos...}
{215}{}{¡De ninguna manera!}
{216}{}{¿De qué estás hablando? Me largo de aquí. Intenta detenerme, fenómeno.}
{217}{}{Yo hago las preguntas, tú no. Siéntate y contéstame.}

# Re-Dialogue
{220}{}{Habla.}
{221}{}{Nos vemos luego.}

# Questions
{230}{}{Habla.}
{231}{}{Suficiente. Me largo.}
{232}{}{Tengo una pregunta más.}

{233}{}{¿Qué hace aquí un viejo explorador de la Hermandad?}
{234}{}{Los Dioses del Acero han caído, pues su Olimpo fue víctima de la llamarada nuclear. Pero algunos sobrevivieron. Aunque estén despojados de su antigua gloria, conservan conocimiento que está fuera del alcance de los mortales. Les ofrecemos asilo, bajo nuestros términos.}
{235}{}{Es decir, buscas sacarles todo lo útil que sepan y abusar de ellos como te parezca.}
{236}{}{Somos guerreros del Viejo Mundo, tenemos la tarea de restaurar la gloria que perdió, a través de la tecnología. Los fracasos de los demás no podrán estorbarnos.}
{237}{}{Ya comprendo. ¿Te puedo preguntar otra cosa?}
{238}{}{Bueno, ese tipo tiene un camino muy difícil por delante. Ahora no es más que un mortal entre sus 'superiores'.}

{240}{}{¿Cómo puedo ayudar a mi gente?}
{241}{}{Debes entrar a la Zona Prohibida para salvar a los esclavos, no tienes otra opción. Para escapar, es necesario desactivar los sistemas de seguridad internos. Es una tarea difícil, incluso para los Hojalateros. La probabilidad de supervivencia es baja. Contacta al instructor una vez que estés listo.}
{242}{}{¿Por qué te importa tanto la Zona Prohibida?}
{243}{}{Allí, los antiguos almacenaron sus reliquias militares. Con el tiempo, se convirtió en un depósito de tecnología y sabiduría. El acceso a su núcleo podría resucitar tecnología antigua, ¡y así extenderemos la gloria del Progreso a través del yermo!}
{244}{}{¿Siquiera sabes qué harás con toda esa tecnología cuando la tengas?}
{245}{}{La Hermandad del Acero sabrá guiar su uso para el bien mayor. Nosotros, los guardianes del Progreso, estamos obligados a ayudarlos.}
{246}{}{¿De qué Hermandad estás hablando?}
{247}{}{Estás desinformado, y eso no me extraña. No deberías saberlo, pero te lo haré saber. La Hermandad del Acero es el vestigio de una antigua orden militar. Pretenden resucitar el Viejo Mundo, una noble misión que los Hojalateros buscamos apoyar, cueste lo que cueste. Nos esforzamos por devolver al mundo la luz de los Dos Soles.}
{248}{}{¿Dos Soles? Pero, sólo hay uno.}
{249}{}{Así es, pobre pedazo de carne. Sólo conoces el sol que calienta la tierra. Pero desconoces del brillo de la Energía Nuclear, que ilumina mucho más.}
{250}{}{¿Y en dónde se ubica esa Hermandad del Acero?}
{251}{}{No eres digno de una respuesta.}
{1251}{}{No eres digna de una respuesta.}
{252}{}{Calculo que mereces una respuesta. Ve al oeste, más allá de Casa Nueva. En la costa del Mar de Cortés, encontrarás el Puerto de Acero - la ciudadela de la Hermandad del Acero.}
{253}{}{¿Quién eres?}
{254}{}{Los extranjeros nos llaman 'Hojalateros', debido a nuestra devoción a la tecnología antigua. Nos dedicamos a ella, sacrificando incluso a nuestra propia humanidad. La tecnología salvará al mundo e impedirá que descienda a la barbarie. La humanidad existirá mientras ardan los Dos Soles, o retrocederá más allá de la redención.}
{255}{}{¿Están aliados con los Seguidores del Fuego?}
{256}{}{La iglesia se estableció con el propósito de propagar el Progreso, en términos comprensibles para un plebeyo. Son figuras entretenidas, los respetamos y cooperamos con ellos, ya que su fe acerca a la gente a nuestros ideales. Pero, ellos se encuentran un escaño más abajo que nosotros.}
{257}{}{Entonces, ¿aquí viene a parar el uranio de Flagstaff?}
{258}{}{La electricidad necesita combustible, y de ella requerimos un amplio suministro. Si no fuera por la codicia de las tribus de Fénix y más allá, consumiríamos todo el uranio de Flagstaff.}
{259}{}{La mina de uranio ya cerró, ¿qué harán ahora?}
{260}{}{Como siempre, buscaremos los restos de la preguerra. Dependemos de la Zona Prohibida, ya que es un basto almacén de recursos y secretos.}
{261}{}{¿Crees que es correcto enviar a la gente a morir?}
{262}{}{En el yermo, no hacen más que sobrevivir. Es mejor permitir que estos salvajes hagan eso en la Zona Prohibida, así ayudarán al Progreso y al mundo. Sus vidas no son más que piezas en una gran máquina.}
{263}{}{¿Qué ocurriría si los esclavos desactivan las defensas?}
{264}{}{Cualquiera que rescate un artefacto valioso o deshabilite las defensas, será liberado con honores. Los Hojalateros cumplimos nuestra palabra.}
{265}{}{¿Sabías que la Hermandad ya no existe?}
{266}{}{Sólo eran algunos transmisores del Progreso, otros los reemplazarán. El Puerto de Acero no era el núcleo central de su gran operación. El cuartel general en California sigue intacto, por lo que Arizona, en algún punto, volverá a sentir el peso de la Hermandad.}
{267}{}{La Catedral del Fuego fue destruida, ¿confiarás menos en el culto?}
{268}{}{La fe de la iglesia es irrelevante. Ayudaban a propagar el Progreso, eso es lo que importa. Sacaremos provecho de esto y seguiremos esparciendo nuestros ideales al asumir control de Fénix.}

{270}{}{Perdiste tu humanidad, te has convertido en una máquina desalmada. Te voy a desconectar, eres una abominación.}
{271}{}{Todo lo que sé, es que esa energía acabó con el Viejo Mundo. ¿Acaso quieres que se repita?}
{272}{}{El error de nuestros ancestros yace en su falta de control. Hemos evolucionado y dejado atrás su debilidad. El Viejo Mundo murió para que nosotros pudiéramos renacer. Para restaurar el orden, la tecnología es clave.}
{273}{}{A alguien como tú no le confiaría ni una tuerca. Te mataré antes de que nos destruyas a todos.}
{274}{}{Pensaré sobre lo que dijiste. Nos vemos... creo.}
{275}{}{Intrigante. Me gustaría saber más acerca de tus metas y opiniones.}
{276}{}{Sabes, tienes razón. Unos errores no deberían limitar nuestros avances.}
{277}{}{Me causa felicidad ver qué tu procesador, aunque orgánico, sea capaz de entenderlo.}
{278}{}{Sí, claro. Pero tengo otra pregunta.}

{300}{}{La Zona Prohibida se encuentra bajo su control, Maestro Hard.}
{301}{}{ZAX se encuentra neutralizado. Los artefactos de la Zona volverán a las manos de la Colectiva, los herederos del Viejo Mundo. El alba de una nueva era está sobre nosotros.}
{302}{}{Digamos que tienes razón. Pero, ¿qué hay de mi gente?}
{303}{}{Te exijo que liberes a mi gente de la esclavitud.}
{304}{}{Tú y los demás se ganaron su libertad. Márchate, pero recuerda esto: ustedes no son más que partes de una gran máquina. La Hermandad del Acero llegará pronto. ¿Aceptaras el Progreso, o seguirás revolcándote en las cenizas del yermo?}
{305}{}{Lo consideraré. Pero por ahora, debo irme.}
{306}{}{¿Qué tiene que ver la Hermandad?}
{307}{}{Servimos a los Dioses del Metal. Ellos supervisan nuestro territorio para el Progreso, optimizando nuestros recursos y tecnología para el renacer del yermo. La servidumbre de la Villa era esencial para nuestro plan. Tienes suerte, eres testigo de un gran cambio, porque se está haciendo historia.}
{308}{}{Creo... que tienes un buen punto.}
{309}{}{Guárdate eso para los demás Hojalateros, yo no te creo.}

# Cody
{350}{}{Se dice que secuestraste a Cody de Casa Grande. ¿Es cierto?}
{351}{}{¿Secuestrarlo? Justo lo que espero de una criatura del yermo; ignorancia.}
{352}{}{Entonces, según tú, ¿qué hiciste?}
{353}{}{Exiges una respuesta... (carcajada metálica) Te daré el gusto. No secuestramos a Cody; sus unidades biológicas eran un fallo. Ellos nos lo dieron, pues eran incapaces de sustentarse.}
{354}{}{¿Tan mala era la situación en Casa Grande?}
{355}{}{El asentamiento tenía un fallo crítico en el sistema - la bomba de agua se descompuso. No tenían otra opción y nos contactaron. A cambio, ofrecieron sus activos, aunque fueran mínimos; esto incluía a Cody, quien ahora contribuye a la Colectiva.}
{356}{}{¿Por qué necesitan niños?}
{357}{}{Nuestra sociedad es avanzada, pero se enfrenta a ineficiencias biológicas de reproducción. Integrar y reprogramar a los jóvenes es algo que asegura nuestro futuro. Ahora Cody tiene un propósito más allá de la supervivencia.}
{358}{}{Su pasado no se mantendrá en secreto, sabes eso, ¿no?}
{359}{}{La sentimentalidad es ilógica. Cody fue asimilado por la Colectiva, ahora está desconectado de su vida anterior.}
{360}{}{Sí, claro. Ya escuché suficiente.}
{361}{}{Estás mal. Él merece escoger su propio futuro. Me aseguraré de que tenga esa elección.}

{368}{}{Esto me resulta convincente. Aceptamos el contrato. Infórmale a tu líder que enviaremos un embajador a negociar.}
{369}{}{Adiós, Maestro Hard.}
{370}{}{Estoy aquí en nombre de los Escudos Azules. Tenemos una propuesta.}
{371}{}{Los forajidos... ¿qué pueden ofrecernos a los Hojalateros?}
{372}{}{Combustible, y mucho. A cambio, quieren el reconocimiento de su independencia y un estatus comercial oficial.}
{373}{}{El combustible podría atenuar el déficit de uranio. Sin embargo, los Escudos Azules son inestables. No podemos arriesgarnos a una alianza así.}
{374}{}{Ben no estará contento, pero es decisión tuya. Le haré saber que rechazaste.}
{375}{}{¿Cómo puedo hacerte cambiar de parecer?}
{376}{}{Demuestra que eres fiable, y lo consideraré.}
{377}{}{Entonces, ya se me ocurrirá algo.}
{378}{}{Tengo una buena reputación con los demás Hojalateros.}
{379}{}{He contribuido al desarrollo de la Zona Prohibida, eso demuestra que somos fiables.}

# Quests
{390}{}{¿Tienes algún trabajo para mí? Puedes contar conmigo.}
{391}{}{Nos... interesa tu proposición.}
{392}{}{¿Qué tienes en mente?}
{393}{}{Atacaron a una de nuestras caravanas. No pudimos identificar a los asaltantes, tu trabajo es investigar esto. Consulta al guardia de la entrada a la ciudad para saber la ruta de la caravana.}
{394}{}{Así que sólo debo caminar un poco, suena fácil.}
{395}{}{Esperaba más, pero me basta.}
{1395}{}{Esperaba más, pero me basta.}
{396}{}{hazme saber qué encuentras antes de actuar. Puedes irte.}
{397}{}{Me pondré con ello.}

{400}{}{He descubierto a quiénes atacaron la caravana - son esclavos convictos, están escondidos en las ruinas de la ciudad.}
{1400}{}{He descubierto a quiénes atacaron la caravana - son esclavos convictos, están escondidos en las ruinas de la ciudad.}
{401}{}{Bien hecho. Has confirmado nuestros cálculos. Estos esclavos nos causaron problemas en el pasado, pero ahora están intensificando su oposición ante los Dos Soles.}
{402}{}{¿Cuál es tu plan?}
{403}{}{Los esclavos tienden emboscadas tanto a caravanas como viajeros. Elimínalos en Two-Sun, y recupera la tecnología que nos robaron.}
{404}{}{¿Por qué no envías a los Hojalateros?}
{405}{}{Los esclavos adaptaron tácticas de guerrilla mientras estaban en la Zona Prohibida. Saben cómo esconderse en las ruinas, y sus trampas son letales. Nos especializamos en la tecnología, pero no en la guerra.}
{406}{}{Pero son un grupo entero, ¿cómo me enfrentaré a ellos?}
{407}{}{Aplica estrategia en donde la tecnología sea insuficiente.}
{408}{}{¿Y qué me darás a cambio?}
{409}{}{Te ofrecemos más que lo material. Únetenos, y serás parte del Progreso en el Nuevo Mundo. Si no, puedes quedarte en la mugre del yermo.}
{410}{}{¿Tendrás gafas de visión nocturna? Me ayudarán entre las ruinas.}
{411}{}{(Te ofrece las gafas) Utilízalas de forma estratégica.}
{412}{}{Esta tecnología no es para forasteros.}
{413}{}{No te daré más. Usa lo que tienes.}
{414}{}{Me ocuparé de ello.}
{415}{}{No me interesa, tengo mejores cosas que hacer.}
{416}{}{Tenemos que hablar sobre los esclavos.}

{420}{}{Los esclavos ya no te serán un problema.}
{421}{}{Excelente. Tienes una voluntad de acero, cosa que apreciamos. Dame un informe completo.}
{422}{}{Esto fue lo que pasó...}
{423}{}{...Estos resultados nos satisfacen. El intendente te entregará tu recompensa. Espera, tengo una última misión para ti.}
{424}{}{¿De qué se trata?}
{425}{}{Completar esta misión ha mejorado tu reputación con los Hojalateros.}
{426}{}{Uno de nuestros delegados fue a Casa Grande, pero no ha regresado. No se ha comunicado con nosotros. Encuentra a nuestro hermano y descubre lo que pasó.}
{427}{}{Mis botas no aguantarán más. Ojalá que valga la pena.}
{428}{}{Ya voy.}
{429}{}{...Tu informe es satisfactorio. El intendente te entregará tu recompensa. Espera, tengo una última misión para ti.}

{430}{}{Encontré a un Hojalatero en Casa Grande, está muerto. Como prueba, tengo su neurochip.}
{431}{}{¿Cuál fue su causa de muerte?}
{432}{}{Lo mató un espía de los rangers.}
{433}{}{Un ranger... No estaba en nuestras expectativas que fueran tanto problema.}
{434}{}{¿A qué te refieres con "tanto problema"?}
{435}{}{Después de tu misión anterior, encontramos evidencia en el escondite de los esclavos la cual indica que los rangers los abastecieron y entrenaron. Buscan socavar nuestra economía y reputación con los demás asentamientos, dado que difundieron rumores falsos sobre nosotros. Los rangers son un gran peligro, eso es obvio.}
{436}{}{Y, ¿ahora qué?}
{437}{}{Debemos prepararnos para la batalla. La Hermandad ya no es relevante, por lo que debemos defendernos nosotros mismos. Puedes ir a casa, ahora reconocemos la Villa como un asentamiento neutral.}
{438}{}{Genial, me esperaban con ansias. Adiós, amigo.}
{439}{}{Ve al Puerto de Acero e informa a la Hermandad de nuestro conflicto con los Rangers. Si necesitan ayuda, puedes contar con nuestra recomendación. Si nuestro mundo tiene un futuro, yace con la Hermandad del Acero. La Gran Actualización se acerca.}
{440}{}{La Hermandad del Acero... suena bien.}
{441}{}{Gracias por confiar en mí, Maestro Hard. No defraudaré al Progreso.}
{442}{}{Lo entiendo, pero, ¿cómo encontraré a un Hojalatero en otra ciudad?}
{443}{}{Usa la radio. Sintoniza su frecuencia con el chip subcutáneo del delegado, eso hará la búsqueda más rápida.}
