{100}{}{Ves a Carlos.}
{101}{}{Estás viendo a un aldeano de la Villa. Parece que algo ha cambiado en él.}
{102}{}{Dicen que la ciencia de verdad está volviendo a Casa Nueva, igual que antes de la Gran Guerra.}
{103}{}{Algún día volveré a casa... para ayudar a que sea más civilizada.}
{104}{}{Emprender un viaje es mi única opción. Ojalá que vea muchas cosas nuevas.}
{105}{}{Cómo... cómo pudiste...}
{106}{}{Tú... todo esto es culpa tuya...}

#First dialogue
{200}{}{... ¿Estás...? ¿Por qué estás aquí?}
{201}{}{Es obvio que vine a salvarte, Carlos. Vámonos de aquí...}
{202}{}{Salvarme... ¿Salvarme de qué? ¿Quieres que vuelva a la Villa? ¿Para que vuelva a matar ratas que se comen nuestros cultivos? ¿Para estar rodeado de enfermedades que un campesino jamás podría curar? ¿Para enfrentarnos con palos y piedras a personas con rifles? No me estás salvando de nada. A mi parecer, la Villa está llena de campesinos de mente estrecha y limitada.}
{203}{}{¿De qué estás hablando?}
{204}{}{Somos salvajes, amigo, entiéndelo. Apenas conocimos la electricidad después de ser esclavizados. Es como haber vivido dentro de una lata hasta que alguien la abrió y nos mostró el mundo que había afuera. A diferencia de lo que pensábamos, la Villa no era el centro de ese mundo, simplemente una pequeña parte de él.}
{1204}{}{Somos salvajes, amiga, entiéndelo. Apenas conocimos la electricidad después de ser esclavizados. Es como haber vivido dentro de una lata hasta que alguien la abrió y nos mostró el mundo que había afuera. A diferencia de lo que pensábamos, la Villa no era el centro de ese mundo, simplemente una pequeña parte de él}
{205}{}{Espera un momento...}
{206}{}{La tecnología es mi pasión y está prohibida en casa, este es el único sitio en donde he podido desarrollar mi potencial. Mantuve mis intereses en secreto para no causarme problemas a mí o a los demás. Ahora soy libre y puedo hacer lo que mi corazón quiera. Lárgate, amigo. Déjame aquí.}
{1206}{}{La tecnología es mi pasión y está prohibida en casa, este es el único sitio en donde he podido desarrollar mi potencial. Mantuve mis intereses en secreto para no causarme problemas a mí o a los demás. Ahora soy libre y puedo hacer lo que mi corazón quiera. Lárgate, amiga. Déjame aquí.}
{207}{}{Me iré, por el momento. Pero no creas que esta es la última vez que nos veremos.}
{208}{}{No haré que cambies de parecer. Adiós, amigo.}

{210}{}{El tiempo de la Villa se acabó, entiéndelo.}
{211}{}{Ya, ya, suficiente.}

{230}{}{¿Puedes explicarme qué está pasando aquí?}
{231}{}{Los Hojalateros están intentando acceder a la tecnología antigua de la Zona Prohibida. Necesitan los recursos y la tecnología de la Zona para expandirse y promover la idea del Progreso. Pero el área está bien protegida. Se han enviado grupos de esclavos y mercenarios a su interior de forma periódica para que traigan tecnología de vuelta, pero no suelen volver.}
{232}{}{Dime qué sabes de los Hojalateros.}
{233}{}{Son un clan semi-religioso con una larga historia. Ellos veneran la tecnología antigua, buscan resucitarla y utilizarla para el servicio de la humanidad.}
{234}{}{Háblame de la Zona Prohibida.}
{235}{}{Es un viejo almacén de equipo militar. El área está bien fortificada y resguardada por robots. Los Hojalateros han descubierto cómo deshabilitar el campo de fuerza de la puerta principal, pero sólo por unos segundos. Si estás pensando en entrar, necesitarás armas y algunas drogas anti-radiación.}
{236}{}{Además de ti, ¿hay alguien más de la Villa?}
{237}{}{Tu papá y Gerardo. Ya han sido enviados a la Zona Prohibida. Si quieres salvarlos, tendrás que entrar ahí.}
{238}{}{Voy a adentrarme en la Zona Prohibida. De verdad necesito tu ayuda, Carlos.}
{239}{}{No... no puedo ayudarte... Los Hojalateros me están vigilando de cerca y mantienen un registro exacto de todo lo que haya en sus almacenes.}
{240}{}{Gracias por la información. Tengo que ponerme con ello.}
{241}{}{¡Los Hojalateros deben estar interesados en que tenga éxito!}
{242}{}{(mira a su alrededor) Puedo darte una cosa, unas granadas de pulso. Dicen que una de estas puede derribar a un robot de inmediato. Úsalas como último recurso.}
{243}{}{Gracias, Carlos. Esto me será de mucha ayuda.}
{244}{}{Tengo más preguntas.}
{245}{}{Perdóname, pero es demasiado arriesgado.}

#Fusion Cell
{250}{}{Necesito una célula de fusión nuclear para un generador. ¿Puedes conseguirme una?}
{251}{}{¡No me pidas nada! A los Hojalateros no les gustará que entregue tecnología sin su permiso.}
{252}{}{Esto es muy importante. ¡Necesito tu ayuda!}
{253}{}{¡No, no y no! No voy a arriesgar mi posición por un campesino.}
{254}{}{Eso me hiere. Adiós.}
{255}{}{Quizás haya alguna forma de hacerlo sin levantar sospechas...}
{256}{}{Ese es el espíritu.}
{257}{}{(mira a su alrededor) Si te lo preguntan, no te lo pasé yo.}
{258}{}{Gracias, amigo.}
{259}{}{Ya lo veremos...}

#Care
{300}{}{¿Volverás a la Villa?}
{301}{}{Ni te molestes en preguntar. Sólo me iré de aquí cuando los Hojalateros me echen.}
{302}{}{Entonces no preguntaré de nuevo. Cuídate.}
{303}{}{Eres un idiota, y te quedarás como un idiota.}
{304}{}{Es demasiado tarde. Derrotaron a los Hojalateros y el área está bajo el control de las máquinas. Si te quedas, morirás.}
{305}{}{Desde que murió el Maestro Hard, los Hojalateros se han vuelto todavía más intolerantes de los forasteros. ¿No te diste cuenta?}
{306}{}{¿Acaso no has oído los rumores sobre tus 'robos'?}
{307}{}{¿Así que es culpa tuya? Pedazo de... Parece que vas en serio.}
{308}{}{No puedes esconderte. Mi padre está decidido en traerte con nosotros, vivo o muerto.}
{309}{}{Lo siento, pero era la única forma de hacer que me escucharas.}
{310}{}{No perteneces a este mundo. Mi padre piensa lo mismo.}
{311}{}{No perteneces a este mundo. En este lugar eres un trabajador más, no eres parte de una comunidad.}
{312}{}{Quizás por el momento sea así, pero estoy creciendo y desarrollándome. Algún día me uniré a los Hojalateros como un igual.}
{313}{}{Ya lo veremos...}
{314}{}{Tienes razón, los Hojalateros desconfían de los forasteros. Hace falta fanatismo ante la tecnología para ganarte su confianza y será muy difícil unirse a ellos como igual.}
{315}{}{Entonces regresa a la Villa y comparte lo que sabes allí - ese es tu destino.}
{316}{}{Por fin, un poco de sensatez entre tanta tontería.}
{317}{}{}
{318}{}{Demonios... Ya me había decidido, no sabes lo difícil que fue. Pero no parece que tenga otra opción.}
{319}{}{¿Qué has decidido?}

{320}{}{No puedo volver a la Villa después de lo que pasó. Mi conocimiento y habilidades se desperdiciarían y tampoco me aceptarán en casa. Ya sabes lo testaruda que es nuestra gente.}
{321}{}{Quizás hayan otros lugares en donde necesiten tus talentos.}
{322}{}{Hmm. ¿Fénix? No, ahí sólo importan las chapas. Mi única opción es Casa Nueva, los caravaneros hablaron de un asentamiento pequeño llamado así. Dijeron que hay todo un laboratorio allí y las mentes más brillantes de Arizona están reunidas ahí.}
{323}{}{¿Qué te impide ir hacia allá?}
{324}{}{Es una comunidad cerrada, puede que no me acepten. Mientras intento arreglármelas aquí, ¿podrías ir con los científicos de ese sitio y preguntarles si puedo unirme?}
{325}{}{Por supuesto, amigo. Lo haré por los viejos tiempos.}
{326}{}{Gracias, }
{327}{}{. Estaré esperándote.}
{328}{}{Nos vemos.}
{329}{}{No, tengo que ir a casa. Es problema tuyo.}
{330}{}{Que pena. Pero, si pasas por ahí, háblale a los científicos de mí, ¿bien?}
{331}{}{No te prometo nada.}
{332}{}{Sí, lo tendré en cuenta.}

{340}{}{Ya hablamos de esto. No puedo ir a casa.}
{341}{}{Es cosa tuya. Adiós.}
{342}{}{Los idiotas nunca aprenden. Adiós.}
{343}{}{Tengo buenas noticias. Los Seguidores del Apocalipsis te aceptarán, les conté de tu conocimiento y tus habilidades.}
{344}{}{Eso es muy alentador. No te preocupes por mí, llegaré sólo. Gracias por todo.}
{345}{}{Lo más importante es que no trabajes para estos malditos Hojalateros. Sal de aquí.}
{346}{}{Puede que algún día también me vaya de la Villa, igual que tú. Adiós.}
{347}{}{Lo lamento, pero los Seguidores del Apocalipsis tienen sus propios problemas ahora mismo. No podrás unirte a ellos.}
{348}{}{¿Tan mal están las cosas? Los caravaneros ya estaban contando rumores. Parece que no tengo otra opción, tendré que embarcarme en un viaje. No sé hacia dónde. Quizás vaya al oeste y llegue a California, o al este hacia Nuevo México. Pero no me voy a quedar aquí.}
{349}{}{Bueno, no es mala idea.}
{350}{}{Adiós, }
{351}{}{. Gracias por todo.}
