{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia de caravana. Está descansando luego de un largo viaje.}

{110}{}{Genial.}
{111}{}{Dame un respiro.}
{112}{}{¿Quieres unirte a nosotros?}
{113}{}{El camino entre Fénix y Two-Sun está en caos.}
{114}{}{Las tormentas de polvo son peores que los saqueadores.}
{115}{}{Nuestro trabajo es muy arriesgado.}
{116}{}{Habla con el jefe, yo solo transporto la carga.}
{117}{}{Manténte alejado de los Hojalateros, es lo mejor.}
{118}{}{Te daré un consejo: no vayas con el doctor de los Hojalateros.}
{119}{}{Debería regresar a Fénix.}
{120}{}{A los Hojalateros no le gustan ni los forasteros ni la charla.}
{121}{}{Los Hojalateros me dan miedo - son como máquinas.}
