{100}{}{Ves a un Hojalatero.}
{101}{}{Ves a un ciudadano de Two-Sun.}

# Floating lines
{110}{}{Los Dioses del Acero están furiosos con nuestra ineficiencia.}
{111}{}{¿Por qué están callados los Dioses del Acero? ¿Se olvidaron de nosotros?}
{112}{}{Los Dioses están contentos.}

{113}{}{Puede que a Casa Nueva se le esté acabando la comida.}
{114}{}{Prometieron enviarle más comida a Casa Nueva.}
{115}{}{He escuchado rumores turbios de Casa Nueva, parece que ya no es seguro.}

{116}{}{Una caravana de Fénix fue asaltada por los forajidos.}
{117}{}{Dicen que por fin acabaron con los Escudos Azules.}
{118}{}{Los Escudos Azules son más fuertes que nunca, debemos tener cuidado con ellos.}

{119}{}{Siempre pensé que los Seguidores del Fuego eran ilógicos.}
{120}{}{A los Seguidores del Fuego les dieron lo que querían.}
{121}{}{Esos primitivos seguidores intentan negociar con nosotros.}

{122}{}{Las reservas de uranio en Flagstaff no son suficientes.}
{123}{}{Tendremos que racionar la electricidad hasta que las minas en Flagstaff vuelvan a funcionar.}
{124}{}{Se han retirado los protocolos de conservación eléctrica; Las reservas de uranio de Flagstaff ya son suficientes.}

{125}{}{La entrada a la Zona Prohibida cambiaría nuestras vidas por completo.}
{126}{}{Debemos irnos antes de que ZAX desate su furia sobre nosotros.}
{127}{}{Entrar a la Zona Prohibida lo cambiará todo.}

{128}{}{Luego de la operación, los circuitos empáticos del Maestro Hard se descompusieron.}
{129}{}{Si vuelvo con el Doctor Jones, podría tener una falla crítica en mis sistemas.}
{130}{}{Mantén tus funciones dentro del marco de la Colectiva.}

{131}{}{No olvides rezarle al Dios de la Tecnología antes de comer.}
{132}{}{Agradécele a los Dioses del Acero por nuestra existencia.}
{133}{}{Mis articulaciones necesitan aceite.}
