{100}{}{Ves a un paciente.}
{101}{}{Ves a un Hojalatero enfermo. Está sufriendo de algunas complicaciones post-operación.}
{102}{}{¿Cómo pudo curarme tu primitiva medicina? ¡Esto es ilógico!}
{104}{}{¿Por qué... aún no he sido... digitalizado?}
{105}{}{Mi... biomatriz... tiene fallas...}

{110}{}{Desactívenme y rescaten mis partes.}
{111}{}{¿Me van a desactivar, doctor?}
{112}{}{No viviré lo suficiente para que digitalicen mi biomatriz, es lo único de lo que me arrepiento.}
{113}{}{Es hora de sacrificarme en nombre del Progreso.}
{114}{}{Hay un error en mi biomatriz.}

{115}{}{Gracias por arreglarme, doctor.}
{116}{}{Al estar tan cerca de ser desactivado, me pensé muchas cosas.}
{117}{}{Necesito recalcular mis algoritmos.}
{118}{}{No vale la pena sacrificarme por el Progreso.}
{119}{}{Mi biomatriz se encuentra estable.}
