{100}{}{Ves a un Hojalatero.}
{101}{}{Ves a uno de los Hojalateros.}

{200}{}{(Luego de un largo viaje en una carretera desolada, llegas al asentamiento de los Hojalateros. Te ponen en fila con los demás esclavos, todos están quemados por el sol.)}
{201}{}{[Más]}
{202}{}{(Un Hojalatero te examina con una tableta en la mano) Tú. ¿También eres de la Villa? Llévenlo con el Instructor, que se vaya con los suyos... Bien, siguiente...}
{203}{}{[Más]}

{210}{}{Estoy ocupado.}
{211}{}{Lo que digas.}
