{100}{}{Ves al capataz de los esclavos.}
{101}{}{Ves a uno de los Hojalatero a cargo de entrenar a los esclavos.}

{200}{}{(dirigiéndose al grupo) ¡Atención! ¡Se les ha asignado esta instalación para proporcionar valor operativo a su existencia, que de otro modo sería inútil!}
{201}{}{[Más]}
{202}{}{Tienen la tarea de recuperar tecnología antigua de la Zona Prohibida. Esta localización contiene valiosa maquinaria de la preguerra. Pero se nos impide el acceso, debido a un avanzado protocolo de seguridad. Su objetivo es entrar en el centro de mando y desactivar las defensas. Si completan esta misión con éxito, se les otorgará la libertad.}
{203}{}{[Más]}
{204}{}{¿Preguntas?}
{205}{}{Sí.}
{206}{}{No.}
{207}{}{¡Entonces muévanse y pónganse en fila! ¡Cualquiera que intente escapar de la Zona Prohibida antes de completar su misión será 'desmantelado', permanentemente!}
{208}{}{Esto no será nada fácil...}
{209}{}{No tengo más preguntas.}

{210}{}{¿Quién te crees que eres? ¡Habla!}
{211}{}{¿Me regresarán mis cosas cuando termine con la misión?}
{212}{}{Podrás recuperar tus pertenencias al registrar la caja del intendente. Eso es si completas la misión, pero no esperes conseguirlo.}
{213}{}{¿Sabes si mi padre está en la Zona Prohibida? Se llama Andrés.}
{214}{}{Ese nombre no se encuentra en mi base de datos. Con tantos salvajes que desaparecen en la Zona, recordar cada caso es inútil.}
{215}{}{¿Qué nos espera en la Zona Prohibida?}
{216}{}{Robots, trampas electromagnéticas y altos niveles radioactivos. El perímetro se encuentra rodeado por un campo de fuerza. Es imposible escapar sin terminar con la misión.}
{217}{}{¿Nos darán armas?}
{218}{}{Tendrás que usar lo que encuentres en la Zona.}
{219}{}{Al menos dame unas nudilleras.}
{220}{}{Al menos dame una pistola básica.}
{221}{}{Al menos dame un estimulante.}
{222}{}{Al menos dame granadas anti-robot.}
{223}{}{¡Cállate de una vez, pedazo de chatarra! No te daremos absolutamente nada.}
{224}{}{¡Toma y cállate de una vez, pedazo de chatarra!}
{225}{}{Tengo otra pregunta.}

{230}{}{¿Tienes algo que reportar? Habla con nuestro líder.}
{231}{}{Claro.}
{232}{}{¿Vienes de voluntario a la Zona Prohibida?}
{233}{}{Sí, estoy listo para entrar.}
{234}{}{No, sólo estaba viendo.}
{235}{}{Exponga sus dudas.}
{236}{}{Habla con nuestro líder, yo sólo trato con los esclavos.}
{237}{}{De acuerdo.}
{238}{}{¡El gran ZAX ha sido derrotado! Ahora empieza el trabajo de verdad. Es hora de buscar más esclavos.}
{239}{}{Ojalá que puedan hacerlo sin mí... Adiós.}
