{100}{}{Ves a tu padre.}
{101}{}{Estás viendo a Andrés, tu padre.}
{102}{}{Tu padre ha muerto.}
{103}{}{Has recibido }
{104}{}{ puntos de experiencia por liberar a tus paisanos.}
{105}{}{¡Esto es por mi infancia! ¡Fue difícil, papá!}
{106}{}{Adiós, padre. Ya no necesito tus lecciones.}

#First dialogue
{200}{}{... ¿¡Eres tú!?}
{201}{}{Hola, papá.}
{202}{}{¿Cómo nos encontraste?}
{203}{}{Pues, he caminado mucho por el desierto, y...}
{204}{}{¿¡Qué acaso no entiendes la situación en la que estamos!? ¡No deberías estar aquí, tienes que estar en nuestro hogar!}
{205}{}{La Villa se está recuperando poco a poco. He conseguido salvar a los aldeanos que estaban en Flagstaff.}
{206}{}{Ahora lo entiendo. Me equivoqué porque no pude dejar de pensar en ti como un niño. Todo esto ha sido terrible, pero te ha otorgado mucha experiencia. Me alegro de que estés aquí.}
{1206}{}{Ahora lo entiendo. Me equivoqué, porque no pude dejar de pensar en ti como una niña. Todo esto ha sido terrible, pero te ha otorgado mucha experiencia. Me alegro de que estés aquí.}
{207}{}{Pensaba que sería mejor salvar al líder de la Villa primero y luego a los demás.}
{208}{}{¡Eso no tiene sentido! La Villa puede vivir sin mí. ¿¡Por qué un asentamiento abandonado necesitaría un líder!? Deberías haber ido a Flagstaff, allí está nuestra gente, incluyendo a tu madre.}
{209}{}{Lo pensaré luego, porque ahora debemos encontrar una salida de aquí. ¿Tienes alguna idea?}
{210}{}{Ya hubiéramos salido de aquí si no fuera por el maldito campo de fuerza, no hay forma de atravesarlo. Nuestra única opción es entrar al centro de control del búnker y desactivar lo que sea que haya en su interior.}
{211}{}{Hagámoslo.}
{212}{}{Es fácil decirlo. Pero el área está repleta de robots y trampas. Nadie sabe qué hay dentro del búnker. Primero, tienes que explorar un poco, equiparte y conseguir la ayuda que puedas. Hemos intentado fabricar armas para luchar contra los robots, pero nuestro técnico murió mientras buscaba partes y yo no sé de tecnología.}
{213}{}{No será ningún problema, padre. Voy a explorar un poco y encontraré una salida.}
{214}{}{Apreciaría un 'gracias'. Al fin y al cabo, te estoy salvando.}
{215}{}{Voy a resolver esto sin tu ayuda. Quédate ahí y espera mis instrucciones.}
{216}{}{¡Paaapá! ¡Llevo tanto tiempo buscándote!}
{1216}{}{¡Paaapá! ¡Llevo tanto tiempo buscándote!}

#Re-dialogue
{220}{}{Habla, }
{221}{}{.}
{222}{}{Ya vuelvo.}

{230}{}{Repasemos el plan.}
{231}{}{Nuestro plan es este. Tendrás que abrirte paso por los robots, bajar al búnker, encontrar los controles del campo de fuerza, apagarlo y así escapar de este maldito y regresar a la Villa.}
{232}{}{De acuerdo.}

{233}{}{¿En dónde puedo conseguir armas?}
{234}{}{Por aquí han muertos muchos esclavos y mercenarios, busca sus cadáveres; puede que todavía tengan armas. Vi que había algo parecido a un arma cerca de un avión grande, pero, se veía demasiado pesada como para usarse.}
{235}{}{¿Hay más esclavos ahí afuera?}
{236}{}{Hay un campamento cerca del búnker, pero el tipo de ahí se negó a cooperar con nosotros. Parece que está un poco... loco, y se ve bastante enfermo.}
{237}{}{¿Cómo puedo lidiar con los robots?}
{238}{}{Esas cosas son más listas que una rata topo. Se esconden en los rincones oscuros o entre las arenas, no podrás verlos de inmediato, pero puedes escucharlos desde lejos. Si te mueves lento o te quedas detrás de ellos, puede que no te vean. Nuestro técnico estaba ensamblando un arma en su mesa de trabajo, quizás ayude contra los robots, pero tendrás que ensamblarla tú.}
{239}{}{}

{240}{}{¿Qué es este lugar?}
{241}{}{Hasta donde sé, es un cementerio de tecnología ya olvidada. Los Hojalateros quieren resucitarlas, no quiero que eso ocurra. ¡Ellos no entienden los peligros de la tecnología antigua!}
{242}{}{¿Cómo sabes que esta tecnología es peligrosa.}
{243}{}{Nuestros ancestros nos enseñaron que debemos temerle a la tecnología antigua. Decían que eran peligrosas y poco confiables. Y tienen razón. ¿Te has topado con cosas que explotan en tus manos o que dañan tu salud con radiación? Han habido comunidades enteras que murieron por depender de la tecnología. En las manos equivocadas, estas cosas se volverán armas.}
{244}{}{Me he cruzado con algunas cosas de ese tipo...}
{245}{}{Debes recordar lo visto en Flagstaff, debes recordar el grupo de saqueadores que esclavizaron a nuestro hogar con nada más que sus armas y collares de choque. ¡Hay que destruir todo este equipamiento! ¡Todo!}
{246}{}{Voy a pensar en qué puedo hacer...}
{247}{}{¿Qué hay de tu puño neumático? Me vendría bien.}
{248}{}{¿Dejarás indefenso a tu viejo? (risa amarga) Está bien, eres nuestra última esperanza.}
{249}{}{Gracias por darme tu arma, padre.}

{250}{}{Cuéntame sobre el asalto a la Villa.}
{251}{}{Hablemos de eso al llegar a casa. Pero la versión corta es que los saqueadores nos atacaron cuando terminaba nuestro día de trabajo, aprovecharon que los campesinos estaban cansados porque regresaban de las plantaciones. Conseguí defender el interior del ayuntamiento, pero nos atraparon a todos, nos ataron y nos llevaron a Flagstaff. Dejaron a la mayoría para que trabajen en su mina, pero trajeron a los mejores hasta aquí.}
{252}{}{¿Has estado en Fénix?}
{253}{}{Sí, nos llevaron a una iglesia liderada por algún tipo de culto. Son gente asquerosa y despiadada, carecen de cualquier compasión. Nos estudiaron a fondo, como si fuéramos conejillos de indias - nos sacaron sangre para analizarla, nos torturaron y nos preguntaron sobre la Villa. Para nuestra desgracia, esa iglesia ahora sabe de nuestro hogar.}
{254}{}{Tengo más preguntas.}
{255}{}{¿Por qué te trajeron a Two-Sun?}
{256}{}{Dado que soy el líder de la Villa, yo sé mucho. Así que entre toda nuestra gente, me consideraron el más adecuado para este trabajo.}

# Joining the party
{260}{}{Acompáñame, necesito tu experiencia.}
{261}{}{Te ayudaré a llegar al búnker, pero tendrás que bajar sin mí.}
{262}{}{Me parece bien.}
{263}{}{¿Por qué?}
{264}{}{Porque así te será más fácil que no te detecten. Además, con toda esa tecnología vieja, no seré de mucha ayuda. Has adquirido más conocimientos y experiencia vagando por Sonora que yo en mi vida entera, hijo.}
{1264}{}{Porque así te será más fácil que no te detecten. Además, con toda esa tecnología vieja, no seré de mucha ayuda. Has adquirido más conocimientos y experiencia vagando por Sonora que yo en mi vida entera, hija.}
{265}{}{Hmm. Bueno, veré que puedo hacer.}
{266}{}{Voy a entrar solo.}
{1266}{}{Voy a entrar sola.}
{267}{}{Yo protegeré la entrada. Buena suerte.}
{268}{}{[Ve]}

# Completing the rescue quest
{300}{}{Podemos irnos, el maestro Hard les ha regresado su libertad.}
{301}{}{Eso hará que salir de Two-Sun sea fácil. Pero, ¿cómo saldremos de *aquí*?}
{302}{}{Hmm, déjame pensarlo.}
{303}{}{El campo de fuerza fue desactivado, podemos irnos de Two-Sun.}
{304}{}{Buen trabajo, }
{305}{}{. Le sacaron partido a nuestra libertad. Ahora, los Hojalateros tendrán acceso a la tecnología antigua que hay aquí y Dios sabe qué problemas van a causar. Al menos tendremos tiempo para prepararnos.}
{306}{}{[Más]}
{307}{}{Has hecho un gran trabajo, }
{308}{}{. No sólo nos liberaste, sino que también le negaste toda esta tecnología a los Hojalateros. Sólo Dios sabe qué clase de caos sembrarían por el yermo si tuvieran acceso al búnker.}
{309}{}{Voy a descansar un momento e iré a casa. Entiendo que debes tener más cosas que hacer. Vuelve a la Villa cuando puedas.}
{310}{}{Adiós, papá.}
{311}{}{Mientras tanto, encuentra a Carlos e intenta hacerlo entrar en razón. Los Hojalateros le lavaron el cerebro y se lo llenaron de tonterías. Si no puedes convencerlo de que salga de aquí... debes acabar con él, ¿entendido? Sé que pido mucho, pero ahora mismo, él representa un peligro para la Villa.}
{312}{}{Lo entiendo, papá. Confía en mí.}
{313}{}{¿Quieres que mate a uno de los nuestros? No puedo hacer eso, pero intentaré convencerlo.}
