{100}{}{Ves a un necrófago.}
{101}{}{Ves a un hombre sucio y delgado. Sus ojos revelan una mente oscura de malas intenciones.}

# First dialogue
{200}{}{¡Alto! Un paso más y estás muerto.}
{201}{}{No quiero tener problemas. ¿Qué tal si hablamos?}
{202}{}{Claro que no, será al revés.}

{203}{}{No caeré en tus trucos. ¡Déjame sólo o te volaré los sesos!}
{204}{}{Escúchame, no podemos hacerlo solos. Tengo un plan para escapar de aquí. Hagamos equipo, ¿bien?}
{205}{}{No es ningún truco. Te mataré, esa arma es mía.}
{206}{}{Me voy, me voy. No quiero pelear.}
{207}{}{¿Cómo sé que no me traicionarás?}
{208}{}{Es difícil ganarte tu confianza, ¿cierto? Nos necesitamos el uno al otro para salir de aquí con vida.}

{209}{}{¡Maldita sea! ¡Quiero salir de aquí! De acuerdo, podemos ir juntos. Pero no creas que me sacrificaré por ti o algo así.}
{210}{}{Bueno, es un principio.}
{211}{}{Mírame de cerca. Somos dos necrófagos. ¿No confías en uno de los tuyos?}
{212}{}{Es obvio que nos necesitamos el uno al otro.}
{213}{}{Buena suerte, normalucho. Pero estaré bien sólo.}

# Dialogue after communion
{220}{}{¿Qué quieres?}
{221}{}{Nada.}

{230}{}{Háblame de ti.}
{231}{}{No me sacarás nada.}
{232}{}{Eh, bueno.}
{233}{}{Al menos dime tu nombre.}
{234}{}{Me llamo Raúl.}
{235}{}{¿De dónde eres, Raúl?}
{236}{}{He viajado mucho, sobre todo por California y el norte de México. ¿Has oído de Tijuana? Nací allá.}
{237}{}{¿Una ciudad mexicana? Debes haber visto muchas cosas.}
{238}{}{Ha sido un siglo de viajar de lado a lado. Y ahora estoy aquí metido, a punto de morir en este vertedero. Pensé que mi muerte sería distinta.}
{239}{}{¿Cien años? ¿Cómo puedes vivir tanto?}
{240}{}{Fíjate bien, las bombas me hicieron esto. No son quemaduras, son... algo más. Me mantienen vivo. No sé si tratarlo como maldición o bendición.}
{241}{}{¡Así que eres del Viejo Mundo!}
{242}{}{Sí, era algo totalmente distinto. No me creerías los avances tecnológicos que teníamos. Pero, ¿sabes qué? La gente no ha cambiado. Siguen peleándose por pendejadas, igual que antes.}
{243}{}{Debes ver las cosas de una manera distinta.}
{244}{}{Eres un... necrófago. ¿Por qué te enviaron los Hojalateros aquí adentro?}
{245}{}{Porque después de tantos años, sé más que cualquier normalucho. Agrégale a eso mi inmunidad a la radiación, y soy perfecto para meterme en una base vieja. Pero te seré sincero, no tengo la menor idea de cómo desactivar las defensas.}
{246}{}{Comprendo.}
{247}{}{Esta conversación no va a ningún lado. Suficiente.}
{248}{}{¿Qué sabes de los necrófagos del Infierno?}
{249}{}{No pude encajar con ellos. Estoy lo suficientemente sano como para no volverme loco. Pero, esos tipos... Ya no se puede hacer nada por ellos. Son demonios.}

# The consignment
{250}{}{Ven conmigo.}
{251}{}{De acuerdo, pero no te metas en problemas. Y recuerda esto; no me voy a meter al búnker.}
{252}{}{Eso lo veremos...}
{253}{}{Espérame, iré a ver qué hay más adelante.}
{254}{}{No te atrevas a traicionarme.}
{255}{}{Nunca haría eso...}

{260}{}{Háblame sobre este lugar.}
{261}{}{Es un viejo almacén militar, los campos de fuerza y campos minados resguardan el perímetro. También hay robots por todos lados, los controla una computadora en el búnker subterráneo.}
{262}{}{¿Qué crees que haya dentro del búnker?}
{263}{}{Seguramente un chingo de robots asesinos y alguna computadora gigante. Dudo que haya alguien vivo ahí dentro. Si vas a bajar, prepárate para lo peor.}
