{100}{}{Ves a Gerardo.}
{101}{}{Ves a uno de los campesinos de la Villa.}

# First dialogue
{200}{}{... ¿¡Eres tú!? Pensé que habías escapado de nuestros asaltantes...}
{201}{}{No, Gerardo, no me atraparon. Voy a sacarlos de aquí.}
{202}{}{Amigo mío, tus palabras me consuelan, pero créeme - no hay escapatoria. ¡Incluso el piso huele a muerte! Todos vamos a morir, y no habrá nadie que llore por nosotros.}
{1202}{}{Amiga mía, tus palabras me consuelan, pero créeme - no hay escapatoria. ¡Incluso el piso huele a muerte! Todos vamos a morir, y no habrá nadie que llore por nosotros.}
{203}{}{¿Dónde está mi padre?}
{204}{}{Debería estar en el hangar en el centro de la Zona Prohibida. Todos los supervivientes están por allá. Dirígete al norte y lo verás.}
{205}{}{De acuerdo, nos vemos.}
{206}{}{Pero, ¿qué hay de ti?}
{207}{}{Andrés me dijo que me quedara aquí y enviara a los demás al hangar. No te preocupes, los contenedores me mantienen a salvo.}
{208}{}{Está bien. Cuídate, Gerardo.}

{210}{}{¡Gracias al cielo! ¡Sigues vivo!}
{1210}{}{¡Gracias al cielo! ¡Sigues viva!}
{211}{}{Quédate aquí.}
{212}{}{El campo de fuerza ya no funciona, y los robots no nos molestarán. Es hora de regresar a la Villa.}
{213}{}{¿Lo conseguiste? Está decidido, ¡eres la persona indicada para liderar la Villa! Pero, es obvio que algo ha cambiado dentro tuyo, amigo... ¡Te veo en casa! Si es que no morimos de camino.}
{1213}{}{¿Lo conseguiste? Está decidido, ¡eres la persona indicada para liderar la Villa! Pero, es obvio que algo ha cambiado dentro tuyo, amiga... ¡Te veo en casa! Si es que no morimos de camino.}
{214}{}{Cuídate.}
{215}{}{¿Ahora qué?}

{220}{}{Sígueme, necesitaré ayuda para luchar.}
{221}{}{¿De qué hablas, amigo? ¡Me llevarás a la tumba! No tenemos oportunidad contra los robots, es mejor esperar a que abran el campo de fuerza.}
{1221}{}{¿De qué hablas, amiga? ¡Me llevarás a la tumba! No tenemos oportunidad contra los robots, es mejor esperar a que abran el campo de fuerza.}
{222}{}{Tú no eres así, Gerardo. Siempre fuiste el valiente del pueblo.}
{223}{}{Yo... Sólo estoy vivo gracias a tu padre. La Villa y este lugar son como el día y la noche. No estoy hecho para esto, lo siento. Aunque vuelva a casa... no seré el mismo. Jamás.}
{224}{}{Gerardo, no es la hora de echarse para atrás. ¡Levántate, tu familia te necesita!}
{225}{}{Está bien, pero... ¡No me meteré a ese pinche búnker, compadre! Te acompañaré hasta la entrada, pero nada más.}
{1225}{}{Está bien, pero... ¡No me meteré a ese pinche búnker, señorita! Te acompañaré hasta la entrada, pero nada más.}
{226}{}{Es mejor que nada.}
{227}{}{No... Me necesitan aquí, Andrés cuenta conmigo.}
{228}{}{Está bien.}
{229}{}{Tenemos que separarnos, quédate aquí, ya vuelvo.}
{230}{}{Como tú digas, amigo...}
{1230}{}{Como tú digas, amiga...}
{231}{}{Trato hecho.}
