{100}{}{Ves a un Hojalatero.}
{101}{}{Ves a un hombre con overoles sucios. Su calva está cubierta de cables y sensores.}
{102}{}{Ves a un hombre con una armadura metálica. Parece ser que unas partes de la armadura se fusionaron con su carne.}


{110}{}{Es necesario desensamblar esta unidad.}
{111}{}{Podemos intercambiar estos componentes con los habitantes de Fénix.}
{112}{}{Este contenedor de tornillos debe ser eliminado.}
{113}{}{Este material no tiene ningún propósito práctico.}
{114}{}{Tengo simpatía por esta colección de chatarra.}
{115}{}{En algún punto, este montón de chatarra fue una maravillosa tecnológica.}
{116}{}{Anticipo la integración de la tecnología de la Zona Prohibida.}
{117}{}{Pronto será necesario un repuesto para el conversor de plasma.}
{118}{}{Pronto, los vehículos aéreos reanudarán su presencia sobre nosotros.}
{119}{}{¿Percibes el armónico funcionamiento de los pistones?}

{120}{}{¿Qué directrices dan los Dioses del Acero?}
{121}{}{Los Dioses del acero han prometido nuevos planos a cambio de células de microfusión.}
{122}{}{Se requiere la entrega inmediata de estos componentes al Puerto de Acero.}
{123}{}{Los Dioses del Acero buscan elevar a nuestra especie.}
{124}{}{}
{125}{}{Ni siquiera los Dioses del Acero podrían resistir el poder de la fisión nuclear.}
{126}{}{Jamás habríamos permitido los sucesos del Puerto de Acero.}
{127}{}{Sobrestimamos la inteligencia de los Dioses del Acero.}
{128}{}{}
{129}{}{}

{130}{}{¿Qué fecha se estima para próximo envío de mineral de uranio?}
{131}{}{La producción de células de fusión es crítica para el renacer de la civilización.}
{132}{}{Debemos restringir la distribución de baterías para optimizar nuestros recursos.}
{133}{}{¿Cuál es el recuento actual respecto al inventario de uranio?}
{134}{}{}
{135}{}{Requerimos los protocolos de conservación eléctrica hasta que Flagstaff reactive la mina.}
{136}{}{Hemos detenido la producción de células de fusión hasta que Flagstaff reinicie sus operaciones mineras.}
{137}{}{Nos han informado de que la mina de Flagstaff se encuentra inactiva.}
{138}{}{¿Qué cantidad de uranio nos queda?}
{139}{}{Sin la operación minera de Flagstaff, se detendrá la producción de baterías.}

{140}{}{¿Cuáles son las exigencias de la Catedral del Fuego?}
{141}{}{Los Seguidores del Fuego carecen de comprensión para cualquier tecnología avanzada.}
{142}{}{La presencia del Embajador de la Catedral nos impide operar eficientemente.}
{143}{}{Es necesario instruir al Embajador de la Catedral de que debe retractar sus directivas ineficientes.}
{144}{}{Si la Catedral insiste, entonces deben asegurar los planos necesarios.}
{145}{}{A pesar de nuestras burlas, la Catedral del Fuego es esencial para nuestras operaciones.}
{146}{}{La adquisición de material nuclear será considerablemente más difícil, puesto que ya no contamos con la Catedral.}
{147}{}{Tras la catástrofe de la Catedral, el valor su divisa ha disminuido drásticamente.}
{148}{}{Es imperativo establecer nuevas alianzas. La relevancia de la Catedral del Fuego ha disminuido.}
{149}{}{Este es el resultado cuando la tecnología avanzada se gestiona mal.}

{150}{}{Mantengan el orden y eviten las distracciones.}
{151}{}{Cada habitante del yermo tiene un comportamiento impredecible.}
{152}{}{Nuestro aumento laboral es consecuencia del alcance del Maestro Hard.}
{153}{}{Es posible que mis sistemas reciban una mejora.}
{154}{}{Un forastero es un compromiso necesario para el Progreso.}
{155}{}{Nuestra colectiva se encuentra libre de crimen; sólo los extranjeros lo provocan.}
{156}{}{Estamos monitoreando la actividad callejera muy activamente.}
{157}{}{}
{158}{}{}
{159}{}{}
