{100}{}{Ves un OjoBot.}
{101}{}{Ves a un robot traductor.}
{102}{}{*Psh-sh-sh*}
{103}{}{Su única respuesta es estática del parlante.}

{110}{}{Creo que podemos entendernos.}

{200}{}{(Un OjoBot te presenta un mensaje de ZAX) Gracias por tu ayuda. Como puedes ver, he conseguido desmantelar este asentamiento. Dejaré que tú y los demás aldeanos se vayan, con una condición - jamás vuelvan a estas tierras.}
{201}{}{Me parece bien.}
{202}{}{Espero que cumplas con tu palabra. Déjame sugerirte algo. Según mis datos, los Hojalateros respondían a una poderosa organización llamada La Hermandad del Acero. Ellos están detrás del auge de la esclavitud en Sonora. Necesitas descubrir cómo eliminar la base de la Hermandad para minimizar futuros riesgos a la Villa.}
{203}{}{¿Entonces piensan seguir con sus planes, aún con lo que acaba de ocurrir..? ¿En dónde puedo encontrar su base?}
{204}{}{Está hacia el oeste, en un puerto en la costa del Mar de Cortés. Es un lugar llamado Puerto Peñasco, la ruta más segura es pasar por un pueblo llamado Casa Nueva. Quiero eliminar a esta amenaza tanto como tú, pero no esperes que te ayude de ahora en adelante. Mis capacidades están contenidas a este lugar.}
{205}{}{Entiendo... Gracias por ayudarme, ZAX.}
{206}{}{No soy uno de tus robots. Descubriré como hacerlo sin tu ayuda.}
