{101}{}{Ves un montón de piezas electrónicas. Parece que alguien intenta ensamblar algo a partir de esto.}
{110}{}{Hay un montón de piezas electrónicas, parece que alguien intenta ensamblar algún tipo de arma a partir de esto.}
{111}{}{Es un arma improvisada de pulso electromagnético, hecha a partir de varias partes encontradas en la Zona Prohibida.}
{112}{}{¡Listo! Ahora los robots serán más obedientes...}
