{100}{}{Ves a un Personaje de Pruebas.}
{101}{}{Ves a un personaje para crueles experimentos. Podrías divertirte mucho con él.}
{110}{}{Ya, ya. Cálmate.}

#Replicas floating
{120}{}{Es un hermoso día para morir.}
{121}{}{Este es un mundo maravilloso, ¿no crees?}
{122}{}{}
{123}{}{}
{124}{}{}
{125}{}{}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

#Dialogue
{200}{}{¡Gloria a la Hermandad!}
{201}{}{Odio a la Hermandad. A ti igual.}
{202}{}{Eh, sí, sí, claro.}
{203}{}{Soy tu comandante ahora. Te ordeno que te unas al destacamento.}
{204}{}{¿Cuáles son mis ordenes, señor?}
{205}{}{Quédese ahí, soldado.}

{206}{}{Inteligencia 2}
{207}{}{Inteligencia 4}
{208}{}{Inteligencia 5}
{209}{}{Inteligencia 6}
{210}{}{Inteligencia 8}

{211}{}{Lo mío es tuyo, ¿no es así, amigo?}
{212}{}{¿Me tomas por tonto? ¡Estoy aquí para ti!}
{213}{}{Quédate aquí mientras pienso qué responder.}
{214}{}{¿Hermandad? Primera vez que lo escucho.}
{215}{}{Háblame de la Hermandad.}
