{100}{}{Ves a un campesino.}
{101}{}{Ves a un habitante de la Villa.}
{102}{}{Parece que alguien te espera en la salida.}
{103}{}{Esto jamás ocurrió, ¿de acuerdo?}
{104}{}{¡Mierda! ¿Qué...? ¿¡Qué demonios eres!?}
{105}{}{Es bueno verte.}

{200}{}{¿Qué tal vas con la búsqueda?}
{201}{}{Genial. Nos vemos.}
{202}{}{Bueno... Para ser honesto, tampoco me gusta la decisión del Consejo. Pero necesitamos dar un ejemplo a la Villa. Es por el bien de todos.}
{203}{}{Ojalá que sí.}
{204}{}{Métete tus excusas en la cola.}

{210}{}{(al salir, te encuentras con un conocido que parece haberte estado acechando) Vaya, vaya. ¡Pensé que sólo teníamos un traidor! ¿Qué demonios estás haciendo? ¿Acaso quieres arruinar nuestra comunidad por un cobarde como él?}
{211}{}{Ustedes están mal, matar a uno de los nuestros nos llevará a la ruina.}

{212}{}{Quizás tengas razón... ¡No lo sé! Después de lo que pasó, todos cambiamos. Solíamos vivir en paz, nadie intentaba joderse al otro. Eso sólo ocurría en los primeros días...}
{213}{}{[Más]}
{214}{}{Nuestros ancestros venían aquí por materiales con los que hacer sus hogares. Decían que la vida era difícil - los vecinos se robaban entre sí. Pero superamos eso y nos volvimos una familia muy unida. Pero todo ha cambiado.}
{215}{}{Entonces deberías entenderme, no podemos hacer eso. Deja que Chris se vaya.}
{216}{}{¡No! Él... tenemos que dar un ejemplo... es lo que decidió la comunidad...}
{217}{}{Tienes miedo. Te da miedo de que la Villa cambie.}
{218}{}{¡Sí! ¡Es eso! Chris... perdóname.}
{219}{}{Entonces, está decidido.}
{220}{}{Haz lo que debas. No te detendré.}
{1220}{}{Haz lo que debas. No te detendré.}
{221}{}{No me importa lo que piensen. Chris quedará libre.}
{222}{}{¡No te perdonaremos por ésto! (escupe en tus pies y se va)}
{223}{}{Vuelve con el rebaño, borrego...}
{224}{}{Sólo deja que Chris se vaya.}
{225}{}{Yo soy quién manda. Y mi decisión es que Chris quedará libre.}
{226}{}{Bueno, si es lo que quieres, se lo haré saber a los demás. Perdón, Chris.}

{230}{}{No es lo que piensas. Lo llevaré a la Villa para que cumpla su condena.}
{231}{}{¿En serio? ¿Y por qué lleva una mochila llena de comida?}
{232}{}{Son mis cosas, hice que las llevara como parte de su castigo.}
{233}{}{Hmm. Sí, deberíamos darle su merecido. No es nada personal, Chris. El pueblo elige, vámonos a la plaza. Es hora de tu castigo.}
{234}{}{[Regresa a la plaza]}

{240}{}{Piensa lo que quieras. Sé lo que hago.}
{241}{}{Hmph. Los demás ya me habían hablado sobre ti. Parece que estaban en lo cierto.}
{242}{}{Hmph. Los demás ya me habían hablado sobre ti. ¡Pero nadie se esperaba esto!}
{243}{}{¡Carajo! No quiero que me rechace mi propia familia. Bueno, ejecútalo, no haré nada.}
{244}{}{No me importa lo que piensen. Chris quedará libre.}
