{100}{}{Ves a la nana.}
{101}{}{Ves a Anita, es una de tus muchas tías.}
{102}{}{¡Sigue así y te daré un chanclazo!}
{103}{}{Has agregado una nueva misión a tu Pip-Boy.}
{104}{}{¡Un hombre de hojalata! ¡Sal de aquí, no le hagas nada a los niños!}

{200}{}{Estoy feliz de verte.}
{201}{}{Primero vienen los saqueadores, y ahora tú.}
{202}{}{Adiós.}
{203}{}{Ya veo. Adiós.}
{204}{}{}
{205}{}{}
{206}{}{, ¿eres tú? ¡Ay, estás bien! ¡Gracias a Dios! Se llevaron a la mitad del pueblo.}
{207}{}{No te preocupes, yo los rescataré.}
{208}{}{Lo sé. Son unos bastardos.}
{209}{}{Ya me di cuenta. ¿Tienes algo útil que decir?}

{210}{}{Cuéntame lo que pasó.}
{211}{}{¡No me hagas recordarlo! Entraron, golpearon a nuestros hombres, quebraron las puertas y las ventanas... ¡No quería ni moverme! Y los niños siguen mal.}
{212}{}{¿Cómo están los niños?}
{213}{}{Están en estado de shock, así que debo cuidarlos. Hasta a mí me vendría bien algo de ayuda... Es terrible.}
{214}{}{¿Te puedo ayudar en algo?}
{215}{}{Creo que sí... Edén perdió a sus padres y se asustó tanto que salió corriendo, ahora está escondido en alguna parte. Quiero ir a buscarlo, pero no puedo dejar sólos a los niños. ¿Podrías ir tú?}
{216}{}{¿En dónde debería buscarlo?}
{217}{}{¡Podría estar escondido en cualquier lado!}
{218}{}{¿Sabes si tiene un sitio favorito en donde jugar?}
{219}{}{Bueno, recuerdo que colocó una "base" en alguna choza de las plantaciones.}
{220}{}{Veré que puedo hacer.}
{221}{}{¿Podrías repetirme qué pasó con Edén?}
{222}{}{Edén perdió a sus padres y se asustó tanto que salió corriendo y ahora está escondido en alguna parte. Me da miedo de que se haya metido en problemas.}
{223}{}{Malas noticias. Edén ha fallecido.}
{224}{}{(casi se desmaya) Ay... Ay, Virgencita... Ya suponía que era demasiado tarde... todo es mi culpa... ¿Por qué no lo detuve?}
{225}{}{Hicimos lo que se pudo.}
{226}{}{Edén ha vuelto, como ya puedes ver.}
{227}{}{¡Se habría muerto sin tu ayuda! Es mi turno de cuidarlo. (caen lágrimas de sus ojos) ¡Muchísimas gracias!}
{228}{}{No importa, somos familia. Lo correcto era ayudarte.}
{229}{}{Apreciaría que me des de comer, pero supongo que un "gracias" es suficiente.}
{1229}{}{Apreciaría que me des de comer, pero supongo que un "gracias" es suficiente.}
{230}{}{Oh, pues... Los bandidos se llevaron todo, nos dejaron sin nada. Pero sí tengo algo que darte, los niños encontraron esto; se le tuvo que haber caído a uno de ellos.}
{1230}{}{Oh, pues... Los bandidos se llevaron todo, no nos queda nada. Pero sí tengo algo que darte, los niños encontraron esto; se le tuvo que haber caído a uno de ellos.}
{231}{}{Nudilleras... Seguro que les daré algún uso.}
{232}{}{Es bueno que estés con nosotros... Ah, cierto, los niños encontraron esto; parece que se le cayó a uno de los bandidos. Llévatelas, quizás te sirvan.}
{233}{}{No han dejado de tener pesadillas. Intento ayudarlos mientras que los demás reconstruyen la Villa. Pero nadie me ayuda, no sé si podremos recuperarnos.}
