{100}{}{Ves a un campesino.}
{101}{}{Ves a uno de tus paisanos, regresó hace poco de Flagstaff.}
{102}{}{¿Dejaste que se te subiera todo a la cabeza después de lo que hiciste? Ten cuidado.}
{103}{}{¡Atrás, grandulón! ¡Sé cómo defenderme!}

{110}{}{¡Qué desastre!}
{111}{}{Será difícil arreglar todo ésto sin piezas de repuesto.}
{112}{}{Ojalá que esos "héroes" dejaran de tocarme la puerta.}
{113}{}{Parece que alguien estuvo husmeando en mi sótano.}
{114}{}{Suficiente, voy a cerrar con llave de ahora en adelante.}
{115}{}{Necesito otra puerta.}
{116}{}{¡Malditos saqueadores, me las van a pagar!}
{117}{}{¡Si yo estuviera a cargo de la Villa esto no hubiera pasado!}
{118}{}{¿En dónde estaba el consejo de la Villa durante todo esto?}
{119}{}{Jamás volveremos a confiar en los forasteros.}

{200}{}{Hola. Gracias por salvarme el pellejo. Si me disculpas, tengo que arreglar la casa.}
{201}{}{Adiós.}
{202}{}{Lo siento, me metí a tu sótano y me llevé algunas cosas.}
{1202}{}{Lo siento, me metí a tu sótano y me llevé algunas cosas.}
{203}{}{Así que fuiste tú. Es de mala educación meter la mano en cosas que no son tuyas, ¿lo sabías?}
{204}{}{Necesitaba todo lo posible para rescatarte a ti y a los demás.}
{205}{}{¡Sí, claro! No importa qué tan héroe te sientas o cuánto hayas conseguido, tienes que pedir permiso antes de hurgar en cosas ajenas, ¿entendido?}
{1205}{}{¡Sí, claro! No importa si te sientes como una heroína o cuánto hayas conseguido, tienes que pedir permiso antes de hurgar en cosas ajenas, ¿entendido?}
{206}{}{Eres un malagradecido... vete al carajo.}
{207}{}{Ya veo.}
{208}{}{Tengo algo de tiempo libre. ¿Te ayudo en algo?}
{209}{}{Me quedan algunas cosas en el sótano, ve a revisar si hay algo que te sirva. La entrada está escondida con unas cajas en esa sala de allá.}
{210}{}{Gracias.}
