{100}{}{Ves a Edén.}
{101}{}{Ves a un niño llamado Edén. Tiene una apariencia sucia y asustada.}
{102}{}{*Asienta con la cabeza en silencio*}
{103}{}{Edén ha regresado a la villa.}
{104}{}{*Aterrado por tu armadura*}

{200}{}{(te observa atemorizado, sin decir una palabra)}
{201}{}{¿No sabes que es peligroso andar por aquí, sólo?}
{202}{}{(sigue observándote, aún con miedo)}
{203}{}{Mira, estamos en un momento difícil, pero saldremos de esta si lo hacemos juntos. Vamos, hay que ir a la Villa.}
{204}{}{No te preocupes, yo te cuidaré.}
{205}{}{Entonces quédate aquí y muérete de hambre, niño malcriado. Me voy.}
{206}{}{Este lugar es demasiado peligroso. Vámonos a la Villa.}
{207}{}{Oye, mira, tengo una fruta, está muy rica. ¿Tienes hambre, verdad?}
{208}{}{Quédate aquí, ya vuelvo.}
{209}{}{Parece que se me cayó del bolsillo. Espérame, ya vengo.}

{210}{}{(niega con la cabeza y se aleja de ti)}
{211}{}{¡Ahh! (Parece que Edén está listo para ir contigo)}
{212}{}{Genial, vamos.}
