{100}{}{Ves al Tío Miguel.}
{101}{}{Ves a tu tío, vino desde Fénix.}
{102}{}{Tío... siempre me caíste mal.}
{103}{}{El Tío Miguel regresó a la Villa.}
{104}{}{Que buena idea, muéstrale a estos orates una tecnología así de avanzada. Les va a ENCANTAR...}
{105}{}{Así que esa es la legendaria servoarmadura. (silba)}

#First dialogue
{200}{}{Hola, sobrino. Creo que ya entiendo por qué te gusta tanto este lugar. Está muy tranquilo, a diferencia de la ciudad.}
{1200}{}{Hola, sobrina. Creo que ya entiendo por qué te gusta tanto este lugar. Está muy tranquilo, a diferencia de la ciudad.}
{201}{}{Me das la impresión de que no te importaba la Villa. ¿Qué te hizo cambiar de parecer?}
{202}{}{¿Qué estás diciendo? ¡Amo a la Villa! Es un maravilloso con gente maravillosa. Es sólo que buscaba mostrarles que su mundito está condenado.}
{203}{}{¿Y entonces por qué volviste?}
{204}{}{Fénix ya no es lo que era. Después de lo que hiciste, casi estalla una guerra civil. Y en ese entonces me di cuenta de que me equivoqué, sobre algunas cosas.}
{205}{}{¿Algunas? Me parece que fueron muchas más, tío Miguel. Nos vemos.}

{210}{}{Me alegra verte, sobrino.}
{1210}{}{Me alegra verte, sobrina.}
{211}{}{Adiós, Tío Miguel.}
