{102}{}{¡Esto es por mi infancia! ¡Fue difícil, papá!}
{103}{}{Adiós, padre. Ya no necesito tus lecciones.}
{104}{}{¿Te sientes bien de la cabeza? Anda al yermo y entierra ese... pedazo de hojalata en algún lugar profundo.}
{105}{}{Tu padre ha regresado a la Villa.}
{106}{}{Me enorgulleces, hijo.}
{1106}{}{Me enorgulleces, hija.}
{107}{}{Ya no eres mi hijo. Para mí, eres un desconocido.}
{1107}{}{Ya no eres mi hija. Para mí, eres una desconocida.}
{108}{}{Si quieres irte, Hazlo. Pero no intentes llevar a los demás por un mal camino.}

#First dialogue
{200}{}{Tu regreso alegró a toda la Villa. Estoy orgulloso de ti.}
{201}{}{Me... alegra saber eso.}
{206}{}{¿Qué te pasó?}
{207}{}{¿Te refieres a mi piel? No es nada.}
{208}{}{Realmente espero que no sea contagioso. Créeme, estoy dispuesto a sacrificar lo que sea, o a quien sea, para proteger a la comunidad. Pero por ahora, suficiente de eso.}
{209}{}{Gracias por ser tan... honesto, papá.}

#Re-dialogue
{210}{}{Habla, te escucho.}
{211}{}{No es nada, mejor me voy.}
{212}{}{¿Más?}

{220}{}{Padre, ¿por qué siempre hemos vivido aislados del resto del mundo?}
{221}{}{Tener demasiado contacto con los forasteros no nos traerá nada bueno. Eso es lo que nos enseñó el Fundador. Quiero que recuerdes los asentamientos que has visitado, la gente está dividida y no es capaz de coexistir en paz y armonía como lo hacemos nosotros.}
{222}{}{[Más]}

{228}{}{Te exijo una explicación - ¿por qué hay un forastero con una toga blanca deambulando por la plaza mientras mira nuestros hogares?}
{229}{}{Se llama Arthur Carrington, es un científico. Parece que su ayuda podría ayudarnos a restaurar la Villa después del asalto.}
{230}{}{¿Quieres la ayuda de alguien que puede leer y sabe matemática pero es incapaz de agarrar una pala?}
{231}{}{Es un poco débil, es cierto, pero sabe mucho del mundo exterior. Él entiende la tecnología antigua, con su ayuda, nosotros podríamos...}
{232}{}{¡No puedo creer lo que estoy escuchando! ¿Acaso tu viaje por el desierto te nubló la mente? Hemos vivido aislados por generaciones, ¿y se te ocurre traer a un desconocido y sugerir que debemos adoptar la tecnología antigua? Reza porque tu decisión no sea la incorrecta. Estaré vigilando a ese forastero... y a ti.}
{233}{}{No te arrepentirás.}
{234}{}{Sabes, la comunidad quiere castigar a Chris por su cobardía.}
{235}{}{La Villa siempre ha seguido la voluntad de la mayoría. Esa es nuestra ley, y así es como hemos sobrevivido en el desierto. La historia de Chris demuestra lo importante que es la unidad.}
{236}{}{}
{237}{}{}
{238}{}{Es por eso que hemos evitado el contacto con los forasteros - así mantenemos a nuestro mundo sin las manchas de su egoísmo. Al dejarlos pasar, no nos trae nada más que la discordia. Recuerda eso cuando hables con los demás campesinos de la Villa.}
{239}{}{Comprendo.}

{240}{}{Necesitaré suministros y armas para mi misión.}
{241}{}{(asiente con la cabeza) Estoy de acuerdo. Es la hora de entregarte algunas de nuestras reliquias. Ve a mi oficina del segundo piso, hay una caja fuerte con objetos valiosos del Viejo Mundo. Toma lo que necesites, el código es 2093. Ese fue el año en el que nuestro Fundador llegó aquí y plantó el primer elote.}
{242}{}{No deshonraré a nuestro Fundador y lucharé por nuestra libertad.}
{243}{}{Gracias.}

#Quests
{250}{}{¿Qué puedo hacer para ayudar?}
{251}{}{Algunos de los nuestros están encarcelados por los colonos de Flagstaff. La Villa me necesita demasiado, debes salvarlos.}
{252}{}{De acuerdo, los traeré aquí.}
{253}{}{¿¡Cómo!? Me costó tanto liberarte de Two-Sun, ahora Flagstaff, y...}
{254}{}{¡No es una elección! Es tu deber como el futuro líder. ¡Haz lo que DEBES hacer!}
{1254}{}{¡No es una elección! Es tu deber como la futura líder. ¡Haz lo que DEBES hacer!}
{255}{}{Tu madre todavía no vuelve de Flagstaff, me temo que debe seguir entre las garras de los esclavistas. ¡Debes salvarla a cualquier costo!}
{256}{}{Puedes contar conmigo, Padre.}
{257}{}{Mamá... está muerta. No llegará a casa.}
{258}{}{Habla con los demás, puede que no sepa todo lo que ocurre en la Villa.}
{259}{}{De acuerdo.}
{260}{}{(respira profundamente con los ojos cerrados) María... ¿Lo viste con tus propios ojos? Es mejor que los demás no lo sepan todavía, una noticia así podría hacer nuestras vidas más difíciles de lo que ya son.}
{261}{}{¿Qué hacemos ahora?}
{262}{}{Tenemos mucho por hacer. Los asaltantes han saqueado el pueblo, las ratas han infestado los sótanos y las plantaciones están en mal estado, pero debemos prepararnos para cualquier amenaza.}
{263}{}{[Más]}
{264}{}{La comunidad lo decidirá, vamos a tener una reunión en el ayuntamiento. Tu experiencia en el yermo resultará crucial. Tienes que estar ahí.}
{265}{}{De acuerdo, ahí estaré.}
{266}{}{Háblale a la gente, puede que no sepa qué está ocurriendo en toda la Villa. Y no te olvides de la reunión, tu opinión será crucial.}
{267}{}{De acuerdo, ahí estaré.}

{270}{}{El Consejo quiere colapsar a la mina de Flagstaff. ¿Qué opinas?}
{271}{}{Es arriesgado, pero necesario. Eres la única persona capaz de hacerlo, si dejamos la mina en paz, necesitarán más esclavos y vendrán hasta acá otra vez. No podemos permitir eso.}
{272}{}{Ya veo.}
{273}{}{La decisión del Consejo es destruir la fábrica de Ciudad Garaje. ¿Qué piensas de eso?}
{274}{}{Los chatarreros lo merecen, ellos nos traicionaron al ayudar a los saqueadores. Si se repara la fábrica, eso nos costará nuestra privacidad, nuestra paz y nuestra forma de vida. Debe ser destruida.}
{275}{}{Comprendo.}
{276}{}{¿Qué es lo que opinas sobre una alianza con los Rangers?}
{277}{}{Los Rangers tienen sus propios objetivos, pero necesitamos aliados para mejorar nuestra seguridad y para eso no hay nadie mejor que los Rangers. Sólo podemos esperar que se limiten a protegernos a cambio de nuestra comida.}
{278}{}{Puede que tengas razón, papá.}
{279}{}{¿Cuál es tu opinión sobre formar una alianza con la Hermandad del Acero?}
{280}{}{No parece que haya otra opción, ¿verdad? Bueno, si no puedes vencerlos, úneteles.}
{281}{}{Buena respuesta, papá.}

# Background of the Villa
{300}{}{Ahora sé de los registros del Fundador. Los leí.}
{301}{}{Bueno, pensé que era demasiado temprano como para que supieras esas cosas. El resto de los aldeanos tampoco debería leerlos - no hay por qué llenarles la cabeza de preguntas que deberían hacerse los líderes. En el futuro, la Villa te verá como su líder, entonces debes tratar las palabras, la sabiduría, del Fundador con respeto y atención.}
{302}{}{¿Estás totalmente de acuerdo con lo que escribió?}
{303}{}{Por supuesto. Hemos seguido su testamento durante generaciones y eso debemos hacer. El Fundador fue sabio, lo moldeó una vida difícil. Si él nos dice que evitemos la tecnología antigua, tiene sentido. Si él nos dice que cosechemos elote, entonces lo haremos bien. Si él nos dice que debemos expulsar a los forasteros, el asalto demuestra que tiene razón.}
{304}{}{Ya veo.}
{305}{}{Resulta que visité el Refugio 27. Jamás lo mencionaste.}
{306}{}{¿¡De qué estás hablando!? ¿El mismo Refugio del que vinieron nuestros ancestros?}
{307}{}{Exacto. Como dijo el Fundador, es un tesoro lleno de tecnología antigua...}
{308}{}{¡Cállate! El Fundador abandonó el Refugio por una razón, y ya la conoces. No saques a relucir el pasado y olvida todo lo que hayas visto y escuchado ahí adentro.}
{1308}{}{¡Cállate! El Fundador abandonó el Refugio por una razón, y ya la conoces. No saques a relucir el pasado y olvida todo lo que hayas visto y escuchado ahí adentro.}
{309}{}{¿Por qué te aterra tanto el pasado?}

{310}{}{El Fundador creía que la comunidad debería abandonar a la tecnología y recurrir al trabajo manual. Él evitó hablar del Refugio y de su tecnología.}
{311}{}{Pero no es sólo eso, ¿cierto? Él robó una especie de Kit de Creación del Jardín del Edén y condenó a todos los que dejó atrás para que sufrieran.}
{312}{}{(enojado) ¡No importa! ¡Él salvó a su gente! (se calma) Los tiempos difíciles exigen decisiones difíciles. El Fundador vivió con esa carga hasta el fin, pero creó a la Villa y le trajo la vida a este desierto. Si alguien se atreve a decir que sus acciones fueron un crimen, yo mismo les arrancaré la lengua.}
{313}{}{Pero, papá...}
{314}{}{Lo entiendo. No volveré a hablar de esto.}

{315}{}{¡Suficiente! No le cuentes a nadie acerca de esto, los demás aldeanos no lo entenderán. Y ni yo ni los ancianos quieren saber de ello.}
{316}{}{Como tú digas, padre.}
{317}{}{Hmph. Me lo pensaré.}
{318}{}{Gracias. No le cuentes a nadie acerca de esto, los demás aldeanos no lo entenderán. Y ni yo ni los ancianos quieren saber de ello.}
