{100}{}{Ves a Arthur Carrington.}
{101}{}{Ves al arqueólogo del Refugio 27.}

# First dialogue
{200}{}{Es tan bueno volver a verte. Te agradezco el honor. La Villa me abre nuevas puertas que puedo investigar. ¡Y ya me sorprende lo que he descubierto! No entiendo cómo se las arreglan sin tecnología avanzada, deberían aprovechar algunas, aunque sea.}
{201}{}{Tal vez.}
{210}{}{¿Sí?}
{211}{}{No es nada. Adiós.}
{212}{}{Suficiente, dime otra cosa.}

{220}{}{Y, ¿te sientes a gusto?}
{221}{}{Para serte honesto, los demás campesinos no son amables con los desconocidos. Los niños se ríen de mí porque soy delgado, y los adultos no quieren hablarme. Eres lo único que los mantiene a raya. Pero, en ellos también veo interés, interés en algo que solía ser un tabú para tu comunidad.}
{222}{}{¿Hablas de la tecnología?}
{223}{}{El trabajo manual es tedioso e inefectivo. Según mis cálculos, un acueducto incrementaría la productividad en un 250% y reducir el trabajo necesario en un 40%. Desafortunadamente, los ancianos no quieren ni escucharme.}
{224}{}{La Villa ha conseguido sobrevivir sin tecnología.}
{225}{}{Sí, ¿pero a qué costo? Enfermedades, malas cosechas, riesgo a lesionarse y las malas condiciones laborales son los problemas que hasta la tecnología más básica de la preguerra podría resolver, tal como una bomba de agua o la iluminación eléctrica.}
{226}{}{¿Crees que la Villa necesita... cambiar?}
{227}{}{Eso es una pregunta que solo tú puedes responder. Pero algún día, la llama de la civilización arderá en el sur una vez más. ¿Serás capaz de defenderte ante tal batalla? Lo dudo. Ni siquiera pudieron defenderse ante un montón de mercenarios con rifles viejos.}
{230}{}{Uno de los aldeanos está herido y necesita ayuda. ¿Puedes ayudarlo?}
{231}{}{Sé algo de medicina, podría ayudar. Pero ten en cuenta que los demás aldeanos tienen una disposición negativa ante la medicina del Viejo Mundo.}
{232}{}{No hay tiempo para pensar en eso, ¡ayúdalo!}
{233}{}{Entonces intentaré ayudarlo con lo que sé.}
{234}{}{Nuestra estación meteorológica está rota. ¿Sabes cómo arreglarla?}
{235}{}{Por supuesto, no será ningún problema. La meteorología es una de mis ciencias favoritas.}
{236}{}{Entonces, por favor, adelante.}
{237}{}{Bien, pero primero intentaré arreglarla yo.}
