{100}{}{Ves un monitor de entretenimiento.}
{101}{}{En esta computadora, puedes escoger servicios de entretenimiento - escuchar música o reproducir películas.}

{110}{}{El monitor necesita corriente eléctrica para funcionar, y no hay mucho de eso en el refugio.}
{111}{}{De lo que había, escogiste un jazz instrumental. El sonido de las trompetas produce un eco a través del refugio, como si fuera un último adiós.}
