{100}{}{Ves la computadora de la librería.}
{101}{}{La computadora podría otorgar acceso a la librería digital, pero no funciona.}

{110}{}{La terminal podría otorgar a la librería digital, pero no funciona.}
{111}{}{Puedes acceder a la librería digital desde esta computadora.}
{112}{}{Has reparado la computadora exitosamente.}
{113}{}{La computadora está apagada. Necesitas reparar el suministro de energía para usarla.}
