{100}{}{Ves a José Solís.}
{101}{}{Ves a un necrófago en un traje de la preguerra. Se ve mucho más limpio y presentable que los demás necrófagos.}
{102}{}{Parece que eres nuevo aquí. ¿Qué tal si me compras un trago y hablamos un poco?}
{103}{}{Mis sueños de "Los Mariachis de José Solís" están acabados.}
{104}{}{¡Los Mariachis de José Solís están de vuelta!}
{105}{}{No me distraigas, estoy ensayando. ¡Hablamos luego!}

{200}{}{Hola, humano. Escuché que había un normalucho en el pueblo, pero pensé que sería otro chiste de los necrófagos. Y aquí estás, cegándome con tu pálida piel, haciendo que recuerde los viejos días. Por cierto, me llamo José Solís, ¿y tú eres?}
{201}{}{Soy }
{202}{}{.}
{203}{}{Encantado de conocerte, }
{204}{}{. ¿Qué te parece nuestra ciudad? ¿Ya te aburriste?}
{205}{}{Soy }
{206}{}{. Recuérdalo, si tu cerebro podrido lo permite.}
{207}{}{Lo entiendo, }
{208}{}{. Veo que no te gusta mucho este lugar. ¿O me equivoco?}
{209}{}{Está bien. Es habitable.}
{210}{}{Es raro escuchar eso de un normalucho. Parece como si me estuvieras tomando el pelo... si lo tuviera. Bueno, ¿qué te trae por aquí?}
{211}{}{Es un poco aburrido.}
{212}{}{¡Así es! Incluso yo quiero traerle algo de vida al sitio. Entonces, ¿qué estás buscando?}
{213}{}{Nada en particular, sólo echo un vistazo. Nos vemos.}
{214}{}{¿Te puedo hacer unas preguntas?}
{215}{}{¡Saludos, compadre! Escuché que había alguien nuevo en el pueblo, pero no de Necrópolis. Es una sorpresa. Me llamo José Solís, ¿y tú?}
{1215}{}{¡Saludos, chiquita preciosa! Escuché que había alguien nuevo en el pueblo, pero no de Necrópolis. Es una sorpresa. Me llamo José Solís, ¿y tú?}
{216}{}{Así es. Éste lugar es mejor que Necrópolis. ¡Y esto es sólo el principio! Algún día podremos restaurar la gloria de esta ciudad, ya lo verás, se te caerá la boca del asombro. ¿Cómo te puedo ayudar?}
{217}{}{¡Claro que sí! Incluso yo quiero traerle algo de vida al sitio. Bueno, ¿con qué te ayudo?}

{220}{}{¡Buenas, compadre!}
{1220}{}{¡Saludos, mi amor!}
{221}{}{Buenas, }
{222}{}{.}
{223}{}{¿Con qué te ayudo, }
{224}{}{?}
{225}{}{Te conozco, }
{226}{}{. Siempre causas problemas. Es mejor que seas sensible y no me molestes sin razón alguna.}
{227}{}{Saludos, Señor Normalucho.}
{1227}{}{Saludos, Señorita Normalucha.}
{228}{}{Saludos, }
{229}{}{. Espero que tengas sentido común para no causar un alboroto por aquí.}
{230}{}{Creo que es hora de que me vaya.}
{231}{}{Bueno, gracias por la charla. Últimamente los normaluchos evitan hablarnos y nos disparan apenas nos ponen el ojo encima. No son muy sociables que digamos.}
{232}{}{Adiós.}

{240}{}{Por supuesto. Dime.}
{241}{}{Sólo si prometes dejarme en paz al acabar.}
{242}{}{¿Qué está pasando aquí?}
{243}{}{La verdad nada interesante. La rutina de siempre de una ciudad grande.}
{244}{}{Hmm. Entiendo.}

{250}{}{¿Qué te parece este sitio?}
{251}{}{Es un pueblo decente. Hay buen clima, buena gente. Pero, San Diego era conocida por su vida cultural. Ahora la única melodía que escuchas es el traqueteo del contador geiger.}
{252}{}{Sí, me encantaría escuchar algo de música de verdad.}
{253}{}{¿Bromeas? Las ruinas tienen más de un siglo. No hay nadie que toque música por aquí.}
{254}{}{Entonces sonríe, bebé. ¡Estás mirando a José Solís! Mi grupo era conocido por toda Baja California, eran buenos tiempos. Estábamos tocando en Bakersfield cuando cayeron las bombas. Yo sobreviví por un milagro. Y ahorita estaba pensando en regresar a mis viejas andanzas.}
{255}{}{¿Y qué te detiene?}
{256}{}{Bueno, para empezar, necesito cuerdas nuevas para mi guitarra. Está en mi habitación ahora mismo, y encontrar algo así entre las ruinas no es fácil.}
{257}{}{Te encontraré unas cuerdas, no hay nada que no pueda encontrar.}
{258}{}{¡Gracias, señor! Juntos podremos recordarle a Dayglow cómo eran los viejos tiempos.}
{1258}{}{Gracias, señorita! Juntos podremos recordarle a Dayglow cómo eran los viejos tiempos.}
{259}{}{Adiós.}
{260}{}{¿Al menos me pagarás el trabajo?}
{261}{}{La verdad, ahora mismo no puedo pagarte. ¿Qué te parece si te doy una parte de lo que gane el primer concierto?}
{262}{}{Me parece bien. Te buscaré las cuerdas.}
{263}{}{No quiero ni chapas ni problemas. Adiós.}
{264}{}{Lo siento, pero no es lo mío. Adiós.}
{265}{}{¿Sabes en dónde puedo encontrar las cuerdas?}
{266}{}{He buscado en todas las ruinas locales; no hay cuerdas por acá. Lo único que queda es ir a Tijuana, solía tener un museo de mariachis y unos escenarios hermosos. Pero ahora está llena de robots y mutantes.}
{267}{}{Entonces tendré que ir al otro lado de la frontera. Iré a buscar.}
{268}{}{¿Probaste las cuerdas nuevas en tu guitarra?}
{269}{}{¡Son maravillosas! Además, mi piel seca hace que sea más fácil presionar las cuerdas. Gracias, amigo mío.}
{1269}{}{¡Son maravillosas! Además, mi piel seca hace que sea más fácil presionar las cuerdas. Gracias, amiga mía.}
{270}{}{De nada. ¿Cuándo vas a tocar?}
{271}{}{¡No me apures! No estoy listo aún. Y lo más importante, no puedo tocar sólo, ¡me faltan mis compañeros!}
{272}{}{¿Entonces también están en Dayglow?}
{273}{}{Fernando es el trompetero y trabaja en la presa, y la señorita Beatriz está en la cafetería de San Isidro. Si pasas por ahí, ¿podrías traerlos?}
{274}{}{Claro, ¿por qué no?}
{275}{}{¿Y qué gano yo si te los traigo?}
{276}{}{Me convenciste, traeré a tus compañeros.}
{277}{}{¡Ay güey, qué emoción!}
{278}{}{Adiós.}
{279}{}{¿En dónde puedo encontrar a Fernando?}
{280}{}{Fernando trabaja en la planta eléctrica de Bonita.}
{281}{}{¿En dónde está Beatriz?}
{282}{}{La señorita de Beatriz trabaja en la cafetería de San Isidro.}
{283}{}{Ya entiendo. Tengo otra pregunta.}
{284}{}{Adiós.}
{285}{}{Ya llegaron Fernando y Beatriz.}
{286}{}{¡Excelente! Tengo mucho que hablar con ellos, ven a nuestro primer concierto, será mañana.}
{287}{}{Está bien. Buena suerte con el ensayo.}
{288}{}{Fernando ya llegó, pero Beatriz ha muerto.}
{289}{}{¡Pobre Beatriz! Al menos ya encontró la paz. Me da algo de envidia...}
{290}{}{Beatriz ya llegó, pero Fernando ha muerto.}
{291}{}{¡Pobre Fernando! Al menos ya encontró la paz. Me da algo de envidia...}
{292}{}{¡Virgencita, no! El sueño se me escapa como arena entre los dedos... A ver, ¿y qué tal un holograma? Sé que queda uno en el centro comercial de Chula Vista. Quizás funcione de reemplazo. ¿Me podrías traer el módulo holográfico? Puedo reconfigurarlo para mis propósitos.}
{293}{}{¿En serio? Bueno, iré a buscar esa cosa, antes de que decidas saltar de un puente.}
{294}{}{Tengo el módulo holográfico, toma.}
{295}{}{Fernando y Beatriz han muerto.}
{296}{}{Fernando y Beatriz han muerto. Lo siento mucho.}
{297}{}{¡Excelente! Necesito tiempo para prepararme, ven a nuestro primer concierto, será mañana.}
{298}{}{Está bien. Buena suerte con el ensayo.}
{299}{}{¡Es mi compadre, }
{1299}{}{¡Es mi musa, }
{300}{}{! Me llevaste de vuelta al 2077. Hace mucho tiempo que no sonreía así. Por cierto, nos fue genial en el concierto. Aquí tienes tu parte, 1.000 chapas. Gracias, amigo mío.}
{1300}{}{! Me llevaste de vuelta al 2077. Hace mucho tiempo que no sonreía así. Por cierto, nos fue genial en el concierto. Aquí tienes tu parte, 1.000 chapas. Gracias, señorita.}
{301}{}{Te deseo suerte, José.}
{302}{}{! Me llevaste de vuelta al 2077. Hace mucho tiempo que no sonreía así. Por cierto, nos fue genial en el concierto. Aquí tienes tu parte, 1.000 chapas. Y de mi parte, este whiskey de la preguerra. Gracias por tu ayuda, amigo mío.}
{1302}{}{! Me llevaste de vuelta al 2077. Hace mucho tiempo que no sonreía así. Por cierto, nos fue genial en el concierto. Aquí tienes tu parte, 1.000 chapas. Y de mi parte, este whiskey de la preguerra. Gracias por su ayuda, señorita.}
{303}{}{¿Qué nombre le pondrás a la banda?}
{304}{}{Hmm, tiene que ser algo romántico. ¿Quizás "El Último Aliento"? ¿A lo mejor "Amor en el Infierno"? ¿Qué tal "Un Último Beso"? O...}
{305}{}{Creo que sería mucho más simple si sólo le pones tu nombre.}
{306}{}{¿Los Mariachis de José Solís...? ¡Por supuesto!}
{307}{}{Bueno, algo es algo...}
{308}{}{Por cierto, ¿qué nombre le pondrás a la banda?}
