{100}{}{Ves a un chatarrero.}
{101}{}{Ves a un chatarrero con equipamiento especial para explorar las ruinas.}
{102}{}{¿También vas a explorar? Entonces ve a las áreas por las que no andaremos. Sólo es una advertencia.}
{103}{}{¡Vamos a pelear! ¡Si no estás con nosotros, piérdete! ¡Vete!}
{104}{}{Ya, ya. Perdón, nos dejamos llevar. Lo siento.}
{105}{}{¡Así es! ¡Somos los que mandan por aquí!}

{200}{}{¡Pelea! ¡Si no estás con nosotros, piérdete! ¡Pelea!}
{201}{}{¡Sí! ¡Te daremos lo que buscas!}
{202}{}{¡Dejen de pelear! No dejaré que causen problemas en el bar de los necrófagos.}
{203}{}{¿Ah, sí? ¿Y qué harás el respecto, PENDEJO?}
{204}{}{Tomaré mi arma y haré pedazos al primero que se mueva.}
{205}{}{¡Jajaja! ¡Eres la mascotita de los necrófagos! ¡Tienes agallas! ¡Dispara! Jajaja. Ya, muchachos, vámonos de aquí. Estos payasos no valen la pena.}
{206}{}{Fuera de aquí.}
{207}{}{Me quedaré aquí hasta que se vayan.}
{208}{}{¿Qué dijiste, bastardo? ¡Haré que te tragues tus palabras, junto a tus dientes!}
{209}{}{[Lanza un montón de chapas al aire. Que se concentren en agarrarlas en vez de pelear.]}
