{100}{}{Ves a un necrófago.}
{101}{}{Ves a un necrófago. Tiene un collar de electrochoques.}
{102}{}{¿Nos dejarás ir? ¡Gracias a Dios! Todavía hay gente buena en el mundo.}

{110}{}{Nos capturaron y nos están forzando a recolectar éstas cosas.}
{111}{}{No nos hagas daño, humano. Lo hacemos lo mejor que podemos.}
{112}{}{Uno de nosotros se volvió loco. Es mejor que te escondas de él.}
{113}{}{Estos chatarreros ni siquiera saben para qué son éstas cosas.}

{120}{}{Nos hacen trabajar muy duro.}
{121}{}{¿A ti también te capturaron? Lo siento, compañero.}
{122}{}{Uno de nosotros se volvió loco. Es mejor que te escondas de él.}
{123}{}{Estos chatarreros ni siquiera saben para qué son éstas cosas.}

