{100}{}{Ves a Rutger.}
{101}{}{Ves al líder de los Comerciantes de Ultramar.}

{200}{}{Tuvimos demasiada suerte de que te encontraras cerca. No tengo palabras para expresar mi gratitud por salvarnos. Pero tengo esto, toma este rifle automático como recompensa. ¿Te puedo ayudar en algo más?}
{1200}{}{Tuvimos demasiada suerte de que te encontraras cerca. No tengo palabras para expresar mi gratitud por salvarnos. Pero tengo esto, toma este rifle automático como recompensa. ¿Te puedo ayudar en algo más?}
{201}{}{Me gustaría hablar contigo.}
{202}{}{Parece que tienes cosas que vender. ¿Puedo echar un vistazo?}
{203}{}{Todo esto que ves era para los necrófagos, pero no estaban interesados... }
{204}{}{[Trueque]}
{205}{}{Sí, por cierto, quería comprar unas cosas a los necrófagos. Pero o no quieren dejarlas o piden demasiado dinero. Te pagaré si las encuentras en las ruinas.}
{206}{}{Bueno, ¿qué necesitas?}
{207}{}{No, no me interesa buscar chatarra vieja.}
{208}{}{¿Qué más necesitas?}
{209}{}{Eso es todo. Adiós, Rutger.}
{210}{}{Quiero preguntarte otra cosa.}
{211}{}{Necesito echar un ojo a lo que vendes de nuevo.}
{212}{}{Estoy buscando estos objetos... (te entrega una lista) 1) chip de agua, 2) placa de circuito impreso, 3) placa de diagnósticos, 4) inyector de combustible, 5) planos de vertibird.}
{213}{}{Si encuentro algo, te lo traeré. Adiós.}
{214}{}{Quiero hablarte sobre los objetos que buscas.}
{215}{}{¿Encontraste algo útil?}
{216}{}{Aún nada. Pero si encuentro algo, te lo traeré. Adiós.}
{217}{}{¿Por qué necesitas estos artefactos?}
{218}{}{Mi jefe, Butch, se enojará mucho conmigo si vuelvo con las manos vacías. El Eje necesita todo tipo de cosas. Y no sólo es el Eje, toda California sobrevive gracias a la tecnología antigua. Y con el tiempo, hay menos y menos de ella.}
{219}{}{Ya entiendo.}
{220}{}{¿En dónde puedo encontrar un chip de agua?}
{221}{}{Esa tecnología se usaba en los refugios de Vault-Tec. Sé que había un refugio cerca de San Diego, pero no sé exactamente dónde.}
{222}{}{¿En dónde puedo encontrar una placa de circuito impreso?}
{223}{}{Ese tipo de tecnología sólo se encuentra en las viejas máquinas de imprenta. El Eje quiere imprimir su propio dinero, y para eso, necesitan la imprenta, pero falta la placa.}
{224}{}{¿En dónde puedo encontrar una placa de diagnósticos?}
{225}{}{Es una parte que usan los Auto-Docs, y esos se encontraban en los hospitales.}
{226}{}{¿En dónde puedo encontrar un inyector de combustible?}
{227}{}{Es chistoso, el comerciante de la otra calle dijo que ya consiguió la parte en otro campamento, pero que no la encuentra. El viejo probablemente la perdió entre toda la basura que guarda.}
{228}{}{¿En dónde puedo encontrar los planos del vertibird?}
{229}{}{¿Escuchaste de la base militar en la Isla Coronado y su aeródromo? Ambas fueron hechas pedazos por los ataques nucleares. Pero los necrófagos dicen que había otra fábrica que también creaba equipamiento militar, es posible que los planos estén allí. Y no, no tengo la menor idea de qué es un "vertibird".}
{230}{}{Encontré una de las cosas que querías: }
{231}{}{.}
{232}{}{¡Bien hecho! Ten 400 chapas, lo llevaré al Eje.}
{233}{}{Gracias por las chapas.}
{234}{}{Has completado el contrato de los Comerciantes de Ultramar. ¡Buen trabajo!}
{235}{}{Me alegro de verte.}
{236}{}{Adiós.}
{237}{}{[Continúa la conversación]}
{238}{}{Me alegro de verte... A ti, no al mutante.}
{239}{}{Parece que ya no somos bienvenidos en Dayglow. Tenemos que irnos pronto.}

{240}{}{¿De dónde viene tu caravana?}
{241}{}{Somos del Eje, allí está nuestra oficina central.}
{242}{}{Háblame del Eje.}
{243}{}{Es la ciudad más grande de California, el centro del comercio y creadora de las chapas de botella, además del proveedor principal de agua limpia. Allá están la mayor parte de las personas y las compañías. Pero también tiene la mayor cantidad de problemas.}
{244}{}{Entiendo.}
{245}{}{En Fénix también usan las chapas para comerciar.}
{246}{}{¿También hay chapas en Fénix? ¡Hmm! Las chapas se han usado en el Eje por muchos años, así que alguien tuvo que haber llevado la idea al este. Pero, ¿quién habrá cruzado la divisoria irradiada entre Arizona y California? ¡Qué interesante!}
{247}{}{Tengo otra duda...}
{248}{}{¿Oficina de qué compañía?}
{249}{}{¿De qué compañía eres?}
{250}{}{Somos los Comerciantes de Ultramar, provenimos del Eje. Transportamos bienes de un asentamiento a otro.}
{251}{}{Háblame del Eje.}
{252}{}{Suena a que es un trabajo difícil.}
{253}{}{No te lo imaginas. Durante un tiempo fuimos atacados por supermutantes y todo tipo de escoria. Perdimos mucha gente y brahmanes hasta que una persona los detuvo. El Morador del Refugio - así le llamaban.}
{254}{}{¿De dónde venían los supermutantes?}
{255}{}{Esos bastardos asaltaban caravanas y secuestraban gente para transformarlos en fenómenos iguales a ellos. Nadie en el Eje los conocía, hasta que una persona descubrió su secreto. Todos estaban horrorizados.}
{256}{}{Sigue.}
{257}{}{Ya me sé la historia, no es necesario que sigas.}
{258}{}{Entonces, ese tipo y la Hermandad del Acero atacaron su nido. Pero parte de su ejército sobrevivió y se esparció a través del yermo.}
{259}{}{Gracias por contarme, Rutger. No sabía nada de eso.}
{1259}{}{Gracias por contarme, Rutger. No sabía nada de eso.}
{260}{}{Gracias por contarme, Rutger. Ni siquiera me contaron esto en el Infierno.}
{261}{}{Pero, esos supermutantes, ¿de dónde vinieron?}
{262}{}{¿De qué oficina estamos hablando?}
{263}{}{Algunos asentamientos tuvieron la mala suerte de cruzarse en su camino. Es por eso que seguimos luchando contra ellos durante años. No es ninguna sorpresa que esos bastardos hayan terminado aquí, lejos de los asentamientos humanos.}
{264}{}{¿Qué le pasó al Morador del Refugio?}
{265}{}{No lo sé, parece que desapareció. Desde ese entonces, no se ha sabido nada de él.}
{266}{}{Butler nos prometió grandes cosas. Parece que encontró oro.}

