{100}{}{Ves a un necrófago enloquecido.}
{101}{}{Ves a uno de los necrófagos. Es difícil entender lo que dice.}

{110}{}{Soy un hombre sin corazón. ¡Sin corazón? ¿Sabes por qué? ¿Lo sabes?}
{111}{}{Un monstruo plantó sus raíces en mi corazón. Me comí el corazón. Ya no está.}
{112}{}{Tenemos poco tiempo.}
{113}{}{Tenemos una última oportunidad.}
{114}{}{¿Dónde está mi raspacráneos?}
{115}{}{Todos hemos perdido algo. Todos estamos perdidos.}
{116}{}{Cántame una canción para despedirme.}
{117}{}{Sólo quiero una cosa, ver la luz al fin del camino.}
{118}{}{Descansa en paz, humano.}
{119}{}{Bienvenido al infierno, bebé.}
{120}{}{*susurros*}

