{100}{}{Ves a Donovan.}
{101}{}{Ves a un robot, dentro yace el cerebro de Donovan.}

{110}{}{Ahora soy un robot. Es tan raro. ¡Y tan genial!}
{111}{}{¡Me siento mucho mejor en éste cuerpo!}
{112}{}{Me siento unos cien años más joven.}
{113}{}{Jamás me he sentido tan bien como me siento ahora.}
{114}{}{Creo que todos los necrófagos deberían tener una forma así.}
{115}{}{¡Patéticos humanos, no tienen idea de lo frágiles que son!}
{116}{}{De Santi fue el que intentó matarme. Bendito sea.}
{117}{}{}
{118}{}{}
{119}{}{}
