{100}{}{Ves a Isaac.}
{101}{}{Ves a un necrófago con ropa de trabajo desgastada.}
{102}{}{Parece que tendré que hacerlo todo yo... otra vez.}
{1102}{}{Parece que tendré que hacerlo todo yo... otra vez.}
{103}{}{Buen trabajo... para un normalucho.}
{104}{}{Esto es la sala de máquinas. Espero que todo esté funcionando bien; porque o si no, la estación será inútil.}
{105}{}{Ya casi llegamos, llévame al panel de la habitación de control.}

{200}{}{Jamás pensé que vería a un normalucho por aquí. ¿Será que tienes un grano en el culo?}
{201}{}{Eres nuevo, pero viniste directo a la acción. Así me gusta. Pero ten cuidado, este lugar es peligroso.}
{1201}{}{Eres nueva, pero viniste directo a la acción. Así me gusta. Pero ten cuidado, este lugar es peligroso.}
{202}{}{Me envía el Señor Gustavo. ¿En qué te puedo ayudar?}
{203}{}{¿Y qué haces tú aquí?}
{204}{}{Intentamos lo imposible, hacer que la presa empiece a generar electricidad. Pero hay robots en la corona durante la guerra, y no dejan que nadie entre.}
{205}{}{¿Hacia dónde debes ir?}
{206}{}{Necesito llegar al centro de control, debe estar bajo tierra en algún lado. Intenta encontrar un camino seguro, preferiría que mi cadáver no se convierta en fertilizante.}
{207}{}{Está bien. Pero primero, iré a echar un ojo.}
{208}{}{Entonces ven conmigo, sé como evitar a los robots.}
{209}{}{Primero, dime, ¿qué es este lugar?}
{210}{}{Esta es la Presa Bonita, originalmente fue creada para almacenar agua, pero construyeron la planta eléctrica durante una crisis de combustible líquido. Apenas tiene capacidad para lo que necesita Dayglow, pero no hay ninguna otra estación funcional en la ciudad.}
{211}{}{Necesito llegar al centro de control. Creo que vamos en el camino correcto.}
{212}{}{Esto es el centro de control. Parece que no lo han limpiado en años, no importa, estoy acostumbrado... Esto debe ser el panel de control... Sólo un momento... Ya casi... Listo. Hmm, la estación está inactiva, habrá que trabajar manualmente.}
{213}{}{¿Qué hay que hacer?}
{214}{}{Tenemos que revisar la segunda turbina en la sala de máquinas. Seguramente necesitará mucho esfuerzo.}
{215}{}{Entendido.}
{216}{}{Esto es la sala de máquinas, pero tenemos que llegar al centro de control.}
{217}{}{Espérame aquí.}
{218}{}{Sígueme.}

{220}{}{La represa no será más que una pedazo de concreto hasta que vuelva a funcionar para Dayglow.}
{221}{}{No me digas que estás perdido...}
{1221}{}{No me digas que estás perdida...}
{222}{}{Espérame. Ya vuelvo.}
{223}{}{¿Qué hay que hacer ahora?}
{224}{}{La segunda turbina ya está funcionando.}
{225}{}{Hm, la turbina funciona, ¿pero por qué no hay corriente? Quizás algunos cables se quemaron. Necesito que revises todo el circuito desde la sala de máquinas hasta acá.}
{226}{}{No me digas eso...}
{227}{}{Entendido.}
{228}{}{Parece que ya no hay ninguna fuga eléctrica en el circuito.}
{229}{}{Así es... Enviaré corriente a la subestación... Demonios, no está respondiendo, también tiene que estar inactiva. Tendrás que ir hacia allá y encenderla. Pero recuerda, tienes que enviar la corriente directo hacia San Isidro y el Pueblo Viejo. Corta la corriente hacia todo lo demás.}
{230}{}{¡En camino!}
{231}{}{Me parece que soy yo el que está haciendo todo...}
{232}{}{¡Ay, Bonita! ¿Oyes ese maravilloso chispeo en los transformadores y el zumbido en los cables? Hace años que no escucho algo así. Gracias compadre,espero que Gustavo te recompense bien. Toma, un contador geiger, te será útil de camino a San Isidro.}
{1232}{}{¡Ay, Bonita! ¿Oyes ese maravilloso chispeo en los transformadores y el zumbido en los cables? Hace años que no escucho algo así. Gracias señorita, no lo habría hecho sin usted, espero que Gustavo la recompense bien. Toma, un contador geiger, le será útil de camino a San Isidro.}
{233}{}{Adiós, Isaac.}
{234}{}{Pero, ¿no hay ruinas impenetrables entre la estación y las áreas residenciales?}
{235}{}{¡Muy bien! Eres inteligente, aunque no seas de nuestra época. Somos necrófagos, pero ya activamos varios robots de trabajo y preparamos las líneas eléctricas. No es para tanto.}
