{100}{}{Ves a un Señor MedBot.}
{101}{}{Ves a un robot médico del modelo Señor Medbot.}
{102}{}{¡Wiu, wiu! ¡Hagan paso a los médicos!}

{200}{}{¡Me arrepiento profundamente de no haber salvado a éstas personas!}
{201}{}{Señor, usted corre riesgo al estar aquí.}
{202}{}{Señor, si contrae envenenamiento radioactivo, no seré capaz de ayudarlo.}
{203}{}{Señor, detecto altos niveles de radiación. Debe abandonar el área.}
{204}{}{Lo hago lo mejor que puedo. Pero no puedo resucitar a éstas personas.}
{205}{}{Lo lamento, señor, pero debo ayudar a éstas personas.}
{206}{}{Hay tantos heridos, es como si hubiera estallado una guerra.}
{207}{}{¿Conoce a alguno de los heridos?}
{208}{}{}
{209}{}{Lo siento, me equivoqué de puerta.}

{1200}{}{¡Me arrepiento profundamente de no haber salvado a éstas personas!}
{1201}{}{Señora, usted corre riesgo al estar aquí.}
{1202}{}{Señora, si contrae envenenamiento radioactivo, no seré capaz de ayudarlo.}
{1203}{}{Señora, detecto altos niveles de radiación. Debe abandonar el área.}
{1204}{}{Lo hago lo mejor que puedo. Pero no puedo resucitar a éstas personas.}
{1205}{}{Lo lamento, señora, pero debo ayudar a éstas personas.}
{1206}{}{Hay tantos heridos, es como si hubiera estallado una guerra.}
{1207}{}{¿Conoce a alguno de los heridos?}
{1208}{}{}
{1209}{}{Lo siento, me equivoqué de puerta.}

{210}{}{Tengo una fractura. ¡Ayuda, doctor!}
{211}{}{Oh, eso es muy malo. Necesitas una hospitalización urgente. Por favor, recuéstese, intentaré ayudar.}
{212}{}{[Sigue las instrucciones del MedBot]}
{213}{}{Ya se encuentra mejor. Tenga más cuidado en el futuro.}
{214}{}{Gracias.}
{215}{}{¿Puedes curarme?}
{216}{}{Por supuesto. Soy un asistente médico. Pero en éste momento mis capacidades están limitadas por la falta de suministros médicos. ¿Puedo ayudarte con algo?}
{217}{}{No, hoy no..}
{218}{}{¡De ninguna manera! No le confiaré mi vida a una máquina descerebrada.}
{219}{}{El Soldado Gomer tiene una herida seria. ¿Podrías ayudarlo?}
{220}{}{El Soldado Gomer se encuentra mejor.}
{221}{}{Gracias.}

