{100}{}{Ves a un necrófago chatarrero.}
{101}{}{Ves a un necrófago. Está inspeccionando el área minuciosamente.}
{102}{}{Oye, amiguito, ¿Tienes fuego? Hay mucha basura aquí, pero no hay ningún encendedor...}
{1102}{}{Oye, amiguita, ¿Tienes fuego? Hay mucha basura aquí, pero no hay ningún encendedor...}
{103}{}{¡Fuego! ¡Fueeegooo!}
{104}{}{Creo que un solo encendedor es suficiente para ti.}

{200}{}{¡El fuego vino desde el cielo! ¿Lo ves? Todo arde. ¡Todo! ¡Incluso la piedra arde!}
{201}{}{Estás loco. ¡Despierta!}
{202}{}{¿Yo, loco? No, no. El fuego de la Gran Guerra todavía arde. Arde en mi corazón. Y cada vez que veo hasta la menor chispa, lo recuerdo. Es imposible olvidarlo. Así que quiero... recordar una vez más. ¡Mira, está ardiendo! ¡Y arde bien!}
{203}{}{Puedo ver que ésto te está gustando. ¿No quieres compartir un poco del fuego con los demás?}
{204}{}{El fuego es realmente encantador.}
{205}{}{¿También te gusta el FUEGO? El fuego de la Gran Guerra todavía arde. Arde en mi corazón. Y cada vez que veo hasta la menor chispa, lo recuerdo. Es imposible olvidarlo. Así que quiero... recordar una vez más. ¡Mira, está ardiendo! ¡Y arde bien!}
{206}{}{¡Ahora puedes crear tu propio fuego!}
{207}{}{Eh, claro, por supuesto.}
{208}{}{De hecho, sí quiero empezar un pequeño incendio. ¿Tienes alguna cosa inflamable?}
{209}{}{Creo que me iré mientras juegas con el encendedor. Adiós.}
{210}{}{¿Te gustan las llamas?}
{211}{}{Definitivamente necesitas las llamas. Todos las necesitamos.}
{212}{}{El fuego purifica. Te quita todo lo que alguna vez tuviste. Crea un vacío. ¿No es eso maravilloso?}
{213}{}{Te guste o no, me llevaré todo el combustible que tengas.}
