{100}{}{Ves a un necrófago.}
{101}{}{Ves a uno de los necrófagos. Parece estar más abatido de lo normal.}

{102}{}{Hola. ¿De dónde apareció un guapo como tú?}
{1102}{}{Hola. ¿De dónde apareció una hermosura como tú?}
{103}{}{Hola, amigo. Ten cuidado allá afuera.}
{1103}{}{Hola, amiga. Ten cuidado allá afuera.}
{104}{}{¡Sálvame de estos mutantes pendejos!}
{105}{}{La última vez que me hicieron eso fue antes de la guerra. En ese entonces eran matones, ahora son los mutantes, todo sigue igual.}
{106}{}{Ay, pensé que estaba acabado. Ten, un estimulante y mi eterna gratitud. Gracias, amigo.}
{1106}{}{Ay, pensé que estaba acabado. Ten, un estimulante y mi eterna gratitud. Gracias, amiga.}

{110}{}{¡No me toques, somos de la misma sangre!}
{111}{}{No le diré a nadie que los vi. En serio.}
{112}{}{¡En la cara no! Me queda un sólo diente...}
{113}{}{¡Déjenme en paz!}
{114}{}{¡No tengo nada para comer!}
{115}{}{¡Alguien, socorro!}
{116}{}{¿Qué quieren de mí?}
{117}{}{Ya te lo dije, no tengo nada de comida.}
{118}{}{¿Quizás deberían ir a cazar al yermo?}
{119}{}{Chicos, seamos amigos, ¿Ya?}

