{100}{}{Ves a la Abuela Judy.}
{101}{}{Ves a una necrófaga con un vestido de la preguerra.}
{102}{}{¡Ah-h!}
{103}{}{Ya sé lo que estaba haciendo Rupert. Pero... lo perdonaré, al menos por esta vez.}

{200}{}{Hola, forastero. Hay más y más caras nuevas aquí en Dayglow.}
{1200}{}{Hola, forastera. Hay más y más caras nuevas aquí en Dayglow}
{201}{}{Así es. Adiós.}
{202}{}{¿Quién eres?}
{203}{}{Soy la Abuela Judy. Vine aquí desde Necrópolis, igual que los demás necrófagos.}
{204}{}{Ya veo. Adiós, abuela.}
{205}{}{¿Qué haces aquí, Judy?}
{206}{}{Cada día visito a Gustavo para saber de los recién llegados o de los fallecidos. Después de todo, es el que manda en el ayuntamiento. Si necesitas encontrar a alguien, ese es el sitio adecuado.}
{207}{}{¿Qué piensas de Gustavo?}
{208}{}{¡Ay, ese jovenzuelo es tan dulce! Cuida mejor a sus guardias que a sí mismo. Siempre nos ha faltado gente como él.}
{209}{}{¿A quién estás buscando?}
{210}{}{Durante el viaje, yo y mi esposo Rupert nos separamos. Ahora no puedo encontrarlo, pero Cabot en el Pueblo Viejo dijo haberlo visto.}
{211}{}{Lamento oír eso. Nos vemos.}
{212}{}{Te ayudaré a encontrarlo.}
{213}{}{¡Eres tan encantador! Aceptaré cualquier ayuda.}
{1213}{}{¡Eres tan encantadora! Aceptaré cualquier ayuda.}
{214}{}{Empezaré mi búsqueda en el Pueblo Viejo, supongo. Hasta luego, Judy.}
{215}{}{¿Me puedes repetir en dónde viste a tu esposo por última vez?}
{216}{}{Mi nombre es Judy. Puedes llamarme Abuela, corazón. Vine de Necrópolis, como los demás necrófagos.}
{217}{}{Sé fuerte, Abuela. Tu esposo Rupert murió, fue en un tiroteo en medio de Little Italy.}
{218}{}{¡No! ¡Pude sentirlo! (se agarra el corazón) ¡Ay!}
{219}{}{Oye, ¿Estás bien?}

{220}{}{Hola, forastero.}
{1220}{}{Hola, forastera.}
{221}{}{Adiós, Abuela.}
