{100}{}{Ves a un supermutante Nocturno.}
{101}{}{Ves a un supermutante con equipamiento de combate.}
{102}{}{Los nocturnos siempre seremos leales al Maestro. Incluso si los normales nos dejan en paz.}

{200}{}{Oye, humano, guarda el arma. Nosotros no hacerte daño si tú no atacar.}
{201}{}{Oye, compañero, no nos temas. Tú dejarnos solos, nosotros dejarte sólo.}
{202}{}{¿Por qué estás siendo tan amable?}
{203}{}{¿Por qué debería confiar en ti?}
{204}{}{Estar cansados de guerra. ¡Sólo querer que humanos dejen de atacarnos!}
{205}{}{Ya veo. Bueno, adiós.}
{206}{}{No te quedes mirando, pequeñito. A mí no gustar que me miren.}
{207}{}{Lo que digas.}
{208}{}{}
{209}{}{}

{210}{}{Dime, ¿es verdad que echaron a Gomer de su escuadrón?}
{211}{}{¿Gomer? Nosotros no querer escuchar de él. ¡Traidor! No es leal a nosotros. No excusa para eso.}
{212}{}{Él puede redimirse.}
{213}{}{No poderse. Gomer tonto, ni poder llevar arma grande. Muy malo que capitán no estar aquí para gritarle...}
{214}{}{¿Qué le pasó al capitán?}
{215}{}{Soldados de Hermandad atraparlo. Nos da vergüenza. Ahora herirlo en lugar de la frontera cerca de San Isidro.}
{216}{}{¿Y por qué están sentados en vez de ir a rescatarlo?}
{217}{}{¡Porque ser trampa, humano tonto! Hermandad querer atraparnos a todos. Capitán dijo cuando se fue: no ayudarlo.}
{218}{}{¡Son unos idiotas! Si fuera tú, haría todo lo posible para rescatarlo. Vámonos Gomer, dejemos a estos perdedores.}
{1218}{}{¡Son unos idiotas! Si fuera tú, haría todo lo posible para rescatarlo. Vámonos Gomer, dejemos a estos perdedores.}
{219}{}{Lo entiendo, una orden es una orden. Vamos, Gomer, tenemos que hablar.}
{220}{}{¡Son unos idiotas! Si fuera tú, haría todo lo posible para rescatarlo. Adiós, perdedores.}
{1220}{}{¡Son unos idiotas! Si fuera tú, haría todo lo posible para rescatarlo. Adiós, perdedores.}
{221}{}{Lo entiendo, una orden es una orden.}
{222}{}{El capitán ha muerto. No pude salvarlo de la Hermandad.}
{223}{}{Eso pensé.}
{224}{}{¿Qué harán sin el capitán?}
{225}{}{¿Eso es todo lo que vas a decir? ¿Ninguna pataleta enojado o algún grito animalístico? ¿Siquiera saben cómo sobrevivir sin el capitán?}
{226}{}{He rescatado al capitán. De nada.}
{227}{}{Nosotros no pedir ayuda, pero tú ayudar. ¿Tú pensar que humanos y mutantes poder ser amigos? Imposible. Pero gracias, nosotros te mostraríamos a Maestro.}
{228}{}{¿Qué es lo que harán ahora?}
{229}{}{¿Qué planes tienen para el futuro? ¿O van a seguir sentados en medio del parque?}
{230}{}{Ir al este. Ellos no saber de nosotros todavía. Lejos de Hermandad y otras personas.}
{231}{}{Pero el capitán está con ustedes, ¿por qué no se van y ya?}
{232}{}{Pero el capitán ya no está con ustedes, ¿por qué no se van y ya?}
{233}{}{Entonces les deseo buena suerte.}
{234}{}{Claro. No es necesario arruinarle la tarde a la gente normal. Ojalá que ya no molesten a nadie.}
{235}{}{¿Y qué hay de Gomer? ¿Dejarán que vaya con ustedes?}
{236}{}{Si quiere, él venir de vuelta con grupo.}
{237}{}{Bueno, al menos tiene la opción.}

