{100}{}{Ante ti hay un necrófago.}
{101}{}{Ves a un necrófago común y corriente.}

{200}{}{Oye, pequeñín, ¿Quieres que te cuente una historia?}
{1200}{}{Ay, señorita, ¿Quiere que le cuente una historia?}
{201}{}{¿Sí? ¡Pues no te la voy a contar! Te la creíste, ¿Cierto?}
{1201}{}{¿Sí? ¡Pues no te la voy a contar! Te la creíste, ¿Cierto?}
{202}{}{Bueno, si de verdad quieres que te cuente algo, tráeme cervezas.}
{1202}{}{Bueno, si de verdad quieres que te cuente algo, tráeme cervezas.}

{210}{}{Vivía en el alcantarillado cuando cayeron las bombas. Tuve que subsistir en ratas y agua estancada. No valió la pena, en serio.}
{211}{}{El Maestro solía ser nuestro líder. Mandaba a todos los necrófagos con un puño de hierro. Por suerte, ya no está con nosotros.}
{212}{}{Incluso antes de la Gran Guerra, el petróleo ya se había acabado. Eso me hace pensar, ¿Por qué estábamos peleando, para empezar?}
{213}{}{Allá para el norte, hay unos asentamientos grandes. Pero no es nada comparado a las ciudades que habían antes de la guerra.}
{214}{}{El Maestro y sus supermutantes iban en serio. Intentaron dominar a los humanos y a los necrófagos. Es bueno que ya no estén, pero no del todo, ¿Cierto?}
{215}{}{Puaj... Demasiada cerveza... Se acabó la entrevista...}

