{100}{}{Ves a Kurt.}
{101}{}{Ves a un necrófago sin nada fuera de lo común.}
{102}{}{¡No tengo chapas! ¡NADA! ¡NI UNA!}
{103}{}{¡BASTA! ¡BASTA! Aquí tienes las chapas. ¡Pero deja de golpearme!}
{104}{}{¡BASTA! ¡BASTA! Ten todas mis chapas. ¡Ya no tengo más!}
{105}{}{Kurt se ha rendido.}
{106}{}{Espera un segundo, ¿Qué es lo que quieres?}
{107}{}{¡Vaya desastre!}

{200}{}{¡Me siento genial hoy! Hace tiempo que no me relajo así... Espera, ¿Qué quieres?}
{201}{}{¿Quién eres?}
{202}{}{Me llaman Kurt. ¿Por qué?}
{203}{}{Te estaba buscando. Estoy aquí por tu deuda al Sr. De Santi.}
{204}{}{El Sr. De Santi está furioso, ¿cierto? ¡Entonces déjalo así! El servicio que ofrece es terrible, su hospedaje es igual de horrendo, no le voy a pagar. Además, un necrófago que extorsiona a otro, ¡Qué desgracia! ¿No puede ver que intentamos establecer el comunismo por aquí? ¿No es obvio?}
{205}{}{Te lo estás inventando. ¡Dame las chapas!}
{206}{}{El Sr. De Santi no te dejará tranquilo.}
{207}{}{¡No te daré una sola chapa! Si quiere dinero, ¡Te lo puede quitar a ti!}
{208}{}{Entonces tendré que tomarlas a la fuerza. ¡Dame tu dinero!}
{209}{}{Está bien, lo pagaré yo.}
