{100}{}{Ves a un forastero.}
{101}{}{Ves a un hombre en un mono del refugio.}

#Cutscenes
{110}{}{   }
{111}{}{¿Quiénes son ustedes?}
{112}{}{No es asunto tuyo, cara podrida. Le harás esas preguntas a Butler, ahora vete.}
{113}{}{Mercenarios, entonces. Es obvio que Butler no se echaría para atrás tan fácilmente.}
{114}{}{Pero llegaron muy tarde, Coronado le pertenece a los necrófagos de San Isidro. Ustedes no tienen lugar aquí.}
{115}{}{¡Tch! Estos idiotas no hacen más que darnos asco. ¡Tírenlos al agua, muchachos!}

{122}{}{No es asunto tuyo, cara podrida. No dejaremos que nadie vaya a la isla sin nuestro permiso.}
{123}{}{Ah, chatarreros. Claro, todos quieren aprovecharse de Coronado.}
{124}{}{¡Pero Coronado le pertenece a TODOS los necrófagos! ¡San Isidro también merece su parte!}
{125}{}{¡Tch! Éstos idiotas no hacen más que darnos asco. ¡Tenemos que echarlos!}
{126}{}{¡Pero Coronado le pertenece a los NECRÓFAGOS! ¡Fuera de nuestra ciudad, normaluchos!}

#Final Dialogue
{200}{}{¡Oye, oye! ¿Estás bien? ¡Despierta!}
{201}{}{¿Qué...? ¿Qué pasó?}
{202}{}{Quedaste inconsciente con la explosión, pero parece que estás bien. Temía que no recibieras mi invitación.}
{1202}{}{Quedaste inconsciente con la explosión, pero parece que estás bien. Temía que no recibieras mi invitación.}
{203}{}{Hubo una pelea, alguien lanzó una granada y quedaste inconsciente con la explosión, pero parece que estás bien. Temía que no recibieras mi invitación.}
{1203}{}{Hubo una pelea, alguien lanzó una granada y quedaste inconsciente con la explosión, pero parece que estás bien. Temía que no recibieras mi invitación.}
{204}{}{¿Y quién eres tú?}
{205}{}{Puede que hayas oído hablar de mí, pero eso no importa. Me alegra que hayas podido completar la misión.}
{1205}{}{Puede que hayas oído hablar de mí, pero eso no importa. Me alegra que hayas podido completar la misión.}
{206}{}{¿Crees que hice lo correcto?}
{1206}{}{¿Crees que hice lo correcto?}
{207}{}{No estoy aquí para juzgarte por tus acciones. Hiciste lo que creíste correcto.}
{1207}{}{No estoy aquí para juzgarte por tus acciones. Hiciste lo que creíste correcto.}
{208}{}{[Sigue escuchando]}
{209}{}{}

{210}{}{Es obvio que los necrófagos estarán muy molestos, los restos del Viejo Mundo ya no serán suyos.}
{211}{}{Quizás le pudieron haber sido útiles al mundo. Pero también podrían haber caído en las manos equivocadas.}
{212}{}{Quién sabe, quizás gracias a esa explosión el mundo evitó otra catástrofe. O quizás la base contenía lo necesario para poner a la humanidad en marcha otra vez. De todas formas, la base ya está destruida. Y gracias a ello, la fuente de los problemas entre necrófagos.}

{220}{}{Es obvio que habrán desacuerdos entre los necrófagos sobre el derecho a los restos del Viejo Mundo.}
{221}{}{Gustavo intentará reclamar todo como suyo y usarlo para el desarrollo de San Isidro. No lo compartirá con los asentamientos humanos, que también necesitan la tecnología desesperadamente. Butler intentará detenerlo.}
{222}{}{Al final, Gustavo será más fuerte y atraerá a los demás necrófagos a su lado. Y entonces Dayglow vivirá su vida habitual, monótona y pacífica, aislada del resto del mundo. Como muchos necrófagos deseaban.}
{223}{}{Gustavo intentará reclamar todo como suyo y usarlo para el desarrollo de San Isidro. No lo compartirá con los asentamientos humanos, que también necesitan la tecnología desesperadamente.}
{224}{}{Entonces Dayglow vivirá una vida xenofóbica. Tal como muchos necrófagos querían.}

{230}{}{Obviamente habrá discordia entre los necrófagos sobre el derecho a los restos del viejo mundo.}
{231}{}{Butler iniciará el comercio activo con los asentamientos humanos del norte. Para algunos, los objetos de la preguerra salvarán sus vidas, y para otros serán terribles. San Isidro sólo se quedará con las migajas, por lo que se convertirá en un tugurio.}
{232}{}{Y gradualmente, los recursos de la isla se acabarán. Pero gracias al comercio la ciudad sobrevivirá, y Dayglow tendrá su vida habitual, monótona y pacífica. Como muchos necrófagos lo querían.}

{240}{}{Es obvio que los necrófagos estarán muy molestos, los restos del Viejo Mundo ya no serán suyos.}
{241}{}{La Hermandad del Acero no dejará que nadie ponga un pie en su mina de oro. Se llevarán todo lo que sea valioso a su cuartel general.}
{242}{}{Los necrófagos solo tendrán las migajas, y con el tiempo, la gente se olvidará de ellos. Y entonces Dayglow volverá a su vida habitual, por monótona que sea.}

{250}{}{Obviamente habrán muchos problemas entre los necrófagos sobre el derecho a los restos del Viejo Mundo.}
{251}{}{Sin líderes, les llevará mucho tiempo encontrar un compromiso mutuo entre fuerzas e intereses distintos. Serán tiempos confusos llenos de caos, incluso en los asentamientos humanos del norte.}
{252}{}{Algunos de los objetos de la preguerra caerán en buenas manos, y otros en las malas. Los necrófagos recibirán lo menos posible, pero ya están acostumbrados. Dayglow se convertirá en lo que fue Necrópolis antes de que los necrófagos la abandonaran. Parece que ese es su destino.}

{260}{}{Bueno, ya no tengo nada que hacer aquí, seguramente tú tampoco. Fue bueno verte, compadre. Adiós.}
{1260}{}{Bueno, ya no tengo nada que hacer aquí, seguramente tú tampoco. Fue bueno verla, señorita. Adiós.}
{261}{}{Adiós, forastero.}

