{100}{}{Ves a un necrófago viejo.}
{101}{}{Ves a un necrófago solitario. Si no fuera por su aspecto espantosamente descompuesto, parecería un tipo bastante amistoso.}
{102}{}{Los de la frontera te andan buscando. No te ayudaré, ni por una montaña de chapas.}
{103}{}{¿Cómo te enteraste del pasaje secreto? ¡Ni siquiera Tobias sabía de él!}
{1103}{}{¿Cómo te enteraste del pasaje secreto? ¡Ni siquiera Tobias sabía de él!}

#Introduction
{200}{}{(A primera vista, parece que hay un cadáver en la silla. Pero conforme te acercas, el cadáver sube su cabeza lentamente y, con voz ronca y arrastrada, dice) ¿Por qué estás aquí, normalucho?}
{201}{}{Busco una forma de entrar a Dayglow.}
{202}{}{Nuestra ciudad sólo admite a los muertos. Los vivos no tienen lugar aquí.}
{203}{}{Ah, entonces no entro. Adiós.}
{204}{}{Y aún así, quiero entrar.}
{205}{}{No intentaré disuadirte. Pero dudo que Tobias te deje pasar la frontera.}
{206}{}{Entonces intentaré convencerlo. Nos vemos, viejo.}
{207}{}{¿Habrá otra forma de entrar?}
{208}{}{Los demás caminos son extremadamente peligrosos. Pero no es necesario ir tan lejos. Conozco un atajo. Puedo llevarte, pero no es gratis. ¿Cuántos chapas tienes? ¿Ustedes también las usan, verdad? Al menos, en el Eje sí.}
{209}{}{¿El Eje?}
{210}{}{Me estás sugiriendo algo claramente ilegal. No voy a ir TAN lejos. Adiós.}
{211}{}{¡El Eje! ¡La ciudad que inventó las chapas de botella! Establecieron la chapa como moneda de cambio para reemplazar el dinero de la preguerra. ¿Cuántas chapas tienes?}
{212}{}{No tengo ni una sola chapa.}
{213}{}{No tengo ni una sola chapa.}
{214}{}{Mientes, sé que trajiste chapas. ¿Cómo, preguntarás? (coloca un dedo en su frente) Visión de rayos X. Jeje, bromeo.}
{1214}{}{Mientes, sé que trajiste chapas. ¿Cómo, preguntarás? (coloca un dedo en su frente) Visión de rayos X. Jeje, bromeo.}
#Note: In reality, it's not X-ray vision, the ghoul guide just studied the PC and their belongings while they slept at one of the campsites.
{215}{}{Estás loco, viejo. Mejor me voy.}
{216}{}{Ya, ten TODAS mis chapas. ¡Ahora llévame a la ciudad!}
{217}{}{Entonces, baja la cabeza... No te preocupes, te la quitaré cuando lleguemos a la ciudad. Confía en mí. Jeje, no eres el primero al que paso por la frontera.}
{1217}{}{Entonces, baja la cabeza... No te preocupes, te la quitaré cuando lleguemos a la ciudad. Confía en mí. Jeje, no eres la primera que paso por la frontera.}
{218}{}{Agh... Bueno. Pero ten cuidado.}
{219}{}{Ni siquiera pienses en engañarme, viejo.}
{220}{}{Te creo. Pero muy estúpido pasar la frontera totalmente quebrado. ¿Qué voy a hacer contigo? Bueno, tráeme tres latas de una buena y vieja cerveza Mexicana. Todavía se encuentran en Tijuana, al oeste.}
{221}{}{De verdad espero que estén por allá.}
{222}{}{¿Y qué tal cinco botellas de Nuka-Cola irradiada? Las encontré en las ruinas.}
{223}{}{Tengo cinco botellas de Nuka-Cola normal. ¿Te sirve?}
{224}{}{Aquí tienes las tres latas.}
{225}{}{Trato hecho. Parece que no puedo sacarte nada más.}
{226}{}{¿Entonces me llevarás a la ciudad?}
{227}{}{¿Encontraste lo que te pedí?}
{228}{}{No. Quizás miré en el sitio equivocado. Intentaré ir a las ruinas otra vez.}
{1228}{}{No. Quizás miré en el sitio equivocado. Intentaré ir a las ruinas otra vez.}
{229}{}{}
{230}{}{¿Todavía no pasas la frontera, verdad? Sé de un atajo. Puedo llevarte, pero no es gratis. ¿Cuántas chapas tienes?}
{231}{}{¿Ya te vas de Dayglow? Bueno, ya era hora.}
{232}{}{Adiós.}
{233}{}{(Ves a un viejo sentado en su silla; lentamente sube su cabeza, mostrando su desfigurado rostro; en una ronca y arrastrada voz, dice) ¡Ah, sangre fresca! Es bueno verte en nuestro reino de los muertos. Si necesitas pasar, habla con Tobias, estará contento de verte.}
{234}{}{Me pondré con eso. Adiós.}
{235}{}{¿Quién es Tobias?}
{236}{}{Tobias es el guardián de la entrada a la ciudad. Se podría decir que es el mediador entre el mundo de los vivos y el de los muertos.}
