{102}{}{Este emisor no tiene energía.}
{103}{}{El emisor es inútil ahora mismo.}
{104}{}{Este emisor está gravemente dañado.}
{105}{}{Has conseguido arreglar el emisor. Está listo para ser usado.}
{106}{}{¡El emisor está dañado!}
{107}{}{Un fuerte pulso viaja a través del piso y se expande por el área, dañando todo lo electrónico en su camino.}
{108}{}{El emisor está dañado.}
{109}{}{El emisor ya está cargado.}
{110}{}{Ya cargaste la batería del emisor.}
{111}{}{El emisor se quemó gracias a su propio voltaje.}
