{100}{}{Tienes una máquina de arcade en frente tuyo.}
{101}{}{Ves una maquinita estilo arcade. Es un clásico.}
{102}{}{Para empezar a jugar, debes pagar. Récord actual: }
{103}{}{ (Desconocido).}
{104}{}{ (}
{105}{}{).}

{200}{}{"Tu nave espacial se dirige al centro de la galaxia. ¡Cuidado! ¡Se aproxima un campo de asteroides! Esquívalos al moverte hacia arriba o hacia abajo, o dispara cargas de plasma para destruirlos. ¡Entre más sobrevivas, más puntos obtienes!"}
{201}{}{¡Adelante!}
{202}{}{Lee las reglas.}
{203}{}{Rechaza y toma tu dinero de nuevo.}
{204}{}{Rechaza.}

{210}{}{Controla la nave (  }
{211}{}{) para evitar la colisión con los asteroides (}
{212}{}{). Chocar un asteroide te quita una vida. Esquiva los asteroides subiendo o bajando, pero sólo entre las tres líneas.}
{213}{}{}
{214}{}{También puedes recolectar puntos (}
{215}{}{) y cargas de plasma (}
{216}{}{) durante el viaje. Una carga de plasma puede destruir un obstáculo, y un superdisparo despeja toda la línea. Obtener una vida extra (}
{217}{}{) es una gran fortuna.}
{218}{}{Cerrar el menú de ayuda.}
{219}{}{Siguiente.}

# Do not remove spaces in the lines!
{220}{}{-|>  }
{221}{}{ [X] }
{222}{}{ -o- }
{223}{}{ -z- }
{224}{}{ ---}
{225}{}{ -Y-}
{226}{}{) }
{227}{}{ -Z-}
{228}{}{(}

{230}{}{Arriba.}
{231}{}{Adelante.}
{232}{}{Abajo.}
{233}{}{-Arriba-}
{234}{}{-Abajo-}
{235}{}{¡Disparo! (}
{236}{}{-¡Disparo!-}
{237}{}{¡Superdisparo!}
{238}{}{)}
{239}{}{¡Explosión! (}

{240}{}{Pausa.}
{241}{}{Juego pausado. Vida: }
{242}{}{. Cargas: }
{243}{}{. Puntos: }
{244}{}{. Tu récord: }
{245}{}{.}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{-Explosión-}

{250}{}{Seguir jugando.}
{251}{}{Terminar la partida.}
{252}{}{¿Estás seguro de que deseas terminar la partida y perder tus puntos acumulados (}
{253}{}{)?}
{254}{}{Regresar y seguir con la partida.}
{255}{}{Sí. Terminar la partida.}
{256}{}{¡Perdiste!}
{257}{}{¡Qué basura de juego! Ya no quiero jugar.}
{258}{}{Está bien. Me irá mejor la siguiente vez.}
{259}{}{}

{260}{}{}
{261}{}{Rechazar. No necesito ninguno de estos premios.}
{262}{}{Fuerza +1.}
{263}{}{Percepción +1.}
{264}{}{Resistencia +1.}
{265}{}{Carisma +1.}
{266}{}{Inteligencia +1.}
{267}{}{Agilidad +1.}
{268}{}{Suerte +1.}
{269}{}{Apostar +20.}
{270}{}{"¡Victoria! Has batido tu propio récord. ¿Deseas continuar?"}
{271}{}{Sí.}
{272}{}{No.}
{273}{}{Habilitar modo supervivencia.}
{274}{}{Deshabilitar modo supervivencia.}
{275}{}{}
{276}{}{"¡Victoria! Has batido el récord y te has convertido en el campeón supremo."}
{277}{}{¡Genial!}
{278}{}{Por fin.}
{279}{}{"Reclama tu cupón de premios."}
{280}{}{"Ahora puedes jugar en ésta máquina de forma gratuita. Y eso no es todo, si el juego te pareció muy fácil, puedes habilitar el modo supervivencia. ¡Buena suerte en el espacio!"}
{281}{}{Bien.}
{282}{}{¿En serio?}
{283}{}{En el modo supervivencia, transiciones entre las líneas (arriba y bajo) cuentan como pasos del vuelo. Por lo tanto, debes recordar el estado de las líneas y planear tus movimientos bien.}
{284}{}{Leer más.}
{285}{}{Entendido.}
{286}{}{Pero, obtienes el doble de vidas y cargas al inicio, el camino es visible dos pasos hacia adelante, y el disparo explosivo destruye no sólo el asteroide de al frente, sino también los de las líneas de al lado.}
{287}{}{Además, obtienes 1 punto por cada paso que tomes. Puedes intercambiar tus puntos.}
{288}{}{}
{289}{}{}

{290}{}{Intercambiar puntos.}
{291}{}{Tienes }
{292}{}{ puntos.}
{293}{}{Seguir con la partida.}
{294}{}{1 disparo por }
{295}{}{1 superdisparo por }
{296}{}{1 vida por }
{297}{}{.}
{298}{}{El derecho a estudiar los caminos hasta el siguiente movimiento por }

