{100}{}{Esta es la computadora de la subestación.}
{101}{}{Ves la computadora que controla la subestación.}
{102}{}{La computadora no enciende.}
{103}{}{Parece que no le está llegando corriente.}

{200}{}{El sistema funciona correctamente. Introducir comando.}
{201}{}{Deja a la computadora en paz.}
{202}{}{¿Cuál es el estado de la planta eléctrica?}
{203}{}{La planta eléctrica no responde.}
{204}{}{¿Cuál es el estado de la subestación?}
{205}{}{La subestación no responde.}
{206}{}{Regresar}
{207}{}{Encender la iluminación exterior de la estación.}
{208}{}{Se han encendido las luces exteriores.}
{209}{}{Encender la iluminación interior de la estación.}
{210}{}{Se han encendido las luces interiores.}
{211}{}{Cancelar la alarma}
{212}{}{Alarma cancelada.}
{213}{}{Cancelar modo de combate para los robots}
{214}{}{¡Cuidado! Se ha cancelado el modo de combate. Todos los robots de seguridad seguirán el protocolo pasivo.}
{215}{}{Enviar robots a reparar la red del monorriel.}
{216}{}{Se ha reparado la red del monorriel.}

