{100}{}{Ves la palanca de los fusibles.}
{101}{}{De acuerdo a las instrucciones, este interruptor de alguna forma transmite corriente a la subestación.}
{110}{}{Bajas la palanca, pero no pasa nada.}
{111}{}{Esto ya no es necesario.}
{112}{}{Bajas la palanca. Responde con un profundo zumbido que causa un eco en todo la habitación.}
{113}{}{Bajas la palanca. El cartel a su lado se enciende con el mensaje "FUGA ELÉCTRICA".}
