{110}{}{La subestación no tiene energía. No le está llegando la corriente.}
{111}{}{La subestación funciona como debería.}
{112}{}{Siguiendo las instrucciones, bajas todas las palancas exceptuando un par. Ahora la corriente se dirige exactamente a donde debe.}
{113}{}{Bajas varias palancas, pero no ocurre nada.}
{114}{}{La subestación actualmente está desconectada de la red eléctrica.}

{200}{}{(En frente tuyo se encuentra un panel enorme con varios enchufes.)}
{201}{}{[SALIR]}
{202}{}{Hmm. ¿A qué enchufes debería conectar los cables?}

{210}{}{Enchufe }
{211}{}{8AVI}
{212}{}{W7VE}
{213}{}{PA3L}
{214}{}{ACM4}
{215}{}{SFX1}
{216}{}{2LIP}
{217}{}{DAT5}

{220}{}{Conectar.}
{221}{}{Desconectar.}
{222}{}{[REGRESAR]}
{223}{}{ (desconectado)}
{224}{}{ (conectado)}

{230}{}{Enciende la subestación con la palanca principal.}
{231}{}{Algo salió mal. El fusible activó el cortacircuitos.}
{232}{}{Ay. A intentarlo de nuevo.}

{250}{}{Hay algunas notas escritas aquí:}
{251}{}{San Isidro}
{252}{}{National City}
{253}{}{Chula Vista}
{254}{}{Pueblo Viejo}
{255}{}{Rancho Otay}
{256}{}{La Mesa}
{257}{}{Mesa Otay}
{258}{}{ - }
{259}{}{}
{260}{}{Tablón de anuncios}
{261}{}{Alguien anotó algunas cosas aquí. Mirarlo de reojo no te dará ninguna pista.}
{262}{}{Estas notas ya no son útiles.}

