{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{El sistema es demasiado complicado para ti.}
{205}{}{Ayudaría encontrar un manual... o un instructor.}
{206}{}{Necesitas usar un método más científico.}
{207}{}{Ya sabes qué hacer.}
{208}{}{¡Bueno, no era tan difícil!}
{209}{}{Esta tecnología es demasiado compleja. Necesitas estudiarla más de cerca.}

{210}{}{Verificar estado del sistema.}
{211}{}{Verificar estado de la Turbina 1.}
{212}{}{Turbina 1: no hay señal.}
{213}{}{Turbina 1: activa.}
{214}{}{Verificar estado de la Turbina 2.}
{215}{}{Turbina 2: no hay señal.}
{216}{}{Turbina 2: activa.}
{217}{}{Verificar estado de la subestación.}
{218}{}{Subestación: no hay señal. }
{219}{}{Subestación: operacional. }
{220}{}{Dirigir corriente a la subestación.}
{221}{}{Hecho.}
{222}{}{La subestación no responde.}
{223}{}{Encender la iluminación de la habitación de las máquinas}
{224}{}{Apagar la iluminación de la habitación de las máquinas}
{225}{}{Encender la iluminación del centro de control}
{226}{}{Apagar la iluminación del centro de control}
{227}{}{Abrir la puerta al almacén}

