{100}{}{Ahora puedes descender a la oscuridad de las profundidades.}
{101}{}{Es difícil de decir por qué falta la escalera. Pero no la hay.}
{102}{}{No puedes arreglar algo que no existe. Necesitas encontrar un sustituto para la escalera.}
{103}{}{A través de la rejilla, observas un profundo conducto de ventilación.}
{104}{}{No hay nada que reparar aquí. Al contrario, el agujero en la rejilla podría serte de ayuda.}
{105}{}{No es posible reparar el puente. Pero podrías bajar desde aquí si tienes una cuerda.}
{106}{}{No puedes hacer nada con esto si tienes las manos vacías.}
{107}{}{Ya puedes bajar.}
{108}{}{Podrías bajar por aquí si tienes una cuerda larga y fuerte.}
