{110}{}{Hay un tipo de ruido que viene del sistema de ventilación. Parece que es su forma de expresar agonía.}
{111}{}{La ventilación por fin se ha callado. Descansa en paz, hijo de la revolución industrial.}
{112}{}{La ventilación tenía amontonada una capa de ceniza tóxica, la cual raspaste y metiste en una lata. Como muestra de gratitud, la ventilación dejó de hacer ese horrendo alboroto.}
{120}{}{*Shhh*}
{121}{}{*Clang*}
{122}{}{*Golpazo*}
{123}{}{*Traqueteo*}
{124}{}{*Crack*}
