{100}{}{Ves una computadora de imprenta.}
{101}{}{Esta computadora está conectada a la imprenta.}
{102}{}{Leer los artículos del siglo anterior fue una experiencia nueva}

#Dialogue
{200}{}{Acceso concedido. Introduzca comando:}
{201}{}{Cerrar sesión.}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Regresar al menú principal}
{205}{}{Cancelar}

{210}{}{Lee los encabezados de los últimos artículos.}
{211}{}{Artículos listos para la imprenta}
{212}{}{Noticias financieras}
{213}{}{"México ha recibido un nuevo cargamento de los robots Sr. Mañoso. Han resultado ser invaluables después de los recientes terremotos."}
{214}{}{Noticias económicas}
{215}{}{"El tercer milagro económico de México. Seguido de la anexión, México ha sido testigo del auge de la industria manufacturera estadounidense. A pesar de que el medio ambiente empeora, el país se enriquece rápidamente."}
{216}{}{Noticias industriales}
{217}{}{"Se acaba el petróleo del Golfo de Cortés y muchas estaciones petrolíferas están fuera de servicio. Se espera que las restantes sigan funcionando por los siguientes diez años, que extraerán las últimas gotas del oro negro."}
{218}{}{Opiniones expertas}
{219}{}{"¿Se avecina una guerra nuclear en México? Preguntamos a los expertos."}
{220}{}{"Está claro que los Estados Unidos no amenazará a México con armamento nuclear. Pero, México tiene otros vecinos que están ansiosos de capturar sus recursos y territorio marítimo."}
{221}{}{"Tras la anexión, Estados Unidos ha instalado numerosas fábricas e instalaciones estratégicas en México. Es evidente que los enemigos de EE.UU buscarían eliminarlas en caso de una guerra. Y esto no sólo nos afectaría a nosotros, sino también al pueblo Mexicano."}
{222}{}{Noticias policíacas}
{223}{}{"México está comprando a Estados Unidos equipos blindados ligeros para llevar a cabo operaciones especiales en sus fronteras terrestres."}
{224}{}{Reportajes criminales}
{225}{}{"Un grupo prohibido anteriormente, simpatizante de China y la Unión Soviética, ha sido eliminado en Ciudad de México. Se reportan bajas entre la población civil."}
{226}{}{Calendario de eventos}
{227}{}{"¡No te lo pierdas! ¡Este sábado disfrute de un espectáculo inolvidable por el legendario mariachi, José Solís!"}

