{100}{}{No es posible cerrar estas puertas.}
{101}{}{La línea del monorriel no tiene corriente. El tranvía no irá a ningún lado.}
{102}{}{El tranvía no se mueve. Algo debe estar roto.}
{103}{}{Después de casi cien años, ¡el monorriel funciona de nuevo!}
{104}{}{El monorriel ya funciona.}

{110}{}{"Bienvenido a la red del Sistema de Tránsito Rápido Metropolitano de San Diego. Por favor, tome asiento y espere al cierre de puertas."}
{111}{}{[Bájate del tranvía]}
{112}{}{[Próxima estación: San Isidro]}
{113}{}{[Próxima estación: Estación central de Chula Vista]}
{114}{}{[Próxima estación: Estación Broadway]}
{115}{}{[Próxima estación: Estación Pueblo Viejo]}
