{100}{}{Ves a Stanley.}
{101}{}{Ves a un necrófago terriblemente huesudo con un overol sucio y desgastado. Tiene clavado un pedazo de acero corrugado en la cabeza.}
{102}{}{Hola, paliducho. Ya no tienes cara de fantasma.}

{200}{}{¡No, no me lleves, no quiero morir! ¡Noooo!}
{201}{}{¿De qué hablas?}
{202}{}{¿¡Qué demonios estás diciendo!?}
{203}{}{Espera, ¿¡eres un humano!? Ay, pensé que eras un fantasma. ¿Por qué me asustas así?}
{204}{}{Te podría preguntar lo mismo. ¿Por qué andas caminando en la oscuridad? Con ojos brillantes, además.}
{205}{}{Lo siento, pero estaba muy asustado. Es fácil sentirse sólo en una estación así. ¿Sabes? Habían rumores de un tren fantasma que se llevaba almas al infierno. Es tonto creer en algo así, por supuesto. Porque ya estamos en el infierno.}
{206}{}{Lo siento, no pensé que encontraría a alguien aquí.}
{1206}{}{Lo siento, no pensé que encontraría a alguien aquí.}
{207}{}{Hace años las estaciones estaban repletas de gente, y ahora están desiertas. Quizás era cierto y el tren fantasma ya se llevó a todos al infierno. Si no me crees, abre los ojos y mira a tu alrededor, ya estamos en el infierno.}
{208}{}{Bueno, ¿qué estás haciendo aquí?}
{209}{}{Mis camaradas me pidieron que prepare la Línea Azul para su funcionamiento. Antes trabajaba en el metro, así que puedo hacer algunas cosas, pero no todo.}
{210}{}{¿Qué necesita para funcionar?}
{211}{}{Primero, en este momento no tenemos electricidad. Y parece que el único lugar del que viene es la planta eléctrica de Bonita, pero está bien protegida desde la guerra. No sólo es necesario arreglar la estación, sino también activar la subestación del monorriel en el Parque Balboa.}
{212}{}{¿Y lo otro?}
{213}{}{Segundo, hay que reparar la línea del monorriel. Los Señores Mañosos pueden hacer eso por nosotros al ocuparse de la electricidad, sólo deben desmantelar algunas líneas viejas. Pero primero tenemos que arreglar la automatización del tranvía, y eso no es posible sin un especialista en electrónicos. La pieza está en el cuarto de control, quizás el técnico en San Isidro lo pueda arreglar, o hasta incluso tú, pero es pesada. ¿Me ayudarás?}
{214}{}{Claro, de esa forma también puedo usar el monorriel.}
{215}{}{Haré lo que sea para hacerles la vida más fácil.}
{216}{}{¡Genial! Si me ayudas te daré parte del pago que me prometió la administración de la ciudad.}
{217}{}{Está bien, nos vemos luego.}
{218}{}{Antes de eso, tengo unas preguntas que hacerte.}

{220}{}{¿Qué pasa, paliducho?}
{221}{}{¿Qué estás mirando, paliducho?}
{1221}{}{¿Qué estás mirando, paliducha?}
{222}{}{¡Vaya, es mi amigo, el paliducho! ¿Cómo andas?}
{1222}{}{¡Vaya, es mi amiga, la paliducha! ¿Cómo andas?}
{223}{}{Adiós.}

{230}{}{¿Qué es un monorriel?}
{231}{}{¿No sabes? ¡Debes estar bromeando! Antes, estas líneas eran recorridas por trenes. Y era genial. Si me ayudas a arreglarla, podrás verlo con tus propios ojos.}
{232}{}{Ya veo.}
{233}{}{¿Qué se necesita para arreglar el monorriel?}
{234}{}{Primero, se necesita dirigir la corriente en la subestación de la Línea Azul, está en algún lado del Parque Balboa. Luego hay que reparar la pieza en el cuarto de control. Si no puedes hacerlo tú, llévasela al técnico en San Isidro.}
{235}{}{Entiendo.}
{236}{}{¿No te molesta eso que tienes en la cabeza?}
{237}{}{¿Qué cosa? Ah, te refieres al acero. Lo he tenido en la cabeza unos cien años. No es nada malo, ya me acostumbré, pero es mejor no sacarlo.}
{238}{}{Está bien, como tú digas.}
{239}{}{¡Es un milagro! Siendo honesto, pensé que nada la haría funcionar. Es tan sorprendente que me cuesta creerlo. Me ayudas a recobrar la confianza en las personas. Quizás aún haya esperanza para ti.}
{240}{}{Eh, bueno.}
{241}{}{No hice esto por ti.}
{242}{}{Supongo que debo repartirme las chapas contigo, te mereces 1,000. Gracias... amigo mío.}
{1242}{}{Supongo que debo repartirme las chapas contigo, te mereces 1,000. Gracias... amiga mía.}
{243}{}{Siempre serás bienvenido aquí, amigo mío.}
{244}{}{Supongo que debo repartirme las chapas contigo, te mereces 1,000. Gracias... compañero.}
{245}{}{Siempre serás bienvenido aquí, compañero.}
{246}{}{Supongo que debo repartirme las chapas contigo, te mereces 500. Gracias... compañero.}
{247}{}{¿Eso es todo? Ya no somos "compañeros".}

