{110}{}{Este equipo no está funcionando.}
{111}{}{Esta radio está funcionando a su máxima capacidad.}
{112}{}{Has remplazado las partes rotas. La estación de radio ya funciona.}
{113}{}{Esta patética chatarra no puede reemplazar las partes rotas.}
{114}{}{La estación de radio no funciona.}
{115}{}{No tienes idea de cuántos problemas nos salvará la radio. Gracias.}
{116}{}{Gomer ser más grande que tú y tener menos cerebros. Gomer nunca podría arreglar esto.}
