{110}{}{Ves unos torpedos nucleares.}
{111}{}{Esto debe ser un explosivo extremadamente poderoso.}
{112}{}{Estos son unos torpedos nucleares. Están listos para la acción.}
{113}{}{Es hora de salir de aquí...}
{114}{}{¡Gomer amar explosiones grandes!}

{123}{}{Has activado el temporizador del torpedo.}
{124}{}{Has cancelado el temporizador del torpedo.}

{150}{}{Tiempo restante para la explosión: }
{151}{}{ segundos.}
