{110}{}{Esta máquina expendedora entrega objetos al insertar dinero.}
{111}{}{Esta máquina expendedora ya ha sido abierta.}
{112}{}{}
{113}{}{La cerradura es demasiado complicada para ti.}
{114}{}{Has colocado una ganzúa. Ahora te será más fácil forzar la cerradura.}
{115}{}{No es posible colocar más ganzúas.}
{116}{}{Este decodificador electrónico no es adecuado para una cerradura mecánica.}
{117}{}{Abriste el contenedor. Es hora de ver que hay adentro.}
{118}{}{Ahora que la máquina está abierta, hacer eso sería inútil.}
{119}{}{Has adquirido: }
{120}{}{La máquina expendedora ya no tiene más existencias.}
{121}{}{ piezas.}
{122}{}{Eres incapaz de traspasar el mecanismo de seguridad de la máquina expendedora.}
