{100}{}{Ves a Alejo.}
{101}{}{Ves a un hombre semidesnudo, lleva un machete y unos ojos llenos de locura.}

{110}{}{¡Muere, rata asquerosa!}
{111}{}{¡Malditas maracas!}
{112}{}{¡Me agarraron! ¡Te digo que me secuestraron!}
{113}{}{¡Alex! ¡Times! ¡Washington!}
{114}{}{¡Seguirás mis órdenes al pie de la letra!}
{115}{}{Esto le enviará un mensaje claro a esos bastardos.}
{116}{}{Yo vine hasta acá, buscaba comida, no molestaba a nadie.}
{117}{}{¡Me vigilan, siempre me andan vigilando!}
{118}{}{¿Qué mexicano me robó el carro?}
{119}{}{¡Revueltas y caos! ¡Revueltas y caos!}
{120}{}{¡Te reventaré a granadas!}
{121}{}{¡No! ¡Puta madre!}
{122}{}{¡Hay monos por todos lados! ¡Hay uno acá!}
{123}{}{¡Malditos hijos de puta!}
{124}{}{¡Ooooh!}
{125}{}{Me encantan los animales, de verdad.}
