{100}{}{Ves a un bandido.}
{101}{}{Ves a otro bandido. Seguramente no es el último que verás.}
{102}{}{El bandido no está dispuesto a dialogar.}
{103}{}{Es Agustín Chacón.}

{110}{}{«¡Poca madre! ¡La Hermandad nos chingo en Caborca!»}
{111}{}{«La Hermandad es rete harto de fuerte.»}
{112}{}{«Pero los superamos en número. ¡Podemos ir en bola y partirles su madre!»}
{113}{}{«Chihuahua, y si no lo hacemos nosotros, ¿entonces quién?»}
{114}{}{«Esta tierra ha sido de mis paisanos y mía durante muchas generaciones.»}
{115}{}{«¡Y ahora esos gringos vienen y nos imponen sus mamadas!»}
{116}{}{«¡Son unos malditos bastardos mal nacidos!»}
{117}{}{«¡Tenemos que mandarlos a la chingada para que dejen nuestras tierras!»}
{118}{}{«¡Esta es nuestra tierra, nuestros jacales!»}
{119}{}{«¡Son unos abusivos invasores de su chingada madre!»}
{120}{}{«Y apenas intenten pisar nuestro territorio...»}
{121}{}{«¡Sólo nosotros tenemos derecho a estas tierras!}
{122}{}{«¡Aumenten las patrullas! La Hermandad no puede chingarnos éste lugar.»}
{123}{}{«Poca madre, ¿Qué hicimos mal? Tuvo que haber sido esa chingada caravana...»}

{130}{}{¡Son unos malditos bastardos mal nacidos!}
{131}{}{¡Y ahora esos gringos vienen y nos imponen sus mamadas!}
{132}{}{¡Chingada madre!}
{133}{}{¡Esta es nuestra tierra!}
{134}{}{¡Valimos madre!}
{135}{}{¡Dejen de papalotear y aumenten las patrullas!}
