{100}{}{Ves a un patrullero.}
{101}{}{Ves a un guerrero de la Hermandad del Acero.}

{110}{}{¿Qué te trae por aquí?}
{111}{}{El pueblo más cercano está allá, al noreste.}
{112}{}{Estos lares están bajo la protección de la Hermandad.}
{113}{}{No te haremos daño, mientras sigas nuestras reglas.}

{120}{}{Saludos, hermano.}
{121}{}{¿Cómo te va, hermano?}
{122}{}{¿Qué está pasando en el yermo, hermano?}
{123}{}{Lo siento, pero no podemos escoltarte a la base.}

{1120}{}{Saludos, hermana.}
{1121}{}{¿Cómo estás, hermana?}
{1122}{}{¿Qué está pasando en el yermo, hermana?}
{1123}{}{Lo siento, pero no podemos escoltarte a la base.}
