{100}{}{Ves a un granjero.}
{101}{}{Ves a un granjero con las manos cubiertas por una capa de tierra, lleva una mochila pesada.}
{102}{}{Oye, guarda el arma, por favor.}

{200}{}{¡Hola, compadre! ¿Te ayudo en algo?}  
{1200}{}{¡Hola, señorita! ¿La ayudo en algo?}  
{201}{}{No, gracias. Adiós.}
{202}{}{¿A dónde vas?}
{203}{}{Iré a vender mis productos al pueblo. Siempre me compran todo.}  
{204}{}{¿Qué vendes?}
{205}{}{Lo que crezca en la granja, intercambio lo que sobra por cosas que necesite.}  
{206}{}{¿Puedo comprarte algo?}
{207}{}{Claro, así me ahorro el viaje.}  
{208}{}{Quizás en otro momento.}
{209}{}{Déjame ver lo que tienes.}

{210}{}{Bueno, tengo que irme.}  
{211}{}{Adiós.}
{212}{}{Hmm... ¿te conozco...? ¡Espera! ¿Los rangers te están buscando, cierto? No sé qué habrás hecho, pero no me hagas nada, por favor.}  
{213}{}{Adiós.}
{214}{}{No le digas a nadie que me viste...}
{215}{}{¿te conozco...? ¡Espera! ¿Los rangers te están buscando, cierto? No te preocupes, no soy un soplón. Igual me andan buscando.}  
{216}{}{Perfecto. ¿A dónde vas?}
