{100}{}{Ves a un pescador.}
{101}{}{Ves a un pescador primitivo.}

{110}{}{¿Pescado mucho? Siempre cazar en grupo, pero ahora ser más difícil, ¿eh?}
{111}{}{No entender mucho tus palabras, pero tu forastero, ¿dónde? ¿De lejos?}
{112}{}{¡No! ¡Agua! Tú no pelear, ¿bien? No sangre, querer agua.}
{113}{}{¡No, no! No dolor. ¿Solo pescado, bueno?}
{114}{}{Peligro aquí... es vida, pescado bueno.}
{115}{}{¿Tú igual cazar? Aquí pez ser bueno, pero vapo... ser peligroso.}
{116}{}{Tú hablar, yo reponer. Pero no confiar fácil, forastero. Muchos venir, muchos pelear.}
{117}{}{Tú, yo... no guerra. ¿Compartir, sí? Sobrevivir juntos.}
{118}{}{Aquí... todos luchar por vivir. Tú, yo... Haiga ser inteligente, no guerra.}
{119}{}{Tú, yo... misma gente, otra tribu, pero mismo. Pescado ser bueno.}
