{100}{}{Ves a un chatarrero.}
{101}{}{Ves a un chatarrero con la ropa sucia, está encorvado bajo el peso de su mochila llena de basura.}
{102}{}{Oye, ¿qué te pasa? No te estoy apuntando o algo así, ¿verdad?}

{200}{}{Mantén tus manos donde pueda verlas, amiguito. No sabes cuántos saqueadores he visto estos días. ¿Qué quieres?}
{201}{}{¿Acaso quieres hacer un trato?}
{202}{}{No, solo necesito pasar por aquí.}
{203}{}{He estado hurgando en estas ruinas para ver si encuentro algo útil. Si necesitas algo, podríamos hacer un trato. Mira lo que tengo.}
{204}{}{Está bien, quizás nos veamos de nuevo.}
{205}{}{Creo que te he visto en algún lado... ¡Espera! ¿A ti te están buscando en Fénix, verdad? No te preocupes, no me molesta, a mí también me están buscando.}
{206}{}{Eso está bien. ¿Qué estás haciendo en un lugar como este?}

{210}{}{¿Necesitas algo? Tengo mucho que vender.}
{211}{}{Tengo que irme.}
