{100}{}{Ves a un cazador.}
{101}{}{Ves a un hombre de barba frondosa. Parece estar cansado de cazar.}
{102}{}{Amigo, ¿qué tal si enfundamos las armas?}

{200}{}{Saludos, viajero. Es raro ver a otro humano por aquí. Por un momento pensé que eras otro animal más.}
{1200}{}{Saludos, viajera. Es raro ver a otro humano por aquí. Por un momento pensé que eras otro animal más.}
{201}{}{Eres un cazador, ¿verdad?}
{202}{}{Así es. No hay mucho que cazar por estos lares, sólo lo suficiente como para alimentarme y vender algo en la ciudad de vez en cuando.}
{203}{}{¿De qué ciudad hablas?}
{204}{}{¿No conoces Flagstaff? Es una colonia, está cerca de una mina vieja. La fundaron hace unos años, y ha crecido mucho. Toma la carretera principal, es imposible no verla.}
{205}{}{Gracias. ¿Has cazado algo?}
{206}{}{Necesito abastecerme, ¿tienes algo que vender?}
{207}{}{Acabo de ahumar algo de carne, podría intercambiarla por algo útil.}
{208}{}{Quizás en otra ocasión.}
{209}{}{Me vendría bien reabastecerme.}
{210}{}{Bueno, debería seguir con mi camino antes de que se pudra la carne.}
{211}{}{Ten cuidado allá afuera.}
{212}{}{Oye, ¿sabías que te están buscando en Flagstaff? Parecían estar enojados contigo. Ten cuidado con ellos; no quiero meterme, pero si me ven hablándote, será difícil vender en la ciudad.}
{213}{}{Espera, me gustaría comprar un poco de carne seca.}
