{110}{}{La caja está tachonada con clavos. La única forma de abrirla es la fuerza bruta.}
{111}{}{Careces de la fuerza para usar la herramienta de forma eficiente.}
{112}{}{Conseguiste abrir la caja a la fuerza.}

{120}{}{Abriste uno de los lados, un poco. ¡Sigue así!}
{121}{}{¡Un poco más, ya casi!}
{122}{}{¡Sigue! La caja está a punto de abrirse.}
{123}{}{Casi... ¡Vamos, dale todo lo que tengas!}
{124}{}{Aún falta, sigue esforzándote.}
{125}{}{¡Ya casi! ¡Último empujón!}
