#For containers
{100}{}{¡Oye, deja eso ahí!}
{101}{}{Haré que te arrepientas si vuelves a tocar eso.}
{102}{}{¡Eso es mío! ¡Quita las manos!}
{103}{}{No sé que estás buscando, pero no está ahí. ¿Entendido?}
{104}{}{Vuelve a tocarlo y tendrás serios problemas.}
{105}{}{Quita tus cochinas manos de ahí.}
{106}{}{Déjame adivinar, ¿estás buscando tus llaves?}
{107}{}{¡Oye, sal de ahí!}
{108}{}{Es de mala educación llevarte lo que no es tuyo.}

{109}{robots}{*Muéstreme su permiso, por favor.*}

#For doors
{110}{}{No puedes entrar ahí.}
{111}{}{¡Oye! ¿¡Qué crees que haces!?}
{112}{}{Déjame adivinar, ¿se te quedaron las llaves?}
{113}{}{¡Sáquese de ahí!}
{114}{}{Si lo intentas, te arrepentirás.}
{115}{}{Ni siquiera lo pienses.}
{116}{}{¿Por qué crees que está cerrada?}
{117}{}{¡Sale de ahí!}
{118}{}{Deja la puerta tranquila o te corto las manos!}

{119}{robots}{*Muéstreme su permiso, por favor.*}

#Replicas during an attack on GG
{120}{people}{¡Te lo advertí!}
{121}{robots}{¡Intruso detectado!}

{122}{}{El dueño de esto no quiere que lo toques.}
{123}{}{El dueño no tiene ninguna intención de dejarte pasar.}
{124}{}{Hay un robot resguardando el almacén.}
{125}{}{El robot resguarda este lugar.}

{126}{}{ no te permitirá tocar esto.}
{127}{}{ no te permitira tocar esto.}
{128}{}{ no tiene ninguna intención de dejarte pasar.}
{129}{}{ no tiene ninguna intención de dejarte pasar.}

{130}{}{¡Sáquese de ahí, pinche gringo!}
{131}{}{«Por favor, no toques eso.»}







