{101}{}{Esta máquina es perfecta para elaborar alcohol.}
{102}{}{Esta máquina podría ser perfecta para elaborar alcohol, pero le falta la materia prima.}
{103}{}{Estás en medio de una pelea, no deberías hacer esto.}

{110}{}{Necesitas colocar la materia prima en la máquina antes de hacer tequila.}
{111}{}{No es tan fácil como parece. Primero, tienes que aprender la receta.}
{112}{}{Has colocado la materia en la máquina. Es hora de preparar el tequila.}
{113}{}{Ya rellenaste la máquina, no puedes agregarle más.}
{114}{}{Vierte la materia prima directamente en el recipiente de la máquina.}
{115}{}{Has preparado el tequila, sólo falta embotellarlo.}
{116}{}{Hay suficiente tequila para }
{117}{}{ botellas.}
{118}{}{Todavía falta algo...}

{120}{}{La máquina está en buen estado y no necesita mantenimiento.}
{121}{}{Colocar todas las botellas en su lugar requiere mucha astucia. ¿Cómo es posible que sólo tú lo hayas conseguido?}
{122}{}{La máquina ha sido destruida. Los borrachos del área acaban de perderlo todo.}
{123}{}{Oh-oh...}
