{108}{}{ Estado actual }
{109}{}{%.}
{110}{}{ bloquea tu camino. Con una almádena o algunos explosivos, podrías derribar el obstáculo.}
{111}{}{No tienes la fuerza necesaria. Intenta usar algo más fuerte.}
{112}{}{Quitas la obstrucción del camino usando la fuerza bruta.}
{113}{}{La explosión destrozó el obstáculo y solo dejó pequeños pedazos.}
{114}{}{Parece que necesitarás armas más pesadas.}
{115}{}{El impacto destrozó el obstáculo y solo dejó pequeños pedazos.}
{116}{}{Obstáculo }
{117}{}{% destruido.}
{118}{}{-}
{119}{}{%}
{120}{}{Solo la fuerza bruta te ayudará con esto.}
{121}{}{No puedes usar el encendedor para poner esto en llamas.}
{122}{}{Busca una herramienta más poderosa.}
{123}{}{Claramente, la construcción no es lo tuyo.}
