{110}{}{La máquina dispensa bebidas, sólo por dinero. A no ser que intentes forzar la cerradura.}
{111}{}{Ya forzaste la cerradura de la máquina.}
{112}{}{}
{113}{}{La cerradura es demasiado complicada para ti.}
{114}{}{Colocaste una ganzúa, ahora será más fácil forzar la cerradura.}
{115}{}{La cerradura ya tiene una ganzúa colocada.}
{116}{}{El decodificador electrónico no te ayudará con una cerradura mecánica.}
{117}{}{Has abierto la máquina, es hora de ver qué hay dentro.}
{118}{}{La máquina ya está abierta, eso no tendría sentido.}
{119}{}{Recibiste una botella de Nuka-Cola, caliente y sin gas.}
{120}{}{La máquina está agotada de Nuka-Cola.}
{121}{}{}
{122}{}{Eres incapaz de forzar el mecanismo de seguridad del mecanismo.}
