#General
{110}{}{Para cerrar el candado de la puerta, la puerta en sí debe estar cerrada.}
{111}{}{Cerraste la puerta.}
{112}{}{Abriste la puerta.}
{113}{}{Es demasiado complicado hacer eso en medio de una pelea.}
{114}{}{La puerta está cerrada.}
{115}{}{Ya no queda rastro de la puerta.}
{116}{}{La explosión no dejo ni un sólo rasguño en la puerta.}
{117}{}{Para colocar el pestillo a la puerta, deberías cerrarla primero.}

#Attempt to open
{120}{}{Descubres que la }
{121}{}{ tiene una trampa peligrosa.}
{122}{}{¡Descubres que la }
{123}{}{ tiene una trampa!}
{124}{}{ tenía una trampa.}

#Skills
{130}{}{Esta habilidad será inútil aquí.}
{131}{}{ fue cerrada.}
{132}{}{ tiene una cerradura con una dificultad de }
{133}{}{.}
{134}{}{ Es una buena idea revisar si posee trampas.}
{135}{}{No fuiste capaz de abrir la cerradura. Inténtalo de nuevo.}
{136}{}{}
{137}{}{No fuiste capaz de abrir la cerradura.}
{138}{}{Con habilidades como las tuyas, no aprendes nada útil.}
{139}{}{La cerradura está más allá de tus habilidades.}

#Broken lock
{140}{}{La cerradura se atascó. Para siempre.}
{141}{}{La cerradura ya se atascó.}
{142}{}{Eso no tiene sentido, la cerradura ya está abierta.}
{143}{}{No es posible quebrar esta cerradura con la fuerza bruta.}
{144}{}{Necesitarás *mucha* fuerza para quebrar la cerradura.}
{145}{}{Quebraste la cerradura usando la fuerza bruta. Nadie será capaz de cerrarla de nuevo.}
{148}{}{ tenía una trampa.}
{149}{}{Las armas deberían usarse en el modo combate.}

#Traps
{150}{}{Eres incapaz de detectar la trampa.}
{151}{}{}
{152}{}{}
{153}{}{Has descubierto una trampa, pero no pudiste desarmarla.}
{154}{}{¡Eso fue un error! Puede que la siguiente vez sea la última.}
{155}{}{Has desarmado con éxito la trampa primitiva.}
{156}{}{Has desarmado con éxito la trampa con un casquillo del calibre 12.}
{157}{}{Has desarmado con éxito la trampa, usaba una granada de fragmentación.}
{158}{}{Has desarmado con éxito la trampa electrónica.}
{159}{}{Has deshabilitado la alarma con éxito.}

#Items
{160}{}{Eso no te ayudará, la cerradura está rota.}
{161}{}{Has colocado una ganzúa. Ahora será más fácil forzar la cerradura.}
{162}{}{La cerradura ya tiene una ganzúa.}
{163}{}{El decodificador electrónico no te ayudará con una cerradura mecánica.}
{164}{}{Esta cerradura necesita una llave distinta.}
{165}{}{La llave no funcionó. Es poco probable que encuentres una llave para esta cerradura.}
{166}{}{La explosión voló a la puerta por los aires.}
{167}{}{La ganzúa no te ayudará con una cerradura electrónica.}
{168}{}{Ya conectaste un decodificador.}
{169}{}{Conectaste el decodificador, esto hará más fácil piratear el ordenador.}
{170}{}{Una pala no te ayudará con esto.}
{171}{}{La llave no pertenece a esta cerradura.}
