#Detailed description
{101}{}{Ves una máquina tragaperras.}
{102}{}{Ves una máquina extraña.}
{103}{}{Ves una máquina tragaperras.}
{104}{}{Ves una máquina tragaperras bastante limpia.}
{105}{}{Ves una máquina tragaperras muy brillante.}

#Interaction, use of skills and items
{110}{}{Abrir la máquina no servirá de nada.}
{111}{}{Es una máquina complicada que hace ruido y escupe fichas. En la Villa no hay nada parecido.}
{112}{}{La máquina no necesita mantenimiento.}
{113}{}{Ponerte a jugar en medio de una pelea sería una pesadilla.}
{114}{}{Parece que esta máquina necesita un tipo especial de ficha.}
{115}{}{A la máquina se le acabaron las fichas. Tendrás que volver otro día.}
{116}{}{No tienes la menor idea de cómo hacer funcionar esta cosa.}
{117}{}{Inserta una ficha para jugar.}
{118}{}{Apuestas: }
{119}{}{.}
{120}{}{No podrás apostar más, a la máquina se le acabaron las fichas.}
{121}{}{No puedes apostar más de 20 fichas.}
{122}{}{La máquina no aceptará esas fichas.}
{123}{}{}
{124}{}{}

#Phrases above the GG when you lose and have no chips in your pocket
{125}{}{¡Esto es una estafa!}
{126}{}{Esa era mi última ficha...}
{127}{}{¿Y cómo voy a ganar más fichas?}
{128}{}{¡Mierda! ¡La máquina me quitó la última ficha que tenía!}
{129}{}{¡Chingada madre! ¡Ya no tengo más fichas!}

#Replicas above the machine
{130}{}{*Ding*}
{131}{}{*Ding*}
{132}{}{*Bz-z-z*}
{133}{}{*Trrrrr*}
{134}{}{*Juega conmigo*}
{135}{}{*Hola, lindura*}
{136}{}{*Una vez que me toques, no me soltarás*}
{137}{}{*Clink*}
{138}{}{*Ding ding*}
{139}{}{*Ding ding ding ding*}
{140}{}{}
{141}{}{}
{142}{}{}
{143}{}{}
{144}{}{}
{145}{}{}
{146}{}{}
{147}{}{}
{148}{}{}
{149}{}{}

#Cues during the game
{150}{}{Perdiste.}
{151}{}{Perdiste. Aguántate.}
{152}{}{Has perdido tu apuesta.}
{153}{}{Parece que la máquina se burla de ti. Perdiste.}
{154}{}{Has perdido. Este no es tu día.}

{155}{}{Ganaste }
{156}{}{ fichas.}
{157}{}{ fichas.}
{158}{}{ fichas. ¡Qué buena suerte!}
{159}{}{¡PREMIO!}

#Names of reels
{160}{}{URANIO}
{161}{}{PLUTONIO}
{162}{}{RADIO}
{163}{}{POLONIO}
{164}{}{RADON}
{165}{}{BERILIO}
{166}{}{MERCURIO}
{167}{}{TELURIO}
{168}{}{TORIO}
{169}{}{PLOMO}

{170}{}{ - }
{171}{}{ÁTOMO}
{172}{}{BOMBA}
{173}{}{NUBE}
{174}{}{VAQUERO}
{175}{}{SIETE}
{176}{}{CAÑON}
{177}{}{COSTA}
{178}{}{}
{179}{}{}
