{110}{}{Necesitas habilidad para usar la trampa.}
{111}{}{¡Rico! Las iguanas fueron muy lentas, y pronto serán una buena cena.}
{112}{}{Con habilidades como las tuyas, la trampa es inútil.}
{113}{}{Ya no queda carnada, la trampa es inútil.}
{114}{}{No es una buena idea colocar dos trampas en el mismo sitio.}
{115}{}{Has colocado la trampa con éxito.}
{116}{}{Buena idea, pero no sabes cómo hacer eso.}
