{110}{}{El emisor está dañado y no funciona. No será posible repararlo aquí.}
{111}{}{Esa habilidad no te ayudará con esto.}
{112}{}{El emisor fue resintonizado a otra frecuencia.}
{113}{}{Te cuesta entender el sistema del emisor.}
{114}{}{Se activó el campo de fuerza.}
{115}{}{Se desactivó el campo de fuerza.}
{116}{}{Es demasiado difícil hacer esto durante el combate.}
{117}{}{Conectaste el decodificador. Será más fácil piratear el sistema.}
{118}{}{No hay ningún lado para conectar el segundo decodificador.}
{119}{}{Eres incapaz de reconfigurar el emisor.}
