{110}{}{ bloquea tu camino. Con la fuerza suficiente o unos explosivos, podrías despejar el camino.}
{111}{}{No tienes la fuerza necesaria para despejar una montaña de rocas.}
{112}{}{Despejas el camino usando la fuerza bruta.}
{113}{}{La explosión manda volando las rocas a todos lados.}
{114}{}{Parece que necesitarás armas más pesadas.}
{115}{}{No puedes cavar en medio de una pelea.}
{116}{}{Necesitas equipamiento especial para ésto.}
