{110}{}{Aquí hay componentes para varios tipos de munición. Si tienes la habilidad adecuada, podrías fabricar algo útil.}
{111}{}{Aquí no queda nada más que basura.}
{112}{}{Con habilidades como las tuyas, solo vas a arruinar los materiales.}
{113}{}{La munición fabricada se encuentra en tu inventario.}
{114}{}{Has fabricado: }
{115}{}{.}
{116}{}{Fabricaste algo de combustible.}

{200}{}{Aquí hay componentes para varios tipos de munición. Escoge sabiamente, pues los suministros de plomo y pólvora son limitados.}
{201}{}{Ahora no.}
{202}{}{Otras.}
{203}{}{Regresar.}
{204}{}{.}
{205}{}{Hay suficientes componentes para }
{206}{}{ cartuchos (basado en tu habilidad de Reparar actual)}
{207}{}{Justo lo que necesitabas. ¡Manos a la obra!}
{208}{}{Pon esto de lado.}
