#
#
#
#
#
{0}{}{Preferenze di Gioco}
{1}{}{Impostazioni Schermo}

{50}{}{Impostazioni Schermo}
{51}{}{Personalizzato}
{52}{}{Larghezza}
{53}{}{Altezza}
{54}{}{Fatto}
{55}{}{Annulla}
{56}{}{Fallout deve essere riavviato per applicare le impostazioni.}
{57}{}{Vuoi riavviare ora Fallout?}
{58}{}{Vero}
{59}{}{Falso}
{60}{}{}

{100}{}{Alta-Risoluzione}
{101}{}{RISOLUZIONE}
{102}{}{Colori}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Cambia immagine inferiore}
{107}{}{Inverti Lista}
{108}{}{Finestra}
{109}{}{Imposta tasto Blocco scorrimento}
{110}{}{Ingrandisci X2}
{111}{}{Frequenza di Aggiornamento}

{130}{}{Tasto Window}
{131}{}{Seleziona}
{132}{}{Nome}

{140}{}{Modalita' Grafica:}
{141}{}{Basica}
{142}{}{Modalita' Sfall DirectX 9:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Processione Vertex Hardware:}
{149}{}{Shader Versione 2.0:}

{150}{}{Scala Pannello}
{151}{}{Nessuno}
{152}{}{Riempi}
{153}{}{Riempi}

{154}{}{Filmati}
{155}{}{Schermata Iniziale}
{156}{}{Aiuto}
{157}{}{Morte}
{158}{}{Slides Finali}
{159}{}{Menu Principale}

{200}{}{Sfall}
{201}{}{SCALA ALLA : RIS.}
{202}{}{MOD. DX-9}
{203}{}{Spento}
{204}{}{Pieno Schermo}
{205}{}{Finestra}
{206}{}{GPU Blitting}
{207}{}{Questa impostazioni non ha effetto quando si e' in modalita' Base.}

{250}{}{Ignora Limite di Scorrimento}
{253}{}{Distanza Percorribile}
{254}{}{Normale}
{255}{}{Max}
{256}{}{Abilita Nebbia di Guerra}
{257}{}{Visibilita' nebbia}
{258}{}{Coperto}
{259}{}{Scoperto}

{300}{}{PREMI UN TASTO o ESC per annullare.}

{500}{}{Impostazioni Hi-Res.}
{501}{}{Imposta la Risoluzione dello schermo, Colore e frequenza di aggiornamento per lo Schermo Intero.}
{502}{}{Imposta il Colore a Schermo Intero.}
{503}{}{Imposta la Frequenza di Aggiornamento. Imposta '0' per usare le impostazioni predefinite del driver.}
{504}{}{Personalizza la Larghezza a Pieno Schermo cliccando nella casella sottostante.}
{505}{}{Personalizza la Altezza a Pieno Schermo cliccando nella casella sottostante.}
{506}{}{Abilita o Disabilita la modalita' a Finestra.}
{507}{}{In modalita' Finestra, questo e' il tasto che dovrai tenere premuto per scorrere le schermante del Gioco e della Mappa.}
{508}{}{Press the red button to select a different key. Or click the number box to edit the Windows Virtual key code.}
{509}{}{The name of the currently selected key.}
{510}{}{Enable X2 scaling. This will also up the min res to 1280x960. With Window mode requiring more space for its frame.}
{511}{}{Enable or Disable Fog Of War. For best results this should be enabled before entering a map for the first time.}
{512}{}{Adjust the light level and the Mouse 'look at' visibility of floors, walls and scenery under the fog.}
{513}{}{Floors, walls and scenery will always be visible and Mouse "look at" will function normally.}
{514}{}{Floors, walls and scenery will be darkened and unresponsive to Mouse "look at" until discovered.}
{515}{}{When enabled, scrolling away from the Player Character is unlimited. This works well if Fog Of War enabled.}
{516}{}{Increase the number of search nodes to extend the path finding distance. 20 levels in 2000 node increments.}
{517}{}{2000 path search nodes (original value). Note: Each level requires an additional 156.25 KB of memory.}
{518}{}{40 000 nodi di ricerca. Nota: richiede 3200000 bytes (3125 KB) di memoria.}
{519}{}{Imposta come certe schermate si visualizzino.}
{520}{}{Dimensione originale.}
{521}{}{Allungata per riempire lo schermo mantenendo le proporzioni.}
{522}{}{Allungata per riempire lo schermo. Nota: uno spazio sarà visibile se i sottotitoli sono abilitati.}
{523}{}{Clicca sotto per scorrere le interfacce di gioco disponibili.}
{524}{}{Applica le modifiche ed Esci.}
{525}{}{Esci senza salvare.}


