{100}{}{You see a missionary.}
{101}{}{You see one of the soldiers. He is in full battle gear.}

{110}{}{You should talk to the commander.}
{111}{}{You're lucky you're not from a tribe of herders.}
{112}{}{The commander leads us. So talk to him.}
{113}{}{Want to join? Well, I'm not gonna share my rations.}
{114}{}{I don't know about the rest of you, but I'm gonna *survive* this night.}
{115}{}{Looks like we're stuck here for a while yet.}

{150}{}{(Humming an old song while looking enviously at your rifle)}
{151}{}{~ Carabinas Treinta Treinta ~}
{152}{}{~ Que los rebeldes portaban ~}
{153}{}{~ Y decían los federales ~}
{154}{}{~ Que con ellas no mataban ~}
{155}{}{~ Con mi 30-30 voy a marchar ~}
{156}{}{~ A engrosar las filas de la rebelión ~}
{157}{}{~ Si mi sangre piden, mi sangre les doy ~}
{158}{}{~ Por los habitantes de nuestra nación ~}
{159}{}{~}

{160}{}{Damn, it's finally over.}
{161}{}{We did it! Hell yeah!}
{162}{}{We handled these natives like they were nothing.}
{163}{}{Those savages won't dare mess with us now.}
{164}{}{The Rangers are hightailing it west, scared shitless.}
{165}{}{Damn right! We're the kings around here.}

{170}{}{Fucking savages!}
{171}{}{I don't want to crawl back to Phoenix with this shame hanging over me.}
{172}{}{These savages are gonna regret ever crossing us.}
{173}{}{Thank God, we're finally going home.}
{174}{}{If the commander's bailing, then there's no point in us sticking around.}
{175}{}{They told me not to get mixed up in this shit...}

{250}{}{(Humming an old song while looking enviously at your rifle)}
{251}{}{~ «Thirty Thirty Carabine» ~}
{252}{}{~ «That the rebels carried» ~}
{253}{}{~ «And the federals said» ~}
{254}{}{~ «You can't kill with them» ~}
{255}{}{~ «With my 30-30 I will march» ~}
{256}{}{~ «To join the ranks of the rebellion» ~}
{257}{}{~ «If they ask for my blood, I will give it» ~}
{258}{}{~ «For the people of our nation» ~}
{259}{}{~}