{100}{}{You see a computer.}
{101}{}{You see an ancient computer with a Spanish keyboard.}

#Dialogue
{200}{}{«Enter command»}
{201}{}{«End session»}
{202}{}{«Back»}

{210}{}{«Fort quarterly report»}
{211}{}{«Report 2162 for the general headquarters in Monterrey. General Sarabia's detachment entered deserted Hermosillo and organized a temporary base. A week later, the order for permanent quartering came.»}
{212}{}{«Fort in El Paso»}
{213}{}{(This report details supplies and communication codes for another fort in El Paso. It appears there is ongoing combat there.)}
{214}{}{«Goals and objectives»}
{215}{}{«The main objective is to hold the position and expand the territory of the new state.»}
{216}{}{«Assessing the situation»}
{217}{}{«According to the latest data, the primary threat to the fort is the Brotherhood of Steel in the ruins of Puerto Penasco and a settlement of Tinsmiths near pre-war Tucson. The fort is training scouts to study the forces of these potential opponents.»}
{218}{}{«Copy computer data to holodisk»}
{219}{}{«Data archive copied»}
{220}{}{(The data is in Spanish. You do not understand what is written here.)}

{300}{}{Ingresar comando}
{301}{}{Cerrar sesión}
{302}{}{Regresar}

{310}{}{Informe trimestral del fuerte}
{311}{}{(Informe 2162 para el cuartel general en Monterrey. El destacamento del General Sarabia entró en el desierto Hermosillo y organizó una base temporal. Una semana después llegó la orden de acantonamiento permanente.)}
{312}{}{Fuerte en El Paso}
{313}{}{(The data is in Spanish. You do not understand what is written here.)}
{314}{}{Metas y objetivos}
{315}{}{(El objetivo principal es mantener la posición y expandir el territorio del nuevo Estado.)}
{316}{}{Evaluación de la situación}
{317}{}{(Según los últimos datos, la principal amenaza para el fuerte es la Hermandad del Acero en las ruinas de Puerto Peñasco y un asentamiento de Hojalateros cerca de la Tucson pre-guerra. El fuerte está entrenando exploradores para estudiar las fuerzas de estos posibles oponentes.)}
{318}{}{Copiar datos del ordenador al holodisco}
{319}{}{Archivo de datos copiado}
