{100}{}{You see a girl.}
{102}{}{You see a girl of haughty demenour.}
{103}{}{You see Ashley.}

{200}{}{Put your weapon away first, then we'll talk.}
{201}{}{Okay.}
{202}{}{Fuck you!}
{203}{}{I'd better go.}
{204}{}{I still have questions.}

{300}{}{Ah, another uneducated child of the wasteland has arrived. The name's Ashley and I sell magazines and books, though you'd hardly know what they are - wouldn't you? How may I help such mediocrity like yourself?}
{301}{}{How may I help a mediocrity like yourself?}
{302}{}{Show me your goods.}
{303}{}{Shut your mouth, bitch, I'll show you "mediocrity"!}
{304}{}{Where do you get your books from?}
{305}{}{Nice dog you have.}
{306}{}{How curious he is. If I'd tell you, my whole business would collapse and I'd have have to sell *JUNK* instead. I'll just say this, I may or may not have found a good source for my merchandise. So? Are you gonna stand here, mouth agape, or are you gonna buy something?}
{3006}{}{How curious she is. If I'd tell you, my whole business would collapse and I'd have have to sell *JUNK* instead. I'll just say this, I may or may not have found a good source for my merchandise. So? Are you gonna stand here, mouth agape, or are you gonna buy something?}

{307}{}{That's Face, my pride and joy! He's saved me from many a vagrant - so I wouldn't anger him if I were you. (she chuckles sadistically) Unless you wanna to lose a hand. Anything else you need?}

{400}{}{Don't touch anything - until you buy it, of course.}
{401}{}{The more you read the smarter you'll get. I guarantee it!}
{402}{}{He who has never committed follies is not as wise as he thinks.}
{403}{}{It's difficult to judge one's self rather than others.}
{404}{}{If you want to hide a tree, hide it in the forest.}
{405}{}{A little common sense, a little tolerance, maybe a little sense of humor -- and you can get very comfortable in this wasteland.}
{406}{}{The wisest person is the one most annoyed by loss of time.}
{407}{}{No matter how many wise words you read, what good are they if you don't put them into practice?}

{500}{}{Books, books get your books!}
{501}{}{Smart as a molerat? You've come to the right place!}
{502}{}{Buy tw-- THREE books and you *may* pet my dog!}
{503}{}{Show off your reading skills to the local chem dealers!}
{504}{}{Ladies like a cultured man.}
{505}{}{Cooking? Shooting? We got books about anything!}
{506}{}{"Knowledge is priceless"? Not over here!}

{700}{}{The book must be used out of hand to flip through the pages.}
{701}{}{You didn't learn anything new and wasted your time.}
{702}{}{You gain new knowledge about traps and stealth.}
{703}{}{You get new scientific knowledge.}
{704}{}{You have learned a lot of useful information about energy weapons.}
{705}{}{You have become better versed in the effectiveness of trading.}
{706}{}{You have learned a lot about the practical use of firearms.}
{707}{}{You have become better versed in the treatment of various injuries.}
{708}{}{You gain new knowledge about repairs.}
{709}{}{You gain new knowledge about survival in the wasteland.}
{710}{}{You have learned a lot about the practical application of hand-to-hand combat techniques.}
{711}{}{You gain new knowledge about the design and intricacies of locks.}

{800}{}{There is a chest in front of you.}
{801}{}{A sturdy steel merchant's chest.}
{802}{}{The chest remains closed, there is no chance with your current skills.}
{803}{}{You can't open it, you don't even have to try.}
{804}{}{Don't even try it.}
{805}{}{You unlock the chest.}

{998}{}{Sic em', Face!}
